### ISSUE TITLE
Panic when sending bad ilp to /write

### ISSUE THREAD

**Issue by craigching** [influxdata/influxdb#10087]
__System info:__ [Include InfluxDB version, operating system name, and other relevant details]

Problem parsing bad ilp in models.ParsePoints(), I can reproduce this in the code by simply calling:

```
package main

import (
	"fmt"

	"github.com/influxdata/influxdb/models"
)

func main() {
	str := "m f=\"blah\"=123,r 1531703600000000000"

	points, err := models.ParsePoints([]byte(str))

	if err != nil {
		fmt.Println(err)
	}

	fmt.Println(points)
}
```

But sending that same ilp to an influx database causes the same panic.

InfluxDB version: 1.5.2
influx source: 1.6.0

Note that I've tried to simplify the ilp to the most minimal case that reproduces the same problem.  The actual ilp that tripped this problem for us was more realistic.

__Steps to reproduce:__

```
% curl -v "localhost:8086/write?db=metrics" -d'm f="blah"=123,r 1531703600000000000'
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8086 (#0)
> POST /write?db=metrics HTTP/1.1
> Host: localhost:8086
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Length: 36
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 36 out of 36 bytes
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain; charset=utf-8
< Request-Id: 4ae234e5-890a-11e8-a553-000000000000
< X-Content-Type-Options: nosniff
< X-Influxdb-Build: OSS
< X-Influxdb-Version: v1.5.2
< X-Request-Id: 4ae234e5-890a-11e8-a553-000000000000
< Date: Mon, 16 Jul 2018 15:09:53 GMT
< Content-Length: 22
<
Internal Server Error
* Connection #0 to host localhost left intact
```

__Expected behavior:__ [What you expected to happen]

Some sort of error indicating bad ilp

__Actual behavior:__ [What actually happened]

Panic in the server:

```
[httpd] ::1 - - [16/Jul/2018:10:09:53 -0500] "POST /write?db=metrics HTTP/1.1" 200 0 "-" "curl/7.54.0" 4ae234e5-890a-11e8-a553-000000000000 67 [panic:runtime error: slice bounds out of range] goroutine 514425 [running]:
runtime/debug.Stack(0xc423194500, 0xc4237f6700, 0xbecb4b3056c05862)
	/usr/local/Cellar/go/1.10.1/libexec/src/runtime/debug/stack.go:24 +0xa7
github.com/influxdata/influxdb/services/httpd.(*Handler).recovery.func1.1(0xc423194500, 0xc4237f6700, 0xbecb4b3056c05862, 0x11140d72390dc, 0x1ebe700, 0xc4200c3ad0, 0x1a4b980, 0xc42291e540)
	/private/tmp/influxdb-20180414-90429-1lo2iuo/src/github.com/influxdata/influxdb/services/httpd/handler.go:1571 +0xcd
panic(0x188a500, 0x1ea9c00)
	/usr/local/Cellar/go/1.10.1/libexec/src/runtime/panic.go:502 +0x229
github.com/influxdata/influxdb/models.walkFields(0xc422f5e50f, 0x1, 0x239, 0xc42405b130)
	/private/tmp/influxdb-20180414-90429-1lo2iuo/src/github.com/influxdata/influxdb/models/points.go:1528 +0x1e7
github.com/influxdata/influxdb/models.parsePoint(0xc422f5e500, 0x24, 0x248, 0x16c112ea, 0xed2deac41, 0x0, 0x0, 0x0, 0xc4253b7470, 0xc42003428c, ...)
	/private/tmp/influxdb-20180414-90429-1lo2iuo/src/github.com/influxdata/influxdb/models/points.go:383 +0x1bf
github.com/influxdata/influxdb/models.ParsePointsWithPrecision(0xc422f5e500, 0x24, 0x248, 0x16c112ea, 0xed2deac41, 0x0, 0x0, 0x0, 0x60000c42405000a, 0x1a59601, ...)
	/private/tmp/influxdb-20180414-90429-1lo2iuo/src/github.com/influxdata/influxdb/models/points.go:340 +0x305
github.com/influxdata/influxdb/services/httpd.(*Handler).serveWrite(0xc4200c3ad0, 0x77ace28, 0xc423194540, 0xc4237f6700, 0x0, 0x0)
	/private/tmp/influxdb-20180414-90429-1lo2iuo/src/github.com/influxdata/influxdb/services/httpd/handler.go:719 +0x8c6
github.com/influxdata/influxdb/services/httpd.(*Handler).(github.com/influxdata/influxdb/services/httpd.serveWrite)-fm(0x77ace28, 0xc423194540, 0xc4237f6700, 0x0, 0x0)
	/private/tmp/influxdb-20180414-90429-1lo2iuo/src/github.com/influxdata/influxdb/services/httpd/handler.go:150 +0x5c
github.com/influxdata/influxdb/services/httpd.authenticate.func1(0x77ace28, 0xc423194540, 0xc4237f6700)
	/private/tmp/influxdb-20180414-90429-1lo2iuo/src/github.com/influxdata/influxdb/services/httpd/handler.go:1371 +0x790
net/http.HandlerFunc.ServeHTTP(0xc42023e780, 0x77ace28, 0xc423194540, 0xc4237f6700)
	/usr/local/Cellar/go/1.10.1/libexec/src/net/http/server.go:1947 +0x44
github.com/influxdata/influxdb/services/httpd.(*Handler).responseWriter.func1(0x1a48ec0, 0xc423194520, 0xc4237f6700)
	/private/tmp/influxdb-20180414-90429-1lo2iuo/src/github.com/influxdata/influxdb/services/httpd/handler.go:1548 +0xab
net/http.HandlerFunc.ServeHTTP(0xc42023e7a0, 0x1a48ec0, 0xc423194520, 0xc4237f6700)
	/usr/local/Cellar/go/1.10.1/libexec/src/net/http/server.go:1947 +0x44
github.com/influxdata/influxdb/services/httpd.gzipFilter.func1(0x1a48ec0, 0xc423194520, 0xc4237f6700)
	/private/tmp/influxdb-20180414-90429-1lo2iuo/src/github.com/influxdata/influxdb/services/httpd/gzip.go:23 +0x29e
net/http.HandlerFunc.ServeHTTP(0xc42023e7c0, 0x1a48ec0, 0xc423194520, 0xc4237f6700)
	/usr/local/Cellar/go/1.10.1/libexec/src/net/http/server.go:1947 +0x44
github.com/influxdata/influxdb/services/httpd.cors.func1(0x1a48ec0, 0xc423194520, 0xc4237f6700)
	/private/tmp/influxdb-20180414-90429-1lo2iuo/src/github.com/influxdata/influxdb/services/httpd/handler.go:1493 +0x102
net/http.HandlerFunc.ServeHTTP(0xc42023e7e0, 0x1a48ec0, 0xc423194520, 0xc4237f6700)
	/usr/local/Cellar/go/1.10.1/libexec/src/net/http/server.go:1947 +0x44
github.com/influxdata/influxdb/services/httpd.requestID.func1(0x1a48ec0, 0xc423194520, 0xc4237f6700)
	/private/tmp/influxdb-20180414-90429-1lo2iuo/src/github.com/influxdata/influxdb/services/httpd/handler.go:1524 +0x179
net/http.HandlerFunc.ServeHTTP(0xc42023e800, 0x1a48ec0, 0xc423194520, 0xc4237f6700)
	/usr/local/Cellar/go/1.10.1/libexec/src/net/http/server.go:1947 +0x44
github.com/influxdata/influxdb/services/httpd.(*Handler).logging.func1(0x1a48ec0, 0xc423194500, 0xc4237f6700)
	/private/tmp/influxdb-20180414-90429-1lo2iuo/src/github.com/influxdata/influxdb/services/httpd/handler.go:1532 +0xe1
net/http.HandlerFunc.ServeHTTP(0xc42023e820, 0x1a48ec0, 0xc423194500, 0xc4237f6700)
	/usr/local/Cellar/go/1.10.1/libexec/src/net/http/server.go:1947 +0x44
github.com/influxdata/influxdb/services/httpd.(*Handler).recovery.func1(0x1a4b980, 0xc42291e540, 0xc4237f6700)
	/private/tmp/influxdb-20180414-90429-1lo2iuo/src/github.com/influxdata/influxdb/services/httpd/handler.go:1585 +0x14c
net/http.HandlerFunc.ServeHTTP(0xc42023e840, 0x1a4b980, 0xc42291e540, 0xc4237f6700)
	/usr/local/Cellar/go/1.10.1/libexec/src/net/http/server.go:1947 +0x44
github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc42023e420, 0x1a4b980, 0xc42291e540, 0xc4237f6700)
	/private/tmp/influxdb-20180414-90429-1lo2iuo/src/github.com/bmizerany/pat/mux.go:117 +0x152
github.com/influxdata/influxdb/services/httpd.(*Handler).ServeHTTP(0xc4200c3ad0, 0x1a4b980, 0xc42291e540, 0xc4237f6700)
	/private/tmp/influxdb-20180414-90429-1lo2iuo/src/github.com/influxdata/influxdb/services/httpd/handler.go:315 +0x24d
net/http.serverHandler.ServeHTTP(0xc42064a270, 0x1a4b980, 0xc42291e540, 0xc4237f6700)
	/usr/local/Cellar/go/1.10.1/libexec/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc4232303c0, 0x1a4cd40, 0xc422a2c1c0)
	/usr/local/Cellar/go/1.10.1/libexec/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.10.1/libexec/src/net/http/server.go:2795 +0x27b
__Additional info:__ [Include gist of relevant config, logs, etc.]
```

**Comment by e-dard** [comment]
@craigching thanks for this. I have reproduced and we will get a fix together.

**Comment by craigching** [comment]
awesome, thanks @e-dard!
