### ISSUE TITLE
influx freezes and can't be written to

### ISSUE THREAD

**Issue by ElFishi** [influxdata/influxdb#10123]
__System info:__ 
Influx 1.6.0, Raspberry Pi 3
Processor: BCM2835
Distribution: Raspbian GNU/Linux 9 (stretch)
Kernel version: Linux 4.14.52-v7+ armv7l
Firmware: #1123

__Steps to reproduce:__

I run Influx together with telegraf and home-assistant to log sensor data. At irregular intervals all three log messages that writing to Influx fails, e.g. 
```
Jul 24 18:35:05 Zorin telegraf[3634]: 2018-07-24T16:35:05Z E! [outputs.influxdb]: when writing to [http://127.0.0.1:8086]: Post http://127.0.0.1:8086/write?db=telegraf: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Jul 24 18:35:05 Zorin telegraf[3634]: 2018-07-24T16:35:05Z E! Error writing to output [influxdb]: could not write any address
Jul 24 18:35:35 Zorin telegraf[3634]: 2018-07-24T16:35:35Z E! [outputs.influxdb]: when writing to [http://127.0.0.1:8086]: Post http://127.0.0.1:8086/write?db=telegraf: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Jul 24 18:35:35 Zorin telegraf[3634]: 2018-07-24T16:35:35Z E! Error writing to output [influxdb]: could not write any address
Jul 24 18:35:41 Zorin influxd[6013]: ts=2018-07-24T16:35:41.425230Z lvl=info msg="failed to store statistics" log_id=09VHdFFW000 service=monitor error=timeout
Jul 24 18:35:45 Zorin telegraf[3634]: 2018-07-24T16:35:45Z E! [outputs.influxdb]: when writing to [http://127.0.0.1:8086]: Post http://127.0.0.1:8086/write?db=telegraf: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Jul 24 18:35:45 Zorin telegraf[3634]: 2018-07-24T16:35:45Z E! Error writing to output [influxdb]: could not write any address
Jul 24 18:35:46 Zorin hass[3709]: 2018-07-24 18:35:46 ERROR (InfluxDB) [homeassistant.components.influxdb] Write error
Jul 24 18:35:46 Zorin hass[3709]: Traceback (most recent call last):
Jul 24 18:35:46 Zorin hass[3709]:   File "/srv/homeassistant/lib/python3.5/site-packages/urllib3/connectionpool.py", line 387, in _make_request
Jul 24 18:35:46 Zorin hass[3709]:     six.raise_from(e, None)
Jul 24 18:35:46 Zorin hass[3709]:   File "<string>", line 2, in raise_from
Jul 24 18:35:46 Zorin hass[3709]:   File "/srv/homeassistant/lib/python3.5/site-packages/urllib3/connectionpool.py", line 383, in _make_request
Jul 24 18:35:46 Zorin hass[3709]:     httplib_response = conn.getresponse()
Jul 24 18:35:46 Zorin hass[3709]:   File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
Jul 24 18:35:46 Zorin hass[3709]:     response.begin()
Jul 24 18:35:46 Zorin hass[3709]:   File "/usr/lib/python3.5/http/client.py", line 297, in begin
Jul 24 18:35:46 Zorin hass[3709]:     version, status, reason = self._read_status()
Jul 24 18:35:46 Zorin hass[3709]:   File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
Jul 24 18:35:46 Zorin hass[3709]:     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
Jul 24 18:35:46 Zorin hass[3709]:   File "/usr/lib/python3.5/socket.py", line 576, in readinto
Jul 24 18:35:46 Zorin hass[3709]:     return self._sock.recv_into(b)
Jul 24 18:35:46 Zorin hass[3709]: socket.timeout: timed out
Jul 24 18:35:46 Zorin hass[3709]: During handling of the above exception, another exception occurred:
Jul 24 18:35:46 Zorin hass[3709]: Traceback (most recent call last):
Jul 24 18:35:46 Zorin hass[3709]:   File "/srv/homeassistant/lib/python3.5/site-packages/requests/adapters.py", line 445, in send
Jul 24 18:35:46 Zorin hass[3709]:     timeout=timeout
Jul 24 18:35:46 Zorin hass[3709]:   File "/srv/homeassistant/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
Jul 24 18:35:46 Zorin hass[3709]:     _stacktrace=sys.exc_info()[2])
Jul 24 18:35:46 Zorin hass[3709]:   File "/srv/homeassistant/lib/python3.5/site-packages/urllib3/util/retry.py", line 357, in increment
Jul 24 18:35:46 Zorin hass[3709]:     raise six.reraise(type(error), error, _stacktrace)
Jul 24 18:35:46 Zorin hass[3709]:   File "/srv/homeassistant/lib/python3.5/site-packages/urllib3/packages/six.py", line 686, in reraise
Jul 24 18:35:46 Zorin hass[3709]:     raise value
Jul 24 18:35:46 Zorin hass[3709]:   File "/srv/homeassistant/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
Jul 24 18:35:46 Zorin hass[3709]:     chunked=chunked)
Jul 24 18:35:46 Zorin hass[3709]:   File "/srv/homeassistant/lib/python3.5/site-packages/urllib3/connectionpool.py", line 389, in _make_request
Jul 24 18:35:46 Zorin hass[3709]:     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
Jul 24 18:35:46 Zorin hass[3709]:   File "/srv/homeassistant/lib/python3.5/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
Jul 24 18:35:46 Zorin hass[3709]:     raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
Jul 24 18:35:46 Zorin hass[3709]: urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=8086): Read timed out. (read timeout=5)
Jul 24 18:35:46 Zorin hass[3709]: During handling of the above exception, another exception occurred:
Jul 24 18:35:46 Zorin hass[3709]: Traceback (most recent call last):
Jul 24 18:35:46 Zorin hass[3709]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/influxdb.py", line 316, in write_to_influxdb
Jul 24 18:35:46 Zorin hass[3709]:     self.influx.write_points(json)
Jul 24 18:35:46 Zorin hass[3709]:   File "/srv/homeassistant/lib/python3.5/site-packages/influxdb/client.py", line 468, in write_points
Jul 24 18:35:46 Zorin hass[3709]:     tags=tags, protocol=protocol)
Jul 24 18:35:46 Zorin hass[3709]:   File "/srv/homeassistant/lib/python3.5/site-packages/influxdb/client.py", line 532, in _write_points
Jul 24 18:35:46 Zorin hass[3709]:     protocol=protocol
Jul 24 18:35:46 Zorin hass[3709]:   File "/srv/homeassistant/lib/python3.5/site-packages/influxdb/client.py", line 312, in write
Jul 24 18:35:46 Zorin hass[3709]:     headers=headers
Jul 24 18:35:46 Zorin hass[3709]:   File "/srv/homeassistant/lib/python3.5/site-packages/influxdb/client.py", line 252, in request
Jul 24 18:35:46 Zorin hass[3709]:     timeout=self._timeout
Jul 24 18:35:46 Zorin hass[3709]:   File "/srv/homeassistant/lib/python3.5/site-packages/requests/sessions.py", line 512, in request
Jul 24 18:35:46 Zorin hass[3709]:     resp = self.send(prep, **send_kwargs)
Jul 24 18:35:46 Zorin hass[3709]:   File "/srv/homeassistant/lib/python3.5/site-packages/requests/sessions.py", line 622, in send
Jul 24 18:35:46 Zorin hass[3709]:     r = adapter.send(request, **kwargs)
Jul 24 18:35:46 Zorin hass[3709]:   File "/srv/homeassistant/lib/python3.5/site-packages/requests/adapters.py", line 526, in send
Jul 24 18:35:46 Zorin hass[3709]:     raise ReadTimeout(e, request=request)
Jul 24 18:35:46 Zorin hass[3709]: requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=8086): Read timed out. (read timeout=5)
Jul 24 18:35:47 Zorin hass[3709]: 2018-07-24 18:35:47 ERROR (InfluxDB) [homeassistant.components.influxdb] Resumed, lost 2 events
```
The problem is not caused by home-assistant, telegraf or the Influx monitor service: When either are disabled the others still throw messages. So I presume Influx locks at random times. 

For a test I moved the data directory to a USB-disk, but I still received the same messages. 
  
Help wanted.

[iostat.txt](https://github.com/influxdata/influxdb/files/2224623/iostat.txt)
[profiles.tar.gz](https://github.com/influxdata/influxdb/files/2224644/profiles.tar.gz)
[vars.txt](https://github.com/influxdata/influxdb/files/2224645/vars.txt)

**Comment by e-dard** [comment]
@ElFishi we would need a stack dump if Influx has deadlocked. When influx freezes can you send a `SIGQUIT` signal to the influx process and please provide the stacktrace?

**Comment by ElFishi** [comment]
Thanks for picking this up. 
I'd love to comply but I'm afraid I need a hand with this. 
I _presume_ influx freezes from the messages I see logged. However, this happens only intermittently. Most of the time there is no problem. 
Can you devise a script that polls influx and  sends the `SIGQUIT `and records the stacktrace once influx locks? I don't have such skills. 
cheers

**Comment by salberin** [comment]
I'm seeing the same behaviour on a Raspberry Pi 3, running only InfluxDb and Chronograph/Telegraph. I'm logging data to it via an external script running on a separate PC and it starts throwing errors. It happens after around 48 hours of uptime. 
What's interesting is that the Pi is not locked up initially. I usually have an SSH connection open to it at all times, and I can start typing a new command. However, pressing enter on the commandline will hangup the Pi. I will attempt sending syslog messages via remote syslog and see what pops up. 
My gut feeling is that influx triggers an Out-of-memory, though.

**Comment by alongL** [comment]
I found if the influxd.exe is just starting(the logging is showing on the screen)  , in this time , If you try to insert data , influxd.exe will  freeze.  My influx version is V1.5 .
I guess the influxd is analysing the data at start time .  I suggest the server no to provide service before data prepare complete.

**Comment by russorat** [comment]
closing due to age. please upgrade to the latest influxdb version and open a new issue if the problem persists.

**Comment by lobocobra** [comment]
Hi I have the latest influxDB and do see the exact same error:
influxd[1029]: ts=2019-11-11T02:35:50.026000Z lvl=info msg="failed to store statistics" log_id=0J1ywLal000 service=monitor error=timeout

After a while then influxdb hangs the whole system.

I run debian in a VMM on my NAS and my gut feeling is also that influxdb uses all memory and then the whole system hangs. root is then in read-only. If I then login root fs is not full but I have to restart the system. It happens always after a few days.

Searching the logs for hours, I believe it starts during backup (disk busy?) and then after 30-40 of such messages the system dies. The disk is locally and should deliver > 100mb/s

I am on debian 9.11 and influxdb  OSS 1.7.9
