### ISSUE TITLE
SHOW MEASUREMENTS triggers segmentation fault

### ISSUE THREAD

**Issue by jacobmarble** [influxdata/influxdb#10174]
__System info:__

1.5.4, Linux, thousands of measurements, >100GB shards

__Steps to reproduce:__

Call `SHOW MEASUREMENTS` at a bad time.

__Expected behavior:__

Measurements shown.

__Actual behavior:__

```
unexpected fault address 0x7f6b1c39c951
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f6b1c39c951 pc=0x45eeac]

goroutine 354152551 [running]:
runtime.throw(0xefdb2d, 0x5)
	/usr/local/go/src/runtime/panic.go:605 +0x95 fp=0xc656d5cc28 sp=0xc656d5cc08 pc=0x42d6b5
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:374 +0x227 fp=0xc656d5cc78 sp=0xc656d5cc28 pc=0x444187
runtime.memmove(0xc625e299e0, 0x7f6b1c39c951, 0x2d)
	/usr/local/go/src/runtime/memmove_amd64.s:184 +0x15c fp=0xc656d5cc80 sp=0xc656d5cc78 pc=0x45eeac
runtime.slicebytetostring(0x0, 0x7f6b1c39c951, 0x2d, 0x280c0, 0xc625e299e0, 0x2d)
	/usr/local/go/src/runtime/string.go:98 +0x79 fp=0xc656d5ccb0 sp=0xc656d5cc80 pc=0x448c09
github.com/influxdata/influxdb/pkg/slices.BytesToStrings(0xc7643e2000, 0xa521, 0xc555, 0xc4dbcf7d58, 0x6, 0x0)
	/go/src/github.com/influxdata/influxdb/pkg/slices/bytes.go:7 +0xe5 fp=0xc656d5cd50 sp=0xc656d5ccb0 pc=0xb97f45
github.com/influxdata/plutonium/cluster.(*Service).processShowMeasurements(0xc420158700, 0x1471ce0, 0xc4a6bb2dd0)
	/go/src/github.com/influxdata/plutonium/cluster/service.go:1750 +0x27c fp=0xc656d5ce10 sp=0xc656d5cd50 pc=0xc9692c
github.com/influxdata/plutonium/cluster.(*Service).handleConn(0xc420158700, 0x1471ce0, 0xc4a6bb2dd0)
	/go/src/github.com/influxdata/plutonium/cluster/service.go:455 +0x1a69 fp=0xc656d5dfa0 sp=0xc656d5ce10 pc=0xc8e689
github.com/influxdata/plutonium/cluster.(*Service).handleMuxConn.func3(0xc57956b260, 0xc420158700, 0xc4a6bb2dd0)
	/go/src/github.com/influxdata/plutonium/cluster/service.go:275 +0x67 fp=0xc656d5dfc8 sp=0xc656d5dfa0 pc=0xca5337
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc656d5dfd0 sp=0xc656d5dfc8 pc=0x45e5a1
created by github.com/influxdata/plutonium/cluster.(*Service).handleMuxConn
	/go/src/github.com/influxdata/plutonium/cluster/service.go:273 +0x195
```

__Additional info:__

Stack trace illustrated:

```golang
mBytes, resp.Err = s.TSDBStore.MeasurementNames(auth, req.Database, req.Condition)
resp.Measurements = slices.BytesToStrings(mBytes)
```

```golang
func BytesToStrings(a [][]byte) []string {
    s := make([]string, 0, len(a))
    for _, v := range a {
>>>        s = append(s, string(v))
    }
    return s
}
```

The problem is that `IndexSet.MeasurementNamesByExpr()` returns a `[][]byte` that is backed by `mmap`'d memory, and that memory is released before it is read. It is allowed to be released is because `MeasurementNamesByExpr` retains and (defer) releases the series file.

Possible solutions:
- Copy the `[][]byte` before returning. The elements are often copied as strings later, so a third copy isn't ideal.
- Return the release function with the byte slice, and allow to caller to safely use the slice until it's done. `MeasurementNamesByExpr` is called from 6 places in this codebase, so there's some work to do.

**Comment by jacobmarble** [comment]
This issue is superseded by #10183
