### ISSUE TITLE
Influxdb won't start after update from 1.5.2 inmem to 1.6.1 tsi

### ISSUE THREAD

**Issue by lassizci** [influxdata/influxdb#10216]
__System info:__ influxdb 1.6.1, ubuntu 16.04, from deb packages.

__Steps to reproduce:__

1. Have a running 1.5.2 with `index-version = "inmem"`
2. build tsi index files
```
influx_inspect buildtsi -datadir /data/influxdb -waldir /data/influxdb
```
3. restart influxdb

__Expected behavior:__ influxdb should start

__Actual behavior:__ Crashes on startup:

```
Aug 21 17:45:13 metricsdb1 influxd[1950]: ts=2018-08-21T17:45:13.370774Z lvl=info msg="Opened shard" log_id=0A3PI3~W000 service=store trace_id=0A3PI3~W002 op_name=tsdb_open index_version=tsi1 path=/data/influxdb/data/events/default/2120 duration=2975.209ms
Aug 21 17:45:18 metricsdb1 influxd[1950]: ts=2018-08-21T17:45:18.157407Z lvl=info msg="Opened file" log_id=0A3PI3~W000 engine=tsm1 service=filestore path=/data/influxdb/data/telegraf20160722/default/1971/000010112-000000007.tsm id=2 duration=3.360ms 
Aug 21 17:45:18 metricsdb1 influxd[1950]: ts=2018-08-21T17:45:18.294371Z lvl=info msg="Opened file" log_id=0A3PI3~W000 engine=tsm1 service=filestore path=/data/influxdb/data/telegraf20160722/default/1971/000020224-000000007.tsm id=5 duration=4.866ms 
Aug 21 17:45:18 metricsdb1 influxd[1950]: ts=2018-08-21T17:45:18.299976Z lvl=info msg="Opened file" log_id=0A3PI3~W000 engine=tsm1 service=filestore path=/data/influxdb/data/telegraf20160722/default/2041/000010112-000000007.tsm id=2 duration=7.861ms 
Aug 21 17:45:18 metricsdb1 influxd[1950]: ts=2018-08-21T17:45:18.348218Z lvl=info msg="Opened file" log_id=0A3PI3~W000 engine=tsm1 service=filestore path=/data/influxdb/data/telegraf20160722/default/2041/000019840-000000007.tsm id=5 duration=1.077ms 
Aug 21 17:45:18 metricsdb1 influxd[1950]: panic: runtime error: slice bounds out of range
Aug 21 17:45:18 metricsdb1 influxd[1950]: goroutine 3148 [running]:
Aug 21 17:45:18 metricsdb1 influxd[1950]: github.com/influxdata/influxdb/tsdb.ReadSeriesKeyTag(0x7f09024dbaf0, 0x1ed, 0x3b1f510, 0x5f, 0x7f09024dbaf0, 0x1ed, 0x3b1f510, 0xa, 0x3b272db, 0x7f08df4cfd2f, ...)
Aug 21 17:45:18 metricsdb1 influxd[1950]:         /go/src/github.com/influxdata/influxdb/tsdb/series_file.go:349 +0x10c
Aug 21 17:45:18 metricsdb1 influxd[1950]: github.com/influxdata/influxdb/tsdb/index/tsi1.(*LogFile).execSeriesEntry(0xc4270f0280, 0xc4324a9ca8)
Aug 21 17:45:18 metricsdb1 influxd[1950]:         /go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/log_file.go:714 +0x34c
Aug 21 17:45:18 metricsdb1 influxd[1950]: github.com/influxdata/influxdb/tsdb/index/tsi1.(*LogFile).execEntry(0xc4270f0280, 0xc4324a9ca8)
Aug 21 17:45:18 metricsdb1 systemd[1]: influxdb.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 21 17:45:18 metricsdb1 systemd[1]: influxdb.service: Unit entered failed state.
```

The crash doesn't seem to always happen at the same file.
__Additional info:__ default config with the exception of the base dir being /data/influxdb instead of /var/lib/influxdb

also tried running
```
influx_inspect verify -dir /data/influxdb/
```
which reported only healthy tsm files

**Comment by lassizci** [comment]
So I did the first pass of `buildtsi` while influxdb was running. Removed all `index` and `_series` directories and tried running `buildtsi` again. On startup it crashed a couple times, but eventually came up

**Comment by e-dard** [comment]
@lassizci I'm going to close this as it sounds like you are up and running. It's important that when `buildtsi` is being run there is no running `influxd` process.
