### ISSUE TITLE
SHOW TAG VALUES returns panic:runtime error: index out of range

### ISSUE THREAD

**Issue by suri70** [influxdata/influxdb#10309]
__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
Influxdb 1.6.3
RedHat 7
influxdb-1.6.3.x86_64.rpm

__Steps to reproduce:__
It happens intermittently and not reproduceable. This is the command we ran
SHOW TAG VALUES FROM ERILTE01_KPI WITH KEY = CELL WHERE MARKET = 'New Jersey'
When I change the MARKET to different value e.g. New York it returns result. So, it does not work only for certain tag.

__Expected behavior:__ [What you expected to happen]
The tag values of the measurement

__Actual behavior:__ [What actually happened]
Influxdb does not crash but it does not give back the tag values of the measurement for that particular tag. When I change the tag filter it returns the tag values correctly.

__Additional info:__ [Include gist of relevant config, logs, etc.]

This is what is the log

Sep 26 09:54:53 polwb007 influxd[1865]: ts=2018-09-26T16:54:53.053196Z lvl=error msg="SHOW TAG VALUES FROM ERILTE01_KPI WITH KEY = CELL WHERE MARKET = 'New Jersey' [panic:runtime error: index out of range] goroutine 6904608 [running]:\nruntime/debug.Stack(0xc61172f2c0, 0xc652c8ef00, 0x4d)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/influxdata/influxdb/query.(*Executor).recover(0xc4201755f0, 0xc61172f2c0, 0xc5c7794d20)\n\t/go/src/github.com/influxdata/influxdb/query/executor.go:394 +0xaf\npanic(0xcd0740, 0x1354d90)\n\t/usr/local/go/src/runtime/panic.go:502 +0x229\nencoding/binary.binary.bigEndian.Uint16(...)\n\t/usr/local/go/src/encoding/binary/binary.go:100\ngithub.com/influxdata/influxdb/tsdb.ReadSeriesKeyMeasurement(...)\n\t/go/src/github.com/influxdata/influxdb/tsdb/series_file.go:338\ngithub.com/influxdata/influxdb/tsdb.parseSeriesKey(0x7f445b18bc07, 0x1, 0x6743f9, 0x0, 0x0, 0x0, 0x9161ba, 0xc4209e6210, 0x63705, 0x7f445b18bc07, ...)\n\t/go/src/github.com/influxdata/influxdb/tsdb/series_file.go:375 +0x41b\ngithub.com/influxdata/influxdb/tsdb.ParseSeriesKey(0x7f445b18bc07, 0x1, 0x6743f9, 0x1, 0x6743f9, 0x0, 0x7f4468d880ab, 0x9, 0x673f55)\n\t/go/src/github.com/influxdata/influxdb/tsdb/series_file.go:358 +0x57\ngithub.com/influxdata/influxdb/tsdb.IndexSet.tagValuesByKeyAndExpr(0xc6d8561200, 0x1, 0x18, 0xc4200c4b40, 0xc4879b0f00, 0x1, 0x18, 0xea96e0, 0x13885f0, 0xc42a326440, ...)\n\t/go/src/github.com/influxdata/influxdb/tsdb/index.go:2368 +0x836\ngithub.com/influxdata/influxdb/tsdb.IndexSet.MeasurementTagKeyValuesByExpr(0xc6d8561200, 0x1, 0x18, 0xc4200c4b40, 0xc4879b0f00, 0x1, 0x18, 0xea96e0, 0x13885f0, 0xc42a326440, ...)\n\t/go/src/github.com/influxdata/influxdb/tsdb/index.go:2479 +0xbd0\ngithub.com/influxdata/influxdb/tsdb.(*Store).TagValues(0xc4203821e0, 0xea96e0, 0x13885f0, 0xc44f7f6700, 0x18, 0x20, 0xea6320, 0xc4831df140, 0x32f2d7fe, 0x109d537404, ...)\n\t/go/src/github.com/influxdata/influxdb/tsdb/store.go:1603 +0x897\ngithub.com/influxdata/influxdb/coordinator.(*StatementExecutor).executeShowTagValues(0xc4203409a0, 0xc600597d00, 0xc4879b0e40, 0x48, 0xf)\n\t/go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:1050 +0x839\ngithub.com/influxdata/influxdb/coordinator.(*StatementExecutor).ExecuteStatement(0xc4203409a0, 0xea94a0, 0xc600597d00, 0xc4879b0e40, 0x1, 0x1)\n\t/go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:194 +0x236f\ngithub.com/influxdata/influxdb/query.(*Executor).executeQuery(0xc4201755f0, 0xc61172f2c0, 0xc5edd7471c, 0x3, 0x0, 0x0, 0xea96e0, 0x13885f0, 0x2710, 0x0, ...)\n\t/go/src/github.com/influxdata/influxdb/query/executor.go:334 +0xb72\ncreated by github.com/influxdata/influxdb/query.(*Executor).ExecuteQuery\n\t/go/src/github.com/influxdata/influxdb/query/executor.go:236 +0xc9\n" log_id=0Am4Dsa0000 service=query

**Comment by benbjohnson** [comment]
@suri70 Can you run this command against your data directory:

```sh
$ influx_inspect verify-seriesfile -v -dir /path/to/influx/data
```

**Comment by suri70** [comment]
Attached is the output

[inspect_series.txt](https://github.com/influxdata/influxdb/files/2461569/inspect_series.txt)

**Comment by benbjohnson** [comment]
@suri70 It's odd to see so many errors in a single system. From the log:

```
ts=2018-10-09T17:37:37.637860Z lvl=error msg="Panic parsing key" log_id=0B2UKuF0000 path=/testmount/influxdb/data/_internal/_series partition=01 segment=0000 key= offset=38684 recovered="runtime error: index out of range"
ts=2018-10-09T17:37:37.789618Z lvl=error msg="Panic parsing key" log_id=0B2UKuF0000 path=/testmount/influxdb/data/ran/_series partition=00 segment=0000 key= offset=2469704 recovered="runtime error: index out of range"
ts=2018-10-09T17:37:37.864753Z lvl=error msg="Panic parsing key" log_id=0B2UKuF0000 path=/testmount/influxdb/data/suritestdb/_series partition=05 segment=0000 key= offset=1839774 recovered="runtime error: index out of range"
ts=2018-10-09T17:37:37.880135Z lvl=error msg="Panic parsing key" log_id=0B2UKuF0000 path=/testmount/influxdb/data/system/_series partition=06 segment=0000 key= offset=35 recovered="runtime error: index out of range"
```

Are you running this on NFS?

**Comment by benbjohnson** [comment]
The error is during reading but it looks like the files were corrupted during write. InfluxDB isn't supported on network file systems (e.g. NFS, GlusterFS). 

Also, it doesn't look like GlusterFS recommends running live databases on it either. From their docs:

> _Gluster does not support so called “structured data”, meaning live, SQL databases. Of course, using Gluster to backup and restore the database would be fine - Gluster is traditionally better when using file sizes at of least 16KB (with a sweet spot around 128KB or so)._
>
> https://docs.gluster.org/en/v3/Install-Guide/Overview/#is-gluster-going-to-work-for-me-and-what-i-need-it-to-do

**Comment by gretel** [comment]
i am getting this, too. can verify data fine though.

```
2019-05-06T21:29:57.388127Z     error   SHOW TAG VALUES FROM autogen.mqtt_consumer WITH KEY IN (host, rack, topic) [panic:runtime error: index out of range] goroutine 188574 [running]:
runtime/debug.Stack(0xc0004a0a20, 0x1, 0x1)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/influxdata/influxdb/query.(*Executor).recover(0xc000150ae0, 0xc0004a2640, 0xc00f7ed800)
        /usr/obj/ports/influxdb-1.6.1/go/src/github.com/influxdata/influxdb/query/executor.go:394 +0xc2
panic(0xd5b660, 0x1696bc0)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
encoding/binary.bigEndian.Uint16(...)
        /usr/local/go/src/encoding/binary/binary.go:100
github.com/influxdata/influxdb/tsdb.ReadSeriesKeyMeasurement(...)
        /usr/obj/ports/influxdb-1.6.1/go/src/github.com/influxdata/influxdb/tsdb/series_file.go:338
github.com/influxdata/influxdb/tsdb.ParseSeriesKey(0x222c4dcd6, 0x1, 0x3fe32a, 0x1, 0x3fe32a, 0x0, 0x1ba, 0x0, 0x0)
        /usr/obj/ports/influxdb-1.6.1/go/src/github.com/influxdata/influxdb/tsdb/series_file.go:359 +0x406
github.com/influxdata/influxdb/tsdb.(*SeriesFile).Series(0xc000097680, 0x1ba, 0x0, 0x0, 0x0, 0x0, 0x2, 0xc000af2520)
        /usr/obj/ports/influxdb-1.6.1/go/src/github.com/influxdata/influxdb/tsdb/series_file.go:200 +0x60
github.com/influxdata/influxdb/tsdb.IndexSet.MeasurementTagKeyValuesByExpr(0xc0004a2aa0, 0x1, 0x2, 0xc000097680, 0xc0004a0e90, 0x1, 0x2, 0x29b9fe578, 0xc000138240, 0xc000af2520, ...)
        /usr/obj/ports/influxdb-1.6.1/go/src/github.com/influxdata/influxdb/tsdb/index.go:2453 +0x6a5
github.com/influxdata/influxdb/tsdb.(*Store).TagValues(0xc00000c1e0, 0x29b9fe578, 0xc000138240, 0xc011078c10, 0x2, 0x2, 0xfd57e0, 0xc00049d290, 0x32f2d7fe, 0x109d537404, ...)
        /usr/obj/ports/influxdb-1.6.1/go/src/github.com/influxdata/influxdb/tsdb/store.go:1574 +0xe87
github.com/influxdata/influxdb/coordinator.(*StatementExecutor).executeShowTagValues(0xc00017f260, 0xc0000e7780, 0xc005f3b740, 0x1697fb0, 0x0)
        /usr/obj/ports/influxdb-1.6.1/go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:1050 +0x2be
github.com/influxdata/influxdb/coordinator.(*StatementExecutor).ExecuteStatement(0xc00017f260, 0xfdb0a0, 0xc0000e7780, 0xc005f3b740, 0x1, 0x1)
        /usr/obj/ports/influxdb-1.6.1/go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:194 +0x387e
github.com/influxdata/influxdb/query.(*Executor).executeQuery(0xc000150ae0, 0xc0004a2640, 0xc00b4c8bbf, 0x8, 0xc00b4c8c47, 0x7, 0x29b9fe578, 0xc000138240, 0x2710, 0x0, ...)
        /usr/obj/ports/influxdb-1.6.1/go/src/github.com/influxdata/influxdb/query/executor.go:334 +0x34e
created by github.com/influxdata/influxdb/query.(*Executor).ExecuteQuery
        /usr/obj/ports/influxdb-1.6.1/go/src/github.com/influxdata/influxdb/query/executor.go:236 +0xc9
        {"log_id": "0FFVub0G000", "service": "query"}
```

```shell
$ influx_inspect verify -dir /tsdb/influxdb/
/tsdb/influxdb/data/_internal/monitor/1/000000001-000000001.tsm: healthy
/tsdb/influxdb/data/_internal/monitor/3/000000002-000000002.tsm: healthy
/tsdb/influxdb/data/_internal/monitor/4/000000002-000000002.tsm: healthy
/tsdb/influxdb/data/_internal/monitor/5/000000001-000000001.tsm: healthy
/tsdb/influxdb/data/_internal/monitor/6/000000004-000000002.tsm: healthy
/tsdb/influxdb/data/_internal/monitor/9/000000001-000000001.tsm: healthy
/tsdb/influxdb/data/chronograf/autogen/10/000000001-000000001.tsm: healthy
/tsdb/influxdb/data/chronograf/autogen/7/000000004-000000002.tsm: healthy
/tsdb/influxdb/data/telegraf/autogen/2/000000022-000000002.tsm: healthy
/tsdb/influxdb/data/telegraf/autogen/8/000000001-000000001.tsm: healthy
/tsdb/influxdb/data/telegraf/autogen/8/000000003-000000001.tsm: healthy
/tsdb/influxdb/data/telegraf/autogen/8/000000005-000000001.tsm: healthy
/tsdb/influxdb/data/telegraf/autogen/8/000000006-000000001.tsm: healthy
Broken Blocks: 0 / 49467, in 0.271399509s

$ influx_inspect verify-seriesfile -v -dir /tsdb/influxdb/data
2019-05-06T21:38:44.176298Z	info	Verifying series file	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/_internal/_series"}
2019-05-06T21:38:44.177967Z	info	Verifying partition	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/_internal/_series", "partition": "00"}
2019-05-06T21:38:44.179263Z	info	Verifying segment	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/_internal/_series", "partition": "00", "segment": "0000"}
2019-05-06T21:38:44.181445Z	info	Verifying index	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/_internal/_series", "partition": "00"}
2019-05-06T21:38:44.182934Z	info	Verifying partition	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/_internal/_series", "partition": "01"}
2019-05-06T21:38:44.184232Z	info	Verifying segment	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/_internal/_series", "partition": "01", "segment": "0000"}
2019-05-06T21:38:44.185582Z	info	Verifying index	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/_internal/_series", "partition": "01"}
2019-05-06T21:38:44.186694Z	info	Verifying partition	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/_internal/_series", "partition": "02"}
2019-05-06T21:38:44.187573Z	info	Verifying segment	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/_internal/_series", "partition": "02", "segment": "0000"}
2019-05-06T21:38:44.189851Z	info	Verifying index	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/_internal/_series", "partition": "02"}
2019-05-06T21:38:44.190645Z	info	Verifying partition	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/_internal/_series", "partition": "03"}
2019-05-06T21:38:44.191619Z	info	Verifying segment	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/_internal/_series", "partition": "03", "segment": "0000"}
2019-05-06T21:38:44.191981Z	info	Verifying index	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/_internal/_series", "partition": "03"}
2019-05-06T21:38:44.192282Z	info	Verifying partition	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/_internal/_series", "partition": "04"}
2019-05-06T21:38:44.192546Z	info	Verifying segment	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/_internal/_series", "partition": "04", "segment": "0000"}
2019-05-06T21:38:44.192891Z	info	Verifying index	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/_internal/_series", "partition": "04"}
2019-05-06T21:38:44.193198Z	info	Verifying partition	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/_internal/_series", "partition": "05"}
2019-05-06T21:38:44.193452Z	info	Verifying segment	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/_internal/_series", "partition": "05", "segment": "0000"}
2019-05-06T21:38:44.193832Z	info	Verifying index	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/_internal/_series", "partition": "05"}
2019-05-06T21:38:44.194087Z	info	Verifying partition	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/_internal/_series", "partition": "06"}
2019-05-06T21:38:44.194383Z	info	Verifying segment	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/_internal/_series", "partition": "06", "segment": "0000"}
2019-05-06T21:38:44.194737Z	info	Verifying index	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/_internal/_series", "partition": "06"}
2019-05-06T21:38:44.194962Z	info	Verifying partition	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/_internal/_series", "partition": "07"}
2019-05-06T21:38:44.195197Z	info	Verifying segment	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/_internal/_series", "partition": "07", "segment": "0000"}
2019-05-06T21:38:44.195584Z	info	Verifying index	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/_internal/_series", "partition": "07"}
2019-05-06T21:38:44.195866Z	info	Verifying series file	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/chronograf/_series"}
2019-05-06T21:38:44.196392Z	info	Verifying partition	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/chronograf/_series", "partition": "00"}
2019-05-06T21:38:44.196662Z	info	Verifying segment	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/chronograf/_series", "partition": "00", "segment": "0000"}
2019-05-06T21:38:44.197015Z	info	Verifying index	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/chronograf/_series", "partition": "00"}
2019-05-06T21:38:44.197236Z	info	Verifying partition	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/chronograf/_series", "partition": "01"}
2019-05-06T21:38:44.197487Z	info	Verifying segment	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/chronograf/_series", "partition": "01", "segment": "0000"}
2019-05-06T21:38:44.197838Z	info	Verifying index	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/chronograf/_series", "partition": "01"}
2019-05-06T21:38:44.198029Z	info	Verifying partition	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/chronograf/_series", "partition": "02"}
2019-05-06T21:38:44.198262Z	info	Verifying segment	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/chronograf/_series", "partition": "02", "segment": "0000"}
2019-05-06T21:38:44.198573Z	info	Verifying index	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/chronograf/_series", "partition": "02"}
2019-05-06T21:38:44.198810Z	info	Verifying partition	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/chronograf/_series", "partition": "03"}
2019-05-06T21:38:44.199060Z	info	Verifying segment	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/chronograf/_series", "partition": "03", "segment": "0000"}
2019-05-06T21:38:44.199468Z	info	Verifying index	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/chronograf/_series", "partition": "03"}
2019-05-06T21:38:44.199687Z	info	Verifying partition	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/chronograf/_series", "partition": "04"}
2019-05-06T21:38:44.199938Z	info	Verifying segment	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/chronograf/_series", "partition": "04", "segment": "0000"}
2019-05-06T21:38:44.200247Z	info	Verifying index	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/chronograf/_series", "partition": "04"}
2019-05-06T21:38:44.200433Z	info	Verifying partition	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/chronograf/_series", "partition": "05"}
2019-05-06T21:38:44.200674Z	info	Verifying segment	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/chronograf/_series", "partition": "05", "segment": "0000"}
2019-05-06T21:38:44.202038Z	info	Verifying index	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/chronograf/_series", "partition": "05"}
2019-05-06T21:38:44.202285Z	info	Verifying partition	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/chronograf/_series", "partition": "06"}
2019-05-06T21:38:44.202534Z	info	Verifying segment	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/chronograf/_series", "partition": "06", "segment": "0000"}
2019-05-06T21:38:44.202942Z	info	Verifying index	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/chronograf/_series", "partition": "06"}
2019-05-06T21:38:44.203149Z	info	Verifying partition	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/chronograf/_series", "partition": "07"}
2019-05-06T21:38:44.203381Z	info	Verifying segment	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/chronograf/_series", "partition": "07", "segment": "0000"}
2019-05-06T21:38:44.203711Z	info	Verifying index	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/chronograf/_series", "partition": "07"}
2019-05-06T21:38:44.203905Z	info	Verifying series file	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/telegraf/_series"}
2019-05-06T21:38:44.204430Z	info	Verifying partition	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/telegraf/_series", "partition": "00"}
2019-05-06T21:38:44.204695Z	info	Verifying segment	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/telegraf/_series", "partition": "00", "segment": "0000"}
2019-05-06T21:38:44.205366Z	info	Verifying index	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/telegraf/_series", "partition": "00"}
2019-05-06T21:38:44.205869Z	info	Verifying partition	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/telegraf/_series", "partition": "01"}
2019-05-06T21:38:44.206134Z	info	Verifying segment	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/telegraf/_series", "partition": "01", "segment": "0000"}
2019-05-06T21:38:44.206782Z	info	Verifying index	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/telegraf/_series", "partition": "01"}
2019-05-06T21:38:44.207224Z	info	Verifying partition	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/telegraf/_series", "partition": "02"}
2019-05-06T21:38:44.207481Z	info	Verifying segment	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/telegraf/_series", "partition": "02", "segment": "0000"}
2019-05-06T21:38:44.208142Z	info	Verifying index	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/telegraf/_series", "partition": "02"}
2019-05-06T21:38:44.208612Z	info	Verifying partition	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/telegraf/_series", "partition": "03"}
2019-05-06T21:38:44.208893Z	info	Verifying segment	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/telegraf/_series", "partition": "03", "segment": "0000"}
2019-05-06T21:38:44.209416Z	info	Verifying index	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/telegraf/_series", "partition": "03"}
2019-05-06T21:38:44.209879Z	info	Verifying partition	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/telegraf/_series", "partition": "04"}
2019-05-06T21:38:44.210119Z	info	Verifying segment	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/telegraf/_series", "partition": "04", "segment": "0000"}
2019-05-06T21:38:44.211498Z	info	Verifying index	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/telegraf/_series", "partition": "04"}
2019-05-06T21:38:44.212030Z	info	Verifying partition	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/telegraf/_series", "partition": "05"}
2019-05-06T21:38:44.212288Z	info	Verifying segment	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/telegraf/_series", "partition": "05", "segment": "0000"}
2019-05-06T21:38:44.212941Z	info	Verifying index	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/telegraf/_series", "partition": "05"}
2019-05-06T21:38:44.213453Z	info	Verifying partition	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/telegraf/_series", "partition": "06"}
2019-05-06T21:38:44.213734Z	info	Verifying segment	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/telegraf/_series", "partition": "06", "segment": "0000"}
2019-05-06T21:38:44.214321Z	info	Verifying index	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/telegraf/_series", "partition": "06"}
2019-05-06T21:38:44.214743Z	info	Verifying partition	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/telegraf/_series", "partition": "07"}
2019-05-06T21:38:44.215025Z	info	Verifying segment	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/telegraf/_series", "partition": "07", "segment": "0000"}
2019-05-06T21:38:44.215562Z	info	Verifying index	{"log_id": "0FFmCJJl000", "path": "/tsdb/influxdb/data/telegraf/_series", "partition": "07"}
```

volume `/tsdb` is backed by a block device via `iscsi` for storage

```
$ mount | grep tsdb
/dev/sd1c on /tsdb type ffs (local, noatime, nodev, nosuid)
```

running on `openbsd65/amd64` using it's package of `influxdb`.

i assume this should be working. maybe i am wrong. maybe the code is. 😸
