### ISSUE TITLE
Panic when executing a Flux query that filters by value and returns no data

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/influxdb#10415]
1. Execute a query that includes a `filter` predicate by `_value`, where no data is returned:

```sh
$ curl -XPOST -sS -H accept:application/csv -H 'content-type:application/vnd.flux' localhost:8086/api/v2/query -d $'from(bucket:"db/rp") |> range(start:-5000h) |> filter(fn:(r) => r.tag0 == "value000" AND r._value == 1) |> group(none:true)'
````

2. Query results in a panic, as follows

```csv
#datatype,string,string
#group,true,true
#default,,
,error,reference
,"panic: runtime error: index out of range
goroutine 151 [running]:
runtime/debug.Stack(0x1c38e80, 0x1c28360, 0x287bc60)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*executionState).do.func1.1(0xc0013a2c80)
	/Users/stuartcarnie/projects/go/influxdata/influxdb/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/executor.go:214 +0xbc
panic(0x1c28360, 0x287bc60)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/storage/reads.(*table).readTags(0xc0024ec800, 0xc002c02a80, 0x4, 0x4)
	/Users/stuartcarnie/projects/go/influxdata/influxdb/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/storage/reads/table.go:106 +0x228
github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/storage/reads.newIntegerGroupTable(0x1f10480, 0xc000642e10, 0x691cd98, 0xc0001fc570, 0x1521081f198edde0, 0x1560fb06af83dde0, 0x1f18080, 0xc0006a41b0, 0xc000576600, 0x4, ...)
	/Users/stuartcarnie/projects/go/influxdata/influxdb/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/storage/reads/table.gen.go:337 +0x2e9
github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/storage/reads.(*tableIterator).handleGroupRead(0xc000642b40, 0xc001229af0, 0x1efdc20, 0xc001dd23c0, 0x0, 0x0)
	/Users/stuartcarnie/projects/go/influxdata/influxdb/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/storage/reads/reader.go:238 +0x3c8
github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/storage/reads.(*tableIterator).Do(0xc000642b40, 0xc001229af0, 0xc00067b620, 0x1ef5800)
	/Users/stuartcarnie/projects/go/influxdata/influxdb/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/storage/reads/reader.go:109 +0x2e8
github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/query/functions/inputs/storage.(*source).run(0xc001dd2280, 0x1f08c20, 0xc00067b620, 0x0, 0xc000477780)
	/Users/stuartcarnie/projects/go/influxdata/influxdb/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/query/functions/inputs/storage/storage.go:105 +0xfb
github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/query/functions/inputs/storage.(*source).Run(0xc001dd2280, 0x1f08c20, 0xc00067b620)
	/Users/stuartcarnie/projects/go/influxdata/influxdb/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/platform/query/functions/inputs/storage/storage.go:96 +0x43
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*executionState).do.func1(0xc0013a2c80, 0x1f08c20, 0xc00067b620, 0x1efdb20, 0xc001dd2280)
	/Users/stuartcarnie/projects/go/influxdata/influxdb/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/executor.go:221 +0x6b
created by github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*executionState).do
	/Users/stuartcarnie/projects/go/influxdata/influxdb/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/executor.go:202 +0x99
",
```

----

Also note that pressing `^C` to terminate the `influxd` process hangs after this panic occurs. This may be because the panic does not allow the cursors to properly cleanup and release TSM files. 

**NOTE**: influxdata/platform/pull/1249 addresses the resource leak issue

**Comment by stuartcarnie** [comment]
**NOTE:** The new planner does not push down grouping or aggregate optimizations, so this panic cannot be reproduced with the above query.

**Comment by stuartcarnie** [comment]
Closing this issue, which is related to influxdata/flux#319
