### ISSUE TITLE
Flaky CLI Test

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb#10430]
This failure popped up during a run of [this PR](https://github.com/influxdata/influxdb/pull/10427/).

```
--- PASS: TestRunCLI_ExecuteInsert_WithSignals (0.02s)
=== CONT  TestRunCLI_ExecuteInsert
Using database db
Using database db db
Unknown precision "". Please use rfc3339, h, m, s, ms, u or ns.
--- PASS: TestParseCommand_Use (0.03s)
=== CONT  TestRunCLI
--- PASS: TestRunCLI_ExecuteInsert (0.01s)
=== CONT  TestNewCLI
--- PASS: TestNewCLI (0.00s)
=== CONT  TestParseCommand_Consistency
Unknown consistency level "one;". Please use any, one, quorum, or all.
Unknown consistency level "one;". Please use any, one, quorum, or all.
--- PASS: TestParseCommand_Consistency (0.00s)
--- PASS: TestParseCommand_Insert (0.04s)
Unknown precision "". Please use rfc3339, h, m, s, ms, u or ns.
Connected to http://127.0.0.1:46472 version x.x
InfluxDB shell version: y.y
Enter an InfluxQL query
> panic: close of closed channel

goroutine 124 [running]:
github.com/influxdata/influxdb/cmd/influx/cli_test.TestRunCLI.func1(0xc00033fc00)
	/root/go/src/github.com/influxdata/influxdb/cmd/influx/cli/cli_test.go:53 +0x57
created by github.com/influxdata/influxdb/cmd/influx/cli_test.TestRunCLI
	/root/go/src/github.com/influxdata/influxdb/cmd/influx/cli/cli_test.go:52 +0x36e
FAIL	github.com/influxdata/influxdb/cmd/influx/cli	1.413s
?   	github.com/influxdata/influxdb/cmd/influx_inspect	[no test files]
?   	github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi	[no test files]
?   	github.com/influxdata/influxdb/cmd/influx_inspect/deletetsm	[no test files]
?   	github.com/influxdata/influxdb/cmd/influx_inspect/dumptsi	[no test files]
testing: warning: no tests to run
PASS
ok  	github.com/influxdata/influxdb/cmd/influx_inspect/dumptsm	1.019s [no tests to run]
?   	github.com/influxdata/influxdb/cmd/influx_inspect/dumptsmwal	[no test files]
=== RUN   Test_exportWALFile
--- PASS: Test_exportWALFile (0.01s)
=== RUN   Test_exportTSMFile
--- PASS: Test_exportTSMFile (0.01s)
PASS
ok  	github.com/influxdata/influxdb/cmd/influx
```

**Comment by stuartcarnie** [comment]
This is racy, as the `c.Quit` channel is closed in the test here:

https://github.com/influxdata/influxdb/blob/9ac37ca459bf15572f4d6c3adfc5ad99452b3a99/cmd/influx/cli/cli_test.go#L52-L54

In addition, it will be closed if the following line results in `io.EOF`

https://github.com/influxdata/influxdb/blob/c5ec3a32441c56be6477c0a897ec56e1c1714d7c/cmd/influx/cli/cli.go#L262

which leads to `l` being set to `"exit"`, calling `ParseCommand("exit")` and finally executing the `"exit"` case in the switch statement:

https://github.com/influxdata/influxdb/blob/c5ec3a32441c56be6477c0a897ec56e1c1714d7c/cmd/influx/cli/cli.go#L284-L285

**Comment by stuartcarnie** [comment]
The two tests which close the channel in the test function don't actually test any useful behavior, so I'm deleting them.
