### ISSUE TITLE
segmentation violation in roaring.difference used by tsdb.DifferenceSeriesIDIterators

### ISSUE THREAD

**Issue by nimdanitro** [influxdata/influxdb#10529]
__System info:__ InfluxDB v1.7.1, Linux amd64

__Steps to reproduce:__ sporadic SIGSEGV after upgrade from 1.6.4 to 1.7.1
__Expected behavior:__  no panic and SIGSEGV

__Actual behavior:__  ```
unexpected fault address 0x7f4821482641
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f4821482641 pc=0x97ebb1]

goroutine 3941050647 [running]:
runtime.throw(0x11ed3e4, 0x5)
        /opt/OSAGgobuild/latest/src/runtime/panic.go:608 +0x72 fp=0xcbb48a8220 sp=0xcbb48a81f0 pc=0x42e072
runtime.sigpanic()
        /opt/OSAGgobuild/latest/src/runtime/signal_unix.go:397 +0x275 fp=0xcbb48a8270 sp=0xcbb48a8220 pc=0x443945
github.com/influxdata/influxdb/vendor/github.com/influxdata/roaring.difference(0xc03685ed40, 0x1d, 0x1d, 0x7f4821482641, 0x1, 0xf9c2d, 0xc03685f400, 0x0, 0x1d, 0x25)
        /usr/src/packages/src/pkg-osaginfluxdb_1orwWK9oi2cm9yPgpTMlhjYs3yl4Gvp8/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/roaring/setutil.go:30 +0x71 fp=0xcbb48a8280 sp=0xcbb48a8270 pc=0x97ebb1
github.com/influxdata/influxdb/vendor/github.com/influxdata/roaring.(*arrayContainer).andNotArray(0xec0a5b0fa0, 0xca0c6cfca0, 0x13697e0, 0xec0a5b1aa0)
        /usr/src/packages/src/pkg-osaginfluxdb_1orwWK9oi2cm9yPgpTMlhjYs3yl4Gvp8/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/roaring/arraycontainer.go:654 +0xe9 fp=0xcbb48a82f0 sp=0xcbb48a8280 pc=0x950e59
github.com/influxdata/influxdb/vendor/github.com/influxdata/roaring.(*arrayContainer).andNot(0xec0a5b0fa0, 0x13697e0, 0xca0c6cfca0, 0x13697e0, 0xec0a5b1aa0)
        /usr/src/packages/src/pkg-osaginfluxdb_1orwWK9oi2cm9yPgpTMlhjYs3yl4Gvp8/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/roaring/arraycontainer.go:615 +0x11d fp=0xcbb48a8320 sp=0xcbb48a82f0 pc=0x950a5d
github.com/influxdata/influxdb/vendor/github.com/influxdata/roaring.AndNot(0xe1a0b79500, 0xe1a0b795e0, 0xec0a5b1880)
        /usr/src/packages/src/pkg-osaginfluxdb_1orwWK9oi2cm9yPgpTMlhjYs3yl4Gvp8/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/roaring/roaring.go:1096 +0x137 fp=0xcbb48a83f0 sp=0xcbb48a8320 pc=0x962f27
github.com/influxdata/influxdb/tsdb.(*SeriesIDSet).AndNot(0xd496397900, 0xec0a5b1880, 0x0)
        /usr/src/packages/src/pkg-osaginfluxdb_1orwWK9oi2cm9yPgpTMlhjYs3yl4Gvp8/src/github.com/influxdata/influxdb/tsdb/series_set.go:181 +0xba fp=0xcbb48a8420 sp=0xcbb48a83f0 pc=0x9a76ba
github.com/influxdata/influxdb/tsdb.DifferenceSeriesIDIterators(0x7ee068f4e0d0, 0xec0a5b1860, 0x7ee068f4e0d0, 0xec0a5b18c0, 0x0, 0x0)
        /usr/src/packages/src/pkg-osaginfluxdb_1orwWK9oi2cm9yPgpTMlhjYs3yl4Gvp8/src/github.com/influxdata/influxdb/tsdb/index.go:703 +0x14a fp=0xcbb48a8498 sp=0xcbb48a8420 pc=0x98a5aa
github.com/influxdata/influxdb/tsdb.IndexSet.seriesByBinaryExprStringIterator(0xccaa45b370, 0x1, 0x1, 0xc000c3c780, 0x0, 0x0, 0x0, 0xc7239b5bf0, 0x23, 0x30, ...)
        /usr/src/packages/src/pkg-osaginfluxdb_1orwWK9oi2cm9yPgpTMlhjYs3yl4Gvp8/src/github.com/influxdata/influxdb/tsdb/index.go:2113 +0x775 fp=0xcbb48a85a8 sp=0xcbb48a8498 pc=0x995315
github.com/influxdata/influxdb/tsdb.IndexSet.seriesByBinaryExprIterator(0xccaa45b370, 0x1, 0x1, 0xc000c3c780, 0x0, 0x0, 0x0, 0xc7239b5bf0, 0x23, 0x30, ...)
        /usr/src/packages/src/pkg-osaginfluxdb_1orwWK9oi2cm9yPgpTMlhjYs3yl4Gvp8/src/github.com/influxdata/influxdb/tsdb/index.go:2050 +0xc5f fp=0xcbb48a8710 sp=0xcbb48a85a8 pc=0x9947cf
github.com/influxdata/influxdb/tsdb.IndexSet.seriesByExprIterator(0xccaa45b370, 0x1, 0x1, 0xc000c3c780, 0x0, 0x0, 0x0, 0xc7239b5bf0, 0x23, 0x30, ...)
        /usr/src/packages/src/pkg-osaginfluxdb_1orwWK9oi2cm9yPgpTMlhjYs3yl4Gvp8/src/github.com/influxdata/influxdb/tsdb/index.go:1977 +0x379 fp=0xcbb48a87c8 sp=0xcbb48a8710 pc=0x993909
github.com/influxdata/influxdb/tsdb.IndexSet.seriesByExprIterator(0xccaa45b370, 0x1, 0x1, 0xc000c3c780, 0x0, 0x0, 0x0, 0xc7239b5bf0, 0x23, 0x30, ...)
        /usr/src/packages/src/pkg-osaginfluxdb_1orwWK9oi2cm9yPgpTMlhjYs3yl4Gvp8/src/github.com/influxdata/influxdb/tsdb/index.go:1954 +0xf7 fp=0xcbb48a8880 sp=0xcbb48a87c8 pc=0x993687
github.com/influxdata/influxdb/tsdb.IndexSet.seriesByExprIterator(0xccaa45b370, 0x1, 0x1, 0xc000c3c780, 0x0, 0x0, 0x0, 0xc7239b5bf0, 0x23, 0x30, ...)
        /usr/src/packages/src/pkg-osaginfluxdb_1orwWK9oi2cm9yPgpTMlhjYs3yl4Gvp8/src/github.com/influxdata/influxdb/tsdb/index.go:1954 +0xf7 fp=0xcbb48a8938 sp=0xcbb48a8880 pc=0x993687
github.com/influxdata/influxdb/tsdb.IndexSet.measurementSeriesByExprIterator(0xccaa45b370, 0x1, 0x1, 0xc000c3c780, 0x0, 0x0, 0x0, 0xc7239b5bf0, 0x23, 0x30, ...)
        /usr/src/packages/src/pkg-osaginfluxdb_1orwWK9oi2cm9yPgpTMlhjYs3yl4Gvp8/src/github.com/influxdata/influxdb/tsdb/index.go:1893 +0xb1 fp=0xcbb48a89f8 sp=0xcbb48a8938 pc=0x992d91
github.com/influxdata/influxdb/tsdb.IndexSet.TagSets(0xccaa45b370, 0x1, 0x1, 0xc000c3c780, 0x0, 0x0, 0x0, 0xc000c3c780, 0xc7239b5bf0, 0x23, ...)
        /usr/src/packages/src/pkg-osaginfluxdb_1orwWK9oi2cm9yPgpTMlhjYs3yl4Gvp8/src/github.com/influxdata/influxdb/tsdb/index.go:2545 +0xef fp=0xcbb48a8cc8 sp=0xcbb48a89f8 pc=0x99974f
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createCallIterator(0xcf6e2fe900, 0x134f760, 0xe792b1af30, 0xc5a6e2aa50, 0x23, 0xe792b1b290, 0x134c5e0, 0xe792b1b290, 0x0, 0x0, ...)
        /usr/src/packages/src/pkg-osaginfluxdb_1orwWK9oi2cm9yPgpTMlhjYs3yl4Gvp8/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:2375 +0x264 fp=0xcbb48a8ef0 sp=0xcbb48a8cc8 pc=0xec5c64
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).CreateIterator(0xcf6e2fe900, 0x134f760, 0xe792b1af30, 0xc5a6e2aa50, 0x23, 0x134c5e0, 0xe792b1b290, 0x0, 0x0, 0x0, ...)
        /usr/src/packages/src/pkg-osaginfluxdb_1orwWK9oi2cm9yPgpTMlhjYs3yl4Gvp8/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:2336 +0x379 fp=0xcbb48a91e0 sp=0xcbb48a8ef0 pc=0xec53a9
github.com/influxdata/influxdb/tsdb.(*Shard).CreateIterator(0xc24cd83200, 0x134f760, 0xe792b1af30, 0xc6c959cdc0, 0x134c5e0, 0xe792b1b290, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/src/packages/src/pkg-osaginfluxdb_1orwWK9oi2cm9yPgpTMlhjYs3yl4Gvp8/src/github.com/influxdata/influxdb/tsdb/shard.go:861 +0x120 fp=0xcbb48a9390 sp=0xcbb48a91e0 pc=0x9acb30
github.com/influxdata/influxdb/tsdb.Shards.CreateIterator(0xeb73bcccd8, 0x1, 0x1, 0x134f760, 0xe792b1af30, 0xc6c959cdc0, 0x134c5e0, 0xe792b1b290, 0x0, 0x0, ...)
        /usr/src/packages/src/pkg-osaginfluxdb_1orwWK9oi2cm9yPgpTMlhjYs3yl4Gvp8/src/github.com/influxdata/influxdb/tsdb/shard.go:1305 +0x13a fp=0xcbb48a9550 sp=0xcbb48a9390 pc=0x9b024a
github.com/influxdata/influxdb/tsdb.(*Shards).CreateIterator(0xd033425b60, 0x134f760, 0xe792b1af30, 0xc6c959cdc0, 0x134c5e0, 0xe792b1b290, 0x0, 0x0, 0x0, 0x0, ...)
        <autogenerated>:1 +0xb5 fp=0xcbb48a96b0 sp=0xcbb48a9550 pc=0x9cd335
github.com/influxdata/influxdb/coordinator.(*LocalShardMapping).CreateIterator(0xc8d5f5db00, 0x134f760, 0xe792b1af30, 0xc6c959cdc0, 0x134c5e0, 0xe792b1b290, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/src/packages/src/pkg-osaginfluxdb_1orwWK9oi2cm9yPgpTMlhjYs3yl4Gvp8/src/github.com/influxdata/influxdb/coordinator/shard_mapper.go:208 +0x3d5 fp=0xcbb48a9870 sp=0xcbb48a96b0 pc=0xa6bcd5
github.com/influxdata/influxdb/query.(*exprIteratorBuilder).callIterator.func1(0xcbb48aae98, 0x134f760, 0xe792b1af30, 0xcbb48a9cf8, 0xcbb48a9cb0, 0xe792b1b290, 0x0, 0x0)
        /usr/src/packages/src/pkg-osaginfluxdb_1orwWK9oi2cm9yPgpTMlhjYs3yl4Gvp8/src/github.com/influxdata/influxdb/query/select.go:581 +0x13a fp=0xcbb48a9b58 sp=0xcbb48a9870 pc=0x8f504a
github.com/influxdata/influxdb/query.(*exprIteratorBuilder).callIterator(0xc98f384e98, 0x134f760, 0xe792b1af30, 0xe792b1b290, 0x134c5e0, 0xe792b1b290, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/src/packages/src/pkg-osaginfluxdb_1orwWK9oi2cm9yPgpTMlhjYs3yl4Gvp8/src/github.com/influxdata/influxdb/query/select.go:605 +0xd5 fp=0xcbb48a9cd8 sp=0xcbb48a9b58 pc=0x8e29f5
github.com/influxdata/influxdb/query.(*exprIteratorBuilder).buildCallIterator.func1(0xe792b1b290, 0x134f760, 0xe792b1af30, 0xc98f384e98, 0xc98f384378, 0x0, 0x0, 0x0, 0x0)
        /usr/src/packages/src/pkg-osaginfluxdb_1orwWK9oi2cm9yPgpTMlhjYs3yl4Gvp8/src/github.com/influxdata/influxdb/query/select.go:513 +0xd0 fp=0xcbb48a9f80 sp=0xcbb48a9cd8 pc=0x8f4040
github.com/influxdata/influxdb/query.(*exprIteratorBuilder).buildCallIterator(0xcbb48aae98, 0x134f760, 0xe792b1af30, 0xe792b1b290, 0x2030cf, 0x2030cf, 0xddd7e4e0d0, 0x8)
        /usr/src/packages/src/pkg-osaginfluxdb_1orwWK9oi2cm9yPgpTMlhjYs3yl4Gvp8/src/github.com/influxdata/influxdb/query/select.go:557 +0xd59 fp=0xcbb48aae48 sp=0xcbb48a9f80 pc=0x8df839
github.com/influxdata/influxdb/query.buildExprIterator(0x134f760, 0xe792b1af30, 0x134c5e0, 0xe792b1b290, 0x7ee068f4e080, 0xc8d5f5db00, 0xe7d2ea4d20, 0x1, 0x1, 0x134c5e0, ...)
        /usr/src/packages/src/pkg-osaginfluxdb_1orwWK9oi2cm9yPgpTMlhjYs3yl4Gvp8/src/github.com/influxdata/influxdb/query/select.go:154 +0x1f4 fp=0xcbb48aafd8 sp=0xcbb48aae48 pc=0x8de7b4
github.com/influxdata/influxdb/query.buildFieldIterator(0x134f760, 0xe792b1af30, 0x134c5e0, 0xe792b1b290, 0x7ee068f4e080, 0xc8d5f5db00, 0xe7d2ea4d20, 0x1, 0x1, 0x0, ...)
        /usr/src/packages/src/pkg-osaginfluxdb_1orwWK9oi2cm9yPgpTMlhjYs3yl4Gvp8/src/github.com/influxdata/influxdb/query/select.go:851 +0x44b fp=0xcbb48ab1d0 sp=0xcbb48aafd8 pc=0x8e545b
github.com/influxdata/influxdb/query.buildCursor(0x134f760, 0xe792b1af30, 0xcf733f4b00, 0x7ee068f4e080, 0xc8d5f5db00, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/src/packages/src/pkg-osaginfluxdb_1orwWK9oi2cm9yPgpTMlhjYs3yl4Gvp8/src/github.com/influxdata/influxdb/query/select.go:736 +0xc7c fp=0xcbb48ab660 sp=0xcbb48ab1d0 pc=0x8e383c
github.com/influxdata/influxdb/query.(*preparedStatement).Select(0xc05a093ce0, 0x134f760, 0xe792b1af30, 0x0, 0x0, 0x0, 0x0)
        /usr/src/packages/src/pkg-osaginfluxdb_1orwWK9oi2cm9yPgpTMlhjYs3yl4Gvp8/src/github.com/influxdata/influxdb/query/select.go:119 +0x180 fp=0xcbb48ab8e0 sp=0xcbb48ab660 pc=0x8de410
github.com/influxdata/influxdb/query.Select(0x134f920, 0xd0e16a2cc0, 0xcf733f4700, 0x1339680, 0xc0003ee0e0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/src/packages/src/pkg-osaginfluxdb_1orwWK9oi2cm9yPgpTMlhjYs3yl4Gvp8/src/github.com/influxdata/influxdb/query/select.go:96 +0xfe fp=0xcbb48ab968 sp=0xcbb48ab8e0 pc=0x8de1fe
github.com/influxdata/influxdb/coordinator.(*StatementExecutor).createIterators(0xc00049cfc0, 0x134f920, 0xd0e16a2cc0, 0xcf733f4700, 0xc0004e83a0, 0x11, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/src/packages/src/pkg-osaginfluxdb_1orwWK9oi2cm9yPgpTMlhjYs3yl4Gvp8/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:635 +0x113 fp=0xcbb48aba20 sp=0xcbb48ab968 pc=0xa71c53
github.com/influxdata/influxdb/coordinator.(*StatementExecutor).executeSelectStatement(0xc00049cfc0, 0xcf733f4700, 0xd0e16a2cc0, 0x0, 0x0)
        /usr/src/packages/src/pkg-osaginfluxdb_1orwWK9oi2cm9yPgpTMlhjYs3yl4Gvp8/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:540 +0x99 fp=0xcbb48abbc8 sp=0xcbb48aba20 pc=0xa71009
github.com/influxdata/influxdb/coordinator.(*StatementExecutor).ExecuteStatement(0xc00049cfc0, 0x1350420, 0xcf733f4700, 0xd0e16a2cc0, 0x1, 0x1)
        /usr/src/packages/src/pkg-osaginfluxdb_1orwWK9oi2cm9yPgpTMlhjYs3yl4Gvp8/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:62 +0x2400 fp=0xcbb48abce8 sp=0xcbb48abbc8 pc=0xa6ea80
github.com/influxdata/influxdb/query.(*Executor).executeQuery(0xc0005697d0, 0xd033425600, 0xc0004e83a0, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/src/packages/src/pkg-osaginfluxdb_1orwWK9oi2cm9yPgpTMlhjYs3yl4Gvp8/src/github.com/influxdata/influxdb/query/executor.go:334 +0x355 fp=0xcbb48abf68 sp=0xcbb48abce8 pc=0x8847e5
runtime.goexit()
        /opt/OSAGgobuild/latest/src/runtime/asm_amd64.s:1333 +0x1 fp=0xcbb48abf70 sp=0xcbb48abf68 pc=0x45dad1
created by github.com/influxdata/influxdb/query.(*Executor).ExecuteQuery
        /usr/src/packages/src/pkg-osaginfluxdb_1orwWK9oi2cm9yPgpTMlhjYs3yl4Gvp8/src/github.com/influxdata/influxdb/query/executor.go:236 +0xc9
```

**Comment by benbjohnson** [comment]
@nimdanitro Thanks for reporting the bug. It definitely shouldn't be doing that.

Two questions:

1. Are you able to share your TSI index (i.e. the `index` directories within your shards). It sounds like you could have a truncated file within  there.

2. Would you be able to try shutting down the server, removing the `index` directories, and then rebuilding them with `influx_inspect buildtsi` (https://docs.influxdata.com/influxdb/v1.7/tools/influx_inspect/#buildtsi)

**Comment by caihuanong** [comment]
@benbjohnson I had a similar problem these days although I have converted all the databases to TSI index by removing the index directories, and then rebuilding them with influx_inspect buildtsi.
It's my panic information:
`ts=2019-01-09T07:30:12.886668Z lvl=info msg="Executing query" log_id=0Ce3qNBl000 service=query query="SELECT mean(incr) AS avg FROM cube_cloud.thirtydays.if_octets_tx WHERE host_port =~ /^(SH-YY-2-B05-HW12804-C-INT_100GE3_0_5)$/ AND _tenant_id =~ /^(039da7a214e54456bf17d5dcc190195b)$/ AND _namespace =~ /^(netmonitor)$/ AND time >= '2019-01-09T03:30:00Z' AND time < '2019-01-09T07:30:00Z' GROUP BY *, time(1m) LIMIT 14400"
unexpected fault address 0x7f6b4db0fc97
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f6b4db0fc97 pc=0x9564d0]

goroutine 439700113 [running]:
runtime.throw(0x11fcfa4, 0x5)
        /usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc2d8bb4560 sp=0xc2d8bb4530 pc=0x42df92
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:397 +0x275 fp=0xc2d8bb45b0 sp=0xc2d8bb4560 pc=0x443895
github.com/influxdata/influxdb/vendor/github.com/influxdata/roaring.(*bitmapContainer).andArray(0xc3388cfc60, 0xc1820addc0, 0xc00018aa80)
        /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/roaring/bitmapcontainer.go:725 +0xd0 fp=0xc2d8bb4600 sp=0xc2d8bb45b0 pc=0x9564d0
github.com/influxdata/influxdb/vendor/github.com/influxdata/roaring.(*bitmapContainer).and(0xc3388cfc60, 0x137c9a0, 0xc1820addc0, 0x70, 0x109e920)
        /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/roaring/bitmapcontainer.go:657 +0x239 fp=0xc2d8bb4648 sp=0xc2d8bb4600 pc=0x955da9
github.com/influxdata/influxdb/vendor/github.com/influxdata/roaring.(*arrayContainer).and(0xc1820addc0, 0x137cb20, 0xc3388cfc60, 0xb, 0x40bd8d)
        /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/roaring/arraycontainer.go:508 +0x1e8 fp=0xc2d8bb4690 sp=0xc2d8bb4648 pc=0x94f2f8
github.com/influxdata/influxdb/vendor/github.com/influxdata/roaring.And(0xc0013e64d0, 0xc0013e6620, 0xc04f9059c0)
        /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/roaring/roaring.go:1005 +0x122 fp=0xc2d8bb4720 sp=0xc2d8bb4690 pc=0x961e62
github.com/influxdata/influxdb/tsdb.(*SeriesIDSet).And(0xc04f905420, 0xc04f9059c0, 0x0)
        /go/src/github.com/influxdata/influxdb/tsdb/series_set.go:170 +0xba fp=0xc2d8bb4750 sp=0xc2d8bb4720 pc=0x9a862a
github.com/influxdata/influxdb/tsdb.IntersectSeriesIDIterators(0x7f669106b080, 0xc04f905980, 0x7f669106b080, 0xc04f9059e0, 0x0, 0x0)
        /go/src/github.com/influxdata/influxdb/tsdb/index.go:527 +0x18c fp=0xc2d8bb47c8 sp=0xc2d8bb4750 pc=0x98a91c
github.com/influxdata/influxdb/tsdb.IndexSet.seriesByExprIterator(0xc338698f60, 0x1, 0x1, 0xc000671c70, 0x0, 0x0, 0x0, 0xc03db3ead0, 0xc, 0x10, ...)
        /go/src/github.com/influxdata/influxdb/tsdb/index.go:1970 +0x258 fp=0xc2d8bb4880 sp=0xc2d8bb47c8 pc=0x9948a8
github.com/influxdata/influxdb/tsdb.IndexSet.seriesByExprIterator(0xc338698f60, 0x1, 0x1, 0xc000671c70, 0x0, 0x0, 0x0, 0xc03db3ead0, 0xc, 0x10, ...)
        /go/src/github.com/influxdata/influxdb/tsdb/index.go:1954 +0xf7 fp=0xc2d8bb4938 sp=0xc2d8bb4880 pc=0x994747
github.com/influxdata/influxdb/tsdb.IndexSet.measurementSeriesByExprIterator(0xc338698f60, 0x1, 0x1, 0xc000671c70, 0x0, 0x0, 0x0, 0xc03db3ead0, 0xc, 0x10, ...)
        /go/src/github.com/influxdata/influxdb/tsdb/index.go:1893 +0xb1 fp=0xc2d8bb49f8 sp=0xc2d8bb4938 pc=0x993e51
github.com/influxdata/influxdb/tsdb.IndexSet.TagSets(0xc338698f60, 0x1, 0x1, 0xc000671c70, 0x0, 0x0, 0x0, 0xc000671c70, 0xc03db3ead0, 0xc, ...)
        /go/src/github.com/influxdata/influxdb/tsdb/index.go:2545 +0xef fp=0xc2d8bb4cc8 sp=0xc2d8bb49f8 pc=0x99a7ff
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createCallIterator(0xc1459d67e0, 0x1361780, 0xc21323d320, 0xc027c5e200, 0xc, 0xc21323d4d0, 0x135e500, 0xc21323d4d0, 0x0, 0x0, ...)
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:2378 +0x264 fp=0xc2d8bb4ef0 sp=0xc2d8bb4cc8 pc=0xed1d34
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).CreateIterator(0xc1459d67e0, 0x1361780, 0xc21323d320, 0xc027c5e200, 0xc, 0x135e500, 0xc21323d4d0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:2339 +0x379 fp=0xc2d8bb51e0 sp=0xc2d8bb4ef0 pc=0xed1479
github.com/influxdata/influxdb/tsdb.(*Shard).CreateIterator(0xc3f0f65680, 0x1361780, 0xc21323d320, 0xc14cc62730, 0x135e500, 0xc21323d4d0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/influxdata/influxdb/tsdb/shard.go:861 +0x120 fp=0xc2d8bb5390 sp=0xc2d8bb51e0 pc=0x9adbe0
github.com/influxdata/influxdb/tsdb.Shards.CreateIterator(0xc23de6b3e8, 0x1, 0x1, 0x1361780, 0xc21323d320, 0xc14cc62730, 0x135e500, 0xc21323d4d0, 0x0, 0x0, ...)
        /go/src/github.com/influxdata/influxdb/tsdb/shard.go:1305 +0x13a fp=0xc2d8bb5550 sp=0xc2d8bb5390 pc=0x9b12fa
github.com/influxdata/influxdb/tsdb.(*Shards).CreateIterator(0xc2eca71d80, 0x1361780, 0xc21323d320, 0xc14cc62730, 0x135e500, 0xc21323d4d0, 0x0, 0x0, 0x0, 0x0, ...)
        <autogenerated>:1 +0xb5 fp=0xc2d8bb56b0 sp=0xc2d8bb5550 pc=0x9cf9c5
github.com/influxdata/influxdb/coordinator.(*LocalShardMapping).CreateIterator(0xc19f117080, 0x1361780, 0xc21323d320, 0xc14cc62730, 0x135e500, 0xc21323d4d0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/influxdata/influxdb/coordinator/shard_mapper.go:208 +0x3d5 fp=0xc2d8bb5870 sp=0xc2d8bb56b0 pc=0xa6e375
github.com/influxdata/influxdb/query.(*exprIteratorBuilder).callIterator.func1(0xc2d8bb6e98, 0x1361780, 0xc21323d320, 0xc2d8bb5cf8, 0xc2d8bb5cb0, 0xc21323d4d0, 0xc44a394070, 0xc2203b5ea0)
        /go/src/github.com/influxdata/influxdb/query/select.go:581 +0x13a fp=0xc2d8bb5b58 sp=0xc2d8bb5870 pc=0x8f43aa
github.com/influxdata/influxdb/query.(*exprIteratorBuilder).callIterator(0xc29aedee98, 0x1361780, 0xc21323d320, 0xc21323d4d0, 0x135e500, 0xc21323d4d0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/influxdata/influxdb/query/select.go:605 +0xd5 fp=0xc2d8bb5cd8 sp=0xc2d8bb5b58 pc=0x8e1d55
github.com/influxdata/influxdb/query.(*exprIteratorBuilder).buildCallIterator.func1(0xc21323d4d0, 0x1361780, 0xc21323d320, 0xc29aedee98, 0xc29aede378, 0xc2203b5f80, 0xc2203b5e30, 0xc2203b5f80, 0xc2203b5ea0)
        /go/src/github.com/influxdata/influxdb/query/select.go:513 +0xd0 fp=0xc2d8bb5f80 sp=0xc2d8bb5cd8 pc=0x8f33a0
github.com/influxdata/influxdb/query.(*exprIteratorBuilder).buildCallIterator(0xc2d8bb6e98, 0x1361780, 0xc21323d320, 0xc21323d4d0, 0x203013, 0x203013, 0xc2f3a1a3b0, 0x8)
        /go/src/github.com/influxdata/influxdb/query/select.go:557 +0xd41 fp=0xc2d8bb6e48 sp=0xc2d8bb5f80 pc=0x8debb1`

**Comment by jacobmarble** [comment]
@caihuanong what version of InfluxDB exhibits this behavior for you?

**Comment by caihuanong** [comment]
> @caihuanong what version of InfluxDB exhibits this behavior for you?

 1.7.2
