### ISSUE TITLE
Panic on Prometheus API read with interval longer than 15 days

### ISSUE THREAD

**Issue by lz1irq** [influxdata/influxdb#10595]
__System info:__ 
OS: `Debian 9 (Stretch)`
InfluxDB version: `1.7.2-1` (.deb from https://repos.influxdata.com/debian)
Prometheus version: `2.4.0 (branch: HEAD, revision: 068eaa5dbfce6c08f3d05d3d3c0bfd96267cfed2)`
Grafana: `5.4.2` (.deb from https://packagecloud.io/grafana/stable/debian)

__Steps to reproduce:__

1. Have existing Prometheus installation with default retention period (15 days) and some metrics already in it
2. Configure Prometheus to use the remote storage APIs:
```
remote_write:
  - url: "http://127.0.0.1:8086/api/v1/prom/write?db=prometheus&u=prometheus&p=password"

remote_read:
  - url: "http://127.0.0.1:8086/api/v1/prom/read?db=prometheus&u=prometheus&p=password"
```
3. Make a Grafana graph panel with any request to the Prometheus data source with a time interval of more than 15 days, e.g. `topk(5, max(scrape_duration_seconds) by (job))` with interval `Last 30 days`.

__Expected behavior:__ A graph is shown with values from the last 30 days.

__Actual behavior:__
1. Grafana shows an error: `server returned HTTP status 500 Internal Server Error`
2. The following trace is generated:
```
14:06:07 influxd[1107]: [httpd] 127.0.0.1 - prometheus [21/Dec/2018:14:06:07 +0200] "POST /api/v1/prom/read?db=prometheus&p=%5BREDACTED%5D&u=prometheus HTTP/1.1" 200 0 "-" "Go-http-client/1.1" cc02e386-0518-11e9-8ac7-000c294bfdf3 292 [panic:runtime error
id memory address or nil pointer dereference] goroutine 8945 [running]:                                                                                                                                                                                                 
14:06:07 influxd[1107]: runtime/debug.Stack(0xc001c952c0, 0xc0032eab00, 0xbeff53abc992ba8e)                                                                                                                                                                   
14:06:07 influxd[1107]:        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7                                                                                                                                                                            
14:06:07 influxd[1107]: github.com/influxdata/influxdb/services/httpd.(*Handler).recovery.func1.1(0xc001c952c0, 0xc0032eab00, 0xbeff53abc992ba8e, 0xd5ce710737, 0x1d25320, 0xc00010ad00, 0x135fe00, 0xc0082fcd20)
14:06:07 influxd[1107]:        /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1690 +0xcd
14:06:07 influxd[1107]: panic(0x1065c20, 0x1cfcbb0)                
14:06:07 influxd[1107]:        /usr/local/go/src/runtime/panic.go:513 +0x1b9
14:06:07 influxd[1107]: github.com/influxdata/influxdb/services/httpd.(*Handler).servePromRead(0xc00010ad00, 0x7fe0c765f530, 0xc001c95300, 0xc0032eab00, 0x1368940, 0xc000082bd0)
14:06:07 influxd[1107]:        /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1065 +0x270
14:06:07 influxd[1107]: github.com/influxdata/influxdb/services/httpd.(*Handler).servePromRead-fm(0x7fe0c765f530, 0xc001c95300, 0xc0032eab00, 0x1368940, 0xc000082bd0)
14:06:07 influxd[1107]:        /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:183 +0x5c
14:06:07 influxd[1107]: github.com/influxdata/influxdb/services/httpd.authenticate.func1(0x7fe0c765f530, 0xc001c95300, 0xc0032eab00)
14:06:07 influxd[1107]:        /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1570 +0x97
14:06:07 influxd[1107]: net/http.HandlerFunc.ServeHTTP(0xc0003b92e0, 0x7fe0c765f530, 0xc001c95300, 0xc0032eab00)
14:06:07 influxd[1107]:        /usr/local/go/src/net/http/server.go:1964 +0x44
14:06:07 influxd[1107]: github.com/influxdata/influxdb/services/httpd.(*Handler).responseWriter.func1(0x135bb40, 0xc001c952e0, 0xc0032eab00)
14:06:07 influxd[1107]:        /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1667 +0xab
14:06:07 influxd[1107]: net/http.HandlerFunc.ServeHTTP(0xc0003b9300, 0x135bb40, 0xc001c952e0, 0xc0032eab00)
14:06:07 influxd[1107]:        /usr/local/go/src/net/http/server.go:1964 +0x44
14:06:07 influxd[1107]: github.com/influxdata/influxdb/services/httpd.gzipFilter.func1(0x135bb40, 0xc001c952e0, 0xc0032eab00)
14:06:07 influxd[1107]:        /go/src/github.com/influxdata/influxdb/services/httpd/gzip.go:23 +0x29d
14:06:07 influxd[1107]: net/http.HandlerFunc.ServeHTTP(0xc0003b9320, 0x135bb40, 0xc001c952e0, 0xc0032eab00)                    
14:06:07 influxd[1107]:        /usr/local/go/src/net/http/server.go:1964 +0x44
14:06:07 influxd[1107]: github.com/influxdata/influxdb/services/httpd.cors.func1(0x135bb40, 0xc001c952e0, 0xc0032eab00)
14:06:07 influxd[1107]:        /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1609 +0xf3
14:06:07 influxd[1107]: net/http.HandlerFunc.ServeHTTP(0xc0003b9340, 0x135bb40, 0xc001c952e0, 0xc0032eab00)                                                      
14:06:07 influxd[1107]:        /usr/local/go/src/net/http/server.go:1964 +0x44
14:06:07 influxd[1107]: github.com/influxdata/influxdb/services/httpd.requestID.func1(0x135bb40, 0xc001c952e0, 0xc0032eab00)
14:06:07 influxd[1107]:        /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1640 +0x179
14:06:07 influxd[1107]: net/http.HandlerFunc.ServeHTTP(0xc0003b9360, 0x135bb40, 0xc001c952e0, 0xc0032eab00)
14:06:07 influxd[1107]:        /usr/local/go/src/net/http/server.go:1964 +0x44
14:06:07 influxd[1107]: github.com/influxdata/influxdb/services/httpd.(*Handler).logging.func1(0x135bb40, 0xc001c952c0, 0xc0032eab00)
14:06:07 influxd[1107]:        /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1648 +0xdc
14:06:07 influxd[1107]: net/http.HandlerFunc.ServeHTTP(0xc0003b9380, 0x135bb40, 0xc001c952c0, 0xc0032eab00)
14:06:07 influxd[1107]:        /usr/local/go/src/net/http/server.go:1964 +0x44
14:06:07 influxd[1107]: github.com/influxdata/influxdb/services/httpd.(*Handler).recovery.func1(0x135fe00, 0xc0082fcd20, 0xc0032eab00)
14:06:07 influxd[1107]:        /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1704 +0x147
14:06:07 influxd[1107]: net/http.HandlerFunc.ServeHTTP(0xc0003b93a0, 0x135fe00, 0xc0082fcd20, 0xc0032eab00)
14:06:07 influxd[1107]:        /usr/local/go/src/net/http/server.go:1964 +0x44
14:06:07 influxd[1107]: github.com/influxdata/influxdb/vendor/github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc0003b8d80, 0x135fe00, 0xc0082fcd20, 0xc0032eab00)
14:06:07 influxd[1107]:        /go/src/github.com/influxdata/influxdb/vendor/github.com/bmizerany/pat/mux.go:117 +0x155
14:06:07 influxd[1107]: github.com/influxdata/influxdb/services/httpd.(*Handler).ServeHTTP(0xc00010ad00, 0x135fe00, 0xc0082fcd20, 0xc0032eab00)
14:06:07 influxd[1107]:        /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:381 +0x247
14:06:07 influxd[1107]: net/http.serverHandler.ServeHTTP(0xc004a7a0d0, 0x135fe00, 0xc0082fcd20, 0xc0032eab00)
14:06:07 influxd[1107]:        /usr/local/go/src/net/http/server.go:2741 +0xab
14:06:07 influxd[1107]: net/http.(*conn).serve(0xc0079430e0, 0x13616c0, 0xc002960c40)                                                                                                                                                      
14:06:07 influxd[1107]:        /usr/local/go/src/net/http/server.go:1847 +0x646                                                                                                                                                            
14:06:07 influxd[1107]: created by net/http.(*Server).Serve                                                                                                                                                                                
14:06:07 influxd[1107]:        /usr/local/go/src/net/http/server.go:2851 +0x2f5   
```

__Additional info:__ 
To me this sounds like it could be somehow related to Prometheus' default internal retention period of 15 days (as going over that time period triggers the panic)... Shorter time intervals display the graphs just fine.

**Comment by marcantoine-bibeau** [comment]
Same for me but without Grafana running. 
I only have prometheus v2.6.0 and InfluxDB 1.7.2

Not sure where the `read` are coming from...
