### ISSUE TITLE
TestLauncher_BucketDelete sometimes fails with a handled panic

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#11153]
I don't have repro steps, and it seems to be pretty rare, but I occasionally see this error:

```
--- FAIL: TestLauncher_BucketDelete (0.41s)
    launcher_test.go:150: unexpected status code: 500, body: {"code":"internal error","message":"a panic has occurred","error":"runtime error: invalid memory address or nil pointer dereference"}, headers: map[Content-Type:[application/json; charset=utf-8] X-Platform-Error-Code:[internal error] Date:[Wed, 16 Jan 2019 19:42:33 GMT] Content-Length:[133]]
FAIL
```

**Comment by e-dard** [comment]
I'll try and repro.

**Comment by e-dard** [comment]
Full trace:

```
2019/01/17 17:57:05 http: panic serving 127.0.0.1:56990: runtime error: invalid memory address or nil pointer dereference
goroutine 1403 [running]:
net/http.(*conn).serve.func1(0xc0009726e0)
	/usr/local/share/go/src/net/http/server.go:1746 +0xd0
panic(0x1f8b140, 0x2fad190)
	/usr/local/share/go/src/runtime/panic.go:513 +0x1b9
github.com/influxdata/influxdb/tsdb/tsm1.(*Engine).DeleteBucket(0xc0001e6a00, 0xc0007e9ec0, 0x14, 0x14, 0x8000000000000000, 0x7fffffffffffffff, 0x0, 0x0)
	/Users/edd/go/src/github.com/influxdata/influxdb/tsdb/tsm1/engine_delete_measurement.go:160 +0x883
github.com/influxdata/influxdb/storage.(*Engine).DeleteBucket(0xc00019aa00, 0x3433cbec32c2000, 0x3433cbec32c2001, 0x0, 0x0)
	/Users/edd/go/src/github.com/influxdata/influxdb/storage/engine.go:382 +0x12d
github.com/influxdata/influxdb/storage.(*BucketService).DeleteBucket(0xc000adca40, 0x2388e00, 0xc000fa4930, 0x3433cbec32c2001, 0x0, 0x0)
	/Users/edd/go/src/github.com/influxdata/influxdb/storage/bucket_service.go:86 +0x8f
github.com/influxdata/influxdb/authorizer.(*BucketService).DeleteBucket(0xc0004aab40, 0x2388e00, 0xc000fa4930, 0x3433cbec32c2001, 0x0, 0x0)
	/Users/edd/go/src/github.com/influxdata/influxdb/authorizer/bucket.go:149 +0xe7
github.com/influxdata/influxdb/http.(*BucketHandler).handleDeleteBucket(0xc001026e70, 0x23818c0, 0xc001035fa0, 0xc000c0ae00)
	/Users/edd/go/src/github.com/influxdata/influxdb/http/bucket_service.go:352 +0xa5
github.com/influxdata/influxdb/http.(*BucketHandler).handleDeleteBucket-fm(0x23818c0, 0xc001035fa0, 0xc000c0ae00)
	/Users/edd/go/src/github.com/influxdata/influxdb/http/bucket_service.go:61 +0x48
net/http.HandlerFunc.ServeHTTP(0xc0004aaaf0, 0x23818c0, 0xc001035fa0, 0xc000c0ae00)
	/usr/local/share/go/src/net/http/server.go:1964 +0x44
github.com/influxdata/influxdb/vendor/github.com/julienschmidt/httprouter.(*Router).Handler.func1(0x23818c0, 0xc001035fa0, 0xc000c0ad00, 0xc0010a7540, 0x1, 0x2)
	/Users/edd/go/src/github.com/influxdata/influxdb/vendor/github.com/julienschmidt/httprouter/params_go17.go:26 +0x1c7
github.com/influxdata/influxdb/vendor/github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc000af4dc0, 0x23818c0, 0xc001035fa0, 0xc000c0ad00)
	/Users/edd/go/src/github.com/influxdata/influxdb/vendor/github.com/julienschmidt/httprouter/router.go:334 +0x792
github.com/influxdata/influxdb/http.(*APIHandler).ServeHTTP(0xc00035fb00, 0x23818c0, 0xc001035fa0, 0xc000c0ad00)
	/Users/edd/go/src/github.com/influxdata/influxdb/http/api_handler.go:230 +0x82f
github.com/influxdata/influxdb/http.(*AuthenticationHandler).ServeHTTP(0xc000af4d00, 0x23818c0, 0xc001035fa0, 0xc000c0aa00)
	/Users/edd/go/src/github.com/influxdata/influxdb/http/authentication_middleware.go:86 +0x4c4
github.com/influxdata/influxdb/http.(*PlatformHandler).ServeHTTP(0xc00100d7c0, 0x23818c0, 0xc001035fa0, 0xc000c0aa00)
	/Users/edd/go/src/github.com/influxdata/influxdb/http/platform_handler.go:62 +0xb5
github.com/influxdata/influxdb/http.(*Handler).ServeHTTP(0xc00035fb90, 0x2387000, 0xc000a5a7e0, 0xc000c0aa00)
	/Users/edd/go/src/github.com/influxdata/influxdb/http/handler.go:166 +0x21a
net/http.serverHandler.ServeHTTP(0xc00104e270, 0x2387000, 0xc000a5a7e0, 0xc000c0a900)
	/usr/local/share/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc0009726e0, 0x2388d40, 0xc0010a6800)
	/usr/local/share/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/share/go/src/net/http/server.go:2851 +0x2f5
```

**Comment by mark-rushakoff** [comment]
I just ran into this too at https://circleci.com/gh/influxdata/influxdb/21243. Reproduced locally with 

```
$ go test -run=TestLauncher_BucketDelete ./cmd/influxd/launcher/ -count=10
--- FAIL: TestLauncher_BucketDelete (0.44s)
    launcher_test.go:150: unexpected status code: 500, body: {"code":"internal error","message":"a panic has occurred","error":"runtime error: invalid memory address or nil pointer dereference"}, headers: map[Content-Type:[application/json; charset=utf-8] X-Platform-Error-Code:[internal error] Date:[Thu, 17 Jan 2019 22:02:45 GMT] Content-Length:[133]]
FAIL
FAIL	github.com/influxdata/influxdb/cmd/influxd/launcher	4.965s
```

Probably out of scope of this issue, but it would be nice to include the panic details in the test output, if possible. I couldn't get at the stack trace even under `go test -v`.

**Comment by e-dard** [comment]
This is a very subtle bug. Any bucket or org id that contains bytes `32` or `44` will be unable to have DROP BUCKET applied to them. I'm working on a fix.
