### ISSUE TITLE
influxd crashed when query top N

### ISSUE THREAD

**Issue by abo** [influxdata/influxdb#11195]
[I] 2019-01-17T02:33:13Z InfluxDB starting, version 1.2.0, branch master, commit b7bb7e8359642b6e071735b50ae41f5eb343fd42
[I] 2019-01-17T02:33:13Z Go version go1.7.4, GOMAXPROCS set to 2

[I] 2019-01-17T02:29:30Z SELECT top(mean_jitter, edge, label, vni, 50) FROM (SELECT mean(rtt) AS mean_rtt, mean(jitter) AS mean_jitter FROM dbdb.one_months.measurement WHERE time >= now() - 30s AND customer = '1811210002' GROUP BY edge, label, vni) WHERE (label = '1091' OR label = '1197' OR label = '1160' O
R label = '493' OR label = '483' OR label = '1205' OR label = '651' OR label = '750' OR label = '1204' OR label = '1203' OR label = '862' OR label = '742' OR
label = '501' OR label = '1188' OR label = '778' OR label = '749' OR label = '739' OR label = '805' OR label = '806') service=query
panic: runtime error: index out of range

goroutine 320303222 [running]:
panic(0xa03980, 0xc4200100c0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/influxdata/influxdb/influxql.(*floatFilterIterator).Next(0xc4339d1200, 0xc423143c20, 0x1, 0x0)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:2452 +0x2cb
github.com/influxdata/influxdb/influxql.(*floatInterruptIterator).Next(0xc43592d860, 0x8, 0x7, 0x2)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:777 +0x52
github.com/influxdata/influxdb/influxql.(*bufFloatIterator).Next(0xc43592d880, 0xc442e8a868, 0xc42346da70, 0xc442e8a868)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:95 +0x3c
github.com/influxdata/influxdb/influxql.(*floatReduceFloatIterator).reduce(0xc428422500, 0x0, 0xc427c854d0, 0x1, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:1046 +0x46
github.com/influxdata/influxdb/influxql.(*floatReduceFloatIterator).Next(0xc428422500, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:1020 +0xa1
github.com/influxdata/influxdb/influxql.(*floatInterruptIterator).Next(0xc43592d8a0, 0xc422f03260, 0xc429778d20, 0x6e38ae)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:777 +0x52
github.com/influxdata/influxdb/influxql.(*bufFloatIterator).Next(0xc43592d8c0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:95 +0x3c
github.com/influxdata/influxdb/influxql.(*floatAuxIterator).stream(0xc43592d920)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:874 +0x32
created by github.com/influxdata/influxdb/influxql.(*floatAuxIterator).Start
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:860 +0x3f

**Comment by abo** [comment]
same on influxdb 1.7.2
