### ISSUE TITLE
cli: `influx setup` return `invalid ID`

### ISSUE THREAD

**Issue by zhulongcheng** [influxdata/influxdb#11332]
```
⇒ ./bin/darwin/influx setup
Welcome to InfluxDB 2.0!
Please type your primary username: logan

Please type your password:

Please type your password again:

Please type your primary organization name: yisi

Please type your primary bucket name: purple

Please type your retention period in hours (exp 168 for 1 week).
Or press ENTER for infinite.:


You have entered:
  Username:          logan
  Organization:      yisi
  Bucket:            purple
  Retention Period:  infinite
Confirm? (y/n): y

invalid ID
```

**Comment by zhulongcheng** [comment]
```
goroutine 386 [running]:
runtime/debug.Stack(0x0, 0x100000000203000, 0x0)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/debug/stack.go:16 +0x22
github.com/influxdata/influxdb.ID.Encode(0x0, 0x62645b5, 0xc0003bf4e8, 0x1131d54, 0xc0001c8d20, 0x1ea43a0)
	/Users/logan/go/src/github.com/influxdata/influxdb/id.go:92 +0x131
github.com/influxdata/influxdb/bolt.(*Client).findOrganizationByID(0xc000494230, 0x2375400, 0xc000111b60, 0xc0001fe8c0, 0x0, 0x0, 0x0)
	/Users/logan/go/src/github.com/influxdata/influxdb/bolt/organization.go:55 +0x40
github.com/influxdata/influxdb/bolt.(*Client).setOrganizationOnBucket(0xc000494230, 0x2375400, 0xc000111b60, 0xc0001fe8c0, 0xc0000184b0, 0x0)
	/Users/logan/go/src/github.com/influxdata/influxdb/bolt/bucket.go:33 +0x5b
github.com/influxdata/influxdb/bolt.(*Client).forEachBucket(0xc000494230, 0x2375400, 0xc000111b60, 0xc0001fe8c0, 0xc0002a1d00, 0xc0003bf660, 0x20, 0x20)
	/Users/logan/go/src/github.com/influxdata/influxdb/bolt/bucket.go:479 +0x1b1
github.com/influxdata/influxdb/bolt.(*Client).findBuckets(0xc000494230, 0x2375400, 0xc000111b60, 0xc0001fe8c0, 0x0, 0x0, 0xc0002a1b88, 0x0, 0x0, 0x0, ...)
	/Users/logan/go/src/github.com/influxdata/influxdb/bolt/bucket.go:296 +0x189
github.com/influxdata/influxdb/bolt.(*Client).createOrgDependentMappings(0xc000494230, 0x2375400, 0xc000111b60, 0xc0001fe8c0, 0xc0002a1b60, 0x0, 0x0)
	/Users/logan/go/src/github.com/influxdata/influxdb/bolt/user_resource_mapping.go:122 +0x8c
github.com/influxdata/influxdb/bolt.(*Client).CreateUserResourceMapping.func1(0xc0001fe8c0, 0x21d9cb0, 0xc0001fe8c0)
	/Users/logan/go/src/github.com/influxdata/influxdb/bolt/user_resource_mapping.go:88 +0xd1
github.com/coreos/bbolt.(*DB).Update(0xc0005bc000, 0xc0003bf820, 0x0, 0x0)
	/Users/logan/go/pkg/mod/github.com/coreos/bbolt@v1.3.1-coreos.6/db.go:667 +0x90
github.com/influxdata/influxdb/bolt.(*Client).CreateUserResourceMapping(0xc000494230, 0x2375400, 0xc000111b60, 0xc0002a1b60, 0x0, 0x0)
	/Users/logan/go/src/github.com/influxdata/influxdb/bolt/user_resource_mapping.go:82 +0x82
github.com/influxdata/influxdb/bolt.(*Client).Generate(0xc000494230, 0x2375400, 0xc000111b60, 0xc000018410, 0x0, 0x0, 0xc00015bb80)
	/Users/logan/go/src/github.com/influxdata/influxdb/bolt/onboarding.go:109 +0x3f8
github.com/influxdata/influxdb/http.(*SetupHandler).handlePostSetup(0xc0000d8980, 0x236ff00, 0xc00050dc00, 0xc0001d4c00)
	/Users/logan/go/src/github.com/influxdata/influxdb/http/onboarding.go:65 +0x9e
github.com/influxdata/influxdb/http.(*SetupHandler).handlePostSetup-fm(0x236ff00, 0xc00050dc00, 0xc0001d4c00)
	/Users/logan/go/src/github.com/influxdata/influxdb/http/onboarding.go:33 +0x48
net/http.HandlerFunc.ServeHTTP(0xc0003237b0, 0x236ff00, 0xc00050dc00, 0xc0001d4c00)
	/usr/local/Cellar/go/1.11.1/libexec/src/net/http/server.go:1964 +0x44
github.com/julienschmidt/httprouter.(*Router).Handler.func1(0x236ff00, 0xc00050dc00, 0xc0001d4b00, 0x0, 0x0, 0x0)
	/Users/logan/go/pkg/mod/github.com/julienschmidt/httprouter@v1.2.0/params_go17.go:26 +0x1c7
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc0005f21c0, 0x236ff00, 0xc00050dc00, 0xc0001d4b00)
	/Users/logan/go/pkg/mod/github.com/julienschmidt/httprouter@v1.2.0/router.go:334 +0x792
github.com/influxdata/influxdb/http.(*APIHandler).ServeHTTP(0xc0005633b0, 0x236ff00, 0xc00050dc00, 0xc0001d4b00)
	/Users/logan/go/src/github.com/influxdata/influxdb/http/api_handler.go:221 +0x9e3
github.com/influxdata/influxdb/http.(*AuthenticationHandler).ServeHTTP(0xc00060d840, 0x236ff00, 0xc00050dc00, 0xc0001d4b00)
	/Users/logan/go/src/github.com/influxdata/influxdb/http/authentication_middleware.go:68 +0x5f5
github.com/influxdata/influxdb/http.(*PlatformHandler).ServeHTTP(0xc0004d4300, 0x236ff00, 0xc00050dc00, 0xc0001d4b00)
	/Users/logan/go/src/github.com/influxdata/influxdb/http/platform_handler.go:62 +0xb5
github.com/influxdata/influxdb/http.(*Handler).ServeHTTP(0xc000563440, 0x23733c0, 0xc0001fe460, 0xc0001d4b00)
	/Users/logan/go/src/github.com/influxdata/influxdb/http/handler.go:166 +0x21a
net/http.serverHandler.ServeHTTP(0xc00002d930, 0x23733c0, 0xc0001fe460, 0xc0001d4a00)
	/usr/local/Cellar/go/1.11.1/libexec/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc0001c8780, 0x2375340, 0xc00061d680)
	/usr/local/Cellar/go/1.11.1/libexec/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.11.1/libexec/src/net/http/server.go:2851 +0x2f5
```

**Comment by zhulongcheng** [comment]
invald data in bolt db:
```
b: &{ID:032b9bb1b5720000 OrganizationID: Organization: Name:one RetentionPolicyName: RetentionPeriod:0s}
```

No errors after removing DB path and restarting the service.
