### ISSUE TITLE
InfluxDB 2.0: Label HTTP API doesn't work

### ISSUE THREAD

**Issue by bednar** [influxdata/influxdb#11748]
When I trying operate with Label API (create, list, delete, ...) then all request fails with server error:

```go
2019/02/07 11:24:12 http: panic serving 172.17.0.1:48130: runtime error: invalid memory address or nil pointer dereference
goroutine 610 [running]:
net/http.(*conn).serve.func1(0xc000b33720)
        /usr/local/go/src/net/http/server.go:1746 +0xd0
panic(0x13e17e0, 0x256b060)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/influxdata/influxdb/http.(*APIHandler).ServeHTTP(0xc0007ec820, 0x17ea260, 0xc0005952e0, 0xc0001d9400)
        /go/src/github.com/influxdata/influxdb/http/api_handler.go:231 +0x8aa
github.com/influxdata/influxdb/http.(*AuthenticationHandler).ServeHTTP(0xc0005f9f40, 0x17ea260, 0xc0005952e0, 0xc0001d9300)
        /go/src/github.com/influxdata/influxdb/http/authentication_middleware.go:86 +0x467
github.com/influxdata/influxdb/http.(*PlatformHandler).ServeHTTP(0xc0004eafa0, 0x17ea260, 0xc0005952e0, 0xc0001d9300)
        /go/src/github.com/influxdata/influxdb/http/platform_handler.go:70 +0xd2
github.com/influxdata/influxdb/http.(*Handler).ServeHTTP(0xc0002da1b0, 0x17ed960, 0xc000659500, 0xc0001d9300)
        /go/src/github.com/influxdata/influxdb/http/handler.go:166 +0x21a
net/http.serverHandler.ServeHTTP(0xc000164b60, 0x17ed960, 0xc000659500, 0xc0001d9200)
        /usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc000b33720, 0x17ef9a0, 0xc00010aec0)
        /usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2851 +0x2f5
```

The problem is that the [label_service](https://github.com/influxdata/influxdb/blob/master/http/label_service.go) is not initialised in [NewAPIHandler](https://github.com/influxdata/influxdb/blob/93093e3b754ae2c3d921e7c9adb020c9b005a090/http/api_handler.go#L77) (caused by #11701).

The fix can be something like this:

```go
h.LabelHandler = NewLabelHandler()
h.LabelHandler.LabelService = b.LabelService
```

**Comment by bednar** [comment]
Fixed by #11762

Thanks @ischolten
