### ISSUE TITLE
InfluxDB 2.0: There is missing validation to required properties when create new Document [area/api]

### ISSUE THREAD

**Issue by bednar** [influxdata/influxdb#12861]
When I creating a `Document` with empty data the request is timing out :

```bash
-> POST 
-> http://127.0.0.1:9999/api/v2/documents/templates
-> {"labels":[]}

<- Socket timeout
```

there should be the `Bad Request` response with message like `document requires a valid DocumentMeta`.

introduced by #12382, cc @desa, @goller

**Comment by desa** [comment]
@bednar I'm not able to reproduce the hanging you're seeing. When I do

```sh
 curl -XPOST -H "Authorization: Token $TOKEN" http://localhost:9999/api/v2/documents/templates -d '{"labels":[]}'
{"code":"internal error","message":"a panic has occurred","error":"runtime error: invalid memory address or nil pointer dereference"}
```

I end up getting this panic
```
runtime error: invalid memory address or nil pointer dereference", "stack": "goroutine 856 [running]:
runtime/debug.Stack(0xc000608af0, 0xc0006be380, 0x40)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/influxdata/influxdb/http.panicHandler(0x26d8640, 0xc0008aaf00, 0xc000236b00, 0x210de80, 0x334cee0)
	/Users/michaeldesa/go/src/github.com/influxdata/influxdb/http/router.go:62 +0x234
github.com/julienschmidt/httprouter.(*Router).recv(0xc00065f3c0, 0x26d8640, 0xc0008aaf00, 0xc000236b00)
	/Users/michaeldesa/go/pkg/mod/github.com/julienschmidt/httprouter@v1.2.0/router.go:270 +0x79
panic(0x210de80, 0x334cee0)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/influxdata/influxdb/kv.(*Service).createDocument(0xc00058e050, 0x26de6c0, 0xc0006b3350, 0x26d7a80, 0xc0008ab240, 0xc000af01f7, 0x9, 0x0, 0x0, 0xc0006b3470)
	/Users/michaeldesa/go/src/github.com/influxdata/influxdb/kv/document.go:352 +0x45
github.com/influxdata/influxdb/kv.(*DocumentStore).CreateDocument.func1(0x26d7a80, 0xc0008ab240, 0x102cbf2, 0xc000000008)
	/Users/michaeldesa/go/src/github.com/influxdata/influxdb/kv/document.go:99 +0xa5
github.com/influxdata/influxdb/bolt.(*KVStore).Update.func1(0xc00043f260, 0x251a500, 0xc00043f260)
	/Users/michaeldesa/go/src/github.com/influxdata/influxdb/bolt/kv.go:122 +0x97
github.com/coreos/bbolt.(*DB).Update(0xc0006a0000, 0xc0003d7828, 0x0, 0x0)
	/Users/michaeldesa/go/pkg/mod/github.com/coreos/bbolt@v1.3.1-coreos.6/db.go:667 +0x90
github.com/influxdata/influxdb/bolt.(*KVStore).Update(0xc000458ca0, 0x26de6c0, 0xc0006b3440, 0xc00051dd80, 0x0, 0x0)
	/Users/michaeldesa/go/src/github.com/influxdata/influxdb/bolt/kv.go:121 +0xd5
github.com/influxdata/influxdb/kv.(*DocumentStore).CreateDocument(0xc0008ab1a0, 0x26de6c0, 0xc0006b3350, 0x0, 0xc000698118, 0x1, 0x1, 0x1, 0x0)
	/Users/michaeldesa/go/src/github.com/influxdata/influxdb/kv/document.go:98 +0xc5
github.com/influxdata/influxdb/http.(*DocumentHandler).handlePostDocument(0xc00019b020, 0x26d8640, 0xc0008aaf00, 0xc000236c00)
	/Users/michaeldesa/go/src/github.com/influxdata/influxdb/http/document_service.go:129 +0x305
github.com/influxdata/influxdb/http.(*DocumentHandler).handlePostDocument-fm(0x26d8640, 0xc0008aaf00, 0xc000236c00)
	/Users/michaeldesa/go/src/github.com/influxdata/influxdb/http/document_service.go:55 +0x48
net/http.HandlerFunc.ServeHTTP(0xc0005e66f0, 0x26d8640, 0xc0008aaf00, 0xc000236c00)
	/usr/local/go/src/net/http/server.go:1964 +0x44
github.com/julienschmidt/httprouter.(*Router).Handler.func1(0x26d8640, 0xc0008aaf00, 0xc000236b00, 0xc0008ab0c0, 0x1, 0x1)
	/Users/michaeldesa/go/pkg/mod/github.com/julienschmidt/httprouter@v1.2.0/params_go17.go:26 +0x1c7
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc00065f3c0, 0x26d8640, 0xc0008aaf00, 0xc000236b00)
	/Users/michaeldesa/go/pkg/mod/github.com/julienschmidt/httprouter@v1.2.0/router.go:334 +0x792
github.com/influxdata/influxdb/http.(*APIHandler).ServeHTTP(0xc0001e4e70, 0x26d8640, 0xc0008aaf00, 0xc000236b00)
	/Users/michaeldesa/go/src/github.com/influxdata/influxdb/http/api_handler.go:295 +0x4a0
github.com/influxdata/influxdb/http.(*AuthenticationHandler).ServeHTTP(0xc00065f240, 0x26d8640, 0xc0008aaf00, 0xc000236a00)
	/Users/michaeldesa/go/src/github.com/influxdata/influxdb/http/authentication_middleware.go:86 +0x467
github.com/influxdata/influxdb/http.(*PlatformHandler).ServeHTTP(0xc00033dfa0, 0x26d8640, 0xc0008aaf00, 0xc000236a00)
	/Users/michaeldesa/go/src/github.com/influxdata/influxdb/http/platform_handler.go:70 +0xd2
github.com/influxdata/influxdb/http.(*Handler).ServeHTTP(0xc000744990, 0x26dc4c0, 0xc00043e8c0, 0xc000236a00)
	/Users/michaeldesa/go/src/github.com/influxdata/influxdb/http/handler.go:166 +0x21a
net/http.serverHandler.ServeHTTP(0xc000370c30, 0x26dc4c0, 0xc00043e8c0, 0xc000236800)
	/usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc00087b5e0, 0x26de600, 0xc00051ca00)
	/usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2851 +0x2f5
```

which is because
https://github.com/influxdata/influxdb/blob/5a014dcb09f5798030d164c2d26f0020d0beee3f/http/document_service.go#L141

the document we unmarshal from the post request is nil.

**Comment by bednar** [comment]
With the latest nightly build I see same panic as is mentioned above.

@desa thx

**Comment by bednar** [comment]
It works perfectly 👍
