### ISSUE TITLE
panic:runtime error: invalid memory address or nil pointer dereference with prometheus

### ISSUE THREAD

**Issue by Seb0042** [influxdata/influxdb#13193]
Hi, I have two instances of prometheus and two of influxdb.
On one everything is fine on the other data are written but I have this error message on the logs.
I don't know what request is.

[05/Apr/2019:15:17:57 +0200] "POST /api/v1/prom/read?db=prometheus HTTP/1.1" 200 0 "-" "Prometheus/2.8.0" 3a595f67-57a5-11e9-9f31-8f412a7ce17b 138 [panic:runtime error: invalid memory address or nil pointer dereference] goroutine 101792 [running]:
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: runtime/debug.Stack(0xc006dbcb00, 0xc0062cbd00, 0xbf21f34149ef4cb5)
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: github.com/influxdata/influxdb/services/httpd.(*Handler).recovery.func1.1(0xc006dbcb00, 0xc0062cbd00, 0xbf21f34149ef4cb5, 0x49ade1b19c44, 0x1d89300, 0xc000287100, 0x1394cc0, 0xc00bfd9180)
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1760 +0xcd
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: panic(0x108d520, 0x1d707c0)
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: /usr/local/go/src/runtime/panic.go:513 +0x1b9
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: github.com/influxdata/influxdb/services/httpd.(*Handler).servePromRead(0xc000287100, 0x7f328ede4b60, 0xc006dbcb20, 0xc0062cbd00, 0x0, 0x0)
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1066 +0x270
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: github.com/influxdata/influxdb/services/httpd.(*Handler).servePromRead-fm(0x7f328ede4b60, 0xc006dbcb20, 0xc0062cbd00, 0x0, 0x0)
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:184 +0x5c
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: github.com/influxdata/influxdb/services/httpd.authenticate.func1(0x7f328ede4b60, 0xc006dbcb20, 0xc0062cbd00)
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1557 +0x788
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: net/http.HandlerFunc.ServeHTTP(0xc0002756c0, 0x7f328ede4b60, 0xc006dbcb20, 0xc0062cbd00)
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: /usr/local/go/src/net/http/server.go:1964 +0x44
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: github.com/influxdata/influxdb/services/httpd.(*Handler).responseWriter.func1(0x1390540, 0xc006dbcb00, 0xc0062cbd00)
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1737 +0xab
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: net/http.HandlerFunc.ServeHTTP(0xc0002756e0, 0x1390540, 0xc006dbcb00, 0xc0062cbd00)
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: /usr/local/go/src/net/http/server.go:1964 +0x44
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: github.com/influxdata/influxdb/services/httpd.gzipFilter.func1(0x1390540, 0xc006dbcb00, 0xc0062cbd00)
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: /go/src/github.com/influxdata/influxdb/services/httpd/gzip.go:23 +0x29d
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: net/http.HandlerFunc.ServeHTTP(0xc000275700, 0x1390540, 0xc006dbcb00, 0xc0062cbd00)
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: /usr/local/go/src/net/http/server.go:1964 +0x44
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: github.com/influxdata/influxdb/services/httpd.cors.func1(0x1390540, 0xc006dbcb00, 0xc0062cbd00)
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1679 +0xf3
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: net/http.HandlerFunc.ServeHTTP(0xc000275720, 0x1390540, 0xc006dbcb00, 0xc0062cbd00)
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: /usr/local/go/src/net/http/server.go:1964 +0x44
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: github.com/influxdata/influxdb/services/httpd.requestID.func1(0x1390540, 0xc006dbcb00, 0xc0062cbd00)
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1710 +0x179
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: net/http.HandlerFunc.ServeHTTP(0xc000275740, 0x1390540, 0xc006dbcb00, 0xc0062cbd00)
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: /usr/local/go/src/net/http/server.go:1964 +0x44
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: github.com/influxdata/influxdb/services/httpd.(*Handler).recovery.func1(0x1394cc0, 0xc00bfd9180, 0xc0062cbd00)
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1774 +0x147
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: net/http.HandlerFunc.ServeHTTP(0xc000275760, 0x1394cc0, 0xc00bfd9180, 0xc0062cbd00)
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: /usr/local/go/src/net/http/server.go:1964 +0x44
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: github.com/influxdata/influxdb/vendor/github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc000275240, 0x1394cc0, 0xc00bfd9180, 0xc0062cbd00)
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: /go/src/github.com/influxdata/influxdb/vendor/github.com/bmizerany/pat/mux.go:117 +0x155
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: github.com/influxdata/influxdb/services/httpd.(*Handler).ServeHTTP(0xc000287100, 0x1394cc0, 0xc00bfd9180, 0xc0062cbd00)
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:382 +0x247
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: net/http.serverHandler.ServeHTTP(0xc0003ea000, 0x1394cc0, 0xc00bfd9180, 0xc0062cbd00)
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: /usr/local/go/src/net/http/server.go:2741 +0xab
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: net/http.(*conn).serve(0xc0011fa320, 0x1396600, 0xc0051e2a80)
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: /usr/local/go/src/net/http/server.go:1847 +0x646
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: created by net/http.(*Server).Serve
Apr  5 15:17:57 node01.prod.appsecu.vault.m1.p.fti.net influxd[12832]: /usr/local/go/src/net/http/server.go:2851 +0x2f5

**Comment by Seb0042** [comment]
Version: 1.7.4
Prometheus: 2.8.0
Centos: 7.6.1810
Kernel: 3.10.0-957.10.1.el7.x86_64

**Comment by Seb0042** [comment]
Hi I upgraded to 1.7.5 and now it works.

**Comment by LuciferInLove** [comment]
Version: 1.7.6
Prometheus: 2.10.0

```
Jun  5 11:40:25 influxdb influxdb: [httpd] - prometheus [05/Jun/2019:11:40:25 +0300] "POST /api/v1/prom/read?db=prometheus&p=%5BREDACTED%5D&u=prometheus HTTP/1.1" 200 0
 "-" "Prometheus/2.10.0" 909f2e77-876d-11e9-ab9f-00155d25ad1b 185 [panic:runtime error: invalid memory address or nil pointer dereference] goroutine 782139 [running]:
Jun  5 11:40:25 influxdb influxdb: runtime/debug.Stack(0xc04444e120, 0xc037c38900, 0xbf35fdde75eca231)
Jun  5 11:40:25 influxdb influxdb: #011/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
Jun  5 11:40:25 influxdb influxdb: github.com/influxdata/influxdb/services/httpd.(*Handler).recovery.func1.1(0xc04444e120, 0xc037c38900, 0xbf35fdde75eca231, 0x587d7c1988, 0x21ab3e0, 0xc000111000, 
0x15bf420, 0xc044450000)
Jun  5 11:40:25 influxdb influxdb: #011/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1786 +0xcd
Jun  5 11:40:25 influxdb influxdb: panic(0x1116ca0, 0x2000040)
Jun  5 11:40:25 influxdb influxdb: #011/usr/local/go/src/runtime/panic.go:513 +0x1b9
Jun  5 11:40:25 influxdb influxdb: github.com/influxdata/influxdb/services/httpd.(*Handler).servePromRead(0xc000111000, 0x7fb30c9d4b30, 0xc04444e160, 0xc037c38900, 0x15c8900, 0xc000bfe7b0)
Jun  5 11:40:25 influxdb influxdb: #011/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1097 +0x30d
Jun  5 11:40:25 influxdb influxdb: github.com/influxdata/influxdb/services/httpd.(*Handler).servePromRead-fm(0x7fb30c9d4b30, 0xc04444e160, 0xc037c38900, 0x15c8900, 0xc000bfe7b0)
Jun  5 11:40:25 influxdb influxdb: #011/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:190 +0x5c
Jun  5 11:40:25 influxdb influxdb: github.com/influxdata/influxdb/services/httpd.authenticate.func1(0x7fb30c9d4b30, 0xc04444e160, 0xc037c38900)
Jun  5 11:40:25 influxdb influxdb: #011/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1666 +0x97
Jun  5 11:40:25 influxdb influxdb: net/http.HandlerFunc.ServeHTTP(0xc0009e1240, 0x7fb30c9d4b30, 0xc04444e160, 0xc037c38900)
Jun  5 11:40:25 influxdb influxdb: #011/usr/local/go/src/net/http/server.go:1964 +0x44
Jun  5 11:40:25 influxdb influxdb: github.com/influxdata/influxdb/services/httpd.(*Handler).responseWriter.func1(0x15ba6a0, 0xc04444e140, 0xc037c38900)
Jun  5 11:40:25 influxdb influxdb: #011/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1763 +0xab
Jun  5 11:40:25 influxdb influxdb: net/http.HandlerFunc.ServeHTTP(0xc0009e1260, 0x15ba6a0, 0xc04444e140, 0xc037c38900)
Jun  5 11:40:25 influxdb influxdb: #011/usr/local/go/src/net/http/server.go:1964 +0x44
Jun  5 11:40:25 influxdb influxdb: github.com/influxdata/influxdb/services/httpd.gzipFilter.func1(0x15ba6a0, 0xc04444e140, 0xc037c38900)
Jun  5 11:40:25 influxdb influxdb: #011/go/src/github.com/influxdata/influxdb/services/httpd/gzip.go:23 +0x29d
Jun  5 11:40:25 influxdb influxdb: net/http.HandlerFunc.ServeHTTP(0xc0009e1280, 0x15ba6a0, 0xc04444e140, 0xc037c38900)
Jun  5 11:40:25 influxdb influxdb: #011/usr/local/go/src/net/http/server.go:1964 +0x44
Jun  5 11:40:25 influxdb influxdb: github.com/influxdata/influxdb/services/httpd.cors.func1(0x15ba6a0, 0xc04444e140, 0xc037c38900)
Jun  5 11:40:25 influxdb influxdb: #011/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1705 +0xf3
Jun  5 11:40:25 influxdb influxdb: net/http.HandlerFunc.ServeHTTP(0xc0009e12a0, 0x15ba6a0, 0xc04444e140, 0xc037c38900)
Jun  5 11:40:25 influxdb influxdb: #011/usr/local/go/src/net/http/server.go:1964 +0x44
Jun  5 11:40:25 influxdb influxdb: github.com/influxdata/influxdb/services/httpd.requestID.func1(0x15ba6a0, 0xc04444e140, 0xc037c38900)
Jun  5 11:40:25 influxdb influxdb: #011/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1736 +0x179
Jun  5 11:40:25 influxdb influxdb: net/http.HandlerFunc.ServeHTTP(0xc0009e12c0, 0x15ba6a0, 0xc04444e140, 0xc037c38900)
Jun  5 11:40:25 influxdb influxdb: #011/usr/local/go/src/net/http/server.go:1964 +0x44
Jun  5 11:40:25 influxdb influxdb: github.com/influxdata/influxdb/services/httpd.(*Handler).logging.func1(0x15ba6a0, 0xc04444e120, 0xc037c38900)
Jun  5 11:40:25 influxdb influxdb: #011/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1744 +0xdc
Jun  5 11:40:25 influxdb influxdb: net/http.HandlerFunc.ServeHTTP(0xc0009e12e0, 0x15ba6a0, 0xc04444e120, 0xc037c38900)
Jun  5 11:40:25 influxdb influxdb: #011/usr/local/go/src/net/http/server.go:1964 +0x44
Jun  5 11:40:25 influxdb influxdb: github.com/influxdata/influxdb/services/httpd.(*Handler).recovery.func1(0x15bf420, 0xc044450000, 0xc037c38900)
Jun  5 11:40:25 influxdb influxdb: #011/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1800 +0x147
Jun  5 11:40:25 influxdb influxdb: net/http.HandlerFunc.ServeHTTP(0xc0009e1300, 0x15bf420, 0xc044450000, 0xc037c38900)
Jun  5 11:40:25 influxdb influxdb: #011/usr/local/go/src/net/http/server.go:1964 +0x44
Jun  5 11:40:25 influxdb influxdb: github.com/influxdata/influxdb/vendor/github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc0009e0d00, 0x15bf420, 0xc044450000, 0xc037c38900)
Jun  5 11:40:25 influxdb influxdb: #011/go/src/github.com/influxdata/influxdb/vendor/github.com/bmizerany/pat/mux.go:117 +0x155
Jun  5 11:40:25 influxdb influxdb: github.com/influxdata/influxdb/services/httpd.(*Handler).ServeHTTP(0xc000111000, 0x15bf420, 0xc044450000, 0xc037c38900)
Jun  5 11:40:25 influxdb influxdb: #011/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:392 +0x247
Jun  5 11:40:25 influxdb influxdb: net/http.serverHandler.ServeHTTP(0xc03be2aea0, 0x15bf420, 0xc044450000, 0xc037c38900)
Jun  5 11:40:25 influxdb influxdb: #011/usr/local/go/src/net/http/server.go:2741 +0xab
Jun  5 11:40:25 influxdb influxdb: net/http.(*conn).serve(0xc06f646500, 0x15c0f60, 0xc023148880)
Jun  5 11:40:25 influxdb influxdb: #011/usr/local/go/src/net/http/server.go:1847 +0x646
Jun  5 11:40:25 influxdb influxdb: created by net/http.(*Server).Serve
Jun  5 11:40:25 influxdb influxdb: #011/usr/local/go/src/net/http/server.go:2851 +0x2f5
```

Please, reopen

**Comment by Christoph-W** [comment]
Same problem on our system.
influxdb 1.7.6
prometheus 2.10.0

The following panic appears every minute:
```
2019-07-31T09:02:04.272723+02:00 monitoring influxdb: [httpd] 127.0.0.1 - promuser [31/Jul/2019:09:02:04 +0200] "POST /api/v1/prom/read?db=Prometheus HTTP/1.1" 200 0 "-" "Prometheus/2.10.0" 1a1b372e-b361-11e9-bd12-fa163e7d88b9 211 [panic:runtime error: invalid memory address or nil pointer dereference] goroutine 413227 [running]:
2019-07-31T09:02:04.274824+02:00 monitoring influxdb: runtime/debug.Stack(0xc0d39d1fa0, 0xc0961d1d00, 0xbf486d1b101a50c7)
2019-07-31T09:02:04.275147+02:00 monitoring influxdb: /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
2019-07-31T09:02:04.275435+02:00 monitoring influxdb: github.com/influxdata/influxdb/services/httpd.(*Handler).recovery.func1.1(0xc0d39d1fa0, 0xc0961d1d00, 0xbf486d1b101a50c7, 0x22c1a4d1aab0, 0x21ab3e0, 0xc000287200, 0x15bf420, 0xc0b6cd5340)
2019-07-31T09:02:04.275740+02:00 monitoring influxdb: /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1786 +0xcd
2019-07-31T09:02:04.276030+02:00 monitoring influxdb: panic(0x1116ca0, 0x2000040)
2019-07-31T09:02:04.276309+02:00 monitoring influxdb: /usr/local/go/src/runtime/panic.go:513 +0x1b9
2019-07-31T09:02:04.276578+02:00 monitoring influxdb: github.com/influxdata/influxdb/services/httpd.(*Handler).servePromRead(0xc000287200, 0x7ef3ce5c61e0, 0xc0d39d1fc0, 0xc0961d1d00, 0x15c8900, 0xc1d4b77b60)
2019-07-31T09:02:04.276887+02:00 monitoring influxdb: /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1097 +0x30d
2019-07-31T09:02:04.277186+02:00 monitoring influxdb: github.com/influxdata/influxdb/services/httpd.(*Handler).servePromRead-fm(0x7ef3ce5c61e0, 0xc0d39d1fc0, 0xc0961d1d00, 0x15c8900, 0xc1d4b77b60)
2019-07-31T09:02:04.280734+02:00 monitoring influxdb: /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:190 +0x5c
2019-07-31T09:02:04.281017+02:00 monitoring influxdb: github.com/influxdata/influxdb/services/httpd.authenticate.func1(0x7ef3ce5c61e0, 0xc0d39d1fc0, 0xc0961d1d00)
2019-07-31T09:02:04.281342+02:00 monitoring influxdb: /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1666 +0x97
2019-07-31T09:02:04.281645+02:00 monitoring influxdb: net/http.HandlerFunc.ServeHTTP(0xc0002fb7e0, 0x7ef3ce5c61e0, 0xc0d39d1fc0, 0xc0961d1d00)
2019-07-31T09:02:04.281934+02:00 monitoring influxdb: /usr/local/go/src/net/http/server.go:1964 +0x44
2019-07-31T09:02:04.282235+02:00 monitoring influxdb: github.com/influxdata/influxdb/services/httpd.(*Handler).responseWriter.func1(0x15ba6a0, 0xc0d39d1fa0, 0xc0961d1d00)
2019-07-31T09:02:04.282511+02:00 monitoring influxdb: /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1763 +0xab
2019-07-31T09:02:04.282812+02:00 monitoring influxdb: net/http.HandlerFunc.ServeHTTP(0xc0002fb800, 0x15ba6a0, 0xc0d39d1fa0, 0xc0961d1d00)
2019-07-31T09:02:04.283094+02:00 monitoring influxdb: /usr/local/go/src/net/http/server.go:1964 +0x44
2019-07-31T09:02:04.283389+02:00 monitoring influxdb: github.com/influxdata/influxdb/services/httpd.gzipFilter.func1(0x15ba6a0, 0xc0d39d1fa0, 0xc0961d1d00)
2019-07-31T09:02:04.283660+02:00 monitoring influxdb: /go/src/github.com/influxdata/influxdb/services/httpd/gzip.go:23 +0x29d
2019-07-31T09:02:04.283967+02:00 monitoring influxdb: net/http.HandlerFunc.ServeHTTP(0xc0002fb820, 0x15ba6a0, 0xc0d39d1fa0, 0xc0961d1d00)
2019-07-31T09:02:04.287066+02:00 monitoring influxdb: /usr/local/go/src/net/http/server.go:1964 +0x44
2019-07-31T09:02:04.287350+02:00 monitoring influxdb: github.com/influxdata/influxdb/services/httpd.cors.func1(0x15ba6a0, 0xc0d39d1fa0, 0xc0961d1d00)
2019-07-31T09:02:04.287617+02:00 monitoring influxdb: /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1705 +0xf3
2019-07-31T09:02:04.287884+02:00 monitoring influxdb: net/http.HandlerFunc.ServeHTTP(0xc0002fb840, 0x15ba6a0, 0xc0d39d1fa0, 0xc0961d1d00)
2019-07-31T09:02:04.288165+02:00 monitoring influxdb: /usr/local/go/src/net/http/server.go:1964 +0x44
2019-07-31T09:02:04.288448+02:00 monitoring influxdb: github.com/influxdata/influxdb/services/httpd.requestID.func1(0x15ba6a0, 0xc0d39d1fa0, 0xc0961d1d00)
2019-07-31T09:02:04.288746+02:00 monitoring influxdb: /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1736 +0x179
2019-07-31T09:02:04.289029+02:00 monitoring influxdb: net/http.HandlerFunc.ServeHTTP(0xc0002fb860, 0x15ba6a0, 0xc0d39d1fa0, 0xc0961d1d00)
2019-07-31T09:02:04.289326+02:00 monitoring influxdb: /usr/local/go/src/net/http/server.go:1964 +0x44
2019-07-31T09:02:04.289615+02:00 monitoring influxdb: github.com/influxdata/influxdb/services/httpd.(*Handler).recovery.func1(0x15bf420, 0xc0b6cd5340, 0xc0961d1d00)
2019-07-31T09:02:04.289886+02:00 monitoring influxdb: /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1800 +0x147
2019-07-31T09:02:04.290169+02:00 monitoring influxdb: net/http.HandlerFunc.ServeHTTP(0xc0002fb880, 0x15bf420, 0xc0b6cd5340, 0xc0961d1d00)
2019-07-31T09:02:04.290428+02:00 monitoring influxdb: /usr/local/go/src/net/http/server.go:1964 +0x44
2019-07-31T09:02:04.290699+02:00 monitoring influxdb: github.com/influxdata/influxdb/vendor/github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc0002fb360, 0x15bf420, 0xc0b6cd5340, 0xc0961d1d00)
2019-07-31T09:02:04.293396+02:00 monitoring influxdb: /go/src/github.com/influxdata/influxdb/vendor/github.com/bmizerany/pat/mux.go:117 +0x155
2019-07-31T09:02:04.293656+02:00 monitoring influxdb: github.com/influxdata/influxdb/services/httpd.(*Handler).ServeHTTP(0xc000287200, 0x15bf420, 0xc0b6cd5340, 0xc0961d1d00)
2019-07-31T09:02:04.293981+02:00 monitoring influxdb: /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:392 +0x247
2019-07-31T09:02:04.294279+02:00 monitoring influxdb: net/http.serverHandler.ServeHTTP(0xc16c72f930, 0x15bf420, 0xc0b6cd5340, 0xc0961d1d00)
2019-07-31T09:02:04.294550+02:00 monitoring influxdb: /usr/local/go/src/net/http/server.go:2741 +0xab
2019-07-31T09:02:04.294809+02:00 monitoring influxdb: net/http.(*conn).serve(0xc0711b6a00, 0x15c0f60, 0xc0c798c740)
2019-07-31T09:02:04.295061+02:00 monitoring influxdb: /usr/local/go/src/net/http/server.go:1847 +0x646
2019-07-31T09:02:04.295336+02:00 monitoring influxdb: created by net/http.(*Server).Serve
2019-07-31T09:02:04.295580+02:00 monitoring influxdb: /usr/local/go/src/net/http/server.go:2851 +0x2f5
```
