### ISSUE TITLE
[pvt-spec] panic on control.Query.pump in e2e tests

### ISSUE THREAD

**Issue by wolffcm** [influxdata/influxdb#13321]
Running tests in `influxdb refactor/private-spec`, I see this failure mode in the end to end tests:
```
$ go test -run TestFluxEndToEnd ./query/stdlib/testing
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1714a02]

goroutine 4683 [running]:
github.com/influxdata/flux/control.(*Query).pump(0xc00022e140, 0x27f4080, 0xc0001ff300)
	/Users/cwolff/go/pkg/mod/github.com/influxdata/flux@v0.23.1-0.20190410205636-00b899c91516/control/controller.go:543 +0x182
created by github.com/influxdata/flux/control.(*Controller).enqueueQuery
	/Users/cwolff/go/pkg/mod/github.com/influxdata/flux@v0.23.1-0.20190410205636-00b899c91516/control/controller.go:225 +0x114
FAIL	github.com/influxdata/influxdb/query/stdlib/testing	6.098s
```

**Comment by jsternberg** [comment]
Fixed by influxdata/flux#1154.
