### ISSUE TITLE
Segfault in TSI go test

### ISSUE THREAD

**Issue by rbetts** [influxdata/influxdb#13704]
```
CI failure: from this morning's tip of master (78551472418216d3da4cf32cc01376c4724d6790), this will eventually segv or timeout: GOTRACEBACK=all GO111MODULE=on go test -failfast -count=10 -v -race ./tsdb/...
```

```
--- PASS: TestIndex_CompactionConsistency (10.21s)
    <autogenerated>:1: 2019-04-29T15:47:55.635-0400     INFO    Index opened    {"index": "tsi", "partitions": 8}
    index_test.go:480: expect 183 measurements after 301 operations

...

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1841414]

goroutine 27484 [running]:
github.com/influxdata/influxdb/tsdb/tsi1.(*FileSet).Duplicate(0x0, 0x182a0cb, 0xc0008f43c0, 0x8e)
        /Users/rbetts/work/influxdb2x/src/github.com/influxdata/influxdb/tsdb/tsi1/file_set.go:74 +0x34
github.com/influxdata/influxdb/tsdb/tsi1.(*Partition).compact(0xc000115040)
        /Users/rbetts/work/influxdb2x/src/github.com/influxdata/influxdb/tsdb/tsi1/partition.go:921 +0x95
github.com/influxdata/influxdb/tsdb/tsi1.(*Partition).Compact(0xc000115040)
        /Users/rbetts/work/influxdb2x/src/github.com/influxdata/influxdb/tsdb/tsi1/partition.go:891 +0x73
github.com/influxdata/influxdb/tsdb/tsi1.(*Partition).compact.func1(0xc000115040, 0xc008aea470, 0x2, 0x2, 0xc008aea480, 0x2, 0x2, 0xc00b26e6c0, 0x2)
        /Users/rbetts/work/influxdb2x/src/github.com/influxdata/influxdb/tsdb/tsi1/partition.go:980 +0x194
created by github.com/influxdata/influxdb/tsdb/tsi1.(*Partition).compact
        /Users/rbetts/work/influxdb2x/src/github.com/influxdata/influxdb/tsdb/tsi1/partition.go:965 +0x632

goroutine 1 [chan receive, 1 minutes]:
testing.tRunner.func1(0xc0001b6100)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:803 +0x2e4
testing.tRunner(0xc0001b6100, 0xc0001d7d88)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:831 +0x17f
testing.runTests(0xc0001801a0, 0x207d4c0, 0x2b, 0x2b, 0xc0000f7e30)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:1117 +0x4ef
testing.(*M).Run(0xc0001b2000, 0x0)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:1034 +0x2ef
main.main()
        _testmain.go:158 +0x222

goroutine 19 [syscall, 2 minutes]:
os/signal.signal_recv(0x1096b11)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/runtime/sigqueue.go:139 +0x9f
os/signal.loop()
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/os/signal/signal_unix.go:23 +0x30
created by os/signal.init.0
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/os/signal/signal_unix.go:29 +0x4f

goroutine 14655 [chan send, 1 minutes]:
testing.tRunner.func1(0xc0001cc400)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:822 +0x3b9
testing.tRunner(0xc0001cc400, 0x1a556e8)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:831 +0x17f
created by testing.(*T).Run
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:878 +0x65a

goroutine 14634 [chan send, 1 minutes]:
testing.tRunner.func1(0xc0001b6200)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:822 +0x3b9
testing.tRunner(0xc0001b6200, 0x1a556f0)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:831 +0x17f
created by testing.(*T).Run
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:878 +0x65a

goroutine 15059 [runnable]:
syscall.Syscall(0x49, 0x38a86000, 0x400000, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/syscall/asm_darwin_amd64.s:16 +0x5
syscall.munmap(0x38a86000, 0x400000, 0x38e85fff, 0xc0004045e0)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/syscall/zsyscall_darwin_amd64.go:1343 +0x59
syscall.(*mmapper).Munmap(0x2077520, 0x38a86000, 0x400000, 0x400000, 0x0, 0x0)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/syscall/syscall_unix.go:97 +0x1b9
syscall.Munmap(0x38a86000, 0x400000, 0x400000, 0x0, 0xc0004ce260)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/syscall/syscall_bsd.go:553 +0x6d
github.com/influxdata/influxdb/pkg/mmap.Unmap(0x38a86000, 0x400000, 0x400000, 0x1063e92, 0x8)
        /Users/rbetts/work/influxdb2x/src/github.com/influxdata/influxdb/pkg/mmap/mmap_unix.go:48 +0x56
github.com/influxdata/influxdb/tsdb.(*SeriesSegment).Close(0xc0004ce230, 0x1a56738, 0xc0008f4480)
        /Users/rbetts/work/influxdb2x/src/github.com/influxdata/influxdb/tsdb/series_segment.go:145 +0xe8
github.com/influxdata/influxdb/tsdb.(*SeriesPartition).Close(0xc0008f4480, 0x0, 0x0)
        /Users/rbetts/work/influxdb2x/src/github.com/influxdata/influxdb/tsdb/series_partition.go:159 +0x143
github.com/influxdata/influxdb/tsdb.(*SeriesFile).Close(0xc000248120, 0x0, 0x0)
        /Users/rbetts/work/influxdb2x/src/github.com/influxdata/influxdb/tsdb/series_file.go:170 +0xf1
github.com/influxdata/influxdb/tsdb/tsi1_test.(*SeriesFile).Reopen(0xc0000aa210, 0x0, 0x0)
        /Users/rbetts/work/influxdb2x/src/github.com/influxdata/influxdb/tsdb/tsi1/tsi1_test.go:318 +0x50
github.com/influxdata/influxdb/tsdb/tsi1_test.(*Index).Reopen(0xc000154180, 0xc00c000b10, 0x19f8880)
        /Users/rbetts/work/influxdb2x/src/github.com/influxdata/influxdb/tsdb/tsi1/index_test.go:588 +0xac
github.com/influxdata/influxdb/tsdb/tsi1_test.TestIndex_MeasurementCardinalityStats.func4(0xc0001b6400)
        /Users/rbetts/work/influxdb2x/src/github.com/influxdata/influxdb/tsdb/tsi1/index_test.go:410 +0x5ed
testing.tRunner(0xc0001b6400, 0x1a556c0)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:827 +0x163
created by testing.(*T).Run
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:878 +0x65a

goroutine 14654 [chan send, 1 minutes]:
testing.tRunner.func1(0xc0001cc300)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:822 +0x3b9
testing.tRunner(0xc0001cc300, 0x1a55678)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:831 +0x17f
created by testing.(*T).Run
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:878 +0x65a

goroutine 14635 [chan send, 1 minutes]:
testing.tRunner.func1(0xc0001b6300)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:822 +0x3b9
testing.tRunner(0xc0001b6300, 0x1a55708)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:831 +0x17f
created by testing.(*T).Run
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:878 +0x65a

goroutine 14653 [chan receive, 1 minutes]:
testing.(*T).Run(0xc0001cc200, 0x1a33a58, 0x5, 0x1a556c0, 0x1)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:879 +0x692
github.com/influxdata/influxdb/tsdb/tsi1_test.TestIndex_MeasurementCardinalityStats(0xc0001cc200)
        /Users/rbetts/work/influxdb2x/src/github.com/influxdata/influxdb/tsdb/tsi1/index_test.go:388 +0xf9
testing.tRunner(0xc0001cc200, 0x1a556c8)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:827 +0x163
created by testing.(*T).Run
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:878 +0x65a

goroutine 14588 [chan receive, 1 minutes]:
testing.runTests.func1.1(0xc0001b6100)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:1124 +0x60
created by testing.runTests.func1
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:1124 +0xdd

goroutine 14656 [chan send, 1 minutes]:
testing.tRunner.func1(0xc0001cc500)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:822 +0x3b9
testing.tRunner(0xc0001cc500, 0x1a55710)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:831 +0x17f
created by testing.(*T).Run
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:878 +0x65a
FAIL    github.com/influxdata/influxdb/tsdb/tsi1        163.572s
```

**Comment by rbetts** [comment]
A second reproduction - since I have it anyway:

```
--- PASS: TestIndex_CompactionConsistency (10.16s)
    <autogenerated>:1: 2019-04-29T17:10:37.216-0400     INFO    Index opened    {"index": "tsi", "partitions": 8}
    index_test.go:480: expect 186 measurements after 298 operations
    index_test.go:482: add: m7390804634012037242

...

panic:  runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1841414]

goroutine 27489 [running]:
github.com/influxdata/influxdb/tsdb/tsi1.(*FileSet).Duplicate(0x0, 0x182a0cb, 0xc006f7d5c0, 0x81)
        /Users/rbetts/work/influxdb2x/src/github.com/influxdata/influxdb/tsdb/tsi1/file_set.go:74 +0x34
github.com/influxdata/influxdb/tsdb/tsi1.(*Partition).compact(0xc0076d0140)
        /Users/rbetts/work/influxdb2x/src/github.com/influxdata/influxdb/tsdb/tsi1/partition.go:921 +0x95
github.com/influxdata/influxdb/tsdb/tsi1.(*Partition).Compact(0xc0076d0140)
        /Users/rbetts/work/influxdb2x/src/github.com/influxdata/influxdb/tsdb/tsi1/partition.go:891 +0x73
github.com/influxdata/influxdb/tsdb/tsi1.(*Partition).compact.func1(0xc0076d0140, 0xc0024ec1f0, 0x2, 0x2, 0xc0024ec200, 0x2, 0x2, 0xc00232e5a0, 0x2)
        /Users/rbetts/work/influxdb2x/src/github.com/influxdata/influxdb/tsdb/tsi1/partition.go:980 +0x194
created by github.com/influxdata/influxdb/tsdb/tsi1.(*Partition).compact
        /Users/rbetts/work/influxdb2x/src/github.com/influxdata/influxdb/tsdb/tsi1/partition.go:965 +0x632

goroutine 1 [chan receive, 1 minutes]:
testing.tRunner.func1(0xc000138400)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:803 +0x2e4
testing.tRunner(0xc000138400, 0xc0000bbd88)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:831 +0x17f
testing.runTests(0xc00000c1e0, 0x207d4c0, 0x2b, 0x2b, 0xc0000f1e30)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:1117 +0x4ef
testing.(*M).Run(0xc0001a0000, 0x0)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:1034 +0x2ef
main.main()
        _testmain.go:158 +0x222

goroutine 19 [syscall, 2 minutes]:
os/signal.signal_recv(0x1096b11)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/runtime/sigqueue.go:139 +0x9f
os/signal.loop()
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/os/signal/signal_unix.go:23 +0x30
created by os/signal.init.0
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/os/signal/signal_unix.go:29 +0x4f

goroutine 14144 [chan send, 1 minutes]:
testing.tRunner.func1(0xc000139c00)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:822 +0x3b9
testing.tRunner(0xc000139c00, 0x1a55678)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:831 +0x17f
created by testing.(*T).Run
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:878 +0x65a

goroutine 14145 [chan send, 1 minutes]:
testing.tRunner.func1(0xc000139d00)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:822 +0x3b9
testing.tRunner(0xc000139d00, 0x1a556e8)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:831 +0x17f
created by testing.(*T).Run
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:878 +0x65a

goroutine 14194 [chan send, 1 minutes]:
testing.tRunner.func1(0xc000139e00)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:822 +0x3b9
testing.tRunner(0xc000139e00, 0x1a55710)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:831 +0x17f
created by testing.(*T).Run
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:878 +0x65a

goroutine 14143 [chan receive, 1 minutes]:
testing.(*T).Run(0xc000139b00, 0x1a33a58, 0x5, 0x1a556c0, 0x1)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:879 +0x692
github.com/influxdata/influxdb/tsdb/tsi1_test.TestIndex_MeasurementCardinalityStats(0xc000139b00)
        /Users/rbetts/work/influxdb2x/src/github.com/influxdata/influxdb/tsdb/tsi1/index_test.go:388 +0xf9
testing.tRunner(0xc000139b00, 0x1a556c8)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:827 +0x163
created by testing.(*T).Run
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:878 +0x65a

goroutine 14193 [chan receive, 1 minutes]:
testing.runTests.func1.1(0xc000138400)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:1124 +0x60
created by testing.runTests.func1
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:1124 +0xdd

goroutine 14196 [chan send, 1 minutes]:
testing.tRunner.func1(0xc006996000)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:822 +0x3b9
testing.tRunner(0xc006996000, 0x1a55708)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:831 +0x17f
created by testing.(*T).Run
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:878 +0x65a

goroutine 14638 [runnable]:
github.com/influxdata/influxdb/tsdb.(*SeriesIndex).execEntry(0xc002504000, 0x1, 0x8000000000007229, 0x1ee6e, 0x29a5ce77, 0x1a, 0x3e1189)
        /Users/rbetts/work/influxdb2x/src/github.com/influxdata/influxdb/tsdb/series_index.go:210 +0x171
github.com/influxdata/influxdb/tsdb.(*SeriesIndex).Recover.func1(0xc002c76101, 0x8000000000007229, 0x1ee6e, 0x29a5ce77, 0x1a, 0x3e1189, 0x1a, 0x3e1189)
        /Users/rbetts/work/influxdb2x/src/github.com/influxdata/influxdb/tsdb/series_index.go:149 +0xc0
github.com/influxdata/influxdb/tsdb.(*SeriesSegment).ForEachEntry(0xc002c761e0, 0xc0150b5af0, 0x1, 0xc0001900f0)
        /Users/rbetts/work/influxdb2x/src/github.com/influxdata/influxdb/tsdb/series_segment.go:246 +0x19e
github.com/influxdata/influxdb/tsdb.(*SeriesIndex).Recover(0xc002504000, 0xc010fb8410, 0x2, 0x2, 0x800001ed00092270, 0xc0150b5be8)
        /Users/rbetts/work/influxdb2x/src/github.com/influxdata/influxdb/tsdb/series_index.go:145 +0x315
github.com/influxdata/influxdb/tsdb.(*SeriesPartition).Open.func1(0xc003ce60c0, 0x4e, 0x1ff)
        /Users/rbetts/work/influxdb2x/src/github.com/influxdata/influxdb/tsdb/series_partition.go:93 +0x18c
github.com/influxdata/influxdb/tsdb.(*SeriesPartition).Open(0xc003ce60c0, 0xc010becb00, 0x1a3a90a)
        /Users/rbetts/work/influxdb2x/src/github.com/influxdata/influxdb/tsdb/series_partition.go:97 +0x199
github.com/influxdata/influxdb/tsdb.(*SeriesFile).Open(0xc000136240, 0x1b245a0, 0xc000096008, 0x0, 0x0)
        /Users/rbetts/work/influxdb2x/src/github.com/influxdata/influxdb/tsdb/series_file.go:148 +0x9ff
github.com/influxdata/influxdb/tsdb/tsi1_test.Index.Open(0xc003ac8000, 0x100000, 0x3e8, 0xc0050f4628, 0x1, 0x1)
        /Users/rbetts/work/influxdb2x/src/github.com/influxdata/influxdb/tsdb/tsi1/index_test.go:565 +0x82
github.com/influxdata/influxdb/tsdb/tsi1_test.(*Index).Reopen(0xc006e5f560, 0xc003ee55f0, 0x19f8880)
        /Users/rbetts/work/influxdb2x/src/github.com/influxdata/influxdb/tsdb/tsi1/index_test.go:595 +0x315
github.com/influxdata/influxdb/tsdb/tsi1_test.TestIndex_MeasurementCardinalityStats.func4(0xc006996b00)
        /Users/rbetts/work/influxdb2x/src/github.com/influxdata/influxdb/tsdb/tsi1/index_test.go:410 +0x5ed
testing.tRunner(0xc006996b00, 0x1a556c0)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:827 +0x163
created by testing.(*T).Run
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:878 +0x65a

goroutine 14195 [chan send, 1 minutes]:
testing.tRunner.func1(0xc000139f00)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:822 +0x3b9
testing.tRunner(0xc000139f00, 0x1a556f0)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:831 +0x17f
created by testing.(*T).Run
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:878 +0x65a
FAIL    github.com/influxdata/influxdb/tsdb/tsi1        156.629s
```

**Comment by benbjohnson** [comment]
Looks like there's something funny in the stats test. The second repro has an unmap.

```
goroutine 15059 [runnable]:
syscall.Syscall(0x49, 0x38a86000, 0x400000, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/syscall/asm_darwin_amd64.s:16 +0x5
syscall.munmap(0x38a86000, 0x400000, 0x38e85fff, 0xc0004045e0)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/syscall/zsyscall_darwin_amd64.go:1343 +0x59
syscall.(*mmapper).Munmap(0x2077520, 0x38a86000, 0x400000, 0x400000, 0x0, 0x0)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/syscall/syscall_unix.go:97 +0x1b9
syscall.Munmap(0x38a86000, 0x400000, 0x400000, 0x0, 0xc0004ce260)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/syscall/syscall_bsd.go:553 +0x6d
github.com/influxdata/influxdb/pkg/mmap.Unmap(0x38a86000, 0x400000, 0x400000, 0x1063e92, 0x8)
        /Users/rbetts/work/influxdb2x/src/github.com/influxdata/influxdb/pkg/mmap/mmap_unix.go:48 +0x56
github.com/influxdata/influxdb/tsdb.(*SeriesSegment).Close(0xc0004ce230, 0x1a56738, 0xc0008f4480)
        /Users/rbetts/work/influxdb2x/src/github.com/influxdata/influxdb/tsdb/series_segment.go:145 +0xe8
github.com/influxdata/influxdb/tsdb.(*SeriesPartition).Close(0xc0008f4480, 0x0, 0x0)
        /Users/rbetts/work/influxdb2x/src/github.com/influxdata/influxdb/tsdb/series_partition.go:159 +0x143
github.com/influxdata/influxdb/tsdb.(*SeriesFile).Close(0xc000248120, 0x0, 0x0)
        /Users/rbetts/work/influxdb2x/src/github.com/influxdata/influxdb/tsdb/series_file.go:170 +0xf1
github.com/influxdata/influxdb/tsdb/tsi1_test.(*SeriesFile).Reopen(0xc0000aa210, 0x0, 0x0)
        /Users/rbetts/work/influxdb2x/src/github.com/influxdata/influxdb/tsdb/tsi1/tsi1_test.go:318 +0x50
github.com/influxdata/influxdb/tsdb/tsi1_test.(*Index).Reopen(0xc000154180, 0xc00c000b10, 0x19f8880)
        /Users/rbetts/work/influxdb2x/src/github.com/influxdata/influxdb/tsdb/tsi1/index_test.go:588 +0xac
github.com/influxdata/influxdb/tsdb/tsi1_test.TestIndex_MeasurementCardinalityStats.func4(0xc0001b6400)
        /Users/rbetts/work/influxdb2x/src/github.com/influxdata/influxdb/tsdb/tsi1/index_test.go:410 +0x5ed
testing.tRunner(0xc0001b6400, 0x1a556c0)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:827 +0x163
created by testing.(*T).Run
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/testing/testing.go:878 +0x65a
```
