### ISSUE TITLE
Storage panic via flux query

### ISSUE THREAD

**Issue by jacobmarble** [influxdata/influxdb#13821]
Caught this in a Chronograf dashboard. NPE in `reads.(*groupByMergedGroupResultSet).Close()`

```
Error: panic: runtime error: invalid memory address or nil pointer dereference
goroutine 1525179542 [running]:
runtime/debug.Stack(0x124b880, 0x1238180, 0x1f563b0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/influxdata/plutonium/vendor/github.com/influxdata/flux/execute.(*executionState).do.func1.1(0xc71085ca80)
	/go/src/github.com/influxdata/plutonium/vendor/github.com/influxdata/flux/execute/executor.go:269 +0xbc
panic(0x1238180, 0x1f563b0)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/storage/reads.(*groupByMergedGroupResultSet).Close(0xc7b8cf2200)
	/go/src/github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/storage/reads/mergegroupresultset.go:199 +0x59
github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/storage/reads.(*tableIterator).handleGroupRead.func1(0xc622bcdcb8, 0xc622bcdcd8, 0xc622bcdcc8, 0x16da920, 0xc7b8cf2200)
	/go/src/github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/storage/reads/reader.go:267 +0x68
panic(0x1238180, 0x1f563b0)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/storage/reads.(*groupByMergedGroupResultSet).next(0xc7b8cf2200)
	/go/src/github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/storage/reads/mergegroupresultset.go:131 +0x9f
github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/storage/reads.(*groupByMergedGroupResultSet).Next(0xc7b8cf2200, 0x15fdc98, 0xc622bcdcb8)
	/go/src/github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/storage/reads/mergegroupresultset.go:179 +0x2f
github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/storage/reads.(*tableIterator).handleGroupRead(0xc63ca503c0, 0xc443a8b870, 0x16da920, 0xc7b8cf2200, 0x0, 0x0)
	/go/src/github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/storage/reads/reader.go:270 +0xd0
github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/storage/reads.(*tableIterator).Do(0xc63ca503c0, 0xc443a8b870, 0xc72b1cf1a0, 0x16c45e0)
	/go/src/github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/storage/reads/reader.go:116 +0x2ff
github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/flux/stdlib/influxdata/influxdb.(*source).run(0xc5fcf25320, 0x16deb20, 0xc72b1cf1a0, 0xc6fc1d0960, 0xc4ac5aaf58)
	/go/src/github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/flux/stdlib/influxdata/influxdb/storage.go:56 +0x176
github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/flux/stdlib/influxdata/influxdb.(*source).Run(0xc5fcf25320, 0x16deb20, 0xc72b1cf1a0)
	/go/src/github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/flux/stdlib/influxdata/influxdb/storage.go:47 +0x43
github.com/influxdata/plutonium/vendor/github.com/influxdata/flux/execute.(*executionState).do.func1(0xc48934c5c0, 0xc71085ca80, 0x16deb20, 0xc72b1cf1a0, 0x16ccc60, 0xc5fcf25320)
	/go/src/github.com/influxdata/plutonium/vendor/github.com/influxdata/flux/execute/executor.go:276 +0x9d
created by github.com/influxdata/plutonium/vendor/github.com/influxdata/flux/execute.(*executionState).do
	/go/src/github.com/influxdata/plutonium/vendor/github.com/influxdata/flux/execute/executor.go:255 +0xe1
```

**Comment by jacobmarble** [comment]
This is what the user sees in Chronograf:
![Screen Shot 2019-05-07 at 9 10 05 AM](https://user-images.githubusercontent.com/622263/57333215-34ee0280-70d1-11e9-9abf-3290f803c00c.png)

**Comment by russorat** [comment]
fixed
