### ISSUE TITLE
InfluxDB restarts with status=2/INVALIDARGUMENT every 5 minutes

### ISSUE THREAD

**Issue by lordofda** [influxdata/influxdb#13891]
Hi,
I have small instalation on raspberry pi 3 consisting od TICK stack with Grafana and Domoticz. The data comes from both local and remote sites (mostly environmental data from domoticz and PC stats from Telegraf and OpenHardwareMonitor). I recently migrated from raspberry pi 2 with a years worth of data and the system worked for around a week or two on fresh instalation and then suddenly it started to break, grafana showed 502 errors. 

Then it loads shards again and then crashes and restarts again. I am just a hobbist, but if you can spare some time please give me pointers as to where to look for the source of this

__Steps to reproduce:__

I don't know, it just happened in the middle of the night, I have no idea why

__Expected behavior:__

Being able to query and write to influxdb, not restarting all the time

__Actual behavior:__
When refreshing grafana it shows 502 errors on 99 in 100 tries, sometimes I am able to see graphs. The same is with command "influx" in terminal. Sometimes I am able to enter it, but then "show databases" doesn't work, shows "connection refused". Domoticz log regularly shows error on write to influx, but some data manages to get through.

__Environment info:__

$ uname -srm
Linux 4.14.98-v7+ armv7l
$ influxd version
InfluxDB v1.7.6 (git: 1.7 01c8dd416270f424ab0c40f9291e269ac6921964)

__Config:__
Config is standard. I tried adding 
[coordinator]
   write-timeout = "10s"
   max-concurrent-queries = 10
   query-timeout = "30s"
After reading some other closed issues on github, but it did not help

__Logs:__
While looking for answers I found this output

journalctl -xe -u influxdb

```
May 12 10:59:20 CentralUnit influxd[11533]: goroutine 1744 [chan receive]:
May 12 10:59:20 CentralUnit influxd[11533]: github.com/influxdata/influxdb/services/subscriber.chanWriter.Run(0x18aab140, 0xf69dd0, 0xe2a2180, 0x426b0a8, 0x426b0b0, 0x3efda10)
May 12 10:59:20 CentralUnit influxd[11533]:         /go/src/github.com/influxdata/influxdb/services/subscriber/service.go:372 +0x38
May 12 10:59:20 CentralUnit influxd[11533]: github.com/influxdata/influxdb/services/subscriber.(*Service).updateSubs.func1(0x9f87370, 0x18aab140, 0xf69dd0, 0xe2a2180, 0x426b0a8, 0x426b0b0, 0x3efda10)
May 12 10:59:20 CentralUnit influxd[11533]:         /go/src/github.com/influxdata/influxdb/services/subscriber/service.go:314 +0x44
May 12 10:59:20 CentralUnit influxd[11533]: created by github.com/influxdata/influxdb/services/subscriber.(*Service).updateSubs
May 12 10:59:20 CentralUnit systemd[1]: influxdb.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 12 10:59:20 CentralUnit systemd[1]: influxdb.service: Unit entered failed state.
May 12 10:59:20 CentralUnit systemd[1]: influxdb.service: Failed with result 'exit-code'.
May 12 10:59:20 CentralUnit systemd[1]: influxdb.service: Service hold-off time over, scheduling restart.
May 12 10:59:20 CentralUnit systemd[1]: Stopped InfluxDB is an open-source, distributed, time series database.
-- Subject: Unit influxdb.service has finished shutting down
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit influxdb.service has finished shutting down.
May 12 10:59:20 CentralUnit systemd[1]: Started InfluxDB is an open-source, distributed, time series database.
-- Subject: Unit influxdb.service has finished start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit influxdb.service has finished starting up.
```
__Performance:__
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 8086: Connection refused
curl -o vars.txt "http://localhost:8086/debug/vars"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
iostat -xd 1 30 > iostat.txt
-bash: iostat: command not found

Thank you in advance for any help :)

**Comment by lordofda** [comment]
Fixed by deleting data and reinstalling Influxdb. Probably old data was corrupted in some way
