### ISSUE TITLE
panic when load data into influxdb

### ISSUE THREAD

**Issue by lanyaye** [influxdata/influxdb#14055]
Hi,
Current I'm running InfluxDB v1.7.6 on centos 7.
And I launch a script to load data into measurement 'snap' in database 'stock'. the batch number is 10000.
I have load data for several hours and there's no issues. but at last it generate the panic.
Note: after panic I reload the batch data which generate the panic into influxdb again and it's OK, the panic is not shown and the data is successfully loaded into InfluxDB. so I believe it will not be our data's issue.
 
now I have resumed the script to continue load rest data. but I'm worried after some hours it may generate panic again. 

I have attached the journalctl log here for the panic. if the panic can be resolved that will be great help. sine we will load data for three days and does not want it  broken again.

```
Jun 04 14:30:00 ds24 influxd[3167]: [httpd] 192.168.0.24 - writer [04/Jun/2019:14:29:59 +0800] "POST /write?db=stock&p=%5BREDACTED%5D&precision=ns&rp=stock&u=writer HTTP/1.1" 204 0 "-" "-" 2d912933-8692-11e9-bf27-000f5327cab0 695288
Jun 04 14:30:00 ds24 influxd[3167]: ts=2019-06-04T06:30:00.992838Z lvl=info msg="Snapshot for path written" log_id=0FUMfFjl000 engine=tsm1 trace_id=0FpIj6ql000 op_name=tsm1_cache_snapshot path=/home/influxdb/var/lib/influxdb/data/stock/stock/28 duration=841.815ms
Jun 04 14:30:00 ds24 influxd[3167]: ts=2019-06-04T06:30:00.992868Z lvl=info msg="Cache snapshot (end)" log_id=0FUMfFjl000 engine=tsm1 trace_id=0FpIj6ql000 op_name=tsm1_cache_snapshot op_event=end op_elapsed=841.844ms
Jun 04 14:30:01 ds24 influxd[3167]: fatal error: unexpected signal during runtime execution
Jun 04 14:30:01 ds24 influxd[3167]: [signal SIGFPE: floating-point exception code=0x1 addr=0x4171aa pc=0x4171aa]
Jun 04 14:30:01 ds24 influxd[3167]: goroutine 30320839 [running]:
Jun 04 14:30:01 ds24 influxd[3167]: runtime.throw(0x12f560e, 0x2a)
Jun 04 14:30:01 ds24 influxd[3167]: /usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc05972f6d0 sp=0xc05972f6a0 pc=0x42df92
Jun 04 14:30:01 ds24 influxd[3167]: runtime.sigpanic()
Jun 04 14:30:01 ds24 influxd[3167]: /usr/local/go/src/runtime/signal_unix.go:374 +0x2f2 fp=0xc05972f720 sp=0xc05972f6d0 pc=0x4438c2
Jun 04 14:30:01 ds24 influxd[3167]: runtime.heapBitsSetType(0xc00e305e60, 0x20, 0x20, 0x11741c0)
Jun 04 14:30:01 ds24 influxd[3167]: /usr/local/go/src/runtime/mbitmap.go:1150 +0x7ca fp=0xc05972f7f8 sp=0xc05972f720 pc=0x4171aa
Jun 04 14:30:01 ds24 influxd[3167]: runtime.mallocgc(0x20, 0x11741c0, 0x1, 0xd60000c05972f8f0)
Jun 04 14:30:01 ds24 influxd[3167]: /usr/local/go/src/runtime/malloc.go:933 +0x540 fp=0xc05972f898 sp=0xc05972f7f8 pc=0x40dba0
Jun 04 14:30:01 ds24 influxd[3167]: runtime.growslice(0x11741c0, 0xc011691d10, 0x1, 0x1, 0x2, 0x4, 0x0, 0x2)
Jun 04 14:30:01 ds24 influxd[3167]: /usr/local/go/src/runtime/slice.go:204 +0x145 fp=0xc05972f900 sp=0xc05972f898 pc=0x444ad5
Jun 04 14:30:01 ds24 influxd[3167]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).WritePoints(0xc0000c4480, 0xc089790000, 0x2710, 0x2710, 0x0, 0x0)
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1340 +0x529 fp=0xc05972faa8 sp=0xc05972f900 pc=0xf71ad9
Jun 04 14:30:01 ds24 influxd[3167]: github.com/influxdata/influxdb/tsdb.(*Shard).WritePoints(0xc005f72fc0, 0xc089790000, 0x2710, 0x2710, 0x0, 0x0)
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/tsdb/shard.go:525 +0x201 fp=0xc05972fb50 sp=0xc05972faa8 pc=0x9b7c81
Jun 04 14:30:01 ds24 influxd[3167]: github.com/influxdata/influxdb/tsdb.(*Store).WriteToShard(0xc000154800, 0x1c, 0xc089790000, 0x2710, 0x2710, 0x0, 0x0)
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/tsdb/store.go:1410 +0x207 fp=0xc05972fbc0 sp=0xc05972fb50 pc=0x9cd197
Jun 04 14:30:01 ds24 influxd[3167]: github.com/influxdata/influxdb/coordinator.(*PointsWriter).writeToShard(0xc000181000, 0xc050a591e0, 0xc048d2d04f, 0x5, 0xc048d2d081, 0x5, 0xc089790000, 0x2710, 0x2710, 0x1b, ...)
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/coordinator/points_writer.go:370 +0x92 fp=0xc05972fec8 sp=0xc05972fbc0 pc=0xa79012
Jun 04 14:30:01 ds24 influxd[3167]: github.com/influxdata/influxdb/coordinator.(*PointsWriter).WritePointsPrivileged.func1(0xc000181000, 0xc04fe801e0, 0xc050a591e0, 0xc048d2d04f, 0x5, 0xc048d2d081, 0x5, 0xc089790000, 0x2710, 0x2710)
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/coordinator/points_writer.go:312 +0xa8 fp=0xc05972ff90 sp=0xc05972fec8 pc=0xa89298
Jun 04 14:30:01 ds24 influxd[3167]: runtime.goexit()
Jun 04 14:30:01 ds24 influxd[3167]: /usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc05972ff98 sp=0xc05972ff90 pc=0x45d971
Jun 04 14:30:01 ds24 influxd[3167]: created by github.com/influxdata/influxdb/coordinator.(*PointsWriter).WritePointsPrivileged
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/coordinator/points_writer.go:311 +0x2bb
Jun 04 14:30:01 ds24 influxd[3167]: goroutine 1 [chan receive, 24534 minutes]:
Jun 04 14:30:01 ds24 influxd[3167]: main.(*Main).Run(0xc0004d3f58, 0xc00003a0a0, 0x2, 0x2, 0xc0004d3f68, 0xfd84e6)
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/cmd/influxd/main.go:90 +0x2d1
Jun 04 14:30:01 ds24 influxd[3167]: main.main()
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/cmd/influxd/main.go:45 +0x12f
Jun 04 14:30:01 ds24 influxd[3167]: goroutine 5 [syscall, 24537 minutes]:
Jun 04 14:30:01 ds24 influxd[3167]: os/signal.signal_recv(0x0)
Jun 04 14:30:01 ds24 influxd[3167]: /usr/local/go/src/runtime/sigqueue.go:139 +0x9c
Jun 04 14:30:01 ds24 influxd[3167]: os/signal.loop()
Jun 04 14:30:01 ds24 influxd[3167]: /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
Jun 04 14:30:01 ds24 influxd[3167]: created by os/signal.init.0
Jun 04 14:30:01 ds24 influxd[3167]: /usr/local/go/src/os/signal/signal_unix.go:29 +0x41
Jun 04 14:30:01 ds24 influxd[3167]: goroutine 8 [IO wait, 24537 minutes]:
Jun 04 14:30:01 ds24 influxd[3167]: internal/poll.runtime_pollWait(0x7f596ef3af00, 0x72, 0x0)
Jun 04 14:30:01 ds24 influxd[3167]: /usr/local/go/src/runtime/netpoll.go:173 +0x66
Jun 04 14:30:01 ds24 influxd[3167]: internal/poll.(*pollDesc).wait(0xc000181098, 0x72, 0xc00016a000, 0x0, 0x0)
Jun 04 14:30:01 ds24 influxd[3167]: /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
Jun 04 14:30:01 ds24 influxd[3167]: internal/poll.(*pollDesc).waitRead(0xc000181098, 0xffffffffffffff00, 0x0, 0x0)
Jun 04 14:30:01 ds24 influxd[3167]: /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
Jun 04 14:30:01 ds24 influxd[3167]: internal/poll.(*FD).Accept(0xc000181080, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
Jun 04 14:30:01 ds24 influxd[3167]: /usr/local/go/src/internal/poll/fd_unix.go:384 +0x1a0
Jun 04 14:30:01 ds24 influxd[3167]: net.(*netFD).accept(0xc000181080, 0x0, 0x0, 0x0)
Jun 04 14:30:01 ds24 influxd[3167]: /usr/local/go/src/net/fd_unix.go:238 +0x42
Jun 04 14:30:01 ds24 influxd[3167]: net.(*TCPListener).accept(0xc00000e9d8, 0x47ba3e, 0xc000592ae0, 0x47b96d)
Jun 04 14:30:01 ds24 influxd[3167]: /usr/local/go/src/net/tcpsock_posix.go:139 +0x2e
Jun 04 14:30:01 ds24 influxd[3167]: net.(*TCPListener).Accept(0xc00000e9d8, 0x0, 0x0, 0x0, 0x0)
Jun 04 14:30:01 ds24 influxd[3167]: /usr/local/go/src/net/tcpsock.go:260 +0x47
Jun 04 14:30:01 ds24 influxd[3167]: github.com/influxdata/influxdb/tcp.(*Mux).Serve(0xc000592ae0, 0x15bf1a0, 0xc00000e9d8, 0xc00000e9d8, 0x0)
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/tcp/mux.go:75 +0x92
Jun 04 14:30:01 ds24 influxd[3167]: created by github.com/influxdata/influxdb/cmd/influxd/run.(*Server).Open
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/cmd/influxd/run/server.go:387 +0x28b
Jun 04 14:30:01 ds24 influxd[3167]: goroutine 9 [select, 24537 minutes]:
Jun 04 14:30:01 ds24 influxd[3167]: github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/control.(*Controller).run(0xc0002b8a80)
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/control/controller.go:307 +0x21f
Jun 04 14:30:01 ds24 influxd[3167]: created by github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/control.New
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/control/controller.go:107 +0x4a6
Jun 04 14:30:01 ds24 influxd[3167]: goroutine 3748 [select]:
Jun 04 14:30:01 ds24 influxd[3167]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).compactCache(0xc00052c000)
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1920 +0x11b
Jun 04 14:30:01 ds24 influxd[3167]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).enableSnapshotCompactions.func1(0xc004ef2930, 0xc00052c000)
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:499 +0x51
Jun 04 14:30:01 ds24 influxd[3167]: created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).enableSnapshotCompactions
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:499 +0x124
Jun 04 14:30:01 ds24 influxd[3167]: goroutine 3802 [select]:
Jun 04 14:30:01 ds24 influxd[3167]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).compactCache(0xc000428120)
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1920 +0x11b
Jun 04 14:30:01 ds24 influxd[3167]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).enableSnapshotCompactions.func1(0xc004ef2b90, 0xc000428120)
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:499 +0x51
Jun 04 14:30:01 ds24 influxd[3167]: created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).enableSnapshotCompactions
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:499 +0x124
Jun 04 14:30:01 ds24 influxd[3167]: goroutine 3799 [select]:
Jun 04 14:30:01 ds24 influxd[3167]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).compact(0xc0005dd440, 0xc004ef2b60)
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1967 +0x25b
Jun 04 14:30:01 ds24 influxd[3167]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).enableLevelCompactions.func1(0xc004ef2b60, 0xc0005dd440)
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:420 +0x5b
Jun 04 14:30:01 ds24 influxd[3167]: created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).enableLevelCompactions
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:420 +0x132
Jun 04 14:30:01 ds24 influxd[3167]: goroutine 3436 [IO wait]:
Jun 04 14:30:01 ds24 influxd[3167]: internal/poll.runtime_pollWait(0x7f596ef3ae30, 0x72, 0x0)
Jun 04 14:30:01 ds24 influxd[3167]: /usr/local/go/src/runtime/netpoll.go:173 +0x66
Jun 04 14:30:01 ds24 influxd[3167]: internal/poll.(*pollDesc).wait(0xc00026a098, 0x72, 0xc058254400, 0x0, 0x0)
Jun 04 14:30:01 ds24 influxd[3167]: /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
Jun 04 14:30:01 ds24 influxd[3167]: internal/poll.(*pollDesc).waitRead(0xc00026a098, 0xffffffffffffff00, 0x0, 0x0)
Jun 04 14:30:01 ds24 influxd[3167]: /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
Jun 04 14:30:01 ds24 influxd[3167]: internal/poll.(*FD).Accept(0xc00026a080, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
Jun 04 14:30:01 ds24 influxd[3167]: /usr/local/go/src/internal/poll/fd_unix.go:384 +0x1a0
Jun 04 14:30:01 ds24 influxd[3167]: net.(*netFD).accept(0xc00026a080, 0xd892af41, 0x6e6c984fd8dd83fc, 0x44d418)
Jun 04 14:30:01 ds24 influxd[3167]: /usr/local/go/src/net/fd_unix.go:238 +0x42
Jun 04 14:30:01 ds24 influxd[3167]: net.(*TCPListener).accept(0xc0003e0878, 0x5cf60fe9, 0xc001354df0, 0x493686)
Jun 04 14:30:01 ds24 influxd[3167]: /usr/local/go/src/net/tcpsock_posix.go:139 +0x2e
Jun 04 14:30:01 ds24 influxd[3167]: net.(*TCPListener).Accept(0xc0003e0878, 0xc001354e40, 0x18, 0xc0005fe480, 0x719b95)
Jun 04 14:30:01 ds24 influxd[3167]: /usr/local/go/src/net/tcpsock.go:260 +0x47
Jun 04 14:30:01 ds24 influxd[3167]: net/http.(*Server).Serve(0xc00fd7b110, 0x15bf1a0, 0xc0003e0878, 0x0, 0x0)
Jun 04 14:30:01 ds24 influxd[3167]: /usr/local/go/src/net/http/server.go:2826 +0x22f
Jun 04 14:30:01 ds24 influxd[3167]: net/http.Serve(0x15bf1a0, 0xc0003e0878, 0x15abdc0, 0xc00026e700, 0xc07c9000c0349, 0xc10c9000c0c49)
Jun 04 14:30:01 ds24 influxd[3167]: /usr/local/go/src/net/http/server.go:2423 +0x6e
Jun 04 14:30:01 ds24 influxd[3167]: github.com/influxdata/influxdb/services/httpd.(*Service).serve(0xc0001890e0, 0x15bf1a0, 0xc0003e0878)
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/services/httpd/service.go:249 +0x62
Jun 04 14:30:01 ds24 influxd[3167]: github.com/influxdata/influxdb/services/httpd.(*Service).serveTCP(0xc0001890e0)
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/services/httpd/service.go:237 +0x3c
Jun 04 14:30:01 ds24 influxd[3167]: created by github.com/influxdata/influxdb/services/httpd.(*Service).Open
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/services/httpd/service.go:186 +0x6aa
Jun 04 14:30:01 ds24 influxd[3167]: goroutine 3762 [select]:
Jun 04 14:30:01 ds24 influxd[3167]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).compactCache(0xc0005dc900)
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1920 +0x11b
Jun 04 14:30:01 ds24 influxd[3167]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).enableSnapshotCompactions.func1(0xc004ef2a10, 0xc0005dc900)
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:499 +0x51
Jun 04 14:30:01 ds24 influxd[3167]: created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).enableSnapshotCompactions
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:499 +0x124
Jun 04 14:30:01 ds24 influxd[3167]: goroutine 3749 [select]:
Jun 04 14:30:01 ds24 influxd[3167]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).compact(0xc00052c000, 0xc004ef2940)
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1967 +0x25b
Jun 04 14:30:01 ds24 influxd[3167]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).enableLevelCompactions.func1(0xc004ef2940, 0xc00052c000)
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:420 +0x5b
Jun 04 14:30:01 ds24 influxd[3167]: created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).enableLevelCompactions
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:420 +0x132
Jun 04 14:30:01 ds24 influxd[3167]: goroutine 3720 [select]:
Jun 04 14:30:01 ds24 influxd[3167]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).compact(0xc00042a480, 0xc00dafd470)
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1967 +0x25b
Jun 04 14:30:01 ds24 influxd[3167]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).enableLevelCompactions.func1(0xc00dafd470, 0xc00042a480)
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:420 +0x5b
Jun 04 14:30:01 ds24 influxd[3167]: created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).enableLevelCompactions
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:420 +0x132
Jun 04 14:30:01 ds24 influxd[3167]: goroutine 3754 [select]:
Jun 04 14:30:01 ds24 influxd[3167]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).compactCache(0xc0002b4b40)
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1920 +0x11b
Jun 04 14:30:01 ds24 influxd[3167]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).enableSnapshotCompactions.func1(0xc004ef2990, 0xc0002b4b40)
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:499 +0x51
Jun 04 14:30:01 ds24 influxd[3167]: created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).enableSnapshotCompactions
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:499 +0x124
Jun 04 14:30:01 ds24 influxd[3167]: goroutine 3803 [select]:
Jun 04 14:30:01 ds24 influxd[3167]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).compact(0xc000428120, 0xc004ef2ba0)
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1967 +0x25b
Jun 04 14:30:01 ds24 influxd[3167]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).enableLevelCompactions.func1(0xc004ef2ba0, 0xc000428120)
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:420 +0x5b
Jun 04 14:30:01 ds24 influxd[3167]: created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).enableLevelCompactions
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:420 +0x132
Jun 04 14:30:01 ds24 influxd[3167]: goroutine 3435 [select]:
Jun 04 14:30:01 ds24 influxd[3167]: github.com/influxdata/influxdb/services/continuous_querier.(*Service).backgroundLoop(0xc000134ea0)
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/services/continuous_querier/service.go:215 +0x187
Jun 04 14:30:01 ds24 influxd[3167]: created by github.com/influxdata/influxdb/services/continuous_querier.(*Service).Open
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/services/continuous_querier/service.go:133 +0x167
Jun 04 14:30:01 ds24 influxd[3167]: goroutine 3804 [select]:
Jun 04 14:30:01 ds24 influxd[3167]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).compactCache(0xc0005dd7a0)
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1920 +0x11b
Jun 04 14:30:01 ds24 influxd[3167]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).enableSnapshotCompactions.func1(0xc004ef2bb0, 0xc0005dd7a0)
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:499 +0x51
Jun 04 14:30:01 ds24 influxd[3167]: created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).enableSnapshotCompactions
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:499 +0x124
Jun 04 14:30:01 ds24 influxd[3167]: goroutine 3809 [select]:
Jun 04 14:30:01 ds24 influxd[3167]: github.com/influxdata/influxdb/services/subscriber.(*Service).run(0xc0002b89c0)
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/services/subscriber/service.go:239 +0x29c
Jun 04 14:30:01 ds24 influxd[3167]: github.com/influxdata/influxdb/services/subscriber.(*Service).Open.func1(0xc0002b89c0)
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/services/subscriber/service.go:98 +0x57
Jun 04 14:30:01 ds24 influxd[3167]: created by github.com/influxdata/influxdb/services/subscriber.(*Service).Open
Jun 04 14:30:01 ds24 influxd[3167]: /go/src/github.com/influxdata/influxdb/services/subscriber/service.go:96 +0x160
Jun 04 14:30:01 ds24 systemd[1]: influxdb.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 04 14:30:01 ds24 systemd[1]: Unit influxdb.service entered failed state.
Jun 04 14:30:01 ds24 systemd[1]: influxdb.service failed.
Jun 04 14:30:02 ds24 systemd[1]: influxdb.service holdoff time over, scheduling restart.
Jun 04 14:30:02 ds24 systemd[1]: Stopped InfluxDB is an open-source, distributed, time series database.
Jun 04 14:30:02 ds24 systemd[1]: Started InfluxDB is an open-source, distributed, time series database.
```

**Comment by e-dard** [comment]
@lanyaye Hi, could you provide more details about your setup?

- Did you build from source or use a release package?
- if you built from source, what version of Go did you build with?
- Has this only happened once?

**Comment by lanyaye** [comment]
@e-dard thanks a lot for replaying. the following is my replay:
> * Did you build from source or use a release package?

No, I did not build from source, just use the official 1.7.6 [https://portal.influxdata.com/downloads/](https://portal.influxdata.com/downloads/) and download centos rpm [https://dl.influxdata.com/influxdb/releases/influxdb-1.7.6.x86_64.rpm](https://dl.influxdata.com/influxdb/releases/influxdb-1.7.6.x86_64.rpm)

> * if you built from source, what version of Go did you build with?

No, just use official centos rpm

> * Has this only happened once?

Yes, I have loaded the data from 4 days, and this only happened once and it does not shown again.
