### ISSUE TITLE
buildtsi can deadlock

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb#14269]
Whilst doing some testing for a fix for #12890 I found a case where `buildtsi` simply deadlocks. In this case I had reduced `GOMAXPROCS` to `2`. Here is the `SIGQUIT` output:

```
ion": "8", "trace_id": "0GSmk3qW000", "op_name": "tsi1_compact_to_level", "tsi1_level": 6, "op_event": "end", "op_elapsed": "411.390ms"}
^\SIGQUIT: quit
PC=0x7fff6a78786a m=0 sigcode=0

goroutine 0 [idle]:
runtime.pthread_cond_wait(0x1dbe428, 0x1dbe3e8, 0x0)
	/usr/local/share/go/src/runtime/sys_darwin.go:357 +0x3b
runtime.semasleep(0xffffffffffffffff, 0xc00008c548)
	/usr/local/share/go/src/runtime/os_darwin.go:63 +0x85
runtime.notesleep(0x1dbe1e8)
	/usr/local/share/go/src/runtime/lock_sema.go:167 +0xe0
runtime.stopm()
	/usr/local/share/go/src/runtime/proc.go:1936 +0xc1
runtime.exitsyscall0(0xc0241b8000)
	/usr/local/share/go/src/runtime/proc.go:3128 +0x118
runtime.mcall(0x105761b)
	/usr/local/share/go/src/runtime/asm_amd64.s:299 +0x5b

goroutine 1 [chan receive, 1 minutes]:
github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi.(*Command).processRetentionPolicy(0xc0000bab80, 0xc0000bc0f0, 0xc00003c15a, 0x6, 0xc013f9ba61, 0x7, 0xc013f9baa0, 0x28, 0xc013f9bad0, 0x27, ...)
	/Users/edd/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi/buildtsi.go:196 +0x54c
github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi.(*Command).processDatabase(0xc0000bab80, 0xc00003c15a, 0x6, 0xc00095a0e0, 0x20, 0xc00095a100, 0x1f, 0x0, 0x0)
	/Users/edd/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi/buildtsi.go:139 +0x552
github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi.(*Command).run(0xc0000bab80, 0x7ffeefbff8f1, 0x19, 0x7ffeefbff913, 0x18, 0x0, 0x7)
	/Users/edd/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi/buildtsi.go:106 +0x2c7
github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi.(*Command).Run(0xc0000bab80, 0xc0000ba020, 0x6, 0x6, 0x8, 0xc0000ba020)
	/Users/edd/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi/buildtsi.go:76 +0x570
main.(*Main).Run(0xc0000e1f50, 0xc0000ba020, 0x6, 0x6, 0x15a791b, 0x16cf540)
	/Users/edd/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/main.go:92 +0xf5f
main.main()
	/Users/edd/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/main.go:27 +0x152

goroutine 63 [semacquire, 1 minutes]:
sync.runtime_Semacquire(0xc030933548)
	/usr/local/share/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc030933540)
	/usr/local/share/go/src/sync/waitgroup.go:130 +0x65
github.com/influxdata/influxdb/tsdb/index/tsi1.(*IndexFile).Close(0xc030933540, 0x0, 0x0)
	/Users/edd/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/index_file.go:131 +0x31
github.com/influxdata/influxdb/tsdb/index/tsi1.(*Partition).Close(0xc0000cc120, 0x0, 0x0)
	/Users/edd/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/partition.go:347 +0x108
github.com/influxdata/influxdb/tsdb/index/tsi1.(*Index).Close(0xc015578000, 0x0, 0x0)
	/Users/edd/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/index.go:346 +0xad
panic(0x16a5b20, 0x1876c70)
	/usr/local/share/go/src/runtime/panic.go:522 +0x1b5
sync.(*WaitGroup).Wait(0xc0000cc1b0)
	/usr/local/share/go/src/sync/waitgroup.go:132 +0xae
github.com/influxdata/influxdb/tsdb/index/tsi1.(*Partition).Wait(...)
	/Users/edd/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/partition.go:327
github.com/influxdata/influxdb/tsdb/index/tsi1.(*Index).Wait(0xc015578000)
	/Users/edd/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/index.go:335 +0x54
github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi.IndexShard(0xc0000bc0f0, 0xc013f9bb00, 0x2b, 0xc013f9bb30, 0x2a, 0x7918, 0x40000000, 0x2710, 0xc000080540, 0x0, ...)
	/Users/edd/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi/buildtsi.go:314 +0xa40
github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi.(*Command).processRetentionPolicy.func1(0xc01551f024, 0xc0005305e0, 0xc0000bab80, 0xc00003c15a, 0x6, 0xc013f9ba61, 0x7, 0xc0000804e0, 0xc0000bc0f0, 0xc013f9baa0, ...)
	/Users/edd/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi/buildtsi.go:189 +0x1c4
created by github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi.(*Command).processRetentionPolicy
	/Users/edd/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi/buildtsi.go:180 +0x4c8

rax    0x104
rbx    0x2
rcx    0x7ffeefbff448
rdx    0xb0100
rdi    0x1dbe428
rsi    0xb0101000b0200
rbp    0x7ffeefbff4d0
rsp    0x7ffeefbff448
r8     0x0
r9     0xa0
r10    0x0
r11    0x202
r12    0x1dbe428
r13    0x16
r14    0xb0101000b0200
r15    0x2c845c0
rip    0x7fff6a78786a
rflags 0x203
cs     0x7
fs     0x0
gs     0x0
```

I'm not convinced it's the same issue as #12890

**Comment by e-dard** [comment]
I think this is actually variant of the underlying cause of https://github.com/influxdata/influxdb/issues/12890

**Comment by e-dard** [comment]
Here are some example races that you can get running `buildtsi`. Since these are interactions around waiting on the index to finish compacting, and closing the index, I think you could hit these whilst closing the index during server shutdown.

<details><summary>Concurrent write to index fields on compact/close</summary>
```
==================
WARNING: DATA RACE
Write at 0x00c00d178de8 by goroutine 62:
  github.com/influxdata/influxdb/tsdb/index/tsi1.(*IndexFile).Close()
      /Users/edd/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/index_file.go:133 +0x5b
  github.com/influxdata/influxdb/tsdb/index/tsi1.(*Partition).Close()
      /Users/edd/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/partition.go:347 +0x15b
  github.com/influxdata/influxdb/tsdb/index/tsi1.(*Index).Close()
      /Users/edd/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/index.go:346 +0xe3
  runtime.call32()
      /usr/local/share/go/src/runtime/asm_amd64.s:519 +0x3a
  github.com/influxdata/influxdb/tsdb/index/tsi1.(*Index).Wait()
      /Users/edd/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/partition.go:327 +0x90
  github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi.IndexShard()
      /Users/edd/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi/buildtsi.go:314 +0xb29
  github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi.(*Command).processRetentionPolicy.func1()
      /Users/edd/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi/buildtsi.go:189 +0x2b0

Previous write at 0x00c00d178de8 by goroutine 8:
  github.com/influxdata/influxdb/tsdb/index/tsi1.(*Partition).compactLogFile()
      /Users/edd/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/index_file.go:78 +0xee2
  github.com/influxdata/influxdb/tsdb/index/tsi1.(*Partition).checkLogFile.func1()
      /Users/edd/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/partition.go:1071 +0x75

Goroutine 62 (running) created at:
  github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi.(*Command).processRetentionPolicy()
      /Users/edd/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi/buildtsi.go:180 +0x57d
  github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi.(*Command).processDatabase()
      /Users/edd/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi/buildtsi.go:139 +0x61d
  github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi.(*Command).run()
      /Users/edd/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi/buildtsi.go:106 +0x2f7
  github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi.(*Command).Run()
      /Users/edd/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi/buildtsi.go:76 +0x79d
  main.(*Main).Run()
      /Users/edd/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/main.go:92 +0x180b
  main.main()
      /Users/edd/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/main.go:27 +0x250

Goroutine 8 (finished) created at:
  github.com/influxdata/influxdb/tsdb/index/tsi1.(*Partition).checkLogFile()
      /Users/edd/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/partition.go:1069 +0x13a
  github.com/influxdata/influxdb/tsdb/index/tsi1.(*Partition).CheckLogFile()
      /Users/edd/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/partition.go:1051 +0xb5
  github.com/influxdata/influxdb/tsdb/index/tsi1.(*Partition).createSeriesListIfNotExists()
      /Users/edd/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/partition.go:666 +0x3b9
  github.com/influxdata/influxdb/tsdb/index/tsi1.(*Index).CreateSeriesListIfNotExists.func1()
      /Users/edd/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/index.go:667 +0x699
==================
```
</details>


<details><summary>Concurrent write to index fields on compact/close</summary>
</details>

<details><summary>Concurrent read/write</summary>
```
==================
WARNING: DATA RACE
Read at 0x00c00d178dd0 by goroutine 62:
  github.com/influxdata/influxdb/tsdb/index/tsi1.(*IndexFile).Close()
      /Users/edd/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/index_file.go:136 +0x10d
  github.com/influxdata/influxdb/tsdb/index/tsi1.(*Partition).Close()
      /Users/edd/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/partition.go:347 +0x15b
  github.com/influxdata/influxdb/tsdb/index/tsi1.(*Index).Close()
      /Users/edd/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/index.go:346 +0xe3
  runtime.call32()
      /usr/local/share/go/src/runtime/asm_amd64.s:519 +0x3a
  github.com/influxdata/influxdb/tsdb/index/tsi1.(*Index).Wait()
      /Users/edd/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/partition.go:327 +0x90
  github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi.IndexShard()
      /Users/edd/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi/buildtsi.go:314 +0xb29
  github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi.(*Command).processRetentionPolicy.func1()
      /Users/edd/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi/buildtsi.go:189 +0x2b0

Previous write at 0x00c00d178dd0 by goroutine 8:
  github.com/influxdata/influxdb/tsdb/index/tsi1.(*Partition).compactLogFile()
      /Users/edd/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/index_file.go:78 +0xee2
  github.com/influxdata/influxdb/tsdb/index/tsi1.(*Partition).checkLogFile.func1()
      /Users/edd/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/partition.go:1071 +0x75

Goroutine 62 (running) created at:
  github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi.(*Command).processRetentionPolicy()
      /Users/edd/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi/buildtsi.go:180 +0x57d
  github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi.(*Command).processDatabase()
      /Users/edd/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi/buildtsi.go:139 +0x61d
  github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi.(*Command).run()
      /Users/edd/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi/buildtsi.go:106 +0x2f7
  github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi.(*Command).Run()
      /Users/edd/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi/buildtsi.go:76 +0x79d
  main.(*Main).Run()
      /Users/edd/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/main.go:92 +0x180b
  main.main()
      /Users/edd/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/main.go:27 +0x250

Goroutine 8 (finished) created at:
  github.com/influxdata/influxdb/tsdb/index/tsi1.(*Partition).checkLogFile()
      /Users/edd/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/partition.go:1069 +0x13a
  github.com/influxdata/influxdb/tsdb/index/tsi1.(*Partition).CheckLogFile()
      /Users/edd/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/partition.go:1051 +0xb5
  github.com/influxdata/influxdb/tsdb/index/tsi1.(*Partition).createSeriesListIfNotExists()
      /Users/edd/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/partition.go:666 +0x3b9
  github.com/influxdata/influxdb/tsdb/index/tsi1.(*Index).CreateSeriesListIfNotExists.func1()
      /Users/edd/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/index.go:667 +0x699
==================
```
</details>

**Comment by sorrison** [comment]
keep open, still ongoing

**Comment by e-dard** [comment]
Fixed via https://github.com/influxdata/influxdb/pull/15182

Will be part of `1.7.9`, which is currently at RC stage.
