### ISSUE TITLE
Points beyond retention policy dropped for infinite retention policy

### ISSUE THREAD

**Issue by hardiksondagar** [influxdata/influxdb#15050]
__Steps to reproduce:__
I'm writing data to InfluxDB in bulk using python library.  If I push data for some specific period it's giving me error saying that `400: {"error":"partial write: points beyond retention policy dropped=1"}`

I did little dig-up to find out why it's giving error for this specific period and found that some shards are overlapping. Can it be the reason?

I tried writing data one at a time and it's working for the same duration same data.

```
$ show shards
name: mydatabase
id  database   retention_policy shard_group start_time           end_time             expiry_time          owners
--  --------   ---------------- ----------- ----------           --------             -----------          ------
447 mydatabase autogen          447         2018-10-22T00:00:00Z 2018-11-19T00:00:00Z 2018-11-19T00:00:00Z
321 mydatabase autogen          321         2018-11-12T00:00:00Z 2018-11-19T00:00:00Z 2018-11-19T00:00:00Z
449 mydatabase autogen          449         2018-11-19T00:00:00Z 2018-12-17T00:00:00Z 2018-12-17T00:00:00Z
67  mydatabase autogen          67          2018-12-24T00:00:00Z 2018-12-31T00:00:00Z 2018-12-31T00:00:00Z
3   mydatabase autogen          3           2018-12-31T00:00:00Z 2019-01-07T00:00:00Z 2019-01-07T00:00:00Z
453 mydatabase autogen          453         2018-12-17T00:00:00Z 2019-01-14T00:00:00Z 2019-01-14T00:00:00Z
4   mydatabase autogen          4           2019-01-07T00:00:00Z 2019-01-14T00:00:00Z 2019-01-14T00:00:00Z
6   mydatabase autogen          6           2019-01-14T00:00:00Z 2019-01-21T00:00:00Z 2019-01-21T00:00:00Z
8   mydatabase autogen          8           2019-01-21T00:00:00Z 2019-01-28T00:00:00Z 2019-01-28T00:00:00Z
10  mydatabase autogen          10          2019-01-28T00:00:00Z 2019-02-04T00:00:00Z 2019-02-04T00:00:00Z
```
Also check retention policy which is set to infinite.
```
> show retention policies
name    duration shardGroupDuration replicaN default
----    -------- ------------------ -------- -------
autogen 0s       672h0m0s           1        true
```
I did changed shardGroupDuration multiple time. Can it cause issue?

__Expected behavior:__
Data should have been written in chunk as well.

__Actual behavior:__
Data is dropped by retention policy

__Environment info:__

* System info: Linux 4.4.0-1087-aws x86_64
* InfluxDB version: InfluxDB v1.7.6 (git: 1.7 01c8dd416270f424ab0c40f9291e269ac6921964)

**Comment by hardiksondagar** [comment]
9255

**Comment by hardiksondagar** [comment]
https://github.com/influxdata/influxdb/issues/9255

**Comment by hardiksondagar** [comment]
#9255

**Comment by hardiksondagar** [comment]
I investigate a little and found that, if I'm pushing data in bulk which have two different specific series, it's dropping with retention policy violation.

**Comment by hardiksondagar** [comment]
Further investigation.
I queries data from different shards and used `EXPLAIN` to check how many series are being queried for that particular date range.
```
> SHOW SHARDS
.
.
658 mydb autogen          658         2019-07-22T00:00:00Z 2019-07-29T00:00:00Z 2020-07-27T00:00:00Z
676 mydb autogen          676         2019-07-29T00:00:00Z 2019-08-05T00:00:00Z 2020-08-03T00:00:00Z
.
.
```

Executing `EXPLAIN` for data from shard **658** and it's giving expected result in terms of number of series. `SensorId` is only tag key and as date range fall into only shard it's giving `NUMBER OF SERIES: 1` 
```
> EXPLAIN select "kWh" from Reading where (SensorId =~ /^1186$/) AND time >= '2019-07-27 00:00:00' AND time <= '2019-07-28 00:00:00' limit 10;
QUERY PLAN
----------
EXPRESSION: <nil>
AUXILIARY FIELDS: "kWh"::float
NUMBER OF SHARDS: 1
NUMBER OF SERIES: 1
CACHED VALUES: 0
NUMBER OF FILES: 2
NUMBER OF BLOCKS: 4
SIZE OF BLOCKS: 32482
```
But when I run the same query on date range that falls into **shard 676**, number of series is 13140 instead of just one.
``` 
> EXPLAIN select "kWh" from Reading where (SensorId =~ /^1186$/) AND time >= '2019-07-29 00:00:00' AND time < '2019-07-30 00:00:00';
QUERY PLAN
----------
EXPRESSION: <nil>
AUXILIARY FIELDS: "kWh"::float
NUMBER OF SHARDS: 1
NUMBER OF SERIES: 13140
CACHED VALUES: 0
NUMBER OF FILES: 11426
NUMBER OF BLOCKS: 23561
SIZE OF BLOCKS: 108031642
```
Any help will be useful.

**Comment by hardiksondagar** [comment]
On checking field cardinality, observed spike in RAM.
```
> SHOW FIELD KEY CARDINALITY
```

I've rebuild the indexes, but cardinality is still high.

**Comment by hardiksondagar** [comment]
It still presents in the latest version too.

**Comment by dgnorton** [comment]
@hardiksondagar so far we haven't been able to fully reproduce the problem. We are able to reproduce the overlapping shards but not the dropped points. Here's a bash script that creates 2 shards that overlap and then tests 3 scenarios, each writes 2 points in a single request:

- Both points could potentially belong to either shard
- Both points could only belong in the second shard
- One point could belong in either shard and the second point belongs in the second shard

https://gist.github.com/dgnorton/3ab595df9a19e1d685caef58c890924c

Maybe you can see a tweak that could be made to the script to more closely match your scenario. My original thought was to create shards that exactly matched the shards in the original issue description and then write the same two points shown in a later comment. However, the points in the later comment have timestamps from 2020, which is beyond the shards shown. The comment with those points was posted Oct of 2019. Does your use case write into the future? Should be fine to do so but just looking for potential details that might help reproduce the issue.

It might be helpful if you could provide 2 points that fail to write and also a snippet of `SHOW SHARDS` that includes all the shards those 2 points could possibly belong to based on time range of the shards.

**Comment by Elbehery** [comment]
retention_policy shard_group start_time           end_time             expiry_time          owners
> --  --------   ---------------- ----------- ----------           --------             -----------          ------
 autogen          447         2018-10-22T00:00:00Z 2018-11-19T00:00:00Z 2018-11-19T00:00:00Z
 autogen          321         2018-11-12T00:00:00Z 2018-11-19T00:00:00Z 2018-11-19T00:00:00Z

Please note that the overlapping shards have the exact `end_time` while the `shard_group` of the longer shard is higher than the shorter one.

Obviously the shard duration was `extended` to cover longer time range, therefore the `shard_id` is higher.

**Comment by 2012ucp1544** [comment]
This error drops in when creating and using new retention policy, while using the default **autogen** works fine.
**Example** : CREATE RETENTION POLICY "rasp_test" ON "influx_policy" DURATION 35d SHARD DURATION 280h REPLICATION 1 DEFAULT

**Comment by 2012ucp1544** [comment]
This causes issue when providing timestamp in saving point in the database.
https://discourse.nodered.org/t/time-stamp-and-influx-db-problem/13715

**Comment by harmv** [comment]
I'm seeing the exact same problem when trying to insert data using the python library.  I have included a small test that displays the problem.

If I don't use explicit data retention policies all works fine, If I pass a policy -> error

### micro test that shows problem

````python
import influxdb
from influxdb import InfluxDBClient

DB_NAME='test'


client = InfluxDBClient(database=DB_NAME)

def main():

    query = """CREATE RETENTION POLICY "p1" on "{database}"  DURATION 400d REPLICATION 1
            """.format(database=DB_NAME)
    # print(query)
    client.query(query)

    points = ['table,unit=1 a=4082i,b=82699i 1577881860000',
              'table,unit=1 a=4082i,b=82699i 1577881861000']

    client.write_points(points, time_precision='ms', protocol='line', retention_policy="p1")


main()
````

### result

First create the database in influx commandline
```
create database test
```

###
Then run the python application
```
$ python influxdb_test.py 
Traceback (most recent call last):
  File "influxdb_test.py", line 23, in <module>
    main()
  File "influxdb_test.py", line 19, in main
    client.write_points(points, time_precision='ms', protocol='line', retention_policy="p1")
  File "venv/lib/python3.5/site-packages/influxdb/client.py", line 608, in write_points
    consistency=consistency)
  File "venv/lib/python3.5/site-packages/influxdb/client.py", line 685, in _write_points
    protocol=protocol
  File "venv/lib/python3.5/site-packages/influxdb/client.py", line 419, in write
    headers=headers
  File "venv/lib/python3.5/site-packages/influxdb/client.py", line 378, in request
    raise InfluxDBClientError(err_msg, response.status_code)
influxdb.exceptions.InfluxDBClientError: 400: {"error":"partial write: points beyond retention policy dropped=2"}
```


### version info
influxdb  1.8.3
pip install influxdb==5.3.1               # the python library

**Comment by harmv** [comment]
I got this exact problem when I was inserting data that was actually outside the retention period.

```
400: {"error":"partial write: points beyond retention policy dropped=1"}
```

So in my case it was a user error.

**Comment by fridayhoho** [comment]
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.7.7

RP:

`SixMonthRetentionPolicyid: SixMonthRetentionPolicy, name: SixMonthRetentionPolicy, duration: 4320h0m0s, shardGroupDuration: 24h0m0s, replicaN: replicaN, default: true`

then i change the shard group duration to: 168h

`SixMonthRetentionPolicyid: SixMonthRetentionPolicy, name: SixMonthRetentionPolicy, duration: 4320h0m0s, shardGroupDuration: 168h0m0s, replicaN: replicaN, default: true`

then  it give me error sometimes( but in fact  the time inserted is in the duration scope):

runWriteHistoryThread error:partial write: points beyond retention policy dropped=1 org.influxdb.InfluxDBException$PointsBeyondRetentionPolicyException: partial write: **points beyond retention policy dropped=1**
	at org.influxdb.InfluxDBException.buildExceptionFromErrorMessage(InfluxDBException.java:141) ~[influxdb-java-2.15.jar!/:?]

`3414 monitor_db SixMonthRetentionPolicy 3414        2021-09-02T00:00:00Z 2021-09-03T00:00:00Z 2022-03-02T00:00:00Z
<br/>
3418 monitor_db SixMonthRetentionPolicy 3418        2021-08-30T00:00:00Z 2021-09-06T00:00:00Z 2022-03-05T00:00:00Z`


shard overlap  occur

**Comment by fridayhoho** [comment]
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.7.7

RP:

`SixMonthRetentionPolicyid: SixMonthRetentionPolicy, name: SixMonthRetentionPolicy, duration: 4320h0m0s, shardGroupDuration: 24h0m0s, replicaN: replicaN, default: true`

then i change the shard group duration to: 168h

`SixMonthRetentionPolicyid: SixMonthRetentionPolicy, name: SixMonthRetentionPolicy, duration: 4320h0m0s, shardGroupDuration: 168h0m0s, replicaN: replicaN, default: true`

then  it give me error sometimes( but in fact  the time inserted is in the duration scope):

runWriteHistoryThread error:partial write: points beyond retention policy dropped=1 org.influxdb.InfluxDBException$PointsBeyondRetentionPolicyException: partial write: **points beyond retention policy dropped=1**
	at org.influxdb.InfluxDBException.buildExceptionFromErrorMessage(InfluxDBException.java:141) ~[influxdb-java-2.15.jar!/:?]

`3414 monitor_db SixMonthRetentionPolicy 3414        2021-09-02T00:00:00Z 2021-09-03T00:00:00Z 2022-03-02T00:00:00Z
<br/>
3418 monitor_db SixMonthRetentionPolicy 3418        2021-08-30T00:00:00Z 2021-09-06T00:00:00Z 2022-03-05T00:00:00Z`


shard overlap  occur

**Comment by rcmonitor** [comment]
> ```
> my_measurement,SensorId=10045 kWh=54191.0 1568744999
> my_measurement,SensorId=10048 kWh=82350600.0 1568658599
> ```
For me, the problem was that precision supposed to be set explicitly when using 1 second resolution as it is in your case (`1568658599`).
So, if using http request, you should add `precision=s` url query parameter
When using Go client as it is in my case, there's
```
influxdb2.NewClientWithOptions(strUrl, strToken,
			influxdb2.DefaultOptions().
				SetPrecision(time.Second))
```
