### ISSUE TITLE
Flaky test on OSS

### ISSUE THREAD

**Issue by affo** [influxdata/influxdb#15220]
I got 

```
FAIL	github.com/influxdata/influxdb/tsdb/tsi1	124.612s
=== FAIL: tsdb/tsi1 TestIndex_MeasurementCardinalityStats/Large (124.61s)
```

In a pipeline and then rebuilt and succeeded.

**Comment by affo** [comment]
I do have the entire log but that too big to be upload and I cannot find any useful information about why the test failed...

**Comment by wolffcm** [comment]
I hit this one twice in a row: https://github.com/influxdata/influxdb/pull/15657

@benbjohnson I assigned to you per the flakey-tests doc procedure, since you authored the test originally.

**Comment by wolffcm** [comment]
(I am skipping this test in the PR I referenced above)

**Comment by jacobmarble** [comment]
I hit this today as well.
https://circleci.com/gh/influxdata/influxdb/80802?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb8a19d]

goroutine 770 [running]:
github.com/influxdata/influxdb/tsdb/tsi1.(*FileSet).Duplicate(...)
	/go/src/github.com/influxdata/influxdb/tsdb/tsi1/file_set.go:74
github.com/influxdata/influxdb/tsdb/tsi1.(*Partition).compact(0xc0005f2160)
	/go/src/github.com/influxdata/influxdb/tsdb/tsi1/partition.go:943 +0x4d
github.com/influxdata/influxdb/tsdb/tsi1.(*Partition).Compact(0xc0005f2160)
	/go/src/github.com/influxdata/influxdb/tsdb/tsi1/partition.go:894 +0x61
github.com/influxdata/influxdb/tsdb/tsi1.(*Partition).checkLogFile.func1(0xc0005f2160, 0xff9380, 0xc0002e0090, 0xc00022f440, 0xc0002e0060)
	/go/src/github.com/influxdata/influxdb/tsdb/tsi1/partition.go:1194 +0x9d
created by github.com/influxdata/influxdb/tsdb/tsi1.(*Partition).checkLogFile
	/go/src/github.com/influxdata/influxdb/tsdb/tsi1/partition.go:1186 +0x1aa

goroutine 1 [chan receive]:
testing.tRunner.func1(0xc0001a4200)
	/usr/local/go/src/testing/testing.go:841 +0x203
testing.tRunner(0xc0001a4200, 0xc000105e30)
	/usr/local/go/src/testing/testing.go:869 +0xca
testing.runTests(0xc00000eec0, 0x167fc00, 0x2d, 0x2d, 0x0)
	/usr/local/go/src/testing/testing.go:1155 +0x2a9
testing.(*M).Run(0xc00019c600, 0x0)
	/usr/local/go/src/testing/testing.go:1072 +0x162
main.main()
	_testmain.go:162 +0x13e

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 610 [chan receive]:
testing.(*T).Run(0xc0002ce300, 0xef5829, 0xf, 0xf17fe8, 0x8e64ca4c01)
	/usr/local/go/src/testing/testing.go:917 +0x381
github.com/influxdata/influxdb/tsdb/tsi1_test.TestIndex_MeasurementCardinalityStats(0xc0001a4400)
	/go/src/github.com/influxdata/influxdb/tsdb/tsi1/index_test.go:432 +0x11a
testing.tRunner(0xc0001a4400, 0xf17ff8)
	/usr/local/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:916 +0x35a

goroutine 615 [chan send]:
testing.tRunner.func1(0xc0001a4900)
	/usr/local/go/src/testing/testing.go:860 +0x283
testing.tRunner(0xc0001a4900, 0xf18038)
	/usr/local/go/src/testing/testing.go:869 +0xca
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:916 +0x35a

goroutine 642 [chan receive]:
testing.runTests.func1.1(0xc0001a4200)
	/usr/local/go/src/testing/testing.go:1162 +0x3b
created by testing.runTests.func1
	/usr/local/go/src/testing/testing.go:1162 +0xac

goroutine 614 [chan send]:
testing.tRunner.func1(0xc0001a4800)
	/usr/local/go/src/testing/testing.go:860 +0x283
testing.tRunner(0xc0001a4800, 0xf18020)
	/usr/local/go/src/testing/testing.go:869 +0xca
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:916 +0x35a

goroutine 612 [chan send]:
testing.tRunner.func1(0xc0001a4600)
	/usr/local/go/src/testing/testing.go:860 +0x283
testing.tRunner(0xc0001a4600, 0xf18018)
	/usr/local/go/src/testing/testing.go:869 +0xca
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:916 +0x35a

goroutine 730 [runnable]:
syscall.Syscall(0x107, 0x6, 0xc00022c000, 0x0, 0xffffffffffffffff, 0x0, 0x15)
	/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
internal/syscall/unix.Unlinkat(0x6, 0xc0004ec094, 0x2, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/syscall/unix/at.go:21 +0x92
os.removeAllFrom(0xc00036e030, 0xc0004ec094, 0x2, 0x0, 0x0)
	/usr/local/go/src/os/removeall_at.go:62 +0x8c
os.removeAllFrom(0xc0003f2050, 0xc0004642e5, 0x1a, 0x0, 0xc0003f2050)
	/usr/local/go/src/os/removeall_at.go:117 +0x544
os.removeAll(0xc0004642e0, 0x1f, 0x0, 0x0)
	/usr/local/go/src/os/removeall_at.go:49 +0x2e2
os.RemoveAll(0xc0004642e0, 0x1f, 0x1, 0xc000424538)
	/usr/local/go/src/os/path.go:67 +0x35
github.com/influxdata/influxdb/tsdb/tsi1_test.(*SeriesFile).Close(0xc000424130, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/tsdb/tsi1/tsi1_test.go:313 +0x90
github.com/influxdata/influxdb/tsdb/tsi1_test.(*Index).Close(0xc000632e40, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/tsdb/tsi1/index_test.go:750 +0xb6
github.com/influxdata/influxdb/tsdb/tsi1_test.TestIndex_MeasurementCardinalityStats.func5(0xc0002ce300)
	/go/src/github.com/influxdata/influxdb/tsdb/tsi1/index_test.go:457 +0x456
testing.tRunner(0xc0002ce300, 0xf17fe8)
	/usr/local/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:916 +0x35a
FAIL	github.com/influxdata/influxdb/tsdb/tsi1	0.313s
```

**Comment by jsternberg** [comment]
The same seems to happen with `LargeWithDelete` in the same area. It appears like a compaction might be happening while the series file is closing.
