### ISSUE TITLE
Add source maps for node modules

### ISSUE THREAD

**Issue by 121watts** [influxdata/influxdb#15402]
Honey badger currently has sourcemaps for the influxdb ui but does not contain any sourcemaps generated by `giraffe` or `clockface`

example backtrace: https://app.honeybadger.io/projects/61122/faults/55769974

**Comment by hoorayimhelping** [comment]
Using [`sourcemap-validator`](https://www.npmjs.com/package/sourcemap-validator) on our prod build, it looks like our builds are producing invalid sourcemaps:

```bash
Error: Warning: mismatched names
Expected: webpackJsonpCallback || 'webpackJsonpCallback' || 'webpackJsonpCallback' || "webpackJsonpCallback" || "webpackJsonpCallback"
Got:  	function webpackJs ||  	function webpackJson ||  	function webpackJson ||  	function webpackJson ||  	function webpackJson
Original Line:  	function webpackJsonpCallback(data) {
Mapping: 1:29→2:0 "webpackJsonpCallback" in webpack://foo/webpack/bootstrap
    at /Users/dschwarz/Development/influxdb/ui/node_modules/sourcemap-validator/index.js:153:17
    at Array.forEach (<anonymous>)
    at SourceMapConsumer_eachMapping [as eachMapping] (/Users/dschwarz/Development/influxdb/ui/node_modules/sourcemap-validator/node_modules/source-map/lib/source-map/source-map-consumer.js:570:10)
    at validate (/Users/dschwarz/Development/influxdb/ui/node_modules/sourcemap-validator/index.js:90:12)
```
