### ISSUE TITLE
Flux not working with the sandbox project on Raspberry Pi 3 (raspbian buster)

### ISSUE THREAD

**Issue by tms0** [influxdata/influxdb#15513]
Hi,

__Steps to reproduce:__

1. Install docker, docker-compose on a RPI 3 running raspbian buster
2. Install the whole stack with the sandbox project
3. With chronograf, try anything related to flux (list measurements, execute script, etc), nothing works. 

__Expected behavior:__

A valid answer from InfluxDB API.

NB : I did the exact same steps on my laptop (Ubuntu, x86_64) and it works as expected.

__Actual behavior:__

Whatever the flux script, InfluxDB throw a runtime error :
```
149200 [panic:runtime error: invalid memory address or nil pointer dereference] goroutine 105230 [running]:
runtime/debug.Stack(0x940ba10, 0x9e75a00, 0x5066c960)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
github.com/influxdata/influxdb/services/httpd.(*Handler).recovery.func1.1(0x940ba10, 0x9e75a00, 0x5066c960, 0xbf633575, 0x27a3758e, 0x461, 0x1a24d08, 0x1cb9280, 0x10055e0, 0x8d00090)
	/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1787 +0x70
panic(0xb78508, 0x1912518)
	/usr/local/go/src/runtime/panic.go:513 +0x194
github.com/influxdata/influxdb/vendor/github.com/apache/arrow/go/arrow/memory.Set(0x9ae6000, 0x40, 0x40, 0x2916c00)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/apache/arrow/go/arrow/memory/memory.go:25 +0x38
github.com/influxdata/influxdb/vendor/github.com/apache/arrow/go/arrow/array.(*builder).init(0x2c57f20, 0x80)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/apache/arrow/go/arrow/array/builder.go:101 +0xcc
github.com/influxdata/influxdb/vendor/github.com/apache/arrow/go/arrow/array.(*Int64Builder).init(0x2c57f20, 0x80)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/apache/arrow/go/arrow/array/numericbuilder.gen.go:102 +0x28
github.com/influxdata/influxdb/vendor/github.com/apache/arrow/go/arrow/array.(*Int64Builder).Resize(0x2c57f20, 0x80)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/apache/arrow/go/arrow/array/numericbuilder.gen.go:125 +0x3c
github.com/influxdata/influxdb/vendor/github.com/apache/arrow/go/arrow/array.(*Int64Builder).Resize-fm(0x80)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/apache/arrow/go/arrow/array/numericbuilder.gen.go:113 +0x24
github.com/influxdata/influxdb/vendor/github.com/apache/arrow/go/arrow/array.(*builder).reserve(0x2c57f20, 0x5a, 0x7e95768)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/apache/arrow/go/arrow/array/builder.go:138 +0x58
github.com/influxdata/influxdb/vendor/github.com/apache/arrow/go/arrow/array.(*Int64Builder).Reserve(0x2c57f20, 0x5a)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/apache/arrow/go/arrow/array/numericbuilder.gen.go:113 +0x4c
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/arrow.NewInt(0x9adc000, 0x5a, 0x3e8, 0x0, 0x8ae87c)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/arrow/int.go:11 +0x8c
github.com/influxdata/influxdb/storage/reads.(*integerTable).advance(0x83600e0, 0xeaf600)
	/go/src/github.com/influxdata/influxdb/storage/reads/table.gen.go:322 +0x80
github.com/influxdata/influxdb/storage/reads.(*integerTable).Do(0x83600e0, 0x8cf8a00, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/storage/reads/table.gen.go:297 +0x98
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/csv.(*ResultEncoder).Encode.func1(0x5673bdc0, 0x83600e0, 0x2, 0x1)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/csv/result.go:826 +0x4d4
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*result).Do(0x6a55720, 0x417b260, 0x6a55720, 0x6a5e000)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/result.go:70 +0xe8
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/csv.(*ResultEncoder).Encode(0x6a55740, 0xffc4e0, 0x91d16e0, 0x1000920, 0x6a55720, 0x809c9a0, 0x3, 0x8d9478, 0xb632c8)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/csv/result.go:771 +0x2b8
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux.(*DelimitedMultiResultEncoder).Encode(0x6a55760, 0x5673bc78, 0x940ba30, 0x1008ac0, 0x6a55780, 0x1008c01, 0xb409500, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/result.go:281 +0xb0
github.com/influxdata/influxdb/services/httpd.(*Handler).serveFluxQuery(0x1cb9280, 0x56b72640, 0x940ba30, 0x9e75a00, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1242 +0x34c
github.com/influxdata/influxdb/services/httpd.(*Handler).serveFluxQuery-fm(0x56b72640, 0x940ba30, 0x9e75a00, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:224 +0x44
github.com/influxdata/influxdb/services/httpd.authenticate.func1(0x56b72640, 0x940ba30, 0x9e75a00)
	/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1579 +0x738
net/http.HandlerFunc.ServeHTTP(0x1dd3d80, 0x56b72640, 0x940ba30, 0x9e75a00)
	/usr/local/go/src/net/http/server.go:1964 +0x34
github.com/influxdata/influxdb/services/httpd.(*Handler).responseWriter.func1(0x1002ea0, 0x4f1b8c0, 0x9e75a00)
	/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1764 +0x84
net/http.HandlerFunc.ServeHTTP(0x1dd3d90, 0x1002ea0, 0x4f1b8c0, 0x9e75a00)
	/usr/local/go/src/net/http/server.go:1964 +0x34
github.com/influxdata/influxdb/services/httpd.gzipFilter.func1(0x1002ee0, 0x940ba20, 0x9e75a00)
	/go/src/github.com/influxdata/influxdb/services/httpd/gzip.go:39 +0x1c0
net/http.HandlerFunc.ServeHTTP(0x1dd3da0, 0x1002ee0, 0x940ba20, 0x9e75a00)
	/usr/local/go/src/net/http/server.go:1964 +0x34
github.com/influxdata/influxdb/services/httpd.cors.func1(0x1002ee0, 0x940ba20, 0x9e75a00)
	/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1706 +0x9c
net/http.HandlerFunc.ServeHTTP(0x1dd3db0, 0x1002ee0, 0x940ba20, 0x9e75a00)
	/usr/local/go/src/net/http/server.go:1964 +0x34
github.com/influxdata/influxdb/services/httpd.requestID.func1(0x1002ee0, 0x940ba20, 0x9e75a00)
	/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1737 +0x134
net/http.HandlerFunc.ServeHTTP(0x1dd3dc0, 0x1002ee0, 0x940ba20, 0x9e75a00)
	/usr/local/go/src/net/http/server.go:1964 +0x34
github.com/influxdata/influxdb/services/httpd.(*Handler).logging.func1(0x1002ee0, 0x940ba10, 0x9e75a00)
	/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1745 +0x94
net/http.HandlerFunc.ServeHTTP(0x1dd3dd0, 0x1002ee0, 0x940ba10, 0x9e75a00)
	/usr/local/go/src/net/http/server.go:1964 +0x34
github.com/influxdata/influxdb/services/httpd.(*Handler).recovery.func1(0x10055e0, 0x8d00090, 0x9e75a00)
	/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1801 +0xe0
net/http.HandlerFunc.ServeHTTP(0x1dd3de0, 0x10055e0, 0x8d00090, 0x9e75a00)
	/usr/local/go/src/net/http/server.go:1964 +0x34
github.com/influxdata/influxdb/vendor/github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0x1dd38e0, 0x10055e0, 0x8d00090, 0x9e75a00)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/bmizerany/pat/mux.go:117 +0xfc
github.com/influxdata/influxdb/services/httpd.(*Handler).ServeHTTP(0x1cb9280, 0x10055e0, 0x8d00090, 0x9e75a00)
	/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:392 +0x230
net/http.serverHandler.ServeHTTP(0x329a000, 0x10055e0, 0x8d00090, 0x9e75a00)
	/usr/local/go/src/net/http/server.go:2741 +0x74
net/http.(*conn).serve(0x8e1e120, 0x1006f00, 0x8e0b6a0)
	/usr/local/go/src/net/http/server.go:1847 +0x58c
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2851 +0x290
```

__Environment info:__

* System info: Linux 4.19.75-v7+ armv7l
* InfluxDB version: latest from sandbox

Please tell me if you need more details...!

Regards,
tms

**Comment by tms0** [comment]
I can't believe I'm the only one facing this issue.

Maybe it's more a docker related thing, do you think I should post this issue on the sandbox repo ?

**Comment by petertriho** [comment]
@tms0 I've tested the 1.7.9 and it seems to be working now (looks like it was the go runtime)

**Comment by mihailescu2m** [comment]
I still have this issue with 1.7.8 (in Docker on an armhf machine)
