### ISSUE TITLE
contains() causes panic: runtime error

### ISSUE THREAD

**Issue by alespour** [influxdata/influxdb#15781]
If my understanding of `contains() `  function is correct, the following queries should yield the same result. However the latter panics with runtime error.  I am running InfluxDB 2.0 alpha 19 linux version.

```
from(bucket: "nyc") |> range(start: -1w) |> filter(fn: (r) => r._measurement == "taxi" and r._field == "lat")
from(bucket: "nyc") |> range(start: -1w) |> filter(fn: (r) => r._measurement == "taxi" and contains(value: r._field, set: ["lat"]))
```

With sample data in attached file, the results are:

```
> from(bucket: "nyc") |> range(start: -1w) |> filter(fn: (r) => r._measurement == "taxi" and r._field == "lat")
Result: _result
Table: keys: [_start, _stop, _field, _measurement, g5, pt]
                   _start:time                      _stop:time           _field:string     _measurement:string               g5:string               pt:string                      _time:time                  _value:float  
------------------------------  ------------------------------  ----------------------  ----------------------  ----------------------  ----------------------  ------------------------------  ----------------------------  
2019-10-30T15:56:49.182962181Z  2019-11-06T15:56:49.182962181Z                     lat                    taxi                   dr5ru                  pickup  2019-11-01T00:00:01.947779410Z                     40.744614  
Table: keys: [_start, _stop, _field, _measurement, g5, pt]
                   _start:time                      _stop:time           _field:string     _measurement:string               g5:string               pt:string                      _time:time                  _value:float  
------------------------------  ------------------------------  ----------------------  ----------------------  ----------------------  ----------------------  ------------------------------  ----------------------------  
2019-10-30T15:56:49.182962181Z  2019-11-06T15:56:49.182962181Z                     lat                    taxi                   dr5ru                 dropoff  2019-11-01T00:11:55.082153551Z                     40.753944  
> from(bucket: "nyc") |> range(start: -1w) |> filter(fn: (r) => r._measurement == "taxi" and contains(value: r._field, set: ["lat"]))
Error: panic: runtime error: invalid memory address or nil pointer dereference

```

[line protocol sample input](https://github.com/influxdata/influxdb/files/3815624/input.txt)

**Comment by alespour** [comment]
Stacktrace:
```
2019-11-06T15:57:26.121346Z	info	Dispatcher panic	{"log_id": "0IwyT5mG000", "service": "storage-reads", "component": "dispatcher", "error": "panic: runtime error: invalid memory address or nil pointer dereference"}
goroutine 80870 [running]:
runtime/debug.Stack(0xc01a591380, 0x284b100, 0x1b57447)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1.1(0xc01a5913e0)
	/go/pkg/mod/github.com/influxdata/flux@v0.52.0/execute/dispatcher.go:81 +0x196
panic(0x18a6fe0, 0x3d368d0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/influxdata/flux/compiler.(*compilerScope).LocalRange(0xc000827770, 0xc000827e60)
	<autogenerated>:1 +0x32
github.com/influxdata/flux/values.BuildExternAssignments(0x288ecc0, 0xc01c1f8e10, 0x7f5ac16d2628, 0xc000827770, 0xc000827770, 0xc000b69b01)
	/go/pkg/mod/github.com/influxdata/flux@v0.52.0/values/scope.go:193 +0x50
github.com/influxdata/flux/compiler.Compile(0x28b0ac0, 0xc000827770, 0xc01c1f8e10, 0x289fae0, 0xc009d1acd0, 0x186b880, 0xc017ff0390, 0xc0006a46c0, 0xc0006a46c0)
	/go/pkg/mod/github.com/influxdata/flux@v0.52.0/compiler/compiler.go:21 +0x254
github.com/influxdata/flux/compiler.(*CompilationCache).Compile(0xc016cce520, 0x289fae0, 0xc009d1acd0, 0x1, 0xc0006a4748, 0x203008, 0x60e6b17461e203)
	/go/pkg/mod/github.com/influxdata/flux@v0.52.0/compiler/compiler.go:421 +0xc8
github.com/influxdata/flux/execute.(*dynamicFn).prepare(0xc01a591440, 0xc0223a49c0, 0x8, 0x8, 0xc017ff0390, 0x4e6440, 0xc01e7f0140)
	/go/pkg/mod/github.com/influxdata/flux@v0.52.0/execute/row_fn.go:57 +0x2d6
github.com/influxdata/flux/execute.(*RowPredicateFn).Prepare(0xc01a591440, 0xc0223a49c0, 0x8, 0x8, 0xc000084a80, 0x4)
	/go/pkg/mod/github.com/influxdata/flux@v0.52.0/execute/row_fn.go:191 +0x58
github.com/influxdata/flux/stdlib/universe.(*filterTransformation).Process(0xc016840780, 0x7e58fd24279ba3c4, 0x38c6b017ca6f0aad, 0x7f5983ef4800, 0xc0223a4c00, 0x0, 0x0)
	/go/pkg/mod/github.com/influxdata/flux@v0.52.0/stdlib/universe/filter.go:153 +0x8d
github.com/influxdata/flux/execute.processMessage(0x288fd00, 0xc016840780, 0x2866fc0, 0xc016f6ed20, 0xc009421768, 0xc01a5912c0, 0xc01608e720)
	/go/pkg/mod/github.com/influxdata/flux@v0.52.0/execute/transport.go:199 +0x1e4
github.com/influxdata/flux/execute.(*consecutiveTransport).processMessages(0xc01a5914a0, 0xa)
	/go/pkg/mod/github.com/influxdata/flux@v0.52.0/execute/transport.go:156 +0xa1
github.com/influxdata/flux/execute.(*poolDispatcher).run(0xc01a5913e0, 0x2887d00, 0xc0004fcea0)
	/go/pkg/mod/github.com/influxdata/flux@v0.52.0/execute/dispatcher.go:132 +0x4b
github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1(0xc01a5913e0, 0x2887d00, 0xc0004fcea0)
	/go/pkg/mod/github.com/influxdata/flux@v0.52.0/execute/dispatcher.go:86 +0x95
created by github.com/influxdata/flux/execute.(*poolDispatcher).Start
	/go/pkg/mod/github.com/influxdata/flux@v0.52.0/execute/dispatcher.go:63 +0x7e
```

**Comment by alespour** [comment]
Transferred to Flux issue #2288.
