### ISSUE TITLE
Swagger.yml: TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#16519]
Ran our swagger through this and saw the following error message:

https://apitools.dev/swagger-parser/online/?url=https%3A%2F%2Fraw.githubusercontent.com%2Finfluxdata%2Finfluxdb%2Fmaster%2Fhttp%2Fswagger.yml

```
This API is valid, but it cannot be shown because it contains circular references

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'properties' -> object with constructor 'Object'
    |     property 'checks' -> object with constructor 'Object'
    --- property 'items' closes the circle
    at JSON.stringify (<anonymous>)
    at toText (https://apitools.dev/swagger-parser/online/js/bundle.min.js:17:291033)
    at Function.editors.addResult (https://apitools.dev/swagger-parser/online/js/bundle.min.js:17:292169)
    at Function.editors.showResult (https://apitools.dev/swagger-parser/online/js/bundle.min.js:17:291450)
    at https://apitools.dev/swagger-parser/online/js/bundle.min.js:17:295981
    at Array.forEach (<anonymous>)
    at https://apitools.dev/swagger-parser/online/js/bundle.min.js:17:295961
```

**Comment by jademcgough** [comment]
The user impact isn't significant - we probably shouldn't have any circular references, but it's allowed by the spec and looks like this is an issue that has existed for over a year in our swagger.

There are multiple places where we have circular references. For example, the `Field` object is recursive:
```yaml
    Field:
      type: object
      properties:
        value:
          description: >-
            value is the value of the field.  Meaning of the value is implied by
            the `type` key
          type: string
        type:
          description: >-
            `type` describes the field type. `func` is a function. `field` is a field reference.
          type: string
          enum:
            - func
            - field
            - integer
            - number
            - regex
            - wildcard
        alias:
          description: >-
            Alias overrides the field name in the returned response.  Applies only
            if type is `func`
          type: string
        args:
          description: Args are the arguments to the function
          type: array
          items:
            $ref: '#/components/schemas/Field'
```

**Comment by ealdwairi** [comment]
have you found a solution?
