### ISSUE TITLE
explain analyze causes SIGSEGV  version 1.7.9

### ISSUE THREAD

**Issue by DG12** [influxdata/influxdb#16771]
[06/Feb/2020:20:19:10 -0500]91
ts=2020-02-07T01:19:10.624613Z lvl=info msg="Executing query" log_id=0Kf8aQO0000 service=query query="EXPLAIN ANALYZE SELECT temperature FROM ruuvi.autogen.ruuvi_measurements WHERE time > now() - 2m"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x120c0]
goroutine 6189172 [running]:
runtime/internal/atomic.goXadd64(0x44546ec, 0x1, 0x0, 0x77c4160, 0x12)
/usr/local/go/src/runtime/internal/atomic/atomic_arm.go:99 +0x1c
github.com/influxdata/influxdb/pkg/metrics.(*Counter).Add(...)
/go/src/github.com/influxdata/influxdb/pkg/metrics/counter.go:21
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createVarRefSeriesIterator(0x9181810, 0x1ab7a80, 0x7325500, 0x0, 0x77c4160, 0x12, 0x50331d0, 0x30, 0x30363c0, 0x0, ...)
/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:2668 +0x1f84
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createTagSetGroupIterators(0x9181810, 0x1ab7a80, 0x7325500, 0x0, 0x77c4160, 0x12, 0x101422a0, 0x2, 0xc, 0x30363c0, ...)
/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:2602 +0x190
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createTagSetIterators.func1(0xa363490, 0x9181810, 0x1ab7a80, 0x7325500, 0x0, 0x77c4160, 0x12, 0xa631340, 0x4, 0x4, ...)
/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:2562 +0xdc
created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createTagSetIterators
/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:2560 +0x364
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x120c0]
goroutine 6189171 [running]:
runtime/internal/atomic.goXadd64(0x44546ec, 0x1, 0x0, 0x77c4160, 0x12)
/usr/local/go/src/runtime/internal/atomic/atomic_arm.go:99 +0x1c
github.com/influxdata/influxdb/pkg/metrics.(*Counter).Add(...)
/go/src/github.com/influxdata/influxdb/pkg/metrics/counter.go:21
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createVarRefSeriesIterator(0x9181810, 0x1ab7a80, 0x7325500, 0x0, 0x77c4160, 0x12, 0x3e73e60, 0x30, 0x30363c0, 0x0, ...)
/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:2668 +0x1f84
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createTagSetGroupIterators(0x9181810, 0x1ab7a80, 0x7325500, 0x0, 0x77c4160, 0x12, 0x10142290, 0x2, 0xe, 0x30363c0, ...)
/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:2602 +0x190
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createTagSetIterators.func1(0xa363490, 0x9181810, 0x1ab7a80, 0x7325500, 0x0, 0x77c4160, 0x12, 0xa631340, 0x4, 0x4, ...)
/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:2562 +0xdc
created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createTagSetIterators
/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:2560 +0x364
2020-02-06 20:19:10 pi93graf daemon.notice systemd[1]: influxdb.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
2020-02-06 20:19:10 pi93graf daemon.notice systemd[1]: influxdb.service: Unit entered failed state.
2020-02-06 20:19:10 pi93graf daemon.warning systemd[1]: influxdb.service: Failed with result 'exit-code'.

__Steps to reproduce:__
EXPLAIN ANALYZE SELECT ...

__Environment info:__
uname -a
Linux pi93graf 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux

influxd version
InfluxDB v1.7.9 (git: 1.7 23bc63d43a8dc05f53afa46e3526ebb5578f3d88)

PLEASE contact me if you need additional information.
Thank you

**Comment by russorat** [comment]
@DG12 thank you for opening this issue. This doesn't seem to be happening with all EXPLAIN ANALYSE queries as I can't repro locally. This sounds like something related to the data or the influxdb setup. Is there any additional info you could give us to help repro this issue locally?

**Comment by 8none1** [comment]
Re-assigning to David for attention by the Sus Eng team.  Please re-re-assign if that's not the right team.
