### ISSUE TITLE
TSI deadlock when `DROP MEASUREMENT` and `DROP DATABASE` run concurrently

### ISSUE THREAD

**Issue by foobar** [influxdata/influxdb#16834]
This can be reproduced easily with v1.7.x. It doesn't seem to exist in inmem index.

Assuming a measurement `m1` in database `db1` has many time series,  run `DROP MEASUREMENT m1`  in one influx session and then run `DROP DATABASE db1` in a new session,  deadlock happens and both queries block.

The stack dump is attached.  
[stackdump.txt](https://github.com/influxdata/influxdb/files/4191595/stackdump.txt)

**Comment by foobar** [comment]
From stack dump, following two goroutines deadlock.

```
goroutine 1183 [semacquire, 20 minutes]:
sync.runtime_SemacquireMutex(0xc002c74964, 0xc006c56600)
        /usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc002c74960)
        /usr/local/go/src/sync/mutex.go:134 +0x109
sync.(*RWMutex).Lock(0xc002c74960)
        /usr/local/go/src/sync/rwmutex.go:93 +0x2d
github.com/influxdata/influxdb/tsdb/index/tsi1.(*Index).DropSeries(0xc002c74960, 0x9d5, 0xc005013b80, 0x2ab, 0x2b6, 0x0, 0x0, 0xc005a58800)
        /go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/index.go:792 +0xbe
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).deleteSeriesRange(0xc000861d40, 0xc00480c000, 0xfa0, 0x2710, 0x8000000000000000, 0x7fffffffffffffff, 0xc00553b440, 0xb)
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1662 +0xb9c
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).DeleteSeriesRangeWithPredicate(0xc000861d40, 0x2139140, 0xc0066f15a0, 0xc0000bed40, 0x0, 0x0)
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1470 +0x7b3
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).DeleteSeriesRange(0xc000861d40, 0x2139140, 0xc0066f15a0, 0x8000000000000000, 0x7fffffffffffffff, 0x0, 0x0)
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1362 +0x7e
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).DeleteMeasurement(0xc000861d40, 0xc0040d14c0, 0x19, 0x20, 0x0, 0x0)
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1770 +0x227
github.com/influxdata/influxdb/tsdb.(*Shard).DeleteMeasurement(0xc006c54000, 0xc0040d14c0, 0x19, 0x20, 0x19, 0x20)
        /go/src/github.com/influxdata/influxdb/tsdb/shard.go:743 +0x84
github.com/influxdata/influxdb/tsdb.(*Store).DeleteMeasurement.func1(0xc006c54000, 0x0, 0x0)
        /go/src/github.com/influxdata/influxdb/tsdb/store.go:947 +0x1fe
github.com/influxdata/influxdb/tsdb.(*Store).walkShards.func1(0xc004eced80, 0xc000c7e7e0, 0xc006c54000)
        /go/src/github.com/influxdata/influxdb/tsdb/store.go:995 +0x48
created by github.com/influxdata/influxdb/tsdb.(*Store).walkShards
        /go/src/github.com/influxdata/influxdb/tsdb/store.go:994 +0x80
```
and 
```
goroutine 904 [semacquire, 20 minutes]:
sync.runtime_Semacquire(0xc002c74a70)
        /usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc002c74a68)
        /usr/local/go/src/sync/waitgroup.go:130 +0x65
github.com/influxdata/influxdb/tsdb/index/tsi1.(*LogFile).Close(0xc002c74a50, 0x1f6ff50, 0xc0004ac900)
        /go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/log_file.go:177 +0x35
github.com/influxdata/influxdb/tsdb/index/tsi1.(*Partition).Close(0xc0004ac900, 0x0, 0x0)
        /go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/partition.go:363 +0x101
github.com/influxdata/influxdb/tsdb/index/tsi1.(*Index).Close(0xc002c74960, 0x0, 0x0)
        /go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/index.go:346 +0xad
github.com/influxdata/influxdb/tsdb.(*Shard).close(0xc006c54000, 0x1f6ff50, 0xc006c541c0)
        /go/src/github.com/influxdata/influxdb/tsdb/shard.go:383 +0x7d
github.com/influxdata/influxdb/tsdb.(*Shard).Close(0xc006c54000, 0x0, 0x0)
        /go/src/github.com/influxdata/influxdb/tsdb/shard.go:368 +0x79
github.com/influxdata/influxdb/tsdb.(*Store).DeleteDatabase.func2(0xc006c54000, 0xc000ba8780, 0x4)
        /go/src/github.com/influxdata/influxdb/tsdb/store.go:820 +0x6e
github.com/influxdata/influxdb/tsdb.(*Store).walkShards.func1(0xc0004527e0, 0xc0006603c0, 0xc006c54000)
        /go/src/github.com/influxdata/influxdb/tsdb/store.go:995 +0x48
created by github.com/influxdata/influxdb/tsdb.(*Store).walkShards
        /go/src/github.com/influxdata/influxdb/tsdb/store.go:994 +0x80
```

Digging into the code, when `DROP MEASUREMENT` command executes, function `DeleteSeriesRangeWithPredicate`  calls
` tsiIndex.RetainFileSet()` which eventually calls 
```
func (f *LogFile) Retain() { f.wg.Add(1) }
```
to add a reference count to LogFile. But then it doesn't hold any lock, and tries to acquire the Index mutex in `DropSeries`.

https://github.com/influxdata/influxdb/blob/3debb957f136e77270a214ef5d9de0f80774dbfa/tsdb/engine/tsm1/engine.go#L1375-L1391

Then `DROP DATABASE` comes in and it acquires a couple of locks in order:
* Shard mutex
* TSI  Index mutex
* TSI Partition mutex
and then it tries to close the partition. Eventually it calls following function, with above locks acquired:
https://github.com/influxdata/influxdb/blob/3debb957f136e77270a214ef5d9de0f80774dbfa/tsdb/index/tsi1/log_file.go#L174-L195

It waits for the reference counter to be released on line 177 but  blocks forever!

That is, goroutine 904 got the Index mutex and waits for the logfile ref count, while goroutine 1183 increased the ref count and asks for the Index mutex.
