### ISSUE TITLE
query filter() function with negative predicate panics

### ISSUE THREAD

**Issue by jacobmarble** [influxdata/influxdb#17062]
Make some data:
```
$ while true; do influx write -o my-org -b my-bucket -t my-token "m,k=a f=$RANDOM"; influx write -o my-org -b my-bucket -t my-token "m,k=b f=$RANDOM"; sleep 0.1; done
```

Query the data with a filter for inclusive of negative values:
```
$ influx query -t my-token -o my-org 'from(bucket: "my-bucket") |> range(start: -10h) |> filter(fn: (r) => r._value >= -1)'
Error: Failed to execute query: panic: runtime error: invalid memory address or nil pointer dereference.
See 'influx query -h' for help
```

From the logs:
```
goroutine 744828 [running]:
runtime/debug.Stack(0xc000a4e5a0, 0x383cc00, 0x28f2f61)
        /Users/jacobmarble/.gvm/gos/go1.13.7/src/runtime/debug/stack.go:24 +0x9d
github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1.1(0xc000a4e600)
        /Users/jacobmarble/go/pkg/mod/github.com/influxdata/flux@v0.62.0/execute/dispatcher.go:81 +0x192
panic(0x25ec1a0, 0x47759d0)
        /Users/jacobmarble/.gvm/gos/go1.13.7/src/runtime/panic.go:679 +0x1b2
github.com/influxdata/flux/compiler.(*compilerScope).LocalRange(0xc0008bc170, 0xc000a25210)
        <autogenerated>:1 +0x2e
github.com/influxdata/flux/values.BuildExternAssignments(0x3889320, 0xc000ec0180, 0x55461e0, 0xc0008bc170, 0xc0008bc170, 0x109002a)
        /Users/jacobmarble/go/pkg/mod/github.com/influxdata/flux@v0.62.0/values/scope.go:193 +0x50
github.com/influxdata/flux/compiler.Compile(0x38aa760, 0xc0008bc170, 0xc000ec0180, 0x3899b00, 0xc000bf4578, 0x25b0260, 0xc00091bc20, 0xc0007c1200, 0xc0007c1200)
        /Users/jacobmarble/go/pkg/mod/github.com/influxdata/flux@v0.62.0/compiler/compiler.go:18 +0x297
github.com/influxdata/flux/compiler.(*CompilationCache).Compile(0xc0004f5100, 0x3899b00, 0xc000bf4578, 0x1, 0xc0007c1288, 0x20, 0xc00090e320)
        /Users/jacobmarble/go/pkg/mod/github.com/influxdata/flux@v0.62.0/compiler/compiler.go:422 +0xc5
github.com/influxdata/flux/execute.(*dynamicFn).prepare(0xc000a4e6c0, 0xc00184a6e0, 0x7, 0x7, 0xc00091bc20, 0xc000a4a600, 0x15)
        /Users/jacobmarble/go/pkg/mod/github.com/influxdata/flux@v0.62.0/execute/row_fn.go:57 +0x2d3
github.com/influxdata/flux/execute.(*RowPredicateFn).Prepare(0xc000a4e6c0, 0xc00184a6e0, 0x7, 0x7, 0x1059007, 0x25acae0)
        /Users/jacobmarble/go/pkg/mod/github.com/influxdata/flux@v0.62.0/execute/row_fn.go:191 +0x58
github.com/influxdata/flux/stdlib/universe.(*filterTransformation).Process(0xc00078c600, 0x7e58fd24279ba3c4, 0x38c6b017ca6f0aad, 0x5546140, 0xc000e41740, 0xc000b56401, 0xc00112e360)
        /Users/jacobmarble/go/pkg/mod/github.com/influxdata/flux@v0.62.0/stdlib/universe/filter.go:183 +0x61
github.com/influxdata/flux/execute.processMessage(0x3880b20, 0xc0009e9620, 0x388a360, 0xc00078c600, 0x385cea0, 0xc000bcf5e0, 0xc000b5669a, 0xc001555500, 0xc000b566f8)
        /Users/jacobmarble/go/pkg/mod/github.com/influxdata/flux@v0.62.0/execute/transport.go:206 +0x2d6
github.com/influxdata/flux/execute.(*consecutiveTransport).processMessages(0xc000a4e720, 0x3880b20, 0xc0009e9620, 0xa)
        /Users/jacobmarble/go/pkg/mod/github.com/influxdata/flux@v0.62.0/execute/transport.go:159 +0xc6
github.com/influxdata/flux/execute.(*poolDispatcher).run(0xc000a4e600, 0x3880b20, 0xc0009e9620)
        /Users/jacobmarble/go/pkg/mod/github.com/influxdata/flux@v0.62.0/execute/dispatcher.go:132 +0x65
github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1(0xc000a4e600, 0x3880b20, 0xc0009e9620)
        /Users/jacobmarble/go/pkg/mod/github.com/influxdata/flux@v0.62.0/execute/dispatcher.go:86 +0xcd
created by github.com/influxdata/flux/execute.(*poolDispatcher).Start
        /Users/jacobmarble/go/pkg/mod/github.com/influxdata/flux@v0.62.0/execute/dispatcher.go:63 +0x7e
```

**Comment by adriandt** [comment]
Investigated this today. Thought it would help me learn about the system.

The following patch will neutralize the panic, but I don't know enough about the system and/or golang to understand why. There is something wrong with the compilerScope implementation of the Scope interface. It is lacking methods. Not sure if that is an oversight, or if something else is wrong elsewhere.

* Bug does not occur in standalone flux.
* Bug is not a recent regression. Goes back to mid January at least (5db4d25b0601b5683188d54eea3bc0d2ea9b96f4)

```
diff --git a/compiler/runtime.go b/compiler/runtime.go
index b95280c7..7cc5be20 100644
--- a/compiler/runtime.go
+++ b/compiler/runtime.go
@@ -80,6 +80,13 @@ type compilerScope struct {
 	values.Scope
 }

+func (s compilerScope) LocalRange(f func(k string, v values.Value)) {
+}
+
+func (s compilerScope) Pop() values.Scope {
+    return nil
+}
+
 func (s compilerScope) Get(name string) values.Value {
 	v, ok := s.Scope.Lookup(name)
 	if !ok {
@@ -97,7 +104,7 @@ func ToScope(s values.Scope) Scope {
 }

 func nestScope(scope Scope) Scope {
-	return compilerScope{scope.Nest(nil)}
+	return compilerScope{values.NewNestedScope(scope, nil)}
 }

 func eval(ctx context.Context, e Evaluator, scope Scope) (values.Value, error) {
```

**Comment by adriandt** [comment]
Stopping on this today ... best I can tell is that scope object is somehow corrupt. This appears to come from the spec object, which is calling into the compiler (interpreter?) that is executing the table predicate function.

**Comment by adriandt** [comment]
With the help of @jsternberg was able to see that the compilerScope is being constructed with nil as the base. This happens due to problems with spec serialization, where the bad scope originates from.
1. Need to catch this and die more gracefully. Or possibly recover and create a fresh scope and issue a warning in the logs. I am told this code will go away anyways and it may not be worth it to fix the spec serialization. Perhaps that is a bigger discussion.
2. Need to pattern match the appropriate push down (see #17075).

**Comment by jsternberg** [comment]
I can confirm that this code is going away when algorithm w lands. The reason why this happens is because the `influx query` command, counterintuitively, runs the repl. If you submit the query with curl it should work properly.

We probably need to talk about the `query` subcommand and determine what it should be doing.

**Comment by adriandt** [comment]
https://github.com/influxdata/flux/pull/2583
