### ISSUE TITLE
buckets() panics in flux repl on algo-w branch

### ISSUE THREAD

**Issue by wolffcm** [influxdata/influxdb#17205]
Seems like we need a way to send calls to `buckets()` to the remote server, or implement a local version of it.
```
$ go run ./cmd/influx repl -o cwolff -t ...
> buckets()
panic: interface conversion: interface {} is nil, not influxdb.StorageDependencies

goroutine 1 [running]:
github.com/influxdata/influxdb/query/stdlib/influxdata/influxdb.GetStorageDependencies(...)
	/Users/cwolff/workspace/github.com/influxdata/influxdb/query/stdlib/influxdata/influxdb/dependencies.go:29
github.com/influxdata/influxdb/query/stdlib/influxdata/influxdb.createBucketsSource(0x631f480, 0x7458918, 0x945cd771fb4a2d34, 0xaa84199846c7979f, 0x63427c0, 0xc0004a24c0, 0xaa84199846c7979f, 0x4438c2a, 0xc00048db80, 0xc0005e6bc0)
	/Users/cwolff/workspace/github.com/influxdata/influxdb/query/stdlib/influxdata/influxdb/buckets.go:112 +0x4ce
github.com/influxdata/flux/execute.(*createExecutionNodeVisitor).Visit(0xc0005e6f60, 0x6355e80, 0xc000353050, 0x74211e0, 0xc000a33460)
	/Users/cwolff/workspace/github.com/influxdata/flux/execute/executor.go:192 +0x533
github.com/influxdata/flux/plan.walk(0x6355e80, 0xc000353050, 0x6147808, 0xc000a33578, 0xc000a333d0, 0x1, 0x2)
	/Users/cwolff/workspace/github.com/influxdata/flux/plan/walk.go:88 +0x19e
github.com/influxdata/flux/plan.walk(0x6355e80, 0xc000352f30, 0x6147808, 0xc000a33578, 0xc000a333d0, 0xc000956780, 0x60)
	/Users/cwolff/workspace/github.com/influxdata/flux/plan/walk.go:82 +0x15d
github.com/influxdata/flux/plan.(*Spec).BottomUpWalk(0xc0004a21c0, 0xc000a33578, 0xc000956780, 0x5282f80)
	/Users/cwolff/workspace/github.com/influxdata/flux/plan/walk.go:60 +0x2fd
github.com/influxdata/flux/execute.(*executor).createExecutionState(0xc0002a4860, 0x6339780, 0xc0008e52c0, 0xc0004a21c0, 0xc00048dbd0, 0x5282f80, 0xc0002a4860, 0x6324180)
	/Users/cwolff/workspace/github.com/influxdata/flux/execute/executor.go:104 +0x18c
github.com/influxdata/flux/execute.(*executor).Execute(0xc0002a4860, 0x6339780, 0xc0008e52c0, 0xc0004a21c0, 0xc00048dbd0, 0x7, 0x0, 0x0, 0x0)
	/Users/cwolff/workspace/github.com/influxdata/flux/execute/executor.go:70 +0x5d
github.com/influxdata/flux/lang.(*Program).Start(0xc0008e5230, 0x6339780, 0xc0008e5260, 0xc00048dbd0, 0xc0008e5260, 0x6307080, 0xc0008e5230, 0x0)
	/Users/cwolff/workspace/github.com/influxdata/flux/lang/compiler.go:253 +0x1f8
github.com/influxdata/flux/repl.(*REPL).doQuery(0xc00081d680, 0x63396c0, 0xc0004a2140, 0xc000352bd0, 0x6342740, 0xc000051e80, 0x0, 0x0)
	/Users/cwolff/workspace/github.com/influxdata/flux/repl/repl.go:229 +0x205
github.com/influxdata/flux/repl.(*REPL).executeLine(0xc00081d680, 0xc000742e90, 0x9, 0x0, 0xc000a339d8)
	/Users/cwolff/workspace/github.com/influxdata/flux/repl/repl.go:188 +0x372
...
```

**Comment by wolffcm** [comment]
I also noticed that the repl does not seem to contact the server at all when invoking `buckets()`, it's trying to execute it locally.

@jsternberg Any thoughts on this one?

**Comment by jsternberg** [comment]
I think this is the same as the influxdb source. We can probably take a similar approach.
