### ISSUE TITLE
[2.0b7] Crashing on closing nil request body

### ISSUE THREAD

**Issue by nsteinmetz** [influxdata/influxdb#17508]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Run InfluxDB2 beta 7 docker image
2. Send data from telegraf as a daemon set and from a telegraf standalone instance
3. Look at influxdb logs

__Expected behavior:__
Normal ingestion of data from telegraf instances to influxdb2

__Actual behavior:__

Seems that from the upgrade of the docker image from beta 6 to beta 7, I can no longer ingest data in influxdb.

__Environment info:__

* System info: Debian 9.0 buster 64 bits for the host
* InfluxDB version: 2.0b7
* Docker 19.03.8

__Config:__
```yaml
version: '3'
services:
  influxdb:
    image: quay.io/influxdb/influxdb:2.0.0-beta
    ports:
      - 127.0.0.1:9999:9999
    volumes:
      - /srv/influx2/influxdb/:/root/
```
__Logs:__

```
influxdb_1  | ts=2020-03-31T16:33:35.010596Z lvl=error msg="a panic has occurred" log_id=0LtMmFK0000 handler=panic error="runtime error: invalid memory address or nil pointer dereference" stacktrace="goroutine 2282 [running]:\nruntime/debug.Stack(0xc000a7c7e0, 0xc000b92602, 0x1dfaa8b)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/influxdata/influxdb/http.baseHandler.panic(0x2dc50c0, 0x2d85488, 0x2df40a0, 0xc008cd7a20, 0xc0008e7900, 0x1ad15e0, 0x47d7da0)\n\t/go/src/github.com/influxdata/influxdb/http/router.go:81 +0x1e6\ngithub.com/influxdata/httprouter.(*Router).recv(0xc008a2d950, 0x2df40a0, 0xc008cd7a20, 0xc0008e7900)\n\t/go/pkg/mod/github.com/influxdata/httprouter@v1.3.1-0.20191122104820-ee83e2772f69/router.go:361 +0x79\npanic(0x1ad15e0, 0x47d7da0)\n\t/usr/local/go/src/runtime/panic.go:679 +0x1b2\ncompress/gzip.(*Reader).Close(0x0, 0xc003288770, 0xc003288730)\n\t/usr/local/go/src/compress/gzip/gunzip.go:292 +0x22\ngithub.com/influxdata/influxdb/http.readWriteRequest.func1(0xc003288818, 0xc003288858)\n\t/go/src/github.com/influxdata/influxdb/http/write_handler.go:345 +0x33\ngithub.com/influxdata/influxdb/http.readWriteRequest(0x2e04d60, 0xc008b6df20, 0x2ddefe0, 0x0, 0xc0058c880c, 0x4, 0x0, 0x0, 0x0, 0x0, ...)\n\t/go/src/github.com/influxdata/influxdb/http/write_handler.go:354 +0x2ee\ngithub.com/influxdata/influxdb/http.(*WriteHandler).handleWrite(0xc008a299a0, 0x2df40a0, 0xc008cd7c00, 0xc0008e7a00)\n\t/go/src/github.com/influxdata/influxdb/http/write_handler.go:252 +0xd6c\nnet/http.HandlerFunc.ServeHTTP(0xc008a09b70, 0x2df40a0, 0xc008cd7a20, 0xc0008e7a00)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\ngithub.com/influxdata/httprouter.(*Router).Handler.func1(0x2df40a0, 0xc008cd7a20, 0xc0008e7a00, 0x0, 0x0, 0x0)\n\t/go/pkg/mod/github.com/influxdata/httprouter@v1.3.1-0.20191122104820-ee83e2772f69/router.go:325 +0x1c8\ngithub.com/influxdata/httprouter.(*Router).ServeHTTP(0xc008a2d950, 0x2df40a0, 0xc008cd7a20, 0xc0008e7900)\n\t/go/pkg/mod/github.com/influxdata/httprouter@v1.3.1-0.20191122104820-ee83e2772f69/router.go:453 +0x896\ngithub.com/go-chi/chi.(*Mux).Mount.func1(0x2df40a0, 0xc008cd7a20, 0xc0008e7900)\n\t/go/pkg/mod/github.com/go-chi/chi@v4.0.2+incompatible/mux.go:292 +0x124\nnet/http.HandlerFunc.ServeHTTP(0xc008a2b7c0, 0x2df40a0, 0xc008cd7a20, 0xc0008e7900)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\ngithub.com/go-chi/chi.(*Mux).routeHTTP(0xc008a0e900, 0x2df40a0, 0xc008cd7a20, 0xc0008e7900)\n\t/go/pkg/mod/github.com/go-chi/chi@v4.0.2+incompatible/mux.go:425 +0x278\nnet/http.HandlerFunc.ServeHTTP(0xc008a08680, 0x2df40a0, 0xc008cd7a20, 0xc0008e7900)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\ngithub.com/influxdata/influxdb/kit/transport/http.SetCORS.func1(0x2df40a0, 0xc008cd7a20, 0xc0008e7900)\n\t/go/src/github.com/influxdata/influxdb/kit/transport/http/middleware.go:25 +0xa7\nnet/http.HandlerFunc.ServeHTTP(0xc008a0b320, 0x2df40a0, 0xc008cd7a20, 0xc0008e7900)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\ngithub.com/go-chi/chi/middleware.StripSlashes.func1(0x2df40a0, 0xc008cd7a20, 0xc0008e7900)\n\t/go/pkg/mod/github.com/go-chi/chi@v4.0.2+incompatible/middleware/strip.go:25 +0xee\nnet/http.HandlerFunc.ServeHTTP(0xc008a0b340, 0x2df40a0, 0xc008cd7a20, 0xc0008e7900)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\ngithub.com/influxdata/influxdb/kit/transport/http.SkipOptions.func1(0x2df40a0, 0xc008cd7a20, 0xc0008e7900)\n\t/go/src/github.com/influxdata/influxdb/kit/transport/http/middleware.go:63 +0xbd\nnet/http.HandlerFunc.ServeHTTP(0xc008a0b360, 0x2df40a0, 0xc008cd7a20, 0xc0008e7900)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\ngithub.com/go-chi/chi.(*Mux).ServeHTTP(0xc008a0e900, 0x2df40a0, 0xc008cd7a20, 0xc0008e7900)\n\t/go/pkg/mod/github.com/go-chi/chi@v4.0.2+incompatible/mux.go:70 +0x513\ngithub.com/influxdata/influxdb/http.(*AuthenticationHandler).ServeHTTP(0xc004300d90, 0x2df40a0, 0xc008cd7a20, 0xc0008e7800)\n\t/go/src/github.com/influxdata/influxdb/http/authentication_middleware.go:120 +0x2a5\ngithub.com/influxdata/influxdb/kit/transport/http.SetCORS.func1(0x2df40a0, 0xc008cd7a20, 0xc0008e7800)\n\t/go/src/github.com/influxdata/influxdb/kit/transport/http/middleware.go:25 +0xa7\nnet/http.HandlerFunc.ServeHTTP(0xc008a2b980, 0x2df40a0, 0xc008cd7a20, 0xc0008e7800)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\ngithub.com/influxdata/influxdb/kit/transport/http.SkipOptions.func1(0x2df40a0, 0xc008cd7a20, 0xc0008e7800)\n\t/go/src/github.com/influxdata/influxdb/kit/transport/http/middleware.go:63 +0xbd\nnet/http.HandlerFunc.ServeHTTP(0xc008a2b9a0, 0x2df40a0, 0xc008cd7a20, 0xc0008e7800)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\ngithub.com/influxdata/influxdb/http.(*PlatformHandler).ServeHTTP(0xc008a2b9e0, 0x2df40a0, 0xc008cd7a20, 0xc0008e7800)\n\t/go/src/github.com/influxdata/influxdb/http/platform_handler.go:62 +0xe6\ngithub.com/go-chi/chi.(*Mux).Mount.func1(0x2df40a0, 0xc008cd7a20, 0xc0008e7800)\n\t/go/pkg/mod/github.com/go-chi/chi@v4.0.2+incompatible/mux.go:292 +0x124\nnet/http.HandlerFunc.ServeHTTP(0xc008a2bde0, 0x2df40a0, 0xc008cd7a20, 0xc0008e7800)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\ngithub.com/go-chi/chi.(*Mux).routeHTTP(0xc008a34f60, 0x2df40a0, 0xc008cd7a20, 0xc0008e7800)\n\t/go/pkg/mod/github.com/go-chi/chi@v4.0.2+incompatible/mux.go:425 +0x278\nnet/http.HandlerFunc.ServeHTTP(0xc008a09c80, 0x2df40a0, 0xc008cd7a20, 0xc0008e7800)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\ngithub.com/influxdata/influxdb/kit/transport/http.Metrics.func1.1(0x2dfa5e0, 0xc0000368c0, 0xc0008e7800)\n\t/go/src/github.com/influxdata/influxdb/kit/transport/http/middleware.go:48 +0x19f\nnet/http.HandlerFunc.ServeHTTP(0xc000707d40, 0x2dfa5e0, 0xc0000368c0, 0xc0008e7800)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\ngithub.com/influxdata/influxdb/kit/transport/http.Trace.func1.1(0x2dfa5e0, 0xc0000368c0, 0xc0008e7800)\n\t/go/src/github.com/influxdata/influxdb/kit/transport/http/middleware.go:88 +0x3a5\nnet/http.HandlerFunc.ServeHTTP(0xc008a1fce0, 0x2dfa5e0, 0xc0000368c0, 0xc0008e7700)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\ngithub.com/go-chi/chi.(*Mux).ServeHTTP(0xc008a34f60, 0x2dfa5e0, 0xc0000368c0, 0xc0008e7600)\n\t/go/pkg/mod/github.com/go-chi/chi@v4.0.2+incompatible/mux.go:82 +0x2b2\ngithub.com/influxdata/influxdb/http.(*Handler).ServeHTTP(0xc000707d00, 0x2dfa5e0, 0xc0000368c0, 0xc0008e7600)\n\t/go/src/github.com/influxdata/influxdb/http/handler.go:130 +0x55\nnet/http.serverHandler.ServeHTTP(0xc0086aa0e0, 0x2dfa5e0, 0xc0000368c0, 0xc0008e7600)\n\t/usr/local/go/src/net/http/server.go:2802 +0xa4\nnet/http.(*conn).serve(0xc000752640, 0x2e04ca0, 0xc0008e9cc0)\n\t/usr/local/go/src/net/http/server.go:1890 +0x875\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:2928 +0x384\n"
```

**Comment by nsteinmetz** [comment]
Discussions on slack: 
* https://influxcommunity.slack.com/archives/CH8RV8PK5/p1585672690029400
* https://influxcommunity.slack.com/archives/CH8RV8PK5/p1585672690029500

**Comment by nsteinmetz** [comment]
I use Traefik 2.1.6 on top of InfluxDB

**Comment by nsteinmetz** [comment]
On telegraf side, I can see:

```
2020-03-31T19:06:55Z E! [agent] Error writing to outputs.influxdb_v2: Post https://host/api/v2/write?bucket=crntk8s&org=cerenit: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Comment by nsteinmetz** [comment]
Seems the issue is still on 2.0b9:

On telegraf side:

```
2020-04-28T07:18:25Z E! [outputs.influxdb_v2] when writing to [https://in2.monitoring.cerenit.fr]: Post https://in2.monitoring.cerenit.fr/api/v2/write?bucket=crntk8s&org=cerenit: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2020-04-28T07:18:25Z E! [agent] Error writing to outputs.influxdb_v2: Post https://in2.monitoring.cerenit.fr/api/v2/write?bucket=crntk8s&org=cerenit: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

I have to see if it's on traefik2 or influxdb2 side now.

My process is:

```
Telegraf -> Traefik2 -> InfluxDB2
```

I now use standalone binaries of influxdb2 and no longer docker packaging.

Will try to add some logs as I don't have as much for now.

**Comment by russorat** [comment]
Thanks for the issue. I'm going to close this for now since it was opened against a pre-release version of InfluxDB. If you are still facing this problem after upgrading to the latest release, please open a new issue with the details.
