### ISSUE TITLE
/docs endpoint not working in master

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#17652]
```
e.name.localCompare is not a function
Stack trace
TypeError: e.name.localCompare is not a function
    at https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js:130:56091
    at Array.sort (<anonymous>)
    at e.initDiscriminator (https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js:130:56004)
    at e.init (https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js:130:54621)
    at new e (https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js:130:50979)
    at e.init (https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js:130:54084)
    at new e (https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js:130:50979)
    at new e (https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js:130:56699)
    at https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js:130:53508
    at Array.map (<anonymous>)

ReDoc Version: 2.0.0-rc.25
Commit: 89054da
```

![image](https://user-images.githubusercontent.com/4805997/78693900-b8e7d600-78b0-11ea-9a3c-f4669622e849.png)

**Comment by russorat** [comment]
from swagger validator:
![image](https://user-images.githubusercontent.com/4805997/79021565-bb586300-7b30-11ea-931c-039682345f43.png)

![image](https://user-images.githubusercontent.com/4805997/79021558-b4315500-7b30-11ea-828b-ce464ffebead.png)
