### ISSUE TITLE
Panic on influxdb2 startup: seriesfile.ReadSeriesKey

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#18057]
After attempting to load a 5GB linne protocol file into influxdb 2 via a simple python script, I am now seeing this panic when trying to start my docker container.

What other information can i provide to help troubleshoot?

```
influxdb_1  | ts=2020-05-12T17:52:15.691826Z lvl=info msg="Welcome to InfluxDB" log_id=0MjW5gIl000 version=2.0.0-beta.9 commit=eb6a5520df build_date=2020-05-12T17:52:15Z
influxdb_1  | ts=2020-05-12T17:52:15.695810Z lvl=info msg="Resources opened" log_id=0MjW5gIl000 service=bolt path=/root/.influxdbv2/influxd.bolt
influxdb_1  | ts=2020-05-12T17:52:15.711680Z lvl=info msg="Opening Series File (start)" log_id=0MjW5gIl000 service=storage-engine service=series-file op_name=series_file_open path=/root/.influxdbv2/engine/_series op_event=start
influxdb_1  | ts=2020-05-12T17:52:15.872392Z lvl=info msg="Opening Series File (end)" log_id=0MjW5gIl000 service=storage-engine service=series-file op_name=series_file_open path=/root/.influxdbv2/engine/_series op_event=end op_elapsed=160.713ms
influxdb_1  | unexpected fault address 0x7ff34e57ca6e
influxdb_1  | fatal error: fault
influxdb_1  | [signal SIGBUS: bus error code=0x2 addr=0x7ff34e57ca6e pc=0x548a38]
influxdb_1  | 
influxdb_1  | goroutine 34 [running]:
influxdb_1  | runtime.throw(0x1e361c7, 0x5)
influxdb_1  |   /usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc00167b6e0 sp=0xc00167b6b0 pc=0x42f602
influxdb_1  | runtime.sigpanic()
influxdb_1  |   /usr/local/go/src/runtime/signal_unix.go:391 +0x455 fp=0xc00167b710 sp=0xc00167b6e0 pc=0x444cb5
influxdb_1  | encoding/binary.Uvarint(0x7ff34e57ca6e, 0x314592, 0x314592, 0x2708f6455e3f5fff, 0xc2462)
influxdb_1  |   /usr/local/go/src/encoding/binary/varint.go:63 +0x38 fp=0xc00167b718 sp=0xc00167b710 pc=0x548a38
influxdb_1  | github.com/influxdata/influxdb/v2/tsdb/seriesfile.ReadSeriesKey(...)
influxdb_1  |   /go/src/github.com/influxdata/influxdb/tsdb/seriesfile/series_file.go:458
influxdb_1  | github.com/influxdata/influxdb/v2/tsdb/seriesfile.(*SeriesPartition).seriesKeyByOffset(0xc000656000, 0x200ceba65, 0x200ceba65, 0x400, 0x20300000000000)
influxdb_1  |   /go/src/github.com/influxdata/influxdb/tsdb/seriesfile/series_partition.go:594 +0xae fp=0xc00167b768 sp=0xc00167b718 pc=0xd41f1e
influxdb_1  | github.com/influxdata/influxdb/v2/tsdb/seriesfile.(*SeriesPartition).SeriesKey(0xc000656000, 0xc2462, 0x7ff353bc6e00, 0x20300000000000, 0x7ff353d17fff)
influxdb_1  |   /go/src/github.com/influxdata/influxdb/tsdb/seriesfile/series_partition.go:434 +0xb4 fp=0xc00167b7b8 sp=0xc00167b768 pc=0xd410b4
influxdb_1  | github.com/influxdata/influxdb/v2/tsdb/seriesfile.(*SeriesFile).SeriesKey(0xc00010b710, 0xc2462, 0x4177ee, 0x7ff353ab3158, 0x0)
influxdb_1  |   /go/src/github.com/influxdata/influxdb/tsdb/seriesfile/series_file.go:287 +0x5b fp=0xc00167b7f0 sp=0xc00167b7b8 pc=0xd3a4fb
influxdb_1  | github.com/influxdata/influxdb/v2/tsdb/tsi1.(*LogFile).execSeriesEntry(0xc000528240, 0xc00167bbb0)
influxdb_1  |   /go/src/github.com/influxdata/influxdb/tsdb/tsi1/log_file.go:763 +0xe24 fp=0xc00167ba90 sp=0xc00167b7f0 pc=0xe20384
influxdb_1  | github.com/influxdata/influxdb/v2/tsdb/tsi1.(*LogFile).execEntry(0xc000528240, 0xc00167bbb0)
influxdb_1  |   /go/src/github.com/influxdata/influxdb/tsdb/tsi1/log_file.go:722 +0x71 fp=0xc00167bb10 sp=0xc00167ba90 pc=0xe1e8d1
influxdb_1  | github.com/influxdata/influxdb/v2/tsdb/tsi1.(*LogFile).open(0xc000528240, 0xc00000c480, 0xc00000c460)
influxdb_1  |   /go/src/github.com/influxdata/influxdb/tsdb/tsi1/log_file.go:181 +0x405 fp=0xc00167bc68 sp=0xc00167bb10 pc=0xe1a535
influxdb_1  | github.com/influxdata/influxdb/v2/tsdb/tsi1.(*LogFile).Open(0xc000528240, 0xc0000bfa10, 0x30)
influxdb_1  |   /go/src/github.com/influxdata/influxdb/tsdb/tsi1/log_file.go:123 +0x2b fp=0xc00167bca0 sp=0xc00167bc68 pc=0xe1a0cb
influxdb_1  | github.com/influxdata/influxdb/v2/tsdb/tsi1.(*Partition).openLogFile(0xc000378000, 0xc0000bfa10, 0x30, 0xc0000bfa10, 0x30, 0xc00167bda0)
influxdb_1  |   /go/src/github.com/influxdata/influxdb/tsdb/tsi1/partition.go:298 +0x7a fp=0xc00167bcd8 sp=0xc00167bca0 pc=0xe29f2a
influxdb_1  | github.com/influxdata/influxdb/v2/tsdb/tsi1.(*Partition).Open.func2(0xc000250d70, 0xc000378000, 0x0, 0x0, 0x0, 0x0, 0x0)
influxdb_1  |   /go/src/github.com/influxdata/influxdb/tsdb/tsi1/partition.go:223 +0x1f6 fp=0xc00167bde0 sp=0xc00167bcd8 pc=0xe424c6
influxdb_1  | github.com/influxdata/influxdb/v2/tsdb/tsi1.(*Partition).Open(0xc000378000, 0x0, 0x0)
influxdb_1  |   /go/src/github.com/influxdata/influxdb/tsdb/tsi1/partition.go:245 +0x445 fp=0xc00167bf80 sp=0xc00167bde0 pc=0xe297b5
influxdb_1  | github.com/influxdata/influxdb/v2/tsdb/tsi1.(*Index).Open.func1(0xc0015cc9d8, 0x8, 0xc0005f8600, 0xc00087d9e0, 0x1)
influxdb_1  |   /go/src/github.com/influxdata/influxdb/tsdb/tsi1/index.go:286 +0x3f fp=0xc00167bfb8 sp=0xc00167bf80 pc=0xe402bf
influxdb_1  | runtime.goexit()
influxdb_1  |   /usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00167bfc0 sp=0xc00167bfb8 pc=0x45f211
influxdb_1  | created by github.com/influxdata/influxdb/v2/tsdb/tsi1.(*Index).Open
influxdb_1  |   /go/src/github.com/influxdata/influxdb/tsdb/tsi1/index.go:280 +0xa02
influxdb_1  | 
influxdb_1  | goroutine 1 [chan receive]:
influxdb_1  | github.com/influxdata/influxdb/v2/tsdb/tsi1.(*Index).Open(0xc0005f8600, 0x2eec740, 0xc000aa9830, 0x0, 0x0)
influxdb_1  |   /go/src/github.com/influxdata/influxdb/tsdb/tsi1/index.go:296 +0xa53
influxdb_1  | github.com/influxdata/influxdb/v2/storage.(*openHelper).Open(0xc000464b98, 0x2eec740, 0xc000aa9830, 0x2ecb3c0, 0xc0005f8600)
influxdb_1  |   /go/src/github.com/influxdata/influxdb/storage/opener.go:28 +0x5c
influxdb_1  | github.com/influxdata/influxdb/v2/storage.(*Engine).Open(0xc00065a180, 0x2eec740, 0xc000aa9830, 0x0, 0x0)
influxdb_1  |   /go/src/github.com/influxdata/influxdb/storage/engine.go:252 +0x1eb
influxdb_1  | github.com/influxdata/influxdb/v2/cmd/influxd/launcher.(*Launcher).run(0xc0000d62c0, 0x2eec680, 0xc000602040, 0x0, 0x0)
influxdb_1  |   /go/src/github.com/influxdata/influxdb/cmd/influxd/launcher/launcher.go:671 +0x3410
influxdb_1  | github.com/influxdata/influxdb/v2/cmd/influxd/launcher.NewCommand.func1(0xc000338f00, 0xc00021c640, 0x0, 0x2)
influxdb_1  |   /go/src/github.com/influxdata/influxdb/cmd/influxd/launcher/launcher.go:89 +0x14a
influxdb_1  | github.com/spf13/cobra.(*Command).execute(0xc000338f00, 0xc0000a2160, 0x2, 0x2, 0xc000338f00, 0xc0000a2160)
influxdb_1  |   /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
influxdb_1  | github.com/spf13/cobra.(*Command).ExecuteC(0xc000338f00, 0x2, 0x2, 0xc000338f00)
influxdb_1  |   /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
influxdb_1  | github.com/spf13/cobra.(*Command).Execute(...)
influxdb_1  |   /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
influxdb_1  | main.main()
influxdb_1  |   /go/src/github.com/influxdata/influxdb/cmd/influxd/main.go:75 +0x76
influxdb_1  | 
influxdb_1  | goroutine 22 [chan receive]:
influxdb_1  | github.com/influxdata/influxdb/v2/bolt.init.0.func1()
influxdb_1  |   /go/src/github.com/influxdata/influxdb/bolt/metrics.go:115 +0x8a
influxdb_1  | created by github.com/influxdata/influxdb/v2/bolt.init.0
influxdb_1  |   /go/src/github.com/influxdata/influxdb/bolt/metrics.go:114 +0xdc
influxdb_1  | 
influxdb_1  | goroutine 23 [syscall]:
influxdb_1  | os/signal.signal_recv(0x0)
influxdb_1  |   /usr/local/go/src/runtime/sigqueue.go:147 +0x9c
influxdb_1  | os/signal.loop()
influxdb_1  |   /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
influxdb_1  | created by os/signal.init.0
influxdb_1  |   /usr/local/go/src/os/signal/signal_unix.go:29 +0x41
influxdb_1  | 
influxdb_1  | goroutine 25 [select]:
influxdb_1  | go.opencensus.io/stats/view.(*worker).start(0xc0000e9360)
influxdb_1  |   /go/pkg/mod/go.opencensus.io@v0.22.0/stats/view/worker.go:154 +0x100
influxdb_1  | created by go.opencensus.io/stats/view.init.0
influxdb_1  |   /go/pkg/mod/go.opencensus.io@v0.22.0/stats/view/worker.go:32 +0x57
influxdb_1  | 
influxdb_1  | goroutine 13 [select]:
influxdb_1  | github.com/influxdata/influxdb/v2/kit/signals.WithSignals.func1(0xc0000a0620, 0x2eec680, 0xc000602000, 0xc000499c80)
influxdb_1  |   /go/src/github.com/influxdata/influxdb/kit/signals/context.go:18 +0xe8
influxdb_1  | created by github.com/influxdata/influxdb/v2/kit/signals.WithSignals
influxdb_1  |   /go/src/github.com/influxdata/influxdb/kit/signals/context.go:16 +0xcd
influxdb_1  | 
influxdb_1  | goroutine 33 [runnable]:
influxdb_1  | github.com/influxdata/influxdb/v2/tsdb/tsi1.(*Index).Open.func1(0xc0015cc9d8, 0x8, 0xc0005f8600, 0xc00087d9e0, 0x0)
influxdb_1  |   /go/src/github.com/influxdata/influxdb/tsdb/tsi1/index.go:280
influxdb_1  | created by github.com/influxdata/influxdb/v2/tsdb/tsi1.(*Index).Open
influxdb_1  |   /go/src/github.com/influxdata/influxdb/tsdb/tsi1/index.go:280 +0xa02
```

**Comment by russorat** [comment]
results of `influxd inspect report-tsm --detailed` 

```
influxdb_1  | File                          Series  New (est) Min Time             Max Time             Load Time
influxdb_1  | 000000000001193-000000004.tsm 404000  403519    2020-05-01T00:00:00Z 2020-05-01T00:08:10Z 320.0119ms
influxdb_1  | 000000000001321-000000004.tsm 404000  0       2020-05-01T00:00:00Z 2020-05-01T00:13:20Z 311.9737ms
influxdb_1  | 000000000001353-000000003.tsm 404000  0       2020-05-01T00:03:50Z 2020-05-01T00:06:20Z 304.4855ms
influxdb_1  | 000000000001361-000000002.tsm 404000  0       2020-05-01T00:06:20Z 2020-05-01T00:07:00Z 490.5107ms
influxdb_1  | 000000000001369-000000002.tsm 404000  0       2020-05-01T00:07:00Z 2020-05-01T00:07:30Z 172.9307ms
influxdb_1  | 000000000001370-000000001.tsm 205840  0       2020-05-01T00:07:30Z 2020-05-01T00:07:40Z 86.0941ms
influxdb_1  | 000000000001371-000000001.tsm 151280  0       2020-05-01T00:07:40Z 2020-05-01T00:07:40Z 155.7977ms
influxdb_1  | 000000000001372-000000001.tsm 116280  0       2020-05-01T00:07:40Z 2020-05-01T00:07:40Z 68.6053ms
influxdb_1  | 000000000001373-000000001.tsm 169360  0       2020-05-01T00:07:40Z 2020-05-01T00:07:50Z 136.2505ms
influxdb_1  | 000000000001374-000000001.tsm 148000  0       2020-05-01T00:07:50Z 2020-05-01T00:07:50Z 158.0693ms
influxdb_1  | 000000000001375-000000001.tsm 203080  0       2020-05-01T00:07:50Z 2020-05-01T00:08:00Z 260.4233ms
influxdb_1  | 000000000001376-000000001.tsm 155280  0       2020-05-01T00:08:00Z 2020-05-01T00:08:00Z 73.4962ms
influxdb_1  |   Files: 12 (0 skipped)
influxdb_1  | 
influxdb_1  | Summary:
influxdb_1  | 
influxdb_1  |   Series Cardinality (est): 403519
influxdb_1  |   Time Range: 2020-05-01T00:00:00Z - 2020-05-01T00:13:20Z
influxdb_1  |   Duration: 13m20s 
influxdb_1  | Statistics
influxdb_1  |   Organizations (1):
influxdb_1  |      - 05ad7794c3047000: 403519 (est) (100%)
influxdb_1  |   Total (est): 403519
influxdb_1  |  
influxdb_1  |  Buckets (1):
influxdb_1  |      - e6d902c47fb743fa: 403519 (est) (100%)
influxdb_1  |   Total (est): 403519
influxdb_1  | 
influxdb_1  |   Series By Measurements (9):
influxdb_1  |     - cpu: 39749 (est) (9%)
influxdb_1  |     - disk: 27999 (est) (6%)
influxdb_1  |     - diskio: 27994 (est) (6%)
influxdb_1  |     - kernel: 24003 (est) (5%)
influxdb_1  |     - mem: 36263 (est) (8%)
influxdb_1  |     - net: 32002 (est) (7%)
influxdb_1  |     - nginx: 27999 (est) (6%)
influxdb_1  |     - postgresl: 64090 (est) (15%)
influxdb_1  |     - redis: 124392 (est) (30%)
influxdb_1  | 
influxdb_1  |   Fields By Measurements (9):
influxdb_1  |     - cpu: 10 (est)
influxdb_1  |     - disk: 7 (est)
influxdb_1  |     - diskio: 7 (est)
influxdb_1  |     - kernel: 6 (est)
influxdb_1  |     - mem: 9 (est)
influxdb_1  |     - net: 8 (est)
influxdb_1  |     - nginx: 7 (est)
influxdb_1  |     - postgresl: 16 (est)
influxdb_1  |     - redis: 31 (est)
influxdb_1  | 
influxdb_1  |   Tag Values By Tag Keys (16):
influxdb_1  |     - arch: 2 (est)
influxdb_1  |     - datacenter: 23 (est)
influxdb_1  |     - fstype: 3 (est)
influxdb_1  |     - hostname: 4000 (est)
influxdb_1  |     - interface: 4 (est)
influxdb_1  |     - os: 3 (est)
influxdb_1  |     - path: 10 (est)
influxdb_1  |     - port: 6676 (est)
influxdb_1  |     - rack: 100 (est)
influxdb_1  |     - region: 9 (est)
influxdb_1  |     - serial: 4000 (est)
influxdb_1  |     - server: 7815 (est)
influxdb_1  |     - service: 20 (est)
influxdb_1  |     - service_environment: 3 (est)
influxdb_1  |     - service_version: 2 (est)
influxdb_1  |     - team: 4 (est)
influxdb_1  | 
influxdb_1  | Completed in 13.723201s
docker_influxdb_1 exited with code 0
```

**Comment by russorat** [comment]
closing this since i opened it.
