### ISSUE TITLE
Flux: Error on filter

### ISSUE THREAD

**Issue by elohmeier** [influxdata/influxdb#18210]
__Steps to reproduce:__

Execute a flux query to fetch Telegraf cpu metrics:
```
from(bucket:"telegraf/autogen")
  |> range(start: -1m)
  |> filter(fn: (r) => r._measurement == "cpu" and r.host == "myhost")
```

__Expected behavior:__
Metrics are returned.

__Actual behavior:__
Influx CLI reports `Error: unknown server error: 500 Internal Server Error`.

__Environment info:__

* System info: Linux 4.12.14-95.51-default x86_64
* InfluxDB version: InfluxDB v1.8.0-c1.8.0 (git: 1.8 53c8549d9af3b280a69ccd25175bd35a740b0d42)
* Other relevant environment details: SUSE Linux Enterprise Server 12 SP4

__Config:__
```
[http]
  flux-enabled = true
```

__Logs:__
```
May 25 12:50:39 srsmpl095 influxd[63065]: [httpd] 10.10.134.90 - influxdb [25/May/2020:12:50:39 +0200] "POST /api/v2/query HTTP/1.1" 200 0 "-" "Go-http-client/1.1" 9259a5a4-9e75-11ea-95e7-005056a64796 375 [panic:runtime error: invalid memory address or nil pointer dereference] goroutine 2480200 [running]:
May 25 12:50:39 srsmpl095 influxd[63065]: runtime/debug.Stack(0xc0f64b0260, 0xc07e546600, 0xbfab069fcb84726c)
May 25 12:50:39 srsmpl095 influxd[63065]:         /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
May 25 12:50:39 srsmpl095 influxd[63065]: github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/services/httpd.(*Handler).recovery.func1.1(0xc0f64b0260, 0xc07e546600, 0xbfab069fcb84726c, 0x15ea76109ef, 0x38bf460, 0xc0696c1500, 0x2725240, 0xc292a59500)
May 25 12:50:39 srsmpl095 influxd[63065]:         /go/src/github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/services/httpd/handler.go:1940 +0xc7
May 25 12:50:39 srsmpl095 influxd[63065]: panic(0x1585820, 0x3490e40)
May 25 12:50:39 srsmpl095 influxd[63065]:         /usr/local/go/src/runtime/panic.go:679 +0x1b2
May 25 12:50:39 srsmpl095 influxd[63065]: github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/flux/stdlib/influxdata/influxdb.PushDownFilterRule.Rewrite(0x274c120, 0xc09c4378c0, 0x17f923a, 0x6, 0xc1da130790, 0x1, 0x1)
May 25 12:50:39 srsmpl095 influxd[63065]:         /go/src/github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/flux/stdlib/influxdata/influxdb/rules.go:109 +0xed
May 25 12:50:39 srsmpl095 influxd[63065]: github.com/influxdata/plutonium/vendor/github.com/influxdata/flux/plan.(*heuristicPlanner).matchRules(0xc1da130020, 0x274c120, 0xc09c4378c0, 0x38ddf80, 0xc09c437800, 0xc09c433c00, 0x0, 0x0)
May 25 12:50:39 srsmpl095 influxd[63065]:         /go/src/github.com/influxdata/plutonium/vendor/github.com/influxdata/flux/plan/heuristic_planner.go:60 +0x35e
May 25 12:50:39 srsmpl095 influxd[63065]: github.com/influxdata/plutonium/vendor/github.com/influxdata/flux/plan.(*heuristicPlanner).Plan(0xc1da130020, 0xc040fb0e80, 0x0, 0x0, 0x0)
May 25 12:50:39 srsmpl095 influxd[63065]:         /go/src/github.com/influxdata/plutonium/vendor/github.com/influxdata/flux/plan/heuristic_planner.go:101 +0x257
May 25 12:50:39 srsmpl095 influxd[63065]: github.com/influxdata/plutonium/vendor/github.com/influxdata/flux/plan.(*physicalPlanner).Plan(0xc0f64b0520, 0xc040fb0e80, 0xc040fb0e80, 0x0, 0x0)
May 25 12:50:39 srsmpl095 influxd[63065]:         /go/src/github.com/influxdata/plutonium/vendor/github.com/influxdata/flux/plan/physical.go:43 +0x3c
May 25 12:50:39 srsmpl095 influxd[63065]: github.com/influxdata/plutonium/vendor/github.com/influxdata/flux/plan.(*planner).Plan(0xc0f64b0580, 0xc09c437680, 0x0, 0x0, 0x0)
May 25 12:50:39 srsmpl095 influxd[63065]:         /go/src/github.com/influxdata/plutonium/vendor/github.com/influxdata/flux/plan/builder.go:47 +0xa4
May 25 12:50:39 srsmpl095 influxd[63065]: github.com/influxdata/plutonium/vendor/github.com/influxdata/flux/repl.Compiler.Compile(0xc09c437680, 0x272da40, 0xc09c41fc80, 0x272da40, 0xc09c41fc80, 0x4, 0x9c41fb00)
May 25 12:50:39 srsmpl095 influxd[63065]:         /go/src/github.com/influxdata/plutonium/vendor/github.com/influxdata/flux/repl/compiler.go:21 +0x67
May 25 12:50:39 srsmpl095 influxd[63065]: github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/flux/control.(*Controller).Query(0xc122800de0, 0x272da40, 0xc09c41fc80, 0x2713da0, 0xc09c437680, 0xc09c4c3888, 0x3439240, 0x1, 0x3439263)
May 25 12:50:39 srsmpl095 influxd[63065]:         /go/src/github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/flux/control/controller.go:43 +0xd9
May 25 12:50:39 srsmpl095 influxd[63065]: github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/services/httpd.(*Handler).serveFluxQuery(0xc0696c1500, 0x7f2807157418, 0xc0f64b02a0, 0xc07e546600, 0x273b860, 0xc12a8c3150)
May 25 12:50:39 srsmpl095 influxd[63065]:         /go/src/github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/services/httpd/handler.go:1359 +0x2f3
May 25 12:50:39 srsmpl095 influxd[63065]: github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/services/httpd.authenticate.func1(0x7f2807157418, 0xc0f64b02a0, 0xc07e546600)
May 25 12:50:39 srsmpl095 influxd[63065]:         /go/src/github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/services/httpd/handler.go:1820 +0x94
May 25 12:50:39 srsmpl095 influxd[63065]: net/http.HandlerFunc.ServeHTTP(0xc17b53ed20, 0x7f2807157418, 0xc0f64b02a0, 0xc07e546600)
May 25 12:50:39 srsmpl095 influxd[63065]:         /usr/local/go/src/net/http/server.go:2007 +0x44
May 25 12:50:39 srsmpl095 influxd[63065]: github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/services/httpd.(*Handler).responseWriter.func1(0x271ff80, 0xc09c43ce10, 0xc07e546600)
May 25 12:50:39 srsmpl095 influxd[63065]:         /go/src/github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/services/httpd/handler.go:1917 +0xab
May 25 12:50:39 srsmpl095 influxd[63065]: net/http.HandlerFunc.ServeHTTP(0xc17b53ed40, 0x271ff80, 0xc09c43ce10, 0xc07e546600)
May 25 12:50:39 srsmpl095 influxd[63065]:         /usr/local/go/src/net/http/server.go:2007 +0x44
May 25 12:50:39 srsmpl095 influxd[63065]: github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/services/httpd.gzipFilter.func1(0x2720000, 0xc0f64b0280, 0xc07e546600)
May 25 12:50:39 srsmpl095 influxd[63065]:         /go/src/github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/services/httpd/gzip.go:39 +0x245
May 25 12:50:39 srsmpl095 influxd[63065]: net/http.HandlerFunc.ServeHTTP(0xc17b53ed60, 0x2720000, 0xc0f64b0280, 0xc07e546600)
May 25 12:50:39 srsmpl095 influxd[63065]:         /usr/local/go/src/net/http/server.go:2007 +0x44
May 25 12:50:39 srsmpl095 influxd[63065]: github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/services/httpd.cors.func1(0x2720000, 0xc0f64b0280, 0xc07e546600)
May 25 12:50:39 srsmpl095 influxd[63065]:         /go/src/github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/services/httpd/handler.go:1859 +0xde
May 25 12:50:39 srsmpl095 influxd[63065]: net/http.HandlerFunc.ServeHTTP(0xc17b53ed80, 0x2720000, 0xc0f64b0280, 0xc07e546600)
May 25 12:50:39 srsmpl095 influxd[63065]:         /usr/local/go/src/net/http/server.go:2007 +0x44
May 25 12:50:39 srsmpl095 influxd[63065]: github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/services/httpd.requestID.func1(0x2720000, 0xc0f64b0280, 0xc07e546600)
May 25 12:50:39 srsmpl095 influxd[63065]:         /go/src/github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/services/httpd/handler.go:1890 +0x34d
May 25 12:50:39 srsmpl095 influxd[63065]: net/http.HandlerFunc.ServeHTTP(0xc17b53eda0, 0x2720000, 0xc0f64b0280, 0xc07e546600)
May 25 12:50:39 srsmpl095 influxd[63065]:         /usr/local/go/src/net/http/server.go:2007 +0x44
May 25 12:50:39 srsmpl095 influxd[63065]: github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/services/httpd.(*Handler).logging.func1(0x2720000, 0xc0f64b0260, 0xc07e546600)
May 25 12:50:39 srsmpl095 influxd[63065]:         /go/src/github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/services/httpd/handler.go:1898 +0xdf
May 25 12:50:39 srsmpl095 influxd[63065]: net/http.HandlerFunc.ServeHTTP(0xc17b53edc0, 0x2720000, 0xc0f64b0260, 0xc07e546600)
May 25 12:50:39 srsmpl095 influxd[63065]:         /usr/local/go/src/net/http/server.go:2007 +0x44
May 25 12:50:39 srsmpl095 influxd[63065]: github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/services/httpd.(*Handler).recovery.func1(0x2725240, 0xc292a59500, 0xc07e546600)
May 25 12:50:39 srsmpl095 influxd[63065]:         /go/src/github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/services/httpd/handler.go:1954 +0x17b
May 25 12:50:39 srsmpl095 influxd[63065]: net/http.HandlerFunc.ServeHTTP(0xc17b53ede0, 0x2725240, 0xc292a59500, 0xc07e546600)
May 25 12:50:39 srsmpl095 influxd[63065]:         /usr/local/go/src/net/http/server.go:2007 +0x44
May 25 12:50:39 srsmpl095 influxd[63065]: github.com/influxdata/plutonium/vendor/github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc17b53e240, 0x2725240, 0xc292a59500, 0xc07e546600)
May 25 12:50:39 srsmpl095 influxd[63065]:         /go/src/github.com/influxdata/plutonium/vendor/github.com/bmizerany/pat/mux.go:117 +0x153
May 25 12:50:39 srsmpl095 influxd[63065]: github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/services/httpd.(*Handler).ServeHTTP(0xc0696c1500, 0x2725240, 0xc292a59500, 0xc07e546600)
May 25 12:50:39 srsmpl095 influxd[63065]:         /go/src/github.com/influxdata/plutonium/vendor/github.com/influxdata/influxdb/services/httpd/handler.go:454 +0x395
May 25 12:50:39 srsmpl095 influxd[63065]: net/http.serverHandler.ServeHTTP(0xc098eb21c0, 0x2725240, 0xc292a59500, 0xc07e546600)
May 25 12:50:39 srsmpl095 influxd[63065]:         /usr/local/go/src/net/http/server.go:2802 +0xa4
May 25 12:50:39 srsmpl095 influxd[63065]: net/http.(*conn).serve(0xc09cbd41e0, 0x272d980, 0xc040fb0bc0)
May 25 12:50:39 srsmpl095 influxd[63065]:         /usr/local/go/src/net/http/server.go:1890 +0x875
May 25 12:50:39 srsmpl095 influxd[63065]: created by net/http.(*Server).Serve
May 25 12:50:39 srsmpl095 influxd[63065]:         /usr/local/go/src/net/http/server.go:2928 +0x384
```

When I run the following command, the raw data is successfully returned:
```
from(bucket:"telegraf/autogen")
  |> range(start: -1m)
```
But as soon as I add the `filter` line, the error above happens.

**Comment by russorat** [comment]
@elohmeier thanks for the report!
