### ISSUE TITLE
CLI panicing on startup

### ISSUE THREAD

**Issue by jsteenb2** [influxdata/influxdb#18408]
the CLI is panicing on all calls in developemtn since flux `v0.61.1` was introduced. THere is now a bug that manifests itself as:

```sh
> influx apply -f dash_test.yml
panic: Expected to find Prop for experimental/json parse, but Prop was missing.
goroutine 1 [running]:
github.com/influxdata/flux/runtime.MustLookupBuiltinType(0x55a568c, 0x11, 0x558dba8, 0x5, 0x0, 0x3, 0x657c440)
	github.com/influxdata/flux@v0.69.1/runtime/lookup.go:49 +0xa0
github.com/influxdata/flux/stdlib/experimental/json.init()
	github.com/influxdata/flux@v0.69.1/stdlib/experimental/json/json.go:21 +0xe3
```

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. `make influx`
2. `influx -h`
3. read panic

__Expected behavior:__
Not to panic

__Actual behavior:__
Panic

__Environment info:__

* System info: `Darwin 18.7.0 x86_64`

**Comment by jsteenb2** [comment]
must use the `make` file. Do not build with go toolchain by yourself now.
