### ISSUE TITLE
Fail to connect to localhost:8086

### ISSUE THREAD

**Issue by annie-anna** [influxdata/influxdb#18586]
I have followed the instructions on https://www.influxdata.com/blog/getting-started-python-influxdb/ (first pip install influxdb, and then run the script), but it reports the connection error
```
>>> from influxdb import InfluxDBClient
>>> client = InfluxDBClient(host='localhost', port=8086)
>>> client.create_database('pyexample')
Traceback (most recent call last):
  File "/mnt/c/Users/ThinkPad/source/temp/env/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/mnt/c/Users/ThinkPad/source/temp/env/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/mnt/c/Users/ThinkPad/source/temp/env/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/ThinkPad/source/temp/env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/mnt/c/Users/ThinkPad/source/temp/env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/mnt/c/Users/ThinkPad/source/temp/env/lib/python3.6/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/mnt/c/Users/ThinkPad/source/temp/env/lib/python3.6/site-packages/urllib3/connection.py", line 172, in _new_conn    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fa7b4d7f2e8>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/ThinkPad/source/temp/env/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/mnt/c/Users/ThinkPad/source/temp/env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/mnt/c/Users/ThinkPad/source/temp/env/lib/python3.6/site-packages/urllib3/util/retry.py", line 439, in increment    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8086): Max retries exceeded with url: /query?q=CREATE+DATABASE+%22pyexample%22 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa7b4d7f2e8>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/ThinkPad/source/temp/env/lib/python3.6/site-packages/influxdb/client.py", line 738, in create_database
    method="POST")
  File "/mnt/c/Users/ThinkPad/source/temp/env/lib/python3.6/site-packages/influxdb/client.py", line 518, in query
    expected_response_code=expected_response_code
  File "/mnt/c/Users/ThinkPad/source/temp/env/lib/python3.6/site-packages/influxdb/client.py", line 333, in request
    timeout=self._timeout
  File "/mnt/c/Users/ThinkPad/source/temp/env/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/mnt/c/Users/ThinkPad/source/temp/env/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/mnt/c/Users/ThinkPad/source/temp/env/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8086): Max retries exceeded with url: /query?q=CREATE+DATABASE+%22pyexample%22 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa7b4d7f2e8>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by abaglione** [comment]
I have the same issue (sorry I can't be of more help).

**Comment by abaglione** [comment]
@annie-anna Ah, I think I can help now. What system are you using? (e.g., Debian?)

My issue was that I assumed `client = InfluxDBClient(host='localhost', port=8086)` automatically causes influxdb to start in the background, but this isn't the case. The instructions at https://www.influxdata.com/blog/getting-started-python-influxdb/  leave out that you actually need to call "influxd" in a terminal prior to running any python code. Does that help?

**Comment by annie-anna** [comment]
Yes, but do you know how to stop service, so that I can change the binding address and start a new one? I have tried the command such as `sudo service influxdb stop` and `sudo systemctl enable influxdb`, but they don't work on Ubuntu.

**Comment by xuezhi123** [comment]
> @annie-anna Ah, I think I can help now. What system are you using? (e.g., Debian?)
> 
> My issue was that I assumed `client = InfluxDBClient(host='localhost', port=8086)` automatically causes influxdb to start in the background, but this isn't the case. The instructions at https://www.influxdata.com/blog/getting-started-python-influxdb/ leave out that you actually need to call "influxd" in a terminal prior to running any python code. Does that help?

Hi! I have the same issue. Could you please explain a bit more about how you solve it? Thank you very much.
