### ISSUE TITLE
Database write issue

### ISSUE THREAD

**Issue by rmkdn** [influxdata/influxdb#18681]
[2020-06-24 01:12:45,067] [MainThread] [DEBUG] [in /IOT/app/app.py :416] {'deviceId': 'X0390772', 'deviceName': 'rgbh01', 'tStamp': '06:55:37 24/06/2020', 'ipAddress': '100.82.57.110', 'rphvol': '247.43', 'yphvol': '246.37', 'bphvol': '248.23', 'rphcu': '0.19', 'yphcu': '0.14', 'bphcu': '0.12', 'necu': '0.06', 'phrpwr': '0.00', 'phrpwrfun': '-0.11', 'phrepwr': '0.00', 'ph3pwr': '0.11', 'freq': '49.98', 'rphpf': '-1.00', 'yphpf': '1.00', 'bphpf': '-1.00', 'avgpf': '1.00', 'rphang': '119.95', 'yphang': '119.68', 'bphang': '120.38', 'avgvol': '247.34', 'actimp': '0', 'actexp': '0', 'actimpfun': '0', 'actexpfun': '0', 'q1': '0', 'q4': '0', 'q2': '0', 'q3': '0', 'apactimp': '0', 'Apactexp': '0', 'netrec': '0', 'netapp': '0', 'actfwdABS': '3537.00', 'apfwdABS': '3605.00', 'relagfwdABS': '265.00', 'releadfwdABS': '179.00'}
[2020-06-24 01:12:45,068] [MainThread] [DEBUG] [in /IOT/app/app.py :423] deviceId: X0390772
[2020-06-24 01:12:45,068] [MainThread] [DEBUG] [in /IOT/app/app.py :439] ttd_devices,deviceId=X0390772,deviceName=rgbh01,tStamp=1592981737.0,ipAddress="100.82.57.110" rphvol=247.43,yphvol=246.37,bphvol=248.23,rphcu=0.19,yphcu=0.14,bphcu=0.12,necu=0.06,phrpwr=0.00,phrpwrfun=-0.11,phrepwr=0.00,ph3pwr=0.11,freq=49.98,rphpf=-1.00,yphpf=1.00,bphpf=-1.00,avgpf=1.00,rphang=119.95,yphang=119.68,bphang=120.38,avgvol=247.34,actimp=0,actexp=0,actimpfun=0,actexpfun=0,q1=0,q4=0,q2=0,q3=0,apactimp=0,Apactexp=0,netrec=0,netapp=0,actfwdABS=3537.00,apfwdABS=3605.00,relagfwdABS=265.00,releadfwdABS=179.00
[2020-06-24 01:12:45,073] [MainThread] [DEBUG] [in /IOT/app/app.py :444] <Response [400]>
[2020-06-24 01:12:45,073] [MainThread] [ERROR] [in /IOT/app/app.py :459] Exception while submitting feedback
Traceback (most recent call last):
  File "/IOT/app/app.py", line 448, in post
    response.raise_for_status()
  File "/opt/conda/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:8086/write?db=IOT
[2020-06-24 01:12:45,073] [MainThread] [DEBUG] [in /IOT/app/app.py :465] <Response 84 bytes [500 INTERNAL SERVER ERROR]>

**Comment by rmkdn** [comment]
Can anyone help me in resolving this issue please.

**Comment by rmkdn** [comment]
Iam receiving a json format data of some parameters and then processing it. Then I'm writing that data to database url but I'm getting the 404 error.
