### ISSUE TITLE
Can't access or delete measurement names with \r.   

### ISSUE THREAD

**Issue by europa502** [influxdata/influxdb#19440]
While running an automated code it accidentally created measurements with names '\r' and and '\r>'. I can neither delete them from InfluxDB CLI nor by using influxdb python module.    
```
client.get_list_measurements()
[{u'name': u'\r'}, {u'name': u'\r>'}, {u'name': u'measurement1'}]
```

When I query measurements from InfluxDB Client I get this - 
```
> show measurements
name: measurements
name
----

>
measurement1
```

It seems like \r is being internally processed by influxDB because when I try to delete the measurement I get this -
```
> delete from >
ERR: error parsing query: found >, expected identifier at line 1, char 15
> delete from "\r>"
ERR: error parsing query: found \r, expected identifier at line 1, char 17
> delete from "\\r>"
> delete from ">"
> delete from "\>"
ERR: error parsing query: found \>, expected identifier at line 1, char 17
> delete from "\\>"
> delete from "\\r >"
> delete from "\\r>"
> delete from "\r >"
ERR: error parsing query: found \r, expected identifier at line 1, char 17
```
I checked if the measurement got deleted after every command but it still exists.

I tried deleting them from python code but still failed. 
```
client.drop_measurement("\r>")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36-32\lib\site-packages\influxdb\client.py", line 774, in drop_measurement
    method="POST")
  File "C:\Python36-32\lib\site-packages\influxdb\client.py", line 518, in query
    expected_response_code=expected_response_code
  File "C:\Python36-32\lib\site-packages\influxdb\client.py", line 369, in request
    raise InfluxDBClientError(err_msg, response.status_code)
influxdb.exceptions.InfluxDBClientError: 400: {"error":"error parsing query: found BADSTRING, expected identifier at line 1, char 17"}

client.drop_measurement('\\r>')
client.get_list_measurements()
[{u'name': u'\r'}, {u'name': u'\r>'}, {u'name': u'measurement1'}]

```

The same issue exists when I try to select those measurements

**Comment by russorat** [comment]
@europa502 thanks for the issue. You might need to run https://docs.influxdata.com/influxdb/v1.8/tools/influx_inspect/#deletetsm to accomplish this.

**Comment by europa502** [comment]
Hi @russorat ,  thanks for the reply. I tried running influx_inspect but got this error 

```
C:\Users\europa\Downloads\influxdb-1.7.6-1>influx_inspect.exe deletetsm -measurement \r> -v -sanitize C://Users//europa//.influxdb//data//Station_Status//autogen//22//000000007-000000004.tsm
deletetsm: rename C://Users//europa//.influxdb//data//Station_Status//autogen//22//000000007-000000004.tsm.rewriting.tmp C://Users//europa//.influxdb//data//Station_Status//autogen//22//000000007-000000004.tsm: Access is denied.
```

I checked with influxd running in the background as well as with no other instances of influxdb running but the output was same. PS. cmd was opened in administrator mode. 

Furthermore when I ran the command with the measurement name in quotes it gave me a different output. 
```
C:\Users\europa\Downloads\influxdb-1.7.6-1>influx_inspect.exe deletetsm -measurement '\r>' -v -sanitize C://Users//europa//.influxdb//data//Station_Status//autogen//22//000000007-000000004.tsm
2020/09/16 13:17:30 processing: C://Users//europa//.influxdb//data//Station_Status//autogen//22//000000007-000000004.tsm
>#!~#Status_code (2019-07-08T13:31:44.7724794Z-2019-07-09T10:05:35.0638767Z) sz=2016
>#!~#Status_time (2019-07-08T05:58:45.4161926Z-2019-07-09T10:05:35.0638767Z) sz=2237
>#!~#Sys_Name (2019-07-08T05:58:45.4161926Z-2019-07-09T10:05:35.0638767Z) sz=2318
>#!~#Test_prog (2019-07-08T13:31:44.7724794Z-2019-07-09T10:05:35.0638767Z) sz=2079
>#!~#Testname (2019-07-08T05:58:45.4161926Z-2019-07-09T10:05:35.0638767Z) sz=2115
>#!~#Total_downtime (2019-07-08T05:58:45.4161926Z-2019-07-09T10:05:35.0638767Z) sz=2413
>#!~#Total_uptime (2019-07-08T05:58:45.4161926Z-2019-07-09T10:05:35.0638767Z) sz=2405
>#!~#Total_user_time (2019-07-08T05:58:45.4161926Z-2019-07-09T10:05:35.0638767Z) sz=2349
>#!~#Users (2019-07-08T05:58:45.4161926Z-2019-07-09T10:05:35.0638767Z) sz=2137
deletetsm: rename C://Users//europa//.influxdb//data//Station_Status//autogen//22//000000007-000000004.tsm.rewriting.tmp C://Users//europa//.influxdb//data//Station_Status//autogen//22//000000007-000000004.tsm: Access is denied.
```

But in either case it didn't reaname the file. In the folder  'C://Users//europa//.influxdb//data//Station_Status//autogen//22//' I can see 000000007-000000004.tsm.rewriting.tmp as well as 000000007-000000004.tsm. So I tried renaming the file manually but when I started influxdb and checked for the measurement name, the measurement was still there, I verified with the python module as well.

**Comment by russorat** [comment]
@europa502 well this wouldn't be the first time windows permissions have been a pain. I'm not sure I can help much there. 

I don't think you need to use the `-measurement` flag when using this command. it will attempt to remove all invalid keys (probably good to make a backup beforehand).
