### ISSUE TITLE
OSS 2.X: Backup and Restore no longer works

### ISSUE THREAD

**Issue by stephanie-engel** [influxdata/influxdb#19496]
**Description:**
When creating a backup, the `backupID` is not generated. As a result, `FetchBackupFile` returns a 500 error. Backup service located [here](https://github.com/influxdata/influxdb/blob/master/backup.go)

**Steps:**
1) Run the latest influxdb nightly image

2) Setup the initial user, org, and bucket
```
curl --request POST 'http://localhost:9999/api/v2/setup' \
--header 'Content-Type: application/json' \
--data-raw '{
    "username": "someone@email.com",
    "password": "password",
    "org": "my-org",
    "bucket": "my-bucket",
    "retentionPeriodHrs": 0
}'
```

3) Send a `POST` (with the newly generated token) to the `/backup` path
```
curl --request POST 'http://localhost:9999/api/v2/backup' \
--header 'Authorization: Token {yourToken}'
```

**Results:**
- The response shows:
```
{"files":["influxd.bolt"]}
```

instead of:

```
{"id":1,"files":["influxd.bolt"]}
```

- A subsequent `GET` to  http://localhost:9999/api/v2/backup/ won't work (and returns a 500 error) since the fetch backup logic requires a valid `backupID`, for example:
```
curl --request GET 'http://localhost:9999/api/v2/backup/null/file/influxd.bolt' \
--header 'Authorization: Token {yourToken} \
```
- **Also, please note:** If the user attempts to do a restore (from a version of influxd that used the original 2.x engine): 
1. stop `influxd`
2.  run `influxd restore --backup-path /path/to/backupFrom2XEngine`, 
then the backup itself will be successful, but restarting `influxd` will show the following errors:

```
$ ./influxd
2020-09-03T19:14:48.085810Z	info	Welcome to InfluxDB	{"log_id": "0P1M7paG000", "version": "2.0.0-beta.16", "commit": "50237d97ad", "build_date": "2020-09-03T05:22:14Z"}
panic: invalid freelist page: 9, page type is branch

goroutine 1 [running]:
github.com/coreos/bbolt.(*freelist).read(0xc000146280, 0xa699000)
	/go/pkg/mod/github.com/coreos/bbolt@v1.3.3/freelist.go:266 +0x2ab
github.com/coreos/bbolt.(*DB).loadFreelist.func1()
	/go/pkg/mod/github.com/coreos/bbolt@v1.3.3/db.go:316 +0xcf
sync.(*Once).doSlow(0xc000228d68, 0xc000967f38)
	/usr/local/go/src/sync/once.go:66 +0xe3
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:57
github.com/coreos/bbolt.(*DB).loadFreelist(0xc000228c00)
	/go/pkg/mod/github.com/coreos/bbolt@v1.3.3/db.go:309 +0x6a
github.com/coreos/bbolt.Open(0xc0005ecab0, 0x26, 0x180, 0xc000968150, 0x0, 0x0, 0x2ca5c40)
	/go/pkg/mod/github.com/coreos/bbolt@v1.3.3/db.go:286 +0x35e
github.com/influxdata/influxdb/v2/bolt.(*Client).Open(0xc000324000, 0x3da1500, 0xc0008d83c0, 0xc000010950, 0xc000b66060)
	/go/src/github.com/influxdata/influxdb/bolt/bbolt.go:57 +0x20a
github.com/influxdata/influxdb/v2/cmd/influxd/launcher.(*Launcher).run(0xc00020a300, 0x3da1500, 0xc0008d83c0, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/cmd/influxd/launcher/launcher.go:614 +0x943
github.com/influxdata/influxdb/v2/cmd/influxd/launcher.cmdRunE.func1(0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/cmd/influxd/launcher/launcher.go:141 +0x127
github.com/influxdata/influxdb/v2/kit/cli.NewCommand.func1(0xc0004b8000, 0x6087088, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/kit/cli/viper.go:61 +0x29
github.com/spf13/cobra.(*Command).execute(0xc0004b8000, 0xc0000d21c0, 0x0, 0x0, 0xc0004b8000, 0xc0000d21c0)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004b8000, 0xd, 0x0, 0x0)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/go/src/github.com/influxdata/influxdb/cmd/influxd/main.go:49 +0x1a7

**Comment by stephanie-engel** [comment]
closing because Stuart already identified the issue here #19316
