### ISSUE TITLE
Build error on master branch

### ISSUE THREAD

**Issue by dgnorton** [influxdata/influxdb#19941]
Not sure if this will repro for others but this was my experience.

__Steps to reproduce:__

1. `git clone https://github.com/influxdata/influxdb`
2. `make` works okay and `influxd` runs
3. Four days later: `git pull`
4. `go install ./cmd/influxd`
5. `influxd` panics when running `influx auth list` (see `panic details` below)

<details>
  <summary>panic details</summary>

```
goroutine 403 [running]:
runtime/debug.Stack(0x4, 0x4, 0x14)
        /home/dgnorton/src/go/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
        /home/dgnorton/src/go/src/runtime/debug/stack.go:16 +0x25
github.com/influxdata/influxdb/v2/http.(*AuthenticationHandler).ServeHTTP(0xc001ca0d20, 0x3bf1980, 0xc001ede1a0, 0xc0000ea300)
        /home/dgnorton/i/i2/influxdb/http/authentication_middleware.go:82 +0x34
github.com/influxdata/influxdb/v2/kit/transport/http.SetCORS.func1(0x3bf1980, 0xc001ede1a0, 0xc0000ea300)
        /home/dgnorton/i/i2/influxdb/kit/transport/http/middleware.go:34 +0xcb
net/http.HandlerFunc.ServeHTTP(0xc001d90540, 0x3bf1980, 0xc001ede1a0, 0xc0000ea300)
        /home/dgnorton/src/go/src/net/http/server.go:2042 +0x44
github.com/influxdata/influxdb/v2/kit/transport/http.SkipOptions.func1(0x3bf1980, 0xc001ede1a0, 0xc0000ea300)
        /home/dgnorton/i/i2/influxdb/kit/transport/http/middleware.go:72 +0xb8
net/http.HandlerFunc.ServeHTTP(0xc001d90560, 0x3bf1980, 0xc001ede1a0, 0xc0000ea300)
        /home/dgnorton/src/go/src/net/http/server.go:2042 +0x44
github.com/influxdata/influxdb/v2/http.(*PlatformHandler).ServeHTTP(0xc001d94510, 0x3bf1980, 0xc001ede1a0, 0xc0000ea300)
        /home/dgnorton/i/i2/influxdb/http/platform_handler.go:78 +0x154
github.com/go-chi/chi.(*Mux).Mount.func1(0x3bf1980, 0xc001ede1a0, 0xc0000ea300)
        /home/dgnorton/go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:298 +0x122
net/http.HandlerFunc.ServeHTTP(0xc001d90c60, 0x3bf1980, 0xc001ede1a0, 0xc0000ea300)
        /home/dgnorton/src/go/src/net/http/server.go:2042 +0x44
github.com/influxdata/influxdb/v2/kit/transport/http.Metrics.func1.1(0x3bf9c40, 0xc000ec6000, 0xc0000ea300)
        /home/dgnorton/i/i2/influxdb/kit/transport/http/middleware.go:57 +0x191
net/http.HandlerFunc.ServeHTTP(0xc001d9ed40, 0x3bf9c40, 0xc000ec6000, 0xc0000ea300)
        /home/dgnorton/src/go/src/net/http/server.go:2042 +0x44
github.com/influxdata/influxdb/v2/kit/transport/http.Trace.func1.1(0x3bf9c40, 0xc000ec6000, 0xc0000ea300)
        /home/dgnorton/i/i2/influxdb/kit/transport/http/middleware.go:97 +0x38f
net/http.HandlerFunc.ServeHTTP(0xc001d94a20, 0x3bf9c40, 0xc000ec6000, 0xc0000ea200)
        /home/dgnorton/src/go/src/net/http/server.go:2042 +0x44
github.com/go-chi/chi.(*ChainHandler).ServeHTTP(0xc001d9ed80, 0x3bf9c40, 0xc000ec6000, 0xc0000ea200)
        /home/dgnorton/go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/chain.go:31 +0x52
github.com/go-chi/chi.(*Mux).routeHTTP(0xc001d81140, 0x3bf9c40, 0xc000ec6000, 0xc0000ea200)
        /home/dgnorton/go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:431 +0x28b
net/http.HandlerFunc.ServeHTTP(0xc00011c6d0, 0x3bf9c40, 0xc000ec6000, 0xc0000ea200)
        /home/dgnorton/src/go/src/net/http/server.go:2042 +0x44
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc001d81140, 0x3bf9c40, 0xc000ec6000, 0xc0000ea100)
        /home/dgnorton/go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:86 +0x2d1
github.com/influxdata/influxdb/v2/http.(*Handler).ServeHTTP(0xc001d96700, 0x3bf9c40, 0xc000ec6000, 0xc0000ea100)
        /home/dgnorton/i/i2/influxdb/http/handler.go:143 +0x55
net/http.serverHandler.ServeHTTP(0xc001c9e000, 0x3bf9c40, 0xc000ec6000, 0xc0000ea100)
        /home/dgnorton/src/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc000e721e0, 0x3c06cc0, 0xc0000661c0)
        /home/dgnorton/src/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        /home/dgnorton/src/go/src/net/http/server.go:2969 +0x36c
```

</details>

6. `make clean` runs successfully
7. `make` (see `make error details` below)

<details>
  <summary>make error details</summary>

```
❯ make
Makefile:89: warning: overriding recipe for target 'bin/linux/influx'
Makefile:86: warning: ignoring old recipe for target 'bin/linux/influx'
make -C http all
make[1]: Entering directory '/home/dgnorton/i/i2/influxdb/http'
go generate -x
env GO111MODULE=on go run github.com/kevinburke/go-bindata/go-bindata -o swagger_gen.go -tags assets -nocompress -pkg http ./swagger.yml
verifying github.com/kevinburke/go-bindata@v3.11.0+incompatible: checksum mismatch
        downloaded: h1:GiPs9jxaG2xY1B5Dt/d/yHUOMlTk14uS35VcmHrdo4I=
        go.sum:     h1:RcC+GJNmrBHbGaOpQ9MBD8z22rdzlIm0esDRDkyxd4s=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
swagger.go:4: running "env": exit status 1
Makefile:16: recipe for target 'swagger_gen.go' failed
make[1]: *** [swagger_gen.go] Error 1
make[1]: Leaving directory '/home/dgnorton/i/i2/influxdb/http'
Makefile:80: recipe for target 'http' failed
make: *** [http] Error 2
```

</details>

__Environment info:__

* Ubuntu 18.04, Linux 4.15.0-121-generic x86_64
* `master` branch, commit 51ff6f7b5c0040088a39dbb78a7a166c3fcbf89c

**Comment by dgnorton** [comment]
Running `go clean --modcache` will get around the `make` error but not sure why the checksum changed. The panic went away after clearing the mod cache and running a clean build.

**Comment by psteinbachs** [comment]
FWIW, I did a clean build on Ubuntu 20.04 and wasn't able to reproduce.

**Comment by dgnorton** [comment]
Closing. I don't think this will happen in new dev environments and old dev environments like mine probably need to run `go clean --modcache` if they encounter this issue.

Possibly related to https://github.com/golang/go/issues/27093
