### ISSUE TITLE
Panic when setting --query-concurrency to large value

### ISSUE THREAD

**Issue by danxmoran** [influxdata/influxdb#20144]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Run `influxd --query-concurrency 9223372036854775807`

__Expected behavior:__
Either the program runs successfully, or the CLI errors out telling me the number is too big.

__Actual behavior:__
```
panic: sync: negative WaitGroup counter

goroutine 1 [running]:
sync.(*WaitGroup).Add(0xc0018362d0, 0x7fffffffffffffff)
        /Users/dan/.gvm/gos/go1.15/src/sync/waitgroup.go:74 +0x147
github.com/influxdata/influxdb/v2/query/control.New(0x7fffffffffffffff, 0x0, 0x7fffffffffffffff, 0x0, 0xa, 0xc00169a480, 0x0, 0x0, 0x0, 0xc001562f90, ...)
        /Users/dan/influxdb/query/control/controller.go:189 +0x7f5
github.com/influxdata/influxdb/v2/cmd/influxd/launcher.(*Launcher).run(0xc0005b0e00, 0x760eb80, 0xc00055d480, 0x0, 0x0)
        /Users/dan/influxdb/cmd/influxd/launcher/launcher.go:901 +0x3a38
github.com/influxdata/influxdb/v2/cmd/influxd/launcher.cmdRunE.func1(0x0, 0x0)
        /Users/dan/influxdb/cmd/influxd/launcher/launcher.go:149 +0x14c
github.com/influxdata/influxdb/v2/kit/cli.NewCommand.func1(0xc000130b00, 0xc000ce90e0, 0x0, 0x2, 0x0, 0x0)
        /Users/dan/influxdb/kit/cli/viper.go:62 +0x29
github.com/spf13/cobra.(*Command).execute(0xc000130b00, 0xc000184190, 0x2, 0x2, 0xc000130b00, 0xc000184190)
        /Users/dan/.gvm/pkgsets/go1.15/global/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000130b00, 0xc000d9ff48, 0x1, 0x1)
        /Users/dan/.gvm/pkgsets/go1.15/global/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/dan/.gvm/pkgsets/go1.15/global/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /Users/dan/influxdb/cmd/influxd/main.go:41 +0x31c
```
This is apparently a known problem in Go's `WaitGroup` impl: https://github.com/golang/go/issues/20687

__Environment info:__
InfluxDB OSS 2.0.2

**Comment by danxmoran** [comment]
The linked issue claims that `math.MaxInt32` (2147483647) is the max value a WaitGroup can handle. The server does attempt to boot with that value, but it's very slow to start / tear down.
