### ISSUE TITLE
Unexpected fault address 0x7fc7df806008

### ISSUE THREAD

**Issue by stepanurban** [influxdata/influxdb#20174]
Hi,
I'm running docker container in ACI quay.io/influxdb/influxdb:2.0.0-rc and getting following error
```
ts=2020-11-25T11:50:40.210429Z lvl=info msg="Welcome to InfluxDB" log_id=0QgohgKW000 version=2.0.0-rc.3 commit=f46a3bd91e build_date=2020-10-29T22:17:55Z
unexpected fault address 0x7fc7df806008
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7fc7df806008 pc=0xce7dc5]

goroutine 1 [running]:
runtime.throw(0x270bc5d, 0x5)
	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc0009677f0 sp=0xc0009677c0 pc=0x438c72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:717 +0x485 fp=0xc000967820 sp=0xc0009677f0 pc=0x44f5c5
go.etcd.io/bbolt.(*Cursor).search(0xc000967b00, 0x52d9930, 0xf, 0xf, 0x11)
	/go/pkg/mod/go.etcd.io/bbolt@v1.3.5/cursor.go:249 +0x65 fp=0xc0009678b8 sp=0xc000967820 pc=0xce7dc5
go.etcd.io/bbolt.(*Cursor).searchPage(0xc000967b00, 0x52d9930, 0xf, 0xf, 0x7fc7df807000)
	/go/pkg/mod/go.etcd.io/bbolt@v1.3.5/cursor.go:308 +0x16c fp=0xc000967960 sp=0xc0009678b8 pc=0xce838c
go.etcd.io/bbolt.(*Cursor).search(0xc000967b00, 0x52d9930, 0xf, 0xf, 0x12)
	/go/pkg/mod/go.etcd.io/bbolt@v1.3.5/cursor.go:265 +0x194 fp=0xc0009679f8 sp=0xc000967960 pc=0xce7ef4
go.etcd.io/bbolt.(*Cursor).seek(0xc000967b00, 0x52d9930, 0xf, 0xf, 0xc, 0x7fc8098d7108, 0xc0008cfba0, 0xc0003981c0, 0x41583b, 0xc000967b28, ...)
	/go/pkg/mod/go.etcd.io/bbolt@v1.3.5/cursor.go:159 +0x7d fp=0xc000967a68 sp=0xc0009679f8 pc=0xce765d
go.etcd.io/bbolt.(*Bucket).CreateBucket(0xc0003981d8, 0x52d9930, 0xf, 0xf, 0xc000a90f00, 0x39ab4e0, 0xc0002a5200)
	/go/pkg/mod/go.etcd.io/bbolt@v1.3.5/bucket.go:167 +0xf6 fp=0xc000967bd0 sp=0xc000967a68 pc=0xce3ad6
go.etcd.io/bbolt.(*Bucket).CreateBucketIfNotExists(0xc0003981d8, 0x52d9930, 0xf, 0xf, 0xc000a90f00, 0x0, 0x0)
	/go/pkg/mod/go.etcd.io/bbolt@v1.3.5/bucket.go:201 +0x4d fp=0xc000967c30 sp=0xc000967bd0 pc=0xce3ecd
go.etcd.io/bbolt.(*Tx).CreateBucketIfNotExists(...)
	/go/pkg/mod/go.etcd.io/bbolt@v1.3.5/tx.go:115
github.com/influxdata/influxdb/v2/bolt.(*Client).initialize.func1(0xc0003981c0, 0x1, 0xc0003981c0)
	/go/src/github.com/influxdata/influxdb/bolt/bbolt.go:92 +0x225 fp=0xc000967d48 sp=0xc000967c30 pc=0x12552e5
go.etcd.io/bbolt.(*DB).Update(0xc000246400, 0xc000967dd0, 0x0, 0x0)
	/go/pkg/mod/go.etcd.io/bbolt@v1.3.5/db.go:694 +0x96 fp=0xc000967db0 sp=0xc000967d48 pc=0xceafd6
github.com/influxdata/influxdb/v2/bolt.(*Client).initialize(0xc000871ae0, 0x39fb7e0, 0xc000a90d00, 0xc000967f00, 0xc000246400)
	/go/src/github.com/influxdata/influxdb/bolt/bbolt.go:73 +0x52 fp=0xc000967df0 sp=0xc000967db0 pc=0x12513d2
github.com/influxdata/influxdb/v2/bolt.(*Client).Open(0xc000871ae0, 0x39fb7e0, 0xc000a90d00, 0xc000010b58, 0xc0008f7260)
	/go/src/github.com/influxdata/influxdb/bolt/bbolt.go:63 +0x2b8 fp=0xc000967f60 sp=0xc000967df0 pc=0x1251118
github.com/influxdata/influxdb/v2/cmd/influxd/launcher.(*Launcher).run(0xc0003afc00, 0x39fb7e0, 0xc000a90d00, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/cmd/influxd/launcher/launcher.go:706 +0x929 fp=0xc00096bc88 sp=0xc000967f60 pc=0x19968c9
github.com/influxdata/influxdb/v2/cmd/influxd/launcher.cmdRunE.func1(0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/cmd/influxd/launcher/launcher.go:142 +0x125 fp=0xc00096bd40 sp=0xc00096bc88 pc=0x19a65e5
github.com/influxdata/influxdb/v2/kit/cli.NewCommand.func1(0xc00039adc0, 0xc000fa9140, 0x0, 0x6, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/kit/cli/viper.go:61 +0x29 fp=0xc00096bd60 sp=0xc00096bd40 pc=0x133de89
github.com/spf13/cobra.(*Command).execute(0xc00039adc0, 0xc000fa9080, 0x6, 0x6, 0xc00039adc0, 0xc000fa9080)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c fp=0xc00096be38 sp=0xc00096bd60 pc=0x1277cfc
github.com/spf13/cobra.(*Command).ExecuteC(0xc00039ab00, 0xc00096bf58, 0x1, 0x1)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375 fp=0xc00096bf10 sp=0xc00096be38 pc=0x1278875
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/go/src/github.com/influxdata/influxdb/cmd/influxd/main.go:48 +0x19e fp=0xc00096bf88 sp=0xc00096bf10 pc=0x1e6783e
runtime.main()
	/usr/local/go/src/runtime/proc.go:204 +0x209 fp=0xc00096bfe0 sp=0xc00096bf88 pc=0x43b469
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00096bfe8 sp=0xc00096bfe0 pc=0x471a41

goroutine 12 [syscall]:
os/signal.signal_recv(0x1)
	/usr/local/go/src/runtime/sigqueue.go:147 +0x9d
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	/usr/local/go/src/os/signal/signal.go:150 +0x45

goroutine 22 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0001014a0)
	/go/pkg/mod/go.opencensus.io@v0.22.3/stats/view/worker.go:154 +0x105
created by go.opencensus.io/stats/view.init.0
	/go/pkg/mod/go.opencensus.io@v0.22.3/stats/view/worker.go:32 +0x57

goroutine 23 [chan receive]:
github.com/influxdata/flux/execute.createOperatorProfiler.func1(0xc00038c310)
	/go/pkg/mod/github.com/influxdata/flux@v0.91.0/execute/profiler.go:108 +0xe5
created by github.com/influxdata/flux/execute.createOperatorProfiler
	/go/pkg/mod/github.com/influxdata/flux@v0.91.0/execute/profiler.go:106 +0xb8

goroutine 24 [chan receive]:
github.com/influxdata/influxdb/v2/bolt.init.0.func1()
	/go/src/github.com/influxdata/influxdb/bolt/metrics.go:115 +0x8a
created by github.com/influxdata/influxdb/v2/bolt.init.0
	/go/src/github.com/influxdata/influxdb/bolt/metrics.go:114 +0xdf

goroutine 13 [select]:
github.com/influxdata/influxdb/v2/kit/signals.WithSignals.func1(0xc00095f450, 0x39fb7e0, 0xc000a90cc0, 0xc000fa91a0)
	/go/src/github.com/influxdata/influxdb/kit/signals/context.go:18 +0xe5
created by github.com/influxdata/influxdb/v2/kit/signals.WithSignals
	/go/src/github.com/influxdata/influxdb/kit/signals/context.go:16 +0xcf
```

**Comment by danxmoran** [comment]
Hi @stepanurban, does the error still occur if you run the latest Docker image? quay.io/influxdb/influxdb:v2.0.2

**Comment by danxmoran** [comment]
Closing as stale
