### ISSUE TITLE
panic:runtime error: invalid memory address or nil pointer dereference InfluxDB v1.7.3

### ISSUE THREAD

**Issue by sairameshv** [influxdata/influxdb#20498]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Bring Up InfluxDB microservice in a Kubernetes cluster
3. Insert some sample influx points at some regular intervals of time.
4. Delete a few inserted points randomly.
5. Query the points present in the database at a random intervals of time using any rest client.

__Expected behavior:__
The Query should return success response along with the valid payload.

__Actual behavior:__
The query was failing intermittently with the following panic logs.

__Environment info:__

* Linux 4.19.81-OpenNetworkLinux x86_64
* InfluxDB v1.7.3 (git: 1.7 698dbc789aff13c2678357a6b93ff73dd7136571)
* Kubernetes v1.16.3, InfluxDB running as a docker image with tag "1.7.3-alpine"

__Rest Client Error Log:__
Error : unable to decode json: received status code 200 err: net/http: request canceled (Client.Timeout exceeded while reading body)

__Logs:__
ts=2020-12-17T05:53:09.839689Z lvl=info msg="Executing query" log_id=0R7jaA6W000 service=query query="SELECT * FROM SDPONAlarms.sdponalarm./.*/ WHERE time >= 0s AND alarmID = '10026' ORDER BY time DESC LIMIT 1000"
ts=2020-12-17T05:53:09.874834Z lvl=error msg="SELECT * FROM SDPONAlarms.sdponalarm./.*/ WHERE time >= 0s AND alarmID = '10026' ORDER BY time DESC LIMIT 1000 [panic:runtime error: invalid memory address or nil pointer dereference] goroutine 626925 [running]:\nruntime/debug.Stack(0xc030484820, 0xc0004fa460, 0x6e)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/influxdata/influxdb/query.(*Executor).recover(0xc0005d4540, 0xc030484820, 0xc024d6b140)\n\t/go/src/github.com/influxdata/influxdb/query/executor.go:394 +0xaf\npanic(0x1085120, 0x1d60470)\n\t/usr/local/go/src/runtime/panic.go:513 +0x1b9\ngithub.com/influxdata/influxdb/query.Iterators.Close(0xc04a8a7b00, 0x3, 0x8, 0xc03ed89db0, 0x1397680)\n\t/go/src/github.com/influxdata/influxdb/query/iterator.go:48 +0x50\ngithub.com/influxdata/influxdb/coordinator.(*LocalShardMapping).CreateIterator(0xc013c763c0, 0x138cb80, 0xc017281230, 0xc03ed89db0, 0x0, 0x0, 0xc054796000, 0x1f, 0x1f, 0x0, ...)\n\t/go/src/github.com/influxdata/influxdb/coordinator/shard_mapper.go:202 +0x2b6\ngithub.com/influxdata/influxdb/query.buildAuxIterator.func1(0xc049508100, 0x1, 0x1, 0x7ff9ce0f4f58, 0xc013c763c0, 0x138cb80, 0xc017281230, 0xc02252f208, 0xc02252f188, 0x0, ...)\n\t/go/src/github.com/influxdata/influxdb/query/select.go:779 +0x13b\ngithub.com/influxdata/influxdb/query.buildAuxIterator(0x138cb80, 0xc017281230, 0x7ff9ce0f4f58, 0xc013c763c0, 0xc049508100, 0x1, 0x1, 0x0, 0x0, 0xc054796000, ...)\n\t/go/src/github.com/influxdata/influxdb/query/select.go:799 +0x3ad\ngithub.com/influxdata/influxdb/query.buildCursor(0x138cb80, 0xc017281230, 0xc03efafc00, 0x7ff9ce0f4f58, 0xc013c763c0, 0x0, 0x0, 0xc054796000, 0x1f, 0x1f, ...)\n\t/go/src/github.com/influxdata/influxdb/query/select.go:701 +0x1606\ngithub.com/influxdata/influxdb/query.(*preparedStatement).Select(0xc03f12c160, 0x138cb80, 0xc017281230, 0x138ed00, 0x1d96f30, 0x0, 0x0)\n\t/go/src/github.com/influxdata/influxdb/query/select.go:119 +0x180\ngithub.com/influxdata/influxdb/query.Select(0x138cd40, 0xc03cc820c0, 0xc038ae4b00, 0x1376400, 0xc000661820, 0x138ed00, 0x1d96f30, 0x0, 0x0, 0x0, ...)\n\t/go/src/github.com/influxdata/influxdb/query/select.go:96 +0xfe\ngithub.com/influxdata/influxdb/coordinator.(*StatementExecutor).createIterators(0xc0001c6b60, 0x138cd40, 0xc03cc820c0, 0xc038ae4b00, 0xc04c60600f, 0xb, 0x0, 0x0, 0x138ed00, 0x1d96f30, ...)\n\t/go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:638 +0x113\ngithub.com/influxdata/influxdb/coordinator.(*StatementExecutor).executeSelectStatement(0xc0001c6b60, 0xc038ae4b00, 0xc03cc820c0, 0x0, 0x0)\n\t/go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:542 +0x99\ngithub.com/influxdata/influxdb/coordinator.(*StatementExecutor).ExecuteStatement(0xc0001c6b60, 0x138dac0, 0xc038ae4b00, 0xc03cc820c0, 0x1, 0x1)\n\t/go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:64 +0x2400\ngithub.com/influxdata/influxdb/query.(*Executor).executeQuery(0xc0005d4540, 0xc030484820, 0xc04c60600f, 0xb, 0x0, 0x0, 0x138ed00, 0x1d96f30, 0x2710, 0x0, ...)\n\t/go/src/github.com/influxdata/influxdb/query/executor.go:334 +0x355\ncreated by github.com/influxdata/influxdb/query.(*Executor).ExecuteQuery\n\t/go/src/github.com/influxdata/influxdb/query/executor.go:236 +0xc9\n" log_id=0R7jaA6W000 service=query

**Comment by sairameshv** [comment]
Any update on this issue?
