### ISSUE TITLE
e2e tests are incredibly flaky

### ISSUE THREAD

**Issue by danxmoran** [influxdata/influxdb#20718]
Our e2e job fails more often than not in CI. See if the changes applied to the `ui` repo in #20482 could also work for our copy of the UI code.

**Comment by danxmoran** [comment]
A sample list of failures from the past few days:

- [ ] The Query Builder from the Data Explorer creates a query, edits it to add another field, then views its results with pride and satisfaction - creates a query, edits it to add another field, then views its results with pride and satisfaction (this is the most common failure)
```
AssertionError: Timed out retrying: Expected to find content: 'Configure' but never did.
    at Context.eval (http://localhost:8086/__cypress/tests?p=cypress/e2e/queryBuilder.test.ts:53:16)
```

- [ ] DataExplorer raw script editing shows flux signatures - shows flux signatures (2nd-most common failure)
```
AssertionError: Timed out retrying: Expected to find element: `.signature`, but never found it.
    at Context.eval (http://localhost:8086/__cypress/tests?p=cypress/e2e/explorer.test.ts:871:42)
```

- [ ] Buckets from the buckets index page can create a bucket - can create a bucket
```
AssertionError: Timed out retrying: Expected to find element: `[data-testid="create-label-form--submit"]`, but never found it.
    at Context.exports.getByTestID (http://localhost:8086/__cypress/tests?p=cypress/support/index.js:870:15)
```

- [ ] DataExplorer raw script editing can filter aggregation functions by name from script editor mode - can filter aggregation functions by name from script editor mode
```
AssertionError: Timed out retrying: expected '<input.cf-input-field>' to have value 'covariance', but the value was 'c'
    at Context.eval (http://localhost:8086/__cypress/tests?p=cypress/e2e/explorer.test.ts:938:18)
```

- [ ] Dashboard can create, clone and destroy cells & toggle in and out of presentation mode - can create, clone and destroy cells & toggle in and out of presentation mode
```
CypressError: `cy.click()` can only be called on a single element. Your subject contained 2 elements. Pass `{ multiple: true }` if you want to serially click each element.

https://on.cypress.io/click
    at mouseAction (http://localhost:8086/__cypress/runner/cypress_runner.js:151230:17)
    at Context.click (http://localhost:8086/__cypress/runner/cypress_runner.js:151374:14)
    at Context.<anonymous> (http://localhost:8086/__cypress/runner/cypress_runner.js:168170:21)
From Your Spec Code:
    at Context.eval (http://localhost:8086/__cypress/tests?p=cypress/e2e/dashboardsView.test.ts:670:48)
```

- [ ] Variables can create and delete a label and filter a variable by label name & sort by variable name - can create and delete a label and filter a variable by label name & sort by variable name
```
CypressError: Timed out retrying: `cy.click()` failed because this element is detached from the DOM.

`<button class="cf-button cf-button-sm cf-button-secondary cf-button-square inline-labels--add" title="Add labels" tabindex="0" type="button" data-testid="inline-labels--add">...</button>`

Cypress requires elements be attached in the DOM to interact with them.

The previous command that ran was:

  > `cy.get()`

This DOM element likely became detached somewhere between the previous and current command.

Common situations why this happens:
  - Your JS framework re-rendered asynchronously
  - Your app code reacted to an event firing and removed the element

You typically need to re-query for the element or add 'guards' which delay Cypress from running new commands.

https://on.cypress.io/element-has-detached-from-dom
    at $Cy.ensureAttached (http://localhost:8086/__cypress/runner/cypress_runner.js:160242:24)
    at runAllChecks (http://localhost:8086/__cypress/runner/cypress_runner.js:149293:12)
    at retryActionability (http://localhost:8086/__cypress/runner/cypress_runner.js:149352:16)
    at tryCatcher (http://localhost:8086/__cypress/runner/cypress_runner.js:9956:23)
    at Function.Promise.attempt.Promise.try (http://localhost:8086/__cypress/runner/cypress_runner.js:7230:29)
    at tryFn (http://localhost:8086/__cypress/runner/cypress_runner.js:163481:24)
    at whenStable (http://localhost:8086/__cypress/runner/cypress_runner.js:163522:12)
    at http://localhost:8086/__cypress/runner/cypress_runner.js:163040:16
    at tryCatcher (http://localhost:8086/__cypress/runner/cypress_runner.js:9956:23)
    at Promise._settlePromiseFromHandler (http://localhost:8086/__cypress/runner/cypress_runner.js:7891:31)
    at Promise._settlePromise (http://localhost:8086/__cypress/runner/cypress_runner.js:7948:18)
    at Promise._settlePromise0 (http://localhost:8086/__cypress/runner/cypress_runner.js:7993:10)
    at Promise._settlePromises (http://localhost:8086/__cypress/runner/cypress_runner.js:8073:18)
    at Promise._fulfill (http://localhost:8086/__cypress/runner/cypress_runner.js:8017:18)
    at http://localhost:8086/__cypress/runner/cypress_runner.js:9631:46
From Your Spec Code:
    at Context.eval (http://localhost:8086/__cypress/tests?p=cypress/e2e/variables.test.ts:171:50)
```

**Comment by danxmoran** [comment]
Closing this now that we're using the UI team's e2e suite, and it's been looking pretty stable.
