### ISSUE TITLE
TSM compactions: Recover from runtime errors

### ISSUE THREAD

**Issue by jla** [influxdata/influxdb#20883]
__Proposal:__
InfluxDB should be able to recover from runtime errors during compaction.

Compaction is a complex process that involves reading, processing and writing large amounts of data, sooner or later a disk or memory error could lead to unexpected errors during this process.

__Current behavior:__
InfluxDB panics and it's unable to fully restart until corrupt TSM files are manually removed.

__Desired behavior:__
InfluxDB to carry on. 

__Use case:__
Been able to record new data should be a priority over optimising the access to the old one.

```
panic: runtime error: slice bounds out of range

goroutine 671 [running]:
github.com/influxdata/influxdb/tsdb/cursors.(*BooleanArray).Include(0xc00933aff0, 0x1648042fc1f9fd28, 0x1648046305449fec)
        /go/src/github.com/influxdata/influxdb/tsdb/cursors/arrayvalues.gen.go:918 +0x263
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*tsmBatchKeyIterator).combineBoolean(0xc012438f00, 0xc032c04501, 0xe3, 0xc032c045a0, 0x1)
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.gen.go:1967 +0x2f7
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*tsmBatchKeyIterator).mergeBoolean(0xc012438f00)
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.gen.go:1910 +0x1aa
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*tsmBatchKeyIterator).merge(0xc012438f00)
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:1833 +0x1d5
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*tsmBatchKeyIterator).Next(0xc012438f00, 0x2182c07dd)
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:1695 +0x119f
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).write(0xc0001e2900, 0xc000040620, 0x66, 0x21765e0, 0xc012438f00, 0x153c501, 0x0, 0x0)
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:1140 +0x1c8
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).writeNewFiles(0xc0001e2900, 0x1c1, 0x3, 0xc011cb8200, 0x5, 0x8, 0x21765e0, 0xc012438f00, 0x1, 0x21765e0, ...)
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:1044 +0x1d2
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).compact(0xc0001e2900, 0x1f8cc00, 0xc011cb8200, 0x5, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:952 +0x40e
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).CompactFull(0xc0001e2900, 0xc011cb8200, 0x5, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:970 +0x170
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*compactionStrategy).compactGroup(0xc000152af0)
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:2158 +0x17db
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*compactionStrategy).Apply(0xc000152af0)
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:2135 +0x54
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).compactHiPriorityLevel.func1(0xc014990190, 0xc0001a2280, 0x2, 0xc000152af0)
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:2052 +0xea
created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).compactHiPriorityLevel
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:2047 +0x12a
```

**Comment by domguard** [comment]
Same here with InfluxDB 1.8, not able to restart

**Comment by davidby-influx** [comment]
A number of the problems that caused unrecoverable compaction errors have now been fixed, lowering the importance of this requested feature

See these PRs:
- https://github.com/influxdata/influxdb/pull/26025
- https://github.com/influxdata/influxdb/pull/26022
- https://github.com/influxdata/influxdb/pull/24520
- https://github.com/influxdata/influxdb/pull/24565
