### ISSUE TITLE
invalid tag format: tag ending with \\\\

### ISSUE THREAD

**Issue by arindamchoudhury** [influxdata/influxdb#21847]
influxdb version: 1.8.6
influxdb client version: 5.3.1

```
data = 'check_invalid_tag,mount_point=d:\\\\,physical_filename=d:\\\\MicrosoftSQLServer\\\\MSSQL14.X3V12PRE\\\\MSSQL\\\\Data\\\\tempdb.mdf size=50 1626247937'

influx_client.write_points([data], time_precision='s', database='arindam', protocol='line')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/influxdb/client.py", line 608, in write_points
    consistency=consistency)
  File "/usr/local/lib/python3.5/dist-packages/influxdb/client.py", line 685, in _write_points
    protocol=protocol
  File "/usr/local/lib/python3.5/dist-packages/influxdb/client.py", line 419, in write
    headers=headers
  File "/usr/local/lib/python3.5/dist-packages/influxdb/client.py", line 378, in request
    raise InfluxDBClientError(err_msg, response.status_code)
influxdb.exceptions.InfluxDBClientError: 400: {"error":"unable to parse 'check_invalid_tag,mount_point=d:\\\\,physical_filename=d:\\\\MicrosoftSQLServer\\\\MSSQL14.X3V12PRE\\\\MSSQL\\\\Data\\\\tempdb.mdf size=50 1626247937': invalid tag format"}
```

**Comment by arindamchoudhury** [comment]
looks like it's a influxdb-python bug
