### ISSUE TITLE
page 20 already freed

### ISSUE THREAD

**Issue by drahnr** [influxdata/influxdb#22825]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. podman pull influx:latest
2. podman run influx:latest
3. crash page double free

__Expected behavior:__
Launch just fine.

__Actual behavior:__

```
Nov 04 13:48:47 jurassicpark podman[179806]: time="2021-11-04T12:48:47Z" level=info msg="reset OCSP cache file. /home/influxdb/.cache/snowflake/ocsp_response_cache.json" func="gosnowflake.(*defaultLogger).Infof" file="log.go:104"
Nov 04 13:48:47 jurassicpark podman[179806]: time="2021-11-04T12:48:47Z" level=info msg="reading OCSP Response cache file. /home/influxdb/.cache/snowflake/ocsp_response_cache.json\n" func="gosnowflake.(*defaultLogger).Infof" file="log.go:104"
Nov 04 13:48:47 jurassicpark podman[179806]: time="2021-11-04T12:48:47Z" level=error msg="failed to open. Ignored. open /home/influxdb/.cache/snowflake/ocsp_response_cache.json: no such file or directory\n" func="gosnowflake.(*defaultLogger).Errorf" file="log.go:120"
Nov 04 13:48:47 jurassicpark podman[179806]: time="2021-11-04T12:48:47Z" level=info msg="reset OCSP cache file. /home/influxdb/.cache/snowflake/ocsp_response_cache.json" func="gosnowflake.(*defaultLogger).Infof" file="log.go:104"
Nov 04 13:48:47 jurassicpark podman[179806]: time="2021-11-04T12:48:47Z" level=info msg="reading OCSP Response cache file. /home/influxdb/.cache/snowflake/ocsp_response_cache.json\n" func="gosnowflake.(*defaultLogger).Infof" file="log.go:104"
Nov 04 13:48:47 jurassicpark podman[179806]: time="2021-11-04T12:48:47Z" level=error msg="failed to open. Ignored. open /home/influxdb/.cache/snowflake/ocsp_response_cache.json: no such file or directory\n" func="gosnowflake.(*defaultLogger).Errorf" file="log.go:120"
Nov 04 13:48:47 jurassicpark podman[179806]: 2021-11-04T12:48:47.952501779Z        info        found existing boltdb file, skipping setup wrapper        {"system": "docker", "bolt_path": "/var/lib/influxdb2/influxd.bolt"}
Nov 04 13:48:47 jurassicpark podman[179806]: time="2021-11-04T12:48:47Z" level=info msg="reset OCSP cache file. /home/influxdb/.cache/snowflake/ocsp_response_cache.json" func="gosnowflake.(*defaultLogger).Infof" file="log.go:104"
Nov 04 13:48:47 jurassicpark podman[179806]: time="2021-11-04T12:48:47Z" level=info msg="reading OCSP Response cache file. /home/influxdb/.cache/snowflake/ocsp_response_cache.json\n" func="gosnowflake.(*defaultLogger).Infof" file="log.go:104"
Nov 04 13:48:47 jurassicpark podman[179806]: time="2021-11-04T12:48:47Z" level=error msg="failed to open. Ignored. open /home/influxdb/.cache/snowflake/ocsp_response_cache.json: no such file or directory\n" func="gosnowflake.(*defaultLogger).Errorf" file="log.go:120"
Nov 04 13:48:54 jurassicpark podman[179806]: ts=2021-11-04T12:48:54.504602Z lvl=info msg="Welcome to InfluxDB" log_id=0XbklSv0000 version=2.0.9 commit=d1233b7951 build_date=2021-10-01T21:09:53Z
Nov 04 13:48:54 jurassicpark podman[179806]: panic: page 20 already freed
Nov 04 13:48:54 jurassicpark podman[179806]: goroutine 1 [running]:
Nov 04 13:48:54 jurassicpark podman[179806]: go.etcd.io/bbolt.(*freelist).free(0xc001666080, 0x12d19a, 0x7fd0c2e46000)
Nov 04 13:48:54 jurassicpark podman[179806]:         /home/circleci/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/freelist.go:175 +0x2c8
Nov 04 13:48:54 jurassicpark podman[179806]: go.etcd.io/bbolt.(*node).spill(0xc00167e0e0)
Nov 04 13:48:54 jurassicpark podman[179806]:         /home/circleci/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/node.go:359 +0x216
Nov 04 13:48:54 jurassicpark podman[179806]: go.etcd.io/bbolt.(*node).spill(0xc00167e070)
Nov 04 13:48:54 jurassicpark podman[179806]:         /home/circleci/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/node.go:346 +0xaa
Nov 04 13:48:54 jurassicpark podman[179806]: go.etcd.io/bbolt.(*node).spill(0xc00167e000)
Nov 04 13:48:54 jurassicpark podman[179806]:         /home/circleci/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/node.go:346 +0xaa
Nov 04 13:48:54 jurassicpark podman[179806]: go.etcd.io/bbolt.(*Bucket).spill(0xc000a2f198)
Nov 04 13:48:54 jurassicpark podman[179806]:         /home/circleci/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/bucket.go:570 +0x32f
Nov 04 13:48:54 jurassicpark podman[179806]: go.etcd.io/bbolt.(*Tx).Commit(0xc000a2f180)
Nov 04 13:48:54 jurassicpark podman[179806]:         /home/circleci/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/tx.go:160 +0xe7
Nov 04 13:48:54 jurassicpark podman[179806]: go.etcd.io/bbolt.(*DB).Update(0x0, 0xc0005acb98)
Nov 04 13:48:54 jurassicpark podman[179806]:         /home/circleci/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:748 +0xe5
Nov 04 13:48:54 jurassicpark podman[179806]: github.com/influxdata/influxdb/v2/bolt.(*Client).initialize(0xc00055c880, {0x1f, 0x0})
Nov 04 13:48:54 jurassicpark podman[179806]:         /home/circleci/go/src/github.com/influxdata/influxdb/bolt/bbolt.go:88 +0x39
Nov 04 13:48:54 jurassicpark podman[179806]: github.com/influxdata/influxdb/v2/bolt.(*Client).Open(0xc00166e0c0, {0x39711d8, 0xc00005e300})
Nov 04 13:48:54 jurassicpark podman[179806]:         /home/circleci/go/src/github.com/influxdata/influxdb/bolt/bbolt.go:76 +0x20e
Nov 04 13:48:54 jurassicpark podman[179806]: github.com/influxdata/influxdb/v2/cmd/influxd/launcher.(*Launcher).run(0xc00028cb60, {0x39711d8, 0xc00005e240}, 0xc00043c600)
Nov 04 13:48:54 jurassicpark podman[179806]:         /home/circleci/go/src/github.com/influxdata/influxdb/cmd/influxd/launcher/launcher.go:260 +0xb36
Nov 04 13:48:54 jurassicpark podman[179806]: github.com/influxdata/influxdb/v2/cmd/influxd/launcher.cmdRunE.func1()
Nov 04 13:48:54 jurassicpark podman[179806]:         /home/circleci/go/src/github.com/influxdata/influxdb/cmd/influxd/launcher/cmd.go:106 +0x2ec
Nov 04 13:48:54 jurassicpark podman[179806]: github.com/influxdata/influxdb/v2/kit/cli.NewCommand.func1(0xc0000e2dc0, {0x9b7b308, 0x0, 0x0})
Nov 04 13:48:54 jurassicpark podman[179806]:         /home/circleci/go/src/github.com/influxdata/influxdb/kit/cli/viper.go:54 +0x1e
Nov 04 13:48:54 jurassicpark podman[179806]: github.com/spf13/cobra.(*Command).execute(0xc0000e2dc0, {0xc00004e210, 0x0, 0x0})
Nov 04 13:48:54 jurassicpark podman[179806]:         /home/circleci/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x60e
Nov 04 13:48:54 jurassicpark podman[179806]: github.com/spf13/cobra.(*Command).ExecuteC(0xc0000e2dc0)
Nov 04 13:48:54 jurassicpark podman[179806]:         /home/circleci/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x3ad
Nov 04 13:48:54 jurassicpark podman[179806]: github.com/spf13/cobra.(*Command).Execute(...)
Nov 04 13:48:54 jurassicpark podman[179806]:         /home/circleci/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
Nov 04 13:48:54 jurassicpark podman[179806]: main.main()
Nov 04 13:48:54 jurassicpark podman[179806]:         /home/circleci/go/src/github.com/influxdata/influxdb/cmd/influxd/main.go:53 +0x41b
```

__Environment info:__

* System info: Linux 5.14.15-200.fc34.x86_64 x86_64
* InfluxDB version: `2.0.9`
* Other relevant environment details: `podman`

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively happening.
# Note: This command will run for ~30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=30s"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz` and `iostat.txt` output files.
```

**Comment by timhallinflux** [comment]
re-try with 2.1.1

**Comment by drahnr** [comment]
```
Nov 17 11:43:02 jurassicpark systemd[1]: Starting influxdb...
Nov 17 11:43:02 jurassicpark podman[4190469]: time="2021-11-17T11:43:02+01:00" level=warning msg="Failed to decode the keys [\"storage.options.btrfs.mountopt\"] from \"/etc/containers/storage.conf\"."
Nov 17 11:43:02 jurassicpark podman[4190469]: Error: no container with name or ID "influxdb2-instance" found: no such container
Nov 17 11:43:02 jurassicpark podman[4190507]: time="2021-11-17T11:43:02+01:00" level=warning msg="Failed to decode the keys [\"storage.options.btrfs.mountopt\"] from \"/etc/containers/storage.conf\"."
Nov 17 11:43:02 jurassicpark podman[4190507]: Error: no container with name or ID "influxdb2-instance" found: no such container
Nov 17 11:43:02 jurassicpark systemd[1]: Started influxdb.
Nov 17 11:43:02 jurassicpark podman[4190584]: time="2021-11-17T11:43:02+01:00" level=warning msg="Failed to decode the keys [\"storage.options.btrfs.mountopt\"] from \"/etc/containers/storage.conf\"."
Nov 17 11:43:04 jurassicpark podman[4190584]: 2021-11-17 11:43:04.438023422 +0100 CET m=+1.676463841 container create 65838e3053535f42d0cff025f429f5e932ee1159a6755a3a4dedd85d07e04807 (image=docker.io/library/influxdb:latest, name=influxdb2-instance)
Nov 17 11:43:04 jurassicpark oci-umount[4190724]: umounthook <debug>: prestart container_id:65838e305353 rootfs:/var/lib/containers/storage/btrfs/subvolumes/819547aec54b61946cf8f2957bdc0d391c880684febff15c15529b67e6e2ec15
Nov 17 11:43:04 jurassicpark podman[4190584]: 2021-11-17 11:43:04.662060399 +0100 CET m=+1.900500815 container init 65838e3053535f42d0cff025f429f5e932ee1159a6755a3a4dedd85d07e04807 (image=docker.io/library/influxdb:latest, name=influxdb2-instance)
Nov 17 11:43:04 jurassicpark podman[4190584]: 2021-11-17 11:43:04.672277236 +0100 CET m=+1.910717659 container start 65838e3053535f42d0cff025f429f5e932ee1159a6755a3a4dedd85d07e04807 (image=docker.io/library/influxdb:latest, name=influxdb2-instance)
Nov 17 11:43:04 jurassicpark podman[4190584]: 2021-11-17 11:43:04.672351715 +0100 CET m=+1.910792167 container attach 65838e3053535f42d0cff025f429f5e932ee1159a6755a3a4dedd85d07e04807 (image=docker.io/library/influxdb:latest, name=influxdb2-instance)
Nov 17 11:43:04 jurassicpark podman[4190584]: 2021-11-17T10:43:04.970897199Z        info        found existing boltdb file, skipping setup wrapper        {"system": "docker", "bolt_path": "/var/lib/influxdb2/influxd.bolt"}
Nov 17 11:43:05 jurassicpark podman[4190584]: ts=2021-11-17T10:43:05.094783Z lvl=info msg="Welcome to InfluxDB" log_id=0XsNjN1W000 version=2.1.1 commit=657e1839de build_date=2021-11-09T03:03:48Z
Nov 17 11:43:05 jurassicpark podman[4190584]: panic: page 20 already freed
Nov 17 11:43:05 jurassicpark podman[4190584]: goroutine 1 [running]:
Nov 17 11:43:05 jurassicpark podman[4190584]: go.etcd.io/bbolt.(*freelist).free(0xc000598100, 0x12d19a, 0x7fb48507d000)
Nov 17 11:43:05 jurassicpark podman[4190584]:         /home/circleci/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/freelist.go:175 +0x2c8
Nov 17 11:43:05 jurassicpark podman[4190584]: go.etcd.io/bbolt.(*node).spill(0xc0005a6d20)
Nov 17 11:43:05 jurassicpark podman[4190584]:         /home/circleci/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/node.go:359 +0x216
Nov 17 11:43:05 jurassicpark podman[4190584]: go.etcd.io/bbolt.(*node).spill(0xc0005a6cb0)
Nov 17 11:43:05 jurassicpark podman[4190584]:         /home/circleci/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/node.go:346 +0xaa
Nov 17 11:43:05 jurassicpark podman[4190584]: go.etcd.io/bbolt.(*node).spill(0xc0005a6c40)
Nov 17 11:43:05 jurassicpark podman[4190584]:         /home/circleci/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/node.go:346 +0xaa
Nov 17 11:43:05 jurassicpark podman[4190584]: go.etcd.io/bbolt.(*Bucket).spill(0xc00077a398)
Nov 17 11:43:05 jurassicpark podman[4190584]:         /home/circleci/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/bucket.go:570 +0x32f
Nov 17 11:43:05 jurassicpark podman[4190584]: go.etcd.io/bbolt.(*Tx).Commit(0xc00077a380)
Nov 17 11:43:05 jurassicpark podman[4190584]:         /home/circleci/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/tx.go:160 +0xe7
Nov 17 11:43:05 jurassicpark podman[4190584]: go.etcd.io/bbolt.(*DB).Update(0x0, 0xc000f84700)
Nov 17 11:43:05 jurassicpark podman[4190584]:         /home/circleci/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:748 +0xe5
Nov 17 11:43:05 jurassicpark podman[4190584]: github.com/influxdata/influxdb/v2/bolt.(*Client).initialize(0xc000b0f180, {0x1f, 0x0})
Nov 17 11:43:05 jurassicpark podman[4190584]:         /home/circleci/go/src/github.com/influxdata/influxdb/bolt/bbolt.go:89 +0x39
Nov 17 11:43:05 jurassicpark podman[4190584]: github.com/influxdata/influxdb/v2/bolt.(*Client).Open(0xc0005a21e0, {0x40a6b18, 0xc000148280})
Nov 17 11:43:05 jurassicpark podman[4190584]:         /home/circleci/go/src/github.com/influxdata/influxdb/bolt/bbolt.go:77 +0x20e
Nov 17 11:43:05 jurassicpark podman[4190584]: github.com/influxdata/influxdb/v2/cmd/influxd/launcher.(*Launcher).openMetaStores(0xc00016aee0, {0x40a6b18, 0xc000148280}, 0xc000423800)
Nov 17 11:43:05 jurassicpark podman[4190584]:         /home/circleci/go/src/github.com/influxdata/influxdb/cmd/influxd/launcher/launcher.go:953 +0x1db
Nov 17 11:43:05 jurassicpark podman[4190584]: github.com/influxdata/influxdb/v2/cmd/influxd/launcher.(*Launcher).run(0xc00016aee0, {0x40a6b18, 0xc000148240}, 0xc000423800)
Nov 17 11:43:05 jurassicpark podman[4190584]:         /home/circleci/go/src/github.com/influxdata/influxdb/cmd/influxd/launcher/launcher.go:219 +0x72a
Nov 17 11:43:05 jurassicpark podman[4190584]: github.com/influxdata/influxdb/v2/cmd/influxd/launcher.cmdRunE.func1()
Nov 17 11:43:05 jurassicpark podman[4190584]:         /home/circleci/go/src/github.com/influxdata/influxdb/cmd/influxd/launcher/cmd.go:107 +0x2ec
Nov 17 11:43:05 jurassicpark podman[4190584]: github.com/influxdata/influxdb/v2/kit/cli.NewCommand.func1(0xc0000e58c0, {0xaeaf4d8, 0x0, 0x0})
Nov 17 11:43:05 jurassicpark podman[4190584]:         /home/circleci/go/src/github.com/influxdata/influxdb/kit/cli/viper.go:54 +0x1e
Nov 17 11:43:05 jurassicpark podman[4190584]: github.com/spf13/cobra.(*Command).execute(0xc0000e58c0, {0xc00004e210, 0x0, 0x0})
Nov 17 11:43:05 jurassicpark podman[4190584]:         /home/circleci/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x60e
Nov 17 11:43:05 jurassicpark podman[4190584]: github.com/spf13/cobra.(*Command).ExecuteC(0xc0000e58c0)
Nov 17 11:43:05 jurassicpark podman[4190584]:         /home/circleci/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x3ad
Nov 17 11:43:05 jurassicpark podman[4190584]: github.com/spf13/cobra.(*Command).Execute(...)
Nov 17 11:43:05 jurassicpark podman[4190584]:         /home/circleci/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
Nov 17 11:43:05 jurassicpark podman[4190584]: main.main()
Nov 17 11:43:05 jurassicpark podman[4190584]:         /home/circleci/go/src/github.com/influxdata/influxdb/cmd/influxd/main.go:61 +0x4b8
Nov 17 11:43:05 jurassicpark podman[4190584]: 2021-11-17 11:43:05.117975098 +0100 CET m=+2.356415533 container died 65838e3053535f42d0cff025f429f5e932ee1159a6755a3a4dedd85d07e04807 (image=docker.io/library/influxdb:latest, name=influxdb2-instance)
Nov 17 11:43:05 jurassicpark podman[4190584]: 2021-11-17 11:43:05.653041217 +0100 CET m=+2.891481632 container remove 65838e3053535f42d0cff025f429f5e932ee1159a6755a3a4dedd85d07e04807 (image=docker.io/library/influxdb:latest, name=influxdb2-instance)
```

issue persists

**Comment by danxmoran** [comment]
This is https://github.com/etcd-io/bbolt/issues/266, it happens after an "unclean" close of the boltdb file (i.e. from an OOM kill).

**Comment by drahnr** [comment]
So what would be the solution here?
