### ISSUE TITLE
Invalid column reader received from predecessor while using InfluxQL syntax on 2.1

### ISSUE THREAD

**Issue by colthreepv** [influxdata/influxdb#22926]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior. **DISCLAIMER: not sure how to reproduce this behavior**

1. Activate v1 compatibility layer
2. Write data
3. Query it with a simple `SELECT last(_field) FROM measurement` query

__Expected behavior:__
Receive my value

__Actual behavior:__
It worked for some weeks flawlessly but today it started to PANIC on some of those v1 compatibility queries

__Environment info:__

* System info: `Linux 5.4.0-89-generic x86_64`
* InfluxDB version: `InfluxDB 2.1.1 (git: 657e1839de) build_date: 2021-11-09T03:03:48Z`
* Other relevant environment details: docker img `influxdb:2.1-alpine@sha256:9ac49ef6120a7e643fe8d7ddb090eaf445b53cf3649a5ea842f5e2ba993641ca`

__Config:__
Completely default

__Logs:__
Panic log:
```
ts=2021-11-24T12:38:27.079510Z lvl=info msg="Executing query" log_id=0Y0V5JU0000 service=query query="SELECT last(balance) FROM slug.forever.\"currency-reward\""
ts=2021-11-24T12:38:27.179213Z lvl=info msg="Invalid column reader received from predecessor" log_id=0Y0V5JU0000 service=storage-reads source="@18:6-18:66: filter" error="mismatched column lengths: map[_field_t1:string:144 _field_t2:string:48 _measurement_t1:string:48 _measurement_t2:string:48 _start:time:48 _stop:time:48 _time:time:48 _value_t1:float:48 _value_t2:float:48 address:string:48 friendlyName:string:48 wallet:string:48]"
panic: runtime error: index out of range [6] with length 6
goroutine 3682 [running]:
github.com/apache/arrow/go/arrow/bitutil.BitIsNotSet(...)
	/home/circleci/go/pkg/mod/github.com/apache/arrow/go/arrow@v0.0.0-20210722123801-4591d76fce28/bitutil/bitutil.go:51
github.com/apache/arrow/go/arrow/array.(*array).IsNull(...)
	/home/circleci/go/pkg/mod/github.com/apache/arrow/go/arrow@v0.0.0-20210722123801-4591d76fce28/array/array.go:112
github.com/influxdata/flux/execute.ValueForRow({0x40e7b58, 0xc0054ca400}, 0x30, 0x7)
	/home/circleci/go/pkg/mod/github.com/influxdata/flux@v0.139.0/execute/table.go:425 +0xa3b
github.com/influxdata/flux/stdlib/universe.(*filterTransformation).filter(0xc004066580, 0x3cb2108, {0x40e7b58, 0xc0054ca400}, {0x40fa360, 0xc0053bdae0}, {0xc00323aa40, 0x3, 0x0}, {0x4076140, ...})
	/home/circleci/go/pkg/mod/github.com/influxdata/flux@v0.139.0/stdlib/universe/filter.go:351 +0x2e5
github.com/influxdata/flux/stdlib/universe.(*filterTransformation).filterChunk(0xc004066580, 0x47c83e, {{{0x40f47c0, 0xc004f9f860}, {0xc004390300, 0xc, 0x10}, {0xc004386d80, 0xc, 0xc}}}, ...)
	/home/circleci/go/pkg/mod/github.com/influxdata/flux@v0.139.0/stdlib/universe/filter.go:315 +0x212
github.com/influxdata/flux/stdlib/universe.(*filterTransformation).filterTable.func1.1({0x40e7bc8, 0xc0053bd5e0})
	/home/circleci/go/pkg/mod/github.com/influxdata/flux@v0.139.0/stdlib/universe/filter.go:298 +0x1d9
github.com/influxdata/flux/execute.(*consecutiveTransportTable).Do.func1({0x40e7bc8, 0xc0053bd5e0})
	/home/circleci/go/pkg/mod/github.com/influxdata/flux@v0.139.0/execute/transport.go:537 +0x542
github.com/influxdata/flux/execute.(*ColListTable).Do(0x3eaee60, 0xc003216401)
	/home/circleci/go/pkg/mod/github.com/influxdata/flux@v0.139.0/execute/table.go:1328 +0x54
github.com/influxdata/flux/execute.(*consecutiveTransportTable).Do(0xc005384930, 0xc0053bdb80)
	/home/circleci/go/pkg/mod/github.com/influxdata/flux@v0.139.0/execute/transport.go:519 +0x87
github.com/influxdata/flux/stdlib/universe.(*filterTransformation).filterTable.func1({0x8, 0x8}, 0xc0054ca2c0)
	/home/circleci/go/pkg/mod/github.com/influxdata/flux@v0.139.0/stdlib/universe/filter.go:296 +0x147
github.com/influxdata/flux/internal/execute/table.StreamWithContext.func1()
	/home/circleci/go/pkg/mod/github.com/influxdata/flux@v0.139.0/internal/execute/table/stream.go:109 +0xa6
created by github.com/influxdata/flux/internal/execute/table.StreamWithContext
	/home/circleci/go/pkg/mod/github.com/influxdata/flux@v0.139.0/internal/execute/table/stream.go:106 +0x225
```

After that I removed the entire measurement history, then started populated again, as soon as there was *any* value, some warnings came back
```
ts=2021-11-24T12:55:53.457888Z lvl=info msg="Executing query" log_id=0Y0V8yhW000 service=query query="SELECT last(balance) FROM slug.forever.\"currency-reward\""
ts=2021-11-24T12:55:53.540686Z lvl=info msg="Invalid column reader received from predecessor" log_id=0Y0V8yhW000 service=storage-reads source="@18:6-18:66: filter" error="mismatched column lengths: map[_field_t1:string:3 _field_t2:string:1 _measurement_t1:string:1 _measurement_t2:string:1 _start:time:1 _stop:time:1 _time:time:1 _value_t1:float:1 _value_t2:float:1 address:string:1 friendlyName:string:1 wallet:string:1]"
ts=2021-11-24T12:55:53.646179Z lvl=info msg="executing new query" log_id=0Y0V8yhW000 query="SELECT last(\"collateral\") FROM \"service01\" WHERE (\"token\" = 'TIK')"
ts=2021-11-24T12:55:53.646509Z lvl=info msg="Executing query" log_id=0Y0V8yhW000 service=query query="SELECT last(collateral) FROM slug.forever.service01 WHERE (token = 'TIK')"
ts=2021-11-24T12:55:53.682162Z lvl=info msg="executing new query" log_id=0Y0V8yhW000 query="SELECT last(\"collateral\") * 56666.2744 FROM \"service01\" WHERE (\"token\" = 'TIK')"
ts=2021-11-24T12:55:53.682335Z lvl=info msg="Executing query" log_id=0Y0V8yhW000 service=query query="SELECT last(collateral) * 56666.274 FROM slug.forever.service01 WHERE (token = 'TIK')"
ts=2021-11-24T12:55:53.704497Z lvl=info msg="executing new query" log_id=0Y0V8yhW000 query="SELECT last(\"borrow\") FROM \"service01\" WHERE (\"token\" = 'TOK' AND \"friendlyName\" = 'mars')"
ts=2021-11-24T12:55:53.704839Z lvl=info msg="Executing query" log_id=0Y0V8yhW000 service=query query="SELECT last(borrow) FROM slug.forever.service01 WHERE (token = 'TOK' AND friendlyName = 'mars')"
ts=2021-11-24T12:55:53.713786Z lvl=info msg="Invalid column reader received from predecessor" log_id=0Y0V8yhW000 service=storage-reads source="@18:6-18:66: filter" error="mismatched column lengths: map[_field_t1:string:3 _field_t2:string:1 _measurement_t1:string:1 _measurement_t2:string:1 _start_t1:time:1 _start_t2:time:1 _stop_t1:time:1 _stop_t2:time:1 _time:time:1 _value_t1:float:1 _value_t2:float:1 address:string:1 friendlyName:string:1 wallet:string:1]"
```

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

iostat command was given without the `-x` option, not present in the influx container, only `iostat -d 1 30 > iostat.txt`

[iostat.txt](https://github.com/influxdata/influxdb/files/7595911/iostat.txt)
[profiles.tar.gz](https://github.com/influxdata/influxdb/files/7595912/profiles.tar.gz)

**Comment by wbaker85** [comment]
Did this issue only start happening when you upgraded to 2.1? If so, what previous version were you running?

**Comment by colthreepv** [comment]
not really, I was using 2.0 months ago, I enabled v1 compatibility layer just recently to do queries unbounded by `|> range`

**Comment by wbaker85** [comment]
Thanks, that will help to narrow down the source of the bug!

**Comment by lesam** [comment]
The stacktrace indicates this is from the InfluxQL transpiler, which has since been removed because of this kind of bug.

2.x now processes InfluxQL without transpiling to flux, so this issue should be fixed.
