### ISSUE TITLE
write points fail and report [shard 90] short buffer?

### ISSUE THREAD

**Issue by lonelyleaf** [influxdata/influxdb#22951]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. write point use java client 
2. client report 
```
com.influxdb.exceptions.InternalServerErrorException: unexpected error writing points to database: [shard 90] short buffer
	at com.influxdb.internal.AbstractRestClient.responseToError(AbstractRestClient.java:118) ~[influxdb-client-core-3.4.0.jar!/:3.4.0]
	at com.influxdb.internal.AbstractRestClient.execute(AbstractRestClient.java:81) ~[influxdb-client-core-3.4.0.jar!/:3.4.0]
	at com.influxdb.client.internal.AbstractWriteBlockingClient.write(AbstractWriteBlockingClient.java:85) ~[influxdb-client-java-3.4.0.jar!/:3.4.0]
	at com.influxdb.client.internal.WriteApiBlockingImpl.lambda$writePoints$1(WriteApiBlockingImpl.java:137) ~[influxdb-client-java-3.4.0.jar!/:3.4.0]
```

3. influxdb logs error too ,and only when write some data trigger this error

__Environment info:__

docker
influx 2.1.1

__Logs:__
Include snippet of errors in log.

```
2021-12-01T06:25:36.585734Z	info	Reading file	{"log_id": "0Y9AZ_e0000", "service": "storage-engine", "engine": "tsm1", "service": "cacheloader", "path": "/var/lib/influxdb2/engine/wal/cb8da52d13f762fb/autogen/96/_00001.wal", "size": 5712}
2021-12-01T06:25:36.591886Z	info	Opened file	{"log_id": "0Y9AZ_e0000", "service": "storage-engine", "engine": "tsm1", "service": "filestore", "path": "/var/lib/influxdb2/engine/data/cb8da52d13f762fb/autogen/94/000000001-000000001.tsm", "id": 0, "duration": "7.343ms"}
2021-12-01T06:25:36.611728Z	info	Opened file	{"log_id": "0Y9AZ_e0000", "service": "storage-engine", "engine": "tsm1", "service": "filestore", "path": "/var/lib/influxdb2/engine/data/cb8da52d13f762fb/autogen/89/000000003-000000002.tsm", "id": 0, "duration": "0.596ms"}
2021-12-01T06:25:43.419126Z	error	Failed to open shard	{"log_id": "0Y9AZ_e0000", "service": "storage-engine", "service": "store", "op_name": "tsdb_open", "db_shard_id": 90, "error": "[shard 90] short buffer"}
2021-12-01T06:25:44.798705Z	info	index opened with 8 partitions	{"log_id": "0Y9AZ_e0000", "service": "storage-engine", "index": "tsi"}
2021-12-01T06:25:44.808490Z	info	index opened with 8 partitions	{"log_id": "0Y9AZ_e0000", "service": "storage-engine", "index": "tsi"}
2021-12-01T06:25:44.810225Z	info	index opened with 8 partitions	{"log_id": "0Y9AZ_e0000", "service": "storage-engine", "index": "tsi"}
2021-12-01T06:25:44.851809Z	info	index opened with 8 partitions	{"log_id": "0Y9AZ_e0000", "service": "storage-engine", "index": "tsi"}
2021-12-01T06:25:44.862204Z	info	index opened with 8 partitions	{"log_id": "0Y9AZ_e0000", "service": "storage-engine", "index": "tsi"}
```

**Comment by abelletti** [comment]
FYI, we are seeing this as well. InfluxDB v2.1.1, Python client. Writing a large number of rows, we first see the issue on row 14995. The error definitely appears to be data-dependent. From skimming the InfluxDB source, this comes from extracting an array of strings from a compressed sequence of bytes. Apparently something becomes corrupt and the decoder expects to find more bytes of string than are actually present.

Going to see if I can downgrade to an earlier InfluxDB and check against that.

**Comment by abelletti** [comment]
In our case, this appears to be caused by corruption in the bucket we're writing to. I've confirmed that writing to a new bucket in a different org works, and even a new bucket in the same org. But writing to this particular bucket/org fails every time, regardless of whether that particular measurement has been purged or not.

**Comment by lonelyleaf** [comment]
@abelletti You're right, I can fix this issue by create a new bucket, thanks. Hope IInfluxdata can add some feature to fix corrupted data in bucket.

**Comment by davidby-influx** [comment]
We have seen this when a disk fills up. That can cause corrupt files which persist after a disk resize or move to a larger disk.
