### ISSUE TITLE
Deadlock in TestExecuteContinuousQuery_TimeRange

### ISSUE THREAD

**Issue by davidby-influx** [influxdata/influxdb#22954]
Running the unit tests in race mode in the 1.9 branch

https://app.circleci.com/pipelines/github/influxdata/influxdb/26141/workflows/c3bdda9c-f4a3-434a-ab32-601d1be51521/jobs/234203/tests#failed-test-0

**Comment by davidby-influx** [comment]
```
Failed
=== RUN   TestExecuteContinuousQuery_TimeRange
=== RUN   TestExecuteContinuousQuery_TimeRange/10s
ts=2021-12-01T04:05:37.280622Z lvl=info msg="Starting continuous query service" log_id=0Y92YwW0000 service=continuous_querier
ts=2021-12-01T04:05:37.280806Z lvl=info msg="Running continuous queries by request" log_id=0Y92YwW0000 service=continuous_querier at=2000-01-01T00:00:00.000000Z
ts=2021-12-01T04:05:37.281199Z lvl=info msg="Running continuous queries by request" log_id=0Y92YwW0000 service=continuous_querier at=2000-01-01T00:00:10.000000Z
ts=2021-12-01T04:05:37.281711Z lvl=info msg="Continuous query execution (start)" log_id=0Y92YwW0000 service=continuous_querier trace_id=0Y92YwWG000 op_name=continuous_querier_execute op_event=start
ts=2021-12-01T04:05:37.281764Z lvl=info msg="Executing continuous query" log_id=0Y92YwW0000 service=continuous_querier trace_id=0Y92YwWG000 op_name=continuous_querier_execute name=cq db_instance=db start=2000-01-01T00:00:00.000000Z end=2000-01-01T00:00:10.000000Z
ts=2021-12-01T04:05:37.352071Z lvl=info msg="Finished continuous query" log_id=0Y92YwW0000 service=continuous_querier trace_id=0Y92YwWG000 op_name=continuous_querier_execute name=cq db_instance=db written=-1 start=2000-01-01T00:00:00.000000Z end=2000-01-01T00:00:10.000000Z duration=70ms
ts=2021-12-01T04:05:37.352196Z lvl=info msg="Continuous query execution (end)" log_id=0Y92YwW0000 service=continuous_querier trace_id=0Y92YwWG000 op_name=continuous_querier_execute op_event=end op_elapsed=70.502ms
ts=2021-12-01T04:05:37.352269Z lvl=info msg="Terminating continuous query service" log_id=0Y92YwW0000 service=continuous_querier
=== RUN   TestExecuteContinuousQuery_TimeRange/1m
ts=2021-12-01T04:05:37.353032Z lvl=info msg="Starting continuous query service" log_id=0Y92Ywn0000 service=continuous_querier
ts=2021-12-01T04:05:37.353223Z lvl=info msg="Running continuous queries by request" log_id=0Y92Ywn0000 service=continuous_querier at=2000-01-01T00:00:00.000000Z
ts=2021-12-01T04:05:37.353652Z lvl=info msg="Running continuous queries by request" log_id=0Y92Ywn0000 service=continuous_querier at=2000-01-01T00:01:00.000000Z
ts=2021-12-01T04:05:37.354105Z lvl=info msg="Continuous query execution (start)" log_id=0Y92Ywn0000 service=continuous_querier trace_id=0Y92YwnW000 op_name=continuous_querier_execute op_event=start
ts=2021-12-01T04:05:37.354179Z lvl=info msg="Executing continuous query" log_id=0Y92Ywn0000 service=continuous_querier trace_id=0Y92YwnW000 op_name=continuous_querier_execute name=cq db_instance=db start=2000-01-01T00:00:00.000000Z end=2000-01-01T00:01:00.000000Z
    service_test.go:463: timed out
panic: test timed out after 10m0s

goroutine 25 [running]:
testing.(*M).startAlarm.func1()
	/go/src/testing/testing.go:1788 +0xbb
created by time.goFunc
	/go/src/time/sleep.go:180 +0x4a

goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc000102b60, {0xbc9fce, 0x24}, 0xbdb368)
	/go/src/testing/testing.go:1307 +0x752
testing.runTests.func1(0x0)
	/go/src/testing/testing.go:1598 +0x9a
testing.tRunner(0xc000102b60, 0xc0001b9bf8)
	/go/src/testing/testing.go:1259 +0x230
testing.runTests(0xc000134400, {0x105afc0, 0xe, 0xe}, {0x0, 0xc000136e80, 0x10658c0})
	/go/src/testing/testing.go:1596 +0x7cb
testing.(*M).Run(0xc000134400)
	/go/src/testing/testing.go:1504 +0x9d2
main.main()
	_testmain.go:71 +0x22c

goroutine 63 [chan receive, 9 minutes]:
testing.(*T).Run(0xc00043c820, {0xbb8ae4, 0x2}, 0xc00023c7e0)
	/go/src/testing/testing.go:1307 +0x752
github.com/influxdata/influxdb/services/continuous_querier.TestExecuteContinuousQuery_TimeRange(0x0)
	/root/project/services/continuous_querier/service_test.go:419 +0x8b9
testing.tRunner(0xc00043c820, 0xbdb368)
	/go/src/testing/testing.go:1259 +0x230
created by testing.(*T).Run
	/go/src/testing/testing.go:1306 +0x727

goroutine 34 [chan receive, 9 minutes]:
github.com/influxdata/flux/execute.createOperatorProfiler.func1(0xc0001245f0)
	/go/pkg/mod/github.com/influxdata/flux@v0.140.0/execute/profiler.go:108 +0x150
created by github.com/influxdata/flux/execute.createOperatorProfiler
	/go/pkg/mod/github.com/influxdata/flux@v0.140.0/execute/profiler.go:106 +0x171

goroutine 16 [select, 9 minutes]:
github.com/influxdata/influxdb/query.(*TaskManager).waitForQuery(0xc000020eb0, 0x0, 0xc00002e900, 0xc00002e840, 0xc00002e960)
	/root/project/query/task_manager.go:308 +0x1ed
created by github.com/influxdata/influxdb/query.(*TaskManager).AttachQuery
	/root/project/query/task_manager.go:215 +0x7d5

goroutine 114 [select, 9 minutes]:
github.com/influxdata/influxdb/query.(*ExecutionContext).watch.func1()
	/root/project/query/execution_context.go:47 +0x209
created by github.com/influxdata/influxdb/query.(*ExecutionContext).watch
	/root/project/query/execution_context.go:39 +0x111

goroutine 14 [chan receive, 9 minutes]:
github.com/influxdata/influxdb/services/continuous_querier.(*Service).runContinuousQueryAndWriteResult(0xc000232510, 0xc0000211d0)
	/root/project/services/continuous_querier/service.go:437 +0x285
github.com/influxdata/influxdb/services/continuous_querier.(*Service).ExecuteContinuousQuery(0xc000232510, 0xc0001b5d30, 0xc0000c0b20, {0x0, 0x0, 0x0})
	/root/project/services/continuous_querier/service.go:384 +0x14bf
github.com/influxdata/influxdb/services/continuous_querier.(*Service).runContinuousQueries(0xc000232510, 0xc00023cab0)
	/root/project/services/continuous_querier/service.go:264 +0x255
github.com/influxdata/influxdb/services/continuous_querier.(*Service).backgroundLoop(0xc000232510)
	/root/project/services/continuous_querier/service.go:225 +0x52a
created by github.com/influxdata/influxdb/services/continuous_querier.(*Service).Open
	/root/project/services/continuous_querier/service.go:133 +0x253

goroutine 15 [chan send, 9 minutes]:
github.com/influxdata/influxdb/services/continuous_querier.TestExecuteContinuousQuery_TimeRange.func1.1({0xc89990, 0xc000228900}, 0xc0001f0f70)
	/root/project/services/continuous_querier/service_test.go:448 +0x465
github.com/influxdata/influxdb/services/continuous_querier.(*StatementExecutor).ExecuteStatement(0xc000010290, 0xbbd729, {0xc89990, 0xc000228900})
	/root/project/services/continuous_querier/service_test.go:829 +0x5d
github.com/influxdata/influxdb/query.(*Executor).executeQuery(0xc00023c870, 0xc00000e8a0, {{0xbb8bd6, 0x2}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
	/root/project/query/executor.go:347 +0x95f
created by github.com/influxdata/influxdb/query.(*Executor).ExecuteQuery
	/root/project/query/executor.go:249 +0x231

goroutine 13 [semacquire, 9 minutes]:
sync.runtime_Semacquire(0xc000252ea4)
	/go/src/runtime/sema.go:56 +0x25
sync.(*WaitGroup).Wait(0xc000252ea4)
	/go/src/sync/waitgroup.go:130 +0xea
github.com/influxdata/influxdb/services/continuous_querier.(*Service).Close(0xc000232510)
	/root/project/services/continuous_querier/service.go:143 +0x8c
runtime.Goexit()
	/go/src/runtime/panic.go:661 +0x1ce
testing.(*common).FailNow(0xc000278000)
	/go/src/testing/testing.go:756 +0x65
testing.(*common).Fatal(0xc00002e780, {0xc0002cfe78, 0x1, 0x1})
	/go/src/testing/testing.go:824 +0x65
github.com/influxdata/influxdb/services/continuous_querier.TestExecuteContinuousQuery_TimeRange.func1(0xc000278000)
	/root/project/services/continuous_querier/service_test.go:463 +0x853
testing.tRunner(0xc000278000, 0xc00023c7e0)
	/go/src/testing/testing.go:1259 +0x230
created by testing.(*T).Run
	/go/src/testing/testing.go:1306 +0x727
```

**Comment by davidby-influx** [comment]
```
Failed
=== RUN   TestExecuteContinuousQuery_TimeRange/10s
ts=2021-12-01T04:05:37.280622Z lvl=info msg="Starting continuous query service" log_id=0Y92YwW0000 service=continuous_querier
ts=2021-12-01T04:05:37.280806Z lvl=info msg="Running continuous queries by request" log_id=0Y92YwW0000 service=continuous_querier at=2000-01-01T00:00:00.000000Z
ts=2021-12-01T04:05:37.281199Z lvl=info msg="Running continuous queries by request" log_id=0Y92YwW0000 service=continuous_querier at=2000-01-01T00:00:10.000000Z
ts=2021-12-01T04:05:37.281711Z lvl=info msg="Continuous query execution (start)" log_id=0Y92YwW0000 service=continuous_querier trace_id=0Y92YwWG000 op_name=continuous_querier_execute op_event=start
ts=2021-12-01T04:05:37.281764Z lvl=info msg="Executing continuous query" log_id=0Y92YwW0000 service=continuous_querier trace_id=0Y92YwWG000 op_name=continuous_querier_execute name=cq db_instance=db start=2000-01-01T00:00:00.000000Z end=2000-01-01T00:00:10.000000Z
ts=2021-12-01T04:05:37.352071Z lvl=info msg="Finished continuous query" log_id=0Y92YwW0000 service=continuous_querier trace_id=0Y92YwWG000 op_name=continuous_querier_execute name=cq db_instance=db written=-1 start=2000-01-01T00:00:00.000000Z end=2000-01-01T00:00:10.000000Z duration=70ms
ts=2021-12-01T04:05:37.352196Z lvl=info msg="Continuous query execution (end)" log_id=0Y92YwW0000 service=continuous_querier trace_id=0Y92YwWG000 op_name=continuous_querier_execute op_event=end op_elapsed=70.502ms
ts=2021-12-01T04:05:37.352269Z lvl=info msg="Terminating continuous query service" log_id=0Y92YwW0000 service=continuous_querier
```

**Comment by davidby-influx** [comment]
```
Failed
=== RUN   TestExecuteContinuousQuery_TimeRange/1m
ts=2021-12-01T04:05:37.353032Z lvl=info msg="Starting continuous query service" log_id=0Y92Ywn0000 service=continuous_querier
ts=2021-12-01T04:05:37.353223Z lvl=info msg="Running continuous queries by request" log_id=0Y92Ywn0000 service=continuous_querier at=2000-01-01T00:00:00.000000Z
ts=2021-12-01T04:05:37.353652Z lvl=info msg="Running continuous queries by request" log_id=0Y92Ywn0000 service=continuous_querier at=2000-01-01T00:01:00.000000Z
ts=2021-12-01T04:05:37.354105Z lvl=info msg="Continuous query execution (start)" log_id=0Y92Ywn0000 service=continuous_querier trace_id=0Y92YwnW000 op_name=continuous_querier_execute op_event=start
ts=2021-12-01T04:05:37.354179Z lvl=info msg="Executing continuous query" log_id=0Y92Ywn0000 service=continuous_querier trace_id=0Y92YwnW000 op_name=continuous_querier_execute name=cq db_instance=db start=2000-01-01T00:00:00.000000Z end=2000-01-01T00:01:00.000000Z
    service_test.go:463: timed out
panic: test timed out after 10m0s

goroutine 25 [running]:
testing.(*M).startAlarm.func1()
	/go/src/testing/testing.go:1788 +0xbb
created by time.goFunc
	/go/src/time/sleep.go:180 +0x4a

goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc000102b60, {0xbc9fce, 0x24}, 0xbdb368)
	/go/src/testing/testing.go:1307 +0x752
testing.runTests.func1(0x0)
	/go/src/testing/testing.go:1598 +0x9a
testing.tRunner(0xc000102b60, 0xc0001b9bf8)
	/go/src/testing/testing.go:1259 +0x230
testing.runTests(0xc000134400, {0x105afc0, 0xe, 0xe}, {0x0, 0xc000136e80, 0x10658c0})
	/go/src/testing/testing.go:1596 +0x7cb
testing.(*M).Run(0xc000134400)
	/go/src/testing/testing.go:1504 +0x9d2
main.main()
	_testmain.go:71 +0x22c

goroutine 63 [chan receive, 9 minutes]:
testing.(*T).Run(0xc00043c820, {0xbb8ae4, 0x2}, 0xc00023c7e0)
	/go/src/testing/testing.go:1307 +0x752
github.com/influxdata/influxdb/services/continuous_querier.TestExecuteContinuousQuery_TimeRange(0x0)
	/root/project/services/continuous_querier/service_test.go:419 +0x8b9
testing.tRunner(0xc00043c820, 0xbdb368)
	/go/src/testing/testing.go:1259 +0x230
created by testing.(*T).Run
	/go/src/testing/testing.go:1306 +0x727

goroutine 34 [chan receive, 9 minutes]:
github.com/influxdata/flux/execute.createOperatorProfiler.func1(0xc0001245f0)
	/go/pkg/mod/github.com/influxdata/flux@v0.140.0/execute/profiler.go:108 +0x150
created by github.com/influxdata/flux/execute.createOperatorProfiler
	/go/pkg/mod/github.com/influxdata/flux@v0.140.0/execute/profiler.go:106 +0x171

goroutine 16 [select, 9 minutes]:
github.com/influxdata/influxdb/query.(*TaskManager).waitForQuery(0xc000020eb0, 0x0, 0xc00002e900, 0xc00002e840, 0xc00002e960)
	/root/project/query/task_manager.go:308 +0x1ed
created by github.com/influxdata/influxdb/query.(*TaskManager).AttachQuery
	/root/project/query/task_manager.go:215 +0x7d5

goroutine 114 [select, 9 minutes]:
github.com/influxdata/influxdb/query.(*ExecutionContext).watch.func1()
	/root/project/query/execution_context.go:47 +0x209
created by github.com/influxdata/influxdb/query.(*ExecutionContext).watch
	/root/project/query/execution_context.go:39 +0x111

goroutine 14 [chan receive, 9 minutes]:
github.com/influxdata/influxdb/services/continuous_querier.(*Service).runContinuousQueryAndWriteResult(0xc000232510, 0xc0000211d0)
	/root/project/services/continuous_querier/service.go:437 +0x285
github.com/influxdata/influxdb/services/continuous_querier.(*Service).ExecuteContinuousQuery(0xc000232510, 0xc0001b5d30, 0xc0000c0b20, {0x0, 0x0, 0x0})
	/root/project/services/continuous_querier/service.go:384 +0x14bf
github.com/influxdata/influxdb/services/continuous_querier.(*Service).runContinuousQueries(0xc000232510, 0xc00023cab0)
	/root/project/services/continuous_querier/service.go:264 +0x255
github.com/influxdata/influxdb/services/continuous_querier.(*Service).backgroundLoop(0xc000232510)
	/root/project/services/continuous_querier/service.go:225 +0x52a
created by github.com/influxdata/influxdb/services/continuous_querier.(*Service).Open
	/root/project/services/continuous_querier/service.go:133 +0x253

goroutine 15 [chan send, 9 minutes]:
github.com/influxdata/influxdb/services/continuous_querier.TestExecuteContinuousQuery_TimeRange.func1.1({0xc89990, 0xc000228900}, 0xc0001f0f70)
	/root/project/services/continuous_querier/service_test.go:448 +0x465
github.com/influxdata/influxdb/services/continuous_querier.(*StatementExecutor).ExecuteStatement(0xc000010290, 0xbbd729, {0xc89990, 0xc000228900})
	/root/project/services/continuous_querier/service_test.go:829 +0x5d
github.com/influxdata/influxdb/query.(*Executor).executeQuery(0xc00023c870, 0xc00000e8a0, {{0xbb8bd6, 0x2}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
	/root/project/query/executor.go:347 +0x95f
created by github.com/influxdata/influxdb/query.(*Executor).ExecuteQuery
	/root/project/query/executor.go:249 +0x231

goroutine 13 [semacquire, 9 minutes]:
sync.runtime_Semacquire(0xc000252ea4)
	/go/src/runtime/sema.go:56 +0x25
sync.(*WaitGroup).Wait(0xc000252ea4)
	/go/src/sync/waitgroup.go:130 +0xea
github.com/influxdata/influxdb/services/continuous_querier.(*Service).Close(0xc000232510)
	/root/project/services/continuous_querier/service.go:143 +0x8c
runtime.Goexit()
	/go/src/runtime/panic.go:661 +0x1ce
testing.(*common).FailNow(0xc000278000)
	/go/src/testing/testing.go:756 +0x65
testing.(*common).Fatal(0xc00002e780, {0xc0002cfe78, 0x1, 0x1})
	/go/src/testing/testing.go:824 +0x65
github.com/influxdata/influxdb/services/continuous_querier.TestExecuteContinuousQuery_TimeRange.func1(0xc000278000)
	/root/project/services/continuous_querier/service_test.go:463 +0x853
testing.tRunner(0xc000278000, 0xc00023c7e0)
	/go/src/testing/testing.go:1259 +0x230
created by testing.(*T).Run
	/go/src/testing/testing.go:1306 +0x727
```
