### ISSUE TITLE
Panic from `CreateIterator` in Flux query

### ISSUE THREAD

**Issue by DStrand1** [influxdata/influxdb#23073]
When running the flux query:
```js
from(bucket: "sensor")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_field"] == "val")
  |> group(columns: ["_measurement"])
  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)
  |> yield(name: "sum")
```
a panic seems to have originated from `CreateIterator` here: https://github.com/influxdata/influxdb/blob/888f82c9c80f77076c4d29032c736a2d2d7ffe93/v1/services/storage/store.go#L546

The panic trace:
```
influxdb_1    | ts=2022-01-22T06:40:35.651164Z lvl=info msg="Execute source panic" log_id=0ZBWnq00000 service=storage-reads error="panic: runtime error: invalid memory address or nil pointer dereference" stacktrace="goroutine 8195863 [running]:
runtime/debug.Stack(0xc000fdecc0, 0x39feb00, 0x2757856)
    /usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/influxdata/flux/execute.(*executionState).do.func1.1(0xc006272180)
    /home/circleci/go/pkg/mod/github.com/influxdata/flux@v0.104.0/execute/executor.go:279 +0x1e5
panic(0x2395400, 0x4bbf8e0)
    /usr/local/go/src/runtime/panic.go:969 +0x175
github.com/influxdata/influxdb/v2/v1/services/storage.(*Store).measurementFields.func1(0x0, 0x0)
    /home/circleci/go/src/github.com/influxdata/influxdb/v1/services/storage/store.go:546 +0x22
panic(0x23b14a0, 0xc006280600)
    /usr/local/go/src/runtime/panic.go:969 +0x175
github.com/influxdata/influxdb/v2/v1/services/storage.(*Store).measurementFields(0xc0008d2fc0, 0x3a4f080, 0xc006280300, 0xc000623bb8, 0x0, 0x0, 0x0, 0x0)
    /home/circleci/go/src/github.com/influxdata/influxdb/v1/services/storage/store.go:549 +0x2ea
github.com/influxdata/influxdb/v2/v1/services/storage.(*Store).TagValues(0xc0008d2fc0, 0x3a4f080, 0xc006280300, 0xc0062805d0, 0x0, 0xc00281dcb0, 0x40f6d8, 0x20)
    /home/circleci/go/src/github.com/influxdata/influxdb/v1/services/storage/store.go:406 +0x3c5
github.com/influxdata/influxdb/v2/storage/flux.(*tagValuesIterator).Do(0xc006272400, 0xc00626fbe0, 0x498546, 0x61eba6e3)
    /home/circleci/go/src/github.com/influxdata/influxdb/storage/flux/reader.go:949 +0x162
github.com/influxdata/influxdb/v2/query/stdlib/influxdata/influxdb.(*Source).processTables(0xc002a9be10, 0x3a4f080, 0xc006280300, 0x3a29e00, 0xc006272400, 0x16cc847cce0bbae3, 0x16cc847ccd6e9b5e, 0x0)
    /home/circleci/go/src/github.com/influxdata/influxdb/query/stdlib/influxdata/influxdb/source.go:76 +0x94
github.com/influxdata/influxdb/v2/query/stdlib/influxdata/influxdb.(*readTagValuesSource).run(0xc002a9be10, 0x3a4f080, 0xc006280300, 0x434fcb37b3008643, 0x2741fa4)
    /home/circleci/go/src/github.com/influxdata/influxdb/query/stdlib/influxdata/influxdb/source.go:491 +0x178
github.com/influxdata/influxdb/v2/query/stdlib/influxdata/influxdb.(*Source).Run(0xc002a9be10, 0x3a4f080, 0xc006280300)
    /home/circleci/go/src/github.com/influxdata/influxdb/query/stdlib/influxdata/influxdb/source.go:56 +0x33c
github.com/influxdata/flux/execute.(*executionState).do.func1(0x3a4f080, 0xc006280300, 0xc006171450, 0xc006272180, 0x3a50c00, 0xc002a9be10)
    /home/circleci/go/pkg/mod/github.com/influxdata/flux@v0.104.0/execute/executor.go:284 +0x1da
created by github.com/influxdata/flux/execute.(*executionState).do
    /home/circleci/go/pkg/mod/github.com/influxdata/flux@v0.104.0/execute/executor.go:254 +0xf8"
```

This issue occurred when using a dashboard with Grafana

**Comment by kaijk** [comment]
This error also happens when exploring in InfluxDB itself as well, not just from Grafana generated queries. 

The sum() and mean() functions  (at least) within aggregateWindow() are broken.  This also happens when using the window() function followed by sum() - see example
```
from(bucket: "myBucket")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => (r._measurement == "kWh") and (r._field == "value") and (r.entity_id == "garage_freezer_energy"))
  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)
 //  alternative specification that fails as well
 // |> window(every: 1d)
 // |> sum()
```

But, for example: the count(), median(), and mode() functions DO work.  

createEmpty() does not need to be specified to reproduce.  See also Issue #21649.

**Comment by jeffreyssmith2nd** [comment]
PR: https://github.com/influxdata/influxdb/pull/23520
