### ISSUE TITLE
Influxdb2 Fails to start

### ISSUE THREAD

**Issue by robfox92** [influxdata/influxdb#23186]
I had some issues a while ago with influxdb, and it hasn't been starting. I didn't have anything important in the db as it is a dev server so I cleared out ~/.influxdb2, uninstalled influxdb2 and then reinstalled it. I'm still having the same issues - errors seem to be something around the bolt file and an invalid page type?

__Steps to reproduce:__

1. Install influxdb2 from deb repository
2. Run influxdb as systemd service

__Expected behavior:__
Influxdb should start and  be available at localhost:8086

__Actual behavior:__
Influxdb does not start and is not available

__Environment info:__

* System info: Linux 5.10.0-11-amd64 x86_64
* InfluxDB version: InfluxDB 2.1.1 (git: 657e1839de) build_date: 2021-11-09T03:03:48Z
* lsb_release: Debian GNU/Linbux 11 (bullseye)

__Logs:__
```Mar 14 08:09:06 cantor systemd[1]: Starting InfluxDB is an open-source, distributed, time series database...

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]: ts=2022-03-14T00:09:06.659108Z lvl=info msg="Welcome to InfluxDB" log_id=0_DRxsOW000 version=2.1.1 commit=657e1839de build_date=2021-11-09T03:03:48Z

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]: panic: invalid page type: 41: 10

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]: goroutine 1 [running]:

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]: go.etcd.io/bbolt.(*Cursor).search(0xc001256468, {0x5ccc730, 0x9, 0x9}, 0x0)

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]:         /home/circleci/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/cursor.go:250 +0x28c

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]: go.etcd.io/bbolt.(*Cursor).searchPage(0xc001256468, {0x5ccc730, 0x9, 0x9}, 0x203000)

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]:         /home/circleci/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/cursor.go:308 +0x173

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]: go.etcd.io/bbolt.(*Cursor).search(0xc001256468, {0x5ccc730, 0x9, 0x9}, 0xc0012563b8)

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]:         /home/circleci/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/cursor.go:265 +0x1ca

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]: go.etcd.io/bbolt.(*Cursor).seek(0xc001256468, {0x5ccc730, 0x0, 0x1})

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]:         /home/circleci/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/cursor.go:159 +0x48

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]: go.etcd.io/bbolt.(*Bucket).CreateBucket(0xc000d96398, {0x5ccc730, 0x5ccbf54, 0x9})

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]:         /home/circleci/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/bucket.go:167 +0xe5

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]: go.etcd.io/bbolt.(*Bucket).CreateBucketIfNotExists(0x0, {0x5ccc730, 0x9, 0x9})

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]:         /home/circleci/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/bucket.go:201 +0x31

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]: go.etcd.io/bbolt.(*Tx).CreateBucketIfNotExists(...)

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]:         /home/circleci/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/tx.go:115

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]: github.com/influxdata/influxdb/v2/bolt.(*Client).initialize.func1(0xc000d96380)

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]:         /home/circleci/go/src/github.com/influxdata/influxdb/bolt/bbolt.go:108 +0x210

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]: go.etcd.io/bbolt.(*DB).Update(0x0, 0xc001256700)

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]:         /home/circleci/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:741 +0x82

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]: github.com/influxdata/influxdb/v2/bolt.(*Client).initialize(0xc0000540a2, {0x1e, 0x0})

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]:         /home/circleci/go/src/github.com/influxdata/influxdb/bolt/bbolt.go:89 +0x39

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]: github.com/influxdata/influxdb/v2/bolt.(*Client).Open(0xc0017f8180, {0x40a6b18, 0xc000720100})

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]:         /home/circleci/go/src/github.com/influxdata/influxdb/bolt/bbolt.go:77 +0x20e

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]: github.com/influxdata/influxdb/v2/cmd/influxd/launcher.(*Launcher).openMetaStores(0xc000d64ee0, {0x40a6b18, 0xc000720100}, 0xc000641800)

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]:         /home/circleci/go/src/github.com/influxdata/influxdb/cmd/influxd/launcher/launcher.go:953 +0x1db

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]: github.com/influxdata/influxdb/v2/cmd/influxd/launcher.(*Launcher).run(0xc000d64ee0, {0x40a6b18, 0xc0007200c0}, 0xc000641800)

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]:         /home/circleci/go/src/github.com/influxdata/influxdb/cmd/influxd/launcher/launcher.go:219 +0x72a

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]: github.com/influxdata/influxdb/v2/cmd/influxd/launcher.cmdRunE.func1()

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]:         /home/circleci/go/src/github.com/influxdata/influxdb/cmd/influxd/launcher/cmd.go:107 +0x2ec

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]: github.com/influxdata/influxdb/v2/kit/cli.NewCommand.func1(0xc0003e7340, {0xaeaf4d8, 0x0, 0x0})

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]:         /home/circleci/go/src/github.com/influxdata/influxdb/kit/cli/viper.go:54 +0x1e

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]: github.com/spf13/cobra.(*Command).execute(0xc0003e7340, {0xc00004e210, 0x0, 0x0})

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]:         /home/circleci/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x60e

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]: github.com/spf13/cobra.(*Command).ExecuteC(0xc0003e7340)

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]:         /home/circleci/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x3ad

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]: github.com/spf13/cobra.(*Command).Execute(...)

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]:         /home/circleci/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]: main.main()

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940852]:         /home/circleci/go/src/github.com/influxdata/influxdb/cmd/influxd/main.go:61 +0x4b8

Mar 14 08:09:06 cantor influxd-systemd-start.sh[3940851]: InfluxDB API at http://localhost:8086/ready unavailable after 1 attempts...

Mar 14 08:09:07 cantor influxd-systemd-start.sh[3940851]: InfluxDB API at http://localhost:8086/ready unavailable after 2 attempts...

Mar 14 08:09:08 cantor influxd-systemd-start.sh[3940851]: InfluxDB API at http://localhost:8086/ready unavailable after 3 attempts...

Mar 14 08:09:09 cantor influxd-systemd-start.sh[3940851]: InfluxDB API at http://localhost:8086/ready unavailable after 4 attempts...```

**Comment by robfox92** [comment]
Seems like I was looking in the wrong folder for my data/boltdb. Reverting influxd.bolt to influxd.bolt.pre-2.1.1-upgrade.backup appears to resolve the issue. More data is missing than I expected, but that's ok as this is a dev server.
