### ISSUE TITLE
使用maven包<artifactId>influxdb-java</artifactId>需要输入用户名密码等信息，已输入，但始终报错，提示权限不足

### ISSUE THREAD

**Issue by jwrwst** [influxdata/influxdb#23222]
操作步骤：
1.   .\influxd.exe启动服务(备注版本：influxdb2-2.1.1-windows)
2. 进入http://localhost:8086管理页面，并按提示输入用户名、密码、组织、bucket等信息
3. 代码集成，引入依赖：
       <dependency>
            <groupId>org.influxdb</groupId>
            <artifactId>influxdb-java</artifactId>
            <version>2.22</version>
        </dependency>
4.错误提示：
Exception in thread "main" org.influxdb.InfluxDBException: {"code":"unauthorized","message":"Unauthorized"}
	at org.influxdb.InfluxDBException.buildExceptionForErrorState(InfluxDBException.java:175)
	at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:846)
	at org.influxdb.impl.InfluxDBImpl.executeQuery(InfluxDBImpl.java:833)
	at org.influxdb.impl.InfluxDBImpl.query(InfluxDBImpl.java:559)
	at com.muscleape.influxdb.controller.TestController.main(TestController.java:60)

使用客户端链接（或cli）问题同上：
![image](https://user-images.githubusercontent.com/24490695/159687976-f1c36f9b-e742-4c3f-b639-df670c77db85.png)

**Comment by slw07** [comment]
老外的回复速度真慢，我也遇到相同的问题，目前没解决
