### ISSUE TITLE
panic: keys must be added in sorted order on Influxdb v2.1

### ISSUE THREAD

**Issue by ghvchen** [influxdata/influxdb#23377]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. ...systemctl start influxdb
2. ...
3. ...

__Expected behavior:__
Influxdb start without restart loop.

__Actual behavior:__
Keep showing that Influxdb is not ready and throw panic saying that keys must be added in sorted order and then restart.

I have tried to remove all index and tsi files and rebuild it with command:
influxd inspect build-tsi

but didn't resolve the issue.

__Environment info:__

* System info: Linux 4.18.0-305.25.1.el8_4.x86_64 x86_64
* InfluxDB version: InfluxDB 2.1.1 (git: 657e1839de) build_date: 2021-11-09T03:03:48Z
* Other relevant environment details: No container, directly installed on Linux.

__Config:__
Used default configuration

__Logs:__
```
May 26 15:43:54  influxd-systemd-start.sh[357072]: ts=2022-05-26T19:43:54.230027Z lvl=info msg="Compacting file" log_id=0ahUBqVG000 service=storage-engine engine=tsm1 tsm1_strategy=full tsm1_optimize=false op_name=tsm1_compact_group tsm1_index=9 tsm1_file=/var/lib/influxdb/engine/data/e6c572d9ae49dccd/autogen/12/000000403-000000001.tsm
May 26 15:48:35  influxd-systemd-start.sh[357072]: ts=2022-05-26T19:48:35.981884Z lvl=info msg="TSM compaction (end)" log_id=0ahUBqVG000 service=storage-engine engine=tsm1 tsm1_strategy=full tsm1_optimize=false op_name=tsm1_compact_group op_event=end op_elapsed=281751.905ms
May 26 15:48:35  influxd-systemd-start.sh[357072]: panic: keys must be added in sorted order: TMPWWILDCARD_SYML,mfile=CTP_SAT1,symbol=xCSYLlLaGJ5#!~#Eng < TMP_WILDCARD_SYML,mfile=CTP_SAT1,symbol=xCSXNcQsIa7#!~#source
May 26 15:48:35  influxd-systemd-start.sh[357072]: goroutine 1629 [running]:
May 26 15:48:35  influxd-systemd-start.sh[357072]: github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*directIndex).Add(0xc02589c660, {0x7f6c853ae404, 0x4, 0xc002e291f0}, 0x3, 0x16f08e9bd9f5ff66, 0x16f08e9bd9f5ff66, 0x1f18f0a4, 0x16)
May 26 15:48:35  influxd-systemd-start.sh[357072]:         /home/circleci/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/writer.go:337 +0x488
May 26 15:48:35  influxd-systemd-start.sh[357072]: github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*tsmWriter).WriteBlock(0xc0096d4f80, {0x7f6c853ae404, 0x3a, 0x933e990}, 0x2, 0x2, {0x7f6c2c8090a8, 0x0, 0x61ee3cec})
May 26 15:48:35  influxd-systemd-start.sh[357072]:         /home/circleci/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/writer.go:686 +0x18e
May 26 15:48:35  influxd-systemd-start.sh[357072]: github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*Compactor).write(0xc0006ba090, {0xc000f3e6c0, 0x55}, {0x40b51f8, 0xc000145760}, 0x1, 0x20300b)
May 26 15:48:35  influxd-systemd-start.sh[357072]:         /home/circleci/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:1178 +0x452
May 26 15:48:35  influxd-systemd-start.sh[357072]: github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*Compactor).writeNewFiles(0xc0006ba090, 0x10, 0x3e8, {0xc0009b7200, 0xa, 0xc000f3e780}, {0x40b51f8, 0xc000145760}, 0x10, 0xc0014d58c0)
May 26 15:48:35  influxd-systemd-start.sh[357072]:         /home/circleci/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:1059 +0x35e
May 26 15:48:35  influxd-systemd-start.sh[357072]: github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*Compactor).compact(0xc0006ba090, 0x0, {0xc0009b7200, 0x7f6d02f2c5b8, 0x10}, 0xc01047c800)
May 26 15:48:35  influxd-systemd-start.sh[357072]:         /home/circleci/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:966 +0x285
May 26 15:48:35  influxd-systemd-start.sh[357072]: github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*Compactor).CompactFull(0xc0006ba090, {0xc0009b7200, 0xa, 0x10}, 0x2)
May 26 15:48:35  influxd-systemd-start.sh[357072]:         /home/circleci/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:984 +0x1d0
May 26 15:48:35  influxd-systemd-start.sh[357072]: github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*compactionStrategy).compactGroup(0xc0005da230)
May 26 15:48:35  influxd-systemd-start.sh[357072]:         /home/circleci/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:2170 +0x216
May 26 15:48:35  influxd-systemd-start.sh[357072]: github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*compactionStrategy).Apply(0xc0005da230)
May 26 15:48:35  influxd-systemd-start.sh[357072]:         /home/circleci/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:2148 +0x37
May 26 15:48:35  influxd-systemd-start.sh[357072]: github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*Engine).compactFull.func1()
May 26 15:48:35  influxd-systemd-start.sh[357072]:         /home/circleci/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:2117 +0xf0
May 26 15:48:35  influxd-systemd-start.sh[357072]: created by github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*Engine).compactFull
May 26 15:48:35  influxd-systemd-start.sh[357072]:         /home/circleci/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:2113 +0xef
May 26 15:48:36  systemd[1]: influxdb.service: Child 357073 belongs to influxdb.service.
May 26 15:48:36  systemd[1]: influxdb.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 26 15:48:36  systemd[1]: influxdb.service: Failed with result 'exit-code'.
May 26 15:48:36  systemd[1]: influxdb.service: Changed running -> failed
May 26 15:48:36  systemd[1]: influxdb.service: Unit entered failed state.
May 26 15:48:36  systemd[1]: influxdb.service: Changed failed -> auto-restart

```
__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively happening.
# Note: This command will run for ~30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=30s"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz` and `iostat.txt` output files.
```

**Comment by mstefany** [comment]
I have exactly the same problem with latest InfluxDB 2.7.1 (I had the same problem also with InfluxDB 1.8.11).

The data is ingested using Telegraf only.

```
May 16 08:40:58 monitoring.stefany.eu influxd-systemd-start.sh[533598]: ts=2023-05-16T06:40:58.057682Z lvl=info msg="TSM compaction (end)" log_id=0hppSZw0000 service=storage-engine engine=tsm1 tsm1_level=1 tsm1_strategy=level op_name=tsm1_compact_group op_event=end op_elapsed=6944.452ms
May 16 08:40:58 monitoring.stefany.eu influxd-systemd-start.sh[533598]: panic: keys must be added in sorted order: storage_wal_writes,bucket=c1e12f6c56b4b591,engine=tsm1,id=2025,path=/var/lib/influxdb/engine/data/c1e12f6c56b4b591/autogen/2025,walPath=/var/lib/influxdb/engine/wal/c1e12f6c56b4b591/autogen/2025#!~#counter < storage_wal_writes,bucket=c1e12f6c56b4b591,engine=tsm1,id=2p21,path=/var/lib/influxdb/engine/data/c1e12f6c56b4b591/autogen/2021,walPath=/var/lib/influxdb/engine/wal/c1e12f6c56b4b591/autogen/2021#!~#counter
May 16 08:40:58 monitoring.stefany.eu influxd-systemd-start.sh[533598]: goroutine 15349 [running]:
May 16 08:40:58 monitoring.stefany.eu influxd-systemd-start.sh[533598]: github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*directIndex).Add(0xc024a227e0, {0x7fa15893a300, 0xcd, 0x28655}, 0x0, 0x175f6fffbe10573d, 0x175f70c5a6033c84, 0x5558cb2, 0x2d6)
May 16 08:40:58 monitoring.stefany.eu influxd-systemd-start.sh[533598]:         /root/project/tsdb/engine/tsm1/writer.go:337 +0x49a
May 16 08:40:58 monitoring.stefany.eu influxd-systemd-start.sh[533598]: github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*tsmWriter).WriteBlock(0xc02b7cd500, {0x7fa15893a300, 0xcd, 0x28655}, 0x2?, 0x2?, {0x7fa1585010fe, 0x2d2, 0x461857})
May 16 08:40:58 monitoring.stefany.eu influxd-systemd-start.sh[533598]:         /root/project/tsdb/engine/tsm1/writer.go:686 +0x19d
May 16 08:40:58 monitoring.stefany.eu influxd-systemd-start.sh[533598]: github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*Compactor).write(0xc03247b950, {0xc0366c9440, 0x57}, {0x7faa4138bd80, 0xc012f17760}, 0x1, 0x7faa3e03ffe7?)
May 16 08:40:58 monitoring.stefany.eu influxd-systemd-start.sh[533598]:         /root/project/tsdb/engine/tsm1/compact.go:1178 +0x472
May 16 08:40:58 monitoring.stefany.eu influxd-systemd-start.sh[533598]: github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*Compactor).writeNewFiles(0xc03247b950, 0x8?, 0x3e8?, {0xc03330b000?, 0x8, 0xc03b370300?}, {0x7faa4138bd80, 0xc012f17760}, 0x8?, 0xc024a22720)
May 16 08:40:58 monitoring.stefany.eu influxd-systemd-start.sh[533598]:         /root/project/tsdb/engine/tsm1/compact.go:1059 +0x326
May 16 08:40:58 monitoring.stefany.eu influxd-systemd-start.sh[533598]: github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*Compactor).compact(0xc03247b950, 0x0?, {0xc03330b000?, 0x8, 0x8}, 0xc110e73cc6d00897?)
May 16 08:40:58 monitoring.stefany.eu influxd-systemd-start.sh[533598]:         /root/project/tsdb/engine/tsm1/compact.go:966 +0x6db
May 16 08:40:58 monitoring.stefany.eu influxd-systemd-start.sh[533598]: github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*Compactor).CompactFull(0xc03247b950, {0xc03330b000, 0x8, 0x8}, 0x2?)
May 16 08:40:58 monitoring.stefany.eu influxd-systemd-start.sh[533598]:         /root/project/tsdb/engine/tsm1/compact.go:984 +0x1c7
May 16 08:40:58 monitoring.stefany.eu influxd-systemd-start.sh[533598]: github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*compactionStrategy).compactGroup(0xc0227f6460)
May 16 08:40:58 monitoring.stefany.eu influxd-systemd-start.sh[533598]:         /root/project/tsdb/engine/tsm1/engine.go:2176 +0x3cd
May 16 08:40:58 monitoring.stefany.eu influxd-systemd-start.sh[533598]: github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*compactionStrategy).Apply(0xc0227f6460)
May 16 08:40:58 monitoring.stefany.eu influxd-systemd-start.sh[533598]:         /root/project/tsdb/engine/tsm1/engine.go:2154 +0x3e
May 16 08:40:58 monitoring.stefany.eu influxd-systemd-start.sh[533598]: github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*Engine).compactLevel.func1()
May 16 08:40:58 monitoring.stefany.eu influxd-systemd-start.sh[533598]:         /root/project/tsdb/engine/tsm1/engine.go:2092 +0xe5
May 16 08:40:58 monitoring.stefany.eu influxd-systemd-start.sh[533598]: created by github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*Engine).compactLevel
May 16 08:40:58 monitoring.stefany.eu influxd-systemd-start.sh[533598]:         /root/project/tsdb/engine/tsm1/engine.go:2084 +0x1a5
May 16 08:40:58 monitoring.stefany.eu systemd[1]: influxdb.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 16 08:40:58 monitoring.stefany.eu systemd[1]: influxdb.service: Failed with result 'exit-code'.
May 16 08:40:58 monitoring.stefany.eu systemd[1]: influxdb.service: Consumed 1min 26.880s CPU time.
May 16 08:40:58 monitoring.stefany.eu systemd[1]: influxdb.service: Scheduled restart job, restart counter is at 13.
May 16 08:40:58 monitoring.stefany.eu systemd[1]: Stopped InfluxDB is an open-source, distributed, time series database.
May 16 08:40:58 monitoring.stefany.eu systemd[1]: influxdb.service: Consumed 1min 26.880s CPU time.
```

**Comment by AlexanderplUs** [comment]
I have the same problem. Any ideas how to fix or delete problem data set?

**Comment by funfried** [comment]
Yesterday I had exactly the same issue with InfluxDB 2.7.3:

```
influx_1            | ts=2023-11-08T20:14:59.259094Z lvl=info msg="TSM compaction (end)" log_id=0lO8at0l000 service=storage-engine engine=tsm1 tsm1_level=1 tsm1_strategy=level op_name=tsm1_compact_group op_event=end op_elapsed=2261.598ms
influx_1            | panic: keys must be added in sorted order: lps_livebox_logs,adCampaignId=470,airtangoUid=04:82:10:10:9b:ed,dataType=DEVICE_UPTIME,liveBoxAudioChannelId=-1,liveBoxAudioProgramListId=-1,liveBoxChannelId=11,liveBoxId=1885,liveBoxName=LB_20796,liveBoxNameAndId=LB_20796\ (1885),liveBoxProgramListId=1,livePointId=340,livePointName=Cleverfit\ Hanau,livePointNameAndId=Cleverfit\ Hanau\ (340),livePointType=Fitnessstudio,logLevel=TRACE,source=postUptimeMetric,sourceType=SCRIPT,thread=SpringTaskExecutorThread-40#!~#livePointLongitude < lps_livebox_logs,adCampaignId=470,airtangoUid=04:82:10:10:9b:ed,dataType=DEVICE_UPTIME,liveBoxAudioChannelId=-1,liveBoxAudioProgramListId=-1,liveBoxChannelId=11,liveBoxId=1885,liveBoxName=LB_20796,liveBoxNameAndId=LB_20796\ (1885),liveBoxProgramListId=1,livePointId=340,livePointName=Cleverfit\ Hanau,livePointNameAndId=Cleverfit\ Hanau\ (340),livePointType=Fitnessstudio,logLevel=TRACE,source=postUptimeMetsic,sourceType=SCRIPT,thread=SpringTaskExecutorThread-40#!~#livePointLatitude
influx_1            |
influx_1            | goroutine 4288 [running]:
influx_1            | github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*directIndex).Add(0xc0b885e4e0, {0x7f5e4f3a63e7, 0x1e5, 0x104b015}, 0x0, 0x1795b29cba82b200, 0x1795b29cba82b200, 0xaffcd4, 0x22)
influx_1            | 	/root/project/tsdb/engine/tsm1/writer.go:337 +0x49a
influx_1            | github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*tsmWriter).WriteBlock(0xc0ab9c6740, {0x7f5e4f3a63e7, 0x1e5, 0x104b015}, 0x2?, 0x2?, {0x7f5e4e4ef5c8, 0x1e, 0x1f01e34})
influx_1            | 	/root/project/tsdb/engine/tsm1/writer.go:686 +0x198
influx_1            | github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*Compactor).write(0xc087582900, {0xc0cf063020, 0x58}, {0x7fc25f116340, 0xc01368ac60}, 0x1, 0x7fc25be3e2c5?)
influx_1            | 	/root/project/tsdb/engine/tsm1/compact.go:1178 +0x472
influx_1            | github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*Compactor).writeNewFiles(0xc087582900, 0x8?, 0x3e8?, {0xc089a3fe80?, 0x8, 0xc09a800540?}, {0x7fc25f116340, 0xc01368ac60}, 0x8?, 0xc0b885e420)
influx_1            | 	/root/project/tsdb/engine/tsm1/compact.go:1059 +0x326
influx_1            | github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*Compactor).compact(0xc087582900, 0x80?, {0xc089a3fe80?, 0x8, 0x8}, 0xc14b18f03b755716?)
influx_1            | 	/root/project/tsdb/engine/tsm1/compact.go:966 +0x6db
influx_1            | github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*Compactor).CompactFull(0xc087582900, {0xc089a3fe80, 0x8, 0x8}, 0x2?)
influx_1            | 	/root/project/tsdb/engine/tsm1/compact.go:984 +0x1c7
influx_1            | github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*compactionStrategy).compactGroup(0xc09215f960)
influx_1            | 	/root/project/tsdb/engine/tsm1/engine.go:2176 +0x3cd
influx_1            | github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*compactionStrategy).Apply(0xc09215f960)
influx_1            | 	/root/project/tsdb/engine/tsm1/engine.go:2154 +0x3e
influx_1            | github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*Engine).compactLevel.func1()
influx_1            | 	/root/project/tsdb/engine/tsm1/engine.go:2092 +0xe5
influx_1            | created by github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*Engine).compactLevel
influx_1            | 	/root/project/tsdb/engine/tsm1/engine.go:2084 +0x1a5
```

I had to delete my bucket, after that Influx was starting up again.

Is anyone looking into this?

Cheers,
Fabian

**Comment by funfried** [comment]
Hello everyone,

I have news regarding this issue: if someone ever comes around this error message, please check your hardware as for us this was a memory (maybe even mainboard) issue which caused this. After we moved our hard disks into another system everything worked great again.

Cheers,
Fabian

**Comment by particleflux** [comment]
Same problem with 1.7.4. Persistent crash on start. `influx_inspect verify` reported all as healthy.

Fixed it by deleting the last `.tsm` file mentioned in logs above the crash

```
2025-01-27T09:37:10.278252Z     info    Compacting file {"log_id": "0uLmkqCG000", "engine": "tsm1", "tsm1_level": 1, "tsm1_strategy": "level", "trace_id": "0uLmnYXG000", "op_name": "tsm1_compact_group", "tsm1_index": 7, "tsm1_file": "/var/lib/influxdb/data/_internal/monitor/2909/000000048-000000001.tsm"}
2025-01-27T09:37:12.310613Z     info    TSM compaction (end)    {"log_id": "0uLmkqCG000", "engine": "tsm1", "tsm1_level": 1, "tsm1_strategy": "level", "trace_id": "0uLmnYXG000", "op_name": "tsm1_compact_group", "op_event": "end", "op_elapsed": "2033.136ms"}
panic: keys must be added in sorted order: tsm1_engine,database=personal,engine=tsm1,hostname=320f36f17a7a,id=972,indexType=inmem,path=/var/lib/influxdb/data/personal/autogen/972,retentionPolicy=autogen,walPath=/var/lib/influxdb/wal/personal/autogen/972#!~#tsmFullCompactionDuration < tsm1_engine,database=personal,engine=tsm1,hostname=320f36f17a7a,id=972,indexType=inmem,path=/var?lib/influxdb/data/personal/autogen/972,retentionPolicy=autogen,walPath=/var/lib/influxdb/wal/personal/autogen/972#!~#cacheCompactionsActive
```

e.g. `rm /var/lib/influxdb/data/_internal/monitor/2909/000000048-000000001.tsm`
