### ISSUE TITLE
debian package has wrong version number

### ISSUE THREAD

**Issue by uvolmer** [influxdata/influxdb#23473]
influxdb 2.x on debian stable:

``` 
sudo apt-get update && sudo apt-get dist-upgrade && sudo apt-get clean
Hit:1 http://mirror.netcologne.de/debian bullseye InRelease
Hit:2 http://mirror.netcologne.de/debian bullseye-updates InRelease         
Hit:3 http://security.debian.org/debian-security bullseye-security InRelease                                                                               
Hit:4 https://repos.influxdata.com/debian bullseye InRelease                                                                                               
Hit:5 https://packages.grafana.com/oss/deb stable InRelease                     
Reading package lists... Done                             
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  linux-image-5.10.0-12-amd64 linux-image-5.10.0-13-amd64
Use 'sudo apt autoremove' to remove them.
The following packages will be upgraded:
  influxdb2
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/89,4 MB of archives.
After this operation, 35,2 MB disk space will be freed.
Do you want to continue? [Y/n] 
dpkg-deb: error: parsing file '/tmp/dpkg-deb.ZyqsmK/control' near line 2 package 'influxdb2':
 'Version' field value 'v2.3.0-1': version number does not start with digit
Traceback (most recent call last):
  File "/usr/share/apt-listchanges/DebianFiles.py", line 124, in readdeb
    output = subprocess.check_output(command)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dpkg-deb', '-f', '/var/cache/apt/archives/influxdb2_v2.3.0-1_amd64.deb', 'Package', 'Source', 'Version', 'Architecture', 'Status']' returned non-zero exit status 2.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/apt-listchanges", line 323, in <module>
    main(config)
  File "/usr/bin/apt-listchanges", line 104, in main
    pkg = DebianFiles.Package(deb)
  File "/usr/share/apt-listchanges/DebianFiles.py", line 358, in __init__
    parser.readdeb(self.path)
  File "/usr/share/apt-listchanges/DebianFiles.py", line 127, in readdeb
    raise RuntimeError(_("Error processing '%(what)s': %(errmsg)s") %
RuntimeError: Error processing '/var/cache/apt/archives/influxdb2_v2.3.0-1_amd64.deb': Command '['dpkg-deb', '-f', '/var/cache/apt/archives/influxdb2_v2.3.0-1_amd64.deb', 'Package', 'Source', 'Version', 'Architecture', 'Status']' returned non-zero exit status 2.
dpkg: error processing archive /var/cache/apt/archives/influxdb2_v2.3.0-1_amd64.deb (--unpack):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'influxdb2':
 'Version' field value 'v2.3.0-1': version number does not start with digit
Errors were encountered while processing:
 /var/cache/apt/archives/influxdb2_v2.3.0-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by uvolmer** [comment]
issue is solved in the meantime

**Comment by derkgort** [comment]
This is happening with the centos/rhel packages too
The version in the packages for 2.2.0 and 2.3.0 are:

2.2.0
v2.3.0

This makes it not able to upgrade.

`# yum install influxdb2-2.3.0.x86_64.rpm 
Loaded plugins: fastestmirror, priorities
Examining influxdb2-2.3.0.x86_64.rpm: influxdb2-v2.3.0-1.x86_64
influxdb2-2.3.0.x86_64.rpm: does not update installed package.
Error: Nothing to do

# rpm -Uvh influxdb2-2.3.0.x86_64.rpm 
error: Failed dependencies:
        influxdb2 < 2.1.0 conflicts with (installed) influxdb2-cli-0:2.3.0-1.x86_64`
