### ISSUE TITLE
InfluxDB v2.4.0 Error Abort

### ISSUE THREAD

**Issue by mdjs147** [influxdata/influxdb#23832]
The server is importing old data (from the year before last to the present), writing new data, and querying data. The runtime is suddenly abnormal.

__Actual behavior:__
influxdata  crash

__Environment info:__
 InfluxDB version: 2.4
windows server 2022
Memory 32GB

__Config:__
{
 "http-bind-address": ":....",
 "engine-path": "D:/influxdb/engine",
 "query-concurrency": 10,
 "query-initial-memory-bytes":10485760,
 "query-memory-bytes": 20971520,
"storage-cache-max-memory-size": 1073741824
}

__Logs:__

goroutine 15972 [select, 3 minutes]:
github.com/influxdata/influxdb/v2/query/control.(*Controller).processQueryQueue(0xc06c0f4ea0)
        /root/project/query/control/controller.go:442 +0x88
github.com/influxdata/influxdb/v2/query/control.New.func1()
        /root/project/query/control/controller.go:231 +0x5d
created by github.com/influxdata/influxdb/v2/query/control.New
        /root/project/query/control/controller.go:229 +0x9be

goroutine 16227 [IO wait]:
internal/poll.runtime_pollWait(0x1efed56448, 0x72)
        /go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0x23?, 0xc01f71da38?, 0x0)
        /go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.execIO(0xc04c93ca18, 0xc01f71da40)
        /go/src/internal/poll/fd_windows.go:175 +0xe5
internal/poll.(*FD).acceptOne(0xc04c93ca00, 0x864c, {0xc005d0a0f0?, 0x4879ff?, 0x0?}, 0x0?)
        /go/src/internal/poll/fd_windows.go:942 +0x6d
internal/poll.(*FD).Accept(0xc04c93ca00, 0xc01f71dc18)
        /go/src/internal/poll/fd_windows.go:976 +0x1d6
net.(*netFD).accept(0xc04c93ca00)
        /go/src/net/fd_windows.go:139 +0x65
net.(*TCPListener).accept(0xc011effcb0)
        /go/src/net/tcpsock_posix.go:139 +0x28
net.(*TCPListener).Accept(0xc011effcb0)
        /go/src/net/tcpsock.go:288 +0x3d
net/http.(*Server).Serve(0xc05cfdaee0, {0x72c7c90, 0xc011effcb0})
        /go/src/net/http/server.go:3039 +0x385
github.com/influxdata/influxdb/v2/cmd/influxd/launcher.(*Launcher).runHTTP.func1(0x0?)
        /root/project/cmd/influxd/launcher/launcher.go:1109 +0x31f
created by github.com/influxdata/influxdb/v2/cmd/influxd/launcher.(*Launcher).runHTTP
        /root/project/cmd/influxd/launcher/launcher.go:1105 +0x76a

goroutine 16033 [select, 3 minutes]:
github.com/influxdata/influxdb/v2/query/control.(*Controller).processQueryQueue(0xc06c0f4ea0)
        /root/project/query/control/controller.go:442 +0x88
github.com/influxdata/influxdb/v2/query/control.New.func1()
        /root/project/query/control/controller.go:231 +0x5d
created by github.com/influxdata/influxdb/v2/query/control.New
        /root/project/query/control/controller.go:229 +0x9be
goroutine 16172 [chan receive, 61 minutes]:
github.com/influxdata/influxdb/v2/task/backend/scheduler.(*TreeScheduler).work(0xc05d2fc240, {0x72ca1e0, 0xc0000a0010}, 0x0?)
        /root/project/task/backend/scheduler/treescheduler.go:312 +0xe5
created by github.com/influxdata/influxdb/v2/task/backend/scheduler.NewScheduler
        /root/project/task/backend/scheduler/treescheduler.go:139 +0x34f

goroutine 16173 [chan receive, 61 minutes]:
github.com/influxdata/influxdb/v2/task/backend/scheduler.(*TreeScheduler).work(0xc05d2fc240, {0x72ca1e0, 0xc0000a0010}, 0x0?)
        /root/project/task/backend/scheduler/treescheduler.go:312 +0xe5
created by github.com/influxdata/influxdb/v2/task/backend/scheduler.NewScheduler
        /root/project/task/backend/scheduler/treescheduler.go:139 +0x34f

goroutine 16174 [chan receive, 61 minutes]:
github.com/influxdata/influxdb/v2/task/backend/scheduler.(*TreeScheduler).work(0xc05d2fc240, {0x72ca1e0, 0xc0000a0010}, 0x0?)
        /root/project/task/backend/scheduler/treescheduler.go:312 +0xe5
created by github.com/influxdata/influxdb/v2/task/backend/scheduler.NewScheduler
        /root/project/task/backend/scheduler/treescheduler.go:139 +0x34f

goroutine 16175 [chan receive, 61 minutes]:
github.com/influxdata/influxdb/v2/task/backend/scheduler.(*TreeScheduler).work(0xc05d2fc240, {0x72ca1e0, 0xc0000a0010}, 0x0?)
        /root/project/task/backend/scheduler/treescheduler.go:312 +0xe5
created by github.com/influxdata/influxdb/v2/task/backend/scheduler.NewScheduler
        /root/project/task/backend/scheduler/treescheduler.go:139 +0x34f

goroutine 16176 [chan receive, 61 minutes]:
github.com/influxdata/influxdb/v2/task/backend/scheduler.(*TreeScheduler).work(0xc05d2fc240, {0x72ca1e0, 0xc0000a0010}, 0x0?)
        /root/project/task/backend/scheduler/treescheduler.go:312 +0xe5
created by github.com/influxdata/influxdb/v2/task/backend/scheduler.NewScheduler
        /root/project/task/backend/scheduler/treescheduler.go:139 +0x34f

goroutine 16177 [chan receive, 61 minutes]:
github.com/influxdata/influxdb/v2/task/backend/scheduler.(*TreeScheduler).work(0xc05d2fc240, {0x72ca1e0, 0xc0000a0010}, 0x0?)
        /root/project/task/backend/scheduler/treescheduler.go:312 +0xe5
created by github.com/influxdata/influxdb/v2/task/backend/scheduler.NewScheduler
        /root/project/task/backend/scheduler/treescheduler.go:139 +0x34f

goroutine 16178 [select]:
github.com/influxdata/influxdb/v2/task/backend/scheduler.NewScheduler.func2()
        /root/project/task/backend/scheduler/treescheduler.go:156 +0xdf
created by github.com/influxdata/influxdb/v2/task/backend/scheduler.NewScheduler
        /root/project/task/backend/scheduler/treescheduler.go:152 +0x565

goroutine 16190 [select]:
github.com/influxdata/influxdb/v2/gather.NewScheduler.func1()
        /root/project/gather/scheduler.go:57 +0xff
created by github.com/influxdata/influxdb/v2/gather.NewScheduler
        /root/project/gather/scheduler.go:54 +0x219

goroutine 16191 [select]:
github.com/influxdata/influxdb/v2/gather.NewScheduler.func2()
        /root/project/gather/scheduler.go:81 +0xfa
created by github.com/influxdata/influxdb/v2/gather.NewScheduler
        /root/project/gather/scheduler.go:76 +0x26a

goroutine 16226 [select, 61 minutes]:
github.com/influxdata/influxdb/v2/telemetry.(*Reporter).Report(0xc011effc50, {0x72ca1a8, 0xc000a6e180})
        /root/project/telemetry/reporter.go:44 +0x445
github.com/influxdata/influxdb/v2/cmd/influxd/launcher.(*Launcher).runReporter.func1()
        /root/project/cmd/influxd/launcher/launcher.go:1187 +0x66
created by github.com/influxdata/influxdb/v2/cmd/influxd/launcher.(*Launcher).runReporter
        /root/project/cmd/influxd/launcher/launcher.go:1185 +0x278

goroutine 398904 [IO wait]:
internal/poll.runtime_pollWait(0x1efed56358, 0x72)
        /go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0x43d4e0?, 0xc01f72c340?, 0x0)
        /go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.execIO(0xc022bfec98, 0x6f20b90)
        /go/src/internal/poll/fd_windows.go:175 +0xe5
internal/poll.(*FD).Read(0xc022bfec80, {0xc0394a1000, 0x1000, 0x1000})
        /go/src/internal/poll/fd_windows.go:441 +0x25f
net.(*netFD).Read(0xc022bfec80, {0xc0394a1000?, 0x4ec026?, 0x1efed56440?})
        /go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc04a65e488, {0xc0394a1000?, 0x0?, 0x0?})
        /go/src/net/net.go:183 +0x45
net/http.(*connReader).Read(0xc043f9ba40, {0xc0394a1000, 0x1000, 0x1000})
        /go/src/net/http/server.go:780 +0x16d
bufio.(*Reader).fill(0xc05d3ca780)
        /go/src/bufio/bufio.go:106 +0x103
bufio.(*Reader).Peek(0xc05d3ca780, 0x4)
        /go/src/bufio/bufio.go:144 +0x5d
net/http.(*conn).serve(0xc0581ce960, {0x72ca250, 0xc006126c60})
        /go/src/net/http/server.go:1992 +0x716
created by net/http.(*Server).Serve
        /go/src/net/http/server.go:3071 +0x4db

goroutine 143718 [IO wait]:
internal/poll.runtime_pollWait(0x1efed55ea8, 0x72)
        /go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0x43d4e0?, 0xc0382491e0?, 0x0)
        /go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.execIO(0xc031df0f18, 0x6f20b90)
        /go/src/internal/poll/fd_windows.go:175 +0xe5
internal/poll.(*FD).Read(0xc031df0f00, {0xc053edd000, 0x1000, 0x1000})
        /go/src/internal/poll/fd_windows.go:441 +0x25f
net.(*netFD).Read(0xc031df0f00, {0xc053edd000?, 0x4ec026?, 0x1efed55f90?})
        /go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc07d2168a8, {0xc053edd000?, 0x0?, 0x0?})
        /go/src/net/net.go:183 +0x45
net/http.(*connReader).Read(0xc04cec8a50, {0xc053edd000, 0x1000, 0x1000})
        /go/src/net/http/server.go:780 +0x16d
bufio.(*Reader).fill(0xc031443020)
        /go/src/bufio/bufio.go:106 +0x103
bufio.(*Reader).Peek(0xc031443020, 0x4)
        /go/src/bufio/bufio.go:144 +0x5d
net/http.(*conn).serve(0xc05bf0da40, {0x72ca250, 0xc006126c60})
        /go/src/net/http/server.go:1992 +0x716
created by net/http.(*Server).Serve
        /go/src/net/http/server.go:3071 +0x4db

goroutine 16317 [select]:
net/http.(*persistConn).writeLoop(0xc01cc26fc0)
        /go/src/net/http/transport.go:2392 +0xf5
created by net/http.(*Transport).dialConn
        /go/src/net/http/transport.go:1751 +0x1791

goroutine 16327 [IO wait]:
internal/poll.runtime_pollWait(0x1efed56088, 0x72)
        /go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0x43d4e0?, 0xc01f542680?, 0x0)
        /go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.execIO(0xc02f86a798, 0x6f20b90)
        /go/src/internal/poll/fd_windows.go:175 +0xe5
internal/poll.(*FD).Read(0xc02f86a780, {0xc03f24f000, 0x1000, 0x1000})
        /go/src/internal/poll/fd_windows.go:441 +0x25f
net.(*netFD).Read(0xc02f86a780, {0xc03f24f000?, 0x4ec026?, 0x1efed56170?})
        /go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc01b2ff078, {0xc03f24f000?, 0x0?, 0x0?})
        /go/src/net/net.go:183 +0x45
net/http.(*connReader).Read(0xc01c5bcfc0, {0xc03f24f000, 0x1000, 0x1000})
        /go/src/net/http/server.go:780 +0x16d
bufio.(*Reader).fill(0xc013a0af60)
        /go/src/bufio/bufio.go:106 +0x103
bufio.(*Reader).Peek(0xc013a0af60, 0x4)
        /go/src/bufio/bufio.go:144 +0x5d
net/http.(*conn).serve(0xc01c5c0820, {0x72ca250, 0xc006126c60})
        /go/src/net/http/server.go:1992 +0x716
created by net/http.(*Server).Serve
        /go/src/net/http/server.go:3071 +0x4db

goroutine 16316 [IO wait]:
internal/poll.runtime_pollWait(0x1efed56178, 0x72)
        /go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0x46e653?, 0x6353f92b?, 0x0)
        /go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.execIO(0xc04c7ec018, 0x6f20b90)
        /go/src/internal/poll/fd_windows.go:175 +0xe5
internal/poll.(*FD).Read(0xc04c7ec000, {0xc0383e9000, 0x1000, 0x1000})
        /go/src/internal/poll/fd_windows.go:441 +0x25f
net.(*netFD).Read(0xc04c7ec000, {0xc0383e9000?, 0x4071b0?, 0x95874270aa8?})
        /go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc01b6e4ee8, {0xc0383e9000?, 0x0?, 0x0?})
        /go/src/net/net.go:183 +0x45
net/http.(*persistConn).Read(0xc01cc26fc0, {0xc0383e9000?, 0xc03e198780?, 0xc021733d30?})
        /go/src/net/http/transport.go:1929 +0x4e
bufio.(*Reader).fill(0xc01ca32f00)
        /go/src/bufio/bufio.go:106 +0x103
bufio.(*Reader).Peek(0xc01ca32f00, 0x1)
        /go/src/bufio/bufio.go:144 +0x5d
net/http.(*persistConn).readLoop(0xc01cc26fc0)
        /go/src/net/http/transport.go:2093 +0x1ac
created by net/http.(*Transport).dialConn
        /go/src/net/http/transport.go:1750 +0x173e

goroutine 951869 [chan receive]:
github.com/influxdata/flux.(*queryResultIterator).More(0xc069ed4600)
        /go/pkg/mod/github.com/influxdata/flux@v0.179.0/result_iterator.go:61 +0x56
github.com/influxdata/flux.(*DelimitedMultiResultEncoder).Encode(0xc069ed4660, {0x72ad740?, 0xc069e51020}, {0x72cf620, 0xc069ed4600})
        /go/pkg/mod/github.com/influxdata/flux@v0.179.0/result.go:303 +0x8c
github.com/influxdata/influxdb/v2/query.ProxyQueryServiceAsyncBridge.Query({{0x72b0da0?, 0xc06c0f4ea0?}}, {0x72ca250?, 0xc069fa8540?}, {0x72ad740, 0xc069e51020}, 0xc069de3490)
        /root/project/query/bridges.go:146 +0x244
github.com/influxdata/influxdb/v2/http.(*FluxHandler).handleQuery(0xc037d80800, {0x72c4e70, 0xc069de7a00}, 0xc069f92c10?)
        /root/project/http/query_handler.go:198 +0x949
net/http.HandlerFunc.ServeHTTP(0x68e9e40?, {0x72c4e70?, 0xc069de7a00?}, 0x4?)
        /go/src/net/http/server.go:2084 +0x2f
github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1({0x72c4e70, 0xc069de7a00}, 0x1ee90b49b8?)
        /go/pkg/mod/github.com/!n!y!times/gziphandler@v1.0.1/gzip.go:293 +0x291
net/http.HandlerFunc.ServeHTTP(0xb?, {0x72c4e70?, 0xc069de7a00?}, 0x40f0c5?)
        /go/src/net/http/server.go:2084 +0x2f
github.com/influxdata/influxdb/v2/http.(*proxyHandler).ServeHTTP(0xc0013cba80, {0x72c4e70, 0xc069de7a00}, 0x88?)
        /root/project/http/proxy_handler.go:33 +0x68
github.com/influxdata/httprouter.(*Router).Handler.func1({0x72c4e70?, 0xc069de7a00?}, 0x69c98c0?, {0x0?, 0x68e9e40?, 0xc069de9b70?})
        /go/pkg/mod/github.com/influxdata/httprouter@v1.3.1-0.20191122104820-ee83e2772f69/router.go:325 +0x2c4
github.com/influxdata/httprouter.(*Router).ServeHTTP(0xc02f2cc630, {0x72c4e70, 0xc069de7a00}, 0xc054e85700)
        /go/pkg/mod/github.com/influxdata/httprouter@v1.3.1-0.20191122104820-ee83e2772f69/router.go:453 +0x4af
github.com/go-chi/chi.(*Mux).Mount.func1({0x72c4e70, 0xc069de7a00}, 0xc054e85700)
        /go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:298 +0x13b
net/http.HandlerFunc.ServeHTTP(0x69b35e0?, {0x72c4e70?, 0xc069de7a00?}, 0xc069bdb000?)
        /go/src/net/http/server.go:2084 +0x2f
github.com/go-chi/chi.(*Mux).routeHTTP(0xc06a377080, {0x72c4e70, 0xc069de7a00}, 0xc054e85700)
        /go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:431 +0x1f9
net/http.HandlerFunc.ServeHTTP(0xc069debe60?, {0x72c4e70?, 0xc069de7a00?}, 0x0?)
        /go/src/net/http/server.go:2084 +0x2f
github.com/influxdata/influxdb/v2/kit/transport/http.SetCORS.func1({0x72c4e70, 0xc069de7a00}, 0xc054e85700)
        /root/project/kit/transport/http/middleware.go:36 +0x308
net/http.HandlerFunc.ServeHTTP(0x1ee974d412?, {0x72c4e70?, 0xc069de7a00?}, 0xc069bcb490?)
        /go/src/net/http/server.go:2084 +0x2f
github.com/go-chi/chi/middleware.StripSlashes.func1({0x72c4e70, 0xc069de7a00}, 0xc054e85700)
        /go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/middleware/strip.go:25 +0x102
net/http.HandlerFunc.ServeHTTP(0xc069debe60?, {0x72c4e70?, 0xc069de7a00?}, 0x0?)
        /go/src/net/http/server.go:2084 +0x2f
github.com/influxdata/influxdb/v2/kit/transport/http.SkipOptions.func1({0x72c4e70, 0xc069de7a00}, 0xc054e85700)
        /root/project/kit/transport/http/middleware.go:81 +0xb9
net/http.HandlerFunc.ServeHTTP(0xc069f93210?, {0x72c4e70?, 0xc069de7a00?}, 0x20?)
        /go/src/net/http/server.go:2084 +0x2f
github.com/influxdata/influxdb/v2/http.panicMW.func1.1({0x72c4e70?, 0xc069de7a00?}, 0xc069fa8210?)
        /root/project/http/router.go:126 +0x92
net/http.HandlerFunc.ServeHTTP(0x15?, {0x72c4e70?, 0xc069de7a00?}, 0x6d72c59?)
        /go/src/net/http/server.go:2084 +0x2f
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc06a377080, {0x72c4e70, 0xc069de7a00}, 0xc054e85700)
        /go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:70 +0x40e
github.com/influxdata/influxdb/v2/kit/feature.(*Handler).ServeHTTP(0xc03d60bd00, {0x72c4e70, 0xc069de7a00}, 0xc054e85600)
        /root/project/kit/feature/middleware.go:43 +0x3ac
github.com/influxdata/influxdb/v2/http.(*AuthenticationHandler).ServeHTTP(0xc02bfa50a0, {0x72c4e70, 0xc069de7a00}, 0xc054e85500)
        /root/project/http/authentication_middleware.go:127 +0x467
github.com/influxdata/influxdb/v2/kit/transport/http.SetCORS.func1({0x72c4e70, 0xc069de7a00}, 0xc054e85500)
        /root/project/kit/transport/http/middleware.go:36 +0x308
net/http.HandlerFunc.ServeHTTP(0xc069debe60?, {0x72c4e70?, 0xc069de7a00?}, 0xc069bdb001?)
        /go/src/net/http/server.go:2084 +0x2f
github.com/influxdata/influxdb/v2/kit/transport/http.SkipOptions.func1({0x72c4e70, 0xc069de7a00}, 0xc054e85500)
        /root/project/kit/transport/http/middleware.go:81 +0xb9
net/http.HandlerFunc.ServeHTTP(0x6d4706f?, {0x72c4e70?, 0xc069de7a00?}, 0xc?)
        /go/src/net/http/server.go:2084 +0x2f
github.com/influxdata/influxdb/v2/http.(*PlatformHandler).ServeHTTP(0xc03d60bf00, {0x72c4e70, 0xc069de7a00}, 0xc054e85500)
        /root/project/http/platform_handler.go:81 +0x1d2
github.com/go-chi/chi.(*Mux).Mount.func1({0x72c4e70, 0xc069de7a00}, 0xc054e85500)
        /go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:298 +0x13b
net/http.HandlerFunc.ServeHTTP(0x0?, {0x72c4e70?, 0xc069de7a00?}, 0x16e0374c38?)
        /go/src/net/http/server.go:2084 +0x2f
github.com/influxdata/influxdb/v2/kit/transport/http.Metrics.func1.1({0x72c7ea0?, 0xc069bc4fc0}, 0xc054e85500)
        /root/project/kit/transport/http/middleware.go:66 +0x1d0
net/http.HandlerFunc.ServeHTTP(0xc069f93808?, {0x72c7ea0?, 0xc069bc4fc0?}, 0x20?)
        /go/src/net/http/server.go:2084 +0x2f
github.com/influxdata/influxdb/v2/kit/transport/http.Trace.func1.1({0x72c7ea0, 0xc069bc4fc0}, 0x1?)
        /root/project/kit/transport/http/middleware.go:106 +0x30c
net/http.HandlerFunc.ServeHTTP(0xc00fd724b0?, {0x72c7ea0?, 0xc069bc4fc0?}, 0xc030623ab8?)
        /go/src/net/http/server.go:2084 +0x2f
github.com/go-chi/chi.(*ChainHandler).ServeHTTP(0x69b35e0?, {0x72c7ea0?, 0xc069bc4fc0?}, 0xc0149fa065?)
        /go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/chain.go:31 +0x2c
github.com/go-chi/chi.(*Mux).routeHTTP(0xc012736ae0, {0x72c7ea0, 0xc069bc4fc0}, 0xc054e85400)
        /go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:431 +0x1f9
net/http.HandlerFunc.ServeHTTP(0x1f00320d90?, {0x72c7ea0?, 0xc069bc4fc0?}, 0x90?)
        /go/src/net/http/server.go:2084 +0x2f
github.com/influxdata/influxdb/v2/http.(*AddHeader).Middleware.func1({0x72c7ea0, 0xc069bc4fc0}, 0x659c601?)
        /root/project/http/handler.go:102 +0x77
net/http.HandlerFunc.ServeHTTP(0x72ca1a8?, {0x72c7ea0?, 0xc069bc4fc0?}, 0x659c640?)
        /go/src/net/http/server.go:2084 +0x2f
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc012736ae0, {0x72c7ea0, 0xc069bc4fc0}, 0xc046650300)
        /go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:86 +0x3c2
github.com/influxdata/influxdb/v2/http.(*Handler).ServeHTTP(0xc0149fa073?, {0x72c7ea0?, 0xc069bc4fc0?}, 0xc011e95aa0?)
        /root/project/http/handler.go:166 +0x2f
net/http.serverHandler.ServeHTTP({0x72c0d28?}, {0x72c7ea0, 0xc069bc4fc0}, 0xc046650300)
        /go/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc05372d400, {0x72ca250, 0xc006126c60})
        /go/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
        /go/src/net/http/server.go:3071 +0x4db

goroutine 399848 [select]:
github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*Engine).compactCache(0xc027a65180)
        /root/project/tsdb/engine/tsm1/engine.go:1958 +0x12d
github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*Engine).enableSnapshotCompactions.func1()
        /root/project/tsdb/engine/tsm1/engine.go:470 +0x58
created by github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*Engine).enableSnapshotCompactions
        /root/project/tsdb/engine/tsm1/engine.go:470 +0x18d

goroutine 952027 [IO wait]:
internal/poll.runtime_pollWait(0x1efed56268, 0x72)
        /go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc0211bcbe0?, 0x9565169cc93?, 0x0)
        /go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.execIO(0xc02f2d2518, 0x6f20b90)
        /go/src/internal/poll/fd_windows.go:175 +0xe5
internal/poll.(*FD).Read(0xc02f2d2500, {0xc069a69451, 0x1, 0x1})
        /go/src/internal/poll/fd_windows.go:441 +0x25f
net.(*netFD).Read(0xc02f2d2500, {0xc069a69451?, 0xc06a3f0c00?, 0xc06a3f0b40?})
        /go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc062084b88, {0xc069a69451?, 0xc0699fd938?, 0x0?})
        /go/src/net/net.go:183 +0x45
net/http.(*connReader).backgroundRead(0xc069a69440)
        /go/src/net/http/server.go:672 +0x3f
created by net/http.(*connReader).startBackgroundRead
        /go/src/net/http/server.go:668 +0xca

goroutine 399849 [select]:
github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*Engine).compact(0xc027a65180, 0x0?)
        /root/project/tsdb/engine/tsm1/engine.go:1999 +0x257
github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*Engine).enableLevelCompactions.func1()
        /root/project/tsdb/engine/tsm1/engine.go:391 +0x58
created by github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*Engine).enableLevelCompactions
        /root/project/tsdb/engine/tsm1/engine.go:391 +0x1be
rax     0x21547a0
rbx     0xd42d7c060
rcx     0xc20240b8
rdi     0xc221aec8
rsi     0xd33bb0f80
rbp     0x2f97bde0
rsp     0xc2023ff0
r8      0xd33bb0ff0
r9      0x1
r10     0x3
r11     0xc221aab0
r12     0x2f97be58
r13     0xc221ef50
r14     0xc221adc0
r15     0xc221ad50
rip     0x2153847
rflags  0x10203
cs      0x33
fs      0x53
gs      0x2b

**Comment by mdjs147** [comment]
Exception 0xc00000fd 0x1 0xcd533fe8 0x2153847
PC=0x2153847
signal arrived during external code execution

runtime.cgocall(0x2034f80, 0xc02f6e98d0)
        /go/src/runtime/cgocall.go:157 +0x4a fp=0xc02f6e98a8 sp=0xc02f6e9870 pc=0x404b2a
github.com/influxdata/flux/libflux/go/libflux._Cfunc_flux_analyze(0x2f5ee5e0, 0x300f21a0, 0xc04a466848)
        _cgo_gotypes.go:110 +0x5b fp=0xc02f6e98d0 sp=0xc02f6e98a8 pc=0x98883b
github.com/influxdata/flux/libflux/go/libflux.AnalyzeWithOptions.func3(0x300f21a0?, 0x2?, 0x0?)
        /go/pkg/mod/github.com/influxdata/flux@v0.179.0/libflux/go/libflux/analyze.go:140 +0x87 fp=0xc02f6e9918 sp=0xc02f6e98d0 pc=0x98b007
github.com/influxdata/flux/libflux/go/libflux.AnalyzeWithOptions(0xc04a466820, {{0x0?, 0x30?, 0x19dac34270?}})
        /go/pkg/mod/github.com/influxdata/flux@v0.179.0/libflux/go/libflux/analyze.go:140 +0x15c fp=0xc02f6e9a08 sp=0xc02f6e9918 pc=0x98abdc
github.com/influxdata/flux/runtime.AnalyzePackage({0x72ca250?, 0xc04a6c9320?}, {0x72c4240?, 0xc04a466820})
        /go/pkg/mod/github.com/influxdata/flux@v0.179.0/runtime/analyze_libflux.go:23 +0xb2 fp=0xc02f6e9a88 sp=0xc02f6e9a08 pc=0x999f52
github.com/influxdata/flux/runtime.(*runtime).Eval(0x8b58210, {0x72ca250, 0xc04a6c9320}, {0x72c4240?, 0xc04a466820?}, {0x72bb008, 0x8bbc008}, {0xc04a469320, 0x2, 0x2})
        /go/pkg/mod/github.com/influxdata/flux@v0.179.0/runtime/runtime.go:102 +0x8b fp=0xc02f6e9b08 sp=0xc02f6e9a88 pc=0x99bf2b
github.com/influxdata/flux/lang.(*AstProgram).getSpec(0xc02b176af0, {0x72ca250, 0xc04a6c92f0}, {0x72a6df0?, 0x6896ac0?})
        /go/pkg/mod/github.com/influxdata/flux@v0.179.0/lang/compiler.go:445 +0x224 fp=0xc02f6e9c78 sp=0xc02f6e9b08 pc=0x131c284
github.com/influxdata/flux/lang.(*AstProgram).Start(0xc02b176af0, {0x72ca250, 0xc04a6c9170}, {0x72cb0f8, 0xc02b176be0})
        /go/pkg/mod/github.com/influxdata/flux@v0.179.0/lang/compiler.go:483 +0x1cf fp=0xc02f6e9e88 sp=0xc02f6e9c78 pc=0x131cb4f
github.com/influxdata/influxdb/v2/query/control.(*Controller).executeQuery(0xc02b8dff78?, 0xc02e3faea0)
        /root/project/query/control/controller.go:488 +0x22d fp=0xc02f6e9f38 sp=0xc02f6e9e88 pc=0x1e6f10d
github.com/influxdata/influxdb/v2/query/control.(*Controller).processQueryQueue(0xc059bc9d40)
        /root/project/query/control/controller.go:446 +0x2e fp=0xc02f6e9fa8 sp=0xc02f6e9f38 pc=0x1e6ee4e
github.com/influxdata/influxdb/v2/query/control.New.func1()
        /root/project/query/control/controller.go:231 +0x5d fp=0xc02f6e9fe0 sp=0xc02f6e9fa8 pc=0x1e6d35d
runtime.goexit()
        /go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc02f6e9fe8 sp=0xc02f6e9fe0 pc=0x46bdc1
created by github.com/influxdata/influxdb/v2/query/control.New
        /root/project/query/control/controller.go:229 +0x9be

goroutine 1 [chan receive]:
github.com/influxdata/influxdb/v2/cmd/influxd/launcher.cmdRunE.func1()
        /root/project/cmd/influxd/launcher/cmd.go:127 +0x317
github.com/influxdata/influxdb/v2/kit/cli.NewCommand.func1(0xc000045340?, {0x8bbc008?, 0x0?, 0x0?})
        /root/project/kit/cli/viper.go:54 +0x1e
github.com/spf13/cobra.(*Command).execute(0xc000045340, {0xc000078230, 0x0, 0x0})
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000045340)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x39c
