### ISSUE TITLE
influx_inspect check-schema can't stat path

### ISSUE THREAD

**Issue by davidby-influx** [influxdata/influxdb#23987]
__Steps to reproduce:__

1. Run `influx_inspect check-schema -path <valid path>` 
2. Receive the following error: `check-schema: error walking file: stat <valid path>: invalid argument`
3. `cd` into the directory and run without the `-path` argument
4. Get the following panic:
```
/influxdb/data/16/autogen/7676 # ./influx_inspect check-schema -conflicts-file conflicts.json -schema-file schema.json
panic: runtime error: index out of range [-3]

goroutine 1 [running]:
github.com/influxdata/influxdb/cmd/influx_inspect/type_conflicts.(*TypeConflictChecker).readFields.func1({0xc00013f7e0, 0xa}, {0xc000153c38?, 0x7fd1f10710f8?}, {0x0?, 0x0?})
	/root/project/cmd/influx_inspect/type_conflicts/type_conflicts.go:76 +0x5e5
io/fs.walkDir({0x7fd1f1927d98, 0xc0003a6580}, {0xc00013f7e0, 0xa}, {0x7fd1f192ddd0, 0xc000139ec0}, 0xc000153da8)
	/go/src/io/fs/walk.go:66 +0x78
io/fs.walkDir({0x7fd1f1927d98, 0xc0003a6580}, {0x7fd1f16a7008, 0x1}, {0x7fd1f192dd28, 0xc0003a6590}, 0xc000153da8)
	/go/src/io/fs/walk.go:85 +0x27d
io/fs.WalkDir({0x7fd1f1927d98, 0xc0003a6580}, {0x7fd1f16a7008, 0x1}, 0xc000153da8)
	/go/src/io/fs/walk.go:112 +0xde
github.com/influxdata/influxdb/cmd/influx_inspect/type_conflicts.(*TypeConflictChecker).readFields(0xc0003e4690)
	/root/project/cmd/influx_inspect/type_conflicts/type_conflicts.go:68 +0xd1
github.com/influxdata/influxdb/cmd/influx_inspect/type_conflicts.(*TypeConflictChecker).Run(0xc0003e4690, {0xc000136140, 0x4, 0x4})
	/root/project/cmd/influx_inspect/type_conflicts/type_conflicts.go:40 +0x1e7
main.(*Main).Run(0xc000153f38, {0xc000136130?, 0x7fd1f0e2c5b8?, 0x60?})
	/root/project/cmd/influx_inspect/main.go:121 +0xc27
main.main()
	/root/project/cmd/influx_inspect/main.go:31 +0x16c
```

__Expected behavior:__
The path argument should be valid and the command should work

__Actual behavior:__
Error or panic (see above)

**Comment by davidby-influx** [comment]
Interestingly, the error is returned by `fs.ValidPath` which disallows paths which start with slash.

https://pkg.go.dev/io/fs@go1.19.4#ValidPath

This is called internally by `fs.WalkDir`.

Switching to `filepath.WalkDir` fixes the `Invalid Argument` error

**Comment by davidby-influx** [comment]
I have not reproduced the panic, @aaronkoerner.  Do you have a replication scenario for that one?

I will drop you a binary to test.

**Comment by davidby-influx** [comment]
@jeffreyssmith2nd - Any ideas about this panic?  IT looks like it is near the new `fields.idxl` warning you added, but that works fine when I test it.....

**Comment by davidby-influx** [comment]
@aaronkoerner - Figured out the panic.
