### ISSUE TITLE
panic: invalid memory address or nil pointer dereference, (*integerGroupTable).advanceCursor

### ISSUE THREAD

**Issue by christiand** [influxdata/influxdb#24078]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Single threaded python script to insert datapoints in a tight loop, using async io writes
2. Query to count the number of datapoints in past few minutes
query: f'from(bucket: "{bucket}") |> range(start: -10m) |> group() |> window(every: 1s) |> count()'

__Expected behavior:__
inserts to complete, query to return

__Actual behavior:__
influxd hits an error (see below)
I have to kill the process and start it again.

__Environment info:__

* System info: Run `uname -srm` and copy the output here
Darwin 21.6.0 x86_64

* InfluxDB version: Run `influxd version` and copy the output here
InfluxDB 2.3.0 (git: 090f681737) build_date: 2022-06-16T18:48:06Z

* Other relevant environment details: Container runtime, disk info, etc

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

Default config, no modifications.

__Logs:__
2023-02-04T03:49:30.271055Z	info	Dispatcher panic	{"log_id": "0fnCphPG000", "service": "storage-reads", "component": "dispatcher", "error": "panic: runtime error: invalid memory address or nil pointer dereference"}
goroutine 133856 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
github.com/influxdata/flux/execute.(*poolDispatcher).recover(0xc000b3afc0)
	github.com/influxdata/flux@v0.171.0/execute/recover.go:53 +0x205
panic({0x608d980, 0xd120330})
	runtime/panic.go:838 +0x207
github.com/influxdata/influxdb/v2/storage/flux.(*integerGroupTable).advanceCursor(0xc0054022a0)
	github.com/influxdata/influxdb/v2/storage/flux/table.gen.go:1957 +0xc0
github.com/influxdata/influxdb/v2/storage/flux.(*integerGroupTable).advance(0xc0054022a0)
	github.com/influxdata/influxdb/v2/storage/flux/table.gen.go:1710 +0x85
github.com/influxdata/influxdb/v2/storage/flux.(*table).do(0xc0045be820?, 0xc046a3a870, 0xc05924d810)
	github.com/influxdata/influxdb/v2/storage/flux/table.go:95 +0x213
github.com/influxdata/influxdb/v2/storage/flux.(*integerGroupTable).Do(0x6331300?, 0xc0045be801?)
	github.com/influxdata/influxdb/v2/storage/flux/table.gen.go:1690 +0x37
github.com/influxdata/flux/execute.(*consecutiveTransportTable).Do(0xc046a3a840, 0xc00a9a0180)
	github.com/influxdata/flux@v0.171.0/execute/transport.go:549 +0x87
github.com/influxdata/flux/stdlib/universe.(*fixedWindowTransformation).Process(0xc0040d4a80, {0xb1, 0xc6, 0xa8, 0x26, 0x2f, 0x15, 0x57, 0x70, 0x99, ...}, ...)
	github.com/influxdata/flux@v0.171.0/stdlib/universe/window.go:356 +0xa3f
github.com/influxdata/flux/execute.(*transformationTransportAdapter).ProcessMessage(0xc061522b40, {0x68c9fd8, 0xc001ad10e0})
	github.com/influxdata/flux@v0.171.0/execute/transport.go:647 +0x195
github.com/influxdata/flux/execute.(*consecutiveTransport).processMessage(0xc008dc63c0, {0x68c9fd8, 0xc001ad10e0})
	github.com/influxdata/flux@v0.171.0/execute/transport.go:292 +0xca
github.com/influxdata/flux/execute.(*consecutiveTransport).processMessages(0xc008dc63c0, {0x68c9210?, 0xc0614ff000?}, 0xa)
	github.com/influxdata/flux@v0.171.0/execute/transport.go:246 +0xe5
github.com/influxdata/flux/execute.(*poolDispatcher).doWork(0xc000b3afc0, {0x68c9210, 0xc0614ff000})
	github.com/influxdata/flux@v0.171.0/execute/dispatcher.go:157 +0x19f
github.com/influxdata/flux/execute.(*poolDispatcher).run(0xc000b3afc0, {0x68c9210, 0xc0614ff000})
	github.com/influxdata/flux@v0.171.0/execute/dispatcher.go:135 +0x4f
github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1()
	github.com/influxdata/flux@v0.171.0/execute/dispatcher.go:75 +0x86
created by github.com/influxdata/flux/execute.(*poolDispatcher).Start
	github.com/influxdata/flux@v0.171.0/execute/dispatcher.go:71 +0x48

2023-02-04T03:49:30.274949Z	warn	internal error not returned to client	{"log_id": "0fnCphPG000", "handler": "error_logger", "error": "context canceled"}

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively happening.
# Note: This command will run for ~30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=30s"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz` and `iostat.txt` output files.
```

**Comment by lukeyeager** [comment]
I hit the same today, using the `influxdb:2.7` docker image. The command I used to generate the panic was `influx delete --bucket ${mybucket} --start 2024-01-02T00:00:00Z --stop 2024-01-04T00:00:00Z`.

```console
# influxd version
InfluxDB v2.7.5 (git: 09a9607fd9) build_date: 2024-01-05T17:17:04Z
```
```
ts=2024-02-06T19:49:04.985165Z lvl=info msg="Dispatcher panic" log_id=0nBzcZbW000 service=storage-reads component=dispatcher error="panic: runtime error: invalid memory address or nil pointer dereference" stacktrace="goroutine 13918 [running]:
runtime/debug.Stack()
        /go/src/runtime/debug/stack.go:24 +0x65
github.com/influxdata/flux/execute.(*poolDispatcher).recover(0xc0027c0fc0)
        /go/pkg/mod/github.com/influxdata/flux@v0.194.5/execute/recover.go:53 +0x205
panic({0x7f93ce2db9c0, 0x7f93cfa18cc0})
        /go/src/runtime/panic.go:884 +0x213
github.com/influxdata/influxdb/v2/storage/flux.(*floatGroupTable).advanceCursor(0xc00777c380)
        /root/project/storage/flux/table.gen.go:973 +0xcc
github.com/influxdata/influxdb/v2/storage/flux.(*floatGroupTable).advance(0xc00777c380)
        /root/project/storage/flux/table.gen.go:727 +0x85
github.com/influxdata/influxdb/v2/storage/flux.(*table).do(0xc00f0e9858?, 0xc016b41278, 0xc00f0e9848)
        /root/project/storage/flux/table.go:95 +0x219
github.com/influxdata/influxdb/v2/storage/flux.(*floatGroupTable).Do(0x7f93ce5de4a0?, 0xc016b0d501?)
        /root/project/storage/flux/table.gen.go:707 +0x37
github.com/influxdata/flux/execute.(*consecutiveTransportTable).Do(0xc016a649f0, 0xc0023b9180)
        /go/pkg/mod/github.com/influxdata/flux@v0.194.5/execute/transport.go:554 +0x87
github.com/influxdata/flux/stdlib/universe.(*fixedWindowTransformation).Process(0xc023bf3590, {0xea, 0x14, 0x7e, 0x7f, 0x88, 0x3, 0x50, 0x77, 0xbe, ...}, ...)
        /go/pkg/mod/github.com/influxdata/flux@v0.194.5/stdlib/universe/window.go:359 +0x10e9
github.com/influxdata/flux/execute.(*transformationTransportAdapter).ProcessMessage(0xc01d3fb320, {0x7f93ce6e8020, 0xc01f6d9080})
        /go/pkg/mod/github.com/influxdata/flux@v0.194.5/execute/transport.go:652 +0x195
github.com/influxdata/flux/execute.(*consecutiveTransport).processMessage(0xc023bf3680, {0x7f93ce6e8020, 0xc01f6d9080})
        /go/pkg/mod/github.com/influxdata/flux@v0.194.5/execute/transport.go:297 +0xca
github.com/influxdata/flux/execute.(*consecutiveTransport).processMessages(0xc023bf3680, {0x7f93ce6e7258?, 0xc01e14c460?}, 0xa)
        /go/pkg/mod/github.com/influxdata/flux@v0.194.5/execute/transport.go:251 +0xe5
github.com/influxdata/flux/execute.(*poolDispatcher).doWork(0xc0027c0fc0, {0x7f93ce6e7258, 0xc01e14c460})
        /go/pkg/mod/github.com/influxdata/flux@v0.194.5/execute/dispatcher.go:157 +0x19f
github.com/influxdata/flux/execute.(*poolDispatcher).run(0xc0027c0fc0, {0x7f93ce6e7258, 0xc01e14c460})
        /go/pkg/mod/github.com/influxdata/flux@v0.194.5/execute/dispatcher.go:135 +0x4f
github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1()
        /go/pkg/mod/github.com/influxdata/flux@v0.194.5/execute/dispatcher.go:75 +0x86
created by github.com/influxdata/flux/execute.(*poolDispatcher).Start
        /go/pkg/mod/github.com/influxdata/flux@v0.194.5/execute/dispatcher.go:71 +0x48
```
