### ISSUE TITLE
runtime error: gobytes: length out of range

### ISSUE THREAD

**Issue by birkhoff-liu** [influxdata/influxdb#24170]
version : 2.0.9

During my use, there is a problem in the log。log content eg:
Mar 21 19:01:23 mqtt201 systemd: Started Session 523 of user root.

Mar 21 19:01:48 mqtt201 influxd-systemd-start.sh: ts=2023-03-21T11:01:47.046883Z lvl=info msg="panic during program start" log_id=0gUGa7c0000 service=storage-reads error="runtime error: gobytes: length out of range" stacktrace="goroutine 3628 [running]:\nruntime/debug.Stack()\n\t/home/circleci/.tools/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/influxdata/influxdb/v2/query/control.(*Controller).executeQuery.func1()\n\t/home/circleci/go/src/github.com/influxdata/influxdb/query/control/controller.go:457 +0x125\npanic({0x35c9e00, 0x38f9b88})\n\t/home/circleci/.tools/go/src/runtime/panic.go:1038 +0x215\ngithub.com/influxdata/flux/libflux/go/libflux._Cfunc_GoBytes(...)\n\t_cgo_gotypes.go:84\ngithub.com/influxdata/flux/libflux/go/libflux.(*SemanticPkg).MarshalFB.func4(0x35f1720)\n\t/home/circleci/go/pkg/mod/github.com/influxdata/[flux@v0.131.0](mailto:flux@v0.131.0)/libflux/go/libflux/analyze.go:35 +0x45\ngithub.com/influxdata/flux/libflux/go/libflux.(*SemanticPkg).MarshalFB(0xc055c9c808)\n\t/home/circleci/go/pkg/mod/github.com/influxdata/[flux@v0.131.0](mailto:flux@v0.131.0)/libflux/go/libflux/analyze.go:35 +0x1db\ngithub.com/influxdata/flux/runtime.AnalyzePackage({0x3948c90, 0xc06c53ed68})\n\t/home/circleci/go/pkg/mod/github.com/influxdata/[flux@v0.131.0](mailto:flux@v0.131.0)/runtime/analyze_libflux.go:24 +0xb4\ngithub.com/influxdata/flux/runtime.(*runtime).Eval(0x9b42900, {0x3971280, 0xc080999bc0}, {0x3948c90, 0xc06c53ed68}, {0x393fd98, 0x9b7b308}, {0xc05f951de0, 0x2, 0x2})\n\t/home/circleci/go/pkg/mod/github.com/influxdata/[flux@v0.131.0](mailto:flux@v0.131.0)/runtime/runtime.go:121 +0x5b\ngithub.com/influxdata/flux/lang.(*AstProgram).getSpec(0xc04057def0, {0x3971280, 0xc080999b90}, 0x38f65d8)\n\t/home/circleci/go/pkg/mod/github.com/influxdata/[flux@v0.131.0](mailto:flux@v0.131.0)/lang/compiler.go:447 +0x224\ngithub.com/influxdata/flux/lang.(*AstProgram).Start(0xc04057def0, {0x3971280, 0xc080999ad0}, 0xc07e711f6c)\n\t/home/circleci/go/pkg/mod/github.com/influxdata/[flux@v0.131.0](mailto:flux@v0.131.0)/lang/compiler.go:484 +0x191\ngithub.com/influxdata/influxdb/v2/query/control.(*Controller).executeQuery(0xc07e711f78, 0xc05f900180)\n\t/home/circleci/go/src/github.com/influxdata/influxdb/query/control/controller.go:480 +0x226\ngithub.com/influxdata/influxdb/v2/query/control.(*Controller).processQueryQueue(0xc02dfc6300)\n\t/home/circleci/go/src/github.com/influxdata/influxdb/query/control/controller.go:438 +0x2e\ngithub.com/influxdata/influxdb/v2/query/control.New.func1()\n\t/home/circleci/go/src/github.com/influxdata/influxdb/query/control/controller.go:220 +0x5d\ncreated by github.com/influxdata/influxdb/v2/query/control.New\n\t/home/circleci/go/src/github.com/influxdata/influxdb/query/control/controller.go:218 +0xa1b\n"

Mar 21 19:02:37 mqtt201 auditd[1301]: Audit daemon rotating log files.

And. Happens every hour

**Comment by jeffreyssmith2nd** [comment]
This is a very old version of flux (and influxdb), do you have the ability to test upgrading to 2.6.1 to see if the issue persists there?
