### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tomwimmenhove** [influxdata/influxdb#24282]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

The queries were genrated by an automated tool. After running the tool again and capturing the queries sent, this was the result (some field-names have been redacted):
```
from(bucket: "loggerBlockInfo")|> range(start: 2023-05-12T09:25:55.0930000Z, stop: 2023-05-16T05:07:04.6900000Z)|> filter(fn: (r) => r._measurement == "***")|> filter(fn: (r) => r._field == "***" or r._field == "***")|> unique(column: "_value")
from(bucket: "loggerBlockInfo")|> range(start: 2023-05-12T09:25:55.0930000Z, stop: 2023-05-16T05:07:04.6900000Z)|> filter(fn: (r) => r._measurement == "***")|> filter(fn: (r) => r._field == "***" or r._field == "***")|> unique(column: "_value")
from(bucket: "loggerBlockInfo")|> range(start: 2023-05-12T09:25:55.0930000Z, stop: 2023-05-16T05:07:04.6900000Z)|> filter(fn: (r) => r._measurement == "***")|> filter(fn: (r) => r._field == "***" or r._field == "***")|> unique(column: "_value")
```
The second query is repeated multiple times with difference start/stop times.

These are the the entries in our Nginx reverse-proxy logs:
```
10.20.30.65 - - [13/Jun/2023:08:38:46 +0000] "POST /influxdb/api/v2/query?org=***&precision=ms HTTP/1.1" 500 120 "-" "-"
10.20.30.65 - - [13/Jun/2023:08:38:48 +0000] "POST /influxdb/api/v2/query?org=***&precision=ms HTTP/1.1" 500 120 "-" "-"
10.20.30.65 - - [13/Jun/2023:08:38:49 +0000] "POST /influxdb/api/v2/query?org=***&precision=ms HTTP/1.1" 500 120 "-" "-"
10.20.30.65 - - [13/Jun/2023:08:38:50 +0000] "POST /influxdb/api/v2/query?org=***&precision=ms HTTP/1.1" 500 120 "-" "-"
```

__Expected behavior:__
Return queried data.

__Actual behavior:__
Return a 500 HTTP error code and log a null-reference error

__Environment info:__
```
$ uname -srm
Linux 5.4.0-146-generic x86_64
$ /usr/bin/influxd version
InfluxDB v2.5.1 (git: 5b6fdbf05d) build_date: 2022-11-02T18:06:28Z
$ free -m
              total        used        free      shared  buff/cache   available
Mem:          80447       21823       33448           0       25176       57782
Swap:         32767         725       32042
$ df -h /mnt/NFS/InfluxData
Filesystem                         Size  Used Avail Use% Mounted on
10.10.12.252:/volume1/InfluxData/   31T   19T   12T  62% /mnt/NFS/InfluxData
$ uptime
 09:30:08 up 69 days, 22:08,  7 users,  load average: 1.09, 1.49, 1.89
$ grep -m 1 model\ name /proc/cpuinfo 
model name      : Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz
```
Running in a VM with 80GB of RAM and using about 19TB of time-series data on disk.

__Config:__
Running with the following command-line:
```
/usr/bin/influxd --storage-cache-snapshot-write-cold-duration=5m --storage-max-concurrent-compactions=8 --storage-series-id-set-cache-size=50 --storage-tsm-use-madv-willneed --engine-path /mnt/NFS/InfluxData/engine
```

__Logs:__
```
Jun 13 08:38:46 influx01 InfluxDB2[6084]: ts=2023-06-13T08:38:46.841679Z lvl=info msg="Dispatcher panic" log_id=0g~0u830000 service=storage-reads component=dispatcher error="panic: runtime error: invalid memory address or nil pointer dereference" stacktrace="goroutine 1643424857 [running]:
runtime/debug.Stack()
	/go/src/runtime/debug/stack.go:24 +0x65
github.com/influxdata/flux/execute.(*poolDispatcher).recover(0xc310a35810)
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/execute/recover.go:53 +0x205
panic({0x7f6a70904920, 0x7f6a71e48810})
	/go/src/runtime/panic.go:838 +0x207
github.com/influxdata/influxdb/v2/tsdb/cursors.(*FloatArray).Len(...)
	/root/project/tsdb/cursors/arrayvalues.gen.go:30
github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*floatArrayAscendingCursor).reset(0xc310a49ea0, 0x175e5b2bf870af40, 0xc3129f6b40?, {0x0?, 0xc06650a9c0?, 0x2?}, 0xc309ce8b40)
	/root/project/tsdb/engine/tsm1/array_cursor.gen.go:51 +0xdb
github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*arrayCursorIterator).buildFloatArrayCursor(_, {_, _}, {_, _, _}, {_, _, _}, {0xc3b974eca8, ...}, ...)
	/root/project/tsdb/engine/tsm1/array_cursor_iterator.gen.go:26 +0x456
github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*arrayCursorIterator).Next(0xc310a35960, {0x7f6a70cbe3a0, 0xc3129f6b40}, 0xc31292d690)
	/root/project/tsdb/engine/tsm1/array_cursor_iterator.go:65 +0x336
github.com/influxdata/influxdb/v2/storage/reads.(*floatMultiShardArrayCursor).nextArrayCursor(0xc31292d740)
	/root/project/storage/reads/array_cursor.gen.go:320 +0x69
github.com/influxdata/influxdb/v2/storage/reads.(*floatMultiShardArrayCursor).Next(0xc31292d740)
	/root/project/storage/reads/array_cursor.gen.go:301 +0x46
github.com/influxdata/influxdb/v2/storage/flux.(*floatTable).advance(0xc3b56bb420)
	/root/project/storage/flux/table.gen.go:88 +0x34
github.com/influxdata/influxdb/v2/storage/flux.(*table).do(0xc150128998?, 0xc312a1c918, 0xc3a10b5988)
	/root/project/storage/flux/table.go:95 +0x213
github.com/influxdata/influxdb/v2/storage/flux.(*floatTable).Do(0x7f6a70bf3a20?, 0xc3708efe01?)
	/root/project/storage/flux/table.gen.go:84 +0x37
github.com/influxdata/flux/execute.(*consecutiveTransportTable).Do(0xc312a1c8d0, 0xc312a15a40)
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/execute/transport.go:554 +0x87
github.com/influxdata/flux/stdlib/universe.(*uniqueTransformation).Process(0xc312a03f80, {0xab, 0x49, 0xb3, 0x40, 0x64, 0x6d, 0x5f, 0x86, 0x9b, ...}, ...)
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/stdlib/universe/unique.go:150 +0x552
github.com/influxdata/flux/execute.(*transformationTransportAdapter).ProcessMessage(0xc3129f6a80, {0x7f6a70cbf0c0, 0xc312a2c320})
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/execute/transport.go:652 +0x195
github.com/influxdata/flux/execute.(*consecutiveTransport).processMessage(0xc30ed6af00, {0x7f6a70cbf0c0, 0xc312a2c320})
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/execute/transport.go:297 +0xca
github.com/influxdata/flux/execute.(*consecutiveTransport).processMessages(0xc30ed6af00, {0x7f6a70cbe2f8?, 0xc312a03c80?}, 0xa)
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/execute/transport.go:251 +0xe5
github.com/influxdata/flux/execute.(*poolDispatcher).doWork(0xc310a35810, {0x7f6a70cbe2f8, 0xc312a03c80})
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/execute/dispatcher.go:157 +0x19f
github.com/influxdata/flux/execute.(*poolDispatcher).run(0xc310a35810, {0x7f6a70cbe2f8, 0xc312a03c80})
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/execute/dispatcher.go:135 +0x4f
github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1()
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/execute/dispatcher.go:75 +0x86
created by github.com/influxdata/flux/execute.(*poolDispatcher).Start
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/execute/dispatcher.go:71 +0x48"

Jun 13 08:38:48 influx01 InfluxDB2[6084]: ts=2023-06-13T08:38:48.140404Z lvl=info msg="Dispatcher panic" log_id=0g~0u830000 service=storage-reads component=dispatcher error="panic: runtime error: invalid memory address or nil pointer dereference" stacktrace="goroutine 1643425013 [running]:
runtime/debug.Stack()
	/go/src/runtime/debug/stack.go:24 +0x65
github.com/influxdata/flux/execute.(*poolDispatcher).recover(0xc313ff4000)
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/execute/recover.go:53 +0x205
panic({0x7f6a70904920, 0x7f6a71e48810})
	/go/src/runtime/panic.go:838 +0x207
github.com/influxdata/influxdb/v2/tsdb/cursors.(*FloatArray).Len(...)
	/root/project/tsdb/cursors/arrayvalues.gen.go:30
github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*floatArrayAscendingCursor).reset(0xc312fdc820, 0x175e5b2bf870af40, 0xc3139de0f0?, {0x0?, 0xc35400d6e0?, 0x2?}, 0xc275b7f320)
	/root/project/tsdb/engine/tsm1/array_cursor.gen.go:51 +0xdb
github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*arrayCursorIterator).buildFloatArrayCursor(_, {_, _}, {_, _, _}, {_, _, _}, {0xc3b974eca8, ...}, ...)
	/root/project/tsdb/engine/tsm1/array_cursor_iterator.gen.go:26 +0x456
github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*arrayCursorIterator).Next(0xc312fd1500, {0x7f6a70cbe3a0, 0xc3139de0f0}, 0xc3008bb690)
	/root/project/tsdb/engine/tsm1/array_cursor_iterator.go:65 +0x336
github.com/influxdata/influxdb/v2/storage/reads.(*floatMultiShardArrayCursor).nextArrayCursor(0xc3008bb740)
	/root/project/storage/reads/array_cursor.gen.go:320 +0x69
github.com/influxdata/influxdb/v2/storage/reads.(*floatMultiShardArrayCursor).Next(0xc3008bb740)
	/root/project/storage/reads/array_cursor.gen.go:301 +0x46
github.com/influxdata/influxdb/v2/storage/flux.(*floatTable).advance(0xc69f065a40)
	/root/project/storage/flux/table.gen.go:88 +0x34
github.com/influxdata/influxdb/v2/storage/flux.(*table).do(0xc06de8d998?, 0xc3139ab488, 0xc06986b988)
	/root/project/storage/flux/table.go:95 +0x213
github.com/influxdata/influxdb/v2/storage/flux.(*floatTable).Do(0x7f6a70bf3a20?, 0xc36b19e501?)
	/root/project/storage/flux/table.gen.go:84 +0x37
github.com/influxdata/flux/execute.(*consecutiveTransportTable).Do(0xc3139ab440, 0xc3140135e0)
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/execute/transport.go:554 +0x87
github.com/influxdata/flux/stdlib/universe.(*uniqueTransformation).Process(0xc313ff3600, {0xab, 0x49, 0xb3, 0x40, 0x64, 0x6d, 0x5f, 0x86, 0x9b, ...}, ...)
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/stdlib/universe/unique.go:150 +0x552
github.com/influxdata/flux/execute.(*transformationTransportAdapter).ProcessMessage(0xc313f99950, {0x7f6a70cbf0c0, 0xc3139ff200})
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/execute/transport.go:652 +0x195
github.com/influxdata/flux/execute.(*consecutiveTransport).processMessage(0xc313e663c0, {0x7f6a70cbf0c0, 0xc3139ff200})
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/execute/transport.go:297 +0xca
github.com/influxdata/flux/execute.(*consecutiveTransport).processMessages(0xc313e663c0, {0x7f6a70cbe2f8?, 0xc313ff3300?}, 0xa)
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/execute/transport.go:251 +0xe5
github.com/influxdata/flux/execute.(*poolDispatcher).doWork(0xc313ff4000, {0x7f6a70cbe2f8, 0xc313ff3300})
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/execute/dispatcher.go:157 +0x19f
github.com/influxdata/flux/execute.(*poolDispatcher).run(0xc313ff4000, {0x7f6a70cbe2f8, 0xc313ff3300})
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/execute/dispatcher.go:135 +0x4f
github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1()
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/execute/dispatcher.go:75 +0x86
created by github.com/influxdata/flux/execute.(*poolDispatcher).Start
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/execute/dispatcher.go:71 +0x48"

Jun 13 08:38:49 influx01 InfluxDB2[6084]: ts=2023-06-13T08:38:49.296637Z lvl=info msg="Dispatcher panic" log_id=0g~0u830000 service=storage-reads component=dispatcher error="panic: runtime error: invalid memory address or nil pointer dereference" stacktrace="goroutine 1643425029 [running]:
runtime/debug.Stack()
	/go/src/runtime/debug/stack.go:24 +0x65
github.com/influxdata/flux/execute.(*poolDispatcher).recover(0xc314a88b60)
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/execute/recover.go:53 +0x205
panic({0x7f6a70904920, 0x7f6a71e48810})
	/go/src/runtime/panic.go:838 +0x207
github.com/influxdata/influxdb/v2/tsdb/cursors.(*FloatArray).Len(...)
	/root/project/tsdb/cursors/arrayvalues.gen.go:30
github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*floatArrayAscendingCursor).reset(0xc314abb950, 0x175e5b2bf870af40, 0xc314c39f50?, {0x0?, 0xc128efa540?, 0x2?}, 0xc1b9fb58c0)
	/root/project/tsdb/engine/tsm1/array_cursor.gen.go:51 +0xdb
github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*arrayCursorIterator).buildFloatArrayCursor(_, {_, _}, {_, _, _}, {_, _, _}, {0xc3b974eca8, ...}, ...)
	/root/project/tsdb/engine/tsm1/array_cursor_iterator.gen.go:26 +0x456
github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*arrayCursorIterator).Next(0xc314a88cb0, {0x7f6a70cbe3a0, 0xc314c39f50}, 0xc314ae7690)
	/root/project/tsdb/engine/tsm1/array_cursor_iterator.go:65 +0x336
github.com/influxdata/influxdb/v2/storage/reads.(*floatMultiShardArrayCursor).nextArrayCursor(0xc314ae7740)
	/root/project/storage/reads/array_cursor.gen.go:320 +0x69
github.com/influxdata/influxdb/v2/storage/reads.(*floatMultiShardArrayCursor).Next(0xc314ae7740)
	/root/project/storage/reads/array_cursor.gen.go:301 +0x46
github.com/influxdata/influxdb/v2/storage/flux.(*floatTable).advance(0xc36d8b9500)
	/root/project/storage/flux/table.gen.go:88 +0x34
github.com/influxdata/influxdb/v2/storage/flux.(*table).do(0xc3af5e0998?, 0xc314ca49d8, 0xc06986d988)
	/root/project/storage/flux/table.go:95 +0x213
github.com/influxdata/influxdb/v2/storage/flux.(*floatTable).Do(0x7f6a70bf3a20?, 0xc3845b0801?)
	/root/project/storage/flux/table.gen.go:84 +0x37
github.com/influxdata/flux/execute.(*consecutiveTransportTable).Do(0xc314ca4990, 0xc314caed90)
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/execute/transport.go:554 +0x87
github.com/influxdata/flux/stdlib/universe.(*uniqueTransformation).Process(0xc314c87a80, {0xab, 0x49, 0xb3, 0x40, 0x64, 0x6d, 0x5f, 0x86, 0x9b, ...}, ...)
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/stdlib/universe/unique.go:150 +0x552
github.com/influxdata/flux/execute.(*transformationTransportAdapter).ProcessMessage(0xc314c39e90, {0x7f6a70cbf0c0, 0xc314c7fca0})
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/execute/transport.go:652 +0x195
github.com/influxdata/flux/execute.(*consecutiveTransport).processMessage(0xc314af83c0, {0x7f6a70cbf0c0, 0xc314c7fca0})
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/execute/transport.go:297 +0xca
github.com/influxdata/flux/execute.(*consecutiveTransport).processMessages(0xc314af83c0, {0x7f6a70cbe2f8?, 0xc314c87780?}, 0xa)
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/execute/transport.go:251 +0xe5
github.com/influxdata/flux/execute.(*poolDispatcher).doWork(0xc314a88b60, {0x7f6a70cbe2f8, 0xc314c87780})
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/execute/dispatcher.go:157 +0x19f
github.com/influxdata/flux/execute.(*poolDispatcher).run(0xc314a88b60, {0x7f6a70cbe2f8, 0xc314c87780})
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/execute/dispatcher.go:135 +0x4f
github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1()
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/execute/dispatcher.go:75 +0x86
created by github.com/influxdata/flux/execute.(*poolDispatcher).Start
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/execute/dispatcher.go:71 +0x48"

Jun 13 08:38:50 influx01 InfluxDB2[6084]: ts=2023-06-13T08:38:50.445257Z lvl=info msg="Dispatcher panic" log_id=0g~0u830000 service=storage-reads component=dispatcher error="panic: runtime error: invalid memory address or nil pointer dereference" stacktrace="goroutine 1643424988 [running]:
runtime/debug.Stack()
	/go/src/runtime/debug/stack.go:24 +0x65
github.com/influxdata/flux/execute.(*poolDispatcher).recover(0xc31c3b0770)
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/execute/recover.go:53 +0x205
panic({0x7f6a70904920, 0x7f6a71e48810})
	/go/src/runtime/panic.go:838 +0x207
github.com/influxdata/influxdb/v2/tsdb/cursors.(*FloatArray).Len(...)
	/root/project/tsdb/cursors/arrayvalues.gen.go:30
github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*floatArrayAscendingCursor).reset(0xc31c3b3a90, 0x175e5b2bf870af40, 0xc32131a840?, {0x0?, 0xc4b87bc240?, 0x2?}, 0xc6c6b71050)
	/root/project/tsdb/engine/tsm1/array_cursor.gen.go:51 +0xdb
github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*arrayCursorIterator).buildFloatArrayCursor(_, {_, _}, {_, _, _}, {_, _, _}, {0xc3b974eca8, ...}, ...)
	/root/project/tsdb/engine/tsm1/array_cursor_iterator.gen.go:26 +0x456
github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*arrayCursorIterator).Next(0xc31c3b08c0, {0x7f6a70cbe3a0, 0xc32131a840}, 0xc321330010)
	/root/project/tsdb/engine/tsm1/array_cursor_iterator.go:65 +0x336
github.com/influxdata/influxdb/v2/storage/reads.(*floatMultiShardArrayCursor).nextArrayCursor(0xc3213300c0)
	/root/project/storage/reads/array_cursor.gen.go:320 +0x69
github.com/influxdata/influxdb/v2/storage/reads.(*floatMultiShardArrayCursor).Next(0xc3213300c0)
	/root/project/storage/reads/array_cursor.gen.go:301 +0x46
github.com/influxdata/influxdb/v2/storage/flux.(*floatTable).advance(0xc03f1aba40)
	/root/project/storage/flux/table.gen.go:88 +0x34
github.com/influxdata/influxdb/v2/storage/flux.(*table).do(0xc07394e998?, 0xc3213134b8, 0xc3a0dc1988)
	/root/project/storage/flux/table.go:95 +0x213
github.com/influxdata/influxdb/v2/storage/flux.(*floatTable).Do(0x7f6a70bf3a20?, 0xc076e13a01?)
	/root/project/storage/flux/table.gen.go:84 +0x37
github.com/influxdata/flux/execute.(*consecutiveTransportTable).Do(0xc321313470, 0xc3213449a0)
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/execute/transport.go:554 +0x87
github.com/influxdata/flux/stdlib/universe.(*uniqueTransformation).Process(0xc32131c600, {0xab, 0x49, 0xb3, 0x40, 0x64, 0x6d, 0x5f, 0x86, 0x9b, ...}, ...)
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/stdlib/universe/unique.go:150 +0x552
github.com/influxdata/flux/execute.(*transformationTransportAdapter).ProcessMessage(0xc32131a780, {0x7f6a70cbf0c0, 0xc321317960})
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/execute/transport.go:652 +0x195
github.com/influxdata/flux/execute.(*consecutiveTransport).processMessage(0xc30ed6b3b0, {0x7f6a70cbf0c0, 0xc321317960})
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/execute/transport.go:297 +0xca
github.com/influxdata/flux/execute.(*consecutiveTransport).processMessages(0xc30ed6b3b0, {0x7f6a70cbe2f8?, 0xc32131c300?}, 0xa)
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/execute/transport.go:251 +0xe5
github.com/influxdata/flux/execute.(*poolDispatcher).doWork(0xc31c3b0770, {0x7f6a70cbe2f8, 0xc32131c300})
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/execute/dispatcher.go:157 +0x19f
github.com/influxdata/flux/execute.(*poolDispatcher).run(0xc31c3b0770, {0x7f6a70cbe2f8, 0xc32131c300})
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/execute/dispatcher.go:135 +0x4f
github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1()
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/execute/dispatcher.go:75 +0x86
created by github.com/influxdata/flux/execute.(*poolDispatcher).Start
	/go/pkg/mod/github.com/influxdata/flux@v0.188.1/execute/dispatcher.go:71 +0x48"
```

**Comment by davidby-influx** [comment]
Fixed here: https://github.com/influxdata/influxdb/pull/24787

in version 2.7.6 and later
