### ISSUE TITLE
influxdb crash when iterating through series in V1

### ISSUE THREAD

**Issue by z3bra** [influxdata/influxdb#24454]
__Steps to reproduce:__

InfluxDB 2.7.1 and Telegraf 1.27.4  running on OpenBSD 7.4

1. configure a new bucket
2. setup "v1 auth" with read-only access to bucket
3. start telegraf with syslog plugin (see conf below)

__Expected behaviour:__
influxdb should drop metrics, or give the expected result (eg. message count)

__Actual behaviour:__
influxdb crash without returning any result :

```
bitterman$ influx v1 shell
InfluxQL Shell 2.7.3
Connected to InfluxDB OSS 2.7.1
> use telegraf
> delete from syslog
ERR: Get "http://localhost:8086/query?db=telegraf&epoch=ns&q=delete+from+syslog&rp=autogen": dial tcp [::1]:8086: connect: connection refused
```

*Note: error happens with `select count(message) from syslog` as well (or apparently anything that iterates over the records).

__Environment info:__

* System info: OpenBSD 7.4 amd64
* Nothing specific about the disk (no network mount or whatever)

__Config:__

InfluxDB running with default settings, except the bind address which is on a wireguard interface:
```
[http]
  # address set on a "wireguard" (VPN) interface
  # which was working fine on influxdb v1.x
  bind-address = "172.17.18.19:8086"
```

Telegraf config:
```
[[inputs.syslog]]
   server = "udp://172.17.18.19:6514"
   syslog_standard = "RFC3164"

[[outputs.influxdb_v2]]
  urls = ["http://172.17.18.19:8086"]
  bucket = "telegraf"
  organization = "test.org"
  token = "$MY_TOKEN" # actually hardcoded and not taken from environment
```

__Logs:__

```
Nov  9 22:28:21 bitterman influxdb[31152]: ts=2023-11-09T21:28:21.211089Z lvl=info msg="Executing query" log_id=0lPUzAs0000 service=query query="DELETE FROM syslog"
Nov  9 22:28:21 bitterman influxdb[31152]: panic: runtime error: index out of range [1] with length 0
Nov  9 22:28:21 bitterman influxdb[31152]:
Nov  9 22:28:21 bitterman influxdb[31152]: goroutine 1578 [running]:
Nov  9 22:28:21 bitterman influxdb[31152]: encoding/binary.bigEndian.Uint16(...)
Nov  9 22:28:21 bitterman influxdb[31152]:      encoding/binary/binary.go:139
Nov  9 22:28:21 bitterman influxdb[31152]: github.com/influxdata/influxdb/v2/tsdb.ReadSeriesKeyMeasurement(...)
Nov  9 22:28:21 bitterman influxdb[31152]:      github.com/influxdata/influxdb/v2/tsdb/series_file.go:380
Nov  9 22:28:21 bitterman influxdb[31152]: github.com/influxdata/influxdb/v2/tsdb.parseSeriesKey({0x2302df00e?, 0x3c000?, 0x3a980?}, {0x0, 0x10000000007?, 0x0})
Nov  9 22:28:21 bitterman influxdb[31152]:      github.com/influxdata/influxdb/v2/tsdb/series_file.go:417 +0x365
Nov  9 22:28:21 bitterman influxdb[31152]: github.com/influxdata/influxdb/v2/tsdb.ParseSeriesKey(...)
Nov  9 22:28:21 bitterman influxdb[31152]:      github.com/influxdata/influxdb/v2/tsdb/series_file.go:400
Nov  9 22:28:21 bitterman influxdb[31152]: github.com/influxdata/influxdb/v2/tsdb.(*seriesIteratorAdapter).Next(0xc001f56be8)
Nov  9 22:28:21 bitterman influxdb[31152]:      github.com/influxdata/influxdb/v2/tsdb/index.go:128 +0x89
Nov  9 22:28:21 bitterman influxdb[31152]: github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*Engine).DeleteSeriesRangeWithPredicate(0xc000166140, {0xd1ca70, 0xc001f78960}, {0xd0b818, 0xc001f56be8}, 0xc001c3cc90)
Nov  9 22:28:21 bitterman influxdb[31152]:      github.com/influxdata/influxdb/v2/tsdb/engine/tsm1/engine.go:1409 +0x190
Nov  9 22:28:21 bitterman influxdb[31152]: github.com/influxdata/influxdb/v2/tsdb/engine/tsm1.(*Engine).DeleteSeriesRange(0x18?, {0xd1ca70?, 0xc001f78960?}, {0xd0b818?, 0xc001f56be8?}, 0x2684905?, 0x18?)
Nov  9 22:28:21 bitterman influxdb[31152]:      github.com/influxdata/influxdb/v2/tsdb/engine/tsm1/engine.go:1361 +0x51
Nov  9 22:28:21 bitterman influxdb[31152]: github.com/influxdata/influxdb/v2/tsdb.(*Shard).DeleteSeriesRange(0xc001f56bd0?, {0xd1ca70, 0xc001f78960}, {0xd0b818, 0xc001f56be8}, 0x1?, 0xc001a97090?)
Nov  9 22:28:21 bitterman influxdb[31152]:      github.com/influxdata/influxdb/v2/tsdb/shard.go:898 +0x69
Nov  9 22:28:21 bitterman influxdb[31152]: github.com/influxdata/influxdb/v2/tsdb.(*Store).DeleteSeries.func1(0xc000f42900)
Nov  9 22:28:21 bitterman influxdb[31152]:      github.com/influxdata/influxdb/v2/tsdb/store.go:1538 +0x66e
Nov  9 22:28:21 bitterman influxdb[31152]: github.com/influxdata/influxdb/v2/tsdb.(*Store).walkShards.func1(0xc000f42900)
Nov  9 22:28:21 bitterman influxdb[31152]:      github.com/influxdata/influxdb/v2/tsdb/store.go:1042 +0x2f
Nov  9 22:28:21 bitterman influxdb[31152]: created by github.com/influxdata/influxdb/v2/tsdb.(*Store).walkShards in goroutine 1577
Nov  9 22:28:21 bitterman influxdb[31152]:      github.com/influxdata/influxdb/v2/tsdb/store.go:1041 +0x48
```

**Comment by z3bra** [comment]
Update on this issue, as the query seems to fail even in V2 (using Flux rather than InfluxQL):

```
bitterman$ influx query 'from(bucket: "telegraf") |> range(start: -12h) |> filter(fn: (r) => r._measurement == "syslog")'
Error: failed to execute query: 500 Internal Server Error: panic: runtime error: index out of range [1] with length 0
```

InfluxDB logs:

```
Nov 10 12:05:43 bitterman influxdb[69487]: ts=2023-11-10T11:05:43.464748Z lvl=info msg="Execute source panic" log_id=0lQDuN6G000 service=storage-reads error="panic: runtime error: index out of range [1] with length 0" stacktrace="goroutine 3558 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x5e\ngithub.com/influxdata/flux/execute.(*executionState).recover(0xc001fcd050)\n\tgithub.com/influxdata/flux@v0.193.0/execute/recover.go:32 +0x1f3\npanic({0x6be8c0?, 0xc002d53b18?})\n\truntime/panic.go:914 +0x21f\nencoding/binary.bigEndian.Uint16(...)\n\tencoding/binary/binary.go:139\ngithub.com/influxdata/influxdb/v2/tsdb.ReadSeriesKeyMeasurement(...)\n\tgithub.com/influxdata/influxdb/v2/tsdb/series_file.go:380\ngithub.com/influxdata/influxdb/v2/tsdb.CompareSeriesKeys({0x2cfacd544?, 0x7?, 0xc00143f678?}, {0x2cfacd440, 0x79, 0x3ffbc0})\n\tgithub.com/influxdata/influxdb/v2/tsdb/series_file.go:452 +0x688\ngithub.com/influxdata/influxdb/v2/tsdb.seriesKeys.Less(...)\n\tgithub.com/influxdata/influxdb/v2/tsdb/series_file.go:529\nsort.partition({0xd176
Nov 10 12:05:43 bitterman influxdb[69487]: 68, 0xc004184df8}, 0x0, 0x4d, 0x33717b5?)\n\tsort/zsortinterface.go:154 +0x176\nsort.pdqsort({0xd17668, 0xc004184df8}, 0x18?, 0x3884a0?, 0x1?)\n\tsort/zsortinterface.go:114 +0x22b\nsort.Sort({0xd17668, 0xc004184df8})\n\tsort/sort.go:51 +0x54\ngithub.com/influxdata/influxdb/v2/tsdb.(*seriesCursor).readSeriesKeys(0xc0041555c0, {0xc004145fd8?, 0x5?, 0x5?})\n\tgithub.com/influxdata/influxdb/v2/tsdb/series_cursor.go:153 +0x2db\ngithub.com/influxdata/influxdb/v2/tsdb.(*seriesCursor).Next(0xc0041555c0)\n\tgithub.com/influxdata/influxdb/v2/tsdb/series_cursor.go:108 +0x5d\ngithub.com/influxdata/influxdb/v2/v1/services/storage.(*indexSeriesCursor).Next(0xc00415a500)\n\tgithub.com/influxdata/influxdb/v2/v1/services/storage/series_cursor.go:151 +0x162\ngithub.com/influxdata/influxdb/v2/storage/reads.(*resultSet).Next(0xc002dcc340)\n\tgithub.com/influxdata/influxdb/v2/storage/reads/resultset.go:50 +0x31\ngithub.com/influxdata/influxdb/v2/storage/flux.(*filterIterator).handleRead(0xc0009ff420, 0xc00151c8e0, {0xd28a60, 0xc
Nov 10 12:05:43 bitterman influxdb[69487]: 002dcc340})\n\tgithub.com/influxdata/influxdb/v2/storage/flux/reader.go:196 +0xff\ngithub.com/influxdata/influxdb/v2/storage/flux.(*filterIterator).Do(0xc0009ff420, 0xc00005e1b8?)\n\tgithub.com/influxdata/influxdb/v2/storage/flux/reader.go:174 +0x125\ngithub.com/influxdata/influxdb/v2/query/stdlib/influxdata/influxdb.(*Source).processTables(0xc004155500, {0xd1ca70?, 0xc0041740c0}, {0xd0e8d8, 0xc0009ff420}, 0x58e0af5a22dcebb9?)\n\tgithub.com/influxdata/influxdb/v2/query/stdlib/influxdata/influxdb/source.go:69 +0xb6\ngithub.com/influxdata/influxdb/v2/query/stdlib/influxdata/influxdb.(*readFilterSource).run(0xc004155500, {0xd1ca70, 0xc0041740c0})\n\tgithub.com/influxdata/influxdb/v2/query/stdlib/influxdata/influxdb/source.go:146 +0xdc\ngithub.com/influxdata/influxdb/v2/query/stdlib/influxdata/influxdb.(*Source).Run(0xc004155500, {0xd1ca70, 0xc0041740c0})\n\tgithub.com/influxdata/influxdb/v2/query/stdlib/influxdata/influxdb/source.go:50 +0xa3\ngithub.com/influxdata/flux/execute.(*executionState).do.func2({0xd1e5
Nov 10 12:05:43 bitterman influxdb[69487]: 90?, 0xc004155500})\n\tgithub.com/influxdata/flux@v0.193.0/execute/executor.go:535 +0x3c5\ncreated by github.com/influxdata/flux/execute.(*executionState).do in goroutine 284\n\tgithub.com/influxdata/flux@v0.193.0/execute/executor.go:515 +0xf0\n"
```
However, the influxd daemon doesn't crash as the error is "caught".
