### ISSUE TITLE
InfluxDB Restarting Automatically Randomly

### ISSUE THREAD

**Issue by Satish2007** [influxdata/influxdb#24860]
Hi All,

I am observing strange issue for my InfluxDB 1.8.10.

**Issue: InfluxDB Restarting Automatically Randomly.**

Error in Logfile:
Mar 28 06:52:02 influx influxd-systemd-start.sh[14374]: unexpected fault address 0x7b35af7b5000
Mar 28 06:52:02 influx influxd-systemd-start.sh[14374]: fatal error: fault
Mar 28 06:52:02 influx influxd-systemd-start.sh[14374]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x7b35af7b5000 pc=0x12a1fd0]
Mar 28 06:52:02 influx influxd-systemd-start.sh[14374]: goroutine 11953909117 [running]:
Mar 28 06:52:02 influx influxd-systemd-start.sh[14374]: runtime.throw(0x169e54a, 0x5)
Mar 28 06:52:02 influx influxd-systemd-start.sh[14374]: #011/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc2e2d8cc18 sp=0xc2e2d8cbe8 pc=0x431272
Mar 28 06:52:02 influx influxd-systemd-start.sh[14374]: runtime.sigpanic()
…
…
…
Mar 28 06:52:09 influx influxd-systemd-start.sh[14374]: #011/usr/local/go/src/net/http/server.go:2928 +0x384
Mar 28 06:52:10 influx systemd[1]: influxdbsud.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 28 06:52:10 influx systemd[1]: influxdbsud.service: Failed with result ‘exit-code’.
Mar 28 06:52:10 influx systemd[1]: influxdbsud.service: Consumed 1month 6d 13h 29min 42.403s CPU time.
Mar 28 06:52:10 influx systemd[1]: influxdbsud.service: Scheduled restart job, restart counter is at 1.
Mar 28 06:52:10 influx systemd[1]: Stopped InfluxDB is an open-source, distributed, time series database.
Mar 28 06:52:10 influx systemd[1]: influxdbsud.service: Consumed 1month 6d 13h 29min 42.403s CPU time.
Mar 28 06:52:10 influx systemd[1]: Starting InfluxDB is an open-source, distributed, time series database…
Mar 28 06:52:10 influx influxd-systemd-start.sh[116443]:
Mar 28 06:52:10 influx influxd-systemd-start.sh[116440]: InfluxDB started
Mar 28 06:52:10 influx systemd[1]: Started InfluxDB is an open-source, distributed, time series database.
Mar 28 06:52:10 influx influxd-systemd-start.sh[116441]: ts=2024-03-28T06:52:10.842072Z lvl=info msg=“InfluxDB starting” log_id=0oCy7trW000 version=1.8.10 branch=1.8 commit=688e697c51fd

System Environment:
Operating System: Ubuntu 22.04 on Azure
InfluxDB Version: 1.8.10
CPU: 32vCPU
RAM: 128GB
Database Size: 80GB
Disk Type: SSD
cache-max-memory: 32GB
Index Type: TSM

Any help/suggestions are appreciated in advance.

With Regards

**Comment by davidby-influx** [comment]
Please include the stack trace that follows after `runtime.panic` as that may contain more clues.
