### ISSUE TITLE
influx v1 auth create: Sudden panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by Sieboldianus** [influxdata/influxdb#24916]
1. InfluxDb installed via apt, `2.7.5-1`
2. I had a v1 auth setup for the last years that worked without flaws. As of today, it stopped working.
- I check tokens, password etc. - all is unchanged.

- However, when I try to list the auth, it does not exist anymore:
```
```
influx v1 auth list --org-id 5b33216874a4da00 \
    --token "............................................................=="
> ID      Description     Name / Token    User Name       User ID Permissions
>   
```
4. I tried to recreate the v1 auth with the same command I used 3 years ago, but this ends in the following error:

```bash
influx v1 auth create --username solaranzeige --org-id 5b33216874a4da00 \
    --token "............................................................==" \
    --read-bucket "cdfb968ed350d8a4" \
    --write-bucket "cdfb968ed350d8a4" \
    --password "................................"
    
> panic: runtime error: index out of range [0] with length 0
> 
> goroutine 1 [running]:
> main.v1FindOneAuthorization(0xc00035f9f8, 0x2523da0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x203000, 0x203000, 0x203000)
>         /home/circleci/go/src/github.com/influxdata/influxdb/cmd/influx/v1_authorization.go:547 +0x1e5
> main.makeV1AuthorizationCreateE.func1(0xc00047e000, 0xc00014a480, 0x0, 0xc, 0xc000477f40, 0xc0000fba70)
>         /home/circleci/go/src/github.com/influxdata/influxdb/cmd/influx/v1_authorization.go:116 +0x1ba
> main.checkSetupRunEMiddleware.func1.1(0xc00047e000, 0xc00014a480, 0x0, 0xc, 0x0, 0x0)
>         /home/circleci/go/src/github.com/influxdata/influxdb/cmd/influx/main.go:467 +0x74
> github.com/spf13/cobra.(*Command).execute(0xc00047e000, 0xc00014a3c0, 0xc, 0xc, 0xc00047e000, 0xc00014a3c0)
>         /home/circleci/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
> github.com/spf13/cobra.(*Command).ExecuteC(0xc000379600, 0x0, 0x0, 0xc000379600)
>         /home/circleci/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
> github.com/spf13/cobra.(*Command).Execute(...)
>         /home/circleci/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
> main.main()
>         /home/circleci/go/src/github.com/influxdata/influxdb/cmd/influx/main.go:43 +0x58
```

__Expected behaviour:__

v1 auth is created successfully using the cli

__Actual behaviour:__

v1 auth is not created successfully using the cli. See the above error.

__Environment info:__

* - InfluxDB installed via apt
* System info: > Linux 6.5.13-1-pve x86_64, Debian 11
* unprivileged LXC on Proxmox (this worked for the last 4 years)

**Comment by Sieboldianus** [comment]
Can be closed: It was my fault - the error simply indicates tat there is no username `solaranzeige ` (`> index out of range [0] with length 0`)
