### ISSUE TITLE
Program crashes when handling long flux query

### ISSUE THREAD

**Issue by koho** [influxdata/influxdb#25015]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behaviour.

1. Submit the following flux query:

```
from(bucket: "energy")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "electricity")
  |> filter(fn: (r) => r["_field"] == "usage")
  |> aggregateWindow(every: 1h, fn: last, createEmpty: false, timeSrc: "_start")
  |> difference()
  |> map(fn: (r) => ({r with
      _value: if (r._time > 2024-04-12T03:00:00Z and r._time <= 2024-04-12T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-12T12:00:00Z and r._time <= 2024-04-12T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-13T03:00:00Z and r._time <= 2024-04-13T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-13T12:00:00Z and r._time <= 2024-04-13T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-14T03:00:00Z and r._time <= 2024-04-14T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-14T12:00:00Z and r._time <= 2024-04-14T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-15T03:00:00Z and r._time <= 2024-04-15T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-15T12:00:00Z and r._time <= 2024-04-15T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-16T03:00:00Z and r._time <= 2024-04-16T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-16T12:00:00Z and r._time <= 2024-04-16T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-17T03:00:00Z and r._time <= 2024-04-17T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-17T12:00:00Z and r._time <= 2024-04-17T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-18T03:00:00Z and r._time <= 2024-04-18T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-18T12:00:00Z and r._time <= 2024-04-18T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-19T03:00:00Z and r._time <= 2024-04-19T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-19T12:00:00Z and r._time <= 2024-04-19T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-20T03:00:00Z and r._time <= 2024-04-20T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-20T12:00:00Z and r._time <= 2024-04-20T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-21T03:00:00Z and r._time <= 2024-04-21T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-21T12:00:00Z and r._time <= 2024-04-21T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-22T03:00:00Z and r._time <= 2024-04-22T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-22T12:00:00Z and r._time <= 2024-04-22T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-23T03:00:00Z and r._time <= 2024-04-23T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-23T12:00:00Z and r._time <= 2024-04-23T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-24T03:00:00Z and r._time <= 2024-04-24T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-24T12:00:00Z and r._time <= 2024-04-24T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-25T03:00:00Z and r._time <= 2024-04-25T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-25T12:00:00Z and r._time <= 2024-04-25T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-26T03:00:00Z and r._time <= 2024-04-26T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-26T12:00:00Z and r._time <= 2024-04-26T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-27T03:00:00Z and r._time <= 2024-04-27T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-27T12:00:00Z and r._time <= 2024-04-27T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-28T03:00:00Z and r._time <= 2024-04-28T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-28T12:00:00Z and r._time <= 2024-04-28T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-29T03:00:00Z and r._time <= 2024-04-29T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-29T12:00:00Z and r._time <= 2024-04-29T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-30T03:00:00Z and r._time <= 2024-04-30T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-04-30T12:00:00Z and r._time <= 2024-04-30T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-01T03:00:00Z and r._time <= 2024-05-01T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-01T12:00:00Z and r._time <= 2024-05-01T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-02T03:00:00Z and r._time <= 2024-05-02T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-02T12:00:00Z and r._time <= 2024-05-02T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-03T03:00:00Z and r._time <= 2024-05-03T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-03T12:00:00Z and r._time <= 2024-05-03T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-04T03:00:00Z and r._time <= 2024-05-04T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-04T12:00:00Z and r._time <= 2024-05-04T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-05T03:00:00Z and r._time <= 2024-05-05T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-05T12:00:00Z and r._time <= 2024-05-05T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-06T03:00:00Z and r._time <= 2024-05-06T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-06T12:00:00Z and r._time <= 2024-05-06T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-07T03:00:00Z and r._time <= 2024-05-07T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-07T12:00:00Z and r._time <= 2024-05-07T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-08T03:00:00Z and r._time <= 2024-05-08T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-08T12:00:00Z and r._time <= 2024-05-08T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-09T03:00:00Z and r._time <= 2024-05-09T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-09T12:00:00Z and r._time <= 2024-05-09T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-10T03:00:00Z and r._time <= 2024-05-10T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-10T12:00:00Z and r._time <= 2024-05-10T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-11T03:00:00Z and r._time <= 2024-05-11T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-11T12:00:00Z and r._time <= 2024-05-11T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-12T03:00:00Z and r._time <= 2024-05-12T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-12T12:00:00Z and r._time <= 2024-05-12T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-13T03:00:00Z and r._time <= 2024-05-13T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-13T12:00:00Z and r._time <= 2024-05-13T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-14T03:00:00Z and r._time <= 2024-05-14T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-14T12:00:00Z and r._time <= 2024-05-14T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-15T03:00:00Z and r._time <= 2024-05-15T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-15T12:00:00Z and r._time <= 2024-05-15T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-16T03:00:00Z and r._time <= 2024-05-16T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-16T12:00:00Z and r._time <= 2024-05-16T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-17T03:00:00Z and r._time <= 2024-05-17T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-17T12:00:00Z and r._time <= 2024-05-17T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-18T03:00:00Z and r._time <= 2024-05-18T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-18T12:00:00Z and r._time <= 2024-05-18T14:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-19T03:00:00Z and r._time <= 2024-05-19T09:00:00Z) then
        r._value *0.84
      else if (r._time > 2024-05-19T12:00:00Z and r._time <= 2024-05-19T14:00:00Z) then
        r._value *0.84
      else
        r._value * 0.3
    }))
  |> aggregateWindow(every: 1mo, fn: sum, createEmpty: false, timeSrc: "_start")
```

__Expected behaviour:__
The query should execute successfully.

__Actual behaviour:__
Program crashes.

__Environment info:__

* Release version: 2.7.6
* System info: Linux 5.15.0-107-generic x86_64

__Config:__
Use default config.

__Logs:__
```
influxdb-2  | thread '<unnamed>' panicked at 'called consume on an unbuffered input', flux-core/src/parser/mod.rs:107:21
influxdb-2  | stack backtrace:
influxdb-2  | SIGABRT: abort
influxdb-2  | PC=0x7fe82fc85792 m=31 sigcode=18446744073709551610
influxdb-2  | signal arrived during cgo execution
influxdb-2  | 
influxdb-2  | goroutine 9744 [syscall]:
influxdb-2  | runtime.cgocall(0x7fe82f9466d0, 0xc0025ae180)
influxdb-2  | 	/go/src/runtime/cgocall.go:157 +0x4b fp=0xc0025ae158 sp=0xc0025ae120 pc=0x7fe82dba3b8b
influxdb-2  | github.com/influxdata/flux/libflux/go/libflux._Cfunc_flux_parse(0x7fe7e0195490, 0x7fe7bb1cc060)
influxdb-2  | 	_cgo_gotypes.go:341 +0x50 fp=0xc0025ae180 sp=0xc0025ae158 pc=0x7fe82e14fa10
influxdb-2  | github.com/influxdata/flux/libflux/go/libflux.Parse({0x0, 0x0}, {0xc00e0e9400?, 0x2381?})
influxdb-2  | 	/go/pkg/mod/github.com/influxdata/flux@v0.194.5/libflux/go/libflux/parser.go:117 +0xc5 fp=0xc0025ae208 sp=0xc0025ae180 pc=0x7fe82e152385
influxdb-2  | github.com/influxdata/flux/libflux/go/libflux.ParseString(...)
influxdb-2  | 	/go/pkg/mod/github.com/influxdata/flux@v0.194.5/libflux/go/libflux/parser.go:106
influxdb-2  | github.com/influxdata/flux/parser.ParseToHandle({0x7fe830ff39e8, 0xc012713ce0}, {0xc00e0e6f00?, 0xc001963200?, 0x0?})
influxdb-2  | 	/go/pkg/mod/github.com/influxdata/flux@v0.194.5/parser/parser.go:117 +0x45 fp=0xc0025ae260 sp=0xc0025ae208 pc=0x7fe82e15aec5
influxdb-2  | github.com/influxdata/flux/runtime.Parse(...)
influxdb-2  | 	/go/pkg/mod/github.com/influxdata/flux@v0.194.5/runtime/parse.go:13
influxdb-2  | github.com/influxdata/flux/runtime.(*runtime).Parse(0x0?, {0x7fe830ff39e8, 0xc012713ce0}, {0xc00e0e4a00?, 0xc0025ae318?})
influxdb-2  | 	/go/pkg/mod/github.com/influxdata/flux@v0.194.5/runtime/runtime.go:28 +0x45 fp=0xc0025ae2b8 sp=0xc0025ae260 pc=0x7fe82e15c8e5
influxdb-2  | github.com/influxdata/flux/lang.Compile({0x7fe830ff39e8?, 0xc012713ce0?}, {0xc00e0e4a00?, 0x2381}, {0x7fe830fffb28, 0x7fe83394b8a0}, {0x49a85aa01?, 0x7fe833950500?, 0x7fe833950500?}, {0xc0025ae3b8, ...})
influxdb-2  | 	/go/pkg/mod/github.com/influxdata/flux@v0.194.5/lang/compiler.go:97 +0x7c fp=0xc0025ae328 sp=0xc0025ae2b8 pc=0x7fe82ea994dc
influxdb-2  | github.com/influxdata/flux/lang.FluxCompiler.Compile({{0xc18ae2accf1e6255, 0x49a84c676, 0x7fe833950500}, {0xc009b92380, 0xd5, 0xe0}, {0xc00e0e4a00, 0x2381}}, {0x7fe830ff39e8, 0xc012713ce0}, ...)
influxdb-2  | 	/go/pkg/mod/github.com/influxdata/flux@v0.194.5/lang/compiler.go:191 +0x305 fp=0xc0025ae408 sp=0xc0025ae328 pc=0x7fe82ea9a005
influxdb-2  | github.com/influxdata/flux/lang.(*FluxCompiler).Compile(0xc00e2a1a00?, {0x7fe830ff39e8?, 0xc012713ce0?}, {0x7fe830fffb28?, 0x7fe83394b8a0?})
influxdb-2  | 	<autogenerated>:1 +0xd3 fp=0xc0025ae4b8 sp=0xc0025ae408 pc=0x7fe82ea9e7d3
influxdb-2  | github.com/influxdata/influxdb/v2/query/control.(*Controller).compileQuery(0xc00ecab440, 0xc00e2a1a00, {0x7fe830fe1520, 0xc00a7c7c40})
influxdb-2  | 	/root/project/query/control/controller.go:385 +0xfa fp=0xc0025ae540 sp=0xc0025ae4b8 pc=0x7fe82f7713ba
influxdb-2  | github.com/influxdata/influxdb/v2/query/control.(*Controller).query(0x7fe830ff39e8?, {0x7fe830ff39e8?, 0xc0127139b0?}, {0x7fe830fe1520, 0xc00a7c7c40}, 0xc00d03ab80?)
influxdb-2  | 	/root/project/query/control/controller.go:267 +0x55 fp=0xc0025ae590 sp=0xc0025ae540 pc=0x7fe82f7706b5
influxdb-2  | github.com/influxdata/influxdb/v2/query/control.(*Controller).Query(0xc00ecab440, {0x7fe830ff39e8?, 0xc012713830?}, 0xc00eec32d0)
influxdb-2  | 	/root/project/query/control/controller.go:250 +0x17a fp=0xc0025ae660 sp=0xc0025ae590 pc=0x7fe82f77043a
influxdb-2  | github.com/influxdata/influxdb/v2/query.ProxyQueryServiceAsyncBridge.Query({{0x7fe830fd2938?, 0xc00ecab440?}}, {0x7fe830ff39e8?, 0xc012713800?}, {0x7fe830fd44f8, 0xc00d1ac480}, 0xc00eec32d0)
influxdb-2  | 	/root/project/query/bridges.go:137 +0x137 fp=0xc0025ae820 sp=0xc0025ae660 pc=0x7fe82f3cf9f7
influxdb-2  | github.com/influxdata/influxdb/v2/query.(*ProxyQueryServiceAsyncBridge).Query(0x7fe83101f6d0?, {0x7fe830ff39e8?, 0xc012713800?}, {0x7fe830fd44f8?, 0xc00d1ac480?}, 0x7fe82dc09dd3?)
influxdb-2  | 	<autogenerated>:1 +0xb8 fp=0xc0025ae968 sp=0xc0025ae820 pc=0x7fe82f3d2238
influxdb-2  | github.com/influxdata/influxdb/v2/http.(*FluxHandler).handleQuery(0xc00bd2b000, {0x7fe830fef4a0, 0xc00d07c840}, 0xc0025aed50?)
influxdb-2  | 	/root/project/http/query_handler.go:198 +0x92d fp=0xc0025aed08 sp=0xc0025ae968 pc=0x7fe82f56342d
influxdb-2  | github.com/influxdata/influxdb/v2/http.(*FluxHandler).handleQuery-fm({0x7fe830fef4a0?, 0xc00d07c840?}, 0xc000c302e0?)
influxdb-2  | 	<autogenerated>:1 +0x36 fp=0xc0025aed38 sp=0xc0025aed08 pc=0x7fe82f5b0296
influxdb-2  | net/http.HandlerFunc.ServeHTTP(0x0?, {0x7fe830fef4a0?, 0xc00d07c840?}, 0x4?)
influxdb-2  | 	/go/src/net/http/server.go:2136 +0x29 fp=0xc0025aed60 sp=0xc0025aed38 pc=0x7fe82ded8489
influxdb-2  | github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1({0x7fe830feb8d0, 0xc000c302e0}, 0xe830dd8320?)
influxdb-2  | 	/go/pkg/mod/github.com/!n!y!times/gziphandler@v1.0.1/gzip.go:289 +0x254 fp=0xc0025aee10 sp=0xc0025aed60 pc=0x7fe82f4f3754
influxdb-2  | net/http.HandlerFunc.ServeHTTP(0x7fe82dbad205?, {0x7fe830feb8d0?, 0xc000c302e0?}, 0xf8?)
influxdb-2  | 	/go/src/net/http/server.go:2136 +0x29 fp=0xc0025aee38 sp=0xc0025aee10 pc=0x7fe82ded8489
influxdb-2  | github.com/influxdata/influxdb/v2/http.(*proxyHandler).ServeHTTP(0xc0007d7be0, {0x7fe830feb8d0, 0xc000c302e0}, 0xc0025f4600?)
influxdb-2  | 	/root/project/http/proxy_handler.go:33 +0x5e fp=0xc0025aee70 sp=0xc0025aee38 pc=0x7fe82f56011e
influxdb-2  | github.com/influxdata/influxdb/v2/http.NewFluxHandler.(*Router).Handler.func1({0x7fe830feb8d0?, 0xc000c302e0?}, 0x7fe830be08a0?, {0x0?, 0x7fe830ac8880?, 0xc00d03a830?})
influxdb-2  | 	/go/pkg/mod/github.com/influxdata/httprouter@v1.3.1-0.20191122104820-ee83e2772f69/router.go:325 +0xee fp=0xc0025aeed0 sp=0xc0025aee70 pc=0x7fe82f562aae
influxdb-2  | github.com/influxdata/httprouter.(*Router).ServeHTTP(0xc008c014d0, {0x7fe830feb8d0, 0xc000c302e0}, 0xc0025f4500)
influxdb-2  | 	/go/pkg/mod/github.com/influxdata/httprouter@v1.3.1-0.20191122104820-ee83e2772f69/router.go:453 +0x359 fp=0xc0025af028 sp=0xc0025aeed0 pc=0x7fe82e25c939
influxdb-2  | github.com/influxdata/influxdb/v2/http.(*FluxHandler).ServeHTTP(0x80?, {0x7fe830feb8d0?, 0xc000c302e0?}, 0xc0127129f0?)
influxdb-2  | 	<autogenerated>:1 +0x29 fp=0xc0025af058 sp=0xc0025af028 pc=0x7fe82f5a6dc9
influxdb-2  | github.com/go-chi/chi.(*Mux).Mount.func1({0x7fe830feb8d0, 0xc000c302e0}, 0xc0025f4500)
influxdb-2  | 	/go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:298 +0x165 fp=0xc0025af0a8 sp=0xc0025af058 pc=0x7fe82e2560a5
influxdb-2  | net/http.HandlerFunc.ServeHTTP(0x7fe830bc6aa0?, {0x7fe830feb8d0?, 0xc000c302e0?}, 0xc00d110410?)
influxdb-2  | 	/go/src/net/http/server.go:2136 +0x29 fp=0xc0025af0d0 sp=0xc0025af0a8 pc=0x7fe82ded8489
influxdb-2  | github.com/go-chi/chi.(*Mux).routeHTTP(0xc00d736a80, {0x7fe830feb8d0, 0xc000c302e0}, 0xc0025f4500)
influxdb-2  | 	/go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:431 +0x1f2 fp=0xc0025af120 sp=0xc0025af0d0 pc=0x7fe82e2568b2
influxdb-2  | github.com/go-chi/chi.(*Mux).routeHTTP-fm({0x7fe830feb8d0?, 0xc000c302e0?}, 0xc0025806e0?)
influxdb-2  | 	<autogenerated>:1 +0x36 fp=0xc0025af150 sp=0xc0025af120 pc=0x7fe82e25a836
influxdb-2  | net/http.HandlerFunc.ServeHTTP(0x7fe830dc3100?, {0x7fe830feb8d0?, 0xc000c302e0?}, 0x1b?)
influxdb-2  | 	/go/src/net/http/server.go:2136 +0x29 fp=0xc0025af178 sp=0xc0025af150 pc=0x7fe82ded8489
influxdb-2  | github.com/influxdata/influxdb/v2/kit/transport/http.SetCORS.func1({0x7fe830feb8d0, 0xc000c302e0}, 0xc0025f4500)
influxdb-2  | 	/root/project/kit/transport/http/middleware.go:48 +0x311 fp=0xc0025af208 sp=0xc0025af178 pc=0x7fe82e56aed1
influxdb-2  | net/http.HandlerFunc.ServeHTTP(0x0?, {0x7fe830feb8d0?, 0xc000c302e0?}, 0xc000e0fe20?)
influxdb-2  | 	/go/src/net/http/server.go:2136 +0x29 fp=0xc0025af230 sp=0xc0025af208 pc=0x7fe82ded8489
influxdb-2  | github.com/go-chi/chi/middleware.StripSlashes.func1({0x7fe830feb8d0, 0xc000c302e0}, 0xc0025f4500)
influxdb-2  | 	/go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/middleware/strip.go:25 +0xf1 fp=0xc0025af270 sp=0xc0025af230 pc=0x7fe82e55efb1
influxdb-2  | net/http.HandlerFunc.ServeHTTP(0xc012712960?, {0x7fe830feb8d0?, 0xc000c302e0?}, 0xc004a3c000?)
influxdb-2  | 	/go/src/net/http/server.go:2136 +0x29 fp=0xc0025af298 sp=0xc0025af270 pc=0x7fe82ded8489
influxdb-2  | github.com/influxdata/influxdb/v2/kit/transport/http.SkipOptions.func1({0x7fe830feb8d0, 0xc000c302e0}, 0xc0025f4500)
influxdb-2  | 	/root/project/kit/transport/http/middleware.go:93 +0xaf fp=0xc0025af2d8 sp=0xc0025af298 pc=0x7fe82e56b04f
influxdb-2  | net/http.HandlerFunc.ServeHTTP(0x7fe82dc3fb05?, {0x7fe830feb8d0?, 0xc000c302e0?}, 0x7fe830bb1920?)
influxdb-2  | 	/go/src/net/http/server.go:2136 +0x29 fp=0xc0025af300 sp=0xc0025af2d8 pc=0x7fe82ded8489
influxdb-2  | github.com/influxdata/influxdb/v2/http.NewBaseChiRouter.panicMW.func3.1({0x7fe830feb8d0?, 0xc000c302e0?}, 0x7fe831010730?)
influxdb-2  | 	/root/project/http/router.go:126 +0x87 fp=0xc0025af368 sp=0xc0025af300 pc=0x7fe82f569e47
influxdb-2  | net/http.HandlerFunc.ServeHTTP(0xc0025f4500?, {0x7fe830feb8d0?, 0xc000c302e0?}, 0x7fe830f83a40?)
influxdb-2  | 	/go/src/net/http/server.go:2136 +0x29 fp=0xc0025af390 sp=0xc0025af368 pc=0x7fe82ded8489
influxdb-2  | github.com/go-chi/chi.(*Mux).ServeHTTP(0xc00d736a80, {0x7fe830feb8d0, 0xc000c302e0}, 0xc0025f4500)
influxdb-2  | 	/go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:70 +0x2f3 fp=0xc0025af3f0 sp=0xc0025af390 pc=0x7fe82e2548b3
influxdb-2  | github.com/influxdata/influxdb/v2/http.(*APIHandler).ServeHTTP(0x7fe830ff39e8?, {0x7fe830feb8d0?, 0xc000c302e0?}, 0x7fe833988f20?)
influxdb-2  | 	<autogenerated>:1 +0x31 fp=0xc0025af420 sp=0xc0025af3f0 pc=0x7fe82f593af1
influxdb-2  | github.com/influxdata/influxdb/v2/kit/feature.(*Handler).ServeHTTP(0xc00d7a5040, {0x7fe830feb8d0, 0xc000c302e0}, 0xc0025f4400)
influxdb-2  | 	/root/project/kit/feature/middleware.go:43 +0x288 fp=0xc0025af508 sp=0xc0025af420 pc=0x7fe82e563f08
influxdb-2  | github.com/influxdata/influxdb/v2/http.(*AuthenticationHandler).ServeHTTP(0xc00eb56bd0, {0x7fe830feb8d0, 0xc000c302e0}, 0xc0025f4300)
influxdb-2  | 	/root/project/http/authentication_middleware.go:130 +0x35a fp=0xc0025af598 sp=0xc0025af508 pc=0x7fe82f53df5a
influxdb-2  | github.com/influxdata/influxdb/v2/http.NewPlatformHandler.SetCORS.func7({0x7fe830feb8d0, 0xc000c302e0}, 0xc0025f4300)
influxdb-2  | 	/root/project/kit/transport/http/middleware.go:48 +0x147 fp=0xc0025af5f0 sp=0xc0025af598 pc=0x7fe82f55fe47
influxdb-2  | net/http.HandlerFunc.ServeHTTP(0xc?, {0x7fe830feb8d0?, 0xc000c302e0?}, 0xc00d110410?)
influxdb-2  | 	/go/src/net/http/server.go:2136 +0x29 fp=0xc0025af618 sp=0xc0025af5f0 pc=0x7fe82ded8489
influxdb-2  | github.com/influxdata/influxdb/v2/http.NewPlatformHandler.SkipOptions.func8({0x7fe830feb8d0, 0xc000c302e0}, 0xc0025f4300)
influxdb-2  | 	/root/project/kit/transport/http/middleware.go:93 +0xaf fp=0xc0025af658 sp=0xc0025af618 pc=0x7fe82f55fccf
influxdb-2  | net/http.HandlerFunc.ServeHTTP(0x7fe830190bf0?, {0x7fe830feb8d0?, 0xc000c302e0?}, 0xc?)
influxdb-2  | 	/go/src/net/http/server.go:2136 +0x29 fp=0xc0025af680 sp=0xc0025af658 pc=0x7fe82ded8489
influxdb-2  | github.com/influxdata/influxdb/v2/http.(*PlatformHandler).ServeHTTP(0xc00d7a5180, {0x7fe830feb8d0, 0xc000c302e0}, 0xc0025f4300)
influxdb-2  | 	/root/project/http/platform_handler.go:84 +0x1c5 fp=0xc0025af6b0 sp=0xc0025af680 pc=0x7fe82f560045
influxdb-2  | github.com/go-chi/chi.(*Mux).Mount.func1({0x7fe830feb8d0, 0xc000c302e0}, 0xc0025f4300)
influxdb-2  | 	/go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:298 +0x165 fp=0xc0025af700 sp=0xc0025af6b0 pc=0x7fe82e2560a5
influxdb-2  | net/http.HandlerFunc.ServeHTTP(0x7fe830fec710?, {0x7fe830feb8d0?, 0xc000c302e0?}, 0xc000c30240?)
influxdb-2  | 	/go/src/net/http/server.go:2136 +0x29 fp=0xc0025af728 sp=0xc0025af700 pc=0x7fe82ded8489
influxdb-2  | github.com/influxdata/influxdb/v2/http.NewRootHandler.func3.Metrics.func2.1({0x7fe830fec710?, 0xc003ba8a80?}, 0xc0025f4300)
influxdb-2  | 	/root/project/kit/transport/http/middleware.go:78 +0x17b fp=0xc0025af800 sp=0xc0025af728 pc=0x7fe82f54c87b
influxdb-2  | net/http.HandlerFunc.ServeHTTP(0xc0025918c8?, {0x7fe830fec710?, 0xc003ba8a80?}, 0x7fe82dc08c1b?)
influxdb-2  | 	/go/src/net/http/server.go:2136 +0x29 fp=0xc0025af828 sp=0xc0025af800 pc=0x7fe82ded8489
influxdb-2  | github.com/influxdata/influxdb/v2/http.NewRootHandler.func3.Trace.func1.1({0x7fe830fec710, 0xc003ba8a80}, 0x1?)
influxdb-2  | 	/root/project/kit/transport/http/middleware.go:118 +0x302 fp=0xc0025af940 sp=0xc0025af828 pc=0x7fe82f54d122
influxdb-2  | net/http.HandlerFunc.ServeHTTP(0xc00d7b2960?, {0x7fe830fec710?, 0xc003ba8a80?}, 0xc00d03a070?)
influxdb-2  | 	/go/src/net/http/server.go:2136 +0x29 fp=0xc0025af968 sp=0xc0025af940 pc=0x7fe82ded8489
influxdb-2  | github.com/go-chi/chi.(*ChainHandler).ServeHTTP(0x7fe830bc6aa0?, {0x7fe830fec710?, 0xc003ba8a80?}, 0xc0018d8345?)
influxdb-2  | 	/go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/chain.go:31 +0x26 fp=0xc0025af998 sp=0xc0025af968 pc=0x7fe82e253e86
influxdb-2  | github.com/go-chi/chi.(*Mux).routeHTTP(0xc00d7593e0, {0x7fe830fec710, 0xc003ba8a80}, 0xc0025f4200)
influxdb-2  | 	/go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:431 +0x1f2 fp=0xc0025af9e8 sp=0xc0025af998 pc=0x7fe82e2568b2
influxdb-2  | github.com/go-chi/chi.(*Mux).routeHTTP-fm({0x7fe830fec710?, 0xc003ba8a80?}, 0x14?)
influxdb-2  | 	<autogenerated>:1 +0x36 fp=0xc0025afa18 sp=0xc0025af9e8 pc=0x7fe82e25a836
influxdb-2  | net/http.HandlerFunc.ServeHTTP(0x7fe830f83a40?, {0x7fe830fec710?, 0xc003ba8a80?}, 0x7fe82d3271d8?)
influxdb-2  | 	/go/src/net/http/server.go:2136 +0x29 fp=0xc0025afa40 sp=0xc0025afa18 pc=0x7fe82ded8489
influxdb-2  | github.com/influxdata/influxdb/v2/http.(*AddHeader).Middleware-fm.(*AddHeader).Middleware.func1({0x7fe830fec710, 0xc003ba8a80}, 0x7fe83235f901?)
influxdb-2  | 	/root/project/http/handler.go:102 +0x72 fp=0xc0025afa90 sp=0xc0025afa40 pc=0x7fe82f590992
influxdb-2  | net/http.HandlerFunc.ServeHTTP(0x7fe830ff3a20?, {0x7fe830fec710?, 0xc003ba8a80?}, 0x7fe83235f940?)
influxdb-2  | 	/go/src/net/http/server.go:2136 +0x29 fp=0xc0025afab8 sp=0xc0025afa90 pc=0x7fe82ded8489
influxdb-2  | github.com/go-chi/chi.(*Mux).ServeHTTP(0xc00d7593e0, {0x7fe830fec710, 0xc003ba8a80}, 0xc0025f4000)
influxdb-2  | 	/go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:86 +0x2b1 fp=0xc0025afb18 sp=0xc0025afab8 pc=0x7fe82e254871
influxdb-2  | github.com/influxdata/influxdb/v2/http.(*Handler).ServeHTTP(0x7fe82dbad585?, {0x7fe830fec710?, 0xc003ba8a80?}, 0xc003ba8a01?)
influxdb-2  | 	/root/project/http/handler.go:166 +0x29 fp=0xc0025afb48 sp=0xc0025afb18 pc=0x7fe82f54db69
influxdb-2  | net/http.serverHandler.ServeHTTP({0x7fe830fe2ce0?}, {0x7fe830fec710?, 0xc003ba8a80?}, 0x6?)
influxdb-2  | 	/go/src/net/http/server.go:2938 +0x8e fp=0xc0025afb78 sp=0xc0025afb48 pc=0x7fe82dedb16e
influxdb-2  | net/http.(*conn).serve(0xc00cfcc120, {0x7fe830ff39e8, 0xc00bd7e660})
influxdb-2  | 	/go/src/net/http/server.go:2009 +0x5f4 fp=0xc0025affb8 sp=0xc0025afb78 pc=0x7fe82ded7054
influxdb-2  | net/http.(*Server).Serve.func3()
influxdb-2  | 	/go/src/net/http/server.go:3086 +0x28 fp=0xc0025affe0 sp=0xc0025affb8 pc=0x7fe82dedb988
influxdb-2  | runtime.goexit()
influxdb-2  | 	/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0025affe8 sp=0xc0025affe0 pc=0x7fe82dc0e421
influxdb-2  | created by net/http.(*Server).Serve in goroutine 9007
influxdb-2  | 	/go/src/net/http/server.go:3086 +0x5cb
```

**Comment by davidby-influx** [comment]
This is failing in parsing the query. You may need to simplify it, as Flux is in maintenance mode, and not being actively improved.
