### ISSUE TITLE
Queries fail with Column is declared as non-nullable but contains null values

### ISSUE THREAD

**Issue by btasker** [influxdata/influxdb#25648]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behaviour.

Define a new table with a small schema

```sh
curl -d 'repro,tag1=a,tag2=b field1=3,field2=4' http://$INFLUXDB/write?db=test
```

Verify that you can query the data
```sh
influxdb3 query --dbname=test "select * from repro"
```

Write in a second point which omits one of the tags
```sh
curl -d 'repro,tag1=a field1=3,field2=4' http://$INFLUXDB/write?db=test
```

Attempt to query again
```sh
influxdb3 query --dbname=test "select * from repro"
```

This fails with
```text
Query command failed: server responded with error [500 Internal Server Error]: query error: error while planning query: Execution error: error getting batches Error creating record batch: Invalid argument error: Column 'tag2' is declared as non-nullable but contains null values
```

This doesn't consistently happen, for example if you omit a tag and write and entirely new field in, it queries fine:
```sh
ben@ratchett:~/Downloads$ curl -d 'repro5,tag1=a,tag2=b field1=3,field2=4' http://$INFLUXDB/write?db=test
ben@ratchett:~/Downloads$ curl -d 'repro5,tag1=a newfield=6' http://$INFLUXDB/write?db=test

$ influxdb3 query --dbname=test "select * from repro5"
+--------+--------+----------+------+------+-------------------------------+
| field1 | field2 | newfield | tag1 | tag2 | time                          |
+--------+--------+----------+------+------+-------------------------------+
|        |        | 6.0      | a    |      | 2024-12-12T16:37:23.790909037 |
| 3.0    | 4.0    |          | a    | b    | 2024-12-12T16:37:13.607174767 |
+--------+--------+----------+------+------+-------------------------------+
```

However, trying different variations ultimately leads to a different error being returned
```
# first write
curl -d 'repro6,tag1=a,tag2=b field1=3,field2=4' http://$INFLUXDB/write?db=test

+--------+--------+------+------+-------------------------------+
| field1 | field2 | tag1 | tag2 | time                          |
+--------+--------+------+------+-------------------------------+
| 3.0    | 4.0    | a    | b    | 2024-12-12T16:48:14.025889928 |
+--------+--------+------+------+-------------------------------+


# Keep tags, omit second field
curl -d 'repro6,tag1=a,tag2=b field1=3' http://$INFLUXDB/write?db=test

+--------+--------+------+------+-------------------------------+
| field1 | field2 | tag1 | tag2 | time                          |
+--------+--------+------+------+-------------------------------+
| 3.0    | 4.0    | a    | b    | 2024-12-12T16:48:14.025889928 |
| 3.0    |        | a    | b    | 2024-12-12T16:48:24.896081684 |
+--------+--------+------+------+-------------------------------+



# Keep tags, omit first field
curl -d 'repro6,tag1=a,tag2=b field2=4' http://$INFLUXDB/write?db=test
+--------+--------+------+------+-------------------------------+
| field1 | field2 | tag1 | tag2 | time                          |
+--------+--------+------+------+-------------------------------+
| 3.0    | 4.0    | a    | b    | 2024-12-12T16:48:14.025889928 |
| 3.0    |        | a    | b    | 2024-12-12T16:48:24.896081684 |
|        | 4.0    | a    | b    | 2024-12-12T16:48:45.603552895 |
+--------+--------+------+------+-------------------------------+


# Keep tags introduce new field
curl -d 'repro6,tag1=a,tag2=b field3=5' http://$INFLUXDB/write?db=test
+--------+--------+--------+------+------+-------------------------------+
| field1 | field2 | field3 | tag1 | tag2 | time                          |
+--------+--------+--------+------+------+-------------------------------+
| 3.0    | 4.0    |        | a    | b    | 2024-12-12T16:48:14.025889928 |
| 3.0    |        |        | a    | b    | 2024-12-12T16:48:24.896081684 |
|        | 4.0    |        | a    | b    | 2024-12-12T16:48:45.603552895 |
|        |        | 5.0    | a    | b    | 2024-12-12T16:49:16.074340717 |
+--------+--------+--------+------+------+-------------------------------+


# Omit first tag, use the new field
curl -d 'repro6,tag2=b field3=5' http://$INFLUXDB/write?db=test
+--------+--------+--------+------+------+-------------------------------+
| field1 | field2 | field3 | tag1 | tag2 | time                          |
+--------+--------+--------+------+------+-------------------------------+
|        |        | 5.0    |      | b    | 2024-12-12T16:49:46.020503326 |
| 3.0    | 4.0    |        | a    | b    | 2024-12-12T16:48:14.025889928 |
| 3.0    |        |        | a    | b    | 2024-12-12T16:48:24.896081684 |
|        | 4.0    |        | a    | b    | 2024-12-12T16:48:45.603552895 |
|        |        | 5.0    | a    | b    | 2024-12-12T16:49:16.074340717 |
+--------+--------+--------+------+------+-------------------------------+


# Omit second tag, use the new field
curl -d 'repro6,tag1=a field3=5' http://$INFLUXDB/write?db=test

Query command failed: server responded with error [500 Internal Server Error]: query error: error while planning query: Execution error: error getting batches Field not found in table buffer: field1
command terminated with exit code 1
```

__Expected behaviour:__

The queries should work, with the tag value showing up as null in the results

__Actual behaviour:__

The query fails

__Environment info:__

* Please provide the command you used to build the project, including any `RUSTFLAGS`: I used the install script

__Logs:__

```text
2024-12-12T16:44:36.153267Z  INFO iox_query::query_log: query when="fail" id=087dea56-435f-41cd-b8d9-baf8ed8b471f namespace_id=0 namespace_name="influxdb3 edge" query_type="sql" query_text=select * from repro query_params=Params { } issue_time=2024-12-12T16:44:36.152554083+00:00 plan_duration_secs=0.000710224 end2end_duration_secs=0.000711817 ingester_metrics=None success=false running=false cancelled=false
2024-12-12T16:44:36.153302Z ERROR influxdb3_server::http: Error while handling request error=query error: error while planning query: Execution error: error getting batches Error creating record batch: Invalid argument error: Column 'tag' is declared as non-nullable but contains null values method=POST uri=/api/v3/query_sql content_length=Some("72")
```

**Comment by btasker** [comment]
It occurred to me that it'd be worth seeing if it persisted across restarts (i.e. if it was something in memory).

Unfortunately, restarting causes it to panic when it comes up
```
2024-12-12T19:28:56.977515Z  INFO influxdb3_write::write_buffer::queryable_buffer: persisting 236 chunks for wal number 900
2024-12-12T19:28:56.977534Z  INFO influxdb3_write::write_buffer::queryable_buffer: Persisting 2 rows for db id 0 and table id 483 and chunk 1734021000000000000 to file docker0/dbs/test-0/repro3-483/2024-12-12/16-30/0000000900.parquet
2024-12-12T19:28:57.009224Z  INFO influxdb3_write::write_buffer::queryable_buffer: Persisted parquet file: docker0/dbs/test-0/repro3-483/2024-12-12/16-30/0000000900.parquet
2024-12-12T19:28:57.009294Z  INFO influxdb3_write::write_buffer::queryable_buffer: Persisting 4 rows for db id 0 and table id 486 and chunk 1734021000000000000 to file docker0/dbs/test-0/repro5-486/2024-12-12/16-30/0000000900.parquet
2024-12-12T19:28:57.083153Z  INFO influxdb3_write::write_buffer::queryable_buffer: Persisted parquet file: docker0/dbs/test-0/repro5-486/2024-12-12/16-30/0000000900.parquet
2024-12-12T19:28:57.083241Z  INFO influxdb3_write::write_buffer::queryable_buffer: Persisting 1 rows for db id 0 and table id 486 and chunk 1734021600000000000 to file docker0/dbs/test-0/repro5-486/2024-12-12/16-40/0000000900.parquet
2024-12-12T19:28:57.083489Z ERROR panic_logging: Thread panic panic_type="unknown" panic_message="called `Result::unwrap()` on an `Err` value: BuildingPlan { source: SchemaError(FieldNotFound { field: Column { relation: None, name: \"tag1\" }, valid_fields: [Column { relation: Some(Bare { table: \"repro5\" }), name: \"tag2\" }, Column { relation: Some(Bare { table: \"repro5\" }), name: \"field1\" }, Column { relation: Some(Bare { table: \"repro5\" }), name: \"time\" }, Column { relation: Some(Bare { table: \"repro5\" }), name: \"newfield\" }] }, Some(\"\")) }" panic_file="influxdb3_write/src/write_buffer/queryable_buffer.rs" panic_line=593 panic_column=10
thread 'tokio-runtime-worker' panicked at influxdb3_write/src/write_buffer/queryable_buffer.rs:593:10:
called `Result::unwrap()` on an `Err` value: BuildingPlan { source: SchemaError(FieldNotFound { field: Column { relation: None, name: "tag1" }, valid_fields: [Column { relation: Some(Bare { table: "repro5" }), name: "tag2" }, Column { relation: Some(Bare { table: "repro5" }), name: "field1" }, Column { relation: Some(Bare { table: "repro5" }), name: "time" }, Column { relation: Some(Bare { table: "repro5" }), name: "newfield" }] }, Some("")) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at /root/project/influxdb3_wal/src/object_store.rs:146:59:
2024-12-12T19:28:57.083828Z ERROR panic_logging: Thread panic panic_type="unknown" panic_message="called `Result::unwrap()` on an `Err` value: RecvError(())" panic_file="/root/project/influxdb3_wal/src/object_store.rs" panic_line=146 panic_column=59
called `Result::unwrap()` on an `Err` value: RecvError(())
2024-12-12T19:28:57.087319Z  WARN executor: DedicatedExecutor dropped without calling shutdown()
2024-12-12T19:28:57.087340Z  INFO influxdb3_cache::parquet_cache: cache request handler closed
```
