### ISSUE TITLE
Panic on influxdb3 0.1.0, revision v2.5.0-14188-gb2f6c1a0b6bdf57f26d2fe061afa4f3495dd8a4a running on Mac M2

### ISSUE THREAD

**Issue by M617263Kaplan** [influxdata/influxdb#25650]
__Logs:__
Include snippet of errors in logs or stack traces here.
Sometimes you can get useful information by running the program with the `RUST_BACKTRACE=full` environment variable.
Finally, the IOx server has a `-vv` for verbose logging.

RUST_BACKTRACE=0
2024-12-12T17:10:09.143125Z  INFO influxdb3::commands::serve: InfluxDB3 Edge server starting git_hash=v2.5.0-14188-gb2f6c1a0b6bdf57f26d2fe061afa4f3495dd8a4a version=0.1.0 uuid=0deb40d5-185b-4a5e-be5f-5b0a83673547 num_cpus=12 build_malloc_conf=
2024-12-12T17:10:09.143190Z  INFO clap_blocks::object_store: Object Store db_dir="/Users/marckaplan/.influxdb3" object_store_type="Directory"
2024-12-12T17:10:09.143302Z  INFO influxdb3::commands::serve: Creating shared query executor num_threads=12
2024-12-12T17:10:09.146259Z  INFO influxdb3::commands::serve: Catalog initialized with instance_id="522a9004-0d4d-4a44-b2f4-a3005154f05e"
2024-12-12T17:10:09.146997Z ERROR panic_logging: Thread panic panic_type="unknown" panic_message="assertion failed: min_time <= max_time" panic_file="influxdb3_wal/src/snapshot_tracker.rs" panic_line=164 panic_column=9
thread 'main' panicked at influxdb3_wal/src/snapshot_tracker.rs:164:9:
assertion failed: min_time <= max_time
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-12-12T17:10:09.147497Z  WARN executor: DedicatedExecutor dropped without calling shutdown()
2024-12-12T17:10:09.147496Z  INFO influxdb3_cache::parquet_cache: cache request handler closed

RUST_BACKTRACE=1
2024-12-12T17:57:20.380454Z  INFO influxdb3::commands::serve: InfluxDB3 Edge server starting git_hash=v2.5.0-14188-gb2f6c1a0b6bdf57f26d2fe061afa4f3495dd8a4a version=0.1.0 uuid=a71e0814-5931-4cb1-a875-821faa45ae4b num_cpus=12 build_malloc_conf=
2024-12-12T17:57:20.380551Z  INFO clap_blocks::object_store: Object Store db_dir="/Users/marckaplan/.influxdb3" object_store_type="Directory"
2024-12-12T17:57:20.380679Z  INFO influxdb3::commands::serve: Creating shared query executor num_threads=12
2024-12-12T17:57:20.382465Z  INFO influxdb3::commands::serve: Catalog initialized with instance_id="522a9004-0d4d-4a44-b2f4-a3005154f05e"
2024-12-12T17:57:20.382850Z ERROR panic_logging: Thread panic panic_type="unknown" panic_message="assertion failed: min_time <= max_time" panic_file="influxdb3_wal/src/snapshot_tracker.rs" panic_line=164 panic_column=9
thread 'main' panicked at influxdb3_wal/src/snapshot_tracker.rs:164:9:
assertion failed: min_time <= max_time
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: influxdb3_wal::snapshot_tracker::WalPeriod::new
   4: influxdb3_write::write_buffer::WriteBufferImpl::new::{{closure}}
   5: influxdb3::commands::serve::command::{{closure}}
   6: influxdb3::main::{{closure}}
   7: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
   8: tokio::runtime::park::CachedParkThread::block_on
   9: tokio::runtime::context::runtime::enter_runtime
  10: tokio::runtime::runtime::Runtime::block_on

**Comment by M617263Kaplan** [comment]
1. shutdown
2. influxdb3 serve --host-id=local01 --object-store=file --data-dir ~/.influxdb3

**Comment by lilic** [comment]
I ran into this panic today, I was using local data dir as well.

I did a few writes, reads, shut down and the panic happened:

```
2025-01-08T12:37:27.767429Z ERROR panic_logging: Thread panic panic_type="unknown" panic_message="assertion failed: min_time <= max_time" panic_file="influxdb3_wal/src/snapshot_tracker.rs" panic_line=164 panic_column=9
thread 'main' panicked at influxdb3_wal/src/snapshot_tracker.rs:164:9:
assertion failed: min_time <= max_time
```

**Comment by nbowisdar** [comment]
influx  | thread 'main' panicked at influxdb3_wal/src/snapshot_tracker.rs:216:9:
influx  | assertion failed: min_time <= max_time
influx  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
influx  | 2025-04-08T14:55:28.949570Z  WARN executor: DedicatedExecutor dropped without calling shutdown()
influx  | 2025-04-08T14:55:28.949581Z  INFO influxdb3_cache::parquet_cache: cache request handler closed

+

**Comment by hiltontj** [comment]
The issue that leads to this panic should have been resolved in https://github.com/influxdata/influxdb/pull/26223.

However, there may still be WAL files that are corrupted as a result. We may need to have some additional handling in place to ignore these files (they are the result of an empty write, so can be ignored safely) instead of letting them panic. That is, if `min_time == i64::MAX` and `max_time == i64::MIN`...

**Comment by hiltontj** [comment]
I opened https://github.com/influxdata/influxdb/issues/26237 to hopefully address this.
