### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by nichdiekuh** [influxdata/influxdb#280]
After upgrading to 0.5 I quickly run into "too many open files" while batch-inserting lots of events. Haven't had this issue on 0.4 with the same script migrating the data:

```

2014/02/27 00:00:18 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:19 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:20 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:21 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:22 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:23 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:24 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:25 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:26 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:27 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:28 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:29 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:30 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:31 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:32 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:33 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:34 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:35 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:36 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:37 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:38 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:39 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:40 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:41 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:42 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:43 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:44 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:45 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:46 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:47 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:48 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:49 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:50 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:51 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:52 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:53 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:54 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:55 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:56 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:57 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:58 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
2014/02/27 00:00:59 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 1s
[02/27/14 00:01:00] [WARN] Rotating request log...
panic: IO error: /opt/influxdb/shared/data/db/request_logs/2014-5872944-27/LOCK: Too many open files

goroutine 6 [running]:
runtime.panic(0x84e3a0, 0xc21b9bdd60)
        /home/vagrant/bin/go/src/pkg/runtime/panic.c:266 +0xb6
datastore.(*LevelDbDatastore).rotateRequestLog(0xc210071000)
        /home/vagrant/influxdb/src/datastore/leveldb_datastore.go:229 +0x25a
datastore.(*LevelDbDatastore).periodicallyRotateRequestLog(0xc210071000)
        /home/vagrant/influxdb/src/datastore/leveldb_datastore.go:214 +0x4f
created by datastore.NewLevelDbDatastore
        /home/vagrant/influxdb/src/datastore/leveldb_datastore.go:205 +0x700

goroutine 1 [sleep]:
time.Sleep(0x3b9aca00)
        /tmp/bindist375750859/go/src/pkg/runtime/time.goc:31 +0x31
```

**Comment by iantheconway** [comment]
I'm having a similar issue in 1.2.3; after writing a few hundred rows I get an error message about too many open files. In order to fix it should I set my ulimit or kern.maxfiles to something higher? Or is there a configuration option in influxdb.conf?

**Comment by linuxmail** [comment]
hi,
I have the same problem under Debian Stretch with 1.6.1-1  (and below). I tried to change it via systemctl edit telegraf.service or "vi /lib/systemd/system/telegraf.service"  but ..

```
su telegraf --shell /bin/bash --command "ulimit -a" |grep open
open files                      (-n) 50000
```
cu denny
