### ISSUE TITLE
[0.9.0]Panic unknown type when writing points with named types

### ISSUE THREAD

**Issue by epelc** [influxdata/influxdb#3024]
Hello, I've just started upgrading to `0.9.0` and I ran into an issue with the go client. I'm receiving unknown type panics if I don't convert all my types back to basic types like `string`. In my example below `provider.Carrier` is a `Carrier` which is defined as `type Carrier string`. To avoid the panic I have to do `string(Carrier)` whenever I use it.

Here is the panic
```
panic: unknown type: provider.Carrier

goroutine 22 [running]:
github.com/influxdb/influxdb/tsdb.Fields.MarshalBinary(0xc208131d10, 0x0, 0x0, 0x0)
	/go/src/github.com/influxdb/influxdb/tsdb/points.go:802 +0xe25
github.com/influxdb/influxdb/tsdb.NewPoint(0xbeac30, 0xc, 0x0, 0xc208131d10, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/influxdb/influxdb/tsdb/points.go:499 +0xa3
github.com/influxdb/influxdb/client.(*Point).MarshalString(0xc20816f680, 0x0, 0x0)
	/go/src/github.com/influxdb/influxdb/client/influxdb.go:372 +0x71
github.com/influxdb/influxdb/client.(*Client).Write(0xc20806d040, 0xc208078580, 0xd, 0x10, 0xbf2990, 0xc, 0x0, 0x0, 0xc20810a3f0, 0xecbf2b601, ...)
	/go/src/github.com/influxdb/influxdb/client/influxdb.go:132 +0xf8d
...
```

Mini example code(needs connection)
```
type Carrier string

ExampleCarrier Carrier = "Example"

conn := //your client connection

conn.Write(client.BatchPoints {
    Points: [] client.Point {
        Fields: map[string] interface {} {
            //This will cause a panic. You need to use string(ExampleCarrier) for it to work
            "Carrier": ExampleCarrier,
        },
    },
    Database: "yourDb",
})
```

**Comment by jwilder** [comment]
Fixed via #4299
