### ISSUE TITLE
go test fails TestEngine_WriteIndex_Quick_Append

### ISSUE THREAD

**Issue by BGraco** [influxdata/influxdb#3782]
Built latest (0.9.3. release?) on a beaglebone black running debian 7.8. 
"go test -v ./... "returns all PASS except for the result below

=== RUN TestEngine_WriteIndex_Quick_Append
SIGQUIT: quit
PC=0x4fbd4

goroutine 6 [syscall, 9 minutes]:
runtime.notetsleepg(0x60f580, 0xffffffff, 0xffffffff, 0x1)
	/root/.gvm/gos/go1.4/src/runtime/lock_futex.go:201 +0x58 fp=0x1081b7ac sp=0x1081b794
runtime.signal_recv(0x4e7ff8)
	/root/.gvm/gos/go1.4/src/runtime/sigqueue.go:109 +0x174 fp=0x1081b7cc sp=0x1081b7ac
os/signal.loop()
	/root/.gvm/gos/go1.4/src/os/signal/signal_unix.go:21 +0x1c fp=0x1081b7ec sp=0x1081b7cc
runtime.goexit()
	/root/.gvm/gos/go1.4/src/runtime/asm_arm.s:1322 +0x4 fp=0x1081b7ec sp=0x1081b7ec
created by os/signal.init·1
	/root/.gvm/gos/go1.4/src/os/signal/signal_unix.go:27 +0x40

goroutine 1 [chan receive, 3 minutes]:
testing.RunTests(0x4e2180, 0x6050a0, 0xa, 0xa, 0xb6e7a001)
	/root/.gvm/gos/go1.4/src/testing/testing.go:556 +0x814
testing.(*M).Run(0x108328a0, 0x60cae8)
	/root/.gvm/gos/go1.4/src/testing/testing.go:485 +0x74
main.main()
	github.com/influxdb/influxdb/tsdb/engine/bz1/_test/_testmain.go:88 +0x1b4

goroutine 16 [running]:
	goroutine running on other thread; stack unavailable
created by testing.RunTests
	/root/.gvm/gos/go1.4/src/testing/testing.go:555 +0x7e0

trap    0x6
error   0x0
oldmask 0x0
r0      0x60f580
r1      0x0
r2      0x0
r3      0x0
r4      0x0
r5      0x0
r6      0x3b9aca00
r7      0xf0
r8      0x60f580
r9      0x0
r10     0x10800a00
fp      0xffffffff
ip      0x10800b6d
sp      0x1081b74c
lr      0x40510
pc      0x4fbd4
cpsr    0x20000010
fault   0x0
*** Test killed with quit: ran too long (10m0s).
FAIL	github.com/influxdb/influxdb/tsdb/engine/bz1	600.016s

**Comment by BGraco** [comment]
This has been resolved
