### ISSUE TITLE
[0.9.4-nightly] runtime: memory allocated by OS (2942005248) not in usable range [0x18c00000,0x98c00000)

### ISSUE THREAD

**Issue by brunoqc** [influxdata/influxdb#3907]
```
 8888888           .d888 888                   8888888b.  888888b.
   888            d88P"  888                   888  "Y88b 888  "88b
   888            888    888                   888    888 888  .88P
   888   88888b.  888888 888 888  888 888  888 888    888 8888888K.
   888   888 "88b 888    888 888  888  Y8bd8P' 888    888 888  "Y88b
   888   888  888 888    888 888  888   X88K   888    888 888    888
   888   888  888 888    888 Y88b 888 .d8""8b. 888  .d88P 888   d88P
 8888888 888  888 888    888  "Y88888 888  888 8888888P"  8888888P"

2015/08/31 13:22:24 InfluxDB starting, version 0.9, branch unknown, commit unknown
2015/08/31 13:22:24 Go version go1.5, GOMAXPROCS set to 2
2015/08/31 13:22:24 Using configuration at: /opt/influxdb/config.toml
[metastore] 2015/08/31 13:22:24 Using data dir: /var/opt/influxdb/meta
[metastore] 2015/08/31 13:22:24 Node at localhost:8088 [Follower]
[metastore] 2015/08/31 13:22:25 Skipping cluster join: already member of cluster: nodeId=1 raftEnabled=true peers=[localhost:8088]
[store] 2015/08/31 13:22:25 Using data dir: /var/opt/influxdb/data
[wal] 2015/08/31 13:22:25 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/08/31 13:22:25 WAL writing to /var/opt/influxdb/wal/telegraf/default/1
[metastore] 2015/08/31 13:22:27 Node at localhost:8088 [Leader]. peers=[localhost:8088]
[metastore] 2015/08/31 13:22:27 Updated node id=1 hostname=localhost:8088
runtime: memory allocated by OS (2942005248) not in usable range [0x18c00000,0x98c00000)
fatal error: out of memory

runtime stack:
runtime.throw(0x8667810, 0xd)
        /usr/local/go/src/runtime/panic.go:527 +0x7f
runtime.largeAlloc(0x78000, 0x0, 0x0)
        /usr/local/go/src/runtime/malloc.go:747 +0xc3
runtime.mallocgc.func3()
        /usr/local/go/src/runtime/malloc.go:634 +0x30
runtime.systemstack(0x18c1aa00)
        /usr/local/go/src/runtime/asm_386.s:267 +0x57
runtime.mstart()
        /usr/local/go/src/runtime/proc1.go:674

goroutine 38 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_386.s:222 fp=0x1cefcd78 sp=0x1cefcd74
runtime.mallocgc(0x78000, 0x84f3600, 0x0, 0x6880c3c0)
        /usr/local/go/src/runtime/malloc.go:635 +0x77f fp=0x1cefcde0 sp=0x1cefcd78
runtime.newarray(0x84f3600, 0xa000, 0x1)
        /usr/local/go/src/runtime/malloc.go:777 +0xbc fp=0x1cefce04 sp=0x1cefcde0
runtime.growslice(0x84efa00, 0x76c70000, 0x8000, 0x8000, 0x8001, 0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/slice.go:97 +0x259 fp=0x1cefce44 sp=0x1cefce04
github.com/influxdb/influxdb/tsdb/engine/wal.(*Partition).addToCache(0x18e95340, 0x3df95e61, 0x59, 0x1c15, 0x3df95eba, 0x9, 0x1bbc, 0x85ba6994, 0x13fef7fd)
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:1359 +0x593 fp=0x1cefcf14 sp=0x1cefce44
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).openPartitionFiles.func1(0x18e61140, 0x18e95340)
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:523 +0x352 fp=0x1cefcfd0 sp=0x1cefcf14
runtime.goexit()
        /usr/local/go/src/runtime/asm_386.s:1662 +0x1 fp=0x1cefcfd4 sp=0x1cefcfd0
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).openPartitionFiles
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:527 +0xb9

goroutine 1 [chan receive, 2 minutes]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).openPartitionFiles(0x18c6a780, 0x0, 0x0)
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:531 +0x10e
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open(0x18c6a780, 0x0, 0x0)
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:210 +0x534
github.com/influxdb/influxdb/tsdb/engine/bz1.(*Engine).LoadMetadataIndex(0x18d09d60, 0x18d0e810, 0x18d09c00, 0x0, 0x0)
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/tsdb/engine/bz1/bz1.go:203 +0xe2
github.com/influxdb/influxdb/tsdb.(*Shard).Open.func1(0x18c84630, 0x0, 0x0)
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/tsdb/shard.go:103 +0x447
github.com/influxdb/influxdb/tsdb.(*Shard).Open(0x18c84630, 0x0, 0x0)
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/tsdb/shard.go:75 +0x2b
github.com/influxdb/influxdb/tsdb.(*Store).loadShards(0x18c5b950, 0x0, 0x0)
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/tsdb/store.go:257 +0xc97
github.com/influxdb/influxdb/tsdb.(*Store).Open(0x18c5b950, 0x0, 0x0)
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/tsdb/store.go:288 +0x261
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1(0x18cc2fc0, 0x0, 0x0)
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:325 +0xa60
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open(0x18cc2fc0, 0x0, 0x0)
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:276 +0x2b
github.com/influxdb/influxdb/cmd/influxd/run.(*Command).Run(0x18c16f40, 0x18c0a208, 0x2, 0x3, 0x0, 0x0)
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:113 +0xaf5
main.(*Main).Run(0x18c45f88, 0x18c0a208, 0x2, 0x3, 0x0, 0x0)
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/cmd/influxd/main.go:81 +0x56e
main.main()
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/cmd/influxd/main.go:42 +0x243

goroutine 17 [syscall, 2 minutes, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_386.s:1662 +0x1

goroutine 5 [syscall, 2 minutes]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x1a
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x36

goroutine 8 [IO wait, 2 minutes]:
net.runtime_pollWait(0xb6bcae00, 0x72, 0x18ce60e0)
        /usr/local/go/src/runtime/netpoll.go:157 +0x55
net.(*pollDesc).Wait(0x18c17c78, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x35
net.(*pollDesc).WaitRead(0x18c17c78, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x33
net.(*netFD).accept(0x18c17c40, 0x0, 0xb5b83050, 0x18ce60f0)
        /usr/local/go/src/net/fd_unix.go:408 +0x20b
net.(*TCPListener).AcceptTCP(0x18d066e8, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:254 +0x47
net.(*TCPListener).Accept(0x18d066e8, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:264 +0x39
github.com/influxdb/influxdb/tcp.(*Mux).Serve(0x18d09040, 0xb6bc9e40, 0x18d066e8, 0x0, 0x0)
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/tcp/mux.go:45 +0x64
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:313 +0x8df

goroutine 9 [chan receive, 2 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0x18d066f0, 0x0, 0x0, 0x0, 0x0)
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x59
github.com/influxdb/influxdb/meta.(*raftLayer).Accept(0x18d09160, 0x0, 0x0, 0x0, 0x0)
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/meta/store.go:2058 +0x47
github.com/hashicorp/raft.(*NetworkTransport).listen(0x18c12a00)
        /home/bbigras/influxdb/src/github.com/hashicorp/raft/net_transport.go:346 +0x56
created by github.com/hashicorp/raft.NewNetworkTransport
        /home/bbigras/influxdb/src/github.com/hashicorp/raft/net_transport.go:138 +0x219

goroutine 10 [select]:
github.com/hashicorp/raft.(*Raft).leaderLoop(0x18c80d80)
        /home/bbigras/influxdb/src/github.com/hashicorp/raft/raft.go:826 +0xac3
github.com/hashicorp/raft.(*Raft).runLeader(0x18c80d80)
        /home/bbigras/influxdb/src/github.com/hashicorp/raft/raft.go:798 +0x76b
github.com/hashicorp/raft.(*Raft).run(0x18c80d80)
        /home/bbigras/influxdb/src/github.com/hashicorp/raft/raft.go:595 +0xa8
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.run)-fm()
        /home/bbigras/influxdb/src/github.com/hashicorp/raft/raft.go:245 +0x20
github.com/hashicorp/raft.(*raftState).goFunc.func1(0x18c80d80, 0x18d067f8)
        /home/bbigras/influxdb/src/github.com/hashicorp/raft/state.go:152 +0x3f
created by github.com/hashicorp/raft.(*raftState).goFunc
        /home/bbigras/influxdb/src/github.com/hashicorp/raft/state.go:153 +0x46

goroutine 11 [select, 2 minutes]:
github.com/hashicorp/raft.(*Raft).runFSM(0x18c80d80)
        /home/bbigras/influxdb/src/github.com/hashicorp/raft/raft.go:502 +0xeb2
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.runFSM)-fm()
        /home/bbigras/influxdb/src/github.com/hashicorp/raft/raft.go:246 +0x20
github.com/hashicorp/raft.(*raftState).goFunc.func1(0x18c80d80, 0x18d06800)
        /home/bbigras/influxdb/src/github.com/hashicorp/raft/state.go:152 +0x3f
created by github.com/hashicorp/raft.(*raftState).goFunc
        /home/bbigras/influxdb/src/github.com/hashicorp/raft/state.go:153 +0x46

goroutine 12 [select, 2 minutes]:
github.com/hashicorp/raft.(*Raft).runSnapshots(0x18c80d80)
        /home/bbigras/influxdb/src/github.com/hashicorp/raft/raft.go:1613 +0x394
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.runSnapshots)-fm()
        /home/bbigras/influxdb/src/github.com/hashicorp/raft/raft.go:247 +0x20
github.com/hashicorp/raft.(*raftState).goFunc.func1(0x18c80d80, 0x18d06808)
        /home/bbigras/influxdb/src/github.com/hashicorp/raft/state.go:152 +0x3f
created by github.com/hashicorp/raft.(*raftState).goFunc
        /home/bbigras/influxdb/src/github.com/hashicorp/raft/state.go:153 +0x46

goroutine 13 [select, 2 minutes]:
github.com/influxdb/influxdb/meta.(*localRaft).logLeaderChanges(0x18d0e2d0)
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/meta/state.go:187 +0x3d3
created by github.com/influxdb/influxdb/meta.(*localRaft).open
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/meta/state.go:177 +0x106a

goroutine 14 [chan receive, 2 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0x18d066f8, 0x0, 0x0, 0x0, 0x0)
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x59
github.com/influxdb/influxdb/meta.(*Store).serveExecListener(0x18c7c300)
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/meta/store.go:619 +0x7f
created by github.com/influxdb/influxdb/meta.(*Store).Open
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/meta/store.go:239 +0x26d

goroutine 15 [chan receive, 2 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0x18d06700, 0x0, 0x0, 0x0, 0x0)
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x59
github.com/influxdb/influxdb/meta.(*Store).serveRPCListener(0x18c7c300)
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/meta/store.go:723 +0x82
created by github.com/influxdb/influxdb/meta.(*Store).Open
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/meta/store.go:242 +0x2ac

goroutine 34 [select, 2 minutes]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).monitorErrorChan(0x18cc2fc0, 0x18c17880)
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:442 +0x121
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:319 +0xa29

goroutine 35 [runnable]:
syscall.Syscall(0x3, 0x1a, 0x18d326f0, 0x8, 0x8, 0x8, 0x0)
        /usr/local/go/src/syscall/asm_linux_386.s:16 +0x5
syscall.read(0x1a, 0x18d326f0, 0x8, 0x8, 0x18, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_linux_386.go:783 +0x4f
syscall.Read(0x1a, 0x18d326f0, 0x8, 0x8, 0x87423e4, 0x0, 0x0)
        /usr/local/go/src/syscall/syscall_unix.go:160 +0x45
os.(*File).read(0x77955588, 0x18d326f0, 0x8, 0x8, 0x0, 0x0, 0x0)
        /usr/local/go/src/os/file_unix.go:211 +0x4a
os.(*File).Read(0x77955588, 0x18d326f0, 0x8, 0x8, 0x0, 0x0, 0x0)
        /usr/local/go/src/os/file.go:95 +0x6f
github.com/influxdb/influxdb/tsdb/engine/wal.(*segment).readCompressedBlock(0x1cf00ee8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:1478 +0x99
github.com/influxdb/influxdb/tsdb/engine/wal.(*Partition).readFile(0x18e951e0, 0x18cefc40, 0x36, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:1311 +0x1bb
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).openPartitionFiles.func1(0x18e61140, 0x18e951e0)
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:517 +0x26c
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).openPartitionFiles
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:527 +0xb9

goroutine 36 [runnable]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*segment).readCompressedBlock(0x18c36ee8, 0x0, 0x0, 0x3b7c08c0, 0x8, 0x8, 0x0, 0x0)
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:1558 +0x18f3
github.com/influxdb/influxdb/tsdb/engine/wal.(*Partition).readFile(0x18e95290, 0x18efcbc0, 0x36, 0x69df4000, 0x381c, 0x4800, 0x0, 0x0)
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:1311 +0x1bb
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).openPartitionFiles.func1(0x18e61140, 0x18e95290)
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:517 +0x26c
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).openPartitionFiles
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:527 +0xb9

goroutine 39 [runnable]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Partition).addToCache(0x18e953f0, 0x667f3e55, 0x6e, 0xab8, 0x667f3ec3, 0x9, 0xa4a, 0x4d30dfa1, 0x13ff14bd)
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:1338
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).openPartitionFiles.func1(0x18e61140, 0x18e953f0)
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:523 +0x352
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).openPartitionFiles
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:527 +0xb9

goroutine 40 [runnable]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*segment).readCompressedBlock(0x18c30ee8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:1551 +0x13ba
github.com/influxdb/influxdb/tsdb/engine/wal.(*Partition).readFile(0x18e954a0, 0x18ef9c40, 0x36, 0x39508000, 0xc58f, 0xf000, 0x0, 0x0)
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:1311 +0x1bb
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).openPartitionFiles.func1(0x18e61140, 0x18e954a0)
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:517 +0x26c
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).openPartitionFiles
        /home/bbigras/influxdb/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:527 +0xb9
```

I'm using a new database with telegraf since a couple of days ago.

```
sudo du -h /var/opt/influxdb
4,0K    /var/opt/influxdb/meta/snapshots
96K     /var/opt/influxdb/meta
624M    /var/opt/influxdb/wal/telegraf/default/1
16M     /var/opt/influxdb/wal/telegraf/default/2
640M    /var/opt/influxdb/wal/telegraf/default
640M    /var/opt/influxdb/wal/telegraf
640M    /var/opt/influxdb/wal
11M     /var/opt/influxdb/data/telegraf/default
11M     /var/opt/influxdb/data/telegraf
11M     /var/opt/influxdb/data
4,0K    /var/opt/influxdb/hh
8,0K    /var/opt/influxdb/run
650M    /var/opt/influxdb
```

influxdb 2de059c663a971e078df733096f7dadbae1e357b
go version go1.5 linux/386

**Comment by beckettsean** [comment]
@brunoqc Are you running InfluxDB on a 32-bit system?

**Comment by brunoqc** [comment]
Yes.

**Comment by beckettsean** [comment]
@benbjohnson @DanielMorsing another 32-bit RAM issue

**Comment by benbjohnson** [comment]
@beckettsean There's going to be a file size limit on 32-bit architectures because Bolt is mmap'd and we only have so much virtual space. Anything larger than 2GB is probably going to fail to allocate an mmap large enough.

**Comment by beckettsean** [comment]
@benbjohnson I understand we have architectural limits, I just hope we can handle them more gracefully than a panic at startup. Are we working on enforcing or at least communicating those file limits?

Is there any way for this user to recover their database or is it just hosed now with a BoltDB file that's too big for the environment?

**Comment by jwilder** [comment]
This is an issue related to `bz1` engine which is deprecated and has been replaced by the `tsm` engine in `0.10.0`.  There is a [conversion tool](https://github.com/influxdata/influxdb/tree/master/cmd/influx_tsm) that can be used to convert `b1` and `bz1` shards to `tsm` format for use in `0.10.0`.   Unfortunately, there isn't anything we can do about this specific panic now.  If you still see this in `0.10.0`, please open a new issue.
