### ISSUE TITLE
[0.9.3, 0.9.4-nightly-d6cb017] Panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by olivierHa** [influxdata/influxdb#3921]
Hello, 

I had memory/cpu issues while running influxdb0.9.3, it got killed by OOM. Now on startup, it crashes with a panic error. I decided to test the nightly build, same result : 

Here is the full stackstrace :
```
2015/09/01 14:12:22 InfluxDB starting, version 0.9.4-nightly-d6cb017, branch master, commit d6cb01722b2f618af84cb9633bd1fb2efb668a8d
2015/09/01 14:12:22 Go version go1.5, GOMAXPROCS set to 8
2015/09/01 14:12:22 Using configuration at: /etc/opt/influxdb/influxdb.conf
[metastore] 2015/09/01 14:12:22 Using data dir: /data/influxdb/meta
[metastore] 2015/09/01 14:12:22 Skipping cluster join: already member of cluster: nodeId=1 raftEnabled=true peers=[localhost:8088]
[store] 2015/09/01 14:12:22 Using data dir: /data/influxdb/data
[metastore] 2015/09/01 14:12:22 Node at localhost:8088 [Follower]
[metastore] 2015/09/01 14:12:24 Node at localhost:8088 [Leader]. peers=[localhost:8088]
[metastore] 2015/09/01 14:12:24 Node at localhost:8088 [Follower]. peers=[localhost:8088]
[metastore] 2015/09/01 14:12:24 Updated node id=1 hostname=localhost:8088
[wal] 2015/09/01 14:12:25 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/09/01 14:12:25 WAL writing to /data/influxdb/wal/graphite/1week/62
[metastore] 2015/09/01 14:12:25 Node at localhost:8088 [Leader]. peers=[localhost:8088]
[wal] 2015/09/01 14:12:26 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/09/01 14:12:26 WAL writing to /data/influxdb/wal/graphite/1week/64
[wal] 2015/09/01 14:12:27 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/09/01 14:12:27 WAL writing to /data/influxdb/wal/graphite/1week/66
[wal] 2015/09/01 14:12:28 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/09/01 14:12:28 WAL writing to /data/influxdb/wal/graphite/1week/68
[wal] 2015/09/01 14:12:32 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/09/01 14:12:32 WAL writing to /data/influxdb/wal/graphite/1week/70
panic: assignment to entry in nil map

goroutine 48 [running]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Partition).addToCache(0xc889be0f00, 0xc88b334410, 0x9a, 0x3bc, 0xc88b3344aa, 0x9, 0x322, 0x13ffb1c774eac800)
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:1350 +0x492
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).openPartitionFiles.func1(0xc86d3715c0, 0xc889be0f00)
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:523 +0x42d
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).openPartitionFiles
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:527 +0xea

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc889be101c)
	/root/.gvm/gos/go1.5/src/runtime/sema.go:43 +0x26
sync.(*Mutex).Lock(0xc889be1018)
	/root/.gvm/gos/go1.5/src/sync/mutex.go:82 +0x1c4
sync.(*RWMutex).Lock(0xc889be1018)
	/root/.gvm/gos/go1.5/src/sync/rwmutex.go:82 +0x30
github.com/influxdb/influxdb/tsdb/engine/wal.(*Partition).Close(0xc889be1000, 0x0, 0x0)
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:792 +0x41
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).close(0xc88a227790, 0x0, 0x0)
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:569 +0xc3
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Close(0xc88a227790, 0x0, 0x0)
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:558 +0x105
github.com/influxdb/influxdb/tsdb/engine/bz1.(*Engine).Close(0xc88a23e040, 0x0, 0x0)
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/tsdb/engine/bz1/bz1.go:140 +0x9e
github.com/influxdb/influxdb/tsdb.(*Shard).close(0xc829738360, 0x0, 0x0)
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/tsdb/shard.go:125 +0x4a
github.com/influxdb/influxdb/tsdb.(*Shard).Open(0xc829738360, 0x0, 0x0)
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/tsdb/shard.go:109 +0x55
github.com/influxdb/influxdb/tsdb.(*Store).loadShards(0xc82012c820, 0x0, 0x0)
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/tsdb/store.go:257 +0xebd
github.com/influxdb/influxdb/tsdb.(*Store).Open(0xc82012c820, 0x0, 0x0)
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/tsdb/store.go:288 +0x316
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1(0xc820140380, 0x0, 0x0)
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:325 +0xc45
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open(0xc820140380, 0x0, 0x0)
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:276 +0x2d
github.com/influxdb/influxdb/cmd/influxd/run.(*Command).Run(0xc82012a180, 0xc82000a0b0, 0x4, 0x4, 0x0, 0x0)
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:113 +0xd0c
main.(*Main).Run(0xc820113f00, 0xc82000a0b0, 0x4, 0x4, 0x0, 0x0)
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/cmd/influxd/main.go:81 +0x67e
main.main()
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/cmd/influxd/main.go:42 +0x29b

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/root/.gvm/gos/go1.5/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
	/root/.gvm/gos/go1.5/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/root/.gvm/gos/go1.5/src/os/signal/signal_unix.go:28 +0x37

goroutine 19 [IO wait]:
net.runtime_pollWait(0x7f822d8bb0c8, 0x72, 0xc82000e180)
	/root/.gvm/gos/go1.5/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82013ab50, 0x72, 0x0, 0x0)
	/root/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82013ab50, 0x0, 0x0)
	/root/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc82013aaf0, 0x0, 0x7f82301426b0, 0xc8293aa000)
	/root/.gvm/gos/go1.5/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc82012e160, 0x9888a0, 0x0, 0x0)
	/root/.gvm/gos/go1.5/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc82012e160, 0x0, 0x0, 0x0, 0x0)
	/root/.gvm/gos/go1.5/src/net/tcpsock_posix.go:264 +0x3d
github.com/influxdb/influxdb/tcp.(*Mux).Serve(0xc8201a4150, 0x7f822d8bb250, 0xc82012e160, 0x0, 0x0)
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/tcp/mux.go:45 +0x5d
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:313 +0xa81

goroutine 20 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc82012e168, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x6f
github.com/influxdb/influxdb/meta.(*raftLayer).Accept(0xc8201a4210, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/meta/store.go:2058 +0x51
github.com/hashicorp/raft.(*NetworkTransport).listen(0xc82013abd0)
	/tmp/tmp.GidTHqyWFj/src/github.com/hashicorp/raft/net_transport.go:346 +0x79
created by github.com/hashicorp/raft.NewNetworkTransport
	/tmp/tmp.GidTHqyWFj/src/github.com/hashicorp/raft/net_transport.go:138 +0x284

goroutine 21 [select]:
github.com/hashicorp/raft.(*Raft).leaderLoop(0xc8201ae000)
	/tmp/tmp.GidTHqyWFj/src/github.com/hashicorp/raft/raft.go:826 +0xcce
github.com/hashicorp/raft.(*Raft).runLeader(0xc8201ae000)
	/tmp/tmp.GidTHqyWFj/src/github.com/hashicorp/raft/raft.go:798 +0x88e
github.com/hashicorp/raft.(*Raft).run(0xc8201ae000)
	/tmp/tmp.GidTHqyWFj/src/github.com/hashicorp/raft/raft.go:595 +0xbb
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.run)-fm()
	/tmp/tmp.GidTHqyWFj/src/github.com/hashicorp/raft/raft.go:245 +0x20
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc8201ae000, 0xc820199410)
	/tmp/tmp.GidTHqyWFj/src/github.com/hashicorp/raft/state.go:152 +0x44
created by github.com/hashicorp/raft.(*raftState).goFunc
	/tmp/tmp.GidTHqyWFj/src/github.com/hashicorp/raft/state.go:153 +0x4d

goroutine 22 [select]:
github.com/hashicorp/raft.(*Raft).runFSM(0xc8201ae000)
	/tmp/tmp.GidTHqyWFj/src/github.com/hashicorp/raft/raft.go:502 +0x10eb
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.runFSM)-fm()
	/tmp/tmp.GidTHqyWFj/src/github.com/hashicorp/raft/raft.go:246 +0x20
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc8201ae000, 0xc820199420)
	/tmp/tmp.GidTHqyWFj/src/github.com/hashicorp/raft/state.go:152 +0x44
created by github.com/hashicorp/raft.(*raftState).goFunc
	/tmp/tmp.GidTHqyWFj/src/github.com/hashicorp/raft/state.go:153 +0x4d

goroutine 23 [select]:
github.com/hashicorp/raft.(*Raft).runSnapshots(0xc8201ae000)
	/tmp/tmp.GidTHqyWFj/src/github.com/hashicorp/raft/raft.go:1613 +0x493
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.runSnapshots)-fm()
	/tmp/tmp.GidTHqyWFj/src/github.com/hashicorp/raft/raft.go:247 +0x20
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc8201ae000, 0xc820199430)
	/tmp/tmp.GidTHqyWFj/src/github.com/hashicorp/raft/state.go:152 +0x44
created by github.com/hashicorp/raft.(*raftState).goFunc
	/tmp/tmp.GidTHqyWFj/src/github.com/hashicorp/raft/state.go:153 +0x4d

goroutine 24 [select]:
github.com/influxdb/influxdb/meta.(*localRaft).logLeaderChanges(0xc820131450)
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/meta/state.go:187 +0x4f5
created by github.com/influxdb/influxdb/meta.(*localRaft).open
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/meta/state.go:177 +0x1344

goroutine 25 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc82012e170, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x6f
github.com/influxdb/influxdb/meta.(*Store).serveExecListener(0xc82013e280)
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/meta/store.go:619 +0xa2
created by github.com/influxdb/influxdb/meta.(*Store).Open
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/meta/store.go:239 +0x364

goroutine 26 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc82012e178, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x6f
github.com/influxdb/influxdb/meta.(*Store).serveRPCListener(0xc82013e280)
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/meta/store.go:723 +0xa2
created by github.com/influxdb/influxdb/meta.(*Store).Open
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/meta/store.go:242 +0x3b6

goroutine 28 [select]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).monitorErrorChan(0xc820140380, 0xc820132a20)
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:442 +0x145
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:319 +0xbff

goroutine 29 [select]:
github.com/influxdb/influxdb/tsdb/engine/b1.(*Engine).autoflusher(0xc82013d5e0, 0xc82028aa80)
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/tsdb/engine/b1/b1.go:469 +0x3c7
created by github.com/influxdb/influxdb/tsdb/engine/b1.(*Engine).Open.func1
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/tsdb/engine/b1/b1.go:134 +0x461

goroutine 55 [select]:
github.com/influxdb/influxdb/tsdb/engine/b1.(*Engine).autoflusher(0xc8208955e0, 0xc8209b2f60)
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/tsdb/engine/b1/b1.go:469 +0x3c7
created by github.com/influxdb/influxdb/tsdb/engine/b1.(*Engine).Open.func1
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/tsdb/engine/b1/b1.go:134 +0x461

goroutine 35 [select]:
github.com/influxdb/influxdb/tsdb/engine/b1.(*Engine).autoflusher(0xc820c660a0, 0xc820aaf2c0)
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/tsdb/engine/b1/b1.go:469 +0x3c7
created by github.com/influxdb/influxdb/tsdb/engine/b1.(*Engine).Open.func1
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/tsdb/engine/b1/b1.go:134 +0x461

goroutine 7 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc82f696750, 0xc8273178c0)
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:605 +0x567
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:219 +0x6bf

goroutine 119 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc82583e340, 0xc82f859ec0)
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:605 +0x567
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:219 +0x6bf

goroutine 44 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc821550b60, 0xc86dec5320)
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:605 +0x567
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:219 +0x6bf

goroutine 103 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc82720b790, 0xc8209b2b40)
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:605 +0x567
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:219 +0x6bf

goroutine 49 [runnable]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Partition).addToCache(0xc889be1000, 0xc88a8c228e, 0x95, 0x50e, 0xc88a8c2323, 0x9, 0x479, 0x13ffb30bca2ff200)
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:1342 +0x2ec
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).openPartitionFiles.func1(0xc86d3715c0, 0xc889be1000)
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:523 +0x42d
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).openPartitionFiles
	/tmp/tmp.GidTHqyWFj/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:527 +0xea
```

Regards

Olivier

**Comment by beckettsean** [comment]
@olivierHa In order to investigate we need a copy of your data. Can you make a gzipped tarball of the entire InfluxDB directory, including `/data`, `/wal`, and `/meta`?

**Comment by olivierHa** [comment]
I've sorry, I can't. To be able to get my cluster online, I had to delete the whole content of the /wal directory.

**Comment by beckettsean** [comment]
@olivierHa okay, thanks for looking. We haven't been able to repro this locally, has it happened to you again?

**Comment by olivierHa** [comment]
not yet, I am fighting with the memory issue right now.
Maybe next time,oom will kill the influxdb process :(
Then I will keep my /wal directory :D

2015-09-03 20:48 GMT+02:00 Sean Beckett <notifications@github.com>:

**Comment by beckettsean** [comment]
Thanks for continuing to test the database, @olivierHa, and we hope to have some fixes for OOM in the RC landing tomorrow.

**Comment by joakimberglund** [comment]
@beckettsean Just had exactly the same problem as @olivierHa 

Tried uppgrading to latest 0.9.4-nightly, before doing anything else.. no luck though, had to rm -rf two of the databases in the wal directory to get it going again.
(sadly I can't (aren't allowed) upload more info on it, like logs)

Will get back if the problem returns

**Comment by jwilder** [comment]
Closing since this is related to b1 storage engine which is no longer maintained.
