### ISSUE TITLE
[0.9.3-rc1] Runs out of fd:s, memory when importing a smallish dataset (Solaris, though)

### ISSUE THREAD

**Issue by calmh** [influxdata/influxdb#3971]
Hi,

I'm attempting to run InfluxDB (v0.9.3-rc1-262-gc1d2f11, current master) on Solaris - more specifically SmartOS. I compiled from source using Go 1.5, and things seem mostly fine. However, when importing data from my older InfluxDB 0.8 instance (massaged into new format and schema, in batches of 4000 rows), I run into an open file limit. The Solaris default open file limit is 65536. I understand that an arbitrarily low limit can be a problem, but should this not be enough? Running pfiles on the process shows the fd:s are essentially all used by database files;

```
jb@zlogin4:~ $ pfiles 42089
42089:  ./src/github.com/influxdb/influxdb/influxd -config influxcfg.toml -hos
  Current rlimit: 65536 file descriptors
   0: S_IFCHR mode:0620 dev:552,14 ino:634994901 uid:502 gid:7 rdev:6,2
      O_RDWR|O_NOCTTY|O_LARGEFILE
      /dev/pts/2
      offset:34625624
   1: S_IFIFO mode:0000 dev:549,0 ino:1026307 uid:502 gid:1 rdev:0,0
      O_RDWR
   2: S_IFIFO mode:0000 dev:549,0 ino:1026307 uid:502 gid:1 rdev:0,0
      O_RDWR
   3: S_IFCHR mode:0644 dev:552,14 ino:634993196 uid:0 gid:3 rdev:49,1
      O_RDONLY|O_LARGEFILE FD_CLOEXEC
      /dev/urandom
      offset:16
   5: S_IFPORT mode:0000 dev:563,0 uid:502 gid:1 size:0
   6: S_IFREG mode:0600 dev:90,65551 ino:212383 uid:502 gid:1 size:4194304
      O_RDWR|O_CREAT|O_LARGEFILE FD_CLOEXEC
      /var/opt/influxdb/meta/raft.db
      offset:0
   7: S_IFREG mode:0644 dev:90,65551 ino:212604 uid:502 gid:1 size:32768
      O_RDWR|O_CREAT|O_LARGEFILE FD_CLOEXEC
      /var/opt/influxdb/data/env/default/1
      offset:0
   8: S_IFREG mode:0644 dev:90,65551 ino:231106 uid:502 gid:1 size:0
      O_RDWR|O_CREAT|O_LARGEFILE FD_CLOEXEC
      /var/opt/influxdb/wal/env/default/1/000000.meta
      offset:0
   9: S_IFREG mode:0644 dev:90,65551 ino:212608 uid:502 gid:1 size:138
      O_RDWR|O_CREAT|O_LARGEFILE FD_CLOEXEC
      /var/opt/influxdb/wal/env/default/1/03.000001.wal
      offset:138
...
32700: S_IFREG mode:0644 dev:90,65551 ino:151286 uid:502 gid:1 size:32768
      O_RDWR|O_CREAT|O_LARGEFILE FD_CLOEXEC
      /var/opt/influxdb/data/env/default/4088
      offset:0
32701: S_IFREG mode:0644 dev:90,65551 ino:151527 uid:502 gid:1 size:62
      O_RDWR|O_CREAT|O_LARGEFILE FD_CLOEXEC
      /var/opt/influxdb/wal/env/default/4087/05.000001.wal
      offset:62
...
65534: S_IFREG mode:0644 dev:90,65551 ino:205032 uid:502 gid:1 size:63
      O_RDWR|O_CREAT|O_LARGEFILE FD_CLOEXEC
      /var/opt/influxdb/wal/env/default/9999/01.000001.wal
      offset:63
65535: S_IFREG mode:0644 dev:90,65551 ino:205030 uid:502 gid:1 size:139
      O_RDWR|O_CREAT|O_LARGEFILE FD_CLOEXEC
      /var/opt/influxdb/wal/env/default/9999/03.000001.wal
      offset:139
```

This is on a mostly default configuration (https://gist.github.com/faa0b0bff4efe1725b2f). Is there something obvious I should tweak to get the number of fd:s down to a more reasonable level?

**Comment by calmh** [comment]
Hmm, I can get past this by increasing the limit to a million fd:s, and perhaps that's by design so it's fine. Instead, I run out of memory some ways into the import when the influxd process hit's 16 GB (the limit of this container). I wonder what's going on here, as I'm trying to import about two million rows only, about 100 megs of data in text format, which should be much more verbose than the binary db format...?

**Comment by beckettsean** [comment]
@calmh I don't know the answer to the file descriptor question. @benbjohnson or @dgnorton any thoughts?

As for the import performance, are you pushing points as fast as possible? It's possible you are filling the WAL and then getting into RAM thrashing as it tries to drain. There are a number of OOM issues open and most a related to high sustained write volume. Dropping to a lower write speed, perhaps 1/3 of the maximum, often helps.

**Comment by benbjohnson** [comment]
It sounds like there's a lot of shards being created. I'm going to merge the [`SHOW SHARDS` PR](https://github.com/influxdb/influxdb/pull/3815) in so we can get visibility into the issue. It'll be available in the nightly.

**Comment by beckettsean** [comment]
@calmh can you pick up the next nightly build and try again? Nightly builds are available by 1 a.m. PDT each night.

```
wget https://s3.amazonaws.com/influxdb/influxdb-nightly-1.x86_64.rpm
sudo yum localinstall influxdb-nightly-1.x86_64.rpm
```

**Comment by calmh** [comment]
I was doing the import by looping over a number of files each containing 4000 rows, sleeping for a few seconds between each POST. That may not have been enough. When the actual out of memory crash comes, the backtrace shows hundreds of thousands of goroutines doing compaction or something similar (from memory, if this is relevant I can capture the full trace next time).

So really, not importing at anything resembling max speed, and as noted the actual dataset is orders of magnitudes smaller than the amount of RAM it tries to allocate for it...

**Comment by calmh** [comment]
"show shards" on  just gives me "Query returned no results!" (on v0.9.3-rc1-289-g02e2ed8) (as opposed to an error before updating to the latest master).

**Comment by calmh** [comment]
However with the latest commit, and pausing five seconds between each imported chunk, there is some compaction activity in the logs. Also this sudden nil dereference:

```
[wal] 2015/09/04 17:57:42 write to index of partition 5 took 142.175µs
[wal] 2015/09/04 17:57:42 write to index of partition 1 took 138.643µs
[wal] 2015/09/04 17:57:42 compaction of partition 5 took 187.422µs
[wal] 2015/09/04 17:57:42 compaction of partition 1 took 190.743µs
2015/09/04 17:57:44 http: panic serving [2001:470:deeb:32::251]:50826: runtime error: invalid memory address or nil pointer dereference
goroutine 148485 [running]:
net/http.(*conn).serve.func1(0xc886041c30, 0xfffffd7ffeeff470, 0xc87070d0e0)
        /opt/local/go/src/net/http/server.go:1287 +0xb5
github.com/influxdb/influxdb/cluster.(*PointsWriter).MapShards(0xc8200aef50, 0xc9535e5d00, 0xc8cd6ff6e0, 0x0, 0x0)
        /home/jb/src/github.com/influxdb/influxdb/cluster/points_writer.go:177 +0x6b6
github.com/influxdb/influxdb/cluster.(*PointsWriter).WritePoints(0xc8200aef50, 0xc9535e5d00, 0x0, 0x0)
        /home/jb/src/github.com/influxdb/influxdb/cluster/points_writer.go:195 +0x16b
github.com/influxdb/influxdb/services/httpd.(*Handler).serveWriteLine(0xc820146310, 0xfffffd7ffe973810, 0xc95f893c00, 0xc9f323e2a0, 0xc8e33fa000, 0x2ace8, 0x3fe00, 0x0)
        /home/jb/src/github.com/influxdb/influxdb/services/httpd/handler.go:509 +0xeb0
github.com/influxdb/influxdb/services/httpd.(*Handler).serveWrite(0xc820146310, 0xfffffd7ffe973810, 0xc95f893c00, 0xc9f323e2a0, 0x0)
        /home/jb/src/github.com/influxdb/influxdb/services/httpd/handler.go:364 +0x722
github.com/influxdb/influxdb/services/httpd.(*Handler).(github.com/influxdb/influxdb/services/httpd.serveWrite)-fm(0xfffffd7ffe973810, 0xc95f893c00, 0xc9f323e2a0, 0x0)
        /home/jb/src/github.com/influxdb/influxdb/services/httpd/handler.go:104 +0x48
github.com/influxdb/influxdb/services/httpd.authenticate.func1(0xfffffd7ffe973810, 0xc95f893c00, 0xc9f323e2a0)
        /home/jb/src/github.com/influxdb/influxdb/services/httpd/handler.go:654 +0x70
net/http.HandlerFunc.ServeHTTP(0xc820148480, 0xfffffd7ffe973810, 0xc95f893c00, 0xc9f323e2a0)
        /opt/local/go/src/net/http/server.go:1422 +0x3a
github.com/influxdb/influxdb/services/httpd.gzipFilter.func1(0xfffffd7ffe973810, 0xc95f893c00, 0xc9f323e2a0)
        /home/jb/src/github.com/influxdb/influxdb/services/httpd/handler.go:705 +0xda
net/http.HandlerFunc.ServeHTTP(0xc8201484a0, 0xfffffd7ffe973810, 0xc95f893c00, 0xc9f323e2a0)
        /opt/local/go/src/net/http/server.go:1422 +0x3a
github.com/influxdb/influxdb/services/httpd.versionHeader.func1(0xfffffd7ffe973810, 0xc95f893c00, 0xc9f323e2a0)
        /home/jb/src/github.com/influxdb/influxdb/services/httpd/handler.go:721 +0xc0
net/http.HandlerFunc.ServeHTTP(0xc8201484c0, 0xfffffd7ffe973810, 0xc95f893c00, 0xc9f323e2a0)
        /opt/local/go/src/net/http/server.go:1422 +0x3a
github.com/influxdb/influxdb/services/httpd.cors.func1(0xfffffd7ffe973810, 0xc95f893c00, 0xc9f323e2a0)
        /home/jb/src/github.com/influxdb/influxdb/services/httpd/handler.go:754 +0x328
net/http.HandlerFunc.ServeHTTP(0xc8201484e0, 0xfffffd7ffe973810, 0xc95f893c00, 0xc9f323e2a0)
        /opt/local/go/src/net/http/server.go:1422 +0x3a
github.com/influxdb/influxdb/services/httpd.requestID.func1(0xfffffd7ffe973810, 0xc95f893c00, 0xc9f323e2a0)
        /home/jb/src/github.com/influxdb/influxdb/services/httpd/handler.go:764 +0x15d
net/http.HandlerFunc.ServeHTTP(0xc820148500, 0xfffffd7ffe973810, 0xc95f893c00, 0xc9f323e2a0)
        /opt/local/go/src/net/http/server.go:1422 +0x3a
github.com/influxdb/influxdb/services/httpd.logging.func1(0xfffffd7ffe973810, 0xc95f893be0, 0xc9f323e2a0)
        /home/jb/src/github.com/influxdb/influxdb/services/httpd/handler.go:772 +0x10b
net/http.HandlerFunc.ServeHTTP(0xc820148520, 0xfffffd7ffe973810, 0xc95f893be0, 0xc9f323e2a0)
        /opt/local/go/src/net/http/server.go:1422 +0x3a
github.com/influxdb/influxdb/services/httpd.recovery.func1(0xfffffd7ffe9737d8, 0xc886041ce0, 0xc9f323e2a0)
        /home/jb/src/github.com/influxdb/influxdb/services/httpd/handler.go:782 +0x114
net/http.HandlerFunc.ServeHTTP(0xc820148540, 0xfffffd7ffe9737d8, 0xc886041ce0, 0xc9f323e2a0)
        /opt/local/go/src/net/http/server.go:1422 +0x3a
github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc820132048, 0xfffffd7ffe9737d8, 0xc886041ce0, 0xc9f323e2a0)
        /home/jb/src/github.com/bmizerany/pat/mux.go:109 +0x244
github.com/influxdb/influxdb/services/httpd.(*Handler).ServeHTTP(0xc820146310, 0xfffffd7ffe9737d8, 0xc886041ce0, 0xc9f323e2a0)
        /home/jb/src/github.com/influxdb/influxdb/services/httpd/handler.go:168 +0x324
net/http.serverHandler.ServeHTTP(0xc8202a2000, 0xfffffd7ffe9737d8, 0xc886041ce0, 0xc9f323e2a0)
        /opt/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc886041c30)
        /opt/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
        /opt/local/go/src/net/http/server.go:1910 +0x3f6
[wal] 2015/09/04 17:57:49 Flush due to idle. Flushing 4 series with 8 points and 136 bytes from partition 3. Compacting 0 series
[wal] 2015/09/04 17:57:49 write to index of partition 3 took 2.684138ms
[wal] 2015/09/04 17:57:49 compaction of partition 3 took 342.783µs
```

**Comment by calmh** [comment]
Ran out of memory after importing about 300.000 k measurements, stopping the import to let it idle a while to see what happens (about 13 GB RSS at that point), then lots of flushes happning and crashed when reaching the limit of 16 GB. About 200k goroutines identical to this in the trace:

```
goroutine 203538 [select, 1 minutes]:
runtime.gopark(0xcff118, 0xc83a07fe98, 0xbbd388, 0x6, 0xc8c3c54318, 0x2)
        /opt/local/go/src/runtime/proc.go:185 +0x179 fp=0xc83a07fbf0 sp=0xc83a07fbc8
runtime.selectgoImpl(0xc83a07fe98, 0x0, 0x18)
        /opt/local/go/src/runtime/select.go:392 +0xa6d fp=0xc83a07fd98 sp=0xc83a07fbf0
runtime.selectgo(0xc83a07fe98)
        /opt/local/go/src/runtime/select.go:212 +0x12 fp=0xc83a07fdb8 sp=0xc83a07fd98
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc931c250a0, 0xc8b3a5ff20)
        /home/jb/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:606 +0x567 fp=0xc83a07ffa0 sp=0xc83a07fdb8
runtime.goexit()
        /opt/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc83a07ffa8 sp=0xc83a07ffa0
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
        /home/jb/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:220 +0x6bf
```

Am I doing something absurd by attempting to import data like this? What's the expected procedure here? The combined size of the uploaded measuerments is about 13 MB at the point of this crash...

**Comment by beckettsean** [comment]
@calmh We need to investigate the contents of your `/meta` directory to debug this further. Can you make a gzip of `/meta` and upload it via http://cwok.me/cu/3971?

**Comment by calmh** [comment]
Sure! I'll get you the data tomorrow.

**Comment by calmh** [comment]
https://nym.se/t/meta.tar.gz

**Comment by jwilder** [comment]
This is an issue related to `bz1` engine which is deprecated and has been replaced by the `tsm` engine in `0.10.0`.  There is a [conversion tool](https://github.com/influxdata/influxdb/tree/master/cmd/influx_tsm) that can be used to convert `b1` and `bz1` shards to `tsm` format for use in `0.10.0`.   Unfortunately, there isn't anything we can do about this specific now.  If you still see this in `0.10.0`, please open a new issue.
