### ISSUE TITLE
[0.9.3-final] process map shard error messages + i/o timeout messages in admin UI

### ISSUE THREAD

**Issue by ecables** [influxdata/influxdb#4012]
One of the nodes in our 3-node cluster appears to be having issues, as shown below. The network is not partitioned, and connectivity is clean to the reported node. 
```
[wal] 2015/09/04 18:52:58 Flushing 0 measurements and 61 series to index
[wal] 2015/09/04 18:53:03 Metadata flush took 5.277566477s
[tcp] 2015/09/04 18:53:30 accept remote write connection from 192.1.1.1:52774
[tcp] 2015/09/04 18:53:35 process map shard error: write message value: write tcp 192.1.1.1:52745: connection reset by peer
[tcp] 2015/09/04 18:53:35 process map shard error writing response: write message type: write tcp 192.1.1.1:52745: broken pipe
[tcp] 2015/09/04 18:53:35 process map shard error: write message type: write tcp 192.1.1.1:52745: broken pipe
[tcp] 2015/09/04 18:53:35 process map shard error writing response: write message type: write tcp 192.1.1.1:52745: broken pipe
[tcp] 2015/09/04 18:53:35 close remote write connection from 192.1.1.1:52745
[retention] 2015/09/04 18:53:47 retention policy shard deletion check commencing
[tcp] 2015/09/04 18:54:01 accept remote write connection from 192.1.1.1:52788
[tcp] 2015/09/04 18:54:01 process map shard error: write message size: write tcp 192.1.1.1:52774: connection reset by peer
[tcp] 2015/09/04 18:54:01 process map shard error writing response: write message type: write tcp 192.1.1.1:52774: broken pipe
[tcp] 2015/09/04 18:54:01 process map shard error: write message type: write tcp 192.1.1.1:52774: broken pipe
[tcp] 2015/09/04 18:54:01 process map shard error writing response: write message type: write tcp 192.1.1.1:52774: broken pipe
[tcp] 2015/09/04 18:54:01 close remote write connection from 192.1.1.1:52774
[tcp] 2015/09/04 18:54:01 accept remote write connection from 192.1.1.1:52790
[tcp] 2015/09/04 18:54:06 process map shard error: write message type: write tcp 192.1.1.1:52788: connection reset by peer
[tcp] 2015/09/04 18:54:06 process map shard error writing response: write message type: write tcp 192.1.1.1:52788: broken pipe
[tcp] 2015/09/04 18:54:06 close remote write connection from 192.1.1.1:52788
[tcp] 2015/09/04 18:54:06 process map shard error: write message value: write tcp 192.1.1.1:52790: connection reset by peer
[tcp] 2015/09/04 18:54:06 process map shard error writing response: write message type: write tcp 192.1.1.1:52790: broken pipe
[tcp] 2015/09/04 18:54:06 close remote write connection from 192.1.1.1:52790
```

When I run queries through the web UI I get the following error occasionally, which oscillates between the other two node IP addresses:
```
Server returned error: read message type: read tcp 192.1.1.1:8088: i/o timeout
```
Additionally, I'm seeing this panic, which may have led to the above issues:
```
2015/09/04 00:25:31 http: panic serving 192.168.1.9:19349: runtime error: index out of range
goroutine 581255 [running]:
net/http.func·011()
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1130 +0xbb
github.com/influxdb/influxdb/services/httpd.(*Handler).serveQuery(0xc2080102a0, 0x7f4497e3d008, 0xc2aff2e700, 0xc2e47fc1a0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:289 +0x16c6
github.com/influxdb/influxdb/services/httpd.*Handler.(github.com/influxdb/influxdb/services/httpd.serveQuery)·fm(0x7f4497e3d008, 0xc2aff2e700, 0xc2e47fc1a0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:95 +0x4f
github.com/influxdb/influxdb/services/httpd.func·001(0x7f4497e3d008, 0xc2aff2e700, 0xc2e47fc1a0)
        /root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:621 +0x78
net/http.HandlerFunc.ServeHTTP(0xc2081711e0, 0x7f4497e3d008, 0xc2aff2e700, 0xc2e47fc1a0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/services/httpd.func·002(0x7f4497e3cf30, 0xc2aff2e580, 0xc2e47fc1a0)
        /root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:679 +0x288
net/http.HandlerFunc.ServeHTTP(0xc2080e2130, 0x7f4497e3cf30, 0xc2aff2e580, 0xc2e47fc1a0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/services/httpd.func·003(0x7f4497e3cf30, 0xc2aff2e580, 0xc2e47fc1a0)
        /root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:688 +0xba
net/http.HandlerFunc.ServeHTTP(0xc208171200, 0x7f4497e3cf30, 0xc2aff2e580, 0xc2e47fc1a0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/services/httpd.func·004(0x7f4497e3cf30, 0xc2aff2e580, 0xc2e47fc1a0)
        /root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:721 +0x31a
net/http.HandlerFunc.ServeHTTP(0xc2080e2160, 0x7f4497e3cf30, 0xc2aff2e580, 0xc2e47fc1a0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/services/httpd.func·005(0x7f4497e3cf30, 0xc2aff2e580, 0xc2e47fc1a0)
        /root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:731 +0x179
net/http.HandlerFunc.ServeHTTP(0xc2080e2180, 0x7f4497e3cf30, 0xc2aff2e580, 0xc2e47fc1a0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/services/httpd.func·006(0x7f4497e3cf30, 0xc2aff2e560, 0xc2e47fc1a0)
        /root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:739 +0x123
net/http.HandlerFunc.ServeHTTP(0xc208171220, 0x7f4497e3cf30, 0xc2aff2e560, 0xc2e47fc1a0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/services/httpd.func·007(0x7f4497e3cef8, 0xc3210461e0, 0xc2e47fc1a0)
        /root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:749 +0x12c
net/http.HandlerFunc.ServeHTTP(0xc208171240, 0x7f4497e3cef8, 0xc3210461e0, 0xc2e47fc1a0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc208037ee0, 0x7f4497e3cef8, 0xc3210461e0, 0xc2e47fc1a0)
        /root/go/src/github.com/bmizerany/pat/mux.go:109 +0x21c
github.com/influxdb/influxdb/services/httpd.(*Handler).ServeHTTP(0xc2080102a0, 0x7f4497e3cef8, 0xc3210461e0, 0xc2e47fc1a0)
        /root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:167 +0x256
net/http.serverHandler.ServeHTTP(0xc23b56c060, 0x7f4497e3cef8, 0xc3210461e0, 0xc2e47fc1a0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2080586e0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1751 +0x35e
```

**Comment by ecables** [comment]
Restarting this node resolved the above problem.
