### ISSUE TITLE
Table/Points not deleted when we drop database

### ISSUE THREAD

**Issue by william-p** [influxdata/influxdb#41]
Hi guys,
i have a issue when i use Python driver (https://github.com/influxdb/influxdb-python) but i think it's core issue.

How to reproduce:
- create database and add correct rights
- add points
- query points (it's okay)
- delete database
- query points (no point, okay)
- recreate database
- query point, server return old points :confused:

Interactive Python

```
Python 2.7.4 (default, Apr 19 2013, 18:28:01) 
[GCC 4.7.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from influxdb import InfluxDBClient
>>> 
>>> client = InfluxDBClient("localhost", 8086, "root", "root", "dbtest")
>>> 
>>> client.create_database("dbtest")
True
>>> client.add_database_user("root", "root")
True
>>> 
>>> json_body = [{
...     "points": [
...         ['value1']
...     ],
...     "name": "id1",
...     "columns": ["key1"]
...  }]
>>> 
>>> client.write_points(json_body)
True
>>> 
>>> print client.query("select * from id1")
[{"name":"id1","columns":["time","sequence_number","key1"],"points":[[1384282753,1,"value1"]]}]
>>> 
>>> client.delete_database("dbtest")
True
>>> 
>>> client.delete_database("dbtest")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/william/gits/checkmy.ws/opt/venv/local/lib/python2.7/site-packages/influxdb/client.py", line 243, in delete_database
    "{0}: {1}".format(response.status_code, response.content))
Exception: 400: Database dbtest doesn't exist
>>> 
>>> print client.query("select * from id1")
[]
>>> 
>>> client.create_database("dbtest")
True
>>> client.add_database_user("root", "root")
True
>>> 
>>> print client.query("select * from id1")
[{"name":"id1","columns":["time","sequence_number","key1"],"points":[[1384282753,1,"value1"]]}]
```

I have missing something ?

Thanks

**Comment by dimrozakis** [comment]
I'm also experiencing the issue where dropping the database doesn't delete the stored measurements. Here's how I can reproduce it:

Create a database called `deleteme`:
```
» /opt/influxdb/influx
Connected to http://localhost:8086 version FIXME
InfluxDB shell 0.9.0
> show databases
name: databases
---------------
name

> create database deleteme
```

Submit a datapoint to create a measurement:
```
» curl -i -XPOST 'http://localhost:8086/write?db=deleteme' --data-binary 'cpu_load_short,host=server01,region=us-west value=0.64 1434055562000000000'
HTTP/1.1 204 No Content
Request-Id: 04ac4111-2593-11e5-8dbe-000000000000
X-Influxdb-Version: FIXME
Date: Wed, 08 Jul 2015 17:01:48 GMT
```

Drop `deleteme` database:
```
» /opt/influxdb/influx
Connected to http://localhost:8086 version FIXME
InfluxDB shell 0.9.0
> show databases
name: databases
---------------
name
deleteme

> use deleteme
Using database deleteme
> show measurements
name: measurements
------------------
name
cpu_load_short

> drop database deleteme
> show databases
name: databases
---------------
name

```

Even though `deleteme` database has been dropped, it can still be 'used' and the measurements are still there. Recreating the `deleteme` database doesn't change anything (other than it will then appear in `show databases`):
```
» /opt/influxdb/influx
Connected to http://localhost:8086 version FIXME
InfluxDB shell 0.9.0
> show databases
name: databases
---------------
name

> use deleteme
Using database deleteme
> show measurements
name: measurements
------------------
name
cpu_load_short
```

Also, what's with the `version FIXME`?

**Comment by beckettsean** [comment]
@dimrozakis please upgrade to 0.9.1. This is a known and fixed bug, covered in https://github.com/influxdb/influxdb/issues/3049

**Comment by dimrozakis** [comment]
@beckettsean I upgraded and the the problem is indeed fixed, thanks.
