### ISSUE TITLE
[0.9.3] panic, above high water mark

### ISSUE THREAD

**Issue by esecules** [influxdata/influxdb#4189]
Hi I am trying to start up influx on top of an existing data directory, but I am consistently getting this error.

```
 8888888           .d888 888                   8888888b.  888888b.
   888            d88P"  888                   888  "Y88b 888  "88b
   888            888    888                   888    888 888  .88P
   888   88888b.  888888 888 888  888 888  888 888    888 8888888K.
   888   888 "88b 888    888 888  888  Y8bd8P' 888    888 888  "Y88b
   888   888  888 888    888 888  888   X88K   888    888 888    888
   888   888  888 888    888 Y88b 888 .d8""8b. 888  .d88P 888   d88P
 8888888 888  888 888    888  "Y88888 888  888 8888888P"  8888888P"

Using configuration at: /etc/opt/influxdb/influxdb.conf
[metastore] 2015/09/21 23:01:00 Using data dir: /srv/meta
[metastore] 2015/09/21 23:01:00 Skipping cluster join: already member of cluster: nodeId=1 raftEnabled=true peers=[localhost:8088]
[store] 2015/09/21 23:01:00 Using data dir: /srv/db
[metastore] 2015/09/21 23:01:00 Node at localhost:8088 [Follower]
[metastore] 2015/09/21 23:01:01 Node at localhost:8088 [Leader]. peers=[localhost:8088]
[metastore] 2015/09/21 23:01:01 Node at localhost:8088 [Follower]. peers=[localhost:8088]
[metastore] 2015/09/21 23:01:01 No leader
[metastore] 2015/09/21 23:01:02 Node at localhost:8088 [Leader]. peers=[localhost:8088]
panic: pgid (68719476860) above high water mark (218360)

goroutine 1 [running]:
github.com/boltdb/bolt.(*node).spill(0xc21ca10150, 0x0, 0x0)
	/root/go/src/github.com/boltdb/bolt/node.go:370 +0x4c6
github.com/boltdb/bolt.(*Bucket).spill(0xc21afab948, 0x0, 0x0)
	/root/go/src/github.com/boltdb/bolt/bucket.go:536 +0x1c4
github.com/boltdb/bolt.(*Tx).Commit(0xc21afab930, 0x0, 0x0)
	/root/go/src/github.com/boltdb/bolt/tx.go:151 +0x1ee
github.com/boltdb/bolt.(*DB).Update(0xc20825a4e0, 0xc2080faef0, 0x0, 0x0)
	/root/go/src/github.com/boltdb/bolt/db.go:554 +0x169

[truncated...]
```

**Comment by rkuchan** [comment]
@esecules, could you send me your config file? Thank you!

**Comment by jwilder** [comment]
Closing this since it pertains to `0.9.3` and `bz1` storage engine.  `0.9.3` is very old at this point and won't be fixed.  `bz1` engine is deprecated and replaced by the `tsm1` engine.  You can upgrade to `0.10` and convert your old shards to `tsm1` format using the [conversion tool](https://github.com/influxdata/influxdb/tree/master/cmd/influx_tsm)
