### ISSUE TITLE
[0.9.4.2] Service crashes if requesting from multiple metrics one of which doesn't exist

### ISSUE THREAD

**Issue by drmclean** [influxdata/influxdb#4430]
I can cause an error by querying a measurement (metric) that doesn't exist in the database along with one which does: 

This is fine and returns data:
`SELECT * FROM <known>` 

This returns empty array as expected:
`SELECT * FROM <unknown>`

This causes server crash:
`SELECT * FROM <known>, <unknown>`

**Comment by jwilder** [comment]
What version of the server are you using?  I'd just tried 87d99fb0d4b63ee7fbebae569912276b2c173350 and was not able to reproduce this.

**Comment by beckettsean** [comment]
Verified panic in 0.9.4.2

```
> select * from bar, foo
name: bar
---------
time			mean	value
2015-10-10T00:40:00Z	12	


name: foo
---------
time				mean	value
2015-10-13T19:24:17.897566272Z		42

> select * from bar, foos
ERR: Get http://localhost:8086/query?db=mydb&q=select+%2A+from+bar%2C+foos: EOF
```

```
[query] 2015/10/13 12:24:28 SELECT * FROM "mydb"."raw".bar, "mydb"."raw".foos
panic: runtime error: index out of range

goroutine 25116 [running]:
github.com/influxdb/influxdb/tsdb.(*tagSetCursor).decodeRawPoint(0xc827534a80, 0xc82219fb00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /private/tmp/influxdb20150916-79767-1iqb77d/influxdb-0.9.4.1/src/github.com/influxdb/influxdb/tsdb/mapper.go:828 +0x4a8
github.com/influxdb/influxdb/tsdb.(*tagSetCursor).Next(0xc827534a80, 0x0, 0x140cd572832309a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x14482, ...)
        /private/tmp/influxdb20150916-79767-1iqb77d/influxdb-0.9.4.1/src/github.com/influxdb/influxdb/tsdb/mapper.go:781 +0x193
github.com/influxdb/influxdb/tsdb.(*SelectMapper).nextChunkRaw(0xc82043b440, 0x0, 0x0, 0x0, 0x0)
        /private/tmp/influxdb20150916-79767-1iqb77d/influxdb-0.9.4.1/src/github.com/influxdb/influxdb/tsdb/mapper.go:351 +0x13b
github.com/influxdb/influxdb/tsdb.(*SelectMapper).NextChunk(0xc82043b440, 0x0, 0x0, 0x0, 0x0)
        /private/tmp/influxdb20150916-79767-1iqb77d/influxdb-0.9.4.1/src/github.com/influxdb/influxdb/tsdb/mapper.go:333 +0x286
github.com/influxdb/influxdb/tsdb.(*StatefulMapper).NextChunk(0xc822df0200, 0xc21de0, 0x0, 0x0)
        /private/tmp/influxdb20150916-79767-1iqb77d/influxdb-0.9.4.1/src/github.com/influxdb/influxdb/tsdb/executor.go:49 +0x4d
github.com/influxdb/influxdb/tsdb.(*SelectExecutor).executeRaw(0xc82219f9b0, 0xc8275349c0)
        /private/tmp/influxdb20150916-79767-1iqb77d/influxdb-0.9.4.1/src/github.com/influxdb/influxdb/tsdb/executor.go:213 +0x167c
created by github.com/influxdb/influxdb/tsdb.(*SelectExecutor).Execute
        /private/tmp/influxdb20150916-79767-1iqb77d/influxdb-0.9.4.1/src/github.com/influxdb/influxdb/tsdb/executor.go:94 +0xa1

```

**Comment by otoolep** [comment]
I cannot reproduce this on master.

> create database test
> use test
Using database test
> insert bar value=100 100
> select * from bar
name: bar
---------
time                            value
1970-01-01T00:00:00.0000001Z    100

> select * from bar, foos
>

**Comment by ChristopherRabotin** [comment]
I think I encountered the same issue: an invalid select query caused the server to crash, running InfluxDB version 0.9.4.2, branch 0.9.4, commit da1b59e7d7764d36786253b2db13b97f42ed4e1d (downloaded from stable 0.9.4).

Here's the beginning of the traceback, and [here is the full trace](https://ncry.pt/p/YdBn#fK4g5GvXixKR5YXSPgPXrLI0sIBJ5QG2yQfi-XvBJz8).
```
[query] 2015/10/21 11:55:33 SELECT value / count(value) FROM "telegraf"."default".net_bytes_recv GROUP BY server LIMIT 10
panic: runtime error: index out of range

goroutine 42296 [running]:
github.com/influxdb/influxdb/influxql.newEchoProcessor.func1(0xc8212ff220, 0x2, 0x2, 0x9bb980, 0xc820a16520)
	/tmp/build/src/github.com/influxdb/influxdb/influxql/result.go:151 +0x42
github.com/influxdb/influxdb/influxql.newBinaryExprEvaluator.func4(0xc8212ff220, 0x2, 0x2, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/influxql/result.go:200 +0xb3
github.com/influxdb/influxdb/tsdb.processForMath(0xc820b97598, 0x1, 0x1, 0xc8212ff200, 0x1, 0x1, 0x0, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/executor.go:989 +0x44c
github.com/influxdb/influxdb/tsdb.(*SelectExecutor).executeAggregate(0xc8225d92c0, 0xc821b7aa20)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/executor.go:534 +0x1944
created by github.com/influxdb/influxdb/tsdb.(*SelectExecutor).Execute
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/executor.go:96 +0xf2

goroutine 1 [chan receive, 1260 minutes]:
main.(*Main).Run(0xc820517f10, 0xc82000a060, 0x4, 0x4, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/main.go:91 +0xa16
main.main()
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/main.go:42 +0x29b

goroutine 17 [syscall, 1260 minutes, locked to thread]:
runtime.goexit()
	/home/philip/.gvm/gos/go1.5/src/runtime/asm_amd64.s:1696 +0x1
...
```

**Comment by otoolep** [comment]
@ChristopherRabotin -- that report is different. It is https://github.com/influxdb/influxdb/issues/4046
