### ISSUE TITLE
Nodes is the leader causes panic intermittent in random test cases

### ISSUE THREAD

**Issue by corylanou** [influxdata/influxdb#4576]
I've seen this panic in different tests intermittently.

Here is the stack trace:

```
--- FAIL: TestServer_Query_Aggregates_IntMax (1.05s)
panic: open meta store: initialize raft: set raft peers: node is the leader [recovered]
	panic: open meta store: initialize raft: set raft peers: node is the leader

goroutine 120 [running]:
testing.tRunner.func1(0xc820083710)
	/tmp/workdir/go/src/testing/testing.go:450 +0x1f5
github.com/influxdb/influxdb/cmd/influxd/run_test.OpenServer(0xc8204ce700, 0x0, 0x0, 0xc820102758)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_helpers_test.go:54 +0xda
github.com/influxdb/influxdb/cmd/influxd/run_test.OpenDefaultServer(0xc8204ce700, 0x0, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_helpers_test.go:81 +0x5b
github.com/influxdb/influxdb/cmd/influxd/run_test.TestServer_Query_Aggregates_IntMax(0xc820083710)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_test.go:1980 +0x71
testing.tRunner(0xc820083710, 0x142fa80)
	/tmp/workdir/go/src/testing/testing.go:456 +0xdd
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:561 +0xaa4

goroutine 1 [chan receive]:
testing.RunTests(0x10c7e58, 0x142f720, 0x48, 0x48, 0x1458d01)
	/tmp/workdir/go/src/testing/testing.go:582 +0x64b
testing.(*M).Run(0xc820093f10, 0xc8201141a0)
	/tmp/workdir/go/src/testing/testing.go:494 +0xe5
main.main()
	github.com/influxdb/influxdb/cmd/influxd/run/_test/_testmain.go:198 +0x210

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 6 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x26
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x45

goroutine 57 [select]:
net/http.(*persistConn).roundTrip(0xc820149130, 0xc820610700, 0x0, 0x0, 0x0)
	/tmp/workdir/go/src/net/http/transport.go:1164 +0xef6
net/http.(*Transport).RoundTrip(0xc820082090, 0xc8201c00e0, 0x10c3719, 0x0, 0x0)
	/tmp/workdir/go/src/net/http/transport.go:235 +0x6b4
net/http.send(0xc8201c00e0, 0x7fb3eadda7a8, 0xc820082090, 0x32, 0x0, 0x0)
	/tmp/workdir/go/src/net/http/client.go:220 +0x73e
net/http.(*Client).send(0x1434540, 0xc8201c00e0, 0x32, 0x0, 0x0)
	/tmp/workdir/go/src/net/http/client.go:143 +0x1f8
net/http.(*Client).doFollowingRedirects(0x1434540, 0xc8201c00e0, 0x10c80b0, 0x0, 0x0, 0x0)
	/tmp/workdir/go/src/net/http/client.go:380 +0x105a
net/http.(*Client).Get(0x1434540, 0xc82021d140, 0x32, 0x2, 0x0, 0x0)
	/tmp/workdir/go/src/net/http/client.go:306 +0xc9
net/http.Get(0xc82021d140, 0x32, 0x15, 0x0, 0x0)
	/tmp/workdir/go/src/net/http/client.go:281 +0x67
github.com/influxdb/influxdb/cmd/influxd/run_test.(*Server).HTTPGet(0xc820161820, 0xc82021d140, 0x32, 0x0, 0x0, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_helpers_test.go:135 +0x76
github.com/influxdb/influxdb/cmd/influxd/run_test.(*Server).QueryWithParams(0xc820161820, 0xf91b50, 0x13, 0xc8203544b0, 0x0, 0x0, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_helpers_test.go:130 +0x24f
github.com/influxdb/influxdb/cmd/influxd/run_test.(*Server).Query(0xc820161820, 0xf91b50, 0x13, 0x0, 0x0, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_helpers_test.go:121 +0x78
github.com/influxdb/influxdb/cmd/influxd/run_test.(*Query).Execute(0xc8204efe38, 0xc820161820, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_helpers_test.go:302 +0x9f
github.com/influxdb/influxdb/cmd/influxd/run_test.TestServer_DatabaseCommands(0xc82012ee10)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_test.go:97 +0xd97
testing.tRunner(0xc82012ee10, 0x142f768)
	/tmp/workdir/go/src/testing/testing.go:456 +0xdd
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:561 +0xaa4

goroutine 65 [chan receive]:
github.com/hashicorp/raft.(*deferError).Error(0xc8205acdc0, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/hashicorp/raft/future.go:56 +0x134
github.com/hashicorp/raft.(*logFuture).Error(0xc8205acdc0, 0x0, 0x0)
	<autogenerated>:14 +0x58
github.com/influxdb/influxdb/meta.(*localRaft).apply(0xc820543ef0, 0xc8207597a0, 0x1b, 0x20, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/meta/state.go:254 +0xbb
github.com/influxdb/influxdb/meta.(*Store).apply(0xc820133a40, 0xc8207597a0, 0x1b, 0x20, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/meta/store.go:1573 +0x8c
github.com/influxdb/influxdb/meta.(*Store).exec(0xc820133a40, 0x5, 0x142ad20, 0xe867c0, 0xc8206945d0, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/meta/store.go:1566 +0x43f
github.com/influxdb/influxdb/meta.(*Store).CreateRetentionPolicy(0xc820133a40, 0xf1c150, 0x3, 0xc8207c8de0, 0x1, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/meta/store.go:1025 +0x255
github.com/influxdb/influxdb/meta.(*Store).CreateDatabase(0xc820133a40, 0xf1c150, 0x3, 0xc8204adab8, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/meta/store.go:930 +0x650
github.com/influxdb/influxdb/cmd/influxd/run_test.(*Server).CreateDatabaseAndRetentionPolicy(0xc8205447c0, 0xf1c150, 0x3, 0xc8205666c0, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_helpers_test.go:111 +0x8a
github.com/influxdb/influxdb/cmd/influxd/run_test.TestServer_Query_DropSeriesFromRegex(0xc82012f050)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_test.go:337 +0x1cd
testing.tRunner(0xc82012f050, 0x142f7c8)
	/tmp/workdir/go/src/testing/testing.go:456 +0xdd
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:561 +0xaa4

goroutine 36 [select]:
github.com/influxdb/influxdb/meta.(*Store).WaitForLeader(0xc8204748c0, 0x0, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/meta/store.go:574 +0x46d
github.com/influxdb/influxdb/meta.(*Store).Open(0xc8204748c0, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/meta/store.go:259 +0x6a1
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1(0xc82045d200, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:379 +0xf9c
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open(0xc82045d200, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:419 +0x3f
github.com/influxdb/influxdb/cmd/influxd/run_test.OpenServer(0xc82046aa80, 0x0, 0x0, 0xc8200f8e80)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_helpers_test.go:53 +0x65
github.com/influxdb/influxdb/cmd/influxd/run_test.TestServer_Query_Alias(0xc820083170)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_test.go:1435 +0x81
testing.tRunner(0xc820083170, 0x142f990)
	/tmp/workdir/go/src/testing/testing.go:456 +0xdd
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:561 +0xaa4

goroutine 35 [chan receive]:
testing.RunTests.func1(0xc820112060, 0xc82012fa70)
	/tmp/workdir/go/src/testing/testing.go:565 +0x6c
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:566 +0xb86

goroutine 63 [chan receive]:
github.com/hashicorp/raft.(*deferError).Error(0xc820b065a0, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/hashicorp/raft/future.go:56 +0x134
github.com/hashicorp/raft.(*logFuture).Error(0xc820b065a0, 0x0, 0x0)
	<autogenerated>:14 +0x58
github.com/influxdb/influxdb/meta.(*localRaft).apply(0xc8203a91d0, 0xc8203fa950, 0xa, 0x10, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/meta/state.go:254 +0xbb
github.com/influxdb/influxdb/meta.(*Store).apply(0xc820132dc0, 0xc8203fa950, 0xa, 0x10, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/meta/store.go:1573 +0x8c
github.com/influxdb/influxdb/meta.(*Store).exec(0xc820132dc0, 0x3, 0x142ac60, 0xe75920, 0xc820adb900, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/meta/store.go:1566 +0x43f
github.com/influxdb/influxdb/meta.(*Store).CreateDatabase(0xc820132dc0, 0xf1c150, 0x3, 0xc8204afa08, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/meta/store.go:906 +0x16f
github.com/influxdb/influxdb/cmd/influxd/run_test.(*Server).CreateDatabaseAndRetentionPolicy(0xc8203fba70, 0xf1c150, 0x3, 0xc820add020, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_helpers_test.go:111 +0x8a
github.com/influxdb/influxdb/cmd/influxd/run_test.TestServer_Query_DropAndRecreateSeries(0xc82012efc0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_test.go:249 +0x1cd
testing.tRunner(0xc82012efc0, 0x142f7b0)
	/tmp/workdir/go/src/testing/testing.go:456 +0xdd
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:561 +0xaa4

goroutine 61 [chan receive]:
github.com/hashicorp/raft.(*deferError).Error(0xc8205ad0e0, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/hashicorp/raft/future.go:56 +0x134
github.com/hashicorp/raft.(*logFuture).Error(0xc8205ad0e0, 0x0, 0x0)
	<autogenerated>:14 +0x58
github.com/influxdb/influxdb/meta.(*localRaft).apply(0xc820542230, 0xc820606c20, 0x17, 0x20, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/meta/state.go:254 +0xbb
github.com/influxdb/influxdb/meta.(*Store).apply(0xc820133040, 0xc820606c20, 0x17, 0x20, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/meta/store.go:1573 +0x8c
github.com/influxdb/influxdb/meta.(*Store).exec(0xc820133040, 0x5, 0x142ad20, 0xe867c0, 0xc820618300, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/meta/store.go:1566 +0x43f
github.com/influxdb/influxdb/meta.(*Store).CreateRetentionPolicy(0xc820133040, 0xf1c150, 0x3, 0xc8205e6c60, 0x0, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/meta/store.go:1025 +0x255
github.com/influxdb/influxdb/cmd/influxd/run_test.(*Server).CreateDatabaseAndRetentionPolicy(0xc8203fbf00, 0xf1c150, 0x3, 0xc8205e6c60, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_helpers_test.go:113 +0x11b
github.com/influxdb/influxdb/cmd/influxd/run_test.TestServer_Query_DropDatabaseIsolated(0xc82012ef30)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_test.go:177 +0x1cd
testing.tRunner(0xc82012ef30, 0x142f798)
	/tmp/workdir/go/src/testing/testing.go:456 +0xdd
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:561 +0xaa4

goroutine 62 [chan receive]:
testing.RunTests.func1(0xc820112060, 0xc82012ef30)
	/tmp/workdir/go/src/testing/testing.go:565 +0x6c
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:566 +0xb86

goroutine 64 [chan receive]:
testing.RunTests.func1(0xc820112060, 0xc82012efc0)
	/tmp/workdir/go/src/testing/testing.go:565 +0x6c
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:566 +0xb86

goroutine 60 [chan receive]:
testing.RunTests.func1(0xc820112060, 0xc82012eea0)
	/tmp/workdir/go/src/testing/testing.go:565 +0x6c
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:566 +0xb86

goroutine 78 [chan receive]:
testing.RunTests.func1(0xc820112060, 0xc82012f3b0)
	/tmp/workdir/go/src/testing/testing.go:565 +0x6c
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:566 +0xb86

goroutine 58 [chan receive]:
testing.RunTests.func1(0xc820112060, 0xc82012ee10)
	/tmp/workdir/go/src/testing/testing.go:565 +0x6c
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:566 +0xb86

goroutine 68 [chan receive]:
testing.RunTests.func1(0xc820112060, 0xc82012f0e0)
	/tmp/workdir/go/src/testing/testing.go:565 +0x6c
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:566 +0xb86

goroutine 69 [chan receive]:
github.com/influxdb/influxdb/meta.(*Store).Open(0xc820133540, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/meta/store.go:258 +0x687
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1(0xc82042c480, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:379 +0xf9c
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open(0xc82042c480, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:419 +0x3f
github.com/influxdb/influxdb/cmd/influxd/run_test.OpenServer(0xc820436380, 0x0, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_helpers_test.go:53 +0x65
github.com/influxdb/influxdb/cmd/influxd/run_test.TestServer_DatabaseRetentionPolicyAutoCreate(0xc82012f170)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_test.go:522 +0x6e
testing.tRunner(0xc82012f170, 0x142f7f8)
	/tmp/workdir/go/src/testing/testing.go:456 +0xdd
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:561 +0xaa4

goroutine 67 [select]:
net/http.(*Transport).getConn(0xc820082090, 0xc8200a2380, 0x0, 0xc820702540, 0x4, 0xc820702547, 0xf, 0x0, 0x0, 0x0)
	/tmp/workdir/go/src/net/http/transport.go:554 +0x832
net/http.(*Transport).RoundTrip(0xc820082090, 0xc8200a2380, 0x4432b0, 0x0, 0x0)
	/tmp/workdir/go/src/net/http/transport.go:228 +0x62b
net/http.send(0xc8200a2380, 0x7fb3eadda7a8, 0xc820082090, 0x5b, 0x0, 0x0)
	/tmp/workdir/go/src/net/http/client.go:220 +0x73e
net/http.(*Client).send(0x1434540, 0xc8200a2380, 0x5b, 0x0, 0x0)
	/tmp/workdir/go/src/net/http/client.go:143 +0x1f8
net/http.(*Client).doFollowingRedirects(0x1434540, 0xc8200a2380, 0x10c80b0, 0x0, 0x0, 0x0)
	/tmp/workdir/go/src/net/http/client.go:380 +0x105a
net/http.(*Client).Get(0x1434540, 0xc820702540, 0x5b, 0x2, 0x0, 0x0)
	/tmp/workdir/go/src/net/http/client.go:306 +0xc9
net/http.Get(0xc820702540, 0x5b, 0x3e, 0x0, 0x0)
	/tmp/workdir/go/src/net/http/client.go:281 +0x67
github.com/influxdb/influxdb/cmd/influxd/run_test.(*Server).HTTPGet(0xc820544130, 0xc820702540, 0x5b, 0x0, 0x0, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_helpers_test.go:135 +0x76
github.com/influxdb/influxdb/cmd/influxd/run_test.(*Server).QueryWithParams(0xc820544130, 0x1026820, 0x3c, 0xc820618570, 0x0, 0x0, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_helpers_test.go:130 +0x24f
github.com/influxdb/influxdb/cmd/influxd/run_test.(*Server).Query(0xc820544130, 0x1026820, 0x3c, 0x0, 0x0, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_helpers_test.go:121 +0x78
github.com/influxdb/influxdb/cmd/influxd/run_test.(*Query).Execute(0xc820497e28, 0xc820544130, 0x0, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_helpers_test.go:302 +0x9f
github.com/influxdb/influxdb/cmd/influxd/run_test.TestServer_RetentionPolicyCommands(0xc82012f0e0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run/server_test.go:511 +0x110c
testing.tRunner(0xc82012f0e0, 0x142f7e0)
	/tmp/workdir/go/src/testing/testing.go:456 +0xdd
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:561 +0xaa4

goroutine 66 [chan receive]:
testing.RunTests.func1(0xc820112060, 0xc82012f050)
	/tmp/workdir/go/src/testing/testing.go:565 +0x6c
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:566 +0xb86
---- remainder truncated
```

**Comment by otoolep** [comment]
Yeah, I've been seeing this on-and-off for a while now.

**Comment by jwilder** [comment]
This appears to be fixed now.
