### ISSUE TITLE
[0.9.4.2]retention policy auto delete shard FATAL

### ISSUE THREAD

**Issue by ryanjin** [influxdata/influxdb#4669]
I have build a database for a month and alter the retention policy just now.
```
alter retention policy default on dubboservice_scv3 DURATION 7d
```

and wait 30m. Finally, influxdb crashed....

Here comes the influxdb.log
```
826597 [wal] 2015/11/05 18:11:54 Flush due to memory. Flushing 306960 series with 1484630 points and 25238710 bytes from partition 1
826598 [wal] 2015/11/05 18:12:02 Flush due to idle. Flushing 70 series with 70 points and 3071 bytes from partition 1
826599 [wal] 2015/11/05 18:12:02 write to index of partition 1 took 43.574274ms
826600 [retention] 2015/11/05 18:12:07 retention policy enforcement check commencing
826601 [retention] 2015/11/05 18:12:07 retention policy shard deletion check commencing
826602 [retention] 2015/11/05 18:12:07 deleted shard group 35 from database dubboservice_sc, retention policy default
826603 [retention] 2015/11/05 18:12:07 deleted shard group 36 from database dubboservice_scv2, retention policy default
826604 [retention] 2015/11/05 18:12:07 deleted shard group 37 from database dubboservice_scv3, retention policy default
826605 [retention] 2015/11/05 18:12:07 shard ID 2 deleted
826606 [retention] 2015/11/05 18:12:07 shard ID 32 deleted
826607 [retention] 2015/11/05 18:12:07 shard ID 5 deleted
826608 unexpected fault address 0x7f47262e6008
826609 fatal error: fault
826610 [signal 0xb code=0x1 addr=0x7f47262e6008 pc=0x797294]
826611 
826612 goroutine 64638331 [running]:
826613 runtime.throw(0xbd2650, 0x5)
826614         /home/philip/.gvm/gos/go1.5/src/runtime/panic.go:527 +0x90 fp=0xc99eadb538 sp=0xc99eadb520
826615 runtime.sigpanic()
826616         /home/philip/.gvm/gos/go1.5/src/runtime/sigpanic_unix.go:27 +0x2ab fp=0xc99eadb588 sp=0xc99eadb538
826617 github.com/boltdb/bolt.(*Cursor).first(0xc985c85400)
826618         /tmp/build/src/github.com/boltdb/bolt/cursor.go:169 +0x264 fp=0xc99eadb628 sp=0xc99eadb588
826619 github.com/boltdb/bolt.(*Cursor).next(0xc985c85400, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ffffff7)
826620         /tmp/build/src/github.com/boltdb/bolt/cursor.go:232 +0x125 fp=0xc99eadb688 sp=0xc99eadb628
826621 github.com/boltdb/bolt.(*Cursor).Next(0xc985c85400, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
826622         /tmp/build/src/github.com/boltdb/bolt/cursor.go:68 +0x90 fp=0xc99eadb6d0 sp=0xc99eadb688
826623 github.com/influxdb/influxdb/tsdb/engine/bz1.(*Cursor).Next(0xc8b1d5cb40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
826624         /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/bz1/bz1.go:741 +0x1bf fp=0xc99eadb788 sp=0xc99eadb6d0
826625 github.com/influxdb/influxdb/tsdb.(*multiCursor).pop(0xc8b1d5cb90, 0xc986879e3c, 0x8, 0x15, 0xc986879e48, 0x9, 0x9)
826626         /tmp/build/src/github.com/influxdb/influxdb/tsdb/cursor.go:103 +0x186 fp=0xc99eadb840 sp=0xc99eadb788```

**Comment by beckettsean** [comment]
@ryanjin what version of InfluxDB? 0.9.4?

**Comment by ryanjin** [comment]
@beckettsean 0.9.4.2

**Comment by beckettsean** [comment]
What is the output from `SHOW SHARDS` and the output from `ls -lR /var/opt/influxdb/data/` (assuming you have default Linux install paths.)

**Comment by ryanjin** [comment]
I restart the influxdb app yesterday. and old shards had been deleted.

I remember the database had 2shards and each shard cost between 25 G  and 35G

**Comment by jwilder** [comment]
This is an issue with the `b1` and `bz1` storage engines. Those engine are deprecated and have been replaced by the `tsm1` engine in `0.10.0`.  There is a [conversion tool](https://github.com/influxdata/influxdb/tree/master/cmd/influx_tsm) that you can use to convert your shards in `b1` and `bz1` format to `tsm1` when upgrading to `0.10.0.`.

If you see this error with the `tsm1` engine and in `0.10.0`.  Please open a new issue.
