### ISSUE TITLE
Restore functionality panics (0.9.5-nightly)

### ISSUE THREAD

**Issue by simcap** [influxdata/influxdb#4671]
Basically retrying a restore (after a fix done for #4642 ). It is still not working though with a different error.

My configuration is:
- 1 fresh install of a single InfluxDB instance version `0.9.5-nightly-780df57`
- and therefore no clustering

With a backup snapshot I have handy (done successfully) i run this command (with no InfluxDb process running):

`sudo /opt/influxdb/influxd restore -config /etc/opt/influxdb/influxdb.conf /tmp/latest-snapshot`

I get the following stacktrace:

```
unpacking: _internal/monitor/10 (33890304 bytes)
unpacking: _internal/monitor/13 (42020864 bytes)
unpacking: _internal/monitor/17 (53149696 bytes)
unpacking: _internal/monitor/21 (62894080 bytes)
unpacking: _internal/monitor/25 (72585216 bytes)
unpacking: _internal/monitor/29 (32546816 bytes)
unpacking: _internal/monitor/4 (18874368 bytes)
unpacking: _internal/monitor/7 (26234880 bytes)
unpacking: meta (1499 bytes)
[metastore] 2015/11/05 15:30:02 Using data dir: /root/.influxdb/meta
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x28 pc=0x5af09c]

goroutine 1 [running]:
github.com/influxdb/influxdb/meta.(*localRaft).open(0xc82016e9b0, 0x0, 0x0)
    /tmp/tmp.6hgbnetKDW/src/github.com/influxdb/influxdb/meta/state.go:144 +0x57c
github.com/influxdb/influxdb/meta.(*Store).openRaft(0xc820080780, 0x0, 0x0)
    /tmp/tmp.6hgbnetKDW/src/github.com/influxdb/influxdb/meta/store.go:421 +0x46
github.com/influxdb/influxdb/meta.(*Store).Open.func1(0xc820080780, 0x0, 0x0)
    /tmp/tmp.6hgbnetKDW/src/github.com/influxdb/influxdb/meta/store.go:217 +0x26d
github.com/influxdb/influxdb/meta.(*Store).Open(0xc820080780, 0x0, 0x0)
    /tmp/tmp.6hgbnetKDW/src/github.com/influxdb/influxdb/meta/store.go:196 +0x2cd
github.com/influxdb/influxdb/cmd/influxd/restore.(*Command).unpackMeta(0xc8200154a0, 0xc82000aeb0, 0xc820110a30, 0x4, 0x5db, 0xecdca77a8, 0x15d90e44, 0x10a11e0, 0xc8200f6000, 0x0, ...)
    /tmp/tmp.6hgbnetKDW/src/github.com/influxdb/influxdb/cmd/influxd/restore/restore.go:178 +0xa7a
github.com/influxdb/influxdb/cmd/influxd/restore.(*Command).unpack(0xc8200154a0, 0xc82000aeb0, 0xc8200f6000, 0x0, 0x0)
    /tmp/tmp.6hgbnetKDW/src/github.com/influxdb/influxdb/cmd/influxd/restore/restore.go:125 +0x547
github.com/influxdb/influxdb/cmd/influxd/restore.(*Command).Restore(0xc8200154a0, 0xc8200f6000, 0x7ffc09cd6941, 0x14, 0x0, 0x0)
    /tmp/tmp.6hgbnetKDW/src/github.com/influxdb/influxdb/cmd/influxd/restore/restore.go:59 +0x4da
github.com/influxdb/influxdb/cmd/influxd/restore.(*Command).Run(0xc8200154a0, 0xc82000a0c0, 0x3, 0x3, 0x0, 0x0)
    /tmp/tmp.6hgbnetKDW/src/github.com/influxdb/influxdb/cmd/influxd/restore/restore.go:40 +0xc0
main.(*Main).Run(0xc8200ebf00, 0xc82000a0c0, 0x3, 0x3, 0x0, 0x0)
    /tmp/tmp.6hgbnetKDW/src/github.com/influxdb/influxdb/cmd/influxd/main.go:124 +0x1e0f
main.main()
    /tmp/tmp.6hgbnetKDW/src/github.com/influxdb/influxdb/cmd/influxd/main.go:46 +0x29b

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /root/.gvm/gos/go1.5.1/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
    /root/.gvm/gos/go1.5.1/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
    /root/.gvm/gos/go1.5.1/src/os/signal/signal_unix.go:28 +0x37

goroutine 8 [runnable]:
github.com/hashicorp/raft.(*NetworkTransport).listen(0xc820164d20)
    /tmp/tmp.6hgbnetKDW/src/github.com/hashicorp/raft/net_transport.go:359
created by github.com/hashicorp/raft.NewNetworkTransportWithLogger
    /tmp/tmp.6hgbnetKDW/src/github.com/hashicorp/raft/net_transport.go:154 +0x279
```

I will have a look more deeply and do a PR if I have time.

**Comment by simcap** [comment]
I am guessing the `localRaft.store.RemoteAddr` is `nil`

**Comment by simcap** [comment]
I have submitted a PR for that https://github.com/influxdb/influxdb/pull/4674

**Comment by pauldix** [comment]
Closing this since it's on a very old version.
