### ISSUE TITLE
Database vanished after select * from measurement and SHOW databases

### ISSUE THREAD

**Issue by shayts7** [influxdata/influxdb#4716]
Hi,

we are using influxdb 0.9.4.2
After running:
1. select * from m1
2. select * from m2
3. show databases (while the other selects are running)

we got panic exception: "panic: interface conversion: interface {} is string, not map[string]interface {}" and from that moment our logs where full of go stacktraces output, until the moment that we restart the service. Than we ran "SHOW databases", and suddenly we did not see our database!

when using influxdb internal CLI, and type "use <our database>" influxdb accepted our command and even showed us metadata from the database, but still we cannot run any select query.

It seems like the database exists, but some pointer to that database is missing.

Question: is there any way we can restore our database definitions?

Below you can find the log prints where we sent the queries and saw the "panic" exception:
```
Nov 09 13:35:11 ip-10-10-47-127.us-west-2.compute.internal bash[6182]: [query] 2015/11/09 13:35:11 SELECT * FROM "1210534572"."default".issue_change
Nov 09 13:35:18 ip-10-10-47-127.us-west-2.compute.internal bash[6182]: [wal] 2015/11/09 13:35:18 Flush due to idle. Flushing 2253 series with 2253 points and 139758 bytes from partition 1
Nov 09 13:35:18 ip-10-10-47-127.us-west-2.compute.internal bash[6182]: [wal] 2015/11/09 13:35:18 write to index of partition 1 took 850.932463ms
Nov 09 13:35:27 ip-10-10-47-127.us-west-2.compute.internal bash[6182]: [query] 2015/11/09 13:35:27 SELECT * FROM "1210534572"."default".code_test_run
Nov 09 13:35:27 ip-10-10-47-127.us-west-2.compute.internal bash[6182]: [wal] 2015/11/09 13:35:27 Flush due to idle. Flushing 2253 series with 2253 points and 139758 bytes from partition 1
Nov 09 13:35:28 ip-10-10-47-127.us-west-2.compute.internal bash[6182]: [wal] 2015/11/09 13:35:28 write to index of partition 1 took 855.904656ms
Nov 09 13:35:28 ip-10-10-47-127.us-west-2.compute.internal bash[6182]: [http] 2015/11/09 13:35:28 10.10.29.117 - - [09/Nov/2015:13:35:27 +0000] GET /query?q=SELECT+*+FROM+code_test_run&db=1210534572 HTTP/1.1
Nov 09 13:35:29 ip-10-10-47-127.us-west-2.compute.internal bash[6182]: [query] 2015/11/09 13:35:29 SHOW DATABASES
Nov 09 13:35:29 ip-10-10-47-127.us-west-2.compute.internal bash[6182]: [http] 2015/11/09 13:35:29 10.10.29.117 - - [09/Nov/2015:13:35:29 +0000] GET /query?q=SHOW+DATABASES&db=1210534572 HTTP/1.1 200 119 http
Nov 09 13:35:32 ip-10-10-47-127.us-west-2.compute.internal bash[6182]: panic: interface conversion: interface {} is string, not map[string]interface {}
Nov 09 13:35:32 ip-10-10-47-127.us-west-2.compute.internal bash[6182]: goroutine 302198 [running]:
Nov 09 13:35:32 ip-10-10-47-127.us-west-2.compute.internal bash[6182]: github.com/influxdb/influxdb/tsdb.(*limitedRowWriter).processValues(0xc8a72e3a40, 0xc8b0766000, 0x2710, 0x3c00, 0x0)
Nov 09 13:35:32 ip-10-10-47-127.us-west-2.compute.internal bash[6182]: /tmp/build/src/github.com/influxdb/influxdb/tsdb/executor.go:857 +0x13e1
Nov 09 13:35:32 ip-10-10-47-127.us-west-2.compute.internal bash[6182]: github.com/influxdb/influxdb/tsdb.(*limitedRowWriter).Add(0xc8a72e3a40, 0xc86db3c000, 0x15e6, 0x1c00, 0xc8b070e960)
Nov 09 13:35:32 ip-10-10-47-127.us-west-2.compute.internal bash[6182]: /tmp/build/src/github.com/influxdb/influxdb/tsdb/executor.go:746 +0x388
Nov 09 13:35:32 ip-10-10-47-127.us-west-2.compute.internal bash[6182]: github.com/influxdb/influxdb/tsdb.(*SelectExecutor).executeRaw(0xc82a2b04e0, 0xc82c238540)
Nov 09 13:35:32 ip-10-10-47-127.us-west-2.compute.internal bash[6182]: /tmp/build/src/github.com/influxdb/influxdb/tsdb/executor.go:370 +0xc06
Nov 09 13:35:32 ip-10-10-47-127.us-west-2.compute.internal bash[6182]: created by github.com/influxdb/influxdb/tsdb.(*SelectExecutor).Execute
Nov 09 13:35:32 ip-10-10-47-127.us-west-2.compute.internal bash[6182]: /tmp/build/src/github.com/influxdb/influxdb/tsdb/executor.go:94 +0xa1
Nov 09 13:35:32 ip-10-10-47-127.us-west-2.compute.internal bash[6182]: goroutine 1 [chan receive, 10115 minutes]:
Nov 09 13:35:32 ip-10-10-47-127.us-west-2.compute.internal bash[6182]: main.(*Main).Run(0xc820045f10, 0xc82000a130, 0x1, 0x1, 0x0, 0x0)
Nov 09 13:35:32 ip-10-10-47-127.us-west-2.compute.internal bash[6182]: /tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/main.go:91 +0xa16
Nov 09 13:35:32 ip-10-10-47-127.us-west-2.compute.internal bash[6182]: main.main()
Nov 09 13:35:32 ip-10-10-47-127.us-west-2.compute.internal bash[6182]: /tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/main.go:42 +0x29b
Nov 09 13:35:32 ip-10-10-47-127.us-west-2.compute.internal bash[6182]: goroutine 17 [syscall, 10115 minutes, locked to thread]:
Nov 09 13:35:32 ip-10-10-47-127.us-west-2.compute.internal bash[6182]: runtime.goexit()
Nov 09 13:35:32 ip-10-10-47-127.us-west-2.compute.internal bash[6182]: /home/philip/.gvm/gos/go1.5/src/runtime/asm_amd64.s:1696 +0x1
Nov 09 13:35:32 ip-10-10-47-127.us-west-2.compute.internal bash[6182]: goroutine 5 [syscall, 10115 minutes]:
Nov 09 13:35:32 ip-10-10-47-127.us-west-2.compute.internal bash[6182]: os/signal.loop()
....
....

```

**Comment by otoolep** [comment]
That panic has been fixed in master, if you like, you can upgrade to a nightly to avoid it.

**Comment by shayts7** [comment]
Thanks. Do you know how can I revive the database? The data is all in place.

**Comment by otoolep** [comment]
Can you please show us the output of `SHOW DATABASES`?

**Comment by shayts7** [comment]
Sure,

The output contains all of the dbs except the one that executed "the select * from...":
{"results":[{"series":[{"name":"databases","columns":["name"],"values":[["_internal"],["mydb1"]]}]}]}

**Comment by otoolep** [comment]
Thanks @shayts7.

We have no other reports of anything like this. `SELECT` does nothing to write or remove anything from the disk. Has your config changed? Check the config -- can you show us all the files underneath the `data` directory?

**Comment by otoolep** [comment]
For example:
```
~/.influxdb/data $ du -h
1.3M    ./_internal/monitor
1.3M    ./_internal
32K     ./db/default
36K     ./db
1.4M    .
```

**Comment by otoolep** [comment]
For example:
```
~/.influxdb/data $ find . 
.
./_internal
./_internal/monitor
./_internal/monitor/1
./_internal/monitor/3
./db
./db/default
./db/default/4
```

**Comment by shayts7** [comment]
Sure

Here it is:
[dataDirOutput.txt](https://github.com/influxdb/influxdb/files/31727/dataDirOutput.txt)

The vanished DB is 1210534572 (You can see it in the output)

Thanks,
Shay

**Comment by shayts7** [comment]
p.s. - Maybe the problem is not related to the "SELECT * FROM", That was only a guess. 
Maybe it's related to the "SHOW DATABASES".

The most important thing for us now is to understand if there is anyway to restore the DB definition, or should be start over again?

Thanks,
Shay

**Comment by jsternberg** [comment]
I'm sorry we were not able to give a satisfactory answer to the original problem for 0.9. This issue is for an outdated version of InfluxDB that we no longer support so I'm going to close it. If you still are looking to try restoring your data, please try asking on the [mailing list](https://groups.google.com/forum/#!forum/influxdb) and hopefully someone there will be able to help you.

This issue should no longer be present in 1.0.0-beta3 since we replaced the storage and query engine in releases after 0.9, but before 1.0.
