### ISSUE TITLE
[Influxdb-0.9.5] invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by itachi90** [influxdata/influxdb#5232]
When running influxdb-0.9.5 we met with nil pointer deference problem:
```
[http] 2015/12/22 05:38:17 10.50.130.75 - root [22/Dec/2015:05:38:17 +0000] POST /write?consistency=one&db=tenant_e6299a62235a4096af5090c326d634be&p=%5BREDACTED%5D&precision=n&rp=default&u=root HTTP/1.1 204 0 - okhttp/2.4.0 3424514d-a86e-11e5-bf01-000000000000 824.953µs
[wal] 2015/12/22 05:38:18 Flush due to idle. Flushing 810 series with 24631 points and 2664775 bytes from partition 1
[wal] 2015/12/22 05:38:18 Flush due to idle. Flushing 810 series with 24704 points and 2670344 bytes from partition 1
[wal] 2015/12/22 05:38:18 Flush due to idle. Flushing 518 series with 24739 points and 2900824 bytes from partition 1
[wal] 2015/12/22 05:38:18 Flush due to idle. Flushing 2430 series with 73652 points and 7964326 bytes from partition 1
[wal] 2015/12/22 05:38:18 Flush due to idle. Flushing 550 series with 24537 points and 2871095 bytes from partition 1
[wal] 2015/12/22 05:38:18 Flush due to idle. Flushing 810 series with 24341 points and 2631873 bytes from partition 1
[wal] 2015/12/22 05:38:19 Flush due to idle. Flushing 810 series with 24484 points and 2646698 bytes from partition 1
unexpected fault address 0x7f8187c80040
unexpected fault address 0x7f81b0386040
unexpected fault address 0x7f81d4396040
unexpected fault address 0x7f81e5e12040
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x7a62af]
 
goroutine 219422326 [running]:
github.com/boltdb/bolt.(*Tx).rollback(0xc97969f2b0)
	/tmp/build/src/github.com/boltdb/bolt/tx.go:224 +0xdf
github.com/boltdb/bolt.(*DB).Update.func1(0xc97969f2b0)
	/tmp/build/src/github.com/boltdb/bolt/db.go:539 +0x2c
github.com/boltdb/bolt.(*Tx).rollback(0xc97969f2b0)
	/tmp/build/src/github.com/boltdb/bolt/tx.go:224 +0xdf
github.com/boltdb/bolt.(*Tx).Commit(0xc97969f2b0, 0x0, 0x0)
	/tmp/build/src/github.com/boltdb/bolt/tx.go:152 +0x205
github.com/boltdb/bolt.(*DB).Update(0xc8a24d0000, 0xc9e8c1da50, 0x0, 0x0)
	/tmp/build/src/github.com/boltdb/bolt/db.go:554 +0x11d
github.com/influxdb/influxdb/tsdb/engine/bz1.(*Engine).WriteIndex(0xc94d330a00, 0xc973055e30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/bz1/bz1.go:254 +0x86
github.com/influxdb/influxdb/tsdb/engine/wal.(*Partition).flushAndCompact(0xc9a6753680, 0x2, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:1029 +0x731
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).triggerAutoFlush(0xc866f3ea80)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:589 +0xf8
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc866f3ea80, 0xc8daba08a0)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:609 +0x17d
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:240 +0x627
```
Is This a known influxdb bug or issue?

**Comment by beckettsean** [comment]
@itachi90 can you provide more context? 
What kind of load was on the system at the time? 
Did it recover after a restart?
Was there missing data?
How much RAM is on the machine?

**Comment by itachi90** [comment]
Load around 8K points/Sec
Did not recover after restart, terminated when writing wal indices
The node has 240G memory.

**Comment by jwilder** [comment]
This is an issue with the `bz1` storage engine. That engine is deprecated and has been replaced by the `tsm1` engine in `0.10.0`.  There is a [conversion tool](https://github.com/influxdata/influxdb/tree/master/cmd/influx_tsm) that you can use to convert your shards in `bz1` format to `tsm1` when upgrading to `0.10.0.`.
