### ISSUE TITLE
[new query engine] Panic with limit

### ISSUE THREAD

**Issue by toddboom** [influxdata/influxdb#5296]
This is in a testing branch, so this is an issue only for @benbjohnson.

I ran the following query against a 5B point dataset (all in the `cpu` measurement) on the current `tsm1-iterator` branch:
```
SELECT host, location, value FROM stress."default".cpu LIMIT 1
```

And got this panic:
```
[query] 2016/01/06 21:31:09 SELECT * FROM stress."default".cpu LIMIT 1
SELECT: SELECT host, location, value FROM stress."default".cpu LIMIT 1
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x84f2f9]

goroutine 3502 [running]:
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*DevEngine).createVarRefIterator.func1(0xc8201cb4a0, 0xc83606ad80, 0x0, 0xc83606ad58, 0x0, 0x0)
	/home/user/.gvm/pkgsets/go1.5.2/global/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/engine.go:695 +0x989
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*DevEngine).createVarRefIterator(0xc8201cb4a0, 0x0, 0x0, 0xc85ed448a0, 0x3, 0x3, 0xc85ef908e0, 0x1, 0x1, 0x230935999d1c0000, ...)
	/home/user/.gvm/pkgsets/go1.5.2/global/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/engine.go:661 +0xa0
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*DevEngine).CreateIterator(0xc8201cb4a0, 0x0, 0x0, 0xc85ed448a0, 0x3, 0x3, 0xc85ef908e0, 0x1, 0x1, 0x230935999d1c0000, ...)
	/home/user/.gvm/pkgsets/go1.5.2/global/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/engine.go:649 +0x2f6
github.com/influxdb/influxdb/tsdb.(*Shard).CreateIterator(0xc8200a0580, 0x0, 0x0, 0xc85ed448a0, 0x3, 0x3, 0xc85ef908e0, 0x1, 0x1, 0x230935999d1c0000, ...)
	/home/user/.gvm/pkgsets/go1.5.2/global/src/github.com/influxdb/influxdb/tsdb/shard.go:388 +0x85
github.com/influxdb/influxdb/tsdb.Shards.CreateIterator.func1(0xc85ef90890, 0x2, 0x2, 0xc83606b3a0, 0xc83606b2b8, 0x0, 0x0)
	/home/user/.gvm/pkgsets/go1.5.2/global/src/github.com/influxdb/influxdb/tsdb/shard.go:432 +0xb0
github.com/influxdb/influxdb/tsdb.Shards.CreateIterator(0xc85ef90890, 0x2, 0x2, 0x0, 0x0, 0xc85ed448a0, 0x3, 0x3, 0xc85ef908e0, 0x1, ...)
	/home/user/.gvm/pkgsets/go1.5.2/global/src/github.com/influxdb/influxdb/tsdb/shard.go:430 +0xd8
github.com/influxdb/influxdb/tsdb.(*Shards).CreateIterator(0xc85cefc760, 0x0, 0x0, 0xc85ed448a0, 0x3, 0x3, 0xc85ef908e0, 0x1, 0x1, 0x230935999d1c0000, ...)
	<autogenerated>:66 +0xe8
github.com/influxdb/influxdb/influxql.buildAuxIterators(0xc85cefc740, 0x3, 0x4, 0x7f1fe478bf00, 0xc85cefc760, 0x0, 0x0, 0xc85ed448a0, 0x3, 0x3, ...)
	/home/user/.gvm/pkgsets/go1.5.2/global/src/github.com/influxdb/influxdb/influxql/select.go:46 +0x7a
github.com/influxdb/influxdb/influxql.Select(0xc820138240, 0x7f1fe478bf00, 0xc85cefc760, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/user/.gvm/pkgsets/go1.5.2/global/src/github.com/influxdb/influxdb/influxql/select.go:37 +0x499
github.com/influxdb/influxdb/tsdb.(*QueryExecutor).PlanSelect(0xc820014a20, 0xc820138240, 0x2710, 0x0, 0x0, 0x0, 0x0)
	/home/user/.gvm/pkgsets/go1.5.2/global/src/github.com/influxdb/influxdb/tsdb/query_executor.go:288 +0x724
github.com/influxdb/influxdb/tsdb.(*QueryExecutor).planStatement(0xc820014a20, 0x7f1ffc125508, 0xc820138000, 0xc82000a55e, 0x6, 0x2710, 0x0, 0x0, 0x0, 0x0)
	/home/user/.gvm/pkgsets/go1.5.2/global/src/github.com/influxdb/influxdb/tsdb/query_executor.go:404 +0x213
github.com/influxdb/influxdb/tsdb.(*QueryExecutor).executeStatement(0xc820014a20, 0x0, 0x7f1ffc125508, 0xc820138000, 0xc82000a55e, 0x6, 0xc8200144e0, 0x2710, 0xc820014360, 0x0, ...)
	/home/user/.gvm/pkgsets/go1.5.2/global/src/github.com/influxdb/influxdb/tsdb/query_executor.go:464 +0x86
github.com/influxdb/influxdb/tsdb.(*QueryExecutor).ExecuteQuery.func1(0xc8200144e0, 0xc85cefc420, 0xc82000a55e, 0x6, 0xc820014a20, 0x2710, 0xc820014360)
	/home/user/.gvm/pkgsets/go1.5.2/global/src/github.com/influxdb/influxdb/tsdb/query_executor.go:176 +0xafe
created by github.com/influxdb/influxdb/tsdb.(*QueryExecutor).ExecuteQuery
	/home/user/.gvm/pkgsets/go1.5.2/global/src/github.com/influxdb/influxdb/tsdb/query_executor.go:240 +0xa8
```

I assume it's possible that something isn't wired up yet, but just wanted to float it out there.

**Comment by benbjohnson** [comment]
The code that's up there only supports a single field aggregation. e.g. `SELECT count(value) FROM cpu`. I'm trying to wrap up the multi-field and condition field pieces on the iterator right now.

**Comment by toddboom** [comment]
@benbjohnson ah, actually, the original query was only this:

```
SELECT * FROM stress."default".cpu LIMIT 1
```

but i had pasted you the re-written version from the log. makes since that it's not working since the rewrite expands the field under the hood. thanks!

**Comment by toddboom** [comment]
@steverweber good call, thanks!
