### ISSUE TITLE
Exception in thread "INSTRUMENT17" java.lang.RuntimeException: {"error":"timeout"}

### ISSUE THREAD

**Issue by aashishtyagi** [influxdata/influxdb#5298]
Hello Guys,

I m evaluating influxdb for  our requirement . While inserting the data in influxdb (using REST ) i m facing the issue mention below :+1: 
Exception in thread "INSTRUMENT17" java.lang.RuntimeException: {"error":"timeout"}

	at org.influxdb.impl.InfluxDBErrorHandler.handleError(InfluxDBErrorHandler.java:19)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:242)
	at org.influxdb.impl.$Proxy0.writePoints(Unknown Source)
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:148)
	at org.influxdb.impl.BatchProcessor.write(BatchProcessor.java:166)
	at org.influxdb.impl.BatchProcessor.put(BatchProcessor.java:179)
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:134)
	at com.gs.task.PriceTask.run(PriceTask.java:150)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

[gstest.txt](https://github.com/influxdata/influxdb/files/81149/gstest.txt)

please change the ext of gstest.txt to gstest.zip .

This zip file contains the code that i m using . I m running TestInflux.java file to insert the data .

Please assist .

Regards,
Aashish

**Comment by rossmcdonald** [comment]
@aashishtyagi Please open this issue against the InfluxDB Java driver repository [here](https://github.com/influxdata/influxdb-java), as this is a driver-specific error and not an InfluxDB database error.
