### ISSUE TITLE
[0.9.6.1] influxdb panic/crashed claiming no space left on device (which has lots of space)

### ISSUE THREAD

**Issue by bigKS** [influxdata/influxdb#5307]
High level summary:

```
[root@TPC-E9-05-011 influxdb]# grep panic influxd.log
panic: error writing the wal to the index: write /var/lib/influxdb/data/cs/default/12: no space left on device
[root@TPC-E9-05-011 influxdb]# df /var/lib/influxdb/data/cs/default
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/sda1       25736284 4490076  19935872  19% /
[root@TPC-E9-05-011 influxdb]# sudo service influxdb status
influxdb Process is not running [ FAILED ]
```

The thing is, once I restarted it (without doing anything else, like clearing any memory), it kept working for a while.

The panic details:
```
[root@TPC-E9-05-011 influxdb]# grep panic influxd.log
panic: error writing the wal to the index: write /var/lib/influxdb/data/cs/default/12: no space left on device
[root@TPC-E9-05-011 influxdb]# df /var/lib/influxdb/data/cs/default
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/sda1       25736284 4490076  19935872  19% /
[root@TPC-E9-05-011 influxdb]# sudo service influxdb status
influxdb Process is not running [ FAILED ]
[root@TPC-E9-05-011 influxdb]# vim influxd.log
[root@TPC-E9-05-011 influxdb]# grep -A100 panic influxd.log
panic: error writing the wal to the index: write /var/lib/influxdb/data/cs/default/12: no space left on device

goroutine 23 [running]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Partition).flushAndCompact(0xc20b566240, 0x2, 0x0, 0x0)
        /tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:1034 +0x88a
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).triggerAutoFlush(0xc20813a2a0)
        /tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:589 +0xe6
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc20813a2a0, 0xc20b0d1b00)
        /tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:609 +0x167
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
        /tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:241 +0x5ed

goroutine 1 [chan receive, 5 minutes]:
main.(*Main).Run(0xc20802d680, 0xc20800a010, 0x4, 0x4, 0x0, 0x0)
        /tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/cmd/influxd/main.go:96 +0x7b3
main.main()
        /tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/cmd/influxd/main.go:46 +0xdc

goroutine 6 [syscall, 5 minutes]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, 5 minutes, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 8 [IO wait, 5 minutes]:
net.(*pollDesc).Wait(0xc208010530, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010530, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2080104d0, 0x0, 0x7f9ac90d3e70, 0xc208092000)
        /usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208036188, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc208036188, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:244 +0x4c
github.com/influxdb/influxdb/tcp.(*Mux).Serve(0xc20802dc00, 0x7f9ac90d57d0, 0xc208036188, 0x0, 0x0)
        /tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tcp/mux.go:48 +0x54
created by github.com/influxdb/influxdb/cmd/influxd/run.func·003
        /tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:361 +0x9cd

goroutine 9 [chan receive, 5 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc208036190, 0x0, 0x0, 0x0, 0x0)
        /tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x80
github.com/influxdb/influxdb/meta.(*raftLayer).Accept(0xc22016/01/07 12:33:55 InfluxDB starting, version 0.9.6.1, branch 0.9.6, commit 6d3a8603cfdaf1a141779ed88b093dcc5c528e5e, built 2015-12-10T23:40:23+0000
2016/01/07 12:33:55 Go version go1.4.2, GOMAXPROCS set to 2
2016/01/07 12:33:55 Using configuration at: /etc/influxdb/influxdb.conf
[metastore] 2016/01/07 12:33:55 Using data dir: /var/lib/influxdb/meta
[metastore] 2016/01/07 12:33:55 Node at localhost:8088 [Follower]
[metastore] 2016/01/07 12:33:55 Skipping cluster join: already member of cluster: nodeId=1 raftEnabled=true peers=[localhost:8088]
[metastore] 2016/01/07 12:33:57 Node at localhost:8088 [Leader]. peers=[localhost:8088]
[metastore] 2016/01/07 12:33:57 spun up monitoring for 1
[store] 2016/01/07 12:33:57 Using data dir: /var/lib/influxdb/data
[metastore] 2016/01/07 12:33:57 Updated node id=1 hostname=localhost:8088
[wal] 2016/01/07 12:33:57 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 52428800 partition size threshold
[wal] 2016/01/07 12:33:57 WAL writing to /var/lib/influxdb/wal/_internal/monitor/1
[wal] 2016/01/07 12:33:57 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 52428800 partition size threshold
[wal] 2016/01/07 12:33:57 WAL writing to /var/lib/influxdb/wal/cs/default/11
[wal] 2016/01/07 12:33:58 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 52428800 partition size threshold
[wal] 2016/01/07 12:33:58 WAL writing to /var/lib/influxdb/wal/cs/default/12
[wal] 2016/01/07 12:33:58 reading WAL files to flush to index
[wal] 2016/01/07 12:33:58 writing 3302 series from WAL file /var/lib/influxdb/wal/cs/default/12/01.000031.wal to index
[handoff] 2016/01/07 12:33:58 Starting hinted handoff service
[monitor] 2016/01/07 12:33:58 'hh' registered for diagnostics monitoring
[handoff] 2016/01/07 12:33:58 Using data dir: /var/lib/influxdb/hh
[subscriber] 2016/01/07 12:33:58 opened service
[monitor] 2016/01/07 12:33:58 Starting monitor system
[monitor] 2016/01/07 12:33:58 'build' registered for diagnostics monitoring
[monitor] 2016/01/07 12:33:58 'runtime' registered for diagnostics monitoring
[monitor] 2016/01/07 12:33:58 'network' registered for diagnostics monitoring
[monitor] 2016/01/07 12:33:58 'system' registered for diagnostics monitoring
[monitor] 2016/01/07 12:33:58 Storing statistics in database '_internal' retention policy '', at interval 10s
[cluster] 2016/01/07 12:33:58 Starting cluster service
[shard-precreation] 2016/01/07 12:33:58 Starting precreation service with check interval of 10m0s, advance period of 30m0s
[snapshot] 2016/01/07 12:33:58 Starting snapshot service
[copier] 2016/01/07 12:33:58 Starting copier service
[admin] 2016/01/07 12:33:58 Starting admin service
[admin] 2016/01/07 12:33:58 Listening on HTTP: [::]:8083
[continuous_querier] 2016/01/07 12:33:58 Starting continuous query service
[httpd] 2016/01/07 12:33:58 Starting HTTP service
[httpd] 2016/01/07 12:33:58 Authentication enabled: false
[httpd] 2016/01/07 12:33:58 Listening on HTTP: [::]:8086
[retention] 2016/01/07 12:33:58 Starting retention policy enforcement service with check interval of 30m0s
[run] 2016/01/07 12:33:58 Listening for signals
2016/01/07 12:33:58 Sending anonymous usage statistics to m.influxdb.com
[query] 2016/01/07 12:34:00 SHOW DATABASES
[http] 2016/01/07 12:34:00 ::1 - root [07/Jan/2016:12:34:00 -0500] GET /query?db=cs&epoch=ns&q=SHOW+DATABASES HTTP/1.1 200 101 - InfluxDBClient d6cc70ff-b564-11e5-8001-000000000000 1.53078ms
[query] 2016/01/07 12:34:00 SHOW DATABASES
[http] 2016/01/07 12:34:00 ::1 - root [07/Jan/2016:12:34:00 -0500] GET /query?db=cs&epoch=ns&q=SHOW+DATABASES HTTP/1.1 200 101 - InfluxDBClient d6ccc44b-b564-11e5-8002-000000000000 281.204µs
[query] 2016/01/07 12:34:00 DROP DATABASE cs
[http] 2016/01/07 12:34:00 ::1 - root [07/Jan/2016:12:34:00 -0500] GET /query?db=cs&epoch=ns&q=DROP+DATABASE+cs HTTP/1.1 200 40 - InfluxDBClient d6cce005-b564-11e5-8003-000000000000 15.011155ms
```

I will update if I reproduce.

**Comment by beckettsean** [comment]
@bigKS what OS are you on and how was the database installed?

**Comment by zstyblik** [comment]
@bigKS inodes status, if relevant.

**Comment by dswarbrick** [comment]
@bigKS You may have run into this https://github.com/influxdata/influxdb/issues/5207#issuecomment-167016885

**Comment by bigKS** [comment]
@beckettsean 

OS
-----
[ksengal@TPC-E9-11-019 ~]$ uname -a
Linux TPC-E9-11-019.phaedrus.sandvine.com 2.6.32-573.12.1.el6.x86_64 #1 SMP Tue Dec 15 21:19:08 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[ksengal@TPC-E9-11-019 ~]$ cat /etc/*release*
CentOS release 6.7 (Final)
CentOS release 6.7 (Final)
CentOS release 6.7 (Final)
cpe:/o:centos:linux:6:GA

Installed using:
--------
https://docs.influxdata.com/influxdb/v0.9/introduction/installation/

**Comment by jwilder** [comment]
@bigKS I'd suggest upgrading to `0.10` and converting your shards to `tsm1` using the [conversion tool](https://github.com/influxdata/influxdb/tree/master/cmd/influx_tsm).  The `bz1` engine is deprecated and won't be fixed going forward.

If you still encounter this issue with `0.10` and `tsm1` engine, please open a new issue.
