### ISSUE TITLE
[0.9.6.1] Panic after restoring backup

### ISSUE THREAD

**Issue by malaakso** [influxdata/influxdb#5315]
I performed a backup from a remote server (also running 0.9.6.1) and tried to restore it to a local server. Both backup and restore seemed to go fine, but when trying to start the local instance (after fixing the directory ownership to influxdb) I get a panic:
```
2016/01/08 13:17:46 InfluxDB starting, version 0.9.6.1, branch 0.9.6, commit 6d3a8603cfdaf1a141779ed88b093dcc5c528e5e, built 2015-12-10T23:40:23+0000
2016/01/08 13:17:46 Go version go1.4.2, GOMAXPROCS set to 4
2016/01/08 13:17:46 Using configuration at: /etc/influxdb/influxdb.conf
[metastore] 2016/01/08 13:17:46 Using data dir: /var/lib/influxdb/meta
[metastore] 2016/01/08 13:17:46 Skipping cluster join: already member of cluster: nodeId=1 raftEnabled=true peers=[localhost:8088]
[metastore] 2016/01/08 13:17:46 Node at localhost:8088 [Follower]
[metastore] 2016/01/08 13:17:47 Node at localhost:8088 [Leader]. peers=[localhost:8088]
[metastore] 2016/01/08 13:17:47 Node at localhost:8088 [Follower]. peers=[localhost:8088]
[metastore] 2016/01/08 13:17:47 spun up monitoring for 1
[store] 2016/01/08 13:17:47 Using data dir: /var/lib/influxdb/data
[metastore] 2016/01/08 13:17:47 Updated node id=1 hostname=localhost:8088
[wal] 2016/01/08 13:17:47 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 52428800 partition size threshold
[wal] 2016/01/08 13:17:47 WAL writing to /var/lib/influxdb/wal/_internal/monitor/131
[wal] 2016/01/08 13:17:47 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 52428800 partition size threshold
[wal] 2016/01/08 13:17:47 WAL writing to /var/lib/influxdb/wal/_internal/monitor/132
[wal] 2016/01/08 13:17:47 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 52428800 partition size threshold
[wal] 2016/01/08 13:17:47 WAL writing to /var/lib/influxdb/wal/_internal/monitor/133
[wal] 2016/01/08 13:17:47 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 52428800 partition size threshold
[wal] 2016/01/08 13:17:47 WAL writing to /var/lib/influxdb/wal/_internal/monitor/135
[wal] 2016/01/08 13:17:47 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 52428800 partition size threshold
[wal] 2016/01/08 13:17:47 WAL writing to /var/lib/influxdb/wal/_internal/monitor/137
[wal] 2016/01/08 13:17:47 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 52428800 partition size threshold
[wal] 2016/01/08 13:17:47 WAL writing to /var/lib/influxdb/wal/_internal/monitor/138
[wal] 2016/01/08 13:17:47 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 52428800 partition size threshold
[wal] 2016/01/08 13:17:47 WAL writing to /var/lib/influxdb/wal/_internal/monitor/139
panic: invalid page type: 0: 0

goroutine 1 [running]:
github.com/boltdb/bolt.(*Cursor).search(0xc2080d04a0, 0xc20814f260, 0x4, 0x8, 0x1feb)
	/tmp/tmp.NZsW7kxYIE/src/github.com/boltdb/bolt/cursor.go:256 +0x1ed
github.com/boltdb/bolt.(*Cursor).seek(0xc2080d04a0, 0xc20814f260, 0x4, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/tmp/tmp.NZsW7kxYIE/src/github.com/boltdb/bolt/cursor.go:159 +0x122
github.com/boltdb/bolt.(*Bucket).Bucket(0xc2081922b8, 0xc20814f260, 0x4, 0x8, 0x8)
	/tmp/tmp.NZsW7kxYIE/src/github.com/boltdb/bolt/bucket.go:112 +0x1df
github.com/boltdb/bolt.(*Tx).Bucket(0xc2081922a0, 0xc20814f260, 0x4, 0x8, 0x8)
	/tmp/tmp.NZsW7kxYIE/src/github.com/boltdb/bolt/tx.go:100 +0x52
github.com/influxdb/influxdb/tsdb.func·003(0xc2081922a0, 0x0, 0x0)
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/engine.go:110 +0x70
github.com/boltdb/bolt.(*DB).View(0xc2081ac4e0, 0xc208162f10, 0x0, 0x0)
	/tmp/tmp.NZsW7kxYIE/src/github.com/boltdb/bolt/db.go:583 +0xe7
github.com/influxdb/influxdb/tsdb.func·004(0x0, 0x0)
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/engine.go:124 +0x29f
github.com/influxdb/influxdb/tsdb.NewEngine(0xc20814acf0, 0x2c, 0xc20814ad50, 0x2b, 0xbcd740, 0x3, 0x6400000, 0x8bb2c97000, 0x77359400, 0xc20801d9a0, ...)
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/engine.go:125 +0x1df
github.com/influxdb/influxdb/tsdb.func·027(0x0, 0x0)
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/shard.go:113 +0x191
github.com/influxdb/influxdb/tsdb.(*Shard).Open(0xc2081f2160, 0x0, 0x0)
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/shard.go:133 +0x5e
github.com/influxdb/influxdb/tsdb.(*Store).loadShards(0xc2080da000, 0x0, 0x0)
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/store.go:305 +0xc49
github.com/influxdb/influxdb/tsdb.(*Store).Open(0xc2080da000, 0x0, 0x0)
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/store.go:373 +0x334
github.com/influxdb/influxdb/cmd/influxd/run.func·003(0x0, 0x0)
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:373 +0xb92
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open(0xc2080eca20, 0x0, 0x0)
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:410 +0x5e
github.com/influxdb/influxdb/cmd/influxd/run.(*Command).Run(0xc2080723f0, 0xc20800a010, 0x2, 0x2, 0x0, 0x0)
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:124 +0xe1b
main.(*Main).Run(0xc20802d700, 0xc20800a010, 0x2, 0x2, 0x0, 0x0)
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/cmd/influxd/main.go:86 +0x434
main.main()
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/cmd/influxd/main.go:46 +0xdc

goroutine 6 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 21 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc2081921c0, 0xc2081900c0)
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:604 +0x4d3
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:241 +0x5ed

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 8 [IO wait]:
net.(*pollDesc).Wait(0xc20800e450, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20800e450, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc20800e3f0, 0x0, 0x7fb62da86f78, 0xc208180228)
	/usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208036188, 0xc2080166d8, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc208036188, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:244 +0x4c
github.com/influxdb/influxdb/tcp.(*Mux).Serve(0xc20805c080, 0x7fb62da89788, 0xc208036188, 0x0, 0x0)
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tcp/mux.go:48 +0x54
created by github.com/influxdb/influxdb/cmd/influxd/run.func·003
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:361 +0x9cd

goroutine 9 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc208036190, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x80
github.com/influxdb/influxdb/meta.(*raftLayer).Accept(0xc2080d94a0, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/meta/store.go:2325 +0x64
github.com/hashicorp/raft.(*NetworkTransport).listen(0xc20800e4d0)
	/tmp/tmp.NZsW7kxYIE/src/github.com/hashicorp/raft/net_transport.go:362 +0x50
created by github.com/hashicorp/raft.NewNetworkTransportWithLogger
	/tmp/tmp.NZsW7kxYIE/src/github.com/hashicorp/raft/net_transport.go:154 +0x2c4

goroutine 10 [select]:
github.com/hashicorp/raft.(*Raft).runFollower(0xc2080bc1c0)
	/tmp/tmp.NZsW7kxYIE/src/github.com/hashicorp/raft/raft.go:614 +0x9ab
github.com/hashicorp/raft.(*Raft).run(0xc2080bc1c0)
	/tmp/tmp.NZsW7kxYIE/src/github.com/hashicorp/raft/raft.go:598 +0x9c
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.run)·fm()
	/tmp/tmp.NZsW7kxYIE/src/github.com/hashicorp/raft/raft.go:252 +0x27
github.com/hashicorp/raft.func·011()
	/tmp/tmp.NZsW7kxYIE/src/github.com/hashicorp/raft/state.go:152 +0x51
created by github.com/hashicorp/raft.(*raftState).goFunc
	/tmp/tmp.NZsW7kxYIE/src/github.com/hashicorp/raft/state.go:153 +0xe3

goroutine 11 [select]:
github.com/hashicorp/raft.(*Raft).runFSM(0xc2080bc1c0)
	/tmp/tmp.NZsW7kxYIE/src/github.com/hashicorp/raft/raft.go:509 +0x1043
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.runFSM)·fm()
	/tmp/tmp.NZsW7kxYIE/src/github.com/hashicorp/raft/raft.go:253 +0x27
github.com/hashicorp/raft.func·011()
	/tmp/tmp.NZsW7kxYIE/src/github.com/hashicorp/raft/state.go:152 +0x51
created by github.com/hashicorp/raft.(*raftState).goFunc
	/tmp/tmp.NZsW7kxYIE/src/github.com/hashicorp/raft/state.go:153 +0xe3

goroutine 12 [select]:
github.com/hashicorp/raft.(*Raft).runSnapshots(0xc2080bc1c0)
	/tmp/tmp.NZsW7kxYIE/src/github.com/hashicorp/raft/raft.go:1642 +0x466
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.runSnapshots)·fm()
	/tmp/tmp.NZsW7kxYIE/src/github.com/hashicorp/raft/raft.go:254 +0x27
github.com/hashicorp/raft.func·011()
	/tmp/tmp.NZsW7kxYIE/src/github.com/hashicorp/raft/state.go:152 +0x51
created by github.com/hashicorp/raft.(*raftState).goFunc
	/tmp/tmp.NZsW7kxYIE/src/github.com/hashicorp/raft/state.go:153 +0xe3

goroutine 13 [select]:
github.com/influxdb/influxdb/meta.(*localRaft).logLeaderChanges(0xc20804cde0)
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/meta/state.go:192 +0x46e
created by github.com/influxdb/influxdb/meta.(*localRaft).open
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/meta/state.go:182 +0x130c

goroutine 14 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc208036198, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x80
github.com/influxdb/influxdb/meta.(*Store).serveExecListener(0xc2080da140)
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/meta/store.go:742 +0xa1
created by github.com/influxdb/influxdb/meta.(*Store).Open
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/meta/store.go:248 +0x382

goroutine 15 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc2080361a0, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x80
github.com/influxdb/influxdb/meta.(*Store).serveRPCListener(0xc2080da140)
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/meta/store.go:852 +0xc9
created by github.com/influxdb/influxdb/meta.(*Store).Open
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/meta/store.go:251 +0x3cc

goroutine 23 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc208192700, 0xc20812c300)
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:604 +0x4d3
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:241 +0x5ed

goroutine 22 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc2081920e0, 0xc208191020)
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:604 +0x4d3
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:241 +0x5ed

goroutine 24 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc208192540, 0xc20812d8c0)
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:604 +0x4d3
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:241 +0x5ed

goroutine 53 [select]:
github.com/influxdb/influxdb/meta.(*Store).monitorPeerHealth(0xc2080da140)
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/meta/store.go:450 +0x26b
created by github.com/influxdb/influxdb/meta.(*Store).Open
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/meta/store.go:276 +0x703

goroutine 54 [select]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).monitorErrorChan(0xc2080eca20, 0xc20804c420)
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:536 +0x14a
created by github.com/influxdb/influxdb/cmd/influxd/run.func·003
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:367 +0xb44

goroutine 25 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc208192b60, 0xc20812c3c0)
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:604 +0x4d3
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:241 +0x5ed

goroutine 26 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc208192620, 0xc20812df20)
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:604 +0x4d3
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:241 +0x5ed

goroutine 27 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc208192ee0, 0xc20812c480)
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:604 +0x4d3
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:241 +0x5ed
```

**Comment by malaakso** [comment]
Looks the same as #2801, which is closed.

**Comment by toddboom** [comment]
@malaakso are you using the `tsm1` storage engine? if not, you'll want to switch over to that for the new backup and restore functionality.

**Comment by malaakso** [comment]
@toddboom as seen from the dump I'm using Boltdb. It might be a good idea to mention the tsm1 requirement on the [documentation page](https://docs.influxdata.com/influxdb/v0.9/administration/backup_and_restore/), which claims that snapshot functionality is there starting from 0.9.0.

**Comment by jwilder** [comment]
Documentation page has been updated.  @malaakso Unforatunately, I think the only workaround at this point is upgrading to `0.10` and migrating your shards to `tsm` format using the [conversion tool](https://github.com/influxdata/influxdb/tree/master/cmd/influx_tsm).
