### ISSUE TITLE
[0.9.6] crashes

### ISSUE THREAD

**Issue by deric** [influxdata/influxdb#5334]
Influx was unable to write any data:
```
[collectd] 2016/01/10 01:13:14 failed to write point batch to database "collectd": timeout
[monitor] 2016/01/10 01:13:15 failed to store statistics: timeout
[graphite] 2016/01/10 01:13:24 failed to write point batch to database "graphite": timeout
[collectd] 2016/01/10 01:13:24 failed to write point batch to database "collectd": timeout
[monitor] 2016/01/10 01:13:25 failed to store statistics: timeout
fatal error: runtime: out of memory

runtime stack:
runtime.SysMap(0xc914330000, 0x100000, 0x7fb260018c00, 0x1035eb8)
        /usr/local/go/src/runtime/mem_linux.c:149 +0x98
runtime.MHeap_SysAlloc(0x103b5a0, 0x100000, 0x434482)
        /usr/local/go/src/runtime/malloc.c:284 +0x124
runtime.MHeap_Alloc(0x103b5a0, 0x5, 0x10000000035, 0x40f90e)
        /usr/local/go/src/runtime/mheap.c:240 +0x66
runtime.MCentral_CacheSpan(0x1045a78, 0x7faea1fc2d68)
        /usr/local/go/src/runtime/mcentral.c:85 +0x167
runtime.MCache_Refill(0x7fb2641aa770, 0x35, 0x7faea1fc2d68)
        /usr/local/go/src/runtime/mcache.c:90 +0xa0

goroutine 42 [running]:
runtime.switchtoM()
        /usr/local/go/src/runtime/asm_amd64.s:198 fp=0xc81bc97778 sp=0xc81bc97770
runtime.mallocgc(0x2500, 0xb84740, 0x0, 0xc83e397650)
        /usr/local/go/src/runtime/malloc.go:178 +0x849 fp=0xc81bc97828 sp=0xc81bc97778
runtime.newarray(0xb84740, 0x45, 0x40e88a)
```
crashed and afterwards I'm unable to start it again:
```
2016/01/11 16:27:52 InfluxDB starting, version 0.9.6, branch 0.9.6, commit ea8bbabfb68394aab5d9f23f08e29986bc137955, built 2015-12-09T16:10:21+0000
2016/01/11 16:27:52 Go version go1.4.2, GOMAXPROCS set to 8
2016/01/11 16:27:52 Using configuration at: /etc/influxdb/influxdb.conf
[metastore] 2016/01/11 16:27:52 Using data dir: /var/opt/influxdb/meta
[registration] 2016/01/11 16:27:52 registration service terminating
[collectd] 2016/01/11 16:27:52 collectd UDP closed
[retention] 2016/01/11 16:27:52 retention policy enforcement terminating
[monitor] 2016/01/11 16:27:52 shutting down monitor system
[handoff] 2016/01/11 16:27:52 shutting down hh service
[subscriber] 2016/01/11 16:27:52 closed service
panic: close of nil channel

goroutine 1 [running]:
github.com/influxdb/influxdb/meta.(*localRaft).close(0xc208030f00, 0x0, 0x0)
        /tmp/tmp.QrWAFdTR6B/src/github.com/influxdb/influxdb/meta/state.go:206 +0x3e
github.com/influxdb/influxdb/meta.(*Store).close(0xc2080e8140, 0x0, 0x0)
        /tmp/tmp.QrWAFdTR6B/src/github.com/influxdb/influxdb/meta/store.go:562 +0x2fc
github.com/influxdb/influxdb/meta.(*Store).Close(0xc2080e8140, 0x0, 0x0)
        /tmp/tmp.QrWAFdTR6B/src/github.com/influxdb/influxdb/meta/store.go:524 +0x75
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Close(0xc2080926c0, 0x0, 0x0)
        /tmp/tmp.QrWAFdTR6B/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:473 +0x1e4
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open(0xc2080926c0, 0x0, 0x0)
        /tmp/tmp.QrWAFdTR6B/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:428 +0x85
github.com/influxdb/influxdb/cmd/influxd/run.(*Command).Run(0xc208072480, 0xc20800a010, 0x4, 0x4, 0x0, 0x0)
        /tmp/tmp.QrWAFdTR6B/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:124 +0xe1b
main.(*Main).Run(0xc20802d700, 0xc20800a010, 0x4, 0x4, 0x0, 0x0)
        /tmp/tmp.QrWAFdTR6B/src/github.com/influxdb/influxdb/cmd/influxd/main.go:86 +0x434
main.main()
        /tmp/tmp.QrWAFdTR6B/src/github.com/influxdb/influxdb/cmd/influxd/main.go:46 +0xdc

goroutine 6 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
```

is it possible to start influxdb without loosing current data?

**Comment by deric** [comment]
The error seems to be caused by missing influx directory, the defaults are different in latest version... So just moving the data solves the issue. 
```
mv /var/lib/influxdb /var/opt/
```
I guess the error message could be more explanatory.
