### ISSUE TITLE
Tsm1 is failed on the windows

### ISSUE THREAD

**Issue by runner-mei** [influxdata/influxdb#5414]
````
=== RUN TestKeyIterator_TSM_MultipleKeysDeleted
--- FAIL: TestKeyIterator_TSM_MultipleKeysDeleted (0.05s)
panic: create tsm file: rename C:\Users\xxxx\AppData\Local\Temp\tsm1-test741041793\tsm1test732173822 C:\Users\xxxx\AppData\Local\Temp\tsm1-test741041793\000000001-000000001.tsm: Access is denied. [recovered]
panic: create tsm file: rename C:\Users\xxxx\AppData\Local\Temp\tsm1-test741041793\tsm1test732173822 C:\Users\xxxx\AppData\Local\Temp\tsm1-test741041793\000000001-000000001.tsm: Access is denied.

goroutine 88 [running]:
testing.tRunner.func1(0xc082421830)
c:/go/src/testing/testing.go:450 +0x178
github.com/influxdb/influxdb/tsdb/engine/tsm1_test.MustWriteTSM(0xc0822a1480, 0x37, 0x1, 0xc0822d0000, 0x0, 0x0)
D:/developing/go/influxdb/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/compact_test.go:721 +0x349
github.com/influxdb/influxdb/tsdb/engine/tsm1_test.MustTSMReader(0xc0822a1480, 0x37, 0x1, 0xc0822d0000, 0xc0822d0000)
D:/developing/go/influxdb/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/compact_test.go:751 +0x46
github.com/influxdb/influxdb/tsdb/engine/tsm1_test.TestKeyIterator_TSM_MultipleKeysDeleted(0xc082421830)
D:/developing/go/influxdb/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/compact_test.go:285 +0x690

=== RUN TestDefaultCompactionPlanner_FullOnCold
--- FAIL: TestDefaultCompactionPlanner_FullOnCold (0.00s)
compact_test.go:536: tsm file length mismatch: got 3, exp 6
=== RUN TestDefaultCompactionPlanner_FullSkipMaxSize
--- FAIL: TestDefaultCompactionPlanner_FullSkipMaxSize (0.03s)
compact_test.go:576: tsm file length mismatch: got 0, exp 2
=== RUN TestTSMReader_MMAP_Tombstone
--- FAIL: TestTSMReader_MMAP_Tombstone (0.05s)
data_file_test.go:798: unexpected error deleting: rename C:\Users\xxxx\AppData\Local\Temp\tsm1-test530056282\tombstone454754972 C:\Users\xxxx\AppData\Local\Temp\tsm1-test530056282\tsm1test584886769.tombstone: The process cannot access the file because it is being used by another process.

=== RUN TestFileStore_Open_Deleted
--- FAIL: TestFileStore_Open_Deleted (0.22s)
file_store_test.go:670: unexpected error deleting: rename C:\Users\xxxx\AppData\Local\Temp\tsm1-test402625847\tombstone322418267 C:\Users\xxxx\AppData\Local\Temp\tsm1-test402625847\000000001-000000001.tombstone: The process cannot access the file because it is being used by another process.
=== RUN TestTombstoner_Add
--- FAIL: TestTombstoner_Add (0.05s)
tombstone_test.go:34: length mismatch: got 0, exp 1
=== RUN TestTombstoner_Delete
--- FAIL: TestTombstoner_Delete (0.04s)
tombstone_test.go:74: length mismatch: got 0, exp 1
````

**Comment by jwilder** [comment]
This is a known issue. Windows is not currently supported with the TSM engine. See #5359
