### ISSUE TITLE
[0.10.0-beta2] Deadlock in meta.Client 

### ISSUE THREAD

**Issue by dswarbrick** [influxdata/influxdb#5437]
InfluxDB 0.10.0-beta2 hangs (presumably) during level 3 compaction. On a busy server (8K points / sec), this occurred approximately 30 minutes after starting influxd. On a lightly loaded server, it happened at about 00:30 UTC, when I would normally expect the last write of a shard to occur.

The lightly loaded system is Debian 8, 2 cores, 4 GB RAM, x86_64. This was a fresh DB, created by 0.10.0-beta2.

Symptoms are: Grafana graphs stall, TCP sockets of incoming data points back up, influx CLI cannot connect.

Logfile with trace attached.
[influxd.txt](https://github.com/influxdata/influxdb/files/102641/influxd.txt)

**Comment by jwilder** [comment]
Stacktrace looks like there is a deadlock in the new `meta.Client`.  Something introduced via #5403.

```
goroutine 78948 [semacquire, 20 minutes]:
sync.(*RWMutex).RLock(0xc208136118)
	/root/.gvm/gos/go1.4.3/src/sync/rwmutex.go:36 +0x5f
github.com/influxdb/influxdb/services/meta.(*Client).data(0xc208136100, 0x0)
	/tmp/tmp.HhFzCFHe3C/src/github.com/influxdb/influxdb/services/meta/client.go:215 +0x3d
github.com/influxdb/influxdb/services/meta.(*Client).Users(0xc208136100, 0x0, 0x0, 0x0)
	/tmp/tmp.HhFzCFHe3C/src/github.com/influxdb/influxdb/services/meta/client.go:468 +0x43
github.com/influxdb/influxdb/services/httpd.func·003(0x7f3927f3cc60, 0xc20b889820, 0xc2097a1ad0)
	/tmp/tmp.HhFzCFHe3C/src/github.com/influxdb/influxdb/services/httpd/handler.go:707 +0xbd
net/http.HandlerFunc.ServeHTTP(0xc20801f7c0, 0x7f3927f3cc60, 0xc20b889820, 0xc2097a1ad0)
	/root/.gvm/gos/go1.4.3/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/services/httpd.func·004(0x7f3927f3cc60, 0xc20b889820, 0xc2097a1ad0)
	/tmp/tmp.HhFzCFHe3C/src/github.com/influxdb/influxdb/services/httpd/handler.go:751 +0xd9
net/http.HandlerFunc.ServeHTTP(0xc2080d65f0, 0x7f3927f3cc60, 0xc20b889820, 0xc2097a1ad0)
	/root/.gvm/gos/go1.4.3/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/services/httpd.func·005(0x7f3927f3cc60, 0xc20b889820, 0xc2097a1ad0)
	/tmp/tmp.HhFzCFHe3C/src/github.com/influxdb/influxdb/services/httpd/handler.go:767 +0xba
net/http.HandlerFunc.ServeHTTP(0xc20801f7e0, 0x7f3927f3cc60, 0xc20b889820, 0xc2097a1ad0)
	/root/.gvm/gos/go1.4.3/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/services/httpd.func·006(0x7f3927f3cc60, 0xc20b889820, 0xc2097a1ad0)
	/tmp/tmp.HhFzCFHe3C/src/github.com/influxdb/influxdb/services/httpd/handler.go:805 +0x3f4
net/http.HandlerFunc.ServeHTTP(0xc2080d6620, 0x7f3927f3cc60, 0xc20b889820, 0xc2097a1ad0)
	/root/.gvm/gos/go1.4.3/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/services/httpd.func·007(0x7f3927f3cc60, 0xc20b889820, 0xc2097a1ad0)
	/tmp/tmp.HhFzCFHe3C/src/github.com/influxdb/influxdb/services/httpd/handler.go:815 +0x179
net/http.HandlerFunc.ServeHTTP(0xc2080d6640, 0x7f3927f3cc60, 0xc20b889820, 0xc2097a1ad0)
	/root/.gvm/gos/go1.4.3/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/services/httpd.func·008(0x7f3927f3cc60, 0xc20b889800, 0xc2097a1ad0)
	/tmp/tmp.HhFzCFHe3C/src/github.com/influxdb/influxdb/services/httpd/handler.go:823 +0x123
net/http.HandlerFunc.ServeHTTP(0xc20801f800, 0x7f3927f3cc60, 0xc20b889800, 0xc2097a1ad0)
	/root/.gvm/gos/go1.4.3/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/services/httpd.func·010(0x7f3927f369d0, 0xc2084a6460, 0xc2097a1ad0)
	/tmp/tmp.HhFzCFHe3C/src/github.com/influxdb/influxdb/services/httpd/handler.go:842 +0x197
net/http.HandlerFunc.ServeHTTP(0xc20801f820, 0x7f3927f369d0, 0xc2084a6460, 0xc2097a1ad0)
	/root/.gvm/gos/go1.4.3/src/net/http/server.go:1265 +0x41
github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc20802e188, 0x7f3927f369d0, 0xc2084a6460, 0xc2097a1ad0)
	/tmp/tmp.HhFzCFHe3C/src/github.com/bmizerany/pat/mux.go:109 +0x21c
github.com/influxdb/influxdb/services/httpd.(*Handler).ServeHTTP(0xc208136280, 0x7f3927f369d0, 0xc2084a6460, 0xc2097a1ad0)
	/tmp/tmp.HhFzCFHe3C/src/github.com/influxdb/influxdb/services/httpd/handler.go:177 +0x36e
net/http.serverHandler.ServeHTTP(0xc208128000, 0x7f3927f369d0, 0xc2084a6460, 0xc2097a1ad0)
	/root/.gvm/gos/go1.4.3/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc20bda1f40)
	/root/.gvm/gos/go1.4.3/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/root/.gvm/gos/go1.4.3/src/net/http/server.go:1751 +0x35e
```

@dgnorton @corylanou

**Comment by dswarbrick** [comment]
@jwilder Has this hit nightly builds yet? I notice it's been merged to master, but last nightly build was Jan 24 18:34 UTC.

**Comment by jwilder** [comment]
It should be in the nighties by now. @rossmcdonald

**Comment by dswarbrick** [comment]
It looks like the nightly build just updated. I've installed this on my test instance, will report back later if it survives the shard rollover at midnight.

**Comment by rossmcdonald** [comment]
@dswarbrick Sorry about that. I refreshed the old nightly links, so they should now be up to date. I've also switched the nightly process to send new builds to those links, so they should be up-to-date from now on. 

Let me know if you run into any other issues with the nightlies.

**Comment by dswarbrick** [comment]
@jwilder So far, so good. My test instance has been running for 16 hours without incident. I will upgrade my production instance tonight if everything still looks ok.

**Comment by dswarbrick** [comment]
InfluxDB 0.10.0.n1453881635-0 has been running on my production instance for nearly 8 hours now, handling ~8K points / sec. In this time it has done numerous level 3 and full group compactions without incident.

Looks good, I think this can be closed now.

**Comment by jwilder** [comment]
Thanks @dswarbrick!
