### ISSUE TITLE
Crash during data loading

### ISSUE THREAD

**Issue by djMax** [influxdata/influxdb#5481]
4 loaders loading about 50 points at a time as fast as they can causes crashes.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x7485de]

goroutine 5952 [running]:
github.com/boltdb/bolt.(*Tx).page(0xc527f7c7e0, 0x1331, 0xcd75c3af50)
        /tmp/tmp.NZsW7kxYIE/src/github.com/boltdb/bolt/tx.go:518 +0xae
github.com/boltdb/bolt.(*Bucket).pageNode(0xc527f7c7f8, 0x1331, 0xc2ffffffff, 0xc200000000)
        /tmp/tmp.NZsW7kxYIE/src/github.com/boltdb/bolt/bucket.go:697 +0x226
github.com/boltdb/bolt.(*Cursor).search(0xca85edc0c0, 0xcd769bf160, 0x6, 0x8, 0x1331)
        /tmp/tmp.NZsW7kxYIE/src/github.com/boltdb/bolt/cursor.go:254 +0x43
github.com/boltdb/bolt.(*Cursor).seek(0xca85edc0c0, 0xcd769bf160, 0x6, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /tmp/tmp.NZsW7kxYIE/src/github.com/boltdb/bolt/cursor.go:159 +0x122
github.com/boltdb/bolt.(*Bucket).Bucket(0xc527f7c7f8, 0xcd769bf160, 0x6, 0x8, 0x8)
        /tmp/tmp.NZsW7kxYIE/src/github.com/boltdb/bolt/bucket.go:112 +0x1df
github.com/boltdb/bolt.(*Tx).Bucket(0xc527f7c7e0, 0xcd769bf160, 0x6, 0x8, 0x8)
        /tmp/tmp.NZsW7kxYIE/src/github.com/boltdb/bolt/tx.go:100 +0x52
github.com/influxdb/influxdb/tsdb/engine/bz1.(*Tx).Cursor(0xca86266de0, 0xc3bd3eeb60, 0x63, 0xcd76b75190, 0x1, 0x1, 0xc209249420, 0xcd76b75101, 0x0, 0x0)
        /tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/engine/bz1/bz1.go:638 +0x126
github.com/influxdb/influxdb/tsdb.(*AggregateMapper).openMeasurement(0xc51443cb40, 0xc20819b9d0, 0x0, 0x0)
        /tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/aggregate.go:690 +0x551
github.com/influxdb/influxdb/tsdb.(*AggregateMapper).Open(0xc51443cb40, 0x0, 0x0)
        /tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/aggregate.go:646 +0x6fb
github.com/influxdb/influxdb/tsdb.(*AggregateExecutor).openMappers(0xca8880c080, 0x0, 0x0)
        /tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/aggregate.go:205 +0x9b
github.com/influxdb/influxdb/tsdb.(*AggregateExecutor).execute(0xca8880c080, 0xc340ee8000, 0xc23b524240)
        /tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/aggregate.go:70 +0x1ab
created by github.com/influxdb/influxdb/tsdb.(*AggregateExecutor).Execute
        /tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/aggregate.go:48 +0x64
```

**Comment by djMax** [comment]
I have a passing sense that what caused it was hitting a grafana dashboard while the load was happening.

**Comment by djMax** [comment]
This machine has 60 *gigabytes* of ram, there are 380k measurements, and yet a simple query gets
```
wal] 2016/01/29 14:09:57 write to index of partition 1 took 3.502186ms
fatal error: runtime: out of memory

runtime stack:
runtime.SysMap(0xcf95bd0000, 0x100000, 0xc20808a700, 0x102ee78)
	/usr/local/go/src/runtime/mem_linux.c:149 +0x98
runtime.MHeap_SysAlloc(0x1034560, 0x100000, 0x434482)
	/usr/local/go/src/runtime/malloc.c:284 +0x124
runtime.MHeap_Alloc(0x1034560, 0x30, 0x10100000000, 0xc23b6b9d40)
	/usr/local/go/src/runtime/mheap.c:240 +0x66
```

**Comment by djMax** [comment]
I can reproduce this with just queries. 90,000 points in the query

**Comment by seiflotfy** [comment]
Nice catch. Trying to reproduce here :+1: 
Can you give me a more step by step guide on how to reproduce it?

**Comment by djMax** [comment]
I'm not sure other than the data. I WAS using 0.9.6, moved to 0.10 and it stopped.

**Comment by seiflotfy** [comment]
Good to hear, when you moved did you maintain the same data (you did not restore from a backup)?
:+1:

**Comment by djMax** [comment]
I "migrated" the data to the new engine (tsm?), which was essentially a backup/restore as I recall.

**Comment by seiflotfy** [comment]
AFAICT seems like you have been using the bz1 storage which somehow passed something invalid to bolt.I assume with the migration you are now using the tsm storage?

**Comment by djMax** [comment]
Yep, using tsm

**Comment by jwilder** [comment]
This is a `bz1` storage engine issue and should be resolved by migrating old shards to `tsm` and upgrading to `0.10`.
