### ISSUE TITLE
[0.9.6.1] influxdb cannot start while it has stored 80G data

### ISSUE THREAD

**Issue by coolcode** [influxdata/influxdb#5482]
os: centos 7 x64
memory: 30G
cpu: 11 processors * Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz

influxdb was down twice.
First time, influxdb was out of memory while writing data. I restarted it but failed, so I removed it and installed again. influxdb, however, still cannot start.

I had tried the second time in a new centos7 system. however, it still had this problem while storing about 80G data.

Please help me fixing it. Thanks!

```
2016/01/29 19:30:40 InfluxDB starting, version 0.9.6.1, branch 0.9.6, commit 6d3a8603cfdaf1a141779ed88b093dcc5c528e5e, built 2015-12-10T23:40:23+0000
2016/01/29 19:30:40 Go version go1.4.2, GOMAXPROCS set to 12
2016/01/29 19:30:40 no configuration provided, using default settings
[metastore] 2016/01/29 19:30:40 Using data dir: /root/.influxdb/meta
[retention] 2016/01/29 19:30:40 retention policy enforcement terminating
[monitor] 2016/01/29 19:30:40 shutting down monitor system
[handoff] 2016/01/29 19:30:40 shutting down hh service
[subscriber] 2016/01/29 19:30:40 closed service
panic: close of nil channel

goroutine 1 [running]:
github.com/influxdb/influxdb/meta.(*localRaft).close(0xc208030f60, 0x0, 0x0)
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/meta/state.go:206 +0x3e
github.com/influxdb/influxdb/meta.(*Store).close(0xc2080843c0, 0x0, 0x0)
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/meta/store.go:562 +0x2fc
github.com/influxdb/influxdb/meta.(*Store).Close(0xc2080843c0, 0x0, 0x0)
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/meta/store.go:524 +0x75
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Close(0xc2080b8a20, 0x0, 0x0)
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:456 +0x1e4
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open(0xc2080b8a20, 0x0, 0x0)
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:411 +0x85
github.com/influxdb/influxdb/cmd/influxd/run.(*Command).Run(0xc2080743f0, 0xc20800a000, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:124 +0xe1b
main.(*Main).Run(0xc20802b700, 0xc20800a000, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/cmd/influxd/main.go:86 +0x434
main.main()
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/cmd/influxd/main.go:46 +0xdc

goroutine 6 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 8 [runnable]:
net.(*pollDesc).Wait(0xc2080111e0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080111e0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208011180, 0x0, 0x7ff4d54a9e70, 0xc2080f6000)
	/usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc2080361d8, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc2080361d8, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:244 +0x4c
github.com/influxdb/influxdb/tcp.(*Mux).Serve(0xc2080e2240, 0x7ff4d54ab1e0, 0xc2080361d8, 0x0, 0x0)
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tcp/mux.go:48 +0x54
created by github.com/influxdb/influxdb/cmd/influxd/run.func·003
	/tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:361 +0x9cd

```

**Comment by rossmcdonald** [comment]
@coolcode Can you try upgrading to `0.10.0` and let us know if the issue persists? We have databases internally that are much larger than 80GB, so the size shouldn't be an issue.

**Comment by jwilder** [comment]
The trace if from `0.9.6` and this code has change quite substantially since then.
