### ISSUE TITLE
[0.10.0] Crashed the server with a bad derivative query

### ISSUE THREAD

**Issue by binarytemple** [influxdata/influxdb#5628]
* centos 6.7 
* influxdb-0.10.0-1.x86_64

Ran the following query from Grafana - crashed the influxdb server

```
SELECT (derivative(value, 1m) / 60.000) FROM collectd."default".interface_rx 
WHERE type = 'if_octets' AND type_instance = 'eth0' AND time > now() - 30m AND 
time < now() - 1m GROUP BY host
```

Log output:

```
[query] 2016/02/11 10:22:15 SELECT (derivative(value, 1m) / 60.000) FROM collectd."default".interface_rx WHERE type = 'if_octets' AND type_instance = 'eth0' AND time > now() - 30m AND time < now() - 1m GROUP BY host
panic: interface conversion: interface is float64, not map[string]interface {}

goroutine 233276 [running]:
github.com/influxdb/influxdb/tsdb.(*limitedRowWriter).processValues(0xc20b1afd40, 0xc20c796800, 0xad, 0x100, 0x0)
        /tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/raw.go:524 +0x1173
github.com/influxdb/influxdb/tsdb.(*limitedRowWriter).Flush(0xc20b1afd40)
        /tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/raw.go:446 +0xd6
github.com/influxdb/influxdb/tsdb.(*RawExecutor).execute(0xc20baba7b0, 0xc2093420c0, 0xc20805ff20)
        /tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/raw.go:154 +0x17e5
created by github.com/influxdb/influxdb/tsdb.(*RawExecutor).Execute
        /tmp/tmp.NZsW7kxYIE/src/github.com/influxdb/influxdb/tsdb/raw.go:59 +0x64

```

**Comment by seiflotfy** [comment]
Can you try the same query without the brackets as in:
```
SELECT derivative(value, 1m) / 60.000 FROM collectd."default".interface_rx 
WHERE type = 'if_octets' AND type_instance = 'eth0' AND time > now() - 30m AND 
time < now() - 1m GROUP BY host
```

With brackets it crashes here. Works without brackets

**Comment by seiflotfy** [comment]
I set up a PR that should fix it hopefully in master
https://github.com/influxdata/influxdb/pull/5633

**Comment by binarytemple** [comment]
nice work. I'll leave it for now. I was just experimenting with different queries. thanks!
