### ISSUE TITLE
[0.11.0] (master) panic when surrounding the select statement arguments in brackets

### ISSUE THREAD

**Issue by seiflotfy** [influxdata/influxdb#5630]
A simple
```sql
SELECT (mean(value)/1) from cpu
```
or 
```sql
SELECT (derivative(value, 1m)) FROM cpu
```
 yields a panic:
```
[query] 2016/02/11 07:27:04 SELECT (mean(value) / 1.000) FROM stress."default".cpu
panic: invalid expression type: *influxql.ParenExpr

goroutine 105 [running]:
github.com/influxdata/influxdb/influxql.buildExprIterator(0x37ca820, 0xc825c817e0, 0x37cac08, 0xc826908740, 0x37ca820, 0xc825c817e0, 0xd24908, 0x0, 0x0, 0xc825c81c40, ...)
	/Users/seif/Projects/go/src/github.com/influxdata/influxdb/influxql/select.go:362 +0x36dc
github.com/influxdata/influxdb/influxql.buildFieldIterators.func1(0xc825c0f9a8, 0x1, 0x1, 0x37cac08, 0xc826908740, 0xc821fe74e8, 0xc825c81c90, 0x1, 0x1, 0x0, ...)
	/Users/seif/Projects/go/src/github.com/influxdata/influxdb/influxql/select.go:140 +0x548
github.com/influxdata/influxdb/influxql.buildFieldIterators(0xc825c0f9a8, 0x1, 0x1, 0x37cac08, 0xc826908740, 0x0, 0x0, 0xd24908, 0x0, 0x0, ...)
	/Users/seif/Projects/go/src/github.com/influxdata/influxdb/influxql/select.go:127 +0xf8
github.com/influxdata/influxdb/influxql.Select(0xc8222c2750, 0x37cac08, 0xc826908740, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/seif/Projects/go/src/github.com/influxdata/influxdb/influxql/select.go:67 +0xb9c
github.com/influxdata/influxdb/tsdb.(*QueryExecutor).PlanSelect(0xc820132500, 0xc8222c2750, 0x2710, 0x0, 0x0, 0x0, 0x0)
	/Users/seif/Projects/go/src/github.com/influxdata/influxdb/tsdb/query_executor.go:275 +0x724
github.com/influxdata/influxdb/tsdb.(*QueryExecutor).planStatement(0xc820132500, 0x37caa58, 0xc8222c2750, 0xc8202e1e0e, 0x6, 0x2710, 0x0, 0x0, 0x0, 0x0)
	/Users/seif/Projects/go/src/github.com/influxdata/influxdb/tsdb/query_executor.go:524 +0x177
github.com/influxdata/influxdb/tsdb.(*QueryExecutor).executeStatement(0xc820132500, 0x0, 0x37caa58, 0xc8222c2750, 0xc8202e1e0e, 0x6, 0xc820070120, 0x2710, 0xc8202e1ec0, 0x0, ...)
	/Users/seif/Projects/go/src/github.com/influxdata/influxdb/tsdb/query_executor.go:648 +0x86
github.com/influxdata/influxdb/tsdb.(*QueryExecutor).ExecuteQuery.func1(0xc820070120, 0xc8269084c0, 0xc8202e1e0e, 0x6, 0xc820132500, 0x2710, 0xc8202e1ec0)
	/Users/seif/Projects/go/src/github.com/influxdata/influxdb/tsdb/query_executor.go:172 +0x97f
created by github.com/influxdata/influxdb/tsdb.(*QueryExecutor).ExecuteQuery
	/Users/seif/Projects/go/src/github.com/influxdata/influxdb/tsdb/query_executor.go:227 +0xa8
```

**Comment by seiflotfy** [comment]
looking into this

**Comment by seiflotfy** [comment]
I think the valiadtion checksum should exist in the reader.go of tsm since it can be reused elsewhere
esp. if you want to do validate on migration or so? WDYT @jwilder

**Comment by jwilder** [comment]
@seiflotfy I don't understand your question.  This issues seems to be a query parsing/planning bug.  Not a TSM block checksum problem.

**Comment by seiflotfy** [comment]
that was a wrong reference because i am stupid like that. Ignore that please

**Comment by jwilder** [comment]
@seiflotfy No problem.  Thanks for the fix!

**Comment by seiflotfy** [comment]
yeah github insists to not link https://github.com/influxdata/influxdb/issues/5630 properly my bad
