### ISSUE TITLE
[0.11.0] unsupported derivative iterator type

### ISSUE THREAD

**Issue by rossmcdonald** [influxdata/influxdb#5640]
InfluxDB version information:

```
InfluxDB v0.11.0.n1455177634 (git: master 8d7a4a9accba0ace785218a1d8fcc36540f4bca4, built 2016-02-11T08:02:04.633643)
```

Query:

```
SELECT derivative(pointReq, 1s) FROM _internal.monitor."write" WHERE time > now() - 5m
```

Panic:

```
panic: unsupported derivative iterator type: *influxql.integerSortedMergeIterator

goroutine 3434 [running]:
github.com/influxdata/influxdb/influxql.newDerivativeIterator(0x7fba280bf198, 0xc209d2c900, 0x7fba280be7a0, 0xc20bb96ab0, 0x1056640, 0x0, 0x0, 0xc20dec4c50, 0x1, 0x1, ...)
        /tmp/tmp.aWGBEz2ODw/src/github.com/influxdata/influxdb/influxql/call_iterator.go:806 +0x3fa
github.com/influxdata/influxdb/influxql.buildExprIterator(0x7fba280be7a0, 0xc20bb96ab0, 0x7fba280bede0, 0xc20fb31220, 0x7fba280be7a0, 0xc20bb96ab0, 0x1056640, 0x0, 0x0, 0xc20dec4c50, ...)
        /tmp/tmp.aWGBEz2ODw/src/github.com/influxdata/influxdb/influxql/select.go:316 +0x1c65
github.com/influxdata/influxdb/influxql.func·033(0x0, 0x0)
        /tmp/tmp.aWGBEz2ODw/src/github.com/influxdata/influxdb/influxql/select.go:140 +0x5cb
github.com/influxdata/influxdb/influxql.buildFieldIterators(0xc20802b3c8, 0x1, 0x1, 0x7fba280bede0, 0xc20fb31220, 0x0, 0x0, 0x1056640, 0x0, 0x0, ...)
        /tmp/tmp.aWGBEz2ODw/src/github.com/influxdata/influxdb/influxql/select.go:175 +0x103
github.com/influxdata/influxdb/influxql.Select(0xc20f349520, 0x7fba280bede0, 0xc20fb31220, 0x0, 0x0, 0x0, 0x0, 0x0)
        /tmp/tmp.aWGBEz2ODw/src/github.com/influxdata/influxdb/influxql/select.go:67 +0xd6d
github.com/influxdata/influxdb/tsdb.(*QueryExecutor).PlanSelect(0xc20800ad70, 0xc20f349520, 0x2710, 0x0, 0x0, 0x0, 0x0)
        /tmp/tmp.aWGBEz2ODw/src/github.com/influxdata/influxdb/tsdb/query_executor.go:275 +0x6ff
github.com/influxdata/influxdb/tsdb.(*QueryExecutor).planStatement(0xc20800ad70, 0x7fba280be8d0, 0xc20f349520, 0xc20fb2fd0e, 0x9, 0x2710, 0x0, 0x0, 0x0, 0x0)
        /tmp/tmp.aWGBEz2ODw/src/github.com/influxdata/influxdb/tsdb/query_executor.go:524 +0x1a4
github.com/influxdata/influxdb/tsdb.(*QueryExecutor).executeStatement(0xc20800ad70, 0x0, 0x7fba280be8d0, 0xc20f349520, 0xc20fb2fd0e, 0x9, 0xc20a058d80, 0x2710, 0xc20a058d20, 0x0, ...)
        /tmp/tmp.aWGBEz2ODw/src/github.com/influxdata/influxdb/tsdb/query_executor.go:648 +0x8f
github.com/influxdata/influxdb/tsdb.func·004()
        /tmp/tmp.aWGBEz2ODw/src/github.com/influxdata/influxdb/tsdb/query_executor.go:172 +0xa1d
created by github.com/influxdata/influxdb/tsdb.(*QueryExecutor).ExecuteQuery
        /tmp/tmp.aWGBEz2ODw/src/github.com/influxdata/influxdb/tsdb/query_executor.go:227 +0x242
```

/cc @jsternberg @benbjohnson

**Comment by seiflotfy** [comment]
on it

**Comment by jsternberg** [comment]
I'm assigning this to myself since this was just a section we missed.

**Comment by seiflotfy** [comment]
No worries, ping me when done would like to know what changed :D

**Comment by jsternberg** [comment]
@seiflotfy a PR was created about half an hour ago. Feel free to take a look at it and give any feedback you want.
