### ISSUE TITLE
[0.10.0] Querying a cluster with no leader causes panic

### ISSUE THREAD

**Issue by rossmcdonald** [influxdata/influxdb#5657]
Version information:

```
InfluxDB v0.10.0 (git: 0.10.0 b8bb32ecad9808ef00219e7d2469514890a0987a, built 2016-02-04T17:06:04.850564)
```

A bit of a strange use-case, but executing a query from a server that was dropped using the `DROP DATA SERVER` command results in:

```
[query] 2016/02/12 20:00:34 SELECT * FROM _internal.monitor."shard"
panic: invalid argument to Intn

goroutine 94 [running]:
math/rand.(*Rand).Intn(0xc208026a20, 0x0, 0x10)
        /root/.gvm/gos/go1.4.3/src/math/rand/rand.go:95 +0x74
math/rand.Intn(0x0, 0x0)
        /root/.gvm/gos/go1.4.3/src/math/rand/rand.go:195 +0x34
github.com/influxdb/influxdb/cluster.(*ShardMapper).CreateMapper(0xc208037540, 0x2, 0x0, 0x0, 0x0, 0x7ff33e8a1708, 0xc2086c4480, 0x2710, 0x0, 0x0, ...)
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/cluster/shard_mapper.go:49 +0x189
github.com/influxdb/influxdb/tsdb.(*QueryExecutor).PlanSelect(0xc20805a420, 0xc2086c4480, 0x2710, 0x0, 0x0, 0x0, 0x0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/tsdb/query_executor.go:278 +0xbc6
github.com/influxdb/influxdb/tsdb.(*QueryExecutor).planStatement(0xc20805a420, 0x7ff33e8a1708, 0xc2086c4480, 0xc2087659ae, 0x9, 0x2710, 0x0, 0x0, 0x0, 0x0)
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/tsdb/query_executor.go:612 +0x1a4
github.com/influxdb/influxdb/tsdb.(*QueryExecutor).executeStatement(0xc20805a420, 0x0, 0x7ff33e8a1708, 0xc2086c4480, 0xc2087659ae, 0x9, 0xc20848fc80, 0x2710, 0xc20848fc20, 0x0, ...)
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/tsdb/query_executor.go:696 +0x8f
github.com/influxdb/influxdb/tsdb.func·024()
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/tsdb/query_executor.go:168 +0xa07
created by github.com/influxdb/influxdb/tsdb.(*QueryExecutor).ExecuteQuery
        /tmp/tmp.r1Nea5VXEw/src/github.com/influxdb/influxdb/tsdb/query_executor.go:225 +0x242
```

To repro:

- Run `drop data server X`
- Run query against server X

**Comment by rossmcdonald** [comment]
Actually the same error occurs when attempting to query a cluster with no leader. To repro:

- Create a 3 node cluster
- Drop a data and meta server (from the same physical host)
- Run query

**Comment by rossmcdonald** [comment]
Nevermind. Can't repro on nightly.
