### ISSUE TITLE
[0.11.0] panic: interface conversion: influxql.Expr is *influxql.BinaryExpr, not *influxql.VarRef

### ISSUE THREAD

**Issue by wrigtim** [influxdata/influxdb#5968]
Build: 0.11.0~n1457337636

Seeing panic when running this (malformed) query. 
mean(field - field) alone yields: `ERR: error parsing query: expected field argument in mean()`, but nested in non_negative_derivative() causes a panic.

We've just opened up our instance to some more internal developers ;)

```
SELECT non_negative_derivative(mean(created_tmp_tables - created_tmp_disk_tables), 1m) FROM tg_udp."default".mysql WHERE host = 'mysql02' AND time > 1457443029s AND time < 1457609873s GROUP BY time(1m)
```

**Attempt 1:**

```
[query] 2016/03/10 05:39:40 SELECT non_negative_derivative(mean(created_tmp_tables - created_tmp_disk_tables), 1m) FROM tg_udp."default".mysql WHERE host = 'mysql02' AND time > 1457443029s AND time < 1457609873s GROUP BY time(1m)
panic: interface conversion: influxql.Expr is *influxql.BinaryExpr, not *influxql.VarRef
goroutine 3544214 [running]:
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).CreateIterator(0xc288589810, 0x7fac58fa8250, 0xc277e32270, 0x10ae888, 0x0, 0x0, 0xc345c516e0, 0x1, 0x1, 0xdf8475800, ...)
        /tmp/influxdb/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:677 +0xfe
github.com/influxdata/influxdb/tsdb.(*Shard).CreateIterator(0xc20808de00, 0x7fac58fa8250, 0xc277e32270, 0x10ae888, 0x0, 0x0, 0xc345c516e0, 0x1, 0x1, 0xdf8475800, ...)
        /tmp/influxdb/src/github.com/influxdata/influxdb/tsdb/shard.go:401 +0x12d
github.com/influxdata/influxdb/tsdb.(*shardIteratorCreator).CreateIterator(0xc2499418c8, 0x7fac58fa8250, 0xc277e32270, 0x10ae888, 0x0, 0x0, 0xc345c516e0, 0x1, 0x1, 0xdf8475800, ...)
        /tmp/influxdb/src/github.com/influxdata/influxdb/tsdb/shard.go:810 +0x78
github.com/influxdata/influxdb/influxql.func·046(0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/influxql/iterator.go:469 +0x100
github.com/influxdata/influxdb/influxql.IteratorCreators.CreateIterator(0xc345c51720, 0x1, 0x1, 0x7fac58fa8250, 0xc277e32270, 0x10ae888, 0x0, 0x0, 0xc345c516e0, 0x1, ...)
        /tmp/influxdb/src/github.com/influxdata/influxdb/influxql/iterator.go:476 +0x110
github.com/influxdata/influxdb/influxql.(*IteratorCreators).CreateIterator(0xc230061e40, 0x7fac58fa8250, 0xc277e32270, 0x10ae888, 0x0, 0x0, 0xc345c516e0, 0x1, 0x1, 0xdf8475800, ...)
        <autogenerated>:134 +0xfd
github.com/influxdata/influxdb/influxql.func·056(0x0, 0x0, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/influxql/select.go:248 +0xc48
github.com/influxdata/influxdb/influxql.buildExprIterator(0x7fac58fa8250, 0xc277e32270, 0x7fac58fa9eb0, 0xc230061e40, 0x7fac58fa8250, 0xc277e32270, 0x10ae888, 0x0, 0x0, 0xc345c516e0, ...)
        /tmp/influxdb/src/github.com/influxdata/influxdb/influxql/select.go:326 +0x1220
github.com/influxdata/influxdb/influxql.buildExprIterator(0x7fac58fa8250, 0xc277e322a0, 0x7fac58fa9eb0, 0xc230061e40, 0x7fac58fa8250, 0xc277e322a0, 0x10ae888, 0x0, 0x0, 0xc345c516e0, ...)
        /tmp/influxdb/src/github.com/influxdata/influxdb/influxql/select.go:220 +0xd16
github.com/influxdata/influxdb/influxql.func·055(0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/influxql/select.go:151 +0x64c
github.com/influxdata/influxdb/influxql.buildFieldIterators(0xc29a69efb0, 0x1, 0x1, 0x7fac58fa9eb0, 0xc230061e40, 0x0, 0x0, 0x10ae888, 0x0, 0x0, ...)
        /tmp/influxdb/src/github.com/influxdata/influxdb/influxql/select.go:187 +0x103
github.com/influxdata/influxdb/influxql.Select(0xc26fd0cf70, 0x7fac58fa9eb0, 0xc230061e40, 0xc277e32030, 0x0, 0x0, 0x0, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/influxql/select.go:77 +0xd7a
github.com/influxdata/influxdb/cluster.(*QueryExecutor).executeSelectStatement(0xc20805c7e0, 0xc26fd0cf70, 0x2710, 0x1, 0xc305af5ec0, 0xc305af5e60, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/cluster/query_executor.go:447 +0x600
github.com/influxdata/influxdb/cluster.(*QueryExecutor).executeQuery(0xc20805c7e0, 0xc239954380, 0xc28d4c568e, 0x6, 0x2710, 0xc305af5e60, 0xc305af5ec0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/cluster/query_executor.go:120 +0x6d4
created by github.com/influxdata/influxdb/cluster.(*QueryExecutor).ExecuteQuery
        /tmp/influxdb/src/github.com/influxdata/influxdb/cluster/query_executor.go:73 +0x8c
```

**Attempt 2:**

```
[query] 2016/03/10 06:06:14 SELECT non_negative_derivative(mean(created_tmp_tables - created_tmp_disk_tables), 1m) FROM tg_udp."default".mysql WHERE host = 'mysql02' AND time > 1457443029s AND time < 1457609873s GROUP BY time(1m)
panic: interface conversion: influxql.Expr is *influxql.BinaryExpr, not *influxql.VarRef

goroutine 2684 [running]:
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).CreateIterator(0xc2c8218e70, 0x7fe04f49d040, 0xc23ee78540, 0x10ae888, 0x0, 0x0, 0xc2e47e1950, 0x1, 0x1, 0xdf8475800, ...)
        /tmp/influxdb/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:677 +0xfe
github.com/influxdata/influxdb/tsdb.(*Shard).CreateIterator(0xc208061e00, 0x7fe04f49d040, 0xc23ee78540, 0x10ae888, 0x0, 0x0, 0xc2e47e1950, 0x1, 0x1, 0xdf8475800, ...)
        /tmp/influxdb/src/github.com/influxdata/influxdb/tsdb/shard.go:401 +0x12d
github.com/influxdata/influxdb/tsdb.(*shardIteratorCreator).CreateIterator(0xc266281738, 0x7fe04f49d040, 0xc23ee78540, 0x10ae888, 0x0, 0x0, 0xc2e47e1950, 0x1, 0x1, 0xdf8475800, ...)
        /tmp/influxdb/src/github.com/influxdata/influxdb/tsdb/shard.go:810 +0x78
github.com/influxdata/influxdb/influxql.func·046(0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/influxql/iterator.go:469 +0x100
github.com/influxdata/influxdb/influxql.IteratorCreators.CreateIterator(0xc2e47e1970, 0x1, 0x1, 0x7fe04f49d040, 0xc23ee78540, 0x10ae888, 0x0, 0x0, 0xc2e47e1950, 0x1, ...)
        /tmp/influxdb/src/github.com/influxdata/influxdb/influxql/iterator.go:476 +0x110
github.com/influxdata/influxdb/influxql.(*IteratorCreators).CreateIterator(0xc23a007ea0, 0x7fe04f49d040, 0xc23ee78540, 0x10ae888, 0x0, 0x0, 0xc2e47e1950, 0x1, 0x1, 0xdf8475800, ...)
        <autogenerated>:134 +0xfd
github.com/influxdata/influxdb/influxql.func·056(0x0, 0x0, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/influxql/select.go:248 +0xc48
github.com/influxdata/influxdb/influxql.buildExprIterator(0x7fe04f49d040, 0xc23ee78540, 0x7fe04f49e580, 0xc23a007ea0, 0x7fe04f49d040, 0xc23ee78540, 0x10ae888, 0x0, 0x0, 0xc2e47e1950, ...)
        /tmp/influxdb/src/github.com/influxdata/influxdb/influxql/select.go:326 +0x1220
github.com/influxdata/influxdb/influxql.buildExprIterator(0x7fe04f49d040, 0xc23ee78570, 0x7fe04f49e580, 0xc23a007ea0, 0x7fe04f49d040, 0xc23ee78570, 0x10ae888, 0x0, 0x0, 0xc2e47e1950, ...)
        /tmp/influxdb/src/github.com/influxdata/influxdb/influxql/select.go:220 +0xd16
github.com/influxdata/influxdb/influxql.func·055(0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/influxql/select.go:151 +0x64c
github.com/influxdata/influxdb/influxql.buildFieldIterators(0xc21e054898, 0x1, 0x1, 0x7fe04f49e580, 0xc23a007ea0, 0x0, 0x0, 0x10ae888, 0x0, 0x0, ...)
        /tmp/influxdb/src/github.com/influxdata/influxdb/influxql/select.go:187 +0x103
github.com/influxdata/influxdb/influxql.Select(0xc24500c4e0, 0x7fe04f49e580, 0xc23a007ea0, 0xc23ee78300, 0x0, 0x0, 0x0, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/influxql/select.go:77 +0xd7a
github.com/influxdata/influxdb/cluster.(*QueryExecutor).executeSelectStatement(0xc20806c7e0, 0xc24500c4e0, 0x2710, 0x0, 0xc2378b8ae0, 0xc2378b8a80, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/cluster/query_executor.go:447 +0x600
github.com/influxdata/influxdb/cluster.(*QueryExecutor).executeQuery(0xc20806c7e0, 0xc21cdb1900, 0xc22ff937ab, 0x0, 0x2710, 0xc2378b8a80, 0xc2378b8ae0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/cluster/query_executor.go:120 +0x6d4
created by github.com/influxdata/influxdb/cluster.(*QueryExecutor).ExecuteQuery
        /tmp/influxdb/src/github.com/influxdata/influxdb/cluster/query_executor.go:73 +0x8c
```

**Comment by jsternberg** [comment]
This looks like it might be a reasonable query.

Thoughts @pauldix @jwilder?

**Comment by pauldix** [comment]
Doing `mean(field1 -  field2)` isn't currently supported, but I think it should be. Thus doing `non_negative_derivative(mean(field1 - field2))` also should throw a parse error until we support it.

But yes, a reasonable query that we should add support for :)

**Comment by wrigtim** [comment]
@pauldix I realised math operators are unsupported within functions when checking docs, but one of the guys internally has a good use-case for this, so agree that adding support would be fantastic (was going to follow up with an RFE if that made sense).

...but until then not panicking would be awesome too :)

**Comment by jsternberg** [comment]
I'll put a temporary part in the code that protects against this kind of thing so the server doesn't panic and I'll make a new issue for the feature after finishing this.
