### ISSUE TITLE
InfluxDB cluster crashed and burned after rebooting one of the nodes

### ISSUE THREAD

**Issue by sofixa** [influxdata/influxdb#6114]
Hi everybody.

I am running a moderately sized cluster on AWS, with three m4.large instances in it, behind an ELB. Everything was going fine until today, when i decided it's time to upgrade to 0.11. I had another thing to do on one of nodes, so i removed it from the ELB, and rebooted it(planning to update InfluxDB afterwards, then put it back in the cluster and the ELB, and then proceed to do the same thing[without the reboot] on the other two nodes).

But my node-01 never booted, it just hung there(and AWS's status check said it cannot access the instance). Okay, shit happens.

Then, as i was in the process of installing another instance of Influx and attaching the old node-01's EBS volumes to the new one, i noticed my node-03 is dead as well. Completely dead, as the node-01 - no ping, with a failed status check from AWS. I tried restarting from the AWS console, attaching a public IP and pinging it, to no avail.

I had an htop running on my node-02, and i noticed it's on 100% RAM and 100% CPU(out of 8GB RAM and 2CPUs).

I quickly installed another instance, with no data or meta, and tried to make it join the cluster. Then i finished installing another one, and, with the old volumes of the node-01, joined it as well.
To sum up:

node-01, new, with the old data, meta, wal and hh of the old node-01, on InfluxDB 0.11
node-02, still alive, on InfluxDB 0.10.2
node-03, new, no data,meta,wall,hh, on InfluxDB 0.11

My cluster wasn't properly forming(all three nodes were properly resolvable from each other, ping successfull, telnet successfull on 8088 and 8091, but not on 8086). I had multiple errors in each of the log files. After a few restarts, my node-03 successfully joined the cluster(alongside node-02, which never left).

I left it like this for some time, and then i tried to add the node-01, which was still missing.
To sum up:
node-01 is up, with meta service running, v0.11
node-02 is up, meta & data running, v0.10.2
node-03 is up, meta & data running, v11

On node-01 i had various errors:

`[tcp] 2016/03/24 16:12:40 tcp.Mux: handler not registered: 2`

or
`[tcp] 2016/03/24 16:23:55 tcp.Mux: cannot read header byte: read tcp 10.255.144.56:1034: i/o timeout
[tcp] 2016/03/24 16:23:59 tcp.Mux: cannot read header byte: EOF
`
[That's the IP of my load balancer]

Or it just hung while loading various files:

`[tsm1wal] 2016/03/24 16:12:40 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/03/24 16:12:40 tsm1 WAL writing to /influxdb/wal/_internal/monitor/47
[filestore] 2016/03/24 16:12:40 /influxdb/data/_internal/monitor/47/000000001-000000001.tsm (#0) opened in 1.395519ms
`
And, from time to time, i'd see its CPU and RAM usage on 100%. 

Then i thought it's because my node-02 is on a different version, with different config.
So i stopped it and updated.

Now the only node that actually works is node-03, on the two others i get stuff like:

```
[filestore] 2016/03/24 16:14:32 /influxdb/data/telegraf/default/55/000000566-000000007.tsm (#1) opened in 29.80087184s
[filestore] 2016/03/24 16:14:37 /influxdb/data/telegraf/default/55/000000712-000000005.tsm (#2) opened in 33.969497438s
[filestore] 2016/03/24 16:14:41 /influxdb/data/telegraf/default/55/000000566-000000006.tsm (#0) opened in 38.283515073s
[cacheloader] 2016/03/24 16:14:41 reading file /influxdb/wal/telegraf/default/55/_02098.wal, size 4742899
[cacheloader] 2016/03/24 16:14:42 reading file /influxdb/wal/telegraf/default/55/_02099.wal, size 0
[tsm1] 2016/03/24 16:14:42 beginning level 1 compaction of group 0, 2 TSM files
[tsm1] 2016/03/24 16:14:42 compacting level 1 group (0) /influxdb/data/telegraf/default/55/000000719-000000001.tsm (#0)
[tsm1] 2016/03/24 16:14:42 compacting level 1 group (0) /influxdb/data/telegraf/default/55/000000721-000000001.tsm (#1)
[metastore] 2016/03/24 16:14:44 Node at influxdb-01:8088 [Leader]. peers=[influxdb-03:8088 influxdb-01:8088 influxdb-02:8088]
[metastore] 2016/03/24 16:14:47 Node at influxdb-01:8088 [Follower]. peers=[influxdb-01:8088 influxdb-03:8088 influxdb-02:8088]
```

or

```
[cluster] 2016/03/24 16:18:08 close remote connection from 10.255.144.37:39471
[handoff] 2016/03/24 16:18:08 failed to determine if node 5 is active: node not found
[handoff] 2016/03/24 16:18:10 failed to determine if node 5 is active: node not found
[handoff] 2016/03/24 16:18:14 failed to determine if node 5 is active: node not found
[handoff] 2016/03/24 16:18:22 failed to determine if node 5 is active: node not found
[write] 2016/03/24 16:18:27 write failed for shard 56 on node 2: read message type: read tcp 10.255.144.18:8088: i/o timeout
[monitor] 2016/03/24 16:18:27 failed to store statistics: write failed: read message type: read tcp 10.255.144.18:8088: i/o timeout
[write] 2016/03/24 16:18:37 write failed for shard 56 on node 2: read message type: read tcp 10.255.144.18:8088: i/o timeout
[monitor] 2016/03/24 16:18:37 failed to store statistics: write failed: read message type: read tcp 10.255.144.18:8088: i/o timeout
[handoff] 2016/03/24 16:18:38 failed to determine if node 5 is active: node not found
[write] 2016/03/24 16:18:47 write failed for shard 56 on node 2: read message type: read tcp 10.255.144.18:8088: i/o timeout
[monitor] 2016/03/24 16:18:47 failed to store statistics: write failed: read message type: read tcp 10.255.144.18:8088: i/o timeout
```

Sometimes there is even a Go panic stack trace:

```
fatal error: runtime: cannot allocate memory

runtime stack:
runtime.gothrow(0xcebb30, 0x1f)
        /usr/local/go/src/runtime/panic.go:503 +0x8e fp=0x7efd47140b98 sp=0x7efd47140b80
runtime.persistentalloc(0x1000, 0x40, 0x10bbbf8, 0x7efbab77e740)
        /usr/local/go/src/runtime/malloc.go:824 +0x18b fp=0x7efd47140bc0 sp=0x7efd47140b98
getempty(0x7efbab77e740, 0x7efbab77e740)
        /usr/local/go/src/runtime/mgc0.c:581 +0xc6 fp=0x7efd47140bf0 sp=0x7efd47140bc0
scanblock(0xc2e2ec0000, 0xe8da0000, 0x0)
        /usr/local/go/src/runtime/mgc0.c:457 +0x837 fp=0x7efd47140d30 sp=0x7efd47140bf0
runtime.gchelper()
        /usr/local/go/src/runtime/mgc0.c:1191 +0x69 fp=0x7efd47140d58 sp=0x7efd47140d30
stopm()
        /usr/local/go/src/runtime/proc.c:1181 +0x158 fp=0x7efd47140d78 sp=0x7efd47140d58
gcstopm()
        /usr/local/go/src/runtime/proc.c:1351 +0xed fp=0x7efd47140da0 sp=0x7efd47140d78
schedule()
        /usr/local/go/src/runtime/proc.c:1551 +0x9b fp=0x7efd47140dd0 sp=0x7efd47140da0
runtime.gosched_m(0xc209397e60)
        /usr/local/go/src/runtime/proc.c:1674 +0xac fp=0x7efd47140df0 sp=0x7efd47140dd0
runtime.newstack()
        /usr/local/go/src/runtime/stack.c:776 +0x4fa fp=0x7efd47140ea0 sp=0x7efd47140df0
runtime.morestack()
        /usr/local/go/src/runtime/asm_amd64.s:324 +0x7e fp=0x7efd47140ea8 sp=0x7efd47140ea0

goroutine 1 [runnable]:
strings.Join(0xc3747891f0, 0x1, 0x1, 0xc19560, 0x4, 0x2, 0x2)
        /usr/local/go/src/strings/strings.go:382 fp=0xc208116be8 sp=0xc208116be0
github.com/influxdata/influxdb/tsdb/engine/tsm1.seriesAndFieldFromCompositeKey(0xc2a2ce73e0, 0x53, 0x0, 0x0, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:969 +0xf8 fp=0xc208116c58 sp=0xc208116be8
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).addToIndexFromKey(0xc208257810, 0xc2a2ce73e0, 0x53, 0x2, 0xc2083fae10, 0xc23b360240, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:305 +0x58 fp=0xc208116d58 sp=0xc208116c58
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).LoadMetadataIndex(0xc208257810, 0xc26115cd80, 0xc2083fae10, 0xc23b360240, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:209 +0x275 fp=0xc208116f28 sp=0xc208116d58
github.com/influxdata/influxdb/tsdb.func<C2><B7>004(0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/tsdb/shard.go:155 +0x348 fp=0xc208117048 sp=0xc208116f28
github.com/influxdata/influxdb/tsdb.(*Shard).Open(0xc26115cd80, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/tsdb/shard.go:160 +0x6f fp=0xc2081170d8 sp=0xc208117048
github.com/influxdata/influxdb/tsdb.(*Store).loadShards(0xc2080fc0f0, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/tsdb/store.go:144 +0xc46 fp=0xc208117438 sp=0xc2081170d8
github.com/influxdata/influxdb/tsdb.(*Store).Open(0xc2080fc0f0, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/tsdb/store.go:89 +0x334 fp=0xc2081174f8 sp=0xc208117438
github.com/influxdata/influxdb/cmd/influxd/run.(*Server).Open(0xc2080da300, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/cmd/influxd/run/server.go:442 +0xc9c fp=0xc2081179f8 sp=0xc2081174f8
github.com/influxdata/influxdb/cmd/influxd/run.(*Command).Run(0xc208074480, 0xc20800a010, 0x4, 0x4, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/cmd/influxd/run/command.go:133 +0xe9b fp=0xc208117c20 sp=0xc2081179f8
main.(*Main).Run(0xc20803b700, 0xc20800a010, 0x4, 0x4, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/cmd/influxd/main.go:84 +0x3e6 fp=0xc208117ec0 sp=0xc208117c20
main.main()
        /tmp/influxdb/src/github.com/influxdata/influxdb/cmd/influxd/main.go:45 +0xdc fp=0xc208117f98 sp=0xc208117ec0
runtime.main()
        /usr/local/go/src/runtime/proc.go:63 +0xf3 fp=0xc208117fe0 sp=0xc208117f98
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208117fe8 sp=0xc208117fe0

goroutine 2 [garbage collection]:
runtime.switchtoM()
        /usr/local/go/src/runtime/asm_amd64.s:198 fp=0xc20801a788 sp=0xc20801a780
runtime.gogc(0x1)
        /usr/local/go/src/runtime/malloc.go:469 +0x1cf fp=0xc20801a7c0 sp=0xc20801a788
runtime.forcegchelper()
        /usr/local/go/src/runtime/proc.go:104 +0x104 fp=0xc20801a7e0 sp=0xc20801a7c0
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801a7e8 sp=0xc20801a7e0
created by runtime.init<C2><B7>4
        /usr/local/go/src/runtime/proc.go:87 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x4377e0, 0x10b8908, 0xc49190, 0xd)
        /usr/local/go/src/runtime/proc.go:130 +0x105 fp=0xc20801df98 sp=0xc20801df68
runtime.goparkunlock(0x10b8908, 0xc49190, 0xd)
        /usr/local/go/src/runtime/proc.go:136 +0x48 fp=0xc20801dfc0 sp=0xc20801df98
runtime.bgsweep()
        /usr/local/go/src/runtime/mgc0.go:98 +0xbc fp=0xc20801dfe0 sp=0xc20801dfc0
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801dfe8 sp=0xc20801dfe0
created by gc
        /usr/local/go/src/runtime/mgc0.c:1386

goroutine 4 [finalizer wait, 7 minutes]:
runtime.gopark(0x4377e0, 0x10b8900, 0xc5cc30, 0xe)
        /usr/local/go/src/runtime/proc.go:130 +0x105 fp=0xc208018f30 sp=0xc208018f00
runtime.goparkunlock(0x10b8900, 0xc5cc30, 0xe)
        /usr/local/go/src/runtime/proc.go:136 +0x48 fp=0xc208018f58 sp=0xc208018f30
runtime.runfinq()
        /usr/local/go/src/runtime/malloc.go:727 +0xba fp=0xc208018fe0 sp=0xc208018f58
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208018fe8 sp=0xc208018fe0
created by runtime.createfing
        /usr/local/go/src/runtime/malloc.go:707 +0x5e
goroutine 6 [syscall, 7 minutes]:
runtime.notetsleepg(0x10ba8c0, 0xffffffffffffffff, 0xc3dc01)
        /usr/local/go/src/runtime/lock_futex.go:201 +0x52 fp=0xc20801d768 sp=0xc20801d740
runtime.signal_recv(0x172)
        /usr/local/go/src/runtime/sigqueue.go:109 +0x135 fp=0xc20801d7a0 sp=0xc20801d768
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f fp=0xc20801d7e0 sp=0xc20801d7a0
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801d7e8 sp=0xc20801d7e0
created by os/signal.init<C2><B7>1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 95 [select, 7 minutes]:
runtime.gopark(0x41a2c0, 0xc2080e1f38, 0xc391e0, 0x6)
        /usr/local/go/src/runtime/proc.go:130 +0x105 fp=0xc2080e1d18 sp=0xc2080e1ce8
runtime.selectgoImpl(0xc2080e1f38, 0x0, 0x18)
        /usr/local/go/src/runtime/select.go:366 +0xb2c fp=0xc2080e1eb0 sp=0xc2080e1d18
runtime.selectgo(0xc2080e1f38)
        /usr/local/go/src/runtime/select.go:183 +0x12 fp=0xc2080e1ed0 sp=0xc2080e1eb0
github.com/influxdata/influxdb/cmd/influxd/run.(*Server).monitorErrorChan(0xc2080da300, 0xc20806c3c0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/cmd/influxd/run/server.go:608 +0x14a fp=0xc2080e1fd0 sp=0xc2080e1ed0
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080e1fd8 sp=0xc2080e1fd0
created by github.com/influxdata/influxdb/cmd/influxd/run.(*Server).Open
        /tmp/influxdb/src/github.com/influxdata/influxdb/cmd/influxd/run/server.go:397 +0x44c

goroutine 17 [syscall, 7 minutes, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208082fe8 sp=0xc208082fe0

goroutine 8 [runnable]:
runtime.mallocgc(0x30, 0xb615e0, 0xc200000000, 0x410984)
        /usr/local/go/src/runtime/malloc.go:46 fp=0xc2080184c0 sp=0xc2080184b8
runtime.newobject(0xb615e0, 0x7efd490f7f60)
        /usr/local/go/src/runtime/malloc.go:353 +0x49 fp=0xc2080184e8 sp=0xc2080184c0
net.sockaddrToTCP(0x7efd490f7f60, 0xc374776860, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:24 +0xc1 fp=0xc208018570 sp=0xc2080184e8
net.(*netFD).accept(0xc2080107e0, 0xc3780d48c0, 0x0, 0x0)
        /usr/local/go/src/net/fd_unix.go:441 +0x8b1 fp=0xc208018670 sp=0xc208018570
net.(*TCPListener).AcceptTCP(0xc20802c028, 0xc2080186d8, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:234 +0x4e fp=0xc2080186c0 sp=0xc208018670
net.(*TCPListener).Accept(0xc20802c028, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:244 +0x4c fp=0xc208018700 sp=0xc2080186c0
github.com/influxdata/influxdb/tcp.(*Mux).Serve(0xc20806c6c0, 0x7efd490f7ed8, 0xc20802c028, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/tcp/mux.go:52 +0xc7 fp=0xc2080187b8 sp=0xc208018700
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080187c0 sp=0xc2080187b8
created by github.com/influxdata/influxdb/cmd/influxd/run.(*Server).Open
        /tmp/influxdb/src/github.com/influxdata/influxdb/cmd/influxd/run/server.go:389 +0x25e
```

and latern on
On the node-03, the only one running, i get, from time to time, things like this:

```
[metastore] 2016/03/24 16:16:01 Node at influxdb-03:8088 [Follower]. peers=[influxdb-03:8088 influxdb-01:8088 influxdb-02:8088]
```

node-01 is running well(meta service only, though), but the node-02 is at 100% of RAM usage and quite hard to debug. (i suppose that might be connected to the fact that it has a lot of data that the other nodes don't, and it's trying to sync[and i do see it opening a lot of files in its logs, when i actually do manage to open them]).

Show servers output:

```
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://10.255.144.37:8086 version 0.11.0
InfluxDB shell 0.11.0
> show servers
name: data_nodes
----------------
id      http_addr               tcp_addr
1       influxdb-01:8086        influxdb-01:8088
2       influxdb-03:8086        influxdb-03:8088
3       influxdb-02:8086        influxdb-02:8088


name: meta_nodes
----------------
id      http_addr               tcp_addr
1       influxdb-01:8091        influxdb-01:8088
2       influxdb-03:8091        influxdb-03:8088
3       influxdb-02:8091        influxdb-02:8088
```

Edit: actually the node-01 hangs from times to times as well.

Is there something i can do besides starting over? I have a backup from earlier today from the node-02 and i can backup the node-03 now and restore both. Will that pose a conflict? 

Thanks in advance.

**Comment by sofixa** [comment]
Update: After a lot of time(i'm talking hours) the node-01 actually started properly and it is currently working.
But i still get errors in the logs:

`[write] 2016/03/24 16:41:44 write failed for shard 56 on node 2: read message type: read tcp 10.255.144.18:8088: i/o timeout
[monitor] 2016/03/24 16:41:44 failed to store statistics: write failed: read message type: read tcp 10.255.144.18:8088: i/o timeout`
(the IP in question is the IP of the node-02, which is still doing stuff with only meta service up)

**Comment by sofixa** [comment]
And today the cluster is completely dead. nodes 2 and 3 fail to start influxdb(it blocks on service influxdb start) and node 1 is only saying:

`[metastore] 2016/03/25 11:38:09 Waiting for 2 join peers.  Have [influxdb-01:8088]. Asking nodes: [influxdb-03:8091 influxdb-02:8091 influxdb-01:8091]
`
