### ISSUE TITLE
influxd 0.11.0 crashes on SELECT * with large dataset

### ISSUE THREAD

**Issue by gmr** [influxdata/influxdb#6162]
influxd crashed today due to a user issuing a ``SELECT * FROM measurement`` today for a very large dataset. While I don't think the usage was really reasonable for our use case, it probably shouldn't crash the entire influxd process. I've kept the influxd.log incase you'd like it, but it's 477KB, so here's the top few lines:

```
[query] 2016/03/30 14:26:46 SELECT * FROM services."default".service_name
fatal error: runtime: out of memory

runtime stack:
runtime.SysMap(0xc55c920000, 0x100000, 0x100, 0x10bbb98)
	/usr/local/go/src/runtime/mem_linux.c:149 +0x98
runtime.MHeap_SysAlloc(0x10c1280, 0x100000, 0x4316c2)
	/usr/local/go/src/runtime/malloc.c:284 +0x124
runtime.MHeap_Alloc(0x10c1280, 0x1, 0x10000000002, 0x40f7ce)
	/usr/local/go/src/runtime/mheap.c:240 +0x66
runtime.MCentral_CacheSpan(0x10c7df8, 0xc29d4d9d30)
	/usr/local/go/src/runtime/mcentral.c:85 +0x167
runtime.MCache_Refill(0x7f6282e0b4b0, 0x7f6200000002, 0x83f070358)
	/usr/local/go/src/runtime/mcache.c:90 +0xa0

goroutine 74002083 [running]:
runtime.switchtoM()
	/usr/local/go/src/runtime/asm_amd64.s:198 fp=0xc29d4d9b68 sp=0xc29d4d9b60
runtime.mallocgc(0x10, 0x9e6000, 0xc200000000, 0xc55c90dff0)
	/usr/local/go/src/runtime/malloc.go:178 +0x849 fp=0xc29d4d9c18 sp=0xc29d4d9b68
runtime.newobject(0x9e6000, 0xc55c90dff0)
	/usr/local/go/src/runtime/malloc.go:353 +0x49 fp=0xc29d4d9c40 sp=0xc29d4d9c18
runtime.convT2E(0x9e6000, 0xc2d588aa20, 0x0, 0x0)
	/usr/local/go/src/runtime/iface.go:141 +0xd2 fp=0xc29d4d9c78 sp=0xc29d4d9c40
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*stringLiteralCursor).peek(0xc2d588aa20, 0xffffffffffffffff, 0x0, 0x0)
	/tmp/influxdb/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/iterator.gen.go:1084 +0x4e fp=0xc29d4d9ca0 sp=0xc29d4d9c78
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*floatIterator).Next(0xc2d58dc4e0, 0xc2d589ec60)
	/tmp/influxdb/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/iterator.gen.go:149 +0x43d fp=0xc29d4d9d90 sp=0xc29d4d9ca0
github.com/influxdata/influxdb/influxql.(*floatSortedMergeIterator).pop(0xc4169e1a00, 0x60)
	/tmp/influxdb/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:310 +0x109 fp=0xc29d4d9e58 sp=0xc29d4d9d90
github.com/influxdata/influxdb/influxql.(*floatSortedMergeIterator).Next(0xc4169e1a00, 0xc55c91b0e0)
	/tmp/influxdb/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:294 +0x28 fp=0xc29d4d9e70 sp=0xc29d4d9e58
github.com/influxdata/influxdb/influxql.(*floatSortedMergeIterator).pop(0xc37b57aa00, 0xc37b710870)
	/tmp/influxdb/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:310 +0x109 fp=0xc29d4d9f38 sp=0xc29d4d9e70
github.com/influxdata/influxdb/influxql.(*floatSortedMergeIterator).Next(0xc37b57aa00, 0xc55c91d401)
	/tmp/influxdb/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:294 +0x28 fp=0xc29d4d9f50 sp=0xc29d4d9f38
github.com/influxdata/influxdb/influxql.(*bufFloatIterator).Next(0xc37bcd8400, 0x11)
	/tmp/influxdb/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:85 +0x59 fp=0xc29d4d9f78 sp=0xc29d4d9f50
github.com/influxdata/influxdb/influxql.(*floatAuxIterator).stream(0xc37bc873e0)
	/tmp/influxdb/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:625 +0x2b fp=0xc29d4d9fd8 sp=0xc29d4d9f78
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc29d4d9fe0 sp=0xc29d4d9fd8
created by github.com/influxdata/influxdb/influxql.(*floatAuxIterator).Start
	/tmp/influxdb/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:595 +0x32
```

Let me know if the full log is useful and I'll upload it to S3 or something...

**Comment by jwilder** [comment]
#6126 should fix this.
