### ISSUE TITLE
panic running influx_inspect info

### ISSUE THREAD

**Issue by seiflotfy** [influxdata/influxdb#6294]
Running ```influx_inspect info```

gives me 
```
influx_inspect info
[cacheloader] 2016/04/12 23:34:56 reading file /Users/seif/.influxdb/wal/_internal/monitor/1/_00001.wal, size 1077
[cacheloader] 2016/04/12 23:34:56 reading file /Users/seif/.influxdb/wal/_internal/monitor/1/_00002.wal, size 169812
[filestore] 2016/04/12 23:34:56 /Users/seif/.influxdb/data/stress/default/2/000000001-000000001.tsm (#0) opened in 7.417241ms
[cacheloader] 2016/04/12 23:34:56 reading file /Users/seif/.influxdb/wal/stress/default/2/_00006.wal, size 0
[cacheloader] 2016/04/12 23:34:56 reading file /Users/seif/.influxdb/wal/_internal/monitor/1/_00003.wal, size 43295
[cacheloader] 2016/04/12 23:34:56 reading file /Users/seif/.influxdb/wal/_internal/monitor/1/_00006.wal, size 0
[tsm1] 2016/04/12 23:34:56 /Users/seif/.influxdb/data/_internal/monitor/1 database index loaded in 556.748µs
[tsm1] 2016/04/12 23:34:57 /Users/seif/.influxdb/data/stress/default/2 database index loaded in 535.600122ms
Shards: 2, Indexes: 2, Databases: 2, Disk Size: 170, Series: 0

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0xb8c51]

goroutine 1 [running]:
panic(0x52f420, 0xc8200120e0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
github.com/influxdata/influxdb/tsdb.(*FieldCodec).Fields(0x0, 0x0, 0x0, 0x0)
	/Users/seif/Projects/go/src/github.com/influxdata/influxdb/tsdb/shard.go:846 +0x41
main.cmdInfo(0xc8200dc860, 0x15)
	/Users/seif/Projects/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/info.go:65 +0x1019
main.main()
	/Users/seif/Projects/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/main.go:51 +0x56d
```

**Comment by seiflotfy** [comment]
Im on it
