### ISSUE TITLE
[0.12.1] Panic on `count` query

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/influxdb#6472]
### Bug report

Influx Version: 0.12.1
OS: Ubuntu 14.04

Ran into a panic when running a routine query. [Full Stack Trace](https://gist.github.com/jayengee/f4aa5aa2693f04be9ee33610af502681#file-influx-crash-log-log)
```
 [query] 2016/04/26 18:16:50 SELECT count(distinct('collection_id')) FROM analytics."default".events
influxdb_1    | panic: interface conversion: influxql.Expr is *influxql.StringLiteral, not *influxql.VarRef
influxdb_1    |
influxdb_1    | goroutine 238 [running]:
influxdb_1    | github.com/influxdata/influxdb/influxql.buildExprIterator(0x7f046af23340, 0xc20a4d0270, 0x7f046af23688, 0xc20a4cec20, 0x7f046af23340, 0xc20a4d0270, 0xf3ad88, 0x0, 0x0, 0xc20a593fa0, ...)
influxdb_1    | 	/tmp/influxdb/src/github.com/influxdata/influxdb/influxql/select.go:224 +0x17e2
influxdb_1    | github.com/influxdata/influxdb/influxql.func·077(0x0, 0x0, 0x0, 0x0)
influxdb_1    | 	/tmp/influxdb/src/github.com/influxdata/influxdb/influxql/select.go:258 +0xa1f
influxdb_1    | github.com/influxdata/influxdb/influxql.buildExprIterator(0x7f046af23340, 0xc20a4d02a0, 0x7f046af23688, 0xc20a4cec20, 0x7f046af23340, 0xc20a4d02a0, 0xf3ad88, 0x0, 0x0, 0xc20a593fa0, ...)
influxdb_1    | 	/tmp/influxdb/src/github.com/influxdata/influxdb/influxql/select.go:351 +0x140e
influxdb_1    | github.com/influxdata/influxdb/influxql.func·076(0x0, 0x0)
influxdb_1    | 	/tmp/influxdb/src/github.com/influxdata/influxdb/influxql/select.go:161 +0x64c
influxdb_1    | github.com/influxdata/influxdb/influxql.buildFieldIterators(0xc208803b28, 0x1, 0x1, 0x7f046af23688, 0xc20a4cec20, 0x0, 0x0, 0xf3ad88, 0x0, 0x0, ...)
influxdb_1    | 	/tmp/influxdb/src/github.com/influxdata/influxdb/influxql/select.go:197 +0x103
influxdb_1    | github.com/influxdata/influxdb/influxql.Select(0xc20b9356c0, 0x7f046af23688, 0xc20a4cec20, 0xc20a4cd500, 0x0, 0x0, 0x0, 0x0, 0x0)
influxdb_1    | 	/tmp/influxdb/src/github.com/influxdata/influxdb/influxql/select.go:81 +0xd7a
influxdb_1    | github.com/influxdata/influxdb/cluster.(*QueryExecutor).executeSelectStatement(0xc20807a120, 0xc20b9356c0, 0x2710, 0x0, 0x2, 0xc20b9267e0, 0xc20b926840, 0x0, 0x0)
influxdb_1    | 	/tmp/influxdb/src/github.com/influxdata/influxdb/cluster/query_executor.go:500 +0x9c5
influxdb_1    | github.com/influxdata/influxdb/cluster.(*QueryExecutor).executeQuery(0xc20807a120, 0xc20a4ce4e0, 0xc20b926708, 0x9, 0x2710, 0xc20b926840, 0xc20b9267e0)
influxdb_1    | 	/tmp/influxdb/src/github.com/influxdata/influxdb/cluster/query_executor.go:146 +0x9c0
influxdb_1    | created by github.com/influxdata/influxdb/cluster.(*QueryExecutor).ExecuteQuery
influxdb_1    | 	/tmp/influxdb/src/github.com/influxdata/influxdb/cluster/query_executor.go:80 +0x8c
```

**Comment by jwilder** [comment]
@jsternberg
