### ISSUE TITLE
Panic on SHOW FIELD KEYS 

### ISSUE THREAD

**Issue by easyrasta** [influxdata/influxdb#6659]
### Bug report

__System info: InfluxDB starting, version 0.13.0~rc2, branch master, commit 590b3f9fc76904c0035ef1e9731ad1c27903ef76

__Steps to reproduce:__
SHOW FIELD KEYS  in admin interface

__Expected behavior:
```
query] 2016/05/18 10:39:45 SELECT fieldKey, fieldType FROM results."default"._fieldKeys
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x18 pc=0x64a412]

goroutine 194 [running]:
panic(0xb62300, 0xc820010070)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/influxdata/influxdb/tsdb.(*fieldKeysIterator).Next(0xc824fda180, 0xc824b40a20, 0x0, 0x0)
	/root/go/src/github.com/influxdata/influxdb/tsdb/shard.go:1019 +0x392
github.com/influxdata/influxdb/influxql.(*floatSortedMergeIterator).pop(0xc824ee0d80, 0x0, 0x0, 0x0)
	/root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:360 +0x190
github.com/influxdata/influxdb/influxql.(*floatSortedMergeIterator).Next(0xc824ee0d80, 0x4, 0x0, 0x0)
	/root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:349 +0x2d
github.com/influxdata/influxdb/influxql.(*floatInterruptIterator).Next(0xc823e6eae0, 0x7f90d07cdf40, 0x0, 0x0)
	/root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:750 +0xb5
github.com/influxdata/influxdb/influxql.(*floatDedupeIterator).Next(0xc823e6eb00, 0x0, 0x0, 0x0)
	/root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:1973 +0x5e
github.com/influxdata/influxdb/influxql.(*bufFloatIterator).Next(0xc823e6eb40, 0xc8254b9d80, 0x0, 0x0)
	/root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:96 +0x69
github.com/influxdata/influxdb/influxql.(*floatAuxIterator).stream(0xc82553ac30)
	/root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:819 +0x2b
created by github.com/influxdata/influxdb/influxql.(*floatAuxIterator).Start
	/root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:781 +0x35
```

__Additional info: I erased some tsm files due to compaction panic error.  If it's related you could close it

**Comment by jwilder** [comment]
@jsternberg Can you take a look?

**Comment by jsternberg** [comment]
This looks to be caused by 733a17d. It seems to be a race condition where the measurement fields are retrieved, then they are erased by something else, then it tries to use them.
