### ISSUE TITLE
Concurrent map read write panic

### ISSUE THREAD

**Issue by arussellsaw** [influxdata/influxdb#6720]
### Bug report

__System info:__ influxdb 0.13, ubuntu 14.04 on AWS 
__Steps to reproduce:__
i've not been able to reproduce this yet

__Expected behavior:__ no panics
__Actual behavior:__ a panic
__Additional info:__
This happened around midnight, roughly 00:00:01, not sure whether that is relevant or not, a concurrent map read/write panic killed the service.

here is the stack trace of the goroutine that panicked.
```
fatal error: concurrent map read and map write

goroutine 13686416 [running]:
runtime.throw(0xd0b3c0, 0x21)
	/usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc84546b0c8 sp=0xc84546b0b0
runtime.mapaccess1_faststr(0xa18d80, 0xc8314475f0, 0xc822c8d770, 0xa, 0xdb79e6)
	/usr/local/go/src/runtime/hashmap_fast.go:202 +0x5b fp=0xc84546b128 sp=0xc84546b0c8
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).buildCursor(0xc849b404d0, 0xc822c8d770, 0xa, 0xc826d6e0c0, 0x4b, 0xc820ed4e00, 0x5, 0x7fedd87b6818, 0xc820ed5fd0, 0x10ed990, ...)
	/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:979 +0x7f fp=0xc84546b2b0 sp=0xc84546b128
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createVarRefSeriesIterator(0xc849b404d0, 0xc820ed5fd0, 0xc823221b60, 0xc826d6e0c0, 0x4b, 0xc830f46190, 0x7fedd87b68c0, 0xc830bc8780, 0xc84e6a68c0, 0x1, ...)
	/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:955 +0x869 fp=0xc84546b6f0 sp=0xc84546b2b0
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createVarRefIterator.func1(0xc849b404d0, 0xc84546bbd0, 0xc820ed5fd0, 0xc84546bba8, 0x0, 0x0)
	/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:862 +0x6d6 fp=0xc84546bb68 sp=0xc84546b6f0
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createVarRefIterator(0xc849b404d0, 0x7fedd87b6818, 0xc820ed5fd0, 0x10ed990, 0x0, 0x0, 0xc820ed4fd0, 0x1, 0x1, 0x0, ...)
	/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:834 +0xa0 fp=0xc84546bbc8 sp=0xc84546bb68
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).CreateIterator(0xc849b404d0, 0x7fedd87b6850, 0xc830daa690, 0x10ed990, 0x0, 0x0, 0xc820ed4fd0, 0x1, 0x1, 0x0, ...)
	/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:746 +0x15f fp=0xc84546be50 sp=0xc84546bbc8
github.com/influxdata/influxdb/tsdb.(*Shard).CreateIterator(0xc830a44900, 0x7fedd87b6850, 0xc830daa690, 0x10ed990, 0x0, 0x0, 0xc820ed4fd0, 0x1, 0x1, 0x0, ...)
	/root/go/src/github.com/influxdata/influxdb/tsdb/shard.go:417 +0x17f fp=0xc84546bf68 sp=0xc84546be50
github.com/influxdata/influxdb/tsdb.(*shardIteratorCreator).CreateIterator(0xc83e31a678, 0x7fedd87b6850, 0xc830daa690, 0x10ed990, 0x0, 0x0, 0xc820ed4fd0, 0x1, 0x1, 0x0, ...)
	/root/go/src/github.com/influxdata/influxdb/tsdb/shard.go:912 +0x6b fp=0xc84546c070 sp=0xc84546bf68
github.com/influxdata/influxdb/influxql.IteratorCreators.CreateIterator.func1(0xc8448aa720, 0x2, 0x2, 0xc84546c470, 0xc84546c360, 0x0, 0x0)
	/root/go/src/github.com/influxdata/influxdb/influxql/iterator.go:523 +0xe1 fp=0xc84546c1f8 sp=0xc84546c070
github.com/influxdata/influxdb/influxql.IteratorCreators.CreateIterator(0xc8448aa720, 0x2, 0x2, 0x7fedd87b6850, 0xc830daa690, 0x10ed990, 0x0, 0x0, 0xc820ed4fd0, 0x1, ...)
	/root/go/src/github.com/influxdata/influxdb/influxql/iterator.go:521 +0xd8 fp=0xc84546c458 sp=0xc84546c1f8
github.com/influxdata/influxdb/influxql.(*IteratorCreators).CreateIterator(0xc8448aa740, 0x7fedd87b6850, 0xc830daa690, 0x10ed990, 0x0, 0x0, 0xc820ed4fd0, 0x1, 0x1, 0x0, ...)
	<autogenerated>:158 +0xed fp=0xc84546c570 sp=0xc84546c458
github.com/influxdata/influxdb/influxql.buildExprIterator.func1(0xc830daa690, 0x7fedd87037b8, 0xc8448aa740, 0xc84546cec8, 0x46be00, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/influxdata/influxdb/influxql/select.go:308 +0xfb4 fp=0xc84546c918 sp=0xc84546c570
github.com/influxdata/influxdb/influxql.buildExprIterator(0x7fedd87b6850, 0xc830daa690, 0x7fedd87037b8, 0xc8448aa740, 0x7fedd87b6850, 0xc830daa690, 0x10ed990, 0x0, 0x0, 0xc820ed4fd0, ...)
	/root/go/src/github.com/influxdata/influxdb/influxql/select.go:406 +0x1cf9 fp=0xc84546cea8 sp=0xc84546c918
github.com/influxdata/influxdb/influxql.buildFieldIterators.func1(0xc83e31a658, 0x1, 0x1, 0x7fedd87037b8, 0xc8448aa740, 0xc84546d268, 0xc820021800, 0xc820ed5fa0, 0x1, 0x1, ...)
	/root/go/src/github.com/influxdata/influxdb/influxql/select.go:179 +0x5d5 fp=0xc84546d0d8 sp=0xc84546cea8
github.com/influxdata/influxdb/influxql.buildFieldIterators(0xc83e31a658, 0x1, 0x1, 0x7fedd87037b8, 0xc8448aa740, 0x0, 0x0, 0x10ed990, 0x0, 0x0, ...)
	/root/go/src/github.com/influxdata/influxdb/influxql/select.go:165 +0x104 fp=0xc84546d240 sp=0xc84546d0d8
github.com/influxdata/influxdb/influxql.Select(0xc8200c08c0, 0x7fedd87037b8, 0xc8448aa740, 0xc84546da78, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/influxdata/influxdb/influxql/select.go:92 +0xd41 fp=0xc84546d610 sp=0xc84546d240
github.com/influxdata/influxdb/cluster.(*StatementExecutor).executeSelectStatement(0xc82000ab40, 0xc8200c08c0, 0xc831e5ceb0, 0x0, 0x0)
	/root/go/src/github.com/influxdata/influxdb/cluster/statement_executor.go:444 +0xaf6 fp=0xc84546db48 sp=0xc84546d610
github.com/influxdata/influxdb/cluster.(*StatementExecutor).ExecuteStatement(0xc82000ab40, 0x7fedd87b6b38, 0xc8200c08c0, 0xc831e5ceb0, 0x0, 0x0)
	/root/go/src/github.com/influxdata/influxdb/cluster/statement_executor.go:43 +0x9e fp=0xc84546dce8 sp=0xc84546db48
github.com/influxdata/influxdb/influxql.(*QueryExecutor).executeQuery(0xc82017c150, 0xc8448aa300, 0xc84dcf637e, 0x7, 0x2710, 0xc61c01, 0xc835a1f380, 0xc835a1f680)
	/root/go/src/github.com/influxdata/influxdb/influxql/query_executor.go:266 +0xdd4 fp=0xc84546df50 sp=0xc84546dce8
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc84546df58 sp=0xc84546df50
created by github.com/influxdata/influxdb/influxql.(*QueryExecutor).ExecuteQuery
	/root/go/src/github.com/influxdata/influxdb/influxql/query_executor.go:166 +0xa5
```

**Comment by whiten** [comment]
I encountered this this morning running 0.13 on Linux 3.18.25. @e-dard, would more logs help, or is what you have from the original report sufficient?

**Comment by e-dard** [comment]
Fixed via https://github.com/influxdata/influxdb/pull/6722
