### ISSUE TITLE
Panic in ReadFloatBlock on 0.14.0~n201605280800

### ISSUE THREAD

**Issue by daviesalex** [influxdata/influxdb#6753]
We are running [run] 2016/05/31 03:08:30 InfluxDB starting, version 0.14.0~n201605280800, branch master, commit dd58101061a964bf36ff8222172399f255e52340 (effectively HEAD).

After 4 days at 02:36 it looks like we started to get messages like 

```
failed to write point batch to database "tg_udp": timeout
```

At 02:47, after one of these, the node panic'd:

```
[query] 2016/05/31 02:47:36 SELECT pointsWritten FROM _internal.monitor.subscriber
[query] 2016/05/31 02:47:36 SELECT count(usage_user) FROM tg_udp."default".cpu WHERE time > 406799h AND time < 406967h - 10m GROUP BY time(10m), dc
[udp] 2016/05/31 02:47:36 failed to write point batch to database "tg_udp": timeout
[query] 2016/05/31 02:47:40 SELECT non_negative_derivative(mean(writes), 2s) FROM tg_udp."default".diskio WHERE host = 'ny4-devol2' AND "name" = 'sdb' AND time > now() - 30m GROUP BY time(2s)
[query] 2016/05/31 02:47:40 SELECT non_negative_derivative(mean(writes), 2s) FROM tg_udp."default".diskio WHERE host = 'ny4-devol1' AND "name" = 'sdb' AND time > now() - 30m GROUP BY time(2s)
[query] 2016/05/31 02:47:40 SELECT non_negative_derivative(mean(writes), 2s) FROM tg_udp."default".diskio WHERE host = 'ny4-devol2' AND "name" = 'sdc' AND time > now() - 30m GROUP BY time(2s)
[query] 2016/05/31 02:47:40 SELECT non_negative_derivative(mean(reads), 2s) FROM tg_udp."default".diskio WHERE host = 'ny4-devol1' AND "name" = 'sdb' AND time > now() - 30m GROUP BY time(2s)
[query] 2016/05/31 02:47:40 SELECT non_negative_derivative(mean(reads), 2s) FROM tg_udp."default".diskio WHERE host = 'ny4-devol2' AND "name" = 'sdb' AND time > now() - 30m GROUP BY time(2s)
[query] 2016/05/31 02:47:41 SELECT non_negative_derivative(mean(reads), 2s) FROM tg_udp."default".diskio WHERE host = 'ny4-devol2' AND "name" = 'sdc' AND time > now() - 30m GROUP BY time(2s)
[tsm1] 2016/05/31 02:47:42 compacted level 1 group (0) into /data/influxdb-data/metrics/tg_udp/default/173/000000324-000000002.tsm.tmp (#0)
[tsm1] 2016/05/31 02:47:42 compacted level 1 group 0 of 2 files into 1 files in 1m54.398255569s
[tsm1] 2016/05/31 02:47:43 beginning level 2 compaction of group 0, 2 TSM files
[tsm1] 2016/05/31 02:47:43 compacting level 2 group (0) /data/influxdb-data/metrics/tg_udp/default/173/000000322-000000002.tsm (#0)
[tsm1] 2016/05/31 02:47:43 compacting level 2 group (0) /data/influxdb-data/metrics/tg_udp/default/173/000000324-000000002.tsm (#1)
[udp] 2016/05/31 02:47:46 failed to write point batch to database "tg_udp": timeout
panic: runtime error: index out of range

goroutine 4172635 [running]:
panic(0xb796c0, 0xc820010060)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*KeyCursor).ReadFloatBlock(0xc9d1fb3180, 0xd4bdc76d20, 0xd4bdc77518, 0xd4bdc77588, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/file_store.gen.go:37 +0xf8b
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*floatAscendingCursor).nextTSM(0xd4bdc76d00)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/iterator.gen.go:382 +0xc0
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*floatAscendingCursor).nextFloat(0xd4bdc76d00, 0x0, 0x4140a7)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/iterator.gen.go:365 +0x158
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*floatIterator).Next(0xd5995af500, 0xdb84129978, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/iterator.gen.go:162 +0x6d
github.com/influxdata/influxdb/influxql.(*floatInterruptIterator).Next(0xda901be620, 0xc002e0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:750 +0xb5
github.com/influxdata/influxdb/influxql.(*bufFloatIterator).Next(0xda901be640, 0x1, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:96 +0x69
github.com/influxdata/influxdb/influxql.(*bufFloatIterator).NextInWindow(0xda901be640, 0x14535508c6443000, 0x14535594790da000, 0xdb84129688, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:102 +0x31
github.com/influxdata/influxdb/influxql.(*floatReduceIntegerIterator).reduce(0xd2fd2c4600, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:1225 +0x1e2
github.com/influxdata/influxdb/influxql.(*floatReduceIntegerIterator).Next(0xd2fd2c4600, 0xca31648390, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:1191 +0x4e
github.com/influxdata/influxdb/influxql.(*bufIntegerIterator).Next(0xda8d322c60, 0x42926e, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:2102 +0x69
github.com/influxdata/influxdb/influxql.(*integerMergeIterator).Next(0xca31648360, 0xca316483c0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:2217 +0x58f
github.com/influxdata/influxdb/influxql.(*integerParallelIterator).monitor(0xd92b4466c0)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:2488 +0x7e
created by github.com/influxdata/influxdb/influxql.newIntegerParallelIterator
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:2460 +0x105
(END)
```

**Comment by e-dard** [comment]
Fixed via #6754

**Comment by e-dard** [comment]
Thanks for the report @daviesalex!

**Comment by daviesalex** [comment]
Thank you for the quick fix @e-dard; we will update to the nightly tomorrow and confirm. Much appreciated.
