### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by forsberg** [influxdata/influxdb#6829]
### Bug report

__System info:__ InfluxDB 1.0.0beta1-1 (Debian package) on Debian Wheezy 64 bit.

This morning, my test Influx installation had crashed with the following traceback:

```
goroutine 621458783 [running]:
panic(0xb7e320, 0xc820010070)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Cache).merged(0xcc6a93bb00, 0xca15a6a460, 0x99, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/cache.go:417 +0x5e1
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Cache).Values(0xcc6a93bb00, 0xca15a6a460, 0x99, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/cache.go:324 +0xa1
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).buildFloatCursor(0xc9f2d1c180, 0xc82945d420, 0x17, 0xc9784692c0, 0x90, 0xc975631625, 0x5, 0x7f18574c0280, 0xc9cd8b7980, 0x1123908, ...)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1254 +0x100
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).buildCursor(0xc9f2d1c180, 0xc82945d420, 0x17, 0xc9784692c0, 0x90, 0xc9cd8b7980, 0x7f18574c0280, 0xc9cd8b7980, 0x1123908, 0x0, ...)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1240 +0x483
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createVarRefSeriesIterator(0xc9f2d1c180, 0xc9cd8b7980, 0xc832b2a0c0, 0xc9784692c0, 0x90, 0xc9e8009e50, 0x0, 0x0, 0x1123908, 0x0, ...)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1179 +0x98f
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createTagSetGroupIterators(0xc9f2d1c180, 0xc9cd8b7980, 0xc832b2a0c0, 0xc9e7ed3450, 0x1, 0x1, 0xc9e8009e50, 0xc9e7ed3470, 0x1, 0x1, ...)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1068 +0x429
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createTagSetIterators.func1(0xcb46f98e00, 0xca5a39f380, 0x1, 0x1, 0xc9f2d1c180, 0xc9cd8b7980, 0xc832b2a0c0, 0xc9e8009e50, 0xcb32e2e380, 0x0)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1023 +0x11a
created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createTagSetIterators
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1024 +0x419
```

Trying to restart it, it takes a very long time to start - the logfile shows some 33 minutes of loading data, then it does nothing. One thread taking 100% CPU, but no activity in logfile for at least 20 minutes. I then killed it with SIGQUIT to get a traceback. Have tried this twice, see logfiles:

[startup-attempt-2.log.txt](https://github.com/influxdata/influxdb/files/311502/startup-attempt-2.log.txt)
[startup-attempt-3.log.txt](https://github.com/influxdata/influxdb/files/311503/startup-attempt-3.log.txt)

This is the same system as in #6799 with a rather large set of series. 

System have some 228G of data.

**Comment by forsberg** [comment]
It did eventually start up and server requests - after 2h. 

[startup-attempt-5.log.txt](https://github.com/influxdata/influxdb/files/311711/startup-attempt-5.log.txt)

Looks like most of the time is spent around these log entries:

> [store] 2016/06/13 10:31:05 /cassandra/influxdb/data/cassandra_telegraf/rp_24h/99 opened in 33m9.79514608s
> [tsm1] 2016/06/13 10:57:48 beginning level 1 compaction of group 0, 2 TSM files
> [tsm1] 2016/06/13 10:57:48 compacting level 1 group (0) /cassandra/influxdb/data/telegraf/rp_1h/113/000000001-000000001.tsm (#0)
> [tsm1] 2016/06/13 10:57:48 compacting level 1 group (0) /cassandra/influxdb/data/telegraf/rp_1h/113/000000003-000000001.tsm (#1)
> [tsm1] 2016/06/13 10:57:48 compacted level 1 group (0) into /cassandra/influxdb/data/telegraf/rp_1h/113/000000003-000000002.tsm.tmp (#0)
> [tsm1] 2016/06/13 10:57:48 compacted level 1 group 0 of 2 files into 1 files in 157.721969ms
> [shard] 2016/06/13 11:50:24 /cassandra/influxdb/data/cassandra_telegraf/default/75 database index loaded in 1h26m56.947451674s
> [tsm1] 2016/06/13 11:50:24 compactions enabled for: /cassandra/influxdb/data/cassandra_telegraf/default/75
> [store] 2016/06/13 11:50:24 /cassandra/influxdb/data/cassandra_telegraf/default/75 opened in 1h52m34.333113872s
> [subscriber] 2016/06/13 11:50:24 opened service

This is not so good :-( What's could cause this kind of behaviour?

**Comment by jwilder** [comment]
@forsberg What kind of disks are you using?  SSD?  As I mentioned in https://github.com/influxdata/influxdb/issues/6799#issuecomment-224981544, you have some pretty large series keys and 4.6M series.  The two combined are likely causing your indexes in your TSM files  to be very large which takes more time to scan and load. 

The `/cassandra/influxdb/data/cassandra_telegraf/default/75/` shard looks like it's in an odd state and needs a full compaction to run.  It looks like it has a bunch of files that have exceeded the 2GB size threshold and are being skipped until a full compaction runs.  I suspect each of those files has the several million series each so each file is expensive to load.  Full compactions kick in after the shard has been cold for writes for 24hrs.  You might want to lower that value to an hour or less and see if that helps.

**Comment by daviesalex** [comment]
So I moved our 3.5TB data store to be entirety NVMe, and it started by reading sustained 30,000 4k IOPS @ 7G/second. It almost immediately takes 97% of the RAM in the box (256G). What then seems to happen is it gets close to starting in about an hour, but runs out of RAM. 

One of our developers is going to see if there is some low hanging fruit here to read these files in in >4k chunks, reduce the expensive (in terms of kernel resources/locks) allocations and figure out a way to slightly drop the RAM usage so we have a bit more headroom. The problem in our system is the number of IOPS and page faults, not the size of the files. You can see this from top - despite our system having no swap, kswapd is pegging a core:

```
   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
  9926 influxdb  20   0  3.348t 0.357t 0.335t S  2902 96.9 271:53.45 influxd
   491 root      20   0       0      0      0 R 100.0  0.0   8:30.99 kswapd1
   490 root      20   0       0      0      0 R  76.2  0.0   8:01.34 kswapd0
```

From perf, we are spending time here:

```
  57.90%  [kernel]             [k] osq_lock
   6.36%  [kernel]             [k] mutex_spin_on_owner
   5.42%  [kernel]             [k] default_send_IPI_mask_sequence_phys
   4.31%  [kernel]             [k] call_function_interrupt
   3.83%  [kernel]             [k] llist_add_batch
   3.35%  [kernel]             [k] flush_tlb_func
   2.83%  [kernel]             [k] smp_call_function_many
   2.30%  [kernel]             [k] flush_smp_call_function_queue
   2.12%  [kernel]             [k] llist_reverse_order
   0.98%  [kernel]             [k] __list_del_entry
   0.97%  influxd              [.] github.com/influxdata/influxdb/tsdb/engine/tsm1.(*indirectIndex).UnmarshalBinary
```

One of our developers is going to see if we can improve this with some low hanging fruit.

**Comment by forsberg** [comment]
@jwilder I'm on spinning magnetic disks. 

Seems you were right about the compaction, after starting it up I let it boil for a couple of days and it ran a compaction that took down disk usage from 230G to 64 (!)

It would be very good if long-running stuff like loading index could show some progress somewhere - be it in logs or using some command. I don't like processes that sit for hours using one CPU and you don't know what's up..
