### ISSUE TITLE
Using influx_inspect cause fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by freeseacher** [influxdata/influxdb#6901]
### Bug report

System info: docker influxdb:1.0.0-beta1-alpine, host system debian, 4G memory 1G swap, 

**Steps to reproduce:**
1. influx_inspect dumptsm 000000775-000000006.tsm
2. got fatal error: runtime: out of memory

**Expected behavior:** 
no error
**Actual behavior:** [What actually happened]

```
/data/data/telegraf/default/45 # influx_inspect dumptsmdev 000000775-000000006.tsm
Summary:
  File: 000000775-000000006.tsm
  Time Range: 2016-06-20T00:00:00Z - 2016-06-22T03:08:46Z
  Duration: 51h8m46s   Series: 2510606   File Size: 2149995082

fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xa795c0, 0x16)
        /usr/local/go/src/runtime/panic.go:547 +0x90
runtime.sysMap(0xc8d9150000, 0x100000, 0xc820065d00, 0xcee238)
        /usr/local/go/src/runtime/mem_linux.go:206 +0x9b
runtime.(*mheap).sysAlloc(0xcd4120, 0x100000, 0x4458cc)
        /usr/local/go/src/runtime/malloc.go:429 +0x191
runtime.(*mheap).grow(0xcd4120, 0x8, 0x0)
        /usr/local/go/src/runtime/mheap.go:651 +0x63
runtime.(*mheap).allocSpanLocked(0xcd4120, 0x1, 0x7fb13a58b280)
        /usr/local/go/src/runtime/mheap.go:553 +0x4f6
runtime.(*mheap).alloc_m(0xcd4120, 0x1, 0x32, 0x7fb13a58b280)
        /usr/local/go/src/runtime/mheap.go:437 +0x119
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0xc820065e58)
        /usr/local/go/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0xcd4120, 0x1, 0x10000000032, 0x421a54)
        /usr/local/go/src/runtime/mheap.go:503 +0x63
runtime.(*mcentral).grow(0xcd69d0, 0x0)
        /usr/local/go/src/runtime/mcentral.go:209 +0x93
runtime.(*mcentral).cacheSpan(0xcd69d0, 0x7fb13a58b280)
        /usr/local/go/src/runtime/mcentral.go:89 +0x47d
runtime.(*mcache).refill(0x7fb1baa7c000, 0x32, 0x7fb13a58b280)
        /usr/local/go/src/runtime/mcache.go:119 +0xcc
runtime.mallocgc.func2()
        /usr/local/go/src/runtime/malloc.go:642 +0x2b
runtime.systemstack(0xc8481cc1c0)
        /usr/local/go/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1051

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:245 fp=0xc820038a40 sp=0xc820038a38
runtime.mallocgc(0x2000, 0x0, 0x3, 0x0)
        /usr/local/go/src/runtime/malloc.go:643 +0x869 fp=0xc820038b18 sp=0xc820038a40
runtime.rawmem(0x2000, 0x800)
        /usr/local/go/src/runtime/malloc.go:809 +0x32 fp=0xc820038b40 sp=0xc820038b18
runtime.growslice(0x8655a0, 0xc8d914e000, 0x100, 0x100, 0x101, 0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/slice.go:95 +0x233 fp=0xc820038bb0 sp=0xc820038b40
github.com/influxdata/influxdb/tsdb/engine/tsm1.DecodeFloatBlock(0xc8d9053b01, 0x2eb, 0x2eb, 0xc8d913b800, 0xc820038fd8, 0xc820038ed0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/encoding.go:276 +0x707 fp=0xc820038d10 sp=0xc820038bb0
github.com/influxdata/influxdb/tsdb/engine/tsm1.DecodeBlock(0xc8d9053b00, 0x2ec, 0x2ec, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/encoding.go:144 +0x3a6 fp=0xc820039050 sp=0xc820038d10
main.cmdDumpTsm1dev(0xc82000b410)
        /root/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/tsm.go:561 +0x1867 fp=0xc820039bf8 sp=0xc820039050
main.main()
        /root/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/main.go:115 +0x1cc7 fp=0xc820039f50 sp=0xc820039bf8
runtime.main()
        /usr/local/go/src/runtime/proc.go:188 +0x2b0 fp=0xc820039fa0 sp=0xc820039f50
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820039fa8 sp=0xc820039fa0
```

**Comment by e-dard** [comment]
@freeseacher thanks for the report. I'm not too familiar with `influx_inspect`. It could be that there is some inefficient processing of the TSM file happening.

Could you repeat this, and provide a heap-profile when the tool is a good way into the process? Maybe 40-45 minutes in before it panics?

```
curl -o heap.txt "http://localhost:8086/debug/pprof/heap"
```

**Comment by freeseacher** [comment]
that bug is not connected with influxdb server. that tool can show additional info about tsm file.
i can't understand where do i need to use that command
```
curl -o heap.txt "http://localhost:8086/debug/pprof/heap"
```

**Comment by e-dard** [comment]
@freeseacher eugh, of course. Sorry, I was triaging several issues and was on autopilot somewhat 😉 

We don't have any profiling available with `influx_inspect`. We may have some large tsm-files in-house that we can use with a custom build of `influx_inspect` with profiling.

**Comment by freeseacher** [comment]
I got that issue several times before. every time on server with memory low then 4G.
looks like tool trying lo load all file in memory instead of doing it in step by step basis.

**Comment by fumblehool** [comment]
Hi
I would like to work on this issue. Is anybody currently working on this?

**Comment by e-dard** [comment]
@fumblehool it's should be the case that this issue is now resolved. I'm going to close it out. If you have experienced similar problems with `dumptsm` then please open another issue. Thanks.
