### ISSUE TITLE
influx_inspect behave unexpectedly

### ISSUE THREAD

**Issue by freeseacher** [influxdata/influxdb#6979]
I am using `InfluxDB starting, version 1.1.0~n201607080800, branch master, commit 11d141ae1fadfcac2a36e23d4aa38b36271a5daf`
and got several files in my shard 
```
ls
total 8322768K
-rw-r--r--. 1 influxdb influxdb 2151628717 Jul  8 09:28 000000199-000000006.tsm
-rw-r--r--. 1 influxdb influxdb   14588301 Jul  8 09:28 000000199-000000007.tsm
-rw-r--r--. 1 influxdb influxdb 1762443182 Jul  8 14:09 000000359-000000006.tsm
-rw-r--r--. 1 influxdb influxdb 1052077015 Jul  8 15:20 000000391-000000005.tsm
-rw-r--r--. 1 influxdb influxdb  924707007 Jul  8 15:22 000000407-000000004.tsm
-rw-r--r--. 1 influxdb influxdb  856711382 Jul  8 15:16 000000411-000000003.tsm
-rw-r--r--. 1 influxdb influxdb  856664267 Jul  8 15:22 000000415-000000003.tsm
-rw-r--r--. 1 influxdb influxdb  446262311 Jul  8 15:23 000000417-000000002.tsm
-rw-r--r--. 1 influxdb influxdb  457420487 Jul  8 15:54 000000420-000000002.tsm
```
for each of them i run 
```
influx_inspect dumptsm 000000199-000000006.tsm
Summary:
  File: 000000199-000000006.tsm
  Time Range: 2016-07-08T00:00:00Z - 2016-07-08T06:11:48Z
  Duration: 6h11m48s   Series: 4143767   File Size: 2151628717

Statistics
  Blocks:
    Total: 4143767 Size: 1672955934 Min: 30 Max: 3343 Avg: 403
  Index:
    Total: 4143767 Size: 478672770
  Points:
    Total: 330055216
  Encoding:
    Timestamp: 	none: 0 (0%) 	s8b: 3966488 (95%) 	rle: 177279 (4%) 
    Float: 	none: 0 (0%) 	gor: 4143767 (100%) 
  Compression:
    Per block: 5.07 bytes/point
    Total: 6.52 bytes/point
```
for each of them i got analytics like that. except one file 000000391-000000005.tsm
for it instead of statisctics i got some kind of dump
```
# influx_inspect dumptsm 000000391-000000005.tsm
Summary:
  File: 000000391-000000005.tsm
  Time Range: 2016-07-08T10:54:17Z - 2016-07-08T11:46:53Z
  Duration: 52m36s   Series: 5548123   File Size: 1052077015

  Pos           Min Time                Max Time                Ofs             Size    Key                                                                                     
        Field
  1             2016-07-08T11:33:50Z    2016-07-08T11:46:23Z    5               42      CPU\ |\ Usage,object=SW-CAO-1-10#55507                                                  
        value
  2             2016-07-08T10:59:18Z    2016-07-08T11:44:18Z    47              37      CPU\ |\ Usage,object=SW-CAO-1-104#55605                                                 
        value
  3             2016-07-08T10:56:21Z    2016-07-08T11:46:21Z    84              37      CPU\ |\ Usage,object=SW-CAO-1-105#55606                                                 
        value
  4             2016-07-08T11:00:05Z    2016-07-08T11:45:05Z    121             37      CPU\ |\ Usage,object=SW-CAO-1-106#55607       
.....                
```
influxdb fails and i'm trying to find file with 
```
Jul 08 15:54:18 db01 influxd[6259]: [tsm1] 2016/07/08 15:54:18 compacting level 2 group (0) /var/lib/influxdb/data/noc/d90/161/000000417-000000002.tsm (#0)
Jul 08 15:54:18 db01 influxd[6259]: [tsm1] 2016/07/08 15:54:18 compacting level 2 group (0) /var/lib/influxdb/data/noc/d90/161/000000420-000000002.tsm (#1)
Jul 08 15:54:19 db01 influxd[6259]: panic: runtime error: slice bounds out of range
Jul 08 15:54:19 db01 influxd[6259]: goroutine 801 [running]:
Jul 08 15:54:19 db01 influxd[6259]: panic(0xb89b80, 0xc82000e060)
Jul 08 15:54:19 db01 influxd[6259]: /usr/local/go/src/runtime/panic.go:481 +0x3e6
Jul 08 15:54:19 db01 influxd[6259]: github.com/influxdata/influxdb/tsdb/engine/tsm1.unpackBlock(0x7fba0242c200, 0x71, 0x381889d7, 0x7fba0242c201, 0x72, 0x381889d6, 0x0, 0x0, 0x0)
Jul 08 15:54:19 db01 influxd[6259]: /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/encoding.go:594 +0xe7
Jul 08 15:54:19 db01 influxd[6259]: github.com/influxdata/influxdb/tsdb/engine/tsm1.DecodeFloatBlock(0x7fba0242c200, 0x71, 0x381889d7, 0xcca5c1e800, 0xcc82dbd388, 0xcc82dbd280, 0x0, 0x0, 0x0, 0x0, ...)
Jul 08 15:54:19 db01 influxd[6259]: /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/encoding.go:258 +0x28c
Jul 08 15:54:19 db01 influxd[6259]: github.com/influxdata/influxdb/tsdb/engine/tsm1.DecodeBlock(0x7fba0242c1ff, 0x72, 0x381889d8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Jul 08 15:54:19 db01 influxd[6259]: /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/encoding.go:144 +0x3a6
Jul 08 15:54:19 db01 influxd[6259]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*tsmKeyIterator).combine(0xcc72d2c800, 0xc9ffc0fc00, 0x0, 0x0, 0x0)
Jul 08 15:54:19 db01 influxd[6259]: /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:1002 +0xdec
Jul 08 15:54:19 db01 influxd[6259]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*tsmKeyIterator).merge(0xcc72d2c800)
Jul 08 15:54:19 db01 influxd[6259]: /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:901 +0x12f
Jul 08 15:54:19 db01 influxd[6259]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*tsmKeyIterator).Next(0xcc72d2c800, 0xcc2255ec34)
Jul 08 15:54:19 db01 influxd[6259]: /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:868 +0xbff
Jul 08 15:54:19 db01 influxd[6259]: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).write(0xc8cc0bd3b0, 0xcaa72e9240, 0x3e, 0x7fbaa423d000, 0xcc72d2c800, 0x0, 0x0)
Jul 08 15:54:19 db01 influxd[6259]: /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:607 +0x53b
```
error. is that one with dump my one? 
every other have been read with any errors.

**Comment by freeseacher** [comment]
yep. seems yes. after about half hour i got
```
  5477018	2016-07-08T11:45:09Z	2016-07-08T11:45:09Z	394824589	34	Interface\ |\ Packets\ |\ r								
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0x749440, 0xc820010110)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/influxdata/influxdb/tsdb/engine/tsm1.unpackBlock(0xc871d6dd81, 0x71, 0x71, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/encoding.go:591 +0xee
github.com/influxdata/influxdb/tsdb/engine/tsm1.DecodeFloatBlock(0xc871d6dd81, 0x71, 0x71, 0xc8a772c800, 0xc820051068, 0xc820050f60, 0x0, 0x0, 0x0, 0x0, ...)
	/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/encoding.go:258 +0x28c
github.com/influxdata/influxdb/tsdb/engine/tsm1.DecodeBlock(0xc871d6dd80, 0x72, 0x72, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/encoding.go:144 +0x3a6
main.cmdDumpTsm1(0xc82000a7b0)
	/root/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/tsm.go:178 +0x1867
main.main()
	/root/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/main.go:85 +0x1533
``

**Comment by freeseacher** [comment]
so, i got output from `influx_inspect dumptsm` how can i import it to a new file ?

**Comment by jsternberg** [comment]
Is this still happening? I think at the time that this issue was created, there was a `dumptsm` and `dumptsmdev` and `dumptsm` was for an earlier version of the format and it would panic. Since then, I've removed `dumptsm` and renamed `dumptsmdev` to `dumptsm`.

I'm going to close this for now since I'm guessing that's the reason and it will work properly now. if you find it still doesn't work, please comment and I can reopen this.
