### ISSUE TITLE
InfluxDB crashes during backups for one database in one environment, not another.

### ISSUE THREAD

**Issue by evanrich** [influxdata/influxdb#7044]
**Systeminfo:
Debian 8.3 x64
InfluxDB v 0.11.1 (can't upgrade due to cluster support being dropped)
AWS c4.xlarge**

When I run backups of our collectd database in our production environment, I get a panic / influx crash.  Doing the exact same backup in our staging environment on the same database, works.   Backing up our graphite database on both environments works without issue.

We have two environments in AWS, staging and Prod

In our staging environment, the # of series is:

```
root@influxdb-s1:/# influx -database collectd <<< "SHOW SERIES"|wc -l
41731

root@influxdb-s1/# influx -database graphite <<< "SHOW SERIES"|wc -l
149128
```

In production, 

```
root@influxdb-p2:/# influx -database collectd <<< "SHOW SERIES"|wc -l
40047

root@influxdb-p2:/# influx -database graphite <<< "SHOW SERIES"|wc -l
131063
```

So I don't think it's # of series, since the staging environment works for both databases.

The influx logs indicate a panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x636c2f]

goroutine 78720 [running]:
github.com/influxdata/influxdb/tsdb.(*Store).BackupShard(0xc2080680f0, 0x40, 0x0, 0x0, 0x10a7760, 0x7ffaf552e1b8, 0xc20bc80010, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/tsdb/store.go:475 +0x27f
github.com/influxdata/influxdb/services/snapshotter.(*Service).handleConn(0xc208104f00, 0x7ffaf552e0b8, 0xc20bc80010, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/services/snapshotter/service.go:118 +0x22c
github.com/influxdata/influxdb/services/snapshotter.func·001(0x7ffaf552e0b8, 0xc20bc80010)
        /tmp/influxdb/src/github.com/influxdata/influxdb/services/snapshotter/service.go:102 +0xaf
created by github.com/influxdata/influxdb/services/snapshotter.(*Service).serve
        /tmp/influxdb/src/github.com/influxdata/influxdb/services/snapshotter/service.go:105 +0x465

goroutine 1 [chan receive, 548 minutes]:
main.(*Main).Run(0xc20803b700, 0xc20800a010, 0x4, 0x4, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/cmd/influxd/main.go:94 +0x765
main.main()
        /tmp/influxdb/src/github.com/influxdata/influxdb/cmd/influxd/main.go:45 +0xdc

goroutine 6 [syscall, 550 minutes]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 44 [IO wait, 548 minutes]:
net.(*pollDesc).Wait(0xc208010a00, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010a00, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2080109a0, 0xc2082dc000, 0x1000, 0x1000, 0x0, 0x7ffaf552a0d0, 0xc23a787638)
        /usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20802c518, 0xc2082dc000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7ffaf552e168, 0xc20802c518, 0xc20805c108, 0xc2082dc000, 0x1000, 0x1000, 0xaab060, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc20829b3a0, 0xc2082dc000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
        <autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc208105620)
        /usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc208105620, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc20805c0b0)
        /usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 17 [syscall, 550 minutes, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 8 [runnable]:
syscall.Syscall6(0x36, 0xfa, 0x6, 0x1, 0xc20801855c, 0x4, 0x0, 0x0, 0x1, 0x0)
        /usr/local/go/src/syscall/asm_linux_amd64.s:46 +0x5
syscall.setsockopt(0xfa, 0x6, 0x1, 0xc20801855c, 0x4, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_linux_amd64.go:1849 +0x7d
```

But I can't find out why this happens in prod, but not staging.   The panic causes influx to crash and restart on each node, and since we're running backups on 3 nodes, our entire cluster basically restarts.

This seems to be related to the following:

[https://github.com/influxdata/influxdb/issues/3700](url)
[https://github.com/influxdata/influxdb/issues/4139](url)

However those were resolved in 0.9.4 or thereabouts.   If I run a backup and it fails, and immediately run the backup again, it works, so its not 100% reproducible, but i have a cronjob that runs a backup at midnight and I try running it around 9am, so with at least a 9 hour gap in time, it's 100% reproducible.

The cronjob I'm using is

```
0 0 * * * /usr/bin/python /usr/local/bin/influx_to_s3.py --backup collectd --path /var/tmp/backups/
```

which is a custom script I wrote to backup to s3.  The meat of this wrapper that does the backup is

`call(["influxd", "backup", "-database", database_name, "-host", HOST_IP + ":8088", backup_path])`

which translates to

`influxd backup -database collectd -host x.x.x.x:8088 /var/tmp/backups`

**Comment by evanrich** [comment]
syslog also shows the following:

```
Jul 21 09:10:26 influxdb-p2 systemd[1]: influxdb.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 21 09:10:26 influxdb-p2 systemd[1]: Unit influxdb.service entered failed state.
Jul 21 09:10:26 influxdb-p2 systemd[1]: influxdb.service holdoff time over, scheduling restart.
Jul 21 09:10:26 influxdb-p2 systemd[1]: Stopping InfluxDB is an open-source, distributed, time series database...
Jul 21 09:10:26 influxdb-p2 systemd[1]: Starting InfluxDB is an open-source, distributed, time series database...
```

**Comment by jwilder** [comment]
`0.11` is no longer maintained.  The [docs](https://docs.influxdata.com/influxdb/v1.0/administration/upgrading/#upgrading-from-0-10-or-0-11-to-1-0) have instructions on how to upgrade to 1.0 and later.
