### ISSUE TITLE
Trace: during exporting db to plaint format

### ISSUE THREAD

**Issue by freeseacher** [influxdata/influxdb#7224]
hi!
during export to line format got error. version
```
# ../influx -version
InfluxDB shell version: 1.1.0~n201608270800
```

with 
```
# influx_inspect export -db noc -rp d90 -out export -dir /var/lib/influxdb/ -start-time 2016-07-25T00:00:00Z -end-time 2016-07-26T00:00:00Z         
    
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc820596c70)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*RWMutex).Lock(0xc820596c68)
	/usr/local/go/src/sync/rwmutex.go:88 +0xa1
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*TSMReader).Close(0xc820596c60, 0x0, 0x0)
	/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/reader.go:312 +0x41
panic(0x7523c0, 0xc820010120)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*mmapAccessor).readAll(0xc8200eac40, 0xc82889c9c0, 0x53, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/reader.go:1159 +0x6e1
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*TSMReader).ReadAll(0xc820596c60, 0xc82889c9c0, 0x53, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/reader.go:295 +0xac
main.(*cmdExport).writeFiles.func1(0xc820067d50, 0xc8200bf8b8, 0xc820105680, 0x3a, 0x0, 0x0)
	/root/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/export.go:173 +0x495
main.(*cmdExport).writeFiles(0xc820067d50, 0x0, 0x0)
	/root/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/export.go:153 +0xf9e
main.(*cmdExport).export(0xc820067d50, 0x0, 0x0)
	/root/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/export.go:90 +0x64
main.(*cmdExport).run(0xc820067d50, 0x0, 0x0)
	/root/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/export.go:83 +0x64
main.main()
	/root/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/main.go:134 +0xa3e
```
chunk file was good http://pastebin.com/h8QN0nUW
according to wc -l i got
``` 
wc -l /tmp/export;ls /tmp/export
1897708571 /tmp/export
-rw-r--r--. 1 root root 202741191906 авг 27 16:19 /tmp/export
```
so looks like export task was done.

**Comment by corylanou** [comment]
Does it deadlock if you perform the export again?  If so, is it possible for us to get the data you are using to see if we can replicate it locally?

**Comment by freeseacher** [comment]
i already doesn't have data that cause problems. sorry.

**Comment by corylanou** [comment]
Ok, closing for now.  The stack trace doesn't line up with the current branch so there is no way to debug without the data to reproduce.  Please re-open if this re-occurs and if possible save the data that caused it for us to reproduce.
