### ISSUE TITLE
Query panic

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb#7751]
Querying with a `WHERE value=1234` causes a panic. (`value` is a field in this case).

The panic is recovered, but we should address the underlying issue.

```
[query] 2016/12/20 12:15:38 SELECT * FROM db.autogen.cpu WHERE value::float = 1341 [panic:runtime error: invalid memory address or nil pointer dereference] goroutine 3567 [running]:
runtime/debug.Stack(0xc42042b6a0, 0xc42124d000, 0x36)
	/usr/local/share/go/src/runtime/debug/stack.go:24 +0x79
github.com/influxdata/influxdb/influxql.(*QueryExecutor).recover(0xc420174630, 0xc42042b6a0, 0xc4213d2660)
	/var/folders/14/s0_v64092sx2q2r93xp_ml4w0000gn/T/tmp.ikfz9V9q/src/github.com/influxdata/influxdb/influxql/query_executor.go:361 +0x96
panic(0x624ca0, 0xc42000c0c0)
	/usr/local/share/go/src/runtime/panic.go:458 +0x243
github.com/influxdata/influxdb/tsdb/index/tsi1.(*seriesExprIterator).Next(0xc421245890, 0x40, 0xc422b34690)
	/var/folders/14/s0_v64092sx2q2r93xp_ml4w0000gn/T/tmp.ikfz9V9q/src/github.com/influxdata/influxdb/tsdb/index/tsi1/tsi1.go:705 +0x29
github.com/influxdata/influxdb/tsdb/index/tsi1.(*Index).TagSets(0xc421282630, 0xc4207cb2c0, 0x3, 0x8, 0x0, 0x0, 0x0, 0xa6b060, 0xc4212457d0, 0xc4214d0930, ...)
	/var/folders/14/s0_v64092sx2q2r93xp_ml4w0000gn/T/tmp.ikfz9V9q/src/github.com/influxdata/influxdb/tsdb/index/tsi1/index.go:987 +0x155
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createVarRefIterator.func1(0xc422b34aa0, 0xc42013c200, 0x0, 0xc4214d0a00, 0xc422b34a70, 0x644700, 0xc421244f90)
	/var/folders/14/s0_v64092sx2q2r93xp_ml4w0000gn/T/tmp.ikfz9V9q/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1324 +0x130
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createVarRefIterator(0xc42013c200, 0x0, 0x0, 0xc421245860, 0x2, 0x2, 0xc4207cb2a0, 0x1, 0x1, 0x0, ...)
	/var/folders/14/s0_v64092sx2q2r93xp_ml4w0000gn/T/tmp.ikfz9V9q/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1345 +0x95
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).CreateIterator(0xc42013c200, 0x0, 0x0, 0xc421245860, 0x2, 0x2, 0xc4207cb2a0, 0x1, 0x1, 0x0, ...)
	/var/folders/14/s0_v64092sx2q2r93xp_ml4w0000gn/T/tmp.ikfz9V9q/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1302 +0x5d8
github.com/influxdata/influxdb/tsdb.(*Shard).CreateIterator(0xc420188600, 0x0, 0x0, 0xc421245860, 0x2, 0x2, 0xc4207cb2a0, 0x1, 0x1, 0x0, ...)
	/var/folders/14/s0_v64092sx2q2r93xp_ml4w0000gn/T/tmp.ikfz9V9q/src/github.com/influxdata/influxdb/tsdb/shard.go:688 +0x159
github.com/influxdata/influxdb/tsdb.(*shardIteratorCreator).CreateIterator(0xc4207cae20, 0x0, 0x0, 0xc421245860, 0x2, 0x2, 0xc4207cb250, 0x1, 0x1, 0x0, ...)
	/var/folders/14/s0_v64092sx2q2r93xp_ml4w0000gn/T/tmp.ikfz9V9q/src/github.com/influxdata/influxdb/tsdb/shard.go:1112 +0x73
github.com/influxdata/influxdb/influxql.IteratorCreators.CreateIterator.func1(0xc420420600, 0xa, 0x10, 0xc422b351c8, 0xc422b35188, 0xa, 0xc4214d10f0)
	/var/folders/14/s0_v64092sx2q2r93xp_ml4w0000gn/T/tmp.ikfz9V9q/src/github.com/influxdata/influxdb/influxql/iterator.go:623 +0x9b
github.com/influxdata/influxdb/influxql.IteratorCreators.CreateIterator(0xc420420600, 0xa, 0x10, 0x0, 0x0, 0xc421245860, 0x2, 0x2, 0xc4207cb250, 0x1, ...)
	/var/folders/14/s0_v64092sx2q2r93xp_ml4w0000gn/T/tmp.ikfz9V9q/src/github.com/influxdata/influxdb/influxql/iterator.go:632 +0xc4
github.com/influxdata/influxdb/influxql.(*IteratorCreators).CreateIterator(0xc4204535c0, 0x0, 0x0, 0xc421245860, 0x2, 0x2, 0xc4207cb250, 0x1, 0x1, 0x0, ...)
	<autogenerated>:165 +0xaf
github.com/influxdata/influxdb/influxql.buildAuxIterators(0xc4207cb270, 0x2, 0x2, 0xa6d1e0, 0xc4204535c0, 0x0, 0x0, 0xc421245860, 0x2, 0x2, ...)
	/var/folders/14/s0_v64092sx2q2r93xp_ml4w0000gn/T/tmp.ikfz9V9q/src/github.com/influxdata/influxdb/influxql/select.go:105 +0x79
github.com/influxdata/influxdb/influxql.Select(0xc4202c6c40, 0xa6d1e0, 0xc4204535c0, 0xc420286cd0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/var/folders/14/s0_v64092sx2q2r93xp_ml4w0000gn/T/tmp.ikfz9V9q/src/github.com/influxdata/influxdb/influxql/select.go:56 +0xfa5
github.com/influxdata/influxdb/coordinator.(*StatementExecutor).createIterators(0xc4200170e0, 0xc420202460, 0xc422b35c58, 0x4c, 0x0, 0x0, 0x4c, 0x6b255, 0xc4207c1a68)
	/var/folders/14/s0_v64092sx2q2r93xp_ml4w0000gn/T/tmp.ikfz9V9q/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:578 +0x51d
github.com/influxdata/influxdb/coordinator.(*StatementExecutor).executeSelectStatement(0xc4200170e0, 0xc420202460, 0xc422b35c58, 0x0, 0x0)
	/var/folders/14/s0_v64092sx2q2r93xp_ml4w0000gn/T/tmp.ikfz9V9q/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:394 +0x75
github.com/influxdata/influxdb/coordinator.(*StatementExecutor).ExecuteStatement(0xc4200170e0, 0xa6ebe0, 0xc420202460, 0x0, 0x23, 0xc4216bb4a0, 0xc4213d2660, 0xc420013270, 0xc4216bb3e0, 0xc4213d23dc, ...)
	/var/folders/14/s0_v64092sx2q2r93xp_ml4w0000gn/T/tmp.ikfz9V9q/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:51 +0x2b06
github.com/influxdata/influxdb/influxql.(*QueryExecutor).executeQuery(0xc420174630, 0xc42042b6a0, 0xc4213d23dc, 0x2, 0x2710, 0x0, 0x0, 0x0, 0xc4213d25a0, 0xc4213d2540, ...)
	/var/folders/14/s0_v64092sx2q2r93xp_ml4w0000gn/T/tmp.ikfz9V9q/src/github.com/influxdata/influxdb/influxql/query_executor.go:311 +0x575
created by github.com/influxdata/influxdb/influxql.(*QueryExecutor).ExecuteQuery
	/var/folders/14/s0_v64092sx2q2r93xp_ml4w0000gn/T/tmp.ikfz9V9q/src/github.com/influxdata/influxdb/influxql/query_executor.go:206 +0xb5
[httpd] 127.0.0.1 - - [20/Dec/2016:12:15:38 +0000] "POST /query?chunked=true&db=db&epoch=ns&q=select+%2A+from+cpu+where+value%3D1341 HTTP/1.1" 200 171 "-" "InfluxDBShell/unknown" 04a501ad-c6ae-11e6-841a-000000000000 1712
```

**Comment by e-dard** [comment]
Ignore (was using the wrong branch!)
