### ISSUE TITLE
Panic in LogEntry.UnmarshalBinary

### ISSUE THREAD

**Issue by jwilder** [influxdata/influxdb#7943]
I simulated an out of disk space type condition when writing `tsl` files which causes the server to panic on restart.

The `gtruncate` calls trims off the last byte of the file.

```
$ INFLUXDB_DATA_INDEX_VERSION=tsi1 influxd
$ influx_stress
$ truncate -s -1 $HOME/.influxdb/data/stress/autogen/1/00000001.tsl
$ influxd
```

You get the following panic:

```
panic: runtime error: slice bounds out of range

goroutine 20 [running]:
github.com/influxdata/influxdb/tsdb/index/tsi1.(*LogEntry).UnmarshalBinary(0xc42004f830, 0x1ce5014, 0xa, 0xa, 0x0, 0x0)
	/Users/jason/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/log_file.go:894 +0x4ef
github.com/influxdata/influxdb/tsdb/index/tsi1.(*LogFile).open(0xc4200e4540, 0xc420016cd0, 0xc420016c80)
	/Users/jason/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/log_file.go:109 +0x28e
github.com/influxdata/influxdb/tsdb/index/tsi1.(*LogFile).Open(0xc4200e4540, 0x2, 0xc4200155c0)
	/Users/jason/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/log_file.go:72 +0x2b
github.com/influxdata/influxdb/tsdb/index/tsi1.(*Index).openLogFile(0xc420304000, 0xc4200155c0, 0x3c, 0xc4200155c0, 0x3c, 0x175de3d)
	/Users/jason/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/index.go:176 +0x61
github.com/influxdata/influxdb/tsdb/index/tsi1.(*Index).Open(0xc420304000, 0x0, 0x0)
	/Users/jason/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/index.go:133 +0x339
github.com/influxdata/influxdb/tsdb.(*Shard).Open.func1(0xc4200de9c0, 0x0, 0x0)
	/Users/jason/go/src/github.com/influxdata/influxdb/tsdb/shard.go:267 +0x1a9
github.com/influxdata/influxdb/tsdb.(*Shard).Open(0xc4200de9c0, 0x1b232c0, 0xc420156840)
	/Users/jason/go/src/github.com/influxdata/influxdb/tsdb/shard.go:305 +0x2f
github.com/influxdata/influxdb/tsdb.(*Store).loadShards.func1(0xc4201c67e0, 0xc42016a280, 0xc4201c6840, 0x174f1e0, 0xc4201666e0, 0xc4201c0dbc, 0x3, 0xc4201b74c0, 0x7, 0xc4201b75b8, ...)
	/Users/jason/go/src/github.com/influxdata/influxdb/tsdb/store.go:229 +0x604
created by github.com/influxdata/influxdb/tsdb.(*Store).loadShards
	/Users/jason/go/src/github.com/influxdata/influxdb/tsdb/store.go:237 +0x84e
```

**Comment by benbjohnson** [comment]
Fixed in c4e9430.
