### ISSUE TITLE
InfluxDB 1.2 does not start when using a directory for typesdb

### ISSUE THREAD

**Issue by rvichery** [influxdata/influxdb#8028]
### Bug report

__System info:__
influxdb.x86_64 0:1.2.0-1
CentOS Linux release 7.2.1511 

__Steps to reproduce:__

1. Configure influxdb to use a typesdb directory in collectd section
2. Restart influxdb (fails with a go stack trace)

__Expected behavior:__ 
Expect to have a running influxdb

__Actual behavior:__
Influxdb does not start and the attach stack trace can be found in the logs

__Additional info:__ 
It looks like a regression as on 1.1 it is working well. The alltypesdb var is not correctly initialized, prior to 1.2, alltypesdb was initialized with alltypesdb := make(gollectd.Types) and now on 1.2, it is initialized with alltypesdb := new(api.TypesDB).

The changes have been introduced in commit 0260dfb when switching to the new go collectd lib.

/var/log/messages
```
Feb 17 19:48:42 localhost influxd: panic: assignment to entry in nil map
Feb 17 19:48:42 localhost influxd: goroutine 1 [running]:
Feb 17 19:48:42 localhost influxd: panic(0xa03aa0, 0xc421ed1c50)
Feb 17 19:48:42 localhost influxd: /usr/local/go/src/runtime/panic.go:500 +0x1a1
Feb 17 19:48:42 localhost influxd: collectd.org/api.(*TypesDB).Merge(0xc4200205c0, 0xc420020628)
Feb 17 19:48:42 localhost influxd: /root/go/src/collectd.org/api/types.go:65 +0xd4
Feb 17 19:48:42 localhost influxd: github.com/influxdata/influxdb/services/collectd.(*Service).Open.func1(0xc4200af5c0, 0x13)
Feb 17 19:48:42 localhost influxd: /root/go/src/github.com/influxdata/influxdb/services/collectd/service.go:140 +0x44e
Feb 17 19:48:42 localhost influxd: github.com/influxdata/influxdb/services/collectd.(*Service).Open(0xc4200b8480, 0x0, 0x0)
Feb 17 19:48:42 localhost influxd: /root/go/src/github.com/influxdata/influxdb/services/collectd/service.go:143 +0xfef
Feb 17 19:48:42 localhost influxd: github.com/influxdata/influxdb/cmd/influxd/run.(*Server).Open(0xc420076dc0, 0xc42000d140, 0xc420076dc0)
Feb 17 19:48:42 localhost influxd: /root/go/src/github.com/influxdata/influxdb/cmd/influxd/run/server.go:433 +0xb7f
Feb 17 19:48:42 localhost influxd: github.com/influxdata/influxdb/cmd/influxd/run.(*Command).Run(0xc420075680, 0xc42000c1d0, 0x3, 0x3, 0x0, 0xc42000c1d0)
Feb 17 19:48:42 localhost influxd: /root/go/src/github.com/influxdata/influxdb/cmd/influxd/run/command.go:117 +0x852
Feb 17 19:48:42 localhost influxd: main.(*Main).Run(0xc42000ca40, 0xc42000c1d0, 0x3, 0x3, 0x0, 0xed0394a98)
Feb 17 19:48:42 localhost influxd: /root/go/src/github.com/influxdata/influxdb/cmd/influxd/main.go:89 +0x18a
Feb 17 19:48:42 localhost influxd: main.main()
Feb 17 19:48:42 localhost influxd: /root/go/src/github.com/influxdata/influxdb/cmd/influxd/main.go:46 +0xb2
Feb 17 19:48:42 localhost systemd: influxdb.service: main process exited, code=exited, status=2/INVALIDARGUMENT
```

**Comment by dgnorton** [comment]
fixed by #8055
