### ISSUE TITLE
panic:unsupported use of *influxql.ParenExpr in a subquery

### ISSUE THREAD

**Issue by jwilder** [influxdata/influxdb#8040]
Occurs on 1.2 branch at 5c1d97e4a07f2796fe8c0798c82c3cbb6e53a4eb

```
create database test
use test
select sum("sub") from (select (max(usage_user::integer) + min(usage_user)) as sub from cpu group by *)
```

```
[E] 2017-02-21T22:32:25Z SELECT sum(sub) FROM (SELECT (max(usage_user::integer) + min(usage_user)) AS sub FROM foo.autogen.cpu GROUP BY *) [panic:unsupported use of *influxql.ParenExpr in a subquery] goroutine 485 [running]:
runtime/debug.Stack(0xc42060a2e0, 0xc420a22180, 0x71)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
github.com/influxdata/influxdb/influxql.(*QueryExecutor).recover(0xc4201ae810, 0xc42060a2e0, 0xc4207204e0)
	/Users/jason/go/src/github.com/influxdata/influxdb/influxql/query_executor.go:362 +0x96
panic(0x161ce40, 0xc4209b8800)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/influxdata/influxdb/influxql.(*exprIteratorBuilder).buildVarRefIterator.func1.1(0xc42015e0a8, 0xc420897580, 0xc42072fa38, 0x4c, 0xc42072f698, 0x1010f72, 0x1f89198)
	/Users/jason/go/src/github.com/influxdata/influxdb/influxql/select.go:667 +0xcd5
github.com/influxdata/influxdb/influxql.(*exprIteratorBuilder).buildVarRefIterator.func1(0xc42072fa38, 0xc42072f8b8, 0xc420897580, 0xc4209b84c0, 0x0)
	/Users/jason/go/src/github.com/influxdata/influxdb/influxql/select.go:669 +0x370
github.com/influxdata/influxdb/influxql.(*exprIteratorBuilder).buildVarRefIterator(0xc42072fa38, 0xc420897580, 0x6f74696e6f6d2f6c, 0x657465722c392f72, 0x6c6f506e6f69746e, 0x696e6f6d3d796369)
	/Users/jason/go/src/github.com/influxdata/influxdb/influxql/select.go:677 +0xae
github.com/influxdata/influxdb/influxql.buildExprIterator(0x1aab960, 0xc420897580, 0x1ca43c0, 0xc42015e088, 0xc4209b82c0, 0x1, 0x1, 0x1aab960, 0xc420897580, 0x1b02a18, ...)
	/Users/jason/go/src/github.com/influxdata/influxdb/influxql/select.go:406 +0x50e
github.com/influxdata/influxdb/influxql.(*exprIteratorBuilder).buildCallIterator.func1.1(0xc420730e70, 0xc420730040, 0xc4208439b0, 0xc4209b80c0, 0x0)
	/Users/jason/go/src/github.com/influxdata/influxdb/influxql/select.go:808 +0x449
github.com/influxdata/influxdb/influxql.(*exprIteratorBuilder).buildCallIterator.func1(0xc4208439b0, 0xc420730e70, 0xbe73, 0x17125e7, 0x7, 0x171391c)
	/Users/jason/go/src/github.com/influxdata/influxdb/influxql/select.go:827 +0x6ed
github.com/influxdata/influxdb/influxql.(*exprIteratorBuilder).buildCallIterator(0xc420730e70, 0xc4208439b0, 0x18, 0xc420897580, 0x0, 0x1f89198)
	/Users/jason/go/src/github.com/influxdata/influxdb/influxql/select.go:933 +0x339
github.com/influxdata/influxdb/influxql.buildExprIterator(0x1aab660, 0xc4208439b0, 0x1ca43c0, 0xc42015e088, 0xc4209e7640, 0x1, 0x1, 0x1aab660, 0xc4208439b0, 0x1b02a18, ...)
	/Users/jason/go/src/github.com/influxdata/influxdb/influxql/select.go:408 +0x482
github.com/influxdata/influxdb/influxql.buildFieldIterators.func1(0xc42015e090, 0x1, 0x1, 0x1ca43c0, 0xc42015e088, 0xc4209e7640, 0x1, 0x1, 0xc4207312e8, 0xc420897500, ...)
	/Users/jason/go/src/github.com/influxdata/influxdb/influxql/select.go:344 +0x1a9
github.com/influxdata/influxdb/influxql.buildFieldIterators(0xc42015e090, 0x1, 0x1, 0x1ca43c0, 0xc42015e088, 0xc4209e7640, 0x1, 0x1, 0x0, 0x0, ...)
	/Users/jason/go/src/github.com/influxdata/influxdb/influxql/select.go:379 +0x10f
github.com/influxdata/influxdb/influxql.buildIterators(0xc420110380, 0x1ca43c0, 0xc42015e088, 0x0, 0x0, 0x1b02a18, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/jason/go/src/github.com/influxdata/influxdb/influxql/select.go:99 +0x6dd
github.com/influxdata/influxdb/influxql.Select(0xc420110380, 0x1ca43c0, 0xc42015e088, 0xc4208ae5a0, 0xc42015e088, 0x0, 0xc42015e088, 0x0, 0x0)
	/Users/jason/go/src/github.com/influxdata/influxdb/influxql/select.go:40 +0x12e
github.com/influxdata/influxdb/coordinator.(*StatementExecutor).createIterators(0xc420169e30, 0xc4201100e0, 0xc420731cf0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/jason/go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:597 +0x5dc
github.com/influxdata/influxdb/coordinator.(*StatementExecutor).executeSelectStatement(0xc420169e30, 0xc4208940e0, 0xc420731cf0, 0x0, 0x0)
	/Users/jason/go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:433 +0x75
github.com/influxdata/influxdb/coordinator.(*StatementExecutor).ExecuteStatement(0xc420169e30, 0x1aaee20, 0xc4208940e0, 0x0, 0x6, 0xc420468cc0, 0xc4207204e0, 0x1ab2820, 0xc420165e60, 0xc420468c00, ...)
	/Users/jason/go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:57 +0x2b02
github.com/influxdata/influxdb/influxql.(*QueryExecutor).executeQuery(0xc4201ae810, 0xc42060a2e0, 0xc4206ae25c, 0x3, 0x2710, 0x0, 0x0, 0x0, 0xc420720480, 0xc420720420, ...)
	/Users/jason/go/src/github.com/influxdata/influxdb/influxql/query_executor.go:312 +0x577
created by github.com/influxdata/influxdb/influxql.(*QueryExecutor).ExecuteQuery
	/Users/jason/go/src/github.com/influxdata/influxdb/influxql/query_executor.go:207 +0xb5
 service=query
```

**Comment by jsternberg** [comment]
Fixed via #8052.
