### ISSUE TITLE
[BUG] panic: runtime error: index out of range selecting tags in subqueries

### ISSUE THREAD

**Issue by zezuladp** [influxdata/influxdb#8075]
InfluxDB 1.2.0
Ubuntu 14.04

The stacktrace is below.
```
panic: runtime error: index out of range

goroutine 1099065 [running]:
panic(0xa03980, 0xc420014090)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/influxdata/influxdb/influxql.(*auxIteratorFields).send(0xc43b506c60, 0xe33460, 0xc426420ea0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.go:510 +0x7b0
github.com/influxdata/influxdb/influxql.(*floatAuxIterator).stream(0xc4379f0700)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:885 +0xd2
created by github.com/influxdata/influxdb/influxql.(*floatAuxIterator).Start
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:860 +0x3f
```

Here is the query I used to get this error. This occurs consistently on my setup
`select * from (select 30*moving_average(used_today,30) from "users" where time > now() - 35d group by userid)`

Here is the design of the measurement (there is a tag on userid):
```
> select * from "users" where time > now() - 2d
name: users
time                days_used new_users total_users used_today userid
----                --------- --------- ----------- ---------- ------
1488182400000000000           1610        29120                     
1488182400000000000 465                              1          <userid>
1488182400000000000 103                              0          <userid>
```

**Comment by jwilder** [comment]
This should be fixed by #7966
