### ISSUE TITLE
Panic in Store.SeriesCardinality

### ISSUE THREAD

**Issue by jwilder** [influxdata/influxdb#8138]
Dropping a very large DB which took a while hit a panic when stats collection ran.

I had a stress DB created w/ in-mem and was running w/ `INFLUXDB_DATA_INDEX_VERSION=tsi1 influxd`

````
[I] 2017-03-14T21:42:39Z SHOW DATABASES service=query
[httpd] 127.0.0.1 - - [14/Mar/2017:15:42:39 -0600] "POST /query?q=SHOW+DATABASES HTTP/1.1" 200 129 "-" "Go-http-client/1.1" 256b560d-08ff-11e7-8001-000000000000 983
[I] 2017-03-14T21:42:39Z DROP DATABASE stress service=query
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe8 pc=0x224e99]

goroutine 59 [running]:
panic(0x650f80, 0xc42000c0c0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/influxdata/influxdb/tsdb.(*Store).SeriesCardinality.func1(0xc4203b2000, 0xc459fd5ae0, 0xc459fd5b00, 0x3, 0x4, 0x8, 0xc4456444f0)
	/Users/jason/go/src/github.com/influxdata/influxdb/tsdb/store.go:717 +0x39
github.com/influxdata/influxdb/tsdb.(*Store).estimateCardinality(0xc42016e3c0, 0xc42043d12c, 0x6, 0x806918, 0xadb710, 0xc4456444f0, 0xc452346168)
	/Users/jason/go/src/github.com/influxdata/influxdb/tsdb/store.go:691 +0xfc
github.com/influxdata/influxdb/tsdb.(*Store).SeriesCardinality(0xc42016e3c0, 0xc42043d12c, 0x6, 0xc4523461e0, 0xc4456444f0, 0x0)
	/Users/jason/go/src/github.com/influxdata/influxdb/tsdb/store.go:718 +0x4b
github.com/influxdata/influxdb/tsdb.(*Store).Statistics(0xc42016e3c0, 0xc4201b86f0, 0x1, 0x1, 0xc459fd55c0)
	/Users/jason/go/src/github.com/influxdata/influxdb/tsdb/store.go:95 +0x13c
github.com/influxdata/influxdb/cmd/influxd/run.(*Server).Statistics(0xc42016e140, 0xc4201b86f0, 0xc420174170, 0x0, 0x0)
	/Users/jason/go/src/github.com/influxdata/influxdb/cmd/influxd/run/server.go:215 +0xeb
github.com/influxdata/influxdb/monitor.(*Monitor).gatherStatistics(0xc420174120, 0xc42015e350, 0x1, 0x1, 0xc4201b86f0, 0x0, 0x0, 0x0)
	/Users/jason/go/src/github.com/influxdata/influxdb/monitor/service.go:321 +0xc9
github.com/influxdata/influxdb/monitor.(*Monitor).Statistics(0xc420174120, 0xc4201b86f0, 0xae3040, 0x2540be400, 0xed05a5ada, 0xc400000000, 0xae3040)
	/Users/jason/go/src/github.com/influxdata/influxdb/monitor/service.go:313 +0xcbf
github.com/influxdata/influxdb/monitor.(*Monitor).storeStatistics(0xc420174120)
	/Users/jason/go/src/github.com/influxdata/influxdb/monitor/service.go:414 +0x425
created by github.com/influxdata/influxdb/monitor.(*Monitor).Open
	/Users/jason/go/src/github.com/influxdata/influxdb/monitor/service.go:125 +0x361
```

**Comment by e-dard** [comment]
Fixed in https://github.com/influxdata/influxdb/commit/bcb36336465e89969b95dec39ad6e5cb399c5152
