### ISSUE TITLE
panic: NO SERIES? cpu

### ISSUE THREAD

**Issue by jwilder** [influxdata/influxdb#8139]
Running w/ `INFLUXDB_DATA_INDEX_VERSION=tsi1 influxd` and `TestServer_Query_DropAndRecreateMeasurement` against this instance produced the panic below.

Easiest way to repro is to build integration tests off of master via
```
go test -o inttests ./tests
```

Then switch to `tis-log-compact` branc, build and run `INFLUXDB_DATA_INDEX_VERSION=tsi1 influxd`.

Then run:
```
URL=http://localhost:8086 ./inttests -test.parallel 1 -test.run TestServer_Query_DropAndRecreateMeasurement
```

```
[I] 2017-03-14T21:49:51Z DROP MEASUREMENT cpu service=query
panic: NO SERIES? cpu

goroutine 126 [running]:
panic(0x61b240, 0xc420e3e0c0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/influxdata/influxdb/tsdb/index/tsi1.(*LogFile).createMeasurementIfNotExists(0xc420e448c0, 0xc420e4c958, 0x3, 0x8, 0xa)
	/Users/jason/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/log_file.go:635 +0x153
github.com/influxdata/influxdb/tsdb/index/tsi1.(*LogFile).execDeleteMeasurementEntry(0xc420e448c0, 0xc4214f5b88)
	/Users/jason/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/log_file.go:505 +0x4f
github.com/influxdata/influxdb/tsdb/index/tsi1.(*LogFile).execEntry(0xc420e448c0, 0xc4214f5b88)
	/Users/jason/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/log_file.go:494 +0x92
github.com/influxdata/influxdb/tsdb/index/tsi1.(*LogFile).DeleteMeasurement(0xc420e448c0, 0xc420e4c958, 0x3, 0x8, 0x0, 0x0)
	/Users/jason/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/log_file.go:215 +0x122
github.com/influxdata/influxdb/tsdb/index/tsi1.(*Index).DropMeasurement.func4(0xc420e448c0, 0xc4214f5c48, 0xc4214f5c58)
	/Users/jason/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/index.go:422 +0x4c
github.com/influxdata/influxdb/tsdb/index/tsi1.(*Index).withLogFile(0xc4201c5600, 0xc4214f5d40, 0xc4201c5600, 0xc420e3e0a0)
	/Users/jason/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/index.go:325 +0x47
github.com/influxdata/influxdb/tsdb/index/tsi1.(*Index).WithLogFile(0xc4201c5600, 0xc4214f5d40, 0x0, 0x0)
	/Users/jason/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/index.go:314 +0x81
github.com/influxdata/influxdb/tsdb/index/tsi1.(*Index).DropMeasurement(0xc4201c5600, 0xc420e4c958, 0x3, 0x8, 0x0, 0x0)
	/Users/jason/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/index.go:423 +0x2d3
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).DeleteMeasurement(0xc420730400, 0xc420e4c958, 0x3, 0x8, 0x8, 0xc420e4c958)
	/Users/jason/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:891 +0x153
github.com/influxdata/influxdb/tsdb.(*Shard).DeleteMeasurement(0xc4215b24e0, 0xc420e4c958, 0x3, 0x8, 0x3, 0x8)
	/Users/jason/go/src/github.com/influxdata/influxdb/tsdb/shard.go:482 +0x79
github.com/influxdata/influxdb/tsdb.(*Store).DeleteMeasurement.func1(0xc4215b24e0, 0x20002, 0xc420f14794)
	/Users/jason/go/src/github.com/influxdata/influxdb/tsdb/store.go:554 +0x6c
github.com/influxdata/influxdb/tsdb.(*Store).walkShards.func1(0xc420e68e40, 0xc420072900, 0xc4215b24e0)
	/Users/jason/go/src/github.com/influxdata/influxdb/tsdb/store.go:603 +0x48
created by github.com/influxdata/influxdb/tsdb.(*Store).walkShards
	/Users/jason/go/src/github.com/influxdata/influxdb/tsdb/store.go:609 +0x9f
```

**Comment by benbjohnson** [comment]
This check for no series shouldn't have been there. It's valid for a measurement entry in the `tsi1.LogFile` to not have any series if it's a tombstone. Fixed in 1807772.
