### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by lpic10** [influxdata/influxdb#8257]
### Bug report

Issue happened while testing latest nightly build with TSI enabled without trying a a fresh installation.

OS: RHEL 7 (amd64)
InfluxDB version:
1.3.0~n201704050800, branch master, commit abaf42fbab538ec86e2a03e5b885192e496c7d45

The workload is mostly based on 16 kubernetes nodes with telegraf injecting docker/kubernetes/infra metrics. 

```
panic: runtime error: index out of range
goroutine 1959 [running]:
panic(0xa70340, 0xc4200100b0)
/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/influxdata/influxdb/pkg/estimator/hll.variableLengthList.decode(0xc4a2abbd00, 0xff, 0xff, 0xfe, 0x81978, 0x30a, 0xfe)
/root/go/src/github.com/influxdata/influxdb/pkg/estimator/hll/compressed.go:160 +0x67
github.com/influxdata/influxdb/pkg/estimator/hll.(*compressedList).decode(0xc4a8e736a0, 0xfe, 0x81978, 0xc4a8e736a0, 0xff)
/root/go/src/github.com/influxdata/influxdb/pkg/estimator/hll/compressed.go:110 +0x53
github.com/influxdata/influxdb/pkg/estimator/hll.(*iterator).Next(0xc48b891d60, 0xc400081978)
/root/go/src/github.com/influxdata/influxdb/pkg/estimator/hll/compressed.go:19 +0x43
github.com/influxdata/influxdb/pkg/estimator/hll.(*Plus).Merge(0xc4225fe140, 0xedfc40, 0xc48573aeb0, 0x0, 0x0)
/root/go/src/github.com/influxdata/influxdb/pkg/estimator/hll/hll.go:204 +0x21f
github.com/influxdata/influxdb/tsdb/index/tsi1.(*IndexFile).MergeSeriesSketches(0xc56a6eb7c0, 0xedfc40, 0xc4225fe140, 0xedfc40, 0xc4225fe190, 0x0, 0x0)
/root/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/index_file.go:346 +0x52
github.com/influxdata/influxdb/tsdb/index/tsi1.FileSet.SeriesSketches(0xc4a2cccb40, 0x3, 0x3, 0x3, 0x3, 0xc53261bdc0, 0xc48b891ef0, 0x8c4cd8, 0xc420209ea0)
/root/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/file_set.go:569 +0x8d
github.com/influxdata/influxdb/tsdb/index/tsi1.(*Index).SeriesSketches(0xc4bd456a80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/root/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/index.go:547 +0xdf
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).SeriesSketches(0xc4be262f00, 0xc2ab88, 0xc4710237c8, 0x0, 0xedb020, 0xc4238d4d60, 0x0)
/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:340 +0x3d
github.com/influxdata/influxdb/tsdb.(*Shard).SeriesSketches(0xc4710236c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/root/go/src/github.com/influxdata/influxdb/tsdb/shard.go:505 +0xc5
github.com/influxdata/influxdb/tsdb.(*Store).SeriesCardinality.func1(0xc4710236c0, 0xedfc40, 0xc4225fe0a0, 0x0, 0x0, 0x0, 0x0)
/root/go/src/github.com/influxdata/influxdb/tsdb/store.go:716 +0x34
github.com/influxdata/influxdb/tsdb.(*Store).estimateCardinality(0xc420160500, 0xc5018541ef, 0xa, 0xc29e10, 0xf08d70, 0xc4cbcfc7e0, 0xc48b892168)
/root/go/src/github.com/influxdata/influxdb/tsdb/store.go:690 +0xfc
github.com/influxdata/influxdb/tsdb.(*Store).SeriesCardinality(0xc420160500, 0xc5018541ef, 0xa, 0xc48b8921e0, 0xc4cbcfc7e0, 0x0)
/root/go/src/github.com/influxdata/influxdb/tsdb/store.go:717 +0x4b
github.com/influxdata/influxdb/tsdb.(*Store).Statistics(0xc420160500, 0xc4201ccf90, 0x1, 0x1, 0xc420274d40)
/root/go/src/github.com/influxdata/influxdb/tsdb/store.go:95 +0x13c
github.com/influxdata/influxdb/cmd/influxd/run.(*Server).Statistics(0xc4201603c0, 0xc4201ccf90, 0xc42016e140, 0x0, 0x0)
/root/go/src/github.com/influxdata/influxdb/cmd/influxd/run/server.go:216 +0xeb
github.com/influxdata/influxdb/monitor.(*Monitor).gatherStatistics(0xc42016e0f0, 0xc420154008, 0x1, 0x1, 0xc4201ccf90, 0x0, 0x0, 0x0)
/root/go/src/github.com/influxdata/influxdb/monitor/service.go:318 +0xc9
github.com/influxdata/influxdb/monitor.(*Monitor).Statistics(0xc42016e0f0, 0xc4201ccf90, 0xf10b40, 0x6fc23ac00, 0xed076d55c, 0xc500000000, 0xf10b40)
/root/go/src/github.com/influxdata/influxdb/monitor/service.go:310 +0xcc5
github.com/influxdata/influxdb/monitor.(*Monitor).storeStatistics(0xc42016e0f0)
/root/go/src/github.com/influxdata/influxdb/monitor/service.go:411 +0x425
created by github.com/influxdata/influxdb/monitor.(*Monitor).Open
/root/go/src/github.com/influxdata/influxdb/monitor/service.go:122 +0x361
```

**Comment by marchtea** [comment]
same bug here, using latest master branch with `index-version = tsi`

OS: centos 6
InfluxDB Version:
1.3.0 https://github.com/influxdata/influxdb/commit/e17be9f4ba0422a46498b2339bbf7a8a7123cdbe  

I've wrote about 5M points to InfluxDB, and the series cardinality is also about 5M.

panic log is same with lpic10:

```
2017/05/12 19:57:30 tsi1: full compaction complete: file=/data/influxdb/data/app_6/duration_7/217/index/00000165.tsi, t=7.302852881s, sz=46771956
2017/05/12 19:57:30 tsi1: removing index file: file=/data/influxdb/data/app_6/duration_7/217/index/00000162.tsi
2017/05/12 19:57:30 tsi1: removing index file: file=/data/influxdb/data/app_6/duration_7/217/index/00000161.tsi
2017/05/12 19:57:30 tsi1: removing index file: file=/data/influxdb/data/app_6/duration_7/217/index/00000163.tsi
2017/05/12 19:57:30 tsi1: checking for compaction groups: n=5
2017/05/12 19:57:31 tsi1: compacting log file: file=/data/influxdb/data/app_6/duration_7/217/index/00000164.tsl
[httpd] 10.171.21.23 - - [12/May/2017:19:57:31 +0800] "POST /write?consistency=&db=app_6&precision=ns&rp=duration_7 HTTP/1.1" 204 0 "-" "InfluxDBClient" 2db2d82d-370a-11e7-a1c9-000000000000 464914
2017/05/12 19:57:32 tsi1: finished compacting log file: file=/data/influxdb/data/app_6/duration_7/217/index/00000164.tsl, t=737.631368ms, sz=9902465
2017/05/12 19:57:32 tsi1: removing log file: file=/data/influxdb/data/app_6/duration_7/217/index/00000164.tsl
2017/05/12 19:57:32 tsi1: checking for compaction groups: n=6
[httpd] 10.171.21.23 - - [12/May/2017:19:57:33 +0800] "POST /write?consistency=&db=app_6&precision=ns&rp=duration_7 HTTP/1.1" 204 0 "-" "InfluxDBClient" 2f37b0c5-370a-11e7-a1ca-000000000000 252413
[httpd] 10.171.21.23 - - [12/May/2017:19:57:35 +0800] "POST /write?consistency=&db=app_6&precision=ns&rp=duration_7 HTTP/1.1" 204 0 "-" "InfluxDBClient" 3010880d-370a-11e7-a1cb-000000000000 143
[httpd] 10.171.21.23 - - [12/May/2017:19:57:35 +0800] "POST /write?consistency=&db=app_6&precision=ns&rp=duration_7 HTTP/1.1" 204 0 "-" "InfluxDBClient" 30109976-370a-11e7-a1cc-000000000000 137
[httpd] 10.171.21.23 - - [12/May/2017:19:57:35 +0800] "POST /write?consistency=&db=app_6&precision=ns&rp=duration_7 HTTP/1.1" 204 0 "-" "InfluxDBClient" 3010c072-370a-11e7-a1cd-000000000000 153
[httpd] 10.171.21.23 - - [12/May/2017:19:57:35 +0800] "POST /write?consistency=&db=app_6&precision=ns&rp=duration_7 HTTP/1.1" 204 0 "-" "InfluxDBClient" 301477b3-370a-11e7-a1ce-000000000000 92542
[httpd] 10.171.21.23 - - [12/May/2017:19:57:36 +0800] "POST /write?consistency=&db=app_6&precision=ns&rp=duration_7 HTTP/1.1" 204 0 "-" "InfluxDBClient" 309330d0-370a-11e7-a1cf-000000000000 283512
[httpd] 10.171.21.23 - - [12/May/2017:19:57:38 +0800] "POST /write?consistency=&db=app_6&precision=ns&rp=duration_7 HTTP/1.1" 204 0 "-" "InfluxDBClient" 31d837d2-370a-11e7-a1d0-000000000000 273206
panic: runtime error: index out of range

goroutine 452 [running]:
panic(0xa5d1e0, 0xc42000e0b0)
	/Users/summer/.gvm/gos/go1.7.4/src/runtime/panic.go:500 +0x1a1
github.com/influxdata/influxdb/pkg/estimator/hll.variableLengthList.decode(0xc4207cbb00, 0xf9, 0xf9, 0xf8, 0x4340a, 0xb2, 0xf8)
	/Users/summer/code/go/workspace/src/github.com/influxdata/influxdb/pkg/estimator/hll/compressed.go:160 +0x67
github.com/influxdata/influxdb/pkg/estimator/hll.(*compressedList).decode(0xc4262afec0, 0xf8, 0x4340a, 0xc4262afec0, 0xf9)
	/Users/summer/code/go/workspace/src/github.com/influxdata/influxdb/pkg/estimator/hll/compressed.go:110 +0x53
github.com/influxdata/influxdb/pkg/estimator/hll.(*iterator).Next(0xc4895bfd60, 0xc40004340a)
	/Users/summer/code/go/workspace/src/github.com/influxdata/influxdb/pkg/estimator/hll/compressed.go:19 +0x43
github.com/influxdata/influxdb/pkg/estimator/hll.(*Plus).Merge(0xc42acf2e10, 0xe23660, 0xc4650b1db0, 0x0, 0x0)
	/Users/summer/code/go/workspace/src/github.com/influxdata/influxdb/pkg/estimator/hll/hll.go:204 +0x21f
github.com/influxdata/influxdb/tsdb/index/tsi1.(*IndexFile).MergeSeriesSketches(0xc4b93e4640, 0xe23660, 0xc42acf2e10, 0xe23660, 0xc42acf2e60, 0x0, 0x0)
	/Users/summer/code/go/workspace/src/github.com/influxdata/influxdb/tsdb/index/tsi1/index_file.go:355 +0x52
github.com/influxdata/influxdb/tsdb/index/tsi1.FileSet.SeriesSketches(0xc42d93c6c0, 0x6, 0x6, 0x6, 0x6, 0x18, 0xc4200a2180, 0xa59c40, 0xc420af2340)
	/Users/summer/code/go/workspace/src/github.com/influxdata/influxdb/tsdb/index/tsi1/file_set.go:575 +0x8d
github.com/influxdata/influxdb/tsdb/index/tsi1.(*Index).SeriesSketches(0xc42b7f7800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/summer/code/go/workspace/src/github.com/influxdata/influxdb/tsdb/index/tsi1/index.go:544 +0xdf
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).SeriesSketches(0xc426113d40, 0xb73620, 0xc4204002e8, 0xc420af2340, 0xc4200fc1c0, 0xc420af2340, 0x0)
	/Users/summer/code/go/workspace/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:346 +0x3d
github.com/influxdata/influxdb/tsdb.(*Shard).SeriesSketches(0xc4204001c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/summer/code/go/workspace/src/github.com/influxdata/influxdb/tsdb/shard.go:502 +0xc5
github.com/influxdata/influxdb/tsdb.(*Store).SeriesCardinality.func1(0xc4204001c0, 0xc4efd6f820, 0xc420af2340, 0x1, 0x1, 0x8, 0xc452408d20)
	/Users/summer/code/go/workspace/src/github.com/influxdata/influxdb/tsdb/store.go:737 +0x34
github.com/influxdata/influxdb/tsdb.(*Store).estimateCardinality(0xc420220f20, 0xc42968401c, 0x5, 0xb728f8, 0xe4c570, 0xc452408d20, 0xc4895c0168)
	/Users/summer/code/go/workspace/src/github.com/influxdata/influxdb/tsdb/store.go:711 +0xfc
github.com/influxdata/influxdb/tsdb.(*Store).SeriesCardinality(0xc420220f20, 0xc42968401c, 0x5, 0xc4895c01e0, 0xc452408d20, 0x0)
	/Users/summer/code/go/workspace/src/github.com/influxdata/influxdb/tsdb/store.go:738 +0x4b
github.com/influxdata/influxdb/tsdb.(*Store).Statistics(0xc420220f20, 0xc420205020, 0x1, 0x1, 0xc4efd6efc0)
	/Users/summer/code/go/workspace/src/github.com/influxdata/influxdb/tsdb/store.go:95 +0x13c
github.com/influxdata/influxdb/cmd/influxd/run.(*Server).Statistics(0xc42015c3c0, 0xc420205020, 0xc42020c050, 0x0, 0x0)
	/Users/summer/code/go/workspace/src/github.com/influxdata/influxdb/cmd/influxd/run/server.go:215 +0xeb
github.com/influxdata/influxdb/monitor.(*Monitor).gatherStatistics(0xc42020c000, 0xc420af2300, 0x1, 0x1, 0xc420205020, 0x0, 0x0, 0x0)
	/Users/summer/code/go/workspace/src/github.com/influxdata/influxdb/monitor/service.go:318 +0xc9
github.com/influxdata/influxdb/monitor.(*Monitor).Statistics(0xc42020c000, 0xc420205020, 0xe54320, 0x2540be400, 0xed0a79a34, 0xc400000000, 0xe54320)
	/Users/summer/code/go/workspace/src/github.com/influxdata/influxdb/monitor/service.go:310 +0xcc5
github.com/influxdata/influxdb/monitor.(*Monitor).storeStatistics(0xc42020c000)
	/Users/summer/code/go/workspace/src/github.com/influxdata/influxdb/monitor/service.go:411 +0x425
created by github.com/influxdata/influxdb/monitor.(*Monitor).Open
	/Users/summer/code/go/workspace/src/github.com/influxdata/influxdb/monitor/service.go:122 +0x361
 ```

**Comment by jwilder** [comment]
@benbjohnson This should be fixed via #8408 now, right?

**Comment by benbjohnson** [comment]
@jwilder Yes, good catch.

**Comment by nanicpc** [comment]
I have the same "panic error" when querying.  is this fixed already?

```
[I] 2017-09-29T08:34:13Z SELECT bottom(dev, PadID, 2) FROM (SELECT sum(std) AS dev FROM (SELECT stddev(Height) AS std FROM data.autogen.Height WHERE time > now() - 5m GROUP BY time(1m),Family, PadID) WHERE time > now() - 5m GROUP BY time(5m), Family, PadID) service=query
panic: runtime error: index out of range

goroutine 1958367 [running]:
panic(0xa09d20, 0xc42000c0b0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/influxdata/influxdb/influxql.(*floatFilterIterator).Next(0xc4c512b560, 0xc5c47b6b40, 0x10, 0x10)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:2588 +0x2cb
github.com/influxdata/influxdb/influxql.(*floatInterruptIterator).Next(0xc580f238e0, 0xc42049fc00, 0x7f1310413000, 0x0)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:777 +0x52
github.com/influxdata/influxdb/influxql.(*floatFilterIterator).Next(0xc4c512b7a0, 0x0, 0x0, 0xdf8475800)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:2582 +0x58
github.com/influxdata/influxdb/influxql.(*bufFloatIterator).Next(0xc580f23980, 0x0, 0xc5eabe7350, 0x1)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:95 +0x3c
github.com/influxdata/influxdb/influxql.(*floatReduceFloatIterator).reduce(0xc5795a2140, 0x4b00303430384300, 0x3241003033303359, 0x3139323230303043, 0x4d4500584f460030, 0x3241003535313353)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:1046 +0x46
github.com/influxdata/influxdb/influxql.(*floatReduceFloatIterator).Next(0xc5795a2140, 0x4e52415700303131, 0x3239323400474e49, 0x49300049505300)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:1020 +0xa1
github.com/influxdata/influxdb/influxql.(*floatInterruptIterator).Next(0xc580f239c0, 0xc55e8eeea5, 0x5, 0xc55e8eeef0)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:777 +0x52
github.com/influxdata/influxdb/influxql.(*bufFloatIterator).Next(0xc580f239e0, 0xc55e8eed90, 0xe, 0xc55e8f0560)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:95 +0x3c
github.com/influxdata/influxdb/influxql.(*floatReduceFloatIterator).reduce(0xc5795a23c0, 0x18, 0x0, 0x2, 0x2, 0x0)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:1046 +0x46
github.com/influxdata/influxdb/influxql.(*floatReduceFloatIterator).Next(0xc5795a23c0, 0xc415ab4c3e, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:1020 +0xa1
github.com/influxdata/influxdb/influxql.(*floatIntervalIterator).Next(0xc5c47ba600, 0xc5545b4bd0, 0x64b43a, 0xe39d20)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:733 +0x4b
github.com/influxdata/influxdb/influxql.(*floatInterruptIterator).Next(0xc580f23a20, 0xc56a967800, 0x1, 0x0)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:777 +0x52
github.com/influxdata/influxdb/influxql.(*floatInterruptIterator).Next(0xc580f23a40, 0xb, 0x7, 0x3)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:777 +0x52
github.com/influxdata/influxdb/influxql.(*bufFloatIterator).Next(0xc580f23a60, 0xaba352, 0xc5545b4a70, 0xc5b930e790)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:95 +0x3c
github.com/influxdata/influxdb/influxql.(*floatReduceFloatIterator).reduce(0xc5795a2500, 0x0, 0xc5eabe7350, 0x1, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:1046 +0x46
github.com/influxdata/influxdb/influxql.(*floatReduceFloatIterator).Next(0xc5795a2500, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:1020 +0xa1
github.com/influxdata/influxdb/influxql.(*floatInterruptIterator).Next(0xc580f23a80, 0xc5eabeaea0, 0x86c9f2, 0x180001)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:777 +0x52
github.com/influxdata/influxdb/influxql.(*bufFloatIterator).Next(0xc580f23aa0, 0x1b8, 0x86ca23, 0x180001)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:95 +0x3c
github.com/influxdata/influxdb/influxql.(*floatAuxIterator).stream(0xc580f23ae0)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:874 +0x32
created by github.com/influxdata/influxdb/influxql.(*floatAuxIterator).Start
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:860 +0x3f
```

by the way when I run the query with just "bottom(dev,2)" I mean, no tags, it works fine
