### ISSUE TITLE
Cannot allocate memory.

### ISSUE THREAD

**Issue by tau0** [influxdata/influxdb#8284]
Influxdb crashes because of insufficient memory:
https://gist.github.com/tau0/3711456163b7c8b8844dc44922296c8f

But the logs show that the heap in use jumped from 3GB to 6.5Gb in 3 minutes. (HeapInUse ~= Alloc)
<img width="1051" alt="screen shot 2017-04-11 at 14 52 25" src="https://cloud.githubusercontent.com/assets/6191905/24907886/b9bac962-1ec6-11e7-9c0b-f0533388f3ea.png">

As I can see in the logs the problem was during compactification, what can I do to prevent it in the future?

PS: I can attach heap and goroutines profiles, but I don't think this will be helpful, because it's difficult to catch it in the right time.

**Comment by jwilder** [comment]
What version are you running?

**Comment by tau0** [comment]
[I] 2017-04-11T16:53:08Z InfluxDB starting, version 1.2.2, branch master, commit 1bcf3ae74c6b9c4897dab68d513d056277eb24f7

**Comment by keypusher** [comment]
We have seen the same issue on 1.2.2.  Could this be related to recent changes to maximum row limit?

```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xac3afa, 0x16)
        /usr/local/go/src/runtime/panic.go:566 +0x95
runtime.sysMap(0xc3b84c4000, 0x8000, 0xffffff00, 0xe7b998)
        /usr/local/go/src/runtime/mem_linux.go:219 +0x1d0
runtime.(*mheap).mapBits(0xe623a0, 0xd116750000)
        /usr/local/go/src/runtime/mbitmap.go:159 +0xa1
runtime.(*mheap).sysAlloc(0xe623a0, 0x100000, 0x40000f5f27)
        /usr/local/go/src/runtime/malloc.go:408 +0x3a5
runtime.(*mheap).grow(0xe623a0, 0x20, 0x0)
        /usr/local/go/src/runtime/mheap.go:726 +0x62
runtime.(*mheap).allocSpanLocked(0xe623a0, 0x20, 0x0)
        /usr/local/go/src/runtime/mheap.go:630 +0x4f2
runtime.(*mheap).allocStack(0xe623a0, 0x20, 0x1)
        /usr/local/go/src/runtime/mheap.go:597 +0x62
runtime.stackalloc(0xd100040000, 0xd1150e3f90, 0x10000, 0xcb82c05380, 0x0, 0x0)
        /usr/local/go/src/runtime/stack.go:395 +0x2ed
runtime.copystack(0xcb82c05380, 0x40000, 0x410b01)
        /usr/local/go/src/runtime/stack.go:839 +0x83
runtime.newstack()
        /usr/local/go/src/runtime/stack.go:1070 +0x370
runtime.morestack()
        /usr/local/go/src/runtime/asm_amd64.s:366 +0x7f
goroutine 197174 [copystack]:
compress/flate.(*compressor).fillDeflate(0xd1138cc000, 0xd10d5f45a4, 0x13, 0x40, 0x40)
        /usr/local/go/src/compress/flate/deflate.go:122 fp=0xd113e74f70 sp=0xd113e74f68
compress/flate.(*compressor).write(0xd1138cc000, 0xd10d5f45a4, 0x13, 0x40, 0x40, 0x19bcb09b, 0xd1138cc000)
        /usr/local/go/src/compress/flate/deflate.go:547 +0xa6 fp=0xd113e74fb0 sp=0xd113e74f70
compress/flate.(*Writer).Write(0xd1138cc000, 0xd10d5f45a4, 0x13, 0x40, 0x40, 0x19bcb09b, 0x0)
        /usr/local/go/src/compress/flate/deflate.go:702 +0x4b fp=0xd113e74ff8 sp=0xd113e74fb0
compress/gzip.(*Writer).Write(0xcfbaf08e70, 0xd10d5f45a4, 0x13, 0x40, 0x503740, 0xcc78929108, 0xa427a0)
        /usr/local/go/src/compress/gzip/gzip.go:195 +0xc9 fp=0xd113e75048 sp=0xd113e74ff8
github.com/influxdata/influxdb/services/httpd.gzipResponseWriter.Write(0xe29e20, 0xcfbaf08e70, 0xe33560, 0xce7af59ac0, 0xd10d5f45a4, 0x13, 0x40, 0x0, 0x0, 0xd10d5f4580)
        /root/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:999 +0x4f fp=0xd113e75090 sp=0xd113e75048
github.com/influxdata/influxdb/services/httpd.(*gzipResponseWriter).Write(0xce7af59ae0, 0xd10d5f45a4, 0x13, 0x40, 0x40, 0x0, 0x0)
        <autogenerated>:16 +0x8b fp=0xd113e750f0 sp=0xd113e75090
github.com/influxdata/influxdb/services/httpd.(*jsonFormatter).WriteResponse(0xce7af59b20, 0x0, 0x0, 0x0, 0xe2a120, 0xd1061ceb20, 0xce7af59b00, 0x1f4, 0x8dcf)
        /root/go/src/github.com/influxdata/influxdb/services/httpd/response_writer.go:90 +0x211 fp=0xd113e751c0 sp=0xd113e750f0
github.com/influxdata/influxdb/services/httpd.(*responseWriter).WriteResponse(0xce7af59b00, 0x0, 0x0, 0x0, 0xe2a120, 0xd1061ceb20, 0xcc78929320, 0x0, 0xc52f318ae0)
        /root/go/src/github.com/influxdata/influxdb/services/httpd/response_writer.go:55 +0x5a fp=0xd113e75218 sp=0xd113e751c0
github.com/influxdata/influxdb/services/httpd.(*Handler).httpError(0xc4202640a0, 0x7ec6a4c593a0, 0xce7af59b00, 0xab9830, 0x7, 0x1f4)
        /root/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:811 +0x1c3 fp=0xd113e75300 sp=0xd113e75218
github.com/influxdata/influxdb/services/httpd.(*Handler).serveWrite(0xc4202640a0, 0x7ec6a4c593a0, 0xce7af59b00, 0xcfdad980f0, 0xc420098ec0)
        /root/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:671 +0xb79 fp=0xd113e75590 sp=0xd113e75300
github.com/influxdata/influxdb/services/httpd.(*Handler).(github.com/influxdata/influxdb/services/httpd.serveWrite)-fm(0x7ec6a4c593a0, 0xce7af59b00, 0xcfdad980f0, 0xc420098ec0)
        /root/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:130 +0x52 fp=0xd113e755c8 sp=0xd113e75590
github.com/influxdata/influxdb/services/httpd.authenticate.func1(0x7ec6a4c593a0, 0xce7af59b00, 0xcfdad980f0)
        /root/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:978 +0xcb fp=0xd113e75668 sp=0xd113e755c8
net/http.HandlerFunc.ServeHTTP(0xc4204cdba0, 0x7ec6a4c593a0, 0xce7af59b00, 0xcfdad980f0)
        /usr/local/go/src/net/http/server.go:1726 +0x44 fp=0xd113e75690 sp=0xd113e75668
github.com/influxdata/influxdb/services/httpd.(*Handler).responseWriter.func1(0xe35120, 0xce7af59ae0, 0xcfdad980f0)
        /root/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1087 +0xab fp=0xd113e756d8 sp=0xd113e75690
net/http.HandlerFunc.ServeHTTP(0xc4204cdbc0, 0xe35120, 0xce7af59ae0, 0xcfdad980f0)
        /usr/local/go/src/net/http/server.go:1726 +0x44 fp=0xd113e75700 sp=0xd113e756d8
github.com/influxdata/influxdb/services/httpd.gzipFilter.func1(0xe33560, 0xce7af59ac0, 0xcfdad980f0)
        /root/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1023 +0x194 fp=0xd113e75778 sp=0xd113e75700
net/http.HandlerFunc.ServeHTTP(0xc4204cdbe0, 0xe33560, 0xce7af59ac0, 0xcfdad980f0)
        /usr/local/go/src/net/http/server.go:1726 +0x44 fp=0xd113e757a0 sp=0xd113e75778
github.com/influxdata/influxdb/services/httpd.cors.func1(0xe33560, 0xce7af59ac0, 0xcfdad980f0)
        /root/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1061 +0xee fp=0xd113e758f0 sp=0xd113e757a0
net/http.HandlerFunc.ServeHTTP(0xc4204cdc00, 0xe33560, 0xce7af59ac0, 0xcfdad980f0)
        /usr/local/go/src/net/http/server.go:1726 +0x44 fp=0xd113e75918 sp=0xd113e758f0
github.com/influxdata/influxdb/services/httpd.requestID.func1(0xe33560, 0xce7af59ac0, 0xcfdad980f0)
        /root/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1071 +0x138 fp=0xd113e75978 sp=0xd113e75918
net/http.HandlerFunc.ServeHTTP(0xc4204cdc20, 0xe33560, 0xce7af59ac0, 0xcfdad980f0)
        /usr/local/go/src/net/http/server.go:1726 +0x44 fp=0xd113e759a0 sp=0xd113e75978
github.com/influxdata/influxdb/services/httpd.(*Handler).logging.func1(0xe33560, 0xce7af59aa0, 0xcfdad980f0)
        /root/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1079 +0xfa fp=0xd113e75a40 sp=0xd113e759a0
net/http.HandlerFunc.ServeHTTP(0xc4204cdc40, 0xe33560, 0xce7af59aa0, 0xcfdad980f0)
        /usr/local/go/src/net/http/server.go:1726 +0x44 fp=0xd113e75a68 sp=0xd113e75a40
github.com/influxdata/influxdb/services/httpd.(*Handler).recovery.func1(0xe34ae0, 0xcc27de4410, 0xcfdad980f0)
        /root/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1104 +0x148 fp=0xd113e75af0 sp=0xd113e75a68
net/http.HandlerFunc.ServeHTTP(0xc4204cdc60, 0xe34ae0, 0xcc27de4410, 0xcfdad980f0)
        /usr/local/go/src/net/http/server.go:1726 +0x44 fp=0xd113e75b18 sp=0xd113e75af0
github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc420318360, 0xe34ae0, 0xcc27de4410, 0xcfdad980f0)
        /root/go/src/github.com/bmizerany/pat/mux.go:117 +0x63e fp=0xd113e75c40 sp=0xd113e75b18
github.com/influxdata/influxdb/services/httpd.(*Handler).ServeHTTP(0xc4202640a0, 0xe34ae0, 0xcc27de4410, 0xcfdad980f0)
        /root/go/src/github.com/influxdata/influxdb/services/httpd/handler.go:258 +0x38d fp=0xd113e75ca0 sp=0xd113e75c40
net/http.serverHandler.ServeHTTP(0xc5bdd5c880, 0xe34ae0, 0xcc27de4410, 0xcfdad980f0)
        /usr/local/go/src/net/http/server.go:2202 +0x7d fp=0xd113e75ce8 sp=0xd113e75ca0
net/http.(*conn).serve(0xcaf56e2400, 0xe35ca0, 0xc7250c58c0)
        /usr/local/go/src/net/http/server.go:1579 +0x4b7 fp=0xd113e75f48 sp=0xd113e75ce8
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xd113e75f50 sp=0xd113e75f48
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2293 +0x44d

goroutine 1 [chan receive, 9 minutes]:
main.(*Main).Run(0xc42017b2c0, 0xc42000c100, 0x4, 0x4, 0x0, 0xed0885859)
        /root/go/src/github.com/influxdata/influxdb/cmd/influxd/main.go:98 +0x399
main.main()
        /root/go/src/github.com/influxdata/influxdb/cmd/influxd/main.go:46 +0xb2

goroutine 17 [syscall, 14 minutes, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 5 [syscall, 14 minutes]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 66 [IO wait, 14 minutes]:
net.runtime_pollWait(0x7f1671193700, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc420183100, 0x72, 0xc42004c5e8, 0xc420010068)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc420183100, 0xe2e760, 0xc420010068)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).accept(0xc4201830a0, 0x0, 0xe2cca0, 0xc4204bc780)
        /usr/local/go/src/net/fd_unix.go:419 +0x238
net.(*TCPListener).accept(0xc420376030, 0x40000000, 0xc400000000, 0xc42000ca00)
        /usr/local/go/src/net/tcpsock_posix.go:132 +0x2e
net.(*TCPListener).Accept(0xc420376030, 0x0, 0x410b79, 0xc420084538, 0x0)
        /usr/local/go/src/net/tcpsock.go:222 +0x49
github.com/influxdata/influxdb/tcp.(*Mux).Serve(0xc4204de900, 0xe348e0, 0xc420376030, 0xc420376030, 0x0)
        /root/go/src/github.com/influxdata/influxdb/tcp/mux.go:75 +0x93
created by github.com/influxdata/influxdb/cmd/influxd/run.(*Server).Open
        /root/go/src/github.com/influxdata/influxdb/cmd/influxd/run/server.go:367 +0x286

goroutine 261 [select]:
github.com/influxdata/influxdb/tsdb.(*Shard).monitor(0xc4205c4420)
        /root/go/src/github.com/influxdata/influxdb/tsdb/shard.go:918 +0x3b4
created by github.com/influxdata/influxdb/tsdb.(*Shard).Open.func1
        /root/go/src/github.com/influxdata/influxdb/tsdb/shard.go:270 +0x4cd

goroutine 3979 [select]:
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).compactTSMLevel(0xc4205cb560, 0xbb0401, 0x1, 0xc444547020)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1002 +0x162
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).enableLevelCompactions.func2(0xc4205cb560, 0xc444547020)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:217 +0x73
created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).enableLevelCompactions
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:217 +0x13f

goroutine 442 [select]:
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).compactCache(0xc4205ecc60, 0xc4442b82a0)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:962 +0x476
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).enableSnapshotCompactions.func1(0xc4205ecc60, 0xc4442b82a0)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:265 +0x61
created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).enableSnapshotCompactions
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:265 +0xec

goroutine 2652 [select]:
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).compactCache(0xc4202bc900, 0xc4442fa060)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:962 +0x476
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).enableSnapshotCompactions.func1(0xc4202bc900, 0xc4442fa060)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:265 +0x61
created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).enableSnapshotCompactions
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:265 +0xec

...
```

**Comment by tau0** [comment]
So now It crashed again and unable to start at all. It just eats all available memory during loading.
<img width="1374" alt="screen shot 2017-05-26 at 22 35 50" src="https://cloud.githubusercontent.com/assets/6191905/26512779/cf65940e-4270-11e7-8ed4-e63b02ad214f.png">

Any suggestions how to recover it?

**Comment by jwilder** [comment]
If it crashes, can you attach the full stack trace? And the logs from startup?

**Comment by tau0** [comment]
https://gist.github.com/tau0/6cdcc199ad454ac1f3b4478defcc0e5c

**Comment by tau0** [comment]
I think it can be because of shard group duration (which is default), and there are just a lot of shards. But I have no idea how to fix it without losing data. I will try to get a heap profile meanwhile.

**Comment by tau0** [comment]
[heap.txt](https://github.com/influxdata/influxdb/files/1033023/heap.txt)

**Comment by jwilder** [comment]
Can you attach:

```
influx_inspect dumptsm /var/lib/influxdb/data/production/default/823/000000017-000000004.tsm
influx_inspect report -detailed /var/lib/influxdb/data/production/default/823/
```

**Comment by tau0** [comment]
tau0@influxdb00:~$ sudo influx_inspect dumptsm /var/lib/influxdb/data/production/default/823/000000017-000000004.tsm
Summary:
  File: /var/lib/influxdb/data/production/default/823/000000017-000000004.tsm
  Time Range: 2017-04-24T00:00:00Z - 2017-04-30T22:01:08.333012363Z
  Duration: 166h1m8.333012363s   Series: 948075   File Size: 224319077


Statistics
  Blocks:
    Total: 948179 Size: 69144107 Min: 29 Max: 12122 Avg: 72
  Index:
    Total: 948179 Size: 155174957
  Points:
    Total: 12415214
  Encoding:
    Timestamp: 	none: 0 (0%) 	s8b: 241814 (25%) 	rle: 706365 (74%) 
    Float: 	none: 0 (0%) 	gor: 948179 (100%) 
  Compression:
    Per block: 5.57 bytes/point
    Total: 18.07 bytes/point

[result.txt](https://github.com/influxdata/influxdb/files/1033029/result.txt) - I removed tag names because they contain some private information.

**Comment by tau0** [comment]
I see that there are some high cardinality tags.

**Comment by jwilder** [comment]
Yeah, it looks like your cardinality is getting high and probably pushing your working set up against your memory limits.  It looks like you do not have any swap enabled so any allocation that would exceed your physical memory (even temporarily) will cause the server to crash.

From the logs, there were several shards needing a full compactions and one of them hit a memory allocation panic which cause the crash.

If you are running the nightly, you can try setting:

```
[data]
max-concurrent-compactions = 1
```

which will limit the number of full/level number of compactions running across shards.  That might ease some of the memory pressure.  Your schema may need to be adjusted to limit your cardinality a bit though or you may just need more RAM for you data size.

**Comment by tau0** [comment]
Okey, thank you for your help, It saved me half of a night. :) I will try to add swap and add this line to he config.

**Comment by jwilder** [comment]
Closing since there isn't anything do to do here.  If you are still running into issues w/ the current nightly, we can re-open.
