### ISSUE TITLE
1.2 panic on selecting top from subquery

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#8360]
Observed on 1.2 branch at commit e59d3f9f0b73ed312cae158f654990afa486b6ac.

Insert this data:

```
cpu,region=west,host=w u=1
cpu,region=west,host=w u=2
cpu,region=west,host=w u=3
cpu,region=east,host=e u=10
cpu,region=east,host=e u=20
cpu,region=east,host=e u=30
```

Execute this query:

```
select top(m, host, 3) from (select mean(u) as m from cpu)
```

Then the server process panics with:
```
panic: runtime error: index out of range

goroutine 126 [running]:
panic(0x60b480, 0xc42000c180)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1
github.com/influxdata/influxdb/influxql.filterFloatByUniqueTags(0xc421351ce0, 0x1, 0x1, 0xc4221dd9b8, 0x1, 0x1, 0x7b4788, 0xc421351ce0, 0xa3cd60, 0x1121989da0)
	/Users/mr/go/src/github.com/influxdata/influxdb/influxql/call_iterator.go:1020 +0x2b6
github.com/influxdata/influxdb/influxql.NewFloatTopReduceSliceFunc.func1(0xc421351ce0, 0x1, 0x1, 0xc421b69ba8, 0xc421b69c98, 0xc421b69c98)
	/Users/mr/go/src/github.com/influxdata/influxdb/influxql/call_iterator.go:814 +0x45b
github.com/influxdata/influxdb/influxql.(*FloatSliceFuncReducer).Emit(0xc421d848e0, 0xc421b69ba8, 0xc4201d80e9, 0x3)
	/Users/mr/go/src/github.com/influxdata/influxdb/influxql/functions.gen.go:111 +0x44
github.com/influxdata/influxdb/influxql.(*floatReduceFloatIterator).reduce(0xc4201863c0, 0xc420028ef0, 0x0, 0x18, 0xc420028f70, 0x46e312)
	/Users/mr/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:1107 +0x807
github.com/influxdata/influxdb/influxql.(*floatReduceFloatIterator).Next(0xc4201863c0, 0xc4201a0000, 0x20002, 0xc420028f6c)
	/Users/mr/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:1020 +0xa1
github.com/influxdata/influxdb/influxql.(*floatInterruptIterator).Next(0xc421d84800, 0x46e286, 0x180001, 0x0)
	/Users/mr/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:777 +0x52
github.com/influxdata/influxdb/influxql.(*bufFloatIterator).Next(0xc421d84820, 0x46e2b4, 0x180001, 0x0)
	/Users/mr/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:95 +0x3c
github.com/influxdata/influxdb/influxql.(*floatAuxIterator).stream(0xc421d84860)
	/Users/mr/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:874 +0x32
created by github.com/influxdata/influxdb/influxql.(*floatAuxIterator).Start
	/Users/mr/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:860 +0x3f
exit status 2
```

The same query on master as of 0b018caf876ae3c6fdb1b9816cc6bcf0301763a1 does **not** panic.

**Comment by mark-rushakoff** [comment]
This is not a new regression. The same data and query panics on 1.2.0, 1.2.1, 1.2.2, and 1.2.3 tags as well.

**Comment by jsternberg** [comment]
Can you try master? It may have gotten fixed by #8081, but this one may have slipped through since `host` isn't available in the subquery.

**Comment by mark-rushakoff** [comment]
That query did not panic on master as of 0b018ca (May 4). I didn't bisect to see the exact commit where it stopped panicking.

**Comment by jsternberg** [comment]
Then I'm going to close the issue for the moment. It seems like it got resolved with the general refactor of that section of code.

**Comment by mark-rushakoff** [comment]
This panic takes down the 1.2 server process; it is not a recovered panic inside a query.

**Comment by jsternberg** [comment]
@rbetts is the non-recoverable panic worth trying to mitigate for 1.2 and worth a release?

**Comment by rbetts** [comment]
I’m content to leave this unfixed on 1.2 given the scope of changes to the sub-query implementation between 1.2 and 1.3. We’ve been advising users with subquery issues to move to 1.3 for performance reasons as well.
