### ISSUE TITLE
Influxdb crash when subquery with top

### ISSUE THREAD

**Issue by ragonlan** [influxdata/influxdb#8401]
### Bug report

__System info:__  Influxdb 1.2.2-1 amd64 in Debian 8.7

__Steps to reproduce:__

1. We feed influx with statsfeeder data from vcenter. This data is stored in a database named statsfeeder
2. Connection command: influx -precision rfc3339 -database statsfeeder
3. Successful example:
```
 SELECT top("meanBroadcastTx", 6) FROM (SELECT mean("value") as meanBroadcastTx FROM "net.broadcastTx.summation" WHERE "platform" = 'vpar4' AND "type" = 'VirtualMachine' AND value > 0 AND time > now() - 30m GROUP BY "name")
name: net.broadcastTx.summation
time                           top
----                           ---
2017-05-18T11:49:51.253276099Z 16.88888888888889
2017-05-18T11:49:51.253276099Z 8.387096774193548
2017-05-18T11:49:51.253276099Z 8
2017-05-18T11:49:51.253276099Z 6.333333333333333
2017-05-18T11:49:51.253276099Z 5.166666666666667
2017-05-18T11:49:51.253276099Z 4.75
```
3. Crash:
```
 SELECT top("meanBroadcastTx", "name", 6) FROM (SELECT mean("value") as meanBroadcastTx FROM "net.broadcastTx.summation" WHERE "platform" = 'vpar4' AND "type" = 'VirtualMachine' AND value > 0 AND time > now() - 30m GROUP BY "name")
ERR:
```

After this in syslog apears:
```
May 18 14:20:27 influxdb01 influxd[8592]: [I] 2017-05-18T12:20:27Z SELECT top(meanBroadcastTx, "name", 6) FROM (SELECT mean(value) AS meanBroadcastTx FROM statsfeeder.autogen."net.broadcastTx.summation" WHERE platform = 'vpar4' AND type = 'VirtualMachine' AND value > 0 AND time > now() - 30m GROUP BY "name") service=query
May 18 14:20:27 influxdb01 influxd[8592]: panic: runtime error: index out of range
May 18 14:20:27 influxdb01 influxd[8592]: goroutine 22718 [running]:
May 18 14:20:27 influxdb01 influxd[8592]: panic(0xa05e00, 0xc4200100c0)
May 18 14:20:27 influxdb01 influxd[8592]: /usr/local/go/src/runtime/panic.go:500 +0x1a1
May 18 14:20:27 influxdb01 influxd[8592]: github.com/influxdata/influxdb/influxql.filterFloatByUniqueTags(0xc4c60fb000, 0x42, 0x80, 0xc570bdcb58, 0x1, 0x1, 0xbaf198, 0x0, 0x0, 0x1100000000)
May 18 14:20:27 influxdb01 influxd[8592]: /root/go/src/github.com/influxdata/influxdb/influxql/call_iterator.go:1020 +0x2b6
May 18 14:20:27 influxdb01 influxd[8592]: github.com/influxdata/influxdb/influxql.NewFloatTopReduceSliceFunc.func1(0xc4c60fb000, 0x42, 0x80, 0xc54ca43ba8, 0xc54ca43c98, 0xc54ca43c98)
May 18 14:20:27 influxdb01 influxd[8592]: /root/go/src/github.com/influxdata/influxdb/influxql/call_iterator.go:814 +0x45b
May 18 14:20:27 influxdb01 influxd[8592]: github.com/influxdata/influxdb/influxql.(*FloatSliceFuncReducer).Emit(0xc4f0c58780, 0xc54ca43ba8, 0xc4645ba660, 0x19)
May 18 14:20:27 influxdb01 influxd[8592]: /root/go/src/github.com/influxdata/influxdb/influxql/functions.gen.go:111 +0x44
May 18 14:20:27 influxdb01 influxd[8592]: github.com/influxdata/influxdb/influxql.(*floatReduceFloatIterator).reduce(0xc4dc6e88c0, 0xbb0408, 0xc50b673ef8, 0x8, 0xc420216000, 0xc53d3cf1e0)
May 18 14:20:27 influxdb01 influxd[8592]: /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:1107 +0x807
May 18 14:20:27 influxdb01 influxd[8592]: github.com/influxdata/influxdb/influxql.(*floatReduceFloatIterator).Next(0xc4dc6e88c0, 0xc50b673f60, 0x5c406a, 0xc42009e2d0)
May 18 14:20:27 influxdb01 influxd[8592]: /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:1020 +0xa1
May 18 14:20:27 influxdb01 influxd[8592]: github.com/influxdata/influxdb/influxql.(*floatInterruptIterator).Next(0xc4fdbeece0, 0xc4201b7157, 0x7, 0xc569526400)
May 18 14:20:27 influxdb01 influxd[8592]: /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:777 +0x52
May 18 14:20:27 influxdb01 influxd[8592]: github.com/influxdata/influxdb/influxql.(*bufFloatIterator).Next(0xc4fdbeed00, 0xc4cd244c60, 0xc4ffcc4a00, 0xc4ffcc6dc0)
May 18 14:20:27 influxdb01 influxd[8592]: /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:95 +0x3c
May 18 14:20:27 influxdb01 influxd[8592]: github.com/influxdata/influxdb/influxql.(*floatAuxIterator).stream(0xc4fdbeed60)
May 18 14:20:27 influxdb01 influxd[8592]: /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:874 +0x32
May 18 14:20:27 influxdb01 influxd[8592]: created by github.com/influxdata/influxdb/influxql.(*floatAuxIterator).Start
May 18 14:20:27 influxdb01 influxd[8592]: /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:860 +0x3f
May 18 14:20:28 influxdb01 influxd[12679]: 8888888           .d888 888                   8888888b.  888888b.
May 18 14:20:28 influxdb01 influxd[12679]: 888            d88P"  888                   888  "Y88b 888  "88b
May 18 14:20:28 influxdb01 influxd[12679]: 888            888    888                   888    888 888  .88P
May 18 14:20:28 influxdb01 influxd[12679]: 888   88888b.  888888 888 888  888 888  888 888    888 8888888K.
May 18 14:20:28 influxdb01 influxd[12679]: 888   888 "88b 888    888 888  888  Y8bd8P' 888    888 888  "Y88b
May 18 14:20:28 influxdb01 influxd[12679]: 888   888  888 888    888 888  888   X88K   888    888 888    888
May 18 14:20:28 influxdb01 influxd[12679]: 888   888  888 888    888 Y88b 888 .d8""8b. 888  .d88P 888   d88P
May 18 14:20:28 influxdb01 influxd[12679]: 8888888 888  888 888    888  "Y88888 888  888 8888888P"  8888888P"
May 18 14:20:28 influxdb01 influxd[12679]: [I] 2017-05-18T12:20:28Z InfluxDB starting, version 1.2.2, branch master, commit 1bcf3ae74c6b9c4897dab68d513d056277eb24f7
May 18 14:20:28 influxdb01 influxd[12679]: [I] 2017-05-18T12:20:28Z Go version go1.7.4, GOMAXPROCS set to 8
May 18 14:20:28 influxdb01 influxd[12679]: [I] 2017-05-18T12:20:28Z Using configuration at: /etc/influxdb/influxdb.conf
May 18 14:20:28 influxdb01 influxd[12679]: [I] 2017-05-18T12:20:28Z Using data dir: /var/lib/influxdb/data service=store
```

__Expected behavior:__ We try to obtain the top 6 virtual machine with more broadcastTx .

[vars.txt](https://github.com/influxdata/influxdb/files/1010852/vars.txt)

**Comment by jsternberg** [comment]
This is fixed in master and will be in 1.3. Unfortunately, the change was too large that we didn't feel safe backporting it to 1.2.
