### ISSUE TITLE
panic: cannot replace non-contiguous files

### ISSUE THREAD

**Issue by marchtea** [influxdata/influxdb#8459]
### Bug report

I've got this panic with `index=tsi` using latest master branch commit https://github.com/influxdata/influxdb/commit/160fafb6c0328d20d0213b11613ecf68117914f0
and merge the changes in this pull request https://github.com/influxdata/influxdb/pull/8455

OS: centos 6

When panic occurs, influxdb is compacting and have some write requests.
I'm not sure this may related to my data, but the data in these requests have a tag key `tm` using `unix timestamp`, so the series cardinality is very huge. 
Another strange thing is, Influxdb works fine after restart.

log:
```
[httpd] 10.171.21.23 - - [07/Jun/2017:21:31:09 +0800] "POST /write?db=app_6&precision=u&rp=duration_7 HTTP/1.1" 204 0 "-" "-" 915c4a3d-4b85-11e7-82e6-000000000000 4192023
[httpd] 10.171.21.23 - - [07/Jun/2017:21:31:09 +0800] "POST /write?db=app_6&precision=u&rp=duration_7 HTTP/1.1" 204 0 "-" "-" 9135d8f6-4b85-11e7-82e3-000000000000 4446436
[httpd] 10.171.21.23 - - [07/Jun/2017:21:31:10 +0800] "POST /write?db=app_6&precision=u&rp=duration_7 HTTP/1.1" 204 0 "-" "-" 91f4cc7d-4b85-11e7-82f0-000000000000 3197627
[httpd] 10.171.21.23 - - [07/Jun/2017:21:31:13 +0800] "POST /write?db=app_6&precision=u&rp=duration_7 HTTP/1.1" 204 0 "-" "-" 93b2f3c8-4b85-11e7-8301-000000000000 353152
[E] 2017-06-07T13:31:15Z log file compacted index=tsi token=43d62b id=59 elapsed=1.167887121s bytes=13439160 kb_per_sec=11237
[I] 2017-06-07T13:31:15Z performing full compaction index=tsi token=2f06d3 src=59,54 dst=/data/influxdb/data/app_6/duration_7/2707/index/L2-00000061.tsi
[E] 2017-06-07T13:31:15Z log file compacted index=tsi token=a5d47f id=58 elapsed=2.440663854s bytes=26200841 kb_per_sec=10483
panic: cannot replace non-contiguous files

goroutine 3809 [running]:
panic(0xa2f9c0, 0xc543ed80c0)
	/Users/summer/.gvm/gos/go1.7.4/src/runtime/panic.go:500 +0x1a1
github.com/influxdata/influxdb/tsdb/index/tsi1.(*FileSet).MustReplace(0xc47af9c730, 0xc44ee07580, 0x2, 0x2, 0xe363a0, 0xc47ff12dc0, 0x0)
	/Users/summer/code/go/workspace/src/github.com/influxdata/influxdb/tsdb/index/tsi1/file_set.go:82 +0x563
github.com/influxdata/influxdb/tsdb/index/tsi1.(*Index).compactToLevel.func2(0xc42034b880, 0xc4bbed78b0, 0x2, 0x2, 0xc47ff12dc0, 0x0, 0x0)
	/Users/summer/code/go/workspace/src/github.com/influxdata/influxdb/tsdb/index/tsi1/index.go:914 +0xd8
github.com/influxdata/influxdb/tsdb/index/tsi1.(*Index).compactToLevel(0xc42034b880, 0xc4bbed78b0, 0x2, 0x2, 0x2)
	/Users/summer/code/go/workspace/src/github.com/influxdata/influxdb/tsdb/index/tsi1/index.go:922 +0x861
github.com/influxdata/influxdb/tsdb/index/tsi1.(*Index).compact.func1.1(0xc42034b880, 0xc4bbed78b0, 0x2, 0x2, 0x1)
	/Users/summer/code/go/workspace/src/github.com/influxdata/influxdb/tsdb/index/tsi1/index.go:841 +0x8e
created by github.com/influxdata/influxdb/tsdb/index/tsi1.(*Index).compact.func1
	/Users/summer/code/go/workspace/src/github.com/influxdata/influxdb/tsdb/index/tsi1/index.go:850 +0x8b
```

index structure:
```
[root@comm_auto_test_tj0 /data/influxdb/data/app_6/duration_7/2707/index]# ls -lht
total 574M
-rw-r--r-- 1 influxdb influxdb  22M Jun  7 21:31 L2-00000061.tsi
-rw-r--r-- 1 influxdb influxdb  25M Jun  7 21:31 L1-00000058.tsi
-rw-r--r-- 1 influxdb influxdb  731 Jun  7 21:31 MANIFEST
-rw-r--r-- 1 influxdb influxdb 692K Jun  7 21:31 L0-00000060.tsl
-rw-r--r-- 1 influxdb influxdb  13M Jun  7 21:31 L1-00000059.tsi
-rw-r--r-- 1 influxdb influxdb  13M Jun  7 21:31 L1-00000054.tsi
-rw-r--r-- 1 influxdb influxdb  59M Jun  7 21:30 L3-00000056.tsi
-rw-r--r-- 1 influxdb influxdb  43M Jun  7 21:30 L2-00000057.tsi
-rw-r--r-- 1 influxdb influxdb 128M Jun  7 21:28 L4-00000047.tsi
-rw-r--r-- 1 influxdb influxdb 272M Jun  7 21:27 L5-00000040.tsi

```

**Comment by marchtea** [comment]
I hit this panic again. After reading code and log, it seems like `compact` function works wrong.
In log, `compact` process two files in L1:
```
[I] 2017-06-07T13:31:15Z performing full compaction index=tsi token=2f06d3 src=59,54 dst=/data/influxdb/data/app_6/duration_7/2707/index/L2-00000061.tsi
```

But, file structure shows that, there is `L1-58` exists:
```
-rw-r--r-- 1 influxdb influxdb  25M Jun  7 21:31 L1-00000058.tsi
-rw-r--r-- 1 influxdb influxdb  13M Jun  7 21:31 L1-00000059.tsi
-rw-r--r-- 1 influxdb influxdb  13M Jun  7 21:31 L1-00000054.tsi
```

The reason is that L1-59 has compacted before L1-58 and L1-59 immediately start compacting with L1-54. And `L1-58` is compacted before `compact L1-54, L1-59` calling MustReplace.  

When `compact L1-54,L1-59` calling MustReplace, the Slice in FileSet could be

```
L1-54, L1-58, L1-59
```

And the param calling MustReplace is 
oldFiles = [L1-54, L1-59]

So, panic occurs:

```
        //file_set.go: 79
	// Ensure all old files are contiguous.
	for j := range oldFiles {
		if fs.files[i+j] != oldFiles[j] {
			panic("cannot replace non-contiguous files")
		}
	}
```

Log:
```
[E] 2017-06-07T13:31:15Z log file compacted index=tsi token=43d62b id=59 elapsed=1.167887121s bytes=13439160 kb_per_sec=11237
[I] 2017-06-07T13:31:15Z performing full compaction index=tsi token=2f06d3 src=59,54 dst=/data/influxdb/data/app_6/duration_7/2707/index/L2-00000061.tsi
[E] 2017-06-07T13:31:15Z log file compacted index=tsi token=a5d47f id=58 elapsed=2.440663854s bytes=26200841 kb_per_sec=10483
panic: cannot replace non-contiguous files
```

**Comment by benbjohnson** [comment]
@marchtea Can you show what your `MANIFEST` file contains?

**Comment by benbjohnson** [comment]
@marchtea This should fix the issue: https://github.com/influxdata/influxdb/pull/8468

Can you give a try if you get a chance?

**Comment by marchtea** [comment]
I've restart the process and `MANIFEST` has been changed.
I'll try https://github.com/influxdata/influxdb/pull/8468 today and see if this panic occurred again.

**Comment by marchtea** [comment]
@benbjohnson There is a bug in https://github.com/influxdata/influxdb/pull/8468 
It requires the size of first two file in the same level is greater than min size of next level.
For example, if files in level 1 is 
```
-rw-r--r-- 1 influxdb influxdb  11M Jun  9 17:06 L1-00000028.tsi
-rw-r--r-- 1 influxdb influxdb  12M Jun  9 17:07 L1-00000029.tsi
-rw-r--r-- 1 influxdb influxdb  18M Jun  9 17:07 L1-00000033.tsi
-rw-r--r-- 1 influxdb influxdb  20M Jun  9 17:07 L1-00000034.tsi
-rw-r--r-- 1 influxdb influxdb  13M Jun  9 17:08 L1-00000035.tsi
```
The `for loop` in `index.go:812` will only pick first two files(`L1-00000028.tsi`, ` L1-00000029.tsi). Size of these two files adds to `23MB`, which is less than `24MB` and failed the test in 
```
//index.go:836
		if size < i.levels[level+1].MinSize {
			continue
		}
```
And level one will never be compacted again.

**Comment by benbjohnson** [comment]
@marchtea Good catch. The `MinSize` doesn't make any sense since I added the `MaxIndexMergeCount`. I removed the `MinSize` in 64fa20d. Can you try it again?

**Comment by marchtea** [comment]
@benbjohnson `MinSize` still make sense since it set minimum size for compacting to next level. Otherwise, the `compact` function will start compacting when there are two files in the same level even their size are small.
In my test, the `influxd` is always compacting thus cost all available cpu.

**Comment by marchtea** [comment]
@benbjohnson I still got panic and the reason is the same.
Following is the log info, `index file structure` and `MANIFEST` info.

```
[E] 2017-06-11T10:04:14Z log file compacted index=tsi token=3113fa id=13 elapsed=1.2
73250521s bytes=12504153 kb_per_sec=9590
[I] 2017-06-11T10:04:14Z performing full compaction index=tsi token=9623f5 src=13,8 dst=/data/influxdb/data/app_6/duration_7/2775/index/L2-00000015.tsi
[E] 2017-06-11T10:04:14Z log file compacted index=tsi token=916074 id=12 elapsed=2.292981218s bytes=19859458 kb_per_sec=8457
[httpd] 10.171.21.23 - - [11/Jun/2017:18:04:17 +0800] "POST /write?db=app_6&precision=u&rp=duration_7 HTTP/1.1" 204 0 "-" "-" 54ce3a62-4e8d-11e7-813b-000000000000 379
[httpd] 10.171.21.23 - - [11/Jun/2017:18:04:17 +0800] "POST /write?db=app_6&precision=u&rp=duration_7 HTTP/1.1" 204 0 "-" "-" 54ce4487-4e8d-11e7-813d-000000000000 280
[httpd] 10.171.21.23 - - [11/Jun/2017:18:04:17 +0800] "POST /write?db=app_6&precision=u&rp=duration_7 HTTP/1.1" 204 0 "-" "-" 54ce3de5-4e8d-11e7-813c-000000000000 479
panic: cannot replace non-contiguous files

goroutine 1222 [running]:
panic(0xa2f9e0, 0xc461de54d0)
        /Users/summer/.gvm/gos/go1.7.4/src/runtime/panic.go:500 +0x1a1
github.com/influxdata/influxdb/tsdb/index/tsi1.(*FileSet).MustReplace(0xc466770050, 0xc4821d3240, 0x2, 0x2, 0xe36360, 0xc5a7506000, 0x0)
        /Users/summer/code/go/workspace/src/github.com/influxdata/influxdb/tsdb/index/tsi1/file_set.go:82 +0x563
github.com/influxdata/influxdb/tsdb/index/tsi1.(*Index).compactToLevel.func2(0xc420404fc0, 0xc4951edf40, 0x2, 0x2, 0xc5a7506000, 0x0, 0x0)
        /Users/summer/code/go/workspace/src/github.com/influxdata/influxdb/tsdb/index/tsi1/index.go:918 +0xd8
...
```

```
[root@comm_auto_test_tj0 /data/influxdb/data/app_6/duration_7/2775/index]# ls -lht
total 181M
-rw-r--r-- 1 influxdb influxdb 24M Jun 11 18:04 L2-00000015.tsi
-rw-r--r-- 1 influxdb influxdb 19M Jun 11 18:04 L1-00000012.tsi
-rw-r--r-- 1 influxdb influxdb 12M Jun 11 18:04 L1-00000013.tsi
-rw-r--r-- 1 influxdb influxdb 518 Jun 11 18:04 MANIFEST
-rw-r--r-- 1 influxdb influxdb   0 Jun 11 18:04 L0-00000014.tsl
-rw-r--r-- 1 influxdb influxdb 16M Jun 11 18:04 L1-00000008.tsi
-rw-r--r-- 1 influxdb influxdb 82M Jun 11 18:03 L3-00000010.tsi
-rw-r--r-- 1 influxdb influxdb 30M Jun 11 18:03 L2-00000011.tsi
```

```
{
  "levels": [
    {},
    {
      "m": 33554432,
      "k": 6
    },
    {
      "m": 33554432,
      "k": 6
    },
    {
      "m": 67108864,
      "k": 6
    },
    {
      "m": 134217728,
      "k": 6
    },
    {
      "m": 268435456,
      "k": 6
    },
    {
      "m": 536870912,
      "k": 6
    },
    {
      "m": 1073741824,
      "k": 6
    }
  ],
  "files": [
    "L0-00000014.tsl",
    "L1-00000013.tsi",
    "L1-00000012.tsi",
    "L1-00000008.tsi",
    "L2-00000011.tsi",
    "L3-00000010.tsi"
  ]
}
```

**Comment by marchtea** [comment]
@benbjohnson https://github.com/influxdata/influxdb/commit/64fa20da87121c973493bb056ac0244f4697d6c0 still doesn't fix the bug.
The main changes in https://github.com/influxdata/influxdb/commit/64fa20da87121c973493bb056ac0244f4697d6c0 is to break iteration while it get a log file. But  `Log compacting` is to make `L0-xxxxx.tsl` become `L1-xxxx.tsi`, `fs.files` will only be updated when compaction is done. So when calling `FilesByLevel` by level 1, it can't get a log file to stop iteration.

Take logs in previous comment for example:
When `id=13` is compacted and start checking level1, `index.fs.files` is:
```
L0-00000014.tsl
L2-00000015.tsi
L1-00000013.tsi
L0-00000012.tsl
L1-00000008.tsi
L2-00000011.tsi
L3-00000010.tsi
```
Then, `FilesByLevel(level=1)` will still return `L1-00000013.tsi`, `L1-00000008.tsi`.
After `L0-00000012.tsl` is compacted, it will become `L1-00000012.tsi`, thus cause panic.

**Comment by benbjohnson** [comment]
@marchtea OK, I understand what's going on now. I combined the check for contiguous files with the level filtering so it doesn't skip interspersed level zero files. I pushed the changes up to https://github.com/influxdata/influxdb/pull/8468. Can you give 7a53a5c a try?

I removed the `MinSize` because the maximum number of files to compact is two so if those two files don't reach the `MinSize` then they'll never be compacted. The number was higher before but compacting smaller sets of files seems to work much faster than larger sets.

**Comment by marchtea** [comment]
OK, I've got it. I'll try https://github.com/influxdata/influxdb/commit/7a53a5cadd268bcaf3152de45e8392ec6f15ebf8  today : )
