### ISSUE TITLE
Segmentation fault.

### ISSUE THREAD

**Issue by tau0** [influxdata/influxdb#8473]
Got a segmentation fault on:
`[I] 2017-06-10T11:05:10Z InfluxDB starting, version 1.3.0~n201705270801, branch master,` commit 3b08f65a20863266ac7775818931c537deb0507e

thought that you might be interested if no feel free to close.

Trace:

```
[I] 2017-06-10T11:36:05Z retention policy shard deletion check commencing service=retention
[I] 2017-06-10T11:36:05Z shard ID 873 from database _internal, retention policy monitor, deleted service=retention
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x824f12]

goroutine 75826 [running]:
github.com/influxdata/influxdb/tsdb.(*Shard).ForEachMeasurementTagKey(0xc420378380, 0xc4abe25180, 0x20, 0x20, 0xc4c1176f80, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/tsdb/shard.go:978 +0x92
github.com/influxdata/influxdb/tsdb.(*Store).monitorShards.func2(0xc420378380, 0xc4cd416d20, 0xc433a5df78)
        /root/go/src/github.com/influxdata/influxdb/tsdb/store.go:1117 +0x19c
github.com/influxdata/influxdb/tsdb.(*Store).walkShards.func1(0xc4a95f1cb0, 0xc4cea9b800, 0xc420378380)
        /root/go/src/github.com/influxdata/influxdb/tsdb/store.go:623 +0x48
created by github.com/influxdata/influxdb/tsdb.(*Store).walkShards
        /root/go/src/github.com/influxdata/influxdb/tsdb/store.go:629 +0x97
```

**Comment by hpbieker** [comment]
@jwilder Is the 1.3 available as nightly build now? I would like to test this fix :+1:

**Comment by rbetts** [comment]
@hpbieker There is a 1.3 branch (https://github.com/influxdata/influxdb/tree/1.3) you can build now. Nightly is building `master` I think.

**Comment by hpbieker** [comment]
@rbetts, thanks, but I do not want to compile myself as this is for a production server.
