### ISSUE TITLE
influxdb shutdown and output a lot of logs

### ISSUE THREAD

**Issue by whaon** [influxdata/influxdb#8658]
the influxdb process is down,and the log is like below:
```
goroutine 249358 [runnable]:
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).compactTSMFull(0xc42c906480, 0xc4256fbb60)
	/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1020 +0x145
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).enableLevelCompactions.func1(0xc42c906480, 0xc4256fbb60)
	/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:216 +0x61
created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).enableLevelCompactions
	/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:216 +0x113

goroutine 307706 [runnable]:
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).compactTSMLevel(0xc428b35440, 0xbb0400, 0x3, 0xc4264e4f00)
	/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1002 +0x162
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).enableLevelCompactions.func4(0xc428b35440, 0xc4264e4f00)
	/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:219 +0x73
created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).enableLevelCompactions
	/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:219 +0x197

goroutine 308435 [runnable]:
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).compactTSMFull(0xc42415c6c0, 0xc42622e9c0)
	/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1020 +0x145
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).enableLevelCompactions.func1(0xc42415c6c0, 0xc42622e9c0)
	/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:216 +0x61
created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).enableLevelCompactions
	/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:216 +0x113

goroutine 307704 [runnable]:
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).compactTSMLevel(0xc428b35440, 0xbb0401, 0x1, 0xc4264e4f00)
	/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1002 +0x162
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).enableLevelCompactions.func2(0xc428b35440, 0xc4264e4f00)
	/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:217 +0x73
created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).enableLevelCompactions
	/root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:217 +0x13f
```

**Comment by whaon** [comment]
```
goroutine 295290 [IO wait]:
net.runtime_pollWait(0x7fc4b0577af0, 0x72, 0x114)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc430841c60, 0x72, 0xc421a05a20, 0xc42000c1e0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc430841c60, 0xe2e760, 0xc42000c1e0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc430841c00, 0xc4225d0000, 0x1000, 0x1000, 0x0, 0xe2e760, 0xc42000c1e0)
	/usr/local/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc4209cec90, 0xc4225d0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:173 +0x70
net/http.(*connReader).Read(0xc426e95de0, 0xc4225d0000, 0x1000, 0x1000, 0xc42f8a7168, 0x100000000, 0xc4259ec601)
	/usr/local/go/src/net/http/server.go:586 +0x144
bufio.(*Reader).fill(0xc423608f60)
	/usr/local/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Peek(0xc423608f60, 0x4, 0xab61b2, 0x4, 0x1, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:129 +0x62
net/http.(*conn).readRequest(0xc42f8a7100, 0xe35ca0, 0xc427861ec0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:762 +0xdff
net/http.(*conn).serve(0xc42f8a7100, 0xe35ca0, 0xc427861ec0)
	/usr/local/go/src/net/http/server.go:1532 +0x3d3
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d
goroutine 474805 [IO wait]:
net.runtime_pollWait(0x7fc4b0578270, 0x72, 0x2e)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc4243bed80, 0x72, 0xc428359a20, 0xc42000c1e0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc4243bed80, 0xe2e760, 0xc42000c1e0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc4243bed20, 0xc422974000, 0x1000, 0x1000, 0x0, 0xe2e760, 0xc42000c1e0)
	/usr/local/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc42035ca88, 0xc422974000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:173 +0x70
net/http.(*connReader).Read(0xc428d12e40, 0xc422974000, 0x1000, 0x1000, 0xc422190be8, 0x100000000, 0xc421bdc101)
	/usr/local/go/src/net/http/server.go:586 +0x144
bufio.(*Reader).fill(0xc423b5cde0)
	/usr/local/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Peek(0xc423b5cde0, 0x4, 0xab61b2, 0x4, 0x1, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:129 +0x62
net/http.(*conn).readRequest(0xc422190b80, 0xe35ca0, 0xc421cfa880, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:762 +0xdff
net/http.(*conn).serve(0xc422190b80, 0xe35ca0, 0xc421cfa880)
	/usr/local/go/src/net/http/server.go:1532 +0x3d3
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d

```

**Comment by e-dard** [comment]
Should be fixed in https://github.com/influxdata/influxdb/pull/8847 or an earlier PR.
