### ISSUE TITLE
Variety of errors leading to influxdb service crashes in latest 1.3.2

### ISSUE THREAD

**Issue by Eric-aihua** [influxdata/influxdb#8671]
### Bug report
_System info:

InfluxDB Verison:   version 1.3.2, branch 1.3, commit 742b9cb3d74ff1be4aff45d69ee7c9ba66c02565
OS:  Ubuntu 14.04.5 LTS（Desktop）
Uname:  3.13.0-125-generic #174-Ubuntu SMP Mon Jul 10 18:51:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

__Steps to reproduce:__

1. There is a script that has been generating data
2. There are several chronograf browser windows in query data.(AutoReferesh Interval set to 5s)
3. Point Count:About 1 million
4. Series: About 156000 

__Expected behavior:
Not crash

__Actual behavior:
There are a variety of errors leading to service crashes, probably including the following errors:
**1. panic: runtime error: makeslice: len out of range**
Trace：
```
[I] 2017-08-08T03:13:50Z SELECT dr_pps, in_pps, pa_pps FROM cloudportal.six_months.collapsar_flow WHERE time > now() - 3h service=query
panic: runtime error: makeslice: len out of range

goroutine 32724 [running]:
github.com/influxdata/influxdb/influxql.(*floatSortedMergeIterator).pop(0xc4464f0cf0, 0xc44ffea570, 0xe, 0x0)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:386 +0x504
github.com/influxdata/influxdb/influxql.(*floatSortedMergeIterator).Next(0xc4464f0cf0, 0xa84020, 0xc437678750, 0xc42a262f01)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:351 +0x2b
github.com/influxdata/influxdb/influxql.(*floatInterruptIterator).Next(0xc44d7e1440, 0xe, 0x1, 0x1)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:798 +0x4f
github.com/influxdata/influxdb/influxql.(*floatInterruptIterator).Next(0xc44d7e1460, 0xc437678750, 0xc43f8799d8, 0x0)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:798 +0x4f
github.com/influxdata/influxdb/influxql.(*floatInterruptIterator).Next(0xc44d7e1480, 0xc44ffea570, 0xc43c353940, 0xc44d7e1518)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:798 +0x4f
github.com/influxdata/influxdb/influxql.(*floatInterruptIterator).Next(0xc44d7e14a0, 0xc42a262f98, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:798 +0x4f
github.com/influxdata/influxdb/influxql.(*bufFloatIterator).Next(0xc44d7e14c0, 0xeb2000, 0xc43ec3fb60, 0x1)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:95 +0x95
github.com/influxdata/influxdb/influxql.(*floatAuxIterator).stream(0xc44d7e1520)
        /root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:895 +0x32
created by github.com/influxdata/influxdb/influxql.(*floatAuxIterator).Start
```
**2. segmentation violation code=0x1 addr=0x100008 pc=0x41fd75]**

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x100008 pc=0x41fd75]

runtime stack:
runtime.throw(0xba048c, 0x2a)
	/usr/local/go/src/runtime/panic.go:596 +0x95
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:274 +0x2db
runtime.(*mspan).sweep(0x7f50407e7c30, 0x7f50407e7c00, 0xc420001040)
	/usr/local/go/src/runtime/mgcsweep.go:214 +0x115
runtime.sweepone(0x433c26)
	/usr/local/go/src/runtime/mgcsweep.go:110 +0x1ad
runtime.gosweepone.func1()
	/usr/local/go/src/runtime/mgcsweep.go:125 +0x2b
runtime.systemstack(0xc420024000)
	/usr/local/go/src/runtime/asm_amd64.s:327 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1132
```

**3. segmentation violation code=0x2**

```
unexpected fault address 0x7faee5f3aac0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7faee5f3aac0 pc=0x7faee5f3aac0]

goroutine 657876 [running]:
runtime.throw(0xb856b7, 0x5)
	/usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc448f23548 sp=0xc448f23528
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:297 +0x28c fp=0xc448f23598 sp=0xc448f23548
github.com/influxdata/influxdb/influxql.(*bufIntegerIterator).Close(0xc44af079e0, 0x0, 0x0)
	/root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:2994 +0x33 fp=0xc448f235c0 sp=0xc448f23598
github.com/influxdata/influxdb/influxql.(*integerReduceIntegerIterator).Close(0xc4433af080, 0x0, 0x0)
	/root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:4379 +0x2e fp=0xc448f235e8 sp=0xc448f235c0
github.com/influxdata/influxdb/influxql.(*integerMergeIterator).Close(0xc4490c6360, 0xc448f23640, 0x0)
	/root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:3092 +0x54 fp=0xc448f23628 sp=0xc448f235e8
github.com/influxdata/influxdb/influxql.(*integerParallelIterator).Close(0xc44af02800, 0x0, 0x0)
	/root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:3399 +0x83 fp=0xc448f23660 sp=0xc448f23628
github.com/influxdata/influxdb/influxql.(*integerMergeIterator).Close(0xc4490c6a20, 0x0, 0x0)
	/root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:3092 +0x54 fp=0xc448f236a0 sp=0xc448f23660
github.com/influxdata/influxdb/influxql.(*integerMergeIterator).Close(0xc44853d8c0, 0x0, 0xc448f23758)
	/root/go/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:3092 +0x54 fp=0xc448f236e0 sp=0xc448f236a0
```

**4. fatal error: found bad pointer in Go heap (incorrect use of unsafe or cgo?)**

```
fatal error: found bad pointer in Go heap (incorrect use of unsafe or cgo?)

runtime stack:
runtime.throw(0xba6c22, 0x3e)
	/usr/local/go/src/runtime/panic.go:596 +0x95
runtime.heapBitsForObject(0xc4248bc990, 0xc4563d8000, 0x10ae0, 0xc41fdba3fb, 0xc400000002, 0x7ff973a342f8, 0xc420019828, 0x1)
	/usr/local/go/src/runtime/mbitmap.go:434 +0x2bb
runtime.scanobject(0xc4563d8000, 0xc420019828)
	/usr/local/go/src/runtime/mgcmark.go:1326 +0x286
runtime.gcDrainN(0xc420019828, 0x7509d, 0x7ff940fcb568)
	/usr/local/go/src/runtime/mgcmark.go:1174 +0x138
runtime.gcAssistAlloc1(0xc440b7da00, 0x7509d)
	/usr/local/go/src/runtime/mgcmark.go:545 +0x127
runtime.gcAssistAlloc.func1()
	/usr/local/go/src/runtime/mgcmark.go:459 +0x33
runtime.systemstack(0xc420019900)
	/usr/local/go/src/runtime/asm_amd64.s:327 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1132
```

__Additional info:__
Config:default config on ubuntu

 vars.txt: https://gist.github.com/Eric-aihua/91a21020bf7e14015bc3d89be9f88b3c

I found that the operating system itself will have some segment fault, do I need to switch to other operating system? Is there a recommended operating system version?

**Comment by jwilder** [comment]
This looks like a hardware or system issue.  If your operating system is crashing with segfaults I would check your `/var/log/messages` and `dmesg` to see if anything is reported.  The various errors might hint be bad memory.
