### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by eelias** [influxdata/influxdb#8787]
Hello,
I have an ubuntu VM with influxdb version 1.3.5 installed on it:
```
root@hostname:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 14.04 LTS
Release: 14.04
Codename: trusty
```
InfluxDB shell version: 1.3.5
I configured a retention policy 4 days via influx shell:
```
> show retention policies
name duration shardGroupDuration replicaN default
---- -------- ------------------ -------- -------
autogen 0s 168h0m0s 1 false
telegraf 168h0m0s 24h0m0s 1 true
```

Since then the influxdb service fails every few hours about memory issue:
```
[I] 2017-09-04T03:50:19Z retention policy shard deletion check commencing service=retention
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb8 pc=0x820c20]
goroutine 314 [running]:
github.com/influxdata/influxdb/tsdb.(*Shard).UnloadIndex(0xc420466000)
/root/go/src/github.com/influxdata/influxdb/tsdb/shard.go:401 +0x30
github.com/influxdata/influxdb/tsdb.(*Store).DeleteShard(0xc4201f6f20, 0x43, 0x43, 0xc4209dacd8)
/root/go/src/github.com/influxdata/influxdb/tsdb/store.go:441 +0x55
github.com/influxdata/influxdb/services/retention.(*Service).deleteShards(0xc420146be0)
/root/go/src/github.com/influxdata/influxdb/services/retention/service.go:123 +0x75c
created by github.com/influxdata/influxdb/services/retention.(*Service).Open
/root/go/src/github.com/influxdata/influxdb/services/retention/service.go:46 +0x181
```

So I have to restart the service every few hours as workaround.
Can you assist to fix it? Does the retention policy configuration looks bad?
The VM had 8GB of memory, I increased it to 16GB but the issue still the same.
Thank you!

**Comment by rbetts** [comment]
@eelias Thanks for the bug report.
