### ISSUE TITLE
when the value of points end with "\", got java.lang.RuntimeException: {"error":"partial write: unable to parse

### ISSUE THREAD

**Issue by gzll** [influxdata/influxdb#8793]
I use riemann to send points to influxdb, when the value of points end with "\\", riemann would throw a exception: 
```
app_monitor_riemann_server | java.lang.RuntimeException: {"error":"partial write: unable to parse 'dbfsplitter.dbf,batch=20170728029,descpath=A:\\test1\\test2\\,fname=files-\u003edes,host=localhost,stage=copy description=\"files-\u003edes: ??? 25 ???????? A:\\test1\\test2\\ ??\",level=\"debug\",projname=\"??????\",state=\"ok\",value=25.0 1504572240000000000': invalid tag format dropped=0"}
app_monitor_riemann_server | 
app_monitor_riemann_server | 	at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:266)
app_monitor_riemann_server | 	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:167)
app_monitor_riemann_server | 	at riemann.influxdb$write_batch_point.invokeStatic(influxdb.clj:182)
app_monitor_riemann_server | 	at riemann.influxdb$write_batch_point.invoke(influxdb.clj:179)
app_monitor_riemann_server | 	at riemann.influxdb$influxdb_deprecated$streams__9726.invoke(influxdb.clj:253)
```
the "descpath=A:\\test1\\test2\\" made this exception, if I change the value to "descpath=A:\\test1\\test2", everything is ok.

**Comment by gzll** [comment]
I had been told this is a problem form influxdb.
https://github.com/influxdata/influxdb-java/issues/372

**Comment by evenlis** [comment]
I believe I've hit this myself. Has there been any development on this that doesn't show in this or related threads? Should I create a new issue?
