### ISSUE TITLE
Stopping server after killing query panics

### ISSUE THREAD

**Issue by jwilder** [influxdata/influxdb#9018]
### Bug report

__System info:__ 1.4, nightly

__Steps to reproduce:__

1. Run a long query such as a delete
2. Kill it
3. Stop the server before it actually has a chance to be killed

__Actual behavior:__ 

```
^C[I] 2017-10-26T14:23:42Z Signal received, initializing clean shutdown...
[I] 2017-10-26T14:23:42Z Waiting for clean shutdown...
[I] 2017-10-26T14:23:42Z shutting down monitor system service=monitor
[I] 2017-10-26T14:23:42Z terminating storage of statistics service=monitor
[I] 2017-10-26T14:23:42Z Precreation service terminating service=shard-precreation
[I] 2017-10-26T14:23:42Z snapshot listener closed service=snapshot
[I] 2017-10-26T14:23:42Z continuous query service terminating service=continuous_querier
[I] 2017-10-26T14:23:42Z retention policy enforcement terminating service=retention
panic: close of closed channel

goroutine 1322 [running]:
github.com/influxdata/influxdb/query.(*TaskManager).Close(0xc420059860, 0x0, 0x0)
	/Users/jason/go/src/github.com/influxdata/influxdb/query/task_manager.go:290 +0x12e
github.com/influxdata/influxdb/query.(*QueryExecutor).Close(0xc420129c20, 0x0, 0x0)
	/Users/jason/go/src/github.com/influxdata/influxdb/query/query_executor.go:239 +0x2f
github.com/influxdata/influxdb/cmd/influxd/run.(*Server).Close(0xc420010dc0, 0xc6d738, 0xc4200a6e70)
	/Users/jason/go/src/github.com/influxdata/influxdb/cmd/influxd/run/server.go:463 +0x152
github.com/influxdata/influxdb/cmd/influxd/run.(*Command).Close(0xc4200a6e70, 0x0, 0x0)
	/Users/jason/go/src/github.com/influxdata/influxdb/cmd/influxd/run/command.go:140 +0xb3
created by main.(*Main).Run
	/Users/jason/go/src/github.com/influxdata/influxdb/cmd/influxd/main.go:100 +0x42f
```

**Comment by jwilder** [comment]
cc @jsternberg

**Comment by jsternberg** [comment]
That's a good catch. It was introduced in 2ec4f55. It's an easy fix.
