### ISSUE TITLE
v1.4.2 - prometheus remote storage exception

### ISSUE THREAD

**Issue by syepes** [influxdata/influxdb#9134]
### Bug report
Just wanted to report the following exception that I have encountered with the InfluxDB / Prometheus long storage integration, this exception is not continuously happening but it appears from time to time.

__System info:
InfluxDB v1.4.2
Prometheus 2.0
CentOS 7

__Additional info:

```
[I] 2017-11-17T15:40:03Z SELECT f64 FROM PROM.raw._ WHERE job = 'dev' AND u_metric_name !~ 'eventslast.*' AND u_metric_type = 'count' AND __name__ = 'events_metrics_seconds_count' AND time >= '2017-11-16T15:35:02Z' AND time <= '2017-11-16T18:00:00Z' GROUP BY * service=query
[E] 2017-11-17T15:40:03Z SELECT f64 FROM PROM.raw._ WHERE job = 'dev' AND u_metric_name !~ 'eventslast.*' AND u_metric_type = 'count' AND __name__ = 'events_metrics_seconds_count' AND time >= '2017-11-16T15:35:02Z' AND time <= '2017-11-16T18:00:00Z' GROUP BY * [panic:interface conversion: influxql.Expr is *influxql.StringLiteral, not *influxql.RegexLiteral] goroutine 28163241 [running]:
runtime/debug.Stack(0xc4936aeb60, 0xc43edead00, 0xf7)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/influxdata/influxdb/query.(*QueryExecutor).recover(0xc4201ea270, 0xc4936aeb60, 0xc4f593a900)
        /go/src/github.com/influxdata/influxdb/query/query_executor.go:443 +0xaf
panic(0xbca620, 0xc4c692a980)
        /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/influxdata/influxql.(*SelectStatement).RewriteRegexConditions.func1(0x10d15c0, 0xc50f33e6f0, 0xcdff20, 0x10d1880)
        /go/src/github.com/influxdata/influxql/ast.go:1359 +0x1cb
github.com/influxdata/influxql.RewriteExpr(0x10d15c0, 0xc50f33e6f0, 0xcdff20, 0xc50f33e6c0, 0xc4e745e4d0)
        /go/src/github.com/influxdata/influxql/ast.go:3874 +0x189
github.com/influxdata/influxql.RewriteExpr(0x10d15c0, 0xc50f33e900, 0xcdff20, 0x10d15c0, 0xc50f33e6c0)
        /go/src/github.com/influxdata/influxql/ast.go:3852 +0x289
github.com/influxdata/influxql.RewriteExpr(0x10d15c0, 0xc50f33e930, 0xcdff20, 0xc4936aede0, 0xc4e745ea00)
        /go/src/github.com/influxdata/influxql/ast.go:3853 +0x2d5
github.com/influxdata/influxql.(*SelectStatement).RewriteRegexConditions(0xc51469f700)
        /go/src/github.com/influxdata/influxql/ast.go:1350 +0x44
github.com/influxdata/influxdb/query.Compile(0xc51469f600, 0x0, 0x0, 0x0, 0xd80, 0x90, 0xc47ae28b90, 0xc510932000)
        /go/src/github.com/influxdata/influxdb/query/compile.go:115 +0x163
github.com/influxdata/influxdb/query.Prepare(0xc51469f600, 0x10c2540, 0xc42022c040, 0x10d4d40, 0x1139eb0, 0x0, 0xc4f593a960, 0x0, 0x0, 0xc4ff437850, ...)
        /go/src/github.com/influxdata/influxdb/query/select.go:73 +0x4a
github.com/influxdata/influxdb/query.Select(0x10d31c0, 0xc420078060, 0xc51469f600, 0x10c2540, 0xc42022c040, 0x10d4d40, 0x1139eb0, 0x0, 0xc4f593a960, 0x0, ...)
        /go/src/github.com/influxdata/influxdb/query/select.go:83 +0xcf
github.com/influxdata/influxdb/coordinator.(*StatementExecutor).createIterators(0xc4201ec8c0, 0x10d31c0, 0xc420078060, 0xc51469f600, 0xc49ae5fcb0, 0x0, 0x0, 0xc4ff437980, 0xf, 0xc42007c0b8, ...)
        /go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:659 +0x106
github.com/influxdata/influxdb/coordinator.(*StatementExecutor).executeSelectStatement(0xc4201ec8c0, 0x10d31c0, 0xc420078060, 0xc51469f600, 0xc49ae5fcb0, 0x0, 0x0)
        /go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:555 +0x8f
github.com/influxdata/influxdb/coordinator.(*StatementExecutor).ExecuteStatement(0xc4201ec8c0, 0x10d45c0, 0xc51469f600, 0x0, 0x22cd, 0xc507006bd0, 0xc4f593a900, 0x10d8460, 0xc42022e660, 0xc4f593a960, ...)
        /go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:62 +0x29a6
github.com/influxdata/influxdb/query.(*QueryExecutor).executeQuery(0xc4201ea270, 0xc4936aeb60, 0xc512f34129, 0x4, 0x10d4d40, 0x1139eb0, 0x2710, 0x1, 0x0, 0x0, ...)
        /go/src/github.com/influxdata/influxdb/query/query_executor.go:381 +0xb27
created by github.com/influxdata/influxdb/query.(*QueryExecutor).ExecuteQuery
        /go/src/github.com/influxdata/influxdb/query/query_executor.go:276 +0xc3
 service=query
[I] 2017-11-17T15:40:07Z executing continuous query grp_source_h5m (2017-11-17 15:35:00 +0000 UTC to 2017-11-17 15:40:00 +0000 UTC) service=continuous_querier
```

**Comment by mark-rushakoff** [comment]
It's a bug on our end that it's panicking this way, but the query is incorrect. Instead of 
```u_metric_name !~ 'eventslast.*'```

it should be a regex literal, i.e. the quotes should be slashes: 
```u_metric_name !~ /eventslast.*/```

https://docs.influxdata.com/influxdb/v1.3/query_language/spec/#regular-expressions

**Comment by oleg-glushak** [comment]
I have the same issue using Grafana + Prometheus + InfluxDB as a remote storage. It seems you need to convert 
<...> <regexp operator> "<regexp pattern>" (Prometheus format) 
to 
<...> <regexp operator> /<regexp pattern>/ (InfluxDB format)

I assume it could be done on InfluxDB side.
