### ISSUE TITLE
Panic with SHOW SERIES

### ISSUE THREAD

**Issue by goller** [influxdata/influxdb#9196]
I was testing out regex where clauses against `show series where host =~ /.+/` and I got this panic.  After restarting influx I did not get the panic again with the same query.

```
 influxd version
InfluxDB vv1.4.2 (git: master 6d2685d1738277a1c2672fc58df7994627769be6)
```

```
[I] 2017-12-04T14:46:31Z SELECT "key" FROM telegraf.autogen._series WHERE host =~ /.+/ service=query
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x162896d]

goroutine 220936 [running]:
github.com/influxdata/influxdb/tsdb/index/inmem.(*seriesPointIterator).nextKeys.func1(0x94, 0x82, 0x1)
        /private/tmp/influxdb-20171118-98541-1rkb83o/src/github.com/influxdata/influxdb/tsdb/index/inmem/inmem.go:1009 +0x4d
sort.medianOfThree_func(0xc43652fc48, 0xc423dd0600, 0x94, 0x82, 0x70)
        /usr/local/Cellar/go/1.9.2/libexec/src/sort/zfuncversion.go:53 +0x3e
sort.doPivot_func(0xc43652fc48, 0xc423dd0600, 0x0, 0x95, 0x28d3780, 0x0)
        /usr/local/Cellar/go/1.9.2/libexec/src/sort/zfuncversion.go:78 +0x57d
sort.quickSort_func(0xc43652fc48, 0xc423dd0600, 0x0, 0x95, 0x10)
        /usr/local/Cellar/go/1.9.2/libexec/src/sort/zfuncversion.go:143 +0x8a
sort.Slice(0x1779060, 0xc423dd05e0, 0xc43652fc48)
        /usr/local/Cellar/go/1.9.2/libexec/src/sort/sort.go:251 +0xe3
github.com/influxdata/influxdb/tsdb/index/inmem.(*seriesPointIterator).nextKeys(0xc4218fb040, 0xc4202ba000, 0x2800d90)
        /private/tmp/influxdb-20171118-98541-1rkb83o/src/github.com/influxdata/influxdb/tsdb/index/inmem/inmem.go:1008 +0x164
github.com/influxdata/influxdb/tsdb/index/inmem.(*seriesPointIterator).Next(0xc4218fb040, 0xc422c21ba0, 0x1, 0x1)
        /private/tmp/influxdb-20171118-98541-1rkb83o/src/github.com/influxdata/influxdb/tsdb/index/inmem/inmem.go:958 +0x1fb
github.com/influxdata/influxdb/query.(*floatSortedMergeIterator).pop(0xc42c53ec90, 0x14679ca, 0xc43652fef8, 0xc431db1528)
        /private/tmp/influxdb-20171118-98541-1rkb83o/src/github.com/influxdata/influxdb/query/iterator.gen.go:383 +0x40c
github.com/influxdata/influxdb/query.(*floatSortedMergeIterator).Next(0xc42c53ec90, 0xc43652fe48, 0x100a559, 0xc43652fee8)
        /private/tmp/influxdb-20171118-98541-1rkb83o/src/github.com/influxdata/influxdb/query/iterator.gen.go:345 +0x2b
github.com/influxdata/influxdb/query.(*floatInterruptIterator).Next(0xc421c2a220, 0x6, 0x1721220, 0xc431db13f0)
        /private/tmp/influxdb-20171118-98541-1rkb83o/src/github.com/influxdata/influxdb/query/iterator.gen.go:842 +0x4f
github.com/influxdata/influxdb/query.(*floatInterruptIterator).Next(0xc421c2a240, 0xc42c53f140, 0xc43652fee8, 0xc431db1578)
        /private/tmp/influxdb-20171118-98541-1rkb83o/src/github.com/influxdata/influxdb/query/iterator.gen.go:842 +0x4f
github.com/influxdata/influxdb/query.(*floatFastDedupeIterator).Next(0xc421c2a280, 0xc43652ff98, 0x0, 0x0)
        /private/tmp/influxdb-20171118-98541-1rkb83o/src/github.com/influxdata/influxdb/query/iterator.go:1513 +0x48
github.com/influxdata/influxdb/query.(*bufFloatIterator).Next(0xc421c2a2a0, 0x1cecd00, 0xc4228b38c0, 0x1)
        /private/tmp/influxdb-20171118-98541-1rkb83o/src/github.com/influxdata/influxdb/query/iterator.gen.go:90 +0x95
github.com/influxdata/influxdb/query.(*floatAuxIterator).stream(0xc42c53f1a0)
        /private/tmp/influxdb-20171118-98541-1rkb83o/src/github.com/influxdata/influxdb/query/iterator.gen.go:946 +0x32
created by github.com/influxdata/influxdb/query.(*floatAuxIterator).Start
        /private/tmp/influxdb-20171118-98541-1rkb83o/src/github.com/influxdata/influxdb/query/iterator.gen.go:926 +0x3f
```

**Comment by datamuc** [comment]
I have a similar one:

```
ts=2018-06-11T14:21:03.167425Z lvl=info msg="Executing query" log_id=08coNgHG000 service=query query="SELECT \"key\" FROM prom.autogen._series WHERE __name__ =~ /numconnfree/"
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x91caa6]

goroutine 34699 [running]:
github.com/influxdata/influxdb/tsdb.SeriesIDIterators.Close(0xc48ead1f00, 0xa, 0x10, 0xad7224, 0xc48358c220)
	/opt/projects/omd/rpm.topdir/BUILD/omd/packages/influxdb/go/src/github.com/influxdata/influxdb/tsdb/index.go:205 +0x66
github.com/influxdata/influxdb/tsdb.(*seriesIDMergeIterator).Close(0xc483594870, 0x0, 0x0)
	/opt/projects/omd/rpm.topdir/BUILD/omd/packages/influxdb/go/src/github.com/influxdata/influxdb/tsdb/index.go:368 +0x41
github.com/influxdata/influxdb/tsdb.(*filterUndeletedSeriesIDIterator).Close(0xc482dcbea0, 0xc42039bc20, 0x0)
	/opt/projects/omd/rpm.topdir/BUILD/omd/packages/influxdb/go/src/github.com/influxdata/influxdb/tsdb/index.go:294 +0x34
panic(0xce75c0, 0x13139b0)
	/opt/projects/omd/rpm.topdir/BUILD/omd/packages/go-1.9/go-1.9.4/src/runtime/panic.go:491 +0x283
github.com/influxdata/influxdb/tsdb.(*seriesIDMergeIterator).Next(0xc483594870, 0x42c569, 0xc4a8265f20, 0xc4a0f6dc48, 0x18, 0x91edaf)
	/opt/projects/omd/rpm.topdir/BUILD/omd/packages/influxdb/go/src/github.com/influxdata/influxdb/tsdb/index.go:381 +0xd7
github.com/influxdata/influxdb/tsdb.(*filterUndeletedSeriesIDIterator).Next(0xc482dcbea0, 0x12d48c0, 0xc482dcbea0, 0xc42039bc20, 0x0, 0x0)
	/opt/projects/omd/rpm.topdir/BUILD/omd/packages/influxdb/go/src/github.com/influxdata/influxdb/tsdb/index.go:299 +0x38
github.com/influxdata/influxdb/tsdb.(*seriesPointIterator).readSeriesKeys(0xc465964000, 0x7f4895759e77, 0x1, 0x330189, 0x0, 0x0)
	/opt/projects/omd/rpm.topdir/BUILD/omd/packages/influxdb/go/src/github.com/influxdata/influxdb/tsdb/index.go:756 +0x171
github.com/influxdata/influxdb/tsdb.(*seriesPointIterator).Next(0xc465964000, 0x42c569, 0xc400000008, 0xc4a87e9980)
	/opt/projects/omd/rpm.topdir/BUILD/omd/packages/influxdb/go/src/github.com/influxdata/influxdb/tsdb/index.go:712 +0x42c
github.com/influxdata/influxdb/query.(*floatInterruptIterator).Next(0xc4836fe5a0, 0xc4a9b81688, 0x413a5d, 0x42f98b)
	/opt/projects/omd/rpm.topdir/BUILD/omd/packages/influxdb/go/src/github.com/influxdata/influxdb/query/iterator.gen.go:852 +0x4f
github.com/influxdata/influxdb/query.(*floatFastDedupeIterator).Next(0xc4836fe5c0, 0x3, 0xc4503d1900, 0x3)
	/opt/projects/omd/rpm.topdir/BUILD/omd/packages/influxdb/go/src/github.com/influxdata/influxdb/query/iterator.go:1535 +0x48
github.com/influxdata/influxdb/query.(*bufFloatIterator).Next(0xc4836fe5e0, 0x0, 0x45ec21, 0xc420228270)
	/opt/projects/omd/rpm.topdir/BUILD/omd/packages/influxdb/go/src/github.com/influxdata/influxdb/query/iterator.gen.go:90 +0x95
github.com/influxdata/influxdb/query.(*floatAuxIterator).stream(0xc48373d650)
	/opt/projects/omd/rpm.topdir/BUILD/omd/packages/influxdb/go/src/github.com/influxdata/influxdb/query/iterator.gen.go:956 +0x32
created by github.com/influxdata/influxdb/query.(*floatAuxIterator).Start
	/opt/projects/omd/rpm.topdir/BUILD/omd/packages/influxdb/go/src/github.com/influxdata/influxdb/query/iterator.gen.go:936 +0x3f
```

**Comment by e-dard** [comment]
don't close
