### ISSUE TITLE
Query raised INFLUXDB panic

### ISSUE THREAD

**Issue by huangpeizhi** [influxdata/influxdb#9243]
- influxdb 1.4.2
- log:
`
[httpd] 10.88.100.132 - - [19/Dec/2017:14:00:00 +0800] "GET /query?db=mingjun&pretty=true&q=select+count%28last%29+from+%28select+last%28%22event%22%29%2C+%22ext.attr.carrystatus%22%2C+%22ids%22+from+%22fencetaxi%22+group+by+%22ext.id%22%29+where+time+%3E+now%28%29+-+5m+group+by++%22ext.attr.carrystatus%22%2C+%22ids%22 HTTP/1.1" 200 130 "-" "lua-resty-http/0.08 (Lua) ngx_lua/10011" d96f0538-e481-11e7-893f-000000000000 30149290
panic: runtime error: index out of range

goroutine 26564930 [running]:
github.com/influxdata/influxdb/query.(*integerMergeHeap).Less(0xc56bc4a000, 0x12, 0x8, 0x1)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:3656 +0x5f8
container/heap.down(0x10e5040, 0xc56bc4a000, 0x0, 0x19, 0x0)
        /usr/local/go/src/container/heap/heap.go:114 +0x9f
container/heap.Pop(0x10e5040, 0xc56bc4a000, 0x0, 0x0)
        /usr/local/go/src/container/heap/heap.go:64 +0x8f
github.com/influxdata/influxdb/query.(*integerMergeIterator).Next(0xc437354540, 0xc514c9f701, 0xc52ddb4f00, 0xc5351567f8)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:3597 +0x3a6
github.com/influxdata/influxdb/query.(*integerInterruptIterator).Next(0xc573fd4ac0, 0x15019ca92194c000, 0x1, 0xc560fde510)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:4245 +0x4f
github.com/influxdata/influxdb/query.(*bufIntegerIterator).Next(0xc573fd4ae0, 0x1, 0x1, 0xc560fde510)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:3492 +0x95
github.com/influxdata/influxdb/query.(*bufIntegerIterator).NextInWindow(0xc573fd4ae0, 0x15019c63ff325473, 0x7fffffffffffffff, 0x24, 0xc535156c30, 0x24)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:3498 +0x2f
github.com/influxdata/influxdb/query.(*integerReduceIntegerIterator).reduce(0xc5a03889a0, 0xc535156dd0, 0x838dbe, 0x0, 0xc4d0c46810, 0xf)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:4962 +0x22e
github.com/influxdata/influxdb/query.(*integerReduceIntegerIterator).Next(0xc5a03889a0, 0xc4d0c46830, 0xf, 0xc4bb2774a0)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:4912 +0x93
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*integerFinalizerIterator).Next(0xc573fd4b20, 0xc4bb2774a0, 0xc586ae26c1, 0xc560771828)
        <autogenerated>:1 +0x3c
github.com/influxdata/influxdb/query.(*bufIntegerIterator).Next(0xc573fd4bc0, 0xc4f676e2a0, 0xc5365d1aa0, 0x1)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:3492 +0x95
github.com/influxdata/influxdb/query.(*integerMergeIterator).Next(0xc4373545a0, 0xc50b732f01, 0xc52ddb4ea0, 0xc5351572a0)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:3611 +0x6b
github.com/influxdata/influxdb/query.(*integerInterruptIterator).Next(0xc573fd4be0, 0x15019ca92194c000, 0x1, 0xc560fde4d0)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:4245 +0x4f
github.com/influxdata/influxdb/query.(*bufIntegerIterator).Next(0xc573fd4c00, 0x1, 0x1, 0xc560fde4d0)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:3492 +0x95
github.com/influxdata/influxdb/query.(*bufIntegerIterator).NextInWindow(0xc573fd4c00, 0x15019c63ff325473, 0x7fffffffffffffff, 0x24, 0xc5351576d8, 0x24)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:3498 +0x2f
github.com/influxdata/influxdb/query.(*integerReduceIntegerIterator).reduce(0xc5a0388b00, 0xc4202aa000, 0x7f5b0ef40000, 0x0, 0xc50b732f30, 0x1)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:4962 +0x22e
github.com/influxdata/influxdb/query.(*integerReduceIntegerIterator).Next(0xc5a0388b00, 0xc50b732f01, 0xc52ddb4e40, 0xc535157910)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:4912 +0x93
github.com/influxdata/influxdb/query.(*integerInterruptIterator).Next(0xc573fd4c40, 0x15019ca998ca5400, 0x1, 0xc560fde490)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:4245 +0x4f
github.com/influxdata/influxdb/query.(*bufIntegerIterator).Next(0xc573fd4c60, 0x1, 0x1, 0xc560fde490)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:3492 +0x95
github.com/influxdata/influxdb/query.(*bufIntegerIterator).NextInWindow(0xc573fd4c60, 0x15019c63ff325473, 0x7fffffffffffffff, 0x24, 0xc52518eb90, 0x24)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:3498 +0x2f
github.com/influxdata/influxdb/query.(*integerReduceIntegerIterator).reduce(0xc5a0388c60, 0x1, 0x1, 0xc50b732ef0, 0xb8b840, 0xc4c7ddefb0)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:4962 +0x22e
github.com/influxdata/influxdb/query.(*integerReduceIntegerIterator).Next(0xc5a0388c60, 0xc586ae2650, 0xc4ff708260, 0xc4c00d7808)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:4912 +0x93
github.com/influxdata/influxdb/query.(*integerInterruptIterator).Next(0xc573fd4ce0, 0xc535157f98, 0xc52a7417a0, 0x24)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:4245 +0x4f
github.com/influxdata/influxdb/query.(*bufIntegerIterator).Next(0xc573fd4d00, 0x10e4c20, 0xc5860ff3e0, 0x1)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:3492 +0x95
github.com/influxdata/influxdb/query.(*integerAuxIterator).stream(0xc55aab58f0)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:4349 +0x32
created by github.com/influxdata/influxdb/query.(*integerAuxIterator).Start
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:4329 +0x3f
`

**Comment by huangpeizhi** [comment]
@jwilder ,

It happened again, log in the attachment. hope to solve this problem as soon as possible, thanks!

**Comment by huangpeizhi** [comment]
`
[I] 2018-01-31T09:40:29Z failed to write point batch to database "mingjun": timeout service=udp
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xabd3d6]
goroutine 644425194 [running]:
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*KeyCursor).Close(0x0)
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/file_store.go:1061 +0x26
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*integerDescendingCursor).close(0xc571101770, 0x0, 0x0)
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/iterator.gen.go:993 +0x33
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*integerIterator).Close(0xc44db10960, 0x0, 0x0)
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/iterator.gen.go:768 +0xe1
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*integerLimitIterator).Close(0xc6b9b6a120, 0x0, 0x0)
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/iterator.gen.go:790 +0x33
github.com/influxdata/influxdb/query.(*integerSortedMergeIterator).Close(0xcbf8dc30b0, 0x0, 0x0)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:3742 +0x4d
github.com/influxdata/influxdb/query.(*integerInterruptIterator).Close(0xc5031f9040, 0x0, 0x0)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:4226 +0x33
github.com/influxdata/influxdb/query.(*integerLimitIterator).Close(0xcf142e4f00, 0x0, 0x0)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:3973 +0x33
github.com/influxdata/influxdb/query.(*integerMergeIterator).Close(0xc8e3ffeb40, 0xc529e57d48, 0xcd6be60e00)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:3561 +0x51
github.com/influxdata/influxdb/query.(*integerInterruptIterator).Close(0xcc6395d320, 0xc529e57d70, 0xc529e57d48)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:4226 +0x33
github.com/influxdata/influxdb/query.(*bufIntegerIterator).Close(0xcc6395d340, 0x10dbc48, 0xceb5ca6528)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:3463 +0x33
github.com/influxdata/influxdb/query.(*integerReduceIntegerIterator).Close(0xc6b9a3f080, 0xcc6395d360, 0x0)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:4905 +0x2e
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*integerFinalizerIterator).Close(0xcc6395d360, 0x2, 0xc689da3f10)
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/iterator.gen.go:608 +0x5f
github.com/influxdata/influxdb/query.(*integerMergeIterator).Close(0xcbdf59a6c0, 0x150edb7a593b7e00, 0xcddbb6d6d0)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:3561 +0x51
github.com/influxdata/influxdb/query.(*integerInterruptIterator).Close(0xcf613087a0, 0x40688a, 0xc431775bb8)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:4226 +0x33
github.com/influxdata/influxdb/query.(*bufIntegerIterator).Close(0xcf613087c0, 0xccb8dd1708, 0x8)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:3463 +0x33
github.com/influxdata/influxdb/query.(*integerReduceIntegerIterator).Close(0xc421309600, 0x150edb7a593b7e00, 0xb8b840)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:4905 +0x2e
github.com/influxdata/influxdb/query.(*integerInterruptIterator).Close(0xcf613087e0, 0x2, 0x1)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:4226 +0x33
github.com/influxdata/influxdb/query.(*bufIntegerIterator).Close(0xcf61308800, 0x2, 0xc529e57ee8)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:3463 +0x33
github.com/influxdata/influxdb/query.(*integerReduceIntegerIterator).Close(0xc421309760, 0xc5387a1000, 0xc421300001)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:4905 +0x2e
github.com/influxdata/influxdb/query.(*integerInterruptIterator).Close(0xcf61308820, 0xc431775b60, 0xca3a4a9701)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:4226 +0x33
github.com/influxdata/influxdb/query.(*integerInterruptIterator).Next(0xcf61308820, 0xc529e57f98, 0xcbe4589770, 0x44)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:4236 +0xb3
github.com/influxdata/influxdb/query.(*bufIntegerIterator).Next(0xcf61308840, 0x10e4c20, 0xc4f8c5fe40, 0x1)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:3492 +0x95
github.com/influxdata/influxdb/query.(*integerAuxIterator).stream(0xc689da3f80)
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:4349 +0x32
created by github.com/influxdata/influxdb/query.(*integerAuxIterator).Start
        /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:4329 +0x3f
`
