### ISSUE TITLE
panic: assert failed: series key for ID: not found

### ISSUE THREAD

**Issue by kornholi** [influxdata/influxdb#9444]
Even with #9391, still managed to run into this. After deleting lots of series, it wouldn't start back up (no panic during the actual deletion). Manually rebuilding the indices with `influx_inspect buildtsi` fixed the issue.

```
panic: assert failed: series key for ID: 262444 not found

goroutine 243 [running]:
github.com/influxdata/influxdb/tsdb/index/tsi1.assert(0xdefe00, 0xc4218e27e0, 0x23, 0x0, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/tsi1.go:531 +0xf6
github.com/influxdata/influxdb/tsdb/index/tsi1.(*LogFile).execSeriesEntry(0xc4216ecfc0, 0xc4204f5c60)
	/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/log_file.go:621 +0x225
github.com/influxdata/influxdb/tsdb/index/tsi1.(*LogFile).execEntry(0xc4216ecfc0, 0xc4204f5c60)
	/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/log_file.go:575 +0x68
github.com/influxdata/influxdb/tsdb/index/tsi1.(*LogFile).open(0xc4216ecfc0, 0xc420e58780, 0xc420e586e0)
	/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/log_file.go:135 +0x3a8
github.com/influxdata/influxdb/tsdb/index/tsi1.(*LogFile).Open(0xc4216ecfc0, 0xc42555e4b0, 0x42)
	/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/log_file.go:83 +0x2b
github.com/influxdata/influxdb/tsdb/index/tsi1.(*Partition).openLogFile(0xc4216ec5a0, 0xc42555e4b0, 0x42, 0xc42555e4b0, 0x42, 0x8)
	/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/partition.go:222 +0x5a
github.com/influxdata/influxdb/tsdb/index/tsi1.(*Partition).Open(0xc4216ec5a0, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/partition.go:164 +0x5f4
github.com/influxdata/influxdb/tsdb/index/tsi1.(*Index).Open.func1(0xc4266de104, 0x8, 0xc421c06120, 0xc4205e1620, 0x7)
	/go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/index.go:201 +0x30
```

cc @benbjohnson @louisvernon

**Comment by benbjohnson** [comment]
@kornholi Thanks for the bug report! It's fixed in https://github.com/influxdata/influxdb/pull/9496.
