### ISSUE TITLE
Compacting level 1 - panic

### ISSUE THREAD

**Issue by xefil** [influxdata/influxdb#9453]
Hello,

Starting my installation i get this error:

```
(...)
[I] 2018-02-15T18:39:54Z beginning level 1 compaction, 2 TSM files engine=tsm1
[I] 2018-02-15T18:39:54Z compacting level 1 /var/lib/influxdb/data/_internal/monitor/260/000000027-000000001.tsm (#0) engine=tsm1
[I] 2018-02-15T18:39:54Z compacting level 1 /var/lib/influxdb/data/_internal/monitor/260/000000028-000000001.tsm (#1) engine=tsm1
panic: keys must be added in sorted order: shard,database=openhab_db,engine=tsm1,hostU{=oh,id=136,path=/var/lib/influxdb/data/openhab_db/autogen/136,retentionPolicy=autogen,walPath=/var/lib/influxdb/wal/openhab_db/autogen/136#!~#diskBytes < shard,database=openhab_db,engine=tsm1,hostname=oh,id=135,path=/var/lib/influxdb/data/openhab_db/autogen/135,retentionPolicy=autogen,walPath=/var/lib/influxdb/wal/openhab_db/autogen/135#!~#writeReqOk

goroutine 1220 [running]:
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*directIndex).Add(0x131e0660, 0xb3ab894a, 0xc5, 0x255997, 0x1, 0x120d9c00, 0x15128d8f, 0x88e4c00, 0x15128ed5, 0xb7a4, ...)
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/writer.go:329 +0x624
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*tsmWriter).WriteBlock(0x133a23e0, 0xb3ab894a, 0xc5, 0x255997, 0x120d9c00, 0x15128d8f, 0x88e4c00, 0x15128ed5, 0xb3a51bde, 0x1a, ...)
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/writer.go:610 +0x1c4
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).write(0x12e26880, 0x13226280, 0x48, 0xa994c0, 0x12f160b0, 0x0, 0x0)
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:1028 +0x160
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).writeNewFiles(0x12e26880, 0x1c, 0x2, 0xa994c0, 0x12f160b0, 0x2, 0xa994c0, 0x12f160b0, 0x0, 0x0)
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:942 +0x160
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).compact(0x12e26880, 0x747101, 0x132bc820, 0x2, 0x2, 0x2, 0x131eb880, 0x0, 0x12a121e0, 0x131e0150)
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:851 +0x418
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).CompactFast(0x12e26880, 0x132bc820, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:901 +0x104
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*compactionStrategy).compactGroup(0x1339f8c0)
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1550 +0x258
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*compactionStrategy).Apply.func1(0x1307f150, 0x1339f8c0)
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1528 +0x40
created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*compactionStrategy).Apply
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1526 +0x68
```

How to resolve?

Thanks!

Simon

OS: Linux oh 4.14.15-sunxi #28 SMP Mon Jan 29 07:24:48 CET 2018 armv7l GNU/Linux
influx version:  /usr/bin/influxd version
InfluxDB v1.4.2 (git: 1.4 6d2685d1738277a1c2672fc58df7994627769be6)

**Comment by jwilder** [comment]
@xefil Would you be able to send me these two files:

```
/var/lib/influxdb/data/_internal/monitor/260/000000027-000000001.tsm
/var/lib/influxdb/data/_internal/monitor/260/000000028-000000001.tsm
```

If you zip them up and email them to me at jason at influxdata.com that would be very helpful.

**Comment by xefil** [comment]
Ok course. I send you them in the next minutes

**Comment by xefil** [comment]
Files sent!

**Comment by xefil** [comment]
Hello, any news?
Thanks a lot!

**Comment by jwilder** [comment]
@xefil I have the files you sent and am seeing the issue locally.  Still investigating.

**Comment by jwilder** [comment]
@xefil How are your disks mounted? Are they directly attached SSDs, mounted over a NAS or is there a RAID involved? It looks like the file `000000028-000000001.tsm` has an index entry that is corrupted.   The `hostname` tag in the series key for `shard,database=openhab_db,engine=tsm1,hostU{=oh,id=136,path=/var/lib/influxdb/data/openhab_db/autogen/136,retentionPolicy=autogen,walPath=/var/lib/influxdb/wal/openhab_db/autogen/136 diskBytes` has been changed to `hostU{=`.   I verified the actual bytes in the file as `55  7b 00 00` which means they have changed somehow.  The index entries are written in sorted order and since TSM files are immutable once written, this is highly likely a hardware or filesystem issues.

This is the `_internal` database so you can move that file out of the way to get things moving again.

**Comment by xefil** [comment]
Hello @jwilder 

Removing that file all went well. Many thanks!
I think I had a space or power issue some weeks ago. Maybe that was the problem.

Simon

**Comment by joba-1** [comment]
for the record: had the same issue.

version 1.8.0 (opensuse 15.1)
also with xfs on ssd

moved several files from _internal, now it is working again.
