### ISSUE TITLE
Panic in large query results in rapid memory leak after it

### ISSUE THREAD

**Issue by AriSuutariST** [influxdata/influxdb#9549]
__System info:__ InfluxDB 1.4.3

__Steps to reproduce:__

A little bit difficult, but for me this occurs on InfluxDB server that hosts about 20 databases, each having 5000 - 10000 series. Users are performing rather large queries on data, typically something like "select mean(value) from A,B,C,D....Z where time > 'YYYY-MM-DDTHH:MM:SSZ' group by (1m)".

This seem to run well at first, but at some point influxd spits out following at log:
```
[panic:runtime error: invalid memory address or nil pointer dereference] goroutine 847600 [running]:
Mar  9 10:49:09 simtest influxd: runtime/debug.Stack(0xcae5830320, 0xc75b1d2000, 0x6eb)
Mar  9 10:49:09 simtest influxd:        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
Mar  9 10:49:09 simtest influxd: github.com/influxdata/influxdb/query.(*QueryExecutor).recover(0xc42013fcb0, 0xcae5830320, 0xc4a21061e0)
Mar  9 10:49:09 simtest influxd:        /wrkdirs/usr/ports/databases/influxdb/work/influxdb-1.4.3/src/github.com/influxdata/influxdb/query/query_executor.go:447 +0xaf
Mar  9 10:49:09 simtest influxd: panic(0xb87340, 0x10d6830)
Mar  9 10:49:09 simtest influxd:        /usr/local/go/src/runtime/panic.go:505 +0x229
Mar  9 10:49:09 simtest influxd: github.com/influxdata/influxdb/query.Iterators.Close(0xcae582d180, 0x23, 0x32, 0xc9f14d9b88, 0xc9f14d9b40)
Mar  9 10:49:09 simtest influxd:        /wrkdirs/usr/ports/databases/influxdb/work/influxdb-1.4.3/src/github.com/influxdata/influxdb/query/iterator.go:49 +0x37
Mar  9 10:49:09 simtest influxd: github.com/influxdata/influxdb/query.(*exprIteratorBuilder).callIterator(0xc9f14dae70, 0xd16d80, 0xc420036038, 0xcae4fb3ce0, 0xd15440, 0xcae4fb3ce0, 0x11088e0, 0x0, 0x0, 0x0, ...)
Mar  9 10:49:09 simtest influxd:        /wrkdirs/usr/ports/databases/influxdb/work/influxdb-1.4.3/src/github.com/influxdata/influxdb/query/select.go:833 +0x257
Mar  9 10:49:09 simtest influxd: github.com/influxdata/influxdb/query.(*exprIteratorBuilder).buildCallIterator.func1(0xcae4fb3ce0, 0xd16d80, 0xc420036038, 0xc9f14dae70, 0xc9f14da120, 0x0, 0xc62ff191c0, 0xe, 0x0)
Mar  9 10:49:09 simtest influxd:        /wrkdirs/usr/ports/databases/influxdb/work/influxdb-1.4.3/src/github.com/influxdata/influxdb/query/select.go:706 +0xee
Mar  9 10:49:09 simtest influxd: github.com/influxdata/influxdb/query.(*exprIteratorBuilder).buildCallIterator(0xc9f14dae70, 0xd16d80, 0xc420036038, 0xcae4fb3ce0, 0x32, 0xc8b72f4db8, 0x411cad, 0xcae5830640)
Mar  9 10:49:09 simtest influxd:        /wrkdirs/usr/ports/databases/influxdb/work/influxdb-1.4.3/src/github.com/influxdata/influxdb/query/select.go:750 +0xf85
Mar  9 10:49:09 simtest influxd: github.com/influxdata/influxdb/query.buildExprIterator(0xd16d80, 0xc420036038, 0xd15440, 0xcae4fb3ce0, 0xe95cb4b48, 0xc7820a6880, 0xcae582ce00, 0x32, 0x32, 0xd15440, ...)
Mar  9 10:49:09 simtest influxd:        /wrkdirs/usr/ports/databases/influxdb/work/influxdb-1.4.3/src/github.com/influxdata/influxdb/query/select.go:423 +0x448
Mar  9 10:49:09 simtest influxd: github.com/influxdata/influxdb/query.buildFieldIterators.func1(0xcae20b8778, 0x1, 0x1, 0xd16d80, 0xc420036038, 0x0, 0xe95cb4b48, 0xc7820a6880, 0xcae582ce00, 0x32, ...)
Mar  9 10:49:09 simtest influxd:        /wrkdirs/usr/ports/databases/influxdb/work/influxdb-1.4.3/src/github.com/influxdata/influxdb/query/select.go:353 +0x210
Mar  9 10:49:09 simtest influxd: github.com/influxdata/influxdb/query.buildFieldIterators(0xd16d80, 0xc420036038, 0xcae20b8778, 0x1, 0x1, 0xe95cb4b48, 0xc7820a6880, 0xcae582ce00, 0x32, 0x32, ...)
Mar  9 10:49:09 simtest influxd:        /wrkdirs/usr/ports/databases/influxdb/work/influxdb-1.4.3/src/github.com/influxdata/influxdb/query/select.go:400 +0x172
Mar  9 10:49:09 simtest influxd: github.com/influxdata/influxdb/query.buildIterators(0xd16d80, 0xc420036038, 0xcae4fcb900, 0xe95cb4b48, 0xc7820a6880, 0x0, 0x0, 0x11088e0, 0x0, 0x0, ...)
Mar  9 10:49:09 simtest influxd:        /wrkdirs/usr/ports/databases/influxdb/work/influxdb-1.4.3/src/github.com/influxdata/influxdb/query/select.go:188 +0x739
Mar  9 10:49:09 simtest influxd: github.com/influxdata/influxdb/query.(*preparedStatement).Select(0xcae0c0c640, 0xd16d80, 0xc420036038, 0xd18880, 0x11088e0, 0x0, 0xc4a2106240, 0x0, 0x0, 0xd12f80, ...)
Mar  9 10:49:09 simtest influxd:        /wrkdirs/usr/ports/databases/influxdb/work/influxdb-1.4.3/src/github.com/influxdata/influxdb/query/select.go:103 +0xd0
Mar  9 10:49:09 simtest influxd: github.com/influxdata/influxdb/query.Select(0xd16d80, 0xc420036038, 0xcae4fcb600, 0xd087a0, 0xc420216ce0, 0xd18880, 0x11088e0, 0x0, 0xc4a2106240, 0x0, ...)
Mar  9 10:49:09 simtest influxd:        /wrkdirs/usr/ports/databases/influxdb/work/influxdb-1.4.3/src/github.com/influxdata/influxdb/query/select.go:89 +0x11b
```

After that new queries still work, but system starts leaking memory very rapidly and consumes all available memory very quickly (I have 64 Gb ram).

I can trigger this repeatedly by running two scripts that execute a large query repeatedly in loop.

**Comment by e-dard** [comment]
@AriSuutariST could you upgrade to 1.5.0 and see if this issue still occurs?

**Comment by AriSuutariST** [comment]
1.5.0 seems to fix the problem. I have now run my stress test for four hours without panic message.

**Comment by e-dard** [comment]
@AriSuutariST I'm really pleased to hear that! Thanks for updating the ticket.
