### ISSUE TITLE
InfluxDB tag queries failing

### ISSUE THREAD

**Issue by jasonkeller** [influxdata/influxdb#9742]
### Bug report

__System info:__ Red Hat Enterprise Linux Server release 7.4 (Maipo)
8 vCPU (Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz)
16GB memory
InfluxDB 1.5.2, 41k series (was at 22k, but we added some tags to the telegraf poller today)

__Steps to reproduce:__Issue the query - "SHOW TAG VALUES WITH KEY = agent_host WHERE network_desc = 'Education, K-12' 

__Expected behavior:__ Tag query returns with data

__Actual behavior:__ Engine logs an error and doesn't return any data (it did initially; but a short while later this started happening with no other changes).

__Additional info:__ 
```
Apr 18 13:54:31 itddb-es1.nd.gov influxd[17810]: ts=2018-04-18T18:54:31.813051Z lvl=error msg="SHOW TAG VALUES WITH KEY = agent_host WHERE network_desc = 'Education, K-12' [panic:runtime error: invalid memory address or nil pointer dereference] goroutine 207133 [running]:\nruntime/debug.Stack(0xc437ac75c0, 0xc43ce11310, 0x4c)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/influxdata/influxdb/query.(*QueryExecutor).recover(0xc4201959b0, 0xc437ac75c0, 0xc42c0ab620)\n\t/go/src/github.com/influxdata/influxdb/query/query_executor.go:451 +0xaf\npanic(0xce4120, 0x1302970)\n\t/usr/local/go/src/runtime/panic.go:491 +0x283\ngithub.com/influxdata/influxdb/tsdb.(*MeasurementFields).HasField(0x0, 0xc4375efb30, 0xc, 0xc420210640)\n\t/go/src/github.com/influxdata/influxdb/tsdb/shard.go:1408 +0x26\ngithub.com/influxdata/influxdb/tsdb.IndexSet.seriesByBinaryExprIterator(0xc42052a480, 0x1, 0x47, 0xc420210640, 0xc446e4a008, 0x4, 0x8, 0xc46aa044b0, 0x0, 0xd3ac00, ...)\n\t/go/src/github.com/influxdata/influxdb/tsdb/index.go:1833 +0xdd2\ngithub.com/influxdata/influxdb/tsdb.IndexSet.seriesByExprIterator(0xc42052a480, 0x1, 0x47, 0xc420210640, 0xc446e4a008, 0x4, 0x8, 0x12cae00, 0xc46aa044b0, 0x0, ...)\n\t/go/src/github.com/influxdata/influxdb/tsdb/index.go:1786 +0x476\ngithub.com/influxdata/influxdb/tsdb.IndexSet.tagValuesByKeyAndExpr(0xc42052a480, 0x1, 0x47, 0xc420210640, 0x12ce9c0, 0x1336238, 0xc446e4a008, 0x4, 0x8, 0xc46aa062a0, ...)\n\t/go/src/github.com/influxdata/influxdb/tsdb/index.go:2144 +0x1a0\ngithub.com/influxdata/influxdb/tsdb.IndexSet.MeasurementTagKeyValuesByExpr(0xc42052a480, 0x1, 0x47, 0xc420210640, 0x12ce9c0, 0x1336238, 0xc446e4a008, 0x4, 0x8, 0xc46aa062a0, ...)\n\t/go/src/github.com/influxdata/influxdb/tsdb/index.go:2293 +0xca1\ngithub.com/influxdata/influxdb/tsdb.(*Store).TagValues(0xc420068480, 0x12ce9c0, 0x1336238, 0xc46af6c400, 0x47, 0x80, 0x12cae00, 0xc46aa04360, 0x80, 0x200, ...)\n\t/go/src/github.com/influxdata/influxdb/tsdb/store.go:1517 +0x946\ngithub.com/influxdata/influxdb/coordinator.LocalTSDBStore.TagValues(0xc420068480, 0x12ce9c0, 0x13
Apr 18 13:54:31 itddb-es1.nd.gov influxd[17810]: 36238, 0xc46af6c400, 0x47, 0x80, 0x12cae00, 0xc46aa04360, 0x32f2d7fe, 0x109d537404, ...)\n\t<autogenerated>:1 +0x97\ngithub.com/influxdata/influxdb/coordinator.(*StatementExecutor).executeShowTagValues(0xc42025eaf0, 0xc46af5a000, 0xc471b0bc48, 0xdf7588, 0xf)\n\t/go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:1066 +0x840\ngithub.com/influxdata/influxdb/coordinator.(*StatementExecutor).ExecuteStatement(0xc42025eaf0, 0x12ce780, 0xc46af5a000, 0x0, 0x1c, 0xc46af081c0, 0xc42c0ab620, 0xc429928ea0, 0xc43d30b4bc, 0x8, ...)\n\t/go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:194 +0x2937\ngithub.com/influxdata/influxdb/query.(*QueryExecutor).executeQuery(0xc4201959b0, 0xc437ac75c0, 0xc43d30b4bc, 0x8, 0x12ce9c0, 0x1336238, 0x2710, 0x0, 0x0, 0x0, ...)\n\t/go/src/github.com/influxdata/influxdb/query/query_executor.go:389 +0xae8\ncreated by github.com/influxdata/influxdb/query.(*QueryExecutor).ExecuteQuery\n\t/go/src/github.com/influxdata/influxdb/query/query_executor.go:285 +0xc3\n" log_id=07YXO_n0000 service=query

```

**Comment by jasonkeller** [comment]
@dgnorton since I already had to restructure my database (doing 'into' queries, along with using Python to morph the tags and rewrite them to InfluxDB), I doubled the memory in the VM temporarily and plowed through all of this.  Since doing so I've not had a recurrence.  I slimmed about 25000 series out (leaving about 42000).

**Comment by dgnorton** [comment]
@jasonkeller thanks for letting us know!
