### ISSUE TITLE
Influx start up failing (1.5.0)  -- Production outage for us.

### ISSUE THREAD

**Issue by deepujain** [influxdata/influxdb#9914]
### Directions
_GitHub Issues are reserved for actionable bug reports and feature requests._
_General questions should be sent to the [InfluxDB Community Site](https://community.influxdata.com)._

_Before opening an issue, search for similar bug reports or feature requests on GitHub Issues._
_If no similar issue can be found, fill out either the "Bug Report" or the "Feature Request" section below.
_Erase the other section and everything on and above this line._

### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
Influx 1.5.0 or 1.5.2
Lunux
Kubernetes
Docker image 1.5.0 or 1.5.2
__Steps to reproduce:__

1. Start Influx
2. Starts loading all TSM files
3. Influx fails to start and i see an exception

__Expected behavior:__ [What you expected to happen]
Influx start successful

__Actual behavior:__  Influx failed to start

__Additional info:__ [Include gist of relevant config, logs, etc.]
```
2018-05-28T15:16:20.023366000Z ts=2018-05-28T15:16:20.022704Z lvl=info msg="Opened file" log_id=08LpzZf0000 engine=tsm1 service=filestore path=/var/lib/influxdb/data/telegraf_1080d/telegraf_1080d/650/000000022-000000002.tsm id=0 duration=997.997ms
2018-05-28T15:16:20.068584000Z ts=2018-05-28T15:16:20.068008Z lvl=info msg="Opened file" log_id=08LpzZf0000 engine=tsm1 service=filestore path=/var/lib/influxdb/data/telegraf_1080d/telegraf_1080d/523/000000012-000000002.tsm id=0 duration=1024.809ms
2018-05-28T15:16:20.587784000Z ts=2018-05-28T15:16:20.587112Z lvl=info msg="Open store (end)" log_id=08LpzZf0000 service=store trace_id=08Lpz_3l000 op_name=tsdb_open op_event=end op_elapsed=5083.803ms
2018-05-28T15:16:20.590761000Z panic: unreachable
2018-05-28T15:16:20.591211000Z goroutine 1 [running]:
2018-05-28T15:16:20.591664000Z github.com/influxdata/influxdb/tsdb.(*SeriesIndex).execEntry(0xc4201ef680, 0x290225f, 0x61695f6e616d6573, 0x4016fe085, 0x0, 0x0, 0x0)
2018-05-28T15:16:20.591885000Z 	/go/src/github.com/influxdata/influxdb/tsdb/series_index.go:179 +0x167
2018-05-28T15:16:20.592092000Z github.com/influxdata/influxdb/tsdb.(*SeriesIndex).Recover.func1(0x7f604f2c005f, 0x61695f6e616d6573, 0x4016fe085, 0x0, 0x0, 0x0, 0x0, 0x0)
2018-05-28T15:16:20.592302000Z 	/go/src/github.com/influxdata/influxdb/tsdb/series_index.go:127 +0x91
2018-05-28T15:16:20.592504000Z github.com/influxdata/influxdb/tsdb.(*SeriesSegment).ForEachEntry(0xc432ea9040, 0xc4203bc860, 0x0, 0x0)
2018-05-28T15:16:20.592713000Z 	/go/src/github.com/influxdata/influxdb/tsdb/series_segment.go:242 +0xea
2018-05-28T15:16:20.592911000Z github.com/influxdata/influxdb/tsdb.(*SeriesIndex).Recover(0xc4201ef680, 0xc4504ee6c0, 0x5, 0x8, 0xc44ca48f70, 0x0)
2018-05-28T15:16:20.593114000Z 	/go/src/github.com/influxdata/influxdb/tsdb/series_index.go:123 +0x169
2018-05-28T15:16:20.593316000Z github.com/influxdata/influxdb/tsdb.(*SeriesPartition).Open.func1(0xc432dd8370, 0x2f, 0x1ff)
2018-05-28T15:16:20.593522000Z 	/go/src/github.com/influxdata/influxdb/tsdb/series_partition.go:87 +0x132
2018-05-28T15:16:20.593736000Z github.com/influxdata/influxdb/tsdb.(*SeriesPartition).Open(0xc432dd8370, 0xc4504ee680, 0x1)
2018-05-28T15:16:20.593935000Z 	/go/src/github.com/influxdata/influxdb/tsdb/series_partition.go:92 +0x11c
2018-05-28T15:16:20.594142000Z github.com/influxdata/influxdb/tsdb.(*SeriesFile).Open(0xc432ea8cd0, 0x0, 0x0)
2018-05-28T15:16:20.594361000Z 	/go/src/github.com/influxdata/influxdb/tsdb/series_file.go:67 +0x370
2018-05-28T15:16:20.594561000Z github.com/influxdata/influxdb/tsdb.(*Store).openSeriesFile(0xc42040c000, 0xc4203c06a7, 0xd, 0xc454228120, 0x24, 0xc4201e0600)
2018-05-28T15:16:20.594787000Z 	/go/src/github.com/influxdata/influxdb/tsdb/store.go:382 +0x123
2018-05-28T15:16:20.594987000Z github.com/influxdata/influxdb/tsdb.(*Store).loadShards(0xc42040c000, 0x0, 0x0)
2018-05-28T15:16:20.595186000Z 	/go/src/github.com/influxdata/influxdb/tsdb/store.go:228 +0x619
2018-05-28T15:16:20.595391000Z github.com/influxdata/influxdb/tsdb.(*Store).Open(0xc42040c000, 0x0, 0x0)
2018-05-28T15:16:20.595608000Z 	/go/src/github.com/influxdata/influxdb/tsdb/store.go:160 +0x28b
2018-05-28T15:16:20.595818000Z github.com/influxdata/influxdb/cmd/influxd/run.(*Server).Open(0xc42039a5a0, 0xc4203864c0, 0xc42039a5a0)
2018-05-28T15:16:20.596028000Z 	/go/src/github.com/influxdata/influxdb/cmd/influxd/run/server.go:418 +0xa56
2018-05-28T15:16:20.596220000Z github.com/influxdata/influxdb/cmd/influxd/run.(*Command).Run(0xc4202048f0, 0xc4200101a0, 0x0, 0x0, 0xc4200b82a0, 0xc4200b82a0)
2018-05-28T15:16:20.596423000Z 	/go/src/github.com/influxdata/influxdb/cmd/influxd/run/command.go:140 +0xd9a
2018-05-28T15:16:20.596642000Z main.(*Main).Run(0xc420095f40, 0xc4200101a0, 0x0, 0x0, 0x5b0c1d3f, 0x17da5146)
2018-05-28T15:16:20.596850000Z 	/go/src/github.com/influxdata/influxdb/cmd/influxd/main.go:81 +0x1d5
2018-05-28T15:16:20.597065000Z main.main()
2018-05-28T15:16:20.597264000Z 	/go/src/github.com/influxdata/influxdb/cmd/influxd/main.go:45 +0x16a
```

I have 5 different influx instances and each is failing with above exception.   

My initial understanding was database telegraf_1080d might have been corrupted. Hence i moved it out so that influx avoids loading telegraf_1080d. However it then started to fail while load TSM files of 
"k8s" . database.

```
2018-05-28T16:39:04.709773000Z ts=2018-05-28T16:39:04.709328Z lvl=info msg="Opened file" log_id=08Lui_7G000 engine=tsm1 service=filestore path=/var/lib/influxdb/data/k8s/default/396/000000394-000000003.tsm id=0 duration=647.044ms
2018-05-28T16:39:04.887889000Z ts=2018-05-28T16:39:04.887379Z lvl=info msg="Opened file" log_id=08Lui_7G000 engine=tsm1 service=filestore path=/var/lib/influxdb/data/k8s/default/423/000000359-000000002.tsm id=0 duration=824.466ms
2018-05-28T16:39:05.131921000Z ts=2018-05-28T16:39:05.131287Z lvl=info msg="Open store (end)" log_id=08Lui_7G000 service=store trace_id=08Lui_Wl000 op_name=tsdb_open op_event=end op_elapsed=5159.434ms
2018-05-28T16:39:05.134954000Z panic: unreachable
2018-05-28T16:39:05.135410000Z goroutine 1 [running]:
2018-05-28T16:39:05.135614000Z github.com/influxdata/influxdb/tsdb.(*SeriesIndex).execEntry(0xc420362280, 0x290225f, 0x61695f6e616d6573, 0x4016fe085, 0x0, 0x0, 0x0)
```

Also, if this is an issue of for performance, locking, etc the following commands are useful to create debug information for the team.

```
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"

curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
```

**Please note** It will take at least 30 seconds for the first cURL command above to return a response.
This is because it will run a CPU profile as part of its information gathering, which takes 30 seconds to collect.
Ideally you should run these commands when you're experiencing problems, so we can capture the state of the system at that time.

If you're concerned about running a CPU profile (which only has a small, temporary impact on performance), then you can set `?cpu=false` or omit `?cpu=true` altogether.

Please run those if possible and link them from a [gist](http://gist.github.com) or simply attach them as a comment to the issue.

*Please note, the quickest way to fix a bug is to open a Pull Request.*

### Feature Request

Opening a feature request kicks off a discussion.
Requests may be closed if we're not actively planning to work on them.

__Proposal:__ [Description of the feature]

__Current behavior:__ [What currently happens]

__Desired behavior:__ [What you would like to happen]

__Use case:__ [Why is this important (helps with prioritizing requests)]

**Comment by luchano** [comment]
We are having the same issue here, we had influx running in production for a couple of months and since this weekend influx panic with exactly the same error reported here. Still haven't managed to find a solution without wiping all data.

```
ts=2018-05-28T13:37:19.033142Z lvl=info msg="InfluxDB starting" log_id=08LkKEjG000 version=1.5.2 branch=1.5 commit=02d7d4f043b34ecb4e9b2dbec298c6f9450c2a32
ts=2018-05-28T13:37:19.033168Z lvl=info msg="Go runtime" log_id=08LkKEjG000 version=go1.9.2 maxprocs=2
ts=2018-05-28T13:37:19.140695Z lvl=info msg="Using data dir" log_id=08LkKEjG000 service=store path=/var/lib/influxdb/data
ts=2018-05-28T13:37:19.142104Z lvl=info msg="Open store (start)" log_id=08LkKEjG000 service=store trace_id=08LkKF9W000 op_name=tsdb_open op_event=start
ts=2018-05-28T13:37:19.160826Z lvl=info msg="Open store (end)" log_id=08LkKEjG000 service=store trace_id=08LkKF9W000 op_name=tsdb_open op_event=end op_elapsed=18.701ms
panic: unreachable
goroutine 1 [running]:
github.com/influxdata/influxdb/tsdb.(*SeriesIndex).execEntry(0xc42017f7c0, 0x3e7839, 0xf726574656e74, 0x18a9e, 0x0, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/tsdb/series_index.go:179 +0x167
github.com/influxdata/influxdb/tsdb.(*SeriesIndex).Recover.func1(0x7f2f636dfa39, 0xf726574656e74, 0x18a9e, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/tsdb/series_index.go:127 +0x91
github.com/influxdata/influxdb/tsdb.(*SeriesSegment).ForEachEntry(0xc4202745a0, 0xc420216860, 0xc420242e70, 0x0)
	/go/src/github.com/influxdata/influxdb/tsdb/series_segment.go:242 +0xea
github.com/influxdata/influxdb/tsdb.(*SeriesIndex).Recover(0xc42017f7c0, 0xc42016db30, 0x1, 0x1, 0xc420179a00, 0x0)
	/go/src/github.com/influxdata/influxdb/tsdb/series_index.go:123 +0x169
github.com/influxdata/influxdb/tsdb.(*SeriesPartition).Open.func1(0xc42018eb00, 0x2b, 0x1ff)
	/go/src/github.com/influxdata/influxdb/tsdb/series_partition.go:87 +0x132
github.com/influxdata/influxdb/tsdb.(*SeriesPartition).Open(0xc42018eb00, 0xc4202ac040, 0x1)
	/go/src/github.com/influxdata/influxdb/tsdb/series_partition.go:92 +0x11c
github.com/influxdata/influxdb/tsdb.(*SeriesFile).Open(0xc420274500, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/tsdb/series_file.go:67 +0x370
github.com/influxdata/influxdb/tsdb.(*Store).openSeriesFile(0xc4201d0180, 0xc42026df57, 0x9, 0xc42026df60, 0x20, 0x0)
	/go/src/github.com/influxdata/influxdb/tsdb/store.go:382 +0x123
github.com/influxdata/influxdb/tsdb.(*Store).loadShards(0xc4201d0180, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/tsdb/store.go:228 +0x619
github.com/influxdata/influxdb/tsdb.(*Store).Open(0xc4201d0180, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/tsdb/store.go:160 +0x28b
github.com/influxdata/influxdb/cmd/influxd/run.(*Server).Open(0xc4201bd9e0, 0xc420172a00, 0xc4201bd9e0)
	/go/src/github.com/influxdata/influxdb/cmd/influxd/run/server.go:418 +0xa56
github.com/influxdata/influxdb/cmd/influxd/run.(*Command).Run(0xc42018e8f0, 0xc42000e1a0, 0x0, 0x0, 0xc42005c2a0, 0xc42005c2a0)
	/go/src/github.com/influxdata/influxdb/cmd/influxd/run/command.go:140 +0xd9a
main.(*Main).Run(0xc42003bf40, 0xc42000e1a0, 0x0, 0x0, 0x5b0c060f, 0x1e20dd8)
	/go/src/github.com/influxdata/influxdb/cmd/influxd/main.go:81 +0x1d5
main.main()
	/go/src/github.com/influxdata/influxdb/cmd/influxd/main.go:45 +0x16a
```

**Comment by deepujain** [comment]
I have 1.6 years of historical data.

**Comment by vills** [comment]
Same problem. Not only on influxdb startup, but also with execution of `influx_inspect buildtsi`.

```
panic: unreachable

goroutine 1 [running]:
github.com/influxdata/influxdb/tsdb.(*SeriesIndex).execEntry(0xc420090280, 0xb56869, 0x630004686f737400, 0x2004a9848, 0x0, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/tsdb/series_index.go:179 +0x167
github.com/influxdata/influxdb/tsdb.(*SeriesIndex).Recover.func1(0x7fbe2e8a9869, 0x630004686f737400, 0x2004a9848, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/tsdb/series_index.go:127 +0x91
github.com/influxdata/influxdb/tsdb.(*SeriesSegment).ForEachEntry(0xc420080500, 0xc420055770, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/tsdb/series_segment.go:242 +0xea
github.com/influxdata/influxdb/tsdb.(*SeriesIndex).Recover(0xc420090280, 0xc420426020, 0x3, 0x4, 0xc4200885b0, 0x0)
	/go/src/github.com/influxdata/influxdb/tsdb/series_index.go:123 +0x169
github.com/influxdata/influxdb/tsdb.(*SeriesPartition).Open.func1(0xc4200aadc0, 0x2d, 0x1ff)
	/go/src/github.com/influxdata/influxdb/tsdb/series_partition.go:87 +0x132
github.com/influxdata/influxdb/tsdb.(*SeriesPartition).Open(0xc4200aadc0, 0xc420422080, 0x1)
	/go/src/github.com/influxdata/influxdb/tsdb/series_partition.go:92 +0x11c
github.com/influxdata/influxdb/tsdb.(*SeriesFile).Open(0xc420080cd0, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/tsdb/series_file.go:67 +0x370
github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi.(*Command).processDatabase(0xc420116d20, 0xc4200183a7, 0xb, 0xc4200185a0, 0x22, 0xc4200185d0, 0x21, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi/buildtsi.go:107 +0x231
github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi.(*Command).run(0xc420116d20, 0x7ffd70bd6858, 0x16, 0x7ffd70bd6877, 0x15, 0x0, 0x7)
	/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi/buildtsi.go:94 +0x2e0
github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi.(*Command).Run(0xc420116d20, 0xc4200100e0, 0x4, 0x4, 0x0, 0x95dde0)
	/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/buildtsi/buildtsi.go:64 +0x3bc
main.(*Main).Run(0xc420055f38, 0xc4200100d0, 0x4, 0x4, 0xc42001cea0, 0x778518)
	/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/main.go:78 +0xe1a
main.main()
	/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/main.go:23 +0x16c
```

**Comment by vills** [comment]
Not sure i did the right thing, but delete of '_series' directory and regenerate it with `influx_inspect buildtsi` solved problem (influxdb restart should do same).

Did i destroy some data in database? :-)

**Comment by deepujain** [comment]
I downgraded to slower influx1.2 to solve the problem. Luckily that worked.

**Comment by deepujain** [comment]
@vills could you please share , how to run ```influx_inspect buildtsi```

**Comment by vills** [comment]
@deepujain it's in the docs https://docs.influxdata.com/influxdb/v1.5/tools/influx_inspect/#influx-inspect-buildtsi

**Comment by deepujain** [comment]
Same issue with 1.5.3
```
path=/var/lib/influxdb/data/_internal/monitor/729/000000007-000000001.tsm id=2 duration=2.991ms
2018-06-14T04:09:08.501266000Z ts=2018-06-14T04:09:08.500934Z lvl=info msg="Opened file" log_id=08g7ZvRW000 engine=tsm1 service=filestore path=/var/lib/influxdb/data/_internal/monitor/713/000000043-000000003.tsm id=0 duration=7.145ms
2018-06-14T04:09:08.501425000Z ts=2018-06-14T04:09:08.501190Z lvl=info msg="Reading file" log_id=08g7ZvRW000 engine=tsm1 service=cacheloader path=/var/lib/influxdb/wal/_internal/monitor/729/_00043.wal size=10491507
2018-06-14T04:09:09.022808000Z ts=2018-06-14T04:09:09.022341Z lvl=info msg="Open store (end)" log_id=08g7ZvRW000 service=store trace_id=08g7Zvq0000 op_name=tsdb_open op_event=end op_elapsed=969.806ms
2018-06-14T04:09:09.026148000Z panic: unreachable
2018-06-14T04:09:09.026581000Z goroutine 1 [running]:
2018-06-14T04:09:09.026746000Z github.com/influxdata/influxdb/tsdb.(*SeriesIndex).execEntry(0xc4201b4b40, 0xdb22a69, 0x6e673a66616c7365, 0x7024dd8a0, 0x0, 0x0, 0x0)
2018-06-14T04:09:09.026910000Z 	/go/src/github.com/influxdata/influxdb/tsdb/series_index.go:179 +0x167
2018-06-14T04:09:09.027087000Z github.com/influxdata/influxdb/tsdb.(*SeriesIndex).Recover.func1(0x7fa01ce06869, 0x6e673a66616c7365, 0x7024dd8a0, 0x0, 0x0, 0x0, 0x0, 0x0)
2018-06-14T04:09:09.027249000Z 	/go/src/github.com/influxdata/influxdb/tsdb/series_index.go:127 +0x91
2018-06-14T04:09:09.029387000Z github.com/influxdata/influxdb/tsdb.(*SeriesSegment).ForEachEntry(0xc42019d180, 0xc4203cc860, 0x0, 0x0)
2018-06-14T04:09:09.030982000Z 	/go/src/github.com/influxdata/influxdb/tsdb/series_segment.go:242 +0xea
2018-06-14T04:09:09.031641000Z github.com/influxdata/influxdb/tsdb.(*SeriesIndex).Recover(0xc4201b4b40, 0xc42039c940, 0x8, 0x8, 0xc4201aeea0, 0x0)
2018-06-14T04:09:09.031808000Z 	/go/src/github.com/influxdata/influxdb/tsdb/series_index.go:123 +0x169
2018-06-14T04:09:09.031973000Z github.com/influxdata/influxdb/tsdb.(*SeriesPartition).Open.func1(0xc422f50000, 0x25, 0x1ff)
2018-06-14T04:09:09.032144000Z 	/go/src/github.com/influxdata/influxdb/tsdb/series_partition.go:87 +0x132
2018-06-14T04:09:09.032302000Z github.com/influxdata/influxdb/tsdb.(*SeriesPartition).Open(0xc422f50000, 0xc42039c900, 0x1)
2018-06-14T04:09:09.032459000Z 	/go/src/github.com/influxdata/influxdb/tsdb/series_partition.go:92 +0x11c
2018-06-14T04:09:09.032617000Z github.com/influxdata/influxdb/tsdb.(*SeriesFile).Open(0xc42019cc80, 0x0, 0x0)
2018-06-14T04:09:09.032777000Z 	/go/src/github.com/influxdata/influxdb/tsdb/series_file.go:67 +0x370
2018-06-14T04:09:09.032936000Z github.com/influxdata/influxdb/tsdb.(*Store).openSeriesFile(0xc42018e780, 0xc420406d77, 0x3, 0xc420406920, 0x1a, 0xc4201ac660)
2018-06-14T04:09:09.033149000Z 	/go/src/github.com/influxdata/influxdb/tsdb/store.go:384 +0x123
2018-06-14T04:09:09.033313000Z github.com/influxdata/influxdb/tsdb.(*Store).loadShards(0xc42018e780, 0x0, 0x0)
2018-06-14T04:09:09.033474000Z 	/go/src/github.com/influxdata/influxdb/tsdb/store.go:230 +0x619
2018-06-14T04:09:09.033635000Z github.com/influxdata/influxdb/tsdb.(*Store).Open(0xc42018e780, 0x0, 0x0)
2018-06-14T04:09:09.033792000Z 	/go/src/github.com/influxdata/influxdb/tsdb/store.go:162 +0x28b
2018-06-14T04:09:09.033950000Z github.com/influxdata/influxdb/cmd/influxd/run.(*Server).Open(0xc42020e6c0, 0xc42039c780, 0xc42020e6c0)
2018-06-14T04:09:09.034119000Z 	/go/src/github.com/influxdata/influxdb/cmd/influxd/run/server.go:418 +0xa56
2018-06-14T04:09:09.034274000Z github.com/influxdata/influxdb/cmd/influxd/run.(*Command).Run(0xc4201eda20, 0xc4200101a0, 0x0, 0x0, 0xc4200b22a0, 0xc4200b22a0)
2018-06-14T04:09:09.034448000Z 	/go/src/github.com/influxdata/influxdb/cmd/influxd/run/command.go:149 +0xda9
2018-06-14T04:09:09.034598000Z main.(*Main).Run(0xc420097f40, 0xc4200101a0, 0x0, 0x0, 0x5b21ea63, 0x389447d3)
2018-06-14T04:09:09.034800000Z 	/go/src/github.com/influxdata/influxdb/cmd/influxd/main.go:81 +0x1d5
2018-06-14T04:09:09.034978000Z main.main()
2018-06-14T04:09:09.035147000Z 	/go/src/github.com/influxdata/influxdb/cmd/influxd/main.go:45 +0x16a
```

**Comment by benbjohnson** [comment]
This PR should fix the issue with recovery: https://github.com/influxdata/influxdb/pull/10002

**Comment by deepujain** [comment]
@benbjohnson Thanks for the fix. What release will this fix go in ?

**Comment by benbjohnson** [comment]
@deepujain I believe this will be going into `1.6.0`.

**Comment by deepujain** [comment]
Installed 1.6.0. Failure on startup

```
2018-07-15T04:34:39.416896000Z ts=2018-07-15T04:34:39.416562Z lvl=info msg="Reading file" log_id=09J3LvLG000 engine=tsm1 service=cacheloader path=/var/lib/influxdb/wal/_internal/monitor/799/_00043.wal size=10554431
2018-07-15T04:34:39.936044000Z ts=2018-07-15T04:34:39.935308Z lvl=info msg="Open store (end)" log_id=09J3LvLG000 service=store trace_id=09J3LvmW000 op_name=tsdb_open op_event=end op_elapsed=1017.256ms
2018-07-15T04:34:39.939159000Z panic: unreachable
2018-07-15T04:34:39.939650000Z goroutine 1 [running]:
2018-07-15T04:34:39.939866000Z github.com/influxdata/influxdb/tsdb.(*SeriesIndex).execEntry(0xc424e740a0, 0xdb22a69, 0x6e673a66616c7365, 0x7024dd8a0, 0x0, 0x0, 0x0)
2018-07-15T04:34:39.940079000Z 	/go/src/github.com/influxdata/influxdb/tsdb/series_index.go:179 +0x167
2018-07-15T04:34:39.940262000Z github.com/influxdata/influxdb/tsdb.(*SeriesIndex).Recover.func1(0x7f436020f869, 0x6e673a66616c7365, 0x7024dd8a0, 0x0, 0x0, 0x0, 0x0, 0x0)
2018-07-15T04:34:39.940443000Z 	/go/src/github.com/influxdata/influxdb/tsdb/series_index.go:127 +0x91
2018-07-15T04:34:39.940631000Z github.com/influxdata/influxdb/tsdb.(*SeriesSegment).ForEachEntry(0xc4201b8f00, 0xc4203ce0a0, 0x0, 0x0)
2018-07-15T04:34:39.940797000Z 	/go/src/github.com/influxdata/influxdb/tsdb/series_segment.go:245 +0xea
2018-07-15T04:34:39.940971000Z github.com/influxdata/influxdb/tsdb.(*SeriesIndex).Recover(0xc424e740a0, 0xc4200a0380, 0x8, 0x8, 0xc4201a7040, 0x0)
2018-07-15T04:34:39.941154000Z 	/go/src/github.com/influxdata/influxdb/tsdb/series_index.go:123 +0x169
2018-07-15T04:34:39.941318000Z github.com/influxdata/influxdb/tsdb.(*SeriesPartition).Open.func1(0xc4201bf340, 0x25, 0x1ff)
2018-07-15T04:34:39.941527000Z 	/go/src/github.com/influxdata/influxdb/tsdb/series_partition.go:87 +0x132
2018-07-15T04:34:39.941733000Z github.com/influxdata/influxdb/tsdb.(*SeriesPartition).Open(0xc4201bf340, 0xc4200a0340, 0x1)
2018-07-15T04:34:39.941923000Z 	/go/src/github.com/influxdata/influxdb/tsdb/series_partition.go:92 +0x11c
2018-07-15T04:34:39.942089000Z github.com/influxdata/influxdb/tsdb.(*SeriesFile).Open(0xc4201b8a00, 0x0, 0x0)
2018-07-15T04:34:39.942270000Z 	/go/src/github.com/influxdata/influxdb/tsdb/series_file.go:67 +0x370
2018-07-15T04:34:39.942441000Z github.com/influxdata/influxdb/tsdb.(*Store).openSeriesFile(0xc4201aa1e0, 0xc4203fd0f7, 0x3, 0xc4203fc900, 0x1a, 0xc4201a47e0)
2018-07-15T04:34:39.942648000Z 	/go/src/github.com/influxdata/influxdb/tsdb/store.go:455 +0x123
2018-07-15T04:34:39.942823000Z github.com/influxdata/influxdb/tsdb.(*Store).loadShards(0xc4201aa1e0, 0x0, 0x0)
2018-07-15T04:34:39.943005000Z 	/go/src/github.com/influxdata/influxdb/tsdb/store.go:267 +0x671
2018-07-15T04:34:39.943180000Z github.com/influxdata/influxdb/tsdb.(*Store).Open(0xc4201aa1e0, 0x0, 0x0)
2018-07-15T04:34:39.943406000Z 	/go/src/github.com/influxdata/influxdb/tsdb/store.go:188 +0x28b
2018-07-15T04:34:39.943587000Z github.com/influxdata/influxdb/cmd/influxd/run.(*Server).Open(0xc4203567e0, 0xc420352700, 0xc4203567e0)
2018-07-15T04:34:39.943786000Z 	/go/src/github.com/influxdata/influxdb/cmd/influxd/run/server.go:425 +0xa60
2018-07-15T04:34:39.943970000Z github.com/influxdata/influxdb/cmd/influxd/run.(*Command).Run(0xc42036fce0, 0xc4200101a0, 0x0, 0x0, 0xc42039a188, 0xc42039a180)
2018-07-15T04:34:39.944157000Z 	/go/src/github.com/influxdata/influxdb/cmd/influxd/run/command.go:149 +0xda9
2018-07-15T04:34:39.944322000Z main.(*Main).Run(0xc420095f40, 0xc4200101a0, 0x0, 0x0, 0x5b4acede, 0x2ff7c367)
2018-07-15T04:34:39.944485000Z 	/go/src/github.com/influxdata/influxdb/cmd/influxd/main.go:81 +0x1d5
2018-07-15T04:34:39.944672000Z main.main()
2018-07-15T04:34:39.944842000Z 	/go/src/github.com/influxdata/influxdb/cmd/influxd/main.go:45 +0x16a
```

**Comment by deepujain** [comment]
@benbjohnson

**Comment by benbjohnson** [comment]
@deepujain I apologize. It looks like this is going into the `v1.6.1` release.

**Comment by pqvst** [comment]
I'm running into the same issue. Any ETA for the 1.6.1 release?

I ran `influx_inspect verify` and it shows `Broken Blocks: 0`

I tried running `influx_inspect buildtsi` but that also panics.

Is there any way to workaround the issue?

**Comment by timhallinflux** [comment]
InfluxDB 1.6.1 is now available.

**Comment by codylewandowski** [comment]
Adding a note incase anyone else runs across this issue. We're running 1.6.1 and after running an incorrect `influx_inspect` command it appears the inspect tool created a set of incorrect directories within one of the existing directories. This caused influx to not start as described above. 

For example, in `_series` we have `00  01  02  03  04  05  06  07`.  Within `07` we observed `00  0000  0001  0002  0003  0004  01  02  03  04  05  06  07  index` with the two digit items being directories. All other directories within `_series` looked correct. We removed the embedded `00  01  02  03  04  05  06  07` directories and then ran `chown -R influxdb:influxdb` and were able to start influx again.
