### ISSUE TITLE
client got "no space left on device"  for 1.4.2

### ISSUE THREAD

**Issue by superheizai** [influxdata/influxdb#9923]
influxDB: 1.4.2 
CentOS7

when send info to influxDB, I got messages like below. It gave me tips aoubt no space, but I checked on server, here are lots of spaces over there. Any ideas?

write influx error org.influxdb.InfluxDBException: engine: error writing WAL entry: write /var/lib/influxdb/wal/kafka/autogen/335/_00107.wal: no space left on device 
at org.influxdb.InfluxDBException.buildExceptionFromErrorMessage(InfluxDBException.java:154) 
at org.influxdb.InfluxDBException.buildExceptionForErrorState(InfluxDBException.java:166) 
at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:584) 
at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:355) 

### Directions
_GitHub Issues are reserved for actionable bug reports and feature requests._
_General questions should be sent to the [InfluxDB Community Site](https://community.influxdata.com)._

_Before opening an issue, search for similar bug reports or feature requests on GitHub Issues._
_If no similar issue can be found, fill out either the "Bug Report" or the "Feature Request" section below.
_Erase the other section and everything on and above this line._

### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]

__Steps to reproduce:__

1. [First Step]
2. [Second Step]
3. [and so on...]

__Expected behavior:__ [What you expected to happen]

__Actual behavior:__ [What actually happened]

__Additional info:__ [Include gist of relevant config, logs, etc.]

Also, if this is an issue of for performance, locking, etc the following commands are useful to create debug information for the team.

```
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"

curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
```

**Please note** It will take at least 30 seconds for the first cURL command above to return a response.
This is because it will run a CPU profile as part of its information gathering, which takes 30 seconds to collect.
Ideally you should run these commands when you're experiencing problems, so we can capture the state of the system at that time.

If you're concerned about running a CPU profile (which only has a small, temporary impact on performance), then you can set `?cpu=false` or omit `?cpu=true` altogether.

Please run those if possible and link them from a [gist](http://gist.github.com) or simply attach them as a comment to the issue.

*Please note, the quickest way to fix a bug is to open a Pull Request.*

### Feature Request

Opening a feature request kicks off a discussion.
Requests may be closed if we're not actively planning to work on them.

__Proposal:__ [Description of the feature]

__Current behavior:__ [What currently happens]

__Desired behavior:__ [What you would like to happen]

__Use case:__ [Why is this important (helps with prioritizing requests)]

**Comment by JamesGalt** [comment]
same issue on debian 8
`400: {"error":"partial write: write /data/influxdb/data/_series/00/0000: no space left on device dropped=1"}`

**Comment by utjc02** [comment]
got the same on debian 8.
Any workaround here?

**Comment by godidog** [comment]
Same here, on PC running Debian.
Disk was full, freed space, still getting errors like "error writing WAL entry: write /var/lib/influxdb/wal/kafka/autogen/335/_00107.wal: no space left on device"

A response would be nice.

**Comment by 541211190** [comment]
I got the same problem:
`Exception in thread "Thread-11" org.influxdb.InfluxDBException: engine: error writing WAL entry: write /home/influxdb/wal/s2/second/409/_00001.wal: file already closed
	at org.influxdb.InfluxDBException.buildExceptionFromErrorMessage(InfluxDBException.java:154)
	at org.influxdb.InfluxDBException.buildExceptionForErrorState(InfluxDBException.java:166)
	at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:609)
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:369)
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:382)
	at com.cnegroup.power.influxdb.InfluxDBConnection.batchInsert(InfluxDBConnection.java:201)
	at com.cnegroup.power.receiver.InfluxReceiverRunnable.saveRecordValue(InfluxReceiverRunnable.java:201)
	at com.cnegroup.power.receiver.InfluxReceiverRunnable.run(InfluxReceiverRunnable.java:79)
	at java.lang.Thread.run(Thread.java:748)`
How to solve this problem ？
I find my Hard disk storage space is used 100%  which installed influxDB, So expand my hard disk storage space, It began to work.

**Comment by yifeikong** [comment]
same here, I got plenty of spaces on my disk, yet influxdb insisted that no space left on device

**Comment by yifeikong** [comment]
restart influxdb seems to solve the problem

**Comment by JamesGalt** [comment]
The problem is that it empties the db cache so all points in cache are lost.

**Comment by licunzhi** [comment]
> same issue on debian 8
> `400: {"error":"partial write: write /data/influxdb/data/_series/00/0000: no space left on device dropped=1"}`
I also have the same question
post result：{"error":"partial write: write /data/device_statistics/_series/00/0000: no space left on device dropped=495"}

Cloud you please tell me how to solve the question

**Comment by licunzhi** [comment]
@JamesGalt  Have you solved that question?
I want to know how to do to slove that

**Comment by kali-brandwatch** [comment]
I'm experiencing the same on influxdb 1.6.1 over debian 8
Some clients are sending metrics with no issues while other client is getting the disk full response, while others are able to send these no problem.
I can see no relevant log on the influxdb side.

**Comment by bmg-iis** [comment]
For me as well. Debian 9.9 with influxdb 1.7.6.

Do you need more information?

**Comment by foobar** [comment]
I'm seeing this issue with v1.7.7.  The problem is that once a disk error is encountered, the buffer writer of WAL cannot recover, even when the disk goes back to work.
The silent failure is a problem and it's better to escalate if we cannot handle it.

**Comment by hlovdal** [comment]
I saw this behaviour on Centos, influxdb-1.7.9-1.x86_64: Disk goes full -> wal write error. Clean up some disk space but influxdb does not recover. And not only does it not recover which is a bit annoying, but worse it constantly complains about the failure to syslog thereby rapidly filling up the disk again...

**Comment by axeluhl** [comment]
Same here on Debian GNU/Linux 9.13 (stretch) with InfluxDB 1.8.0. I just lost a week worth of data because I hadn't noticed there was a short period where the partition to which InfluxDB stores its data had run out of space. The partition recovered instantly as plenty of temporary space was freed, however InfluxDB kept complaining about no space and did not store any data persistently, yet responded to reading queries properly and did not return errors to the writing clients either.

I think this sort of behavior is fundamentally broken. A database should have persistence as primary goal. If data cannot be made persistent, writers should see exceptions by default. Also, e-mail alerts may have come in handy because I'm not permanently monitoring my syslog.

**Comment by n0valis** [comment]
I am having this problem, still.
Influxdb 1.8.5 on Raspbian 10 buster

**Comment by iwasjoker** [comment]
I also having this problem,still ,this error still exists :(

**Comment by ErvalhouS** [comment]
I've seen that happen with data being stored on a docker volume that ran out of space. After resizing the disk error hasn't gone away until the instance was restarted. InfluxDB Version 2.0.6 ('7c3ead)

**Comment by camilesing** [comment]
This error still exists
Influxdb-1.8.9-1 on CentOS 7.5

**Comment by woloss** [comment]
Same happens on InfluxDB 2.0.8 in docker. If it reaches "no space" state, it won't recover till manual restart.

**Comment by geogeim** [comment]
same here, and the ram usage jumped from 8% to 30%

**Comment by DamienMiras** [comment]
same error here 
`//: engine: error writing WAL entry: write /var/lib/influxdb2/engine/wal/0d284939d1e0cea0/autogen/602/_00219.wal: no space left on device'. Retry in: 125s.`
influx installed in docker with external volume. The file system has once be full and then room have been made.

**Comment by giter** [comment]
same on influxdb:2.2

**Comment by Germaier** [comment]
Same here on influxDB v1.8.10 (git:1.8 688e697c51fd)
Sep  8 17:14:28 raspberrypi influxd-systemd-start.sh[434]: ts=2022-09-08T15:14:28.167771Z lvl=info msg="Error writing snapshot" log_id=0cmfnfT0000 engine=tsm1 error="error opening new segment file for wal (1): write /var/lib/influxdb/wal/_internal/monitor/3/_00002.wal: no space left on device"

Are there any possibilities to solve this issue? Appearently not even with the most recent version V2.2

**Comment by rever67697** [comment]
The reason for this situation may be that the disk has been running low on space before, restart the service

**Comment by Sniper91** [comment]
// bufio.Writer
// Flush writes any buffered data to the underlying io.Writer.
func (b *Writer) Flush() error {
	if b.err != nil {
		return b.err
	}
	...
}
bufio.Writer will always return last error. If disk had been full and then been free, Flush method always returns disk full error.

**Comment by MarcoPignati** [comment]
Same here, only restart of service seems to fix it

**Comment by elofu17** [comment]
For some reason, this issue turned into a "mee too" thread for people whose partition *has* been full and influx don't recover.
See issue #23126 for that particular case.

This issue is that influxdb suddently start to flod the log with "Error writing snapshot" and "no space left on device" even though there's plenty of space.
My Debian 11 server (with influxdb v1.8.10-1) has 75 GB disk and only 24 GB is used. The partition has *not* been full.

**Comment by pkkrusty** [comment]
> For some reason, this issue turned into a "me too" thread for people whose partition **has** been full and influx don't recover. See issue #23126 for this particular use-case.
> 
> This issue is that influxdb suddently start to flod the log with "Error writing snapshot" and "no space left on device" even though there's plenty of space. My Debian 11 server (with influxdb v1.8.10-1) has 75 GB disk and only 24 GB is used. The partition has **not** been full and only 1% of all inodes are used.

This is what I am experiencing on Debian 12 VM, Influxdb 1.8.10. Partition was never full (that I can tell) but this problem crops up every 12-24 hours. A service restart fixes the problem temporarily.
